### ISSUE TITLE
why not support NSDictionary as NSUserDefault

### ISSUE THREAD

**Issue by yuman07** [Tencent/MMKV#10]
### The language of MMKV

Objective-C

### The version of MMKV

v1.0.10

### The platform of MMKV

iOS

### The installation of MMKV

Cocoapods

### What's the issue?

For me, I often use a NSUserDefault to do some simple data persistence. And the NSDictionary is a very important one. Why is there no support for it?

**Comment by lingol** [comment]
Mainly because NSDictionary's value type is uncertain, it's hard to encode/decode NSDictionary properly in protobuf, if not possible.

However, you can turn a NSDictionary into a NSData by NSArchive, and store that NSData in MMKV.

**Comment by MichaelJokAr** [comment]
+1

**Comment by yuman07** [comment]
NSUserDefault can store NSDictionary directly, and MMKV needs to do a conversion through NSArchive. If you consider the consumption of conversion, is the performance advantage of MMKV still greater than NSUserDefault?

**Comment by lingol** [comment]
> NSUserDefault can read/write NSDictionary directly, and MMKV needs to do a conversion through NSArchive. If you consider the consumption of conversion, is the performance advantage of MMKV still greater than NSUserDefault?

Well, NSUserDefault's NSDictionary support doesn't come in free. Which algorithm do you think it used to store NSDictionary? NSArchive? I haven't test it yet, but that's my best guess.

Given that guess, I have confidence MMKV will beat NSUserDefault in such case.

**Comment by yuman07** [comment]
thx~

**Comment by wg689** [comment]
you tell me I should better convert dictionary or Nsarray  to NSData ,not the jsonStr , the reason is ( value type is uncertain, it's hard to encode/decode NSDictionary properly)? when I conert to jsonStr , all is NSString ,
or have other reason ?

**Comment by lingol** [comment]
> you tell me I should better convert dictionary or Nsarray to NSData ,not the jsonStr , the reason is ( value type is uncertain, it's hard to encode/decode NSDictionary properly)? when I conert to jsonStr , all is NSString ,
> or have other reason ?

Use NSData for efficiency, or JSON for convenience. It's your choice.

**Comment by Damonvvong** [comment]
其实可以提供一个直接存 NSDictionary 的 api。然后内部进行一步转换~你觉得呢？

@lingol

**Comment by lingol** [comment]
> 其实可以提供一个直接存 NSDictionary 的 api。然后内部进行一步转换~你觉得呢？
> 
> @lingol

Maybe.

**Comment by lingol** [comment]
Supported with #62
