### ISSUE TITLE
MMKV备份失败

### ISSUE THREAD

**Issue by KeFuYou** [Tencent/MMKV#1000]
我在使用的过程中，发现MMKV的备份逻辑是先保存到 应用包路径下的cache，再保存到指定文件夹。

但是当MMKV的使用场景是：MMKV的文件在外部存储，备份也要备份到外部存储时，就会出现：

MMKV:fail on renameat2() [/data/user/0/com.xxx.xxx/cache/MMKV.jQ14G5] to [/storage/emulated/0/mmkv/backup/AppConfig], 18(Cross-device link)

MMKV:fail to rename [/data/user/0/com.xxx.xxx/cache/MMKV.jQ14G5] to [/storage/emulated/0/mmkv/backup/AppConfig], 18(Cross-device link)

**Comment by lingol** [comment]
Cross-device link

**Comment by lingol** [comment]
The error is clear, you can not backup to a different device.
