### ISSUE TITLE
fail to open and file not valid

### ISSUE THREAD

**Issue by xuzang** [Tencent/MMKV#1004]
哈喽：
      我是一名iOS开发者，目前项目中使用MMKV 遇到以下一些错误。研发debug下没有复现，是通过查看线上日志发现的。  想问下，这些问题如何处理

问题一：
	1. file [/var/mobile/Containers/Data/Application/E882DEAC-3DC3-49AE-B535-404D843D4EE2/Documents/mmkv/User/672505921/user_profile] not valid
	2.  fail to open [/var/mobile/Containers/Data/Application/E882DEAC-3DC3-49AE-B535-404D843D4EE2/Documents/mmkv/User/672505921/user_profile], 2(No such file or directory)
	3. fail to open [/var/mobile/Containers/Data/Application/E882DEAC-3DC3-49AE-B535-404D843D4EE2/Documents/mmkv/User/672505921/user_profile.crc], 2(No such file or directory)

/var/mobile/Containers/Data/Application/E882DEAC-3DC3-49AE-B535-404D843D4EE2/Documents/mmkv/User/672505921/user_profile 是kv 的路径
具体日志来源：
	- (void)mmkvLogWithLevel:(MMKVLogLevel)level file:(const char *)file line:(int)line func:(const char *)funcname message:(NSString *)message {
		    if (level == MMKVLogError) {
				// 把错误信息进行了上报
			}
	}
项目中MMKV的使用场景 举例：
- (void)putString:(NSString *)string {
	MMKV *kv = [MMKV mmkvWithID:”XXXID” rootPath:”XXXPath”];
	[kv setString: string forKey: “XXX”];
}

putString 这个方法会被频繁调用。可能有多个业务同时调用。
每次都会创建一个kv对象（作用域就在这个方法内，没有额外持有kv对象）进行存储。出了方法作用域后，我们没有手动调用Close方法

问题二：
- (BOOL)setString:(NSString *)value forKey:(NSString *)key {
    BOOL result = [self.cache setString:value forKey:key];
    if (result == NO) {
        [self reportErrorWithKey:key value:value];
    }
    return result;
}

self.cache 就是mmkv的对象
种种的setvalue，会有set 失败的情况，如上所示 result 为false
这种情况合理吗？

问题三：
以上2种错误。根据远端日志查看，都是短时间内。高频上报
而且有自修复性。比如用户上午使用查看有error 信息，下午使用却没有
以上错误。需要我们如何处理。对我们的业务逻辑有影响吗，很多业务依赖存储的key-value
Setvalue 失败。是存文件失败，还是 存内存失败。如果存文件失败。后续会有重存的机制吗，存文件失败，内存中的那份数据可靠吗

问题有点多。辛苦大佬看看。刚刚接入mmkv，都是线上收集到的问题 

感谢！！！

**Comment by lingol** [comment]
Looks like someone else has deleted the files. You might check on that.

**Comment by xuzang** [comment]
你好。
我们代码里 我有排查过。没有对Documents 目录下 做清除操作。还有其他方向可以让我排查下吗。线上这个错误蛮多的。

**Comment by xuzang** [comment]
sdk版本是 1.2.14

**Comment by lingol** [comment]
It's the only reasonable explanation. You should check harder.

**Comment by xuzang** [comment]
你好
这个删除操作。除了代码删除，还有其他触发的可能吗，比如系统？或者其他

**Comment by xuzang** [comment]
还有一个疑问。如果是这个文件被删除了。是不是就说明 我所有的存储 都不在了

**Comment by lingol** [comment]
I don't know. You are on your own.

**Comment by xuzang** [comment]
在App使用过程中，如果是文件被删除了。是不是内存的存储 也不在了？？

**Comment by xuzang** [comment]
这些存储的文件 mmkv 都不会 有清理操作把？ 比如调用 clearall 等类似的方法

**Comment by xuzang** [comment]
> 在App使用过程中，如果是文件被删除了。是不是内存的存储 也不在了？？

这个辛苦回复下吧

**Comment by lingol** [comment]
Don't keep asking the same or almost the same questions. Keep looking at why your files being deleted.
