### ISSUE TITLE
 在使用getString时出现了ANR

### ISSUE THREAD

**Issue by ljackChen001** [Tencent/MMKV#1007]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> Kotlin

### The version of MMKV

> MMKV-1.2.12

### The platform of MMKV

> Android

### What's the log of MMKV when that happened?
> 在使用getString时出现了ANR
native: #00 pc 0000000000075f30 /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32) native: 
#01 pc 000000000007a7fc /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+148) native: 
#02 pc 00000000000dfe94 /apex/com.android.runtime/lib64/bionic/libc.so (NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*)+672) native: 
#03 pc 00000000000343bc /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/lib/arm64/libmmkv.so (???) native: 
#04 pc 000000000001ec58 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/lib/arm64/libmmkv.so (???) native: 
#05 pc 0000000000019054 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/lib/arm64/libmmkv.so (???) native: 
#06 pc 00000000002d4044 /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) native: 
#07 pc 000000000020a700 /apex/com.android.art/lib64/libart.so (nterp_helper+5648) native: 
#08 pc 000000000016d184 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/base.apk (offset 20ea000) (com.tencent.mmkv.MMKV.getString+4) native: 
#09 pc 000000000020ae64 /apex/com.android.art/lib64/libart.so (nterp_helper+7540) native: 
#10 pc 00000000002614f8 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/base.apk (offset 1bbf000) (xx.xx.xx.SharedPreferencesProxy.u+32) native: 
#11 pc 000000000020a044 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) native: 
#12 pc 0000000000169478 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/base.apk (offset 1077000) (xx.xx.xx.helper.t.i0+68) native: 
#13 pc 0000000000209124 /apex/com.android.art/lib64/libart.so (nterp_helper+52) native: 
#14 pc 000000000032befe /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/base.apk (offset 72c000) (xx.xx.xx.state.d0.i+42) native: 
#15 pc 000000000020a044 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) native: 
#16 pc 0000000000329840 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/base.apk (offset 72c000) (xx.xx.xx.state.g.t+12) native: 
#17 pc 000000000020a044 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) native: 
#18 pc 00000000004f4e00 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/base.apk (offset 72c000) (g1.d.i+8) native: 
#19 pc 000000000020a044 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) native: 
#20 pc 0000000000313cf8 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/base.apk (offset 72c000) (xx.xx.xx.y+232) native: 
#21 pc 000000000020a044 /apex/com.android.art/lib64/libart.so (nterp_helper+3924) native: 
#22 pc 0000000000418ec8 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/base.apk (offset 72c000) (xx.xx.xxr.V+20) native:
#23 pc 0000000000209124 /apex/com.android.art/lib64/libart.so (nterp_helper+52) native: 
#24 pc 0000000000418c50 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/base.apk (offset 72c000) (xx.xx.xx.J) native: 
#25 pc 0000000000209124 /apex/com.android.art/lib64/libart.so (nterp_helper+52)

**Comment by ljackChen001** [comment]
at com.tencent.mmkv.MMKV.decodeString(MMKV.java)

at com.tencent.mmkv.MMKV.getString(MMKV.java:990)

**Comment by lingol** [comment]
Please **symbolize** your native call stacks. ANR or crashes without symbolized call stacks will be ignored.

**Comment by ljackChen001** [comment]
有点不太理解

> Please **symbolize** your native call stacks. ANR or crashes without symbolized call stacks will be ignored.

**Comment by lingol** [comment]
> 有点不太理解
> 
> > Please **symbolize** your native call stacks. ANR or crashes without symbolized call stacks will be ignored.

请符号化您的native调用堆栈。 没有符号化调用堆栈的 ANR 或崩溃将被忽略。

**Comment by lingol** [comment]
>https://github.com/Tencent/MMKV/pull/3 pc 00000000000343bc /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/lib/arm64/libmmkv.so (???) native:
https://github.com/Tencent/MMKV/pull/4 pc 000000000001ec58 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/lib/arm64/libmmkv.so (???) native:
https://github.com/Tencent/MMKV/pull/5 pc 0000000000019054 /data/app/~~UXeuMsjxGjZq_kU3sRvKew==/xx.xx.xx-ATyVLYOVW6j9sXml9Hdxrw==/lib/arm64/libmmkv.so (???) native:

 这几层都没符号化。

**Comment by ljackChen001** [comment]
> 

目前只有这一个ANR，日志平台还未打捞到，后续有详细日志再贴上，谢谢回复

**Comment by lingol** [comment]
Closed due to lack of information.
