### ISSUE TITLE
decodeBytes 一个已经存入的空列表，destory 时闪退

### ISSUE THREAD

**Issue by Albert556** [Tencent/MMKV#1012]
### The language of MMKV

flutter 3.3.10
dart 2.18.6

### The version of MMKV

mmkv 1.2.16

### The platform of MMKV

Android

### The installation of MMKV

flutter pub.dev

### What's the issue?

使用 encodeBytes 方法保存了一个空列表，用相同的 key 调用 decodeBytes 方法读取内容，获取到一个不为空的 MMBuffer。
用 MMBuffer 的 asList 方法得到一个空列表，当我去 destory 时发生了异常，App 闪退

```dart
                final list = Uint8List(0);
                final buffer = MMBuffer.fromList(list);

                const key = 'bytes';
                mmkv!.encodeBytes(key, buffer);
                final result = mmkv!.decodeBytes(key);
                setState(() {
                  if (result == null) {
                    bytes = 'decodeBytes is null';
                    return;
                  }
                  // bytes = result.takeList().toString();
                  final list = result.asList();
                  if (list == null) {
                    bytes = 'asList is null';
                    return;
                  }
                  bytes = list.toString();
                  result.destroy();
                  return;
                });
```

### What's the log of MMKV when that happened?

I/MMKV    (24126): <flutter-bridge.cpp:50::mmkvInitialize_v1> current API level = 31, libc++_shared=0
I/MMKV    (24126): <MMKV.cpp:208::initializeMMKV> root dir: /data/user/0/com.example.flutter_learning_demo/app_flutter/mmkv
I/flutter (24126): MMKV for flutter with rootDir = /data/user/0/com.example.flutter_learning_demo/app_flutter/mmkv
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 0
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 1
Reloaded 1 of 1664 libraries in 694ms (compile: 28 ms, reload: 297 ms, reassemble: 279 ms).
Reloaded 1 of 1664 libraries in 808ms (compile: 26 ms, reload: 273 ms, reassemble: 269 ms).
Reloaded 1 of 1664 libraries in 1,076ms (compile: 28 ms, reload: 364 ms, reassemble: 522 ms).
Reloaded 1 of 1664 libraries in 812ms (compile: 24 ms, reload: 308 ms, reassemble: 360 ms).
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 0
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 1
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 0
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 1
Reloaded 1 of 1664 libraries in 641ms (compile: 26 ms, reload: 264 ms, reassemble: 239 ms).
Reloaded 1 of 1664 libraries in 577ms (compile: 24 ms, reload: 247 ms, reassemble: 242 ms).
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 0
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 1
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 0
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 1
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 0
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 1
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 0
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 1
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 0
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 1
Reloaded 1 of 1664 libraries in 760ms (compile: 30 ms, reload: 282 ms, reassemble: 327 ms).
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 0
I/ViewRootImpl@31fa77d[MainActivity](24126): ViewPostIme pointer 1
F/libc    (24126): Pointer tag for 0x737cf11b2a was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'.
F/libc    (24126): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24156 (1.ui), pid 24126 (r_learning_demo)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/beyond0qlteue/beyond0q:12/SP1A.210812.016/G970U1UES7IVJ2:user/release-keys'
Revision: '17'
ABI: 'arm64'
Processor: '4'
Timestamp: 2023-01-13 18:29:28.823875934+0800
Process uptime: 736s
Cmdline: com.example.flutter_learning_demo
pid: 24126, tid: 24156, name: 1.ui  >>> com.example.flutter_learning_demo <<<
uid: 10510
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'Pointer tag for 0x737cf11b2a was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'.'

**Comment by lingol** [comment]
That's strange. I will look into it later.

**Comment by lingol** [comment]
It's fixed in dev branch.

**Comment by Albert556** [comment]
我的 demo 通过了
