### ISSUE TITLE
Crash at first use

### ISSUE THREAD

**Issue by danleom89** [Tencent/MMKV#1013]
### The language of MMKV
Swift

### The version of MMKV
v1.2.15

### The platform of MMKV
iOS

### The installation of MMKV
Cocoapods

### What's the issue?

The Framework crashes when the App tries to call `MMKV.default()`

### What's the log of MMKV when that happened?
[MyApp_issue_crash_session_stacktrace.txt](https://github.com/Tencent/MMKV/files/10438011/MyApp_issue_crash_session_stacktrace.txt)

**Comment by lingol** [comment]
Your attachment fails to open. Would you post the most important call stacks here, in plain text?

**Comment by danleom** [comment]
Here’s to you:

Crashlytics - Stack trace
# Application: MyApp

Crashed: com.apple.main-thread
0  MMKVCore                       0x11c00 std::__1::__hash_iterator<std::__1::__hash_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>*> std::__1::__hash_table<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::find<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 802 (__hash_table:802)
1  MMKVCore                       0xc430 mmkv::MMKV::mmkvWithID(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mmkv::MMKVMode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 225 (MMKV.cpp:225)
2  MMKV                           0x75b0 -[MMKV initWithMMapID:cryptKey:rootPath:mode:] + 234 (libMMKV.mm:234)
3  MMKV                           0x7388 +[MMKV mmkvWithID:cryptKey:rootPath:mode:] + 209 (libMMKV.mm:209)
4  MyApp                         0xed83c8 MMKVPersistence.saveFavouriteMerchants(merchants:) + 4360094664

**Comment by OmarJalil** [comment]
This happened to me too, I locked temporarily to v1.2.13

**Comment by lingol** [comment]
I has confirm it. Starting from v1.2.15, you must call `+[MMKV initializeMMKV:]` manually **before** calling any MMKV methods.
