### ISSUE TITLE
Caused by java.lang.IllegalStateException: You should Call MMKV.initialize() first.

### ISSUE THREAD

**Issue by billdizl** [Tencent/MMKV#1014]
## Note:
1.2.15版本出现了crash ，Caused by java.lang.IllegalStateException: You should Call MMKV.initialize() first. 
但是我最baseapplication oncrete方法中进行了初始化，但是仍旧报错崩溃的问题

Caused by java.lang.IllegalStateException: You should Call MMKV.initialize() first.
       at com.tencent.mmkv.MMKV.defaultMMKV(MMKV.java:483)

仅仅部分手机存在这个问题， 需要您们的技术支持

设备
品牌：LGE
型号：Nexus 5X
屏幕方向： 纵向
可用 RAM： 1.32 GB
可用磁盘空间： 376.56 MB
操作系统
版本：Android 8.1.0
屏幕方向： 纵向
是否已取得 root 权限：否

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
The exception is crystal clear. There's nothing more we can offer.

**Comment by billdizl** [comment]
您的意思是无法解决,对吗?  如果针对这个问题,我如果在app内多次初始化,这个没有问题吧?因为目前存在的问题是仅仅国外的8.1的版本会出现这个问题

**Comment by billdizl** [comment]
多次使用MMKv.init(application)  在baseapplication 以及 在继承baseapplication的类中都进行初始化一次,这样子应该没问题吧?

**Comment by lingol** [comment]
> 多次使用MMKv.init(application)  在baseapplication 以及 在继承baseapplication的类中都进行初始化一次,这样子应该没问题吧?

You should call it once and only once.

**Comment by lingol** [comment]
> 您的意思是无法解决,对吗?  如果针对这个问题,我如果在app内多次初始化,这个没有问题吧?因为目前存在的问题是仅仅国外的8.1的版本会出现这个问题

No I mean the error is clear and you should be able to solve it all by yourself. Don't spam it here.

**Comment by billdizl** [comment]
> > 您的意思是无法解决,对吗?  如果针对这个问题,我如果在app内多次初始化,这个没有问题吧?因为目前存在的问题是仅仅国外的8.1的版本会出现这个问题
> 
> No I mean the error is clear and you should be able to solve it all by yourself. Don't spam it here.

错误确实很明显,但是我已经进行初始化了,在application oncrete时进行初始化了,90%的手机都能正常运行,但是部分手机都是8.1的版本的,报这个需要初始化first的错误,崩溃的内容已经是在闪屏页面的下一个页面了,难道初始化很长时间吗? 关键的是 implementation 'com.tencent:mmkv:1.2.8'版本没有出现过问题,从1.2.8版本升级到1.2.14版本后就出现了这个问题

**Comment by lingol** [comment]
Nan. You are checking the wrong direction. You should check the call stacks of the exception and fix the problem quickly.

**Comment by billdizl** [comment]
public class App extends Application {
   @Override
    public void onCreate() {
        super.onCreate();
//初始化mmkv
  MMKV.initialize(this);
 boolan isKey=MMKV.defaultMMKV().decodeBool("",false);
.....
}
}
经过验证线上的问题发现,在部分手机上,mmkv初始化还未完成就获取到MMKV.defaultMMKV()方法,故报Caused by java.lang.IllegalStateException: You should Call MMKV.initialize() first.      SP保存不需要初始化的就不存在这个问题!

**Comment by lingol** [comment]
It's the **cost** you must pay to use MMKV: **make sure** it's initialized before accessing other methods. There's no point for you to complain about it. If you want to use MMKV, follow MMKV's rules.

**Comment by billdizl** [comment]
> It's the **cost** you must pay to use MMKV: **make sure** it's initialized before accessing other methods. There's no point for you to complain about it. If you want to use MMKV, follow MMKV's rules.

我怎么确保他完全初始化,我看源码上面是在MMKV.initialize(this);方法是MMKV.rootDir = rootDir;  我在调用MMKV.initialize(this);立刻马上就调用了MMKV.defaultMMKV()来获取mmkv实例,defaultMMKV方法中 if (rootDir == null) {
            throw new IllegalStateException("You should Call MMKV.initialize() first.");
        }故报了You should Call MMKV.initialize() first,这个问题,我遵循着开发文档做的,但开发文档中没有提及,这不是抱怨,而是想着解决问题.因为目前只有海外版的部分手机存在这个问题,是出现在线上的,我没有该款手机.

**Comment by lingol** [comment]
Now you are talking. That's the right attitude, solve the problem. 
* The first thing you should do is collect crash stacks, and find out where and when this exception is thrown, focus on the outside call stacks (aka your code). 
* Next thing is find out why such call stacks happen before you call `MMKV.initialize()`.

**Comment by 704480904** [comment]
我的海外版三星 Android  12 系统 也出现了这个问题 目前就其中一个手机出现这个问题

**Comment by shenshaonan** [comment]
我也出现这个问题， 海外机型出现的  1.3.2的版本， 如何解决，如果解决不了那我换个插件了

**Comment by lingol** [comment]
> Now you are talking. That's the right attitude, solve the problem. 
> 
> * The first thing you should do is collect crash stacks, and find out where and when this exception is thrown, focus on the outside call stacks (aka your code). 
> 
> * Next thing is find out why such call stacks happen before you call `MMKV.initialize()`.

@704480904 @shenshaonan
