### ISSUE TITLE
刚存的数据，再次进报错 E/MMKV: <MMKV.cpp:395::checkFileCRCValid> check crc [ym] fail, crc32:3761198972, m_crcDigest:2266967967

### ISSUE THREAD

**Issue by JasonYinH** [Tencent/MMKV#1015]
代码
![image](https://user-images.githubusercontent.com/40187930/215462070-175ca421-2846-498f-a1f4-106afb0c10d5.png)
app和集成的SDK都用了mmkv，只是指定的包名不一样，代码都一样
日志
 I/MMKV: Enable checkProcessMode()
 I/MMKV: <native-bridge.cpp:104::JNI_OnLoad> current API level = 29, libc++_shared=0
 I/MMKV: <MMKV.cpp:165::initialize> version v1.2.13, page size 4096, arch arm64-v8a
 I/MMKV: <MMKV.cpp:176::initialize> armv8 AES instructions is supported
I/MMKV: <MMKV.cpp:184::initialize> armv8 CRC32 instructions is supported
 I/MMKV: <MMKV.cpp:207::initializeMMKV> root dir: /data/user/0/com.shine.ym/filesmmkv-z2
 I/MMKV: <MemoryFile.cpp:97::open> open fd[0x52], /data/user/0/com.shine.ym/filesmmkv-z2/ym
 I/MMKV: <MemoryFile.cpp:97::open> open fd[0x53], /data/user/0/com.shine.ym/filesmmkv-z2/ym.crc
 E/MMKV: <MMKV.cpp:395::checkFileCRCValid> check crc [ym] fail, crc32:3761198972, m_crcDigest:2266967967
 I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [ym] with 333800 actual size, file size 1048576, InterProcess 0, meta info version:3
 I/MMKV: <MMKV_IO.cpp:86::loadFromFile> loading [ym] with crc 3164659101 sequence 11 version 3
 I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [ym] with 28 key-values

**Comment by JasonYinH** [comment]
上面是app里的。这个是集成SDK的日志。
![image](https://user-images.githubusercontent.com/40187930/215462473-fd0ff1f9-b4e1-4ebc-8ead-ad3aad0f3cdd.png)

**Comment by lingol** [comment]
Try setting `MULTI_PROCESS_MODE`.

**Comment by lingol** [comment]
> 上面是app里的。这个是集成SDK的日志。 ![image](https://user-images.githubusercontent.com/40187930/215462473-fd0ff1f9-b4e1-4ebc-8ead-ad3aad0f3cdd.png)

The root directory is different from the App. You should initialize MMKV on `Application.onCreate()` once, and only init once.

**Comment by JasonYinH** [comment]
> 尝试设置`MULTI_PROCESS_MODE`。

如果SDK里不用MMKV了，这个就不用设置了吧setting MULTI_PROCESS_MODE.

**Comment by JasonYinH** [comment]
> 



> 尝试设置`MULTI_PROCESS_MODE`。

如果SDK里不用MMKV了，这个在APP里就不用设置了吧setting MULTI_PROCESS_MODE。

**Comment by JasonYinH** [comment]
> > 上面是app里的。这个是集成SDK的日志。![图片](https://user-images.githubusercontent.com/40187930/215462473-fd0ff1f9-b4e1-4ebc-8ead-ad3aad0f3cdd.png)
> 
> 根据目录与 App 不同。您应该开始化 MMKV`Application.onCreate()`一次，并且只开始化一次。

![image](https://user-images.githubusercontent.com/40187930/215638489-226d03e4-5e48-49a0-8a78-5fbac27d40c3.png)
我这个里面用了object关键字,并且在init里初始化了，那就不用再Application.onCreate()里初始化了吧，并且SDK不用MMKV了，只有APP里用

**Comment by lingol** [comment]
I won't repeat myself.
