### ISSUE TITLE
对于多进程在Application的onCreate创建几次

### ISSUE THREAD

**Issue by JasonYinH** [Tencent/MMKV#1017]
因为加了友盟推送，导致Application初始化了多次。通过获取当前的进程名判断是否主进程，是的话初始化 MMKV.initialize(this),但是再次调用会报
![image](https://user-images.githubusercontent.com/40187930/216218449-d85bfc5f-8691-4280-9e89-2595423cd999.png)
![image](https://user-images.githubusercontent.com/40187930/216218469-bb7cea2e-b668-49cd-bd8e-7be479b91db1.png)

**Comment by JasonYinH** [comment]
![image](https://user-images.githubusercontent.com/40187930/216218533-1b7be8c4-03c9-4563-9788-a9af38ab5b23.png)
Process多了个channel

**Comment by lingol** [comment]
You should initialize MMKV once and only once. What you should do is contact the SDK "友盟推送" developer and solve it with them.
