### ISSUE TITLE
MMKV Flutter script incompatible with ruby 3.2.0

### ISSUE THREAD

**Issue by Rizzaxc** [Tencent/MMKV#1020]
### The version of MMKV

 ` mmkv: ">=1.2.16"`

### The platform of MMKV

Flutter is on `3.7.1` and Dart on `2.19.1`

### What's the issue?
The method `exists` has been renamed `exist` on ruby 3.2.0, making `pod install` fail

```
[!] Invalid `Podfile` file: undefined method `exists?' for File:Class.

 #  from /../my_project/ios/Podfile:25
 #  -------------------------------------------
 #        require File.expand_path(File.join(plugin['path'], 'tool', 'mmkvpodhelper.rb'))
 >        mmkv_fix_plugin_name(flutter_application_path, is_module)
 #        return
 #  -------------------------------------------
```

```
ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22]
pod --version
Ignoring debug-1.7.1 because its extensions are not built. Try: gem pristine debug --version 1.7.1
Ignoring rbs-2.8.2 because its extensions are not built. Try: gem pristine rbs --version 2.8.2
1.11.3
```

**Comment by lingol** [comment]
Noted.

**Comment by imbaTao** [comment]
require 'json'

def fix_mmkv_plugin_name(flutter_application_path)
  is_module = false
  plugin_deps_file = File.expand_path(File.join(flutter_application_path, '..', '.flutter-plugins-dependencies'))
  
  if !File.exist?(plugin_deps_file)
    is_module = true
    plugin_deps_file = File.expand_path(File.join(flutter_application_path, '.flutter-plugins-dependencies'))
  end

  plugin_deps_content = File.read(plugin_deps_file)
  plugin_deps = JSON.parse(plugin_deps_content).dig('plugins', 'ios') || []

  plugin_deps.each do |plugin|
    if plugin['name'] == 'mmkv' || plugin['name'] == 'mmkvflutter'
      require File.expand_path(File.join(plugin['path'], 'tool', 'mmkvpodhelper.rb'))
      mmkv_fix_plugin_name(flutter_application_path, is_module)
      return
    end
  end

  raise "Fail to find any mmkv plugin dependencies in #{plugin_deps_file}. If you're running pod install manually, make sure flutter pub get is executed first"
end

fix_mmkv_plugin_name(File.dirname(File.realpath(__FILE__)))
