### ISSUE TITLE
 InvalidProtocolBuffer truncatedMessage

### ISSUE THREAD

**Issue by lvjiancong** [Tencent/MMKV#1027]
android依赖版本：
implementation 'com.tencent:mmkv:1.2.15'

使用了MMKV.MULTI_PROCESS_MODE
代码：MMKV.mmkvWithID(NAME, MMKV.MULTI_PROCESS_MODE);

出现问题：
<MMKV.cpp:552::getString> InvalidProtocolBuffer truncatedMessage

**Comment by lingol** [comment]
You should look at the logs of MMKV carefully.

**Comment by lingol** [comment]
Any updates?

**Comment by lvjiancong** [comment]
不好意思忘记回复您了，我这边有排查到问题，不是单进程问题，是当存入的值为的类型和取出来的时候类型不匹配导致的，比如我存入的是int，但取的时候用了getString。场景出现在我自己写的getAll()方法时
