### ISSUE TITLE
openssl

### ISSUE THREAD

**Issue by whuthj** [Tencent/MMKV#1029]
The vulnerabilities were addressed in OpenSSL 1.02f/1.01r. To confirm your OpenSSL version, you can do a grep search for:

$ unzip -p YourApp.apk | strings | grep "OpenSSL"

**Comment by lingol** [comment]
What vulnerabilities?

**Comment by whuthj** [comment]
What version of openssl is used by mmkv

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/FAQ
