### ISSUE TITLE
MMKV crash on  HONOR  OXF-AN00

### ISSUE THREAD

**Issue by joychic** [Tencent/MMKV#1030]
## Note:
crash on  HONOR  OXF-AN00  Android10

### The language of MMKV

> Java, or Kotlin

### The version of MMKV
1.2.14

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?
java stacktrace:
"at com.tencent.mmkv.MMKV.decodeString(Native Method)
at com.tencent.mmkv.MMKV.decodeString(MMKV.java:2)
at vd.b.loadAll(MMKVCookiePersistor.java:4)
at vd.f.loadForRequest(NewRePersistentCookieJar.java:2)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:17)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:6)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)

code:"-1 (SI_QUEUE)"
backtrace:"#00 pc 000000000006f06c /apex/com.android.runtime/lib64/bionic/libc.so (abort+160)
#01 pc 000000000005591c /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so
#02 pc 0000000000041714 /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so (__gxx_personality_v0+348)
#03 pc 000000000016bb08 /data/asan/system/lib64/libc++.so
#04 pc 000000000016be2c /data/asan/system/lib64/libc++.so (_Unwind_RaiseException+252)
#05 pc 000000000006bcc8 /data/asan/system/lib64/libc++.so (__cxa_throw+104)
#06 pc 000000000002e1d0 /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so
#07 pc 000000000001eccc /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so
#08 pc 0000000000019058 /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so
#09 pc 000000000025cc8c /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/oat/arm64/base.odex (art_jni_trampoline+188)
#10 pc 0000000000145334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
#11 pc 00000000001541a4 /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252)
#12 pc 00000000002efd0c /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE+384)
#13 pc 00000000002eafdc /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+912)
#14 pc 00000000005c09cc /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+400)
#15 pc 000000000013f914 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
#16 pc 00000000005c4b48 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1368)
#17 pc 0000000000143594 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
#18 pc 00000000005c0130 /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1752)
#19 pc 000000000013fa14 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
#20 pc 00000000005c0130 /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1752)
#21 pc 000000000013fa14 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
#22 pc 00000000005c0130 /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1752)
#23 pc 000000000013fa14 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
#24 pc 00000000005c4b48 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1368)
#25 pc 0000000000143594 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
#26 pc 00000000005c0130 /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1752)
#27 pc 000000000013fa14 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
#28 pc 00000000005c4b48 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1368)
#29 pc 0000000000143594 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
#30 pc 00000000002c0948 /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.679723278222956480+240)
#31 pc 00000000005a980c /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1012)
#32 pc 000000000014e468 /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88)
#33 pc 0000000000145334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
#34 pc 00000000001541a4 /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252)
#35 pc 00000000004ca58c /apex/com.android.runtime/lib64/libart.so (_ZN3art12_GLOBAL__N_118InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS0_8ArgArrayEPNS_6JValueEPKc+104)
#36 pc 00000000004cb620 /apex/com.android.runtime/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithJValuesERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDPK6jvalue+416)
#37 pc 00000000003977a0 /apex/com.android.runtime/lib64/libart.so (_ZN3art3JNI17CallObjectMethodAEP7_JNIEnvP8_jobjectP10_jmethodIDPK6jvalue+624)
#38 pc 0000000000033180 <anonymous: 59e980b000>
"

**Comment by lingol** [comment]
Please provide **symbolized** native call stacks of MMKV.
>backtrace:"#00 pc 000000000006f06c /apex/com.android.runtime/lib64/bionic/libc.so (abort+160)
https://github.com/Tencent/MMKV/pull/1 pc 000000000005591c /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so
https://github.com/Tencent/MMKV/pull/2 pc 0000000000041714 /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so (__gxx_personality_v0+348)
https://github.com/Tencent/MMKV/pull/3 pc 000000000016bb08 /data/asan/system/lib64/libc++.so
https://github.com/Tencent/MMKV/pull/4 pc 000000000016be2c /data/asan/system/lib64/libc++.so (_Unwind_RaiseException+252)
https://github.com/Tencent/MMKV/pull/5 pc 000000000006bcc8 /data/asan/system/lib64/libc++.so (__cxa_throw+104)
https://github.com/Tencent/MMKV/pull/6 pc 000000000002e1d0 /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so
https://github.com/Tencent/MMKV/pull/7 pc 000000000001eccc /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so
https://github.com/Tencent/MMKV/pull/8 pc 0000000000019058 /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so

**Comment by lingol** [comment]
Closed due to lack of information.

**Comment by billdizl** [comment]
> ## Note:
> crash on HONOR OXF-AN00 Android10
> 
> ### The language of MMKV
> > Java, or Kotlin
> 
> ### The version of MMKV
> 1.2.14
> 
> ### The platform of MMKV
> Android
> 
> ### The installation of MMKV
> Maven
> 
> ### What's the issue?
> java stacktrace: "at com.tencent.mmkv.MMKV.decodeString(Native Method) at com.tencent.mmkv.MMKV.decodeString(MMKV.java:2) at vd.b.loadAll(MMKVCookiePersistor.java:4) at vd.f.loadForRequest(NewRePersistentCookieJar.java:2) at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:17) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:6) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
> 
> code:"-1 (SI_QUEUE)" backtrace:"#00 pc 000000000006f06c /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) #1 pc 000000000005591c /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so #2 pc 0000000000041714 /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so (__gxx_personality_v0+348) #3 pc 000000000016bb08 /data/asan/system/lib64/libc++.so #4 pc 000000000016be2c /data/asan/system/lib64/libc++.so (_Unwind_RaiseException+252) #5 pc 000000000006bcc8 /data/asan/system/lib64/libc++.so (__cxa_throw+104) #6 pc 000000000002e1d0 /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so #7 pc 000000000001eccc /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so #8 pc 0000000000019058 /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/lib/arm64/libmmkv.so #9 pc 000000000025cc8c /data/app/com.shizhuang.duapp-OnELbDT7QYX24WPdL89_RQ==/oat/arm64/base.odex (art_jni_trampoline+188) #10 pc 0000000000145334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) #11 pc 00000000001541a4 /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252) #12 pc 00000000002efd0c /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE+384) #13 pc 00000000002eafdc /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+912) #14 pc 00000000005c09cc /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+400) #15 pc 000000000013f914 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) #16 pc 00000000005c4b48 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1368) #17 pc 0000000000143594 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20) #18 pc 00000000005c0130 /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1752) #19 pc 000000000013fa14 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) #20 pc 00000000005c0130 /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1752) #21 pc 000000000013fa14 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) #22 pc 00000000005c0130 /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1752) #23 pc 000000000013fa14 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) #24 pc 00000000005c4b48 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1368) #25 pc 0000000000143594 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20) #26 pc 00000000005c0130 /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1752) #27 pc 000000000013fa14 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20) #28 pc 00000000005c4b48 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtualQuick+1368) #29 pc 0000000000143594 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual_quick+20) #30 pc 00000000002c0948 /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.679723278222956480+240) #31 pc 00000000005a980c /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1012) #32 pc 000000000014e468 /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) #33 pc 0000000000145334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) #34 pc 00000000001541a4 /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252) #35 pc 00000000004ca58c /apex/com.android.runtime/lib64/libart.so (_ZN3art12_GLOBAL__N_118InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS0_8ArgArrayEPNS_6JValueEPKc+104) #36 pc 00000000004cb620 /apex/com.android.runtime/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithJValuesERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDPK6jvalue+416) #37 pc 00000000003977a0 /apex/com.android.runtime/lib64/libart.so (_ZN3art3JNI17CallObjectMethodAEP7_JNIEnvP8_jobjectP10_jmethodIDPK6jvalue+624) #38 pc 0000000000033180 <anonymous: 59e980b000> "
> 
> ### What's the log of MMKV when that happened?

请问你这个解决了吗?
