### ISSUE TITLE
Flutter mmkv failed to load so library in Android 6.0

### ISSUE THREAD

**Issue by pengboboer** [Tencent/MMKV#1034]
## Note:
flutter mmkv occasionally appears on Android 6.0 devices, and the so library fails to load

### The language of MMKV

Flutter

### The version of MMKV

v1.2.4/v1.2.5/v1.2.6

### The platform of MMKV

Flutter/Android

### The installation of MMKV

pub 

### What's the issue?
Our app is using mmkv, but recently it was reported that some Android 6.0 mobile phones, such as vivoY66, crashed when the app was started under certain conditions. There is no problem with using vivoY66 when it was started for the first time or even after pressing the return key of the phone, while using vivoY66 to kill the process manually. After restarting the app, an error will be reported during the initialization operation of MMKV:

Invalid argument(s): Failed to load dynamic library 'libmmkv.so': dlopen failed: library "libmmkv.so" not found

![image](https://user-images.githubusercontent.com/39305741/223995090-edd96418-750a-494c-8c51-0d79aeb15505.png)

Then I found the error location. It doesn't look like the error of mmkv. It may be the error of ffi loading so library

![image](https://user-images.githubusercontent.com/39305741/224241096-f9d3b66a-74b9-4901-8bfd-d5797bc793a6.png)

This situation is real, because a large part of our users are still low-end mobile phones. The way to reproduce it is to use Vivo y66 (Android 6.0 device) to start the app normally once, then kill the process manually, click the app again to restart, and then throw an error

I see that no one has this situation when using Flutter mmkv, so I put forward an issue to help more people identify problems more quickly

### What's the log of MMKV when that happened?
Invalid argument(s): Failed to load dynamic library 'libmmkv.so': dlopen failed: library "libmmkv.so" not found

**Comment by lingol** [comment]
How do you suggest solving this problem, as you can clearly reproduce it in your description?

**Comment by pengboboer** [comment]
@lingol This issue has been resolved and is running well online, but the solution is not the best. Do you consider closing this issue?
