### ISSUE TITLE
空间增长，文件重整疑问

### ISSUE THREAD

**Issue by lvjiancong** [Tencent/MMKV#1037]
您好，有几个问题请教一下：
1、当空间增长，达到文件重整时会进行“文件重整、key 排重，尝试序列化保存排重结果”，这个处理后是会将原本重复的旧值删除，只保留一个key对应一个value吗？
2、使用 append 实现增量更新，随着数据的增加读取速度影响如何？

**Comment by lingol** [comment]
1. Yes.
2. Doesn't matter in general.

**Comment by lvjiancong** [comment]
> 1. Yes.
> 2. Doesn't matter in general.

thanks
