### ISSUE TITLE
如果不希望用户通过“一键换机”的功能，在新的手机上读到在旧手机上存储的数据，该怎么做？

### ISSUE THREAD

**Issue by ElevenZhaoy** [Tencent/MMKV#1042]
### The language of MMKV

> Java, or Kotlin

### The platform of MMKV

> Android

**Comment by lingol** [comment]
Customize your MMKV root path. https://github.com/Tencent/MMKV/wiki/android_advance_cn#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B9%E7%9B%AE%E5%BD%95
