### ISSUE TITLE
安卓平台上开机向导后会出现mmkv的native crash

### ISSUE THREAD

**Issue by evanyixie** [Tencent/MMKV#1046]
您好， 我们在安卓应用中集成了mmkv，使用的是多进程模式，各项功能特性都正常。
但是我们在开机向导后，会几乎必现native crash。
该native crash的错误主要是MuteLockTimeout, 或者是空指针，同时流水日志中会有filed to open的一些日志。由于不便提供具体日志，请问您是否了解该问题？

正常的重启开机或者启动应用时，不会出现该问题。只有在手机HOTA升级的开机向导后，立刻进入应用，使用mmkv的读写接口会出现此异常。请您提供一下解决该问题的方向与思路。

**Comment by lingol** [comment]
No idea.
