### ISSUE TITLE
UnsatisfiedLinkError *** too long

### ISSUE THREAD

**Issue by xushengwei** [Tencent/MMKV#1048]
## Note:
部分手机启动时加载mmkv出现崩溃

androidVersion:5.1
device:meizu m2 note 
flyme 6.3.5.0A

### The language of MMKV
Kotlin

### The version of MMKV
v1.2.15  

### The platform of MMKV
 Android

### What's the log of MMKV when that happened?
java.lang.UnsatisfiedLinkError: dlopen failed: library name "/data/app/***-2/lib/arm64/libmmkv.so" too long

**Comment by lingol** [comment]
The reason is clear, your application installation path is too long. Solve it yourself.
>java.lang.UnsatisfiedLinkError: dlopen failed: library name "/data/app/***-2/lib/arm64/libmmkv.so" **too long**
