### ISSUE TITLE
Migrate flutter plugin to federated plugins to solve naming conflict on iOS

### ISSUE THREAD

**Issue by hyiso** [Tencent/MMKV#1051]
### Discussed in https://github.com/Tencent/MMKV/discussions/1050

<div type='discussions-op-text'>

<sup>Originally posted by **hyiso** March 29, 2023</sup>
Migrate `mmkv` plugin to federated plugins, as:
- `mmkv` entry package
-  `mmkv_ios` plugin for iOS
- `mmkv_android` plugin for Android
- `mmkv_platform_interface` interface package

to solve the Pod naming conflict instead of modify Podfile/ruby script manually.
</div>

**Comment by lingol** [comment]
Not interested.

**Comment by T-moz** [comment]
@lingol The solution describe in the readme.md to avoid the naming conflict on iOS greatly reduce the developper experience on iPhone.
- pod install needs to be run more often than necessary.
- when an app that depends on mmkv is run on profile mode, the hot restart causes a crash.

This greatly reduce the development speed of any developper using mmkv on a flutter app.

---

MMKV is really one the best locale database for a iOS and Android app in the flutter ecosystem.
But the devX is not that great.

Please, reconsider this issue.

**Comment by lingol** [comment]
Hey guys, good news. I just found out it's easier than we thought. With these simple steps,

1. Move the ios part of the original `mmkv` package into a separate package `mmkv_ios`, and declare it `implements: mmkv` in the podspec.yaml.
2. Modify the `mmkv` package's podspec.yaml to depend on `mmkv_ios`, and change ios platform to `default_package: mmkv_ios` (endorsed).

The naming conflict headache is gone! 
Looks like the Federated Plugin Runtime doesn't really rely on the platform interface framework. Suppose all we care about is the naming headache, we are already done.

It's a bit ugly just moving things around without some proper refactoring. So I will keep polishing it a little more.

**Comment by lingol** [comment]
It's released in [v1.3.5](https://github.com/Tencent/MMKV/releases/tag/v1.3.5).

**Comment by T-moz** [comment]
@lingol Thanks for the package update !
I juste tried it in my app, it works like a charm 🤩

Congrats for this new version
