### ISSUE TITLE
 Flutter 1.2.9升级到1.2.16后获取不到值

### ISSUE THREAD

**Issue by aizuzi** [Tencent/MMKV#1056]
### The language of MMKV

Flutter

### The version of MMKV

1.2.9升级到1.2.16

### The platform of MMKV

Android

### The installation of MMKV

pub.dev

### What's the issue?

升级后获取不到之前保存的值，Flutter版本从2.2.3升级到了3.7.5，不确定跟这个有没有关系
下面是升级后打开的部分log

I/MMKV    (30470): <flutter-bridge.cpp:50::mmkvInitialize_v1> current API level = 30, libc++_shared=0
I/MMKV    (30470): <MMKV.cpp:165::initialize> version v1.2.15, page size 4096, arch arm64-v8a
I/MMKV    (30470): <MMKV.cpp:176::initialize> armv8 AES instructions is supported
I/MMKV    (30470): <MMKV.cpp:184::initialize> armv8 CRC32 instructions is supported
I/MMKV    (30470): <MMKV.cpp:208::initializeMMKV> root dir: /data/user/0/com.zuzi.fit/app_flutter/mmkv
I/MMKV    (30470): <MemoryFile.cpp:97::open> open fd[0x6a], /data/user/0/com.zuzi.fit/app_flutter/mmkv/mmkv.default
I/MMKV    (30470): <MemoryFile.cpp:97::open> open fd[0x6b], /data/user/0/com.zuzi.fit/app_flutter/mmkv/mmkv.default.crc
I/MMKV    (30470): <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 625 actual size, file size 4096, InterProcess 0, meta info version:3
I/MMKV    (30470): <MMKV_IO.cpp:86::loadFromFile> loading [mmkv.default] with crc 2553746452 sequence 1 version 3
E/MMKV    (30470): <MiniPBCoder.cpp:285::decodeOneMap> InvalidProtocolBuffer truncatedMessage
I/MMKV    (30470): <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values

**Comment by lingol** [comment]
It's a known issue and has a one-time workaround. 
Check out the release note. https://github.com/Tencent/MMKV/releases/tag/v1.2.9
