### ISSUE TITLE
Can MMKV be used instead of SharedPreference? And is there a size limit of the MMKV file

### ISSUE THREAD

**Issue by ByaneChen** [Tencent/MMKV#1058]
hi，I plan to migrate the SharedPreference data to MMKV recently, as we have stored too much data in SharedPreference, the file may be up to 10M ~ 100M, is it suitable to migrate the data to MMKV？will the performance decrease when the data grows to 10 ~ 100M+? Thanks.

**Comment by lingol** [comment]
Yes you should migrate to MMKV. However, No storage engine performs well both on small datasets and big datasets. You should separate them into different MMKV instances.
