### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Croie** [Tencent/MMKV#1059]
开发语言：Java, or Kotlin
使用mmkv版本：v1.2.8
android系统：11，12
android厂商：vivo

问题栈信息：
java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mmkv.MMKV.jniInitialize(java.lang.String, int) (tried Java_com_tencent_mmkv_MMKV_jniInitialize and Java_com_tencent_mmkv_MMKV_jniInitialize__Ljava_lang_String_2I)
    com.tencent.mmkv.MMKV.jniInitialize(MMKV.java:0)
    com.tencent.mmkv.MMKV.doInitialize(MMKV.java:123)
    com.tencent.mmkv.MMKV.initialize(MMKV.java:108)
    com.tencent.mmkv.MMKV.initialize(MMKV.java:97)
    com.funbox.libcommon.DoFunApplication.initMMKV(DoFunApplication.java:64)
    com.funbox.libcommon.DoFunApplication.onCreate(DoFunApplication.java:38)
    com.funbox.plus.ThailandApplication.onCreate(ThailandApplication.java:14)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1242)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:7185)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:2152)
    android.os.Handler.dispatchMessage(Handler.java:106)
    android.os.Looper.loop(Looper.java:239)
    android.app.ActivityThread.main(ActivityThread.java:8179)
    java.lang.reflect.Method.invoke(Method.java:0)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by lingol** [comment]
Looks like you have failed to load libmmkv.so.

**Comment by lingol** [comment]
One more thing, your version is way too old. Consider upgrading to the latest version even though it has nothing to do with this crash.
