### ISSUE TITLE
支持对象

### ISSUE THREAD

**Issue by AgoniAlways** [Tencent/MMKV#106]

**Comment by lingol** [comment]
If you mean supporting Objective-C objects, MMKV already supports encoding `<NSCoding>`.
Just implement `<NSCoding>` in your interface and everything should work.

**Comment by AgoniAlways** [comment]
谢谢，Android 库是否支持Java对象？

**Comment by lingol** [comment]
#109

**Comment by lingol** [comment]
> 谢谢，Android 库是否支持Java对象？

Supported with [commit](https://github.com/Tencent/MMKV/commit/0c61567c920501017c975a2ceed350e3584ba7cb), hopefully will come out this week.

**Comment by AgoniAlways** [comment]
共同期待
