### ISSUE TITLE
backup/restore can't work

### ISSUE THREAD

**Issue by hulong121** [Tencent/MMKV#1061]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Objective-C

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

v1.2.15

### The platform of MMKV

> e.g. iOS or Android
iOS

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html
i create an empty project for test MMKV backup/restore, 
i found that, if i call [MMKV restoreOneMMKV] after write some data into the origin mmkv instance, the restore will fail
please check the log.txt and the demo project which name is testMMKV.zip(unzip it and run 'pod init', 'pod install' to generate workspace),
the steps to reproduce are:
1.click 'saveMain' button
2.click 'backup' button
3.click 'setRandToMain' button
4.click 'restore' button(you can click 'readMain' button to show the data, mostly not restore successfully)
5.click 'setRandToMain' button again
6.click 'restore' button again
then you can search log 'check crc', means crc check failed, and the origin data have nothing now.

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.
[log.txt](https://github.com/Tencent/MMKV/files/11199909/log.txt)
[testMMKV.zip](https://github.com/Tencent/MMKV/files/11199910/testMMKV.zip)

**Comment by lingol** [comment]
Noted.

**Comment by lingol** [comment]
This is a bug due to the metafile not correctly reloading. It's fixed in the dev branch.

**Comment by hulong121** [comment]
got it, thanks.

**Comment by lingol** [comment]
It's released in v1.2.16.
