### ISSUE TITLE
building witch ming64, print type "w_char" error.

### ISSUE THREAD

**Issue by xy52059** [Tencent/MMKV#1062]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

v1.2.15

### The platform of MMKV

> e.g. iOS or Android

mingw

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

When I building witch ming64, print type "w_char" error.

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

[I] <MMKV.cpp:208::initializeMMKV> root dir: %ws

**Comment by lingol** [comment]
I don't understand your question. You might consider using an online translator or AI.

**Comment by xy52059** [comment]
I can use Chinese?

**Comment by xy52059** [comment]
当我用ming64编译出demo，在运行demo后，打印log中，std::wstring类型没有转换成对应的字符串，而是输出字符串"%ws"，
我把源码中"%ws"替换成"%ls"后，可以正常打印

**Comment by lingol** [comment]
Which compiler are you using, GCC or clang?

**Comment by lingol** [comment]
And which port of MMKV did you use, I mean did you use [MMKV for Win32](https://github.com/Tencent/MMKV/wiki/windows_setup_cn) or [MMKV for POSIX](https://github.com/Tencent/MMKV/wiki/posix_setup_cn)?
