### ISSUE TITLE
MMKV store path is not safe in iOS

### ISSUE THREAD

**Issue by yuman07** [Tencent/MMKV#107]
### The language of MMKV

Objective-C

### The version of MMKV

1.0.12

### The platform of MMKV

iOS

### The installation of MMKV

Cocoapods

### What's the issue?

MMKV will auto store data on 'sandBox/Documents/mmkv/mmkv.default' in iOS
this file path is not safe, when the app has config info.plist 'Supports Documents browser = YES'
it will let users see&get these file from apple's 'Files' app

**Comment by lingol** [comment]
And your suggestion is?

**Comment by yuman07** [comment]
> And what's your suggestion? I'm all ears.

i recommend store it at 'sandBox/Library/mmkv'
library folder is also lasting, but not be see by users

**Comment by lingol** [comment]
And did you know that files stored in **library** will not be backup by iTunes/iCloud? When you restore an iDevice, those files is lost.
And now do you still think it's a good idea to store MMKV in library?

**Comment by yuman07** [comment]
> And did you know that files stored in **library** will not be backup by iTunes/iCloud? When you restore an iDevice, those files are lost.
> Do you still think it's a good idea to store MMKV in library?

From the information I collected, the 'Library' will also be backup by iCloud.
as ' https://developer.apple.com/icloud/documentation/data-storage/index.html ' say

> iCloud includes Backup, which automatically backs up a user’s iOS device daily over Wi-Fi. **Everything in your app’s home directory is backed up, with the exception of the application bundle itself, the caches directory, and temp directory**. Purchased music, apps, books, the Camera Roll, device settings, home screen and app organization, messages, and ringtones are backed up as well. Because backups are done wirelessly and stored in iCloud for each user, it’s best to minimize the amount of data that’s stored for your app. Large files will lengthen the time it takes to perform a backup and consume more of a user’s available iCloud storage.

**Comment by lingol** [comment]
> From the information I collected, the 'Library' will also be backup by iCloud.
> as ' https://developer.apple.com/icloud/documentation/data-storage/index.html ' say

It's true. I'm wrong, my apprize. That reminds me of Why WeChat doesn't store any important/unregenerable data inside `Library`. I thought it was because of not backing up by iCloud. Which is not quit correct. And I do some dig around. It turns out to be some Apple's best protocol:

>This is the top-level directory for any files that are not user data files. You typically put files in one of several standard subdirectories. iOS apps commonly use the Application Support and Caches subdirectories; however, you can create custom subdirectories.
>Use the Library subdirectories for any files you don’t want exposed to the user. Your app should not use these directories for user data files.
https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html

And We think MMKV is no doubt **user data file**.

**Comment by lingol** [comment]
Closing for not active in days.

**Comment by yuman07** [comment]
since wechat 7.0, any normal user can see all file in the Document dictionary
they can see, rename, move , even delete it 
Did you still think it is safe to save mmkv in the Document dictionary?
![wechatimg9](https://user-images.githubusercontent.com/39876471/50443583-02701400-093f-11e9-8985-4851b656fcc4.jpeg)
![wechatimg10](https://user-images.githubusercontent.com/39876471/50443585-0308aa80-093f-11e9-913f-4d970ba27fbd.jpeg)
![wechatimg11](https://user-images.githubusercontent.com/39876471/50443586-03a14100-093f-11e9-8d30-e1e7cd84ea39.jpeg)

**Comment by lingol** [comment]
It's a mistake to expose these files. Will fix soon.

**Comment by lingol** [comment]
Released with [v1.0.16](https://github.com/Tencent/MMKV/releases/tag/v1.0.16).
