### ISSUE TITLE
<MemoryFile.cpp:94::open> fail to open [/data/user/0/xxxx/files/mmkv/user_config], 2(No such file or directory)

### ISSUE THREAD

**Issue by leeGYPlus** [Tencent/MMKV#1072]
### The language of MMKV

> Java

### The version of MMKV
```
implementation 'com.tencent:mmkv:1.2.13'
```

### The platform of MMKV

>  Android

### The installation of MMKV

> Maven

### What's the issue?

> After initializing MMKV in Application, attempting to write a value using MMKV immediately encountered an issue. 

> My Project is **Launcher**，when I reboot device，I meet The problem，but when i restart the application, the problem has gone. I can`t understand it.

The following are the  code:

```
//Application 
public void onCreate() {
        super.onCreate();
       MMKV.initialize(this);
      UserConfig.setValue(xxxx);
}

//UserConfig
public class UserConfig{

   private static volatile LocalConfig mLocalConfig;
    protected static LocalConfig getInstance(final String configName) {
        if (mLocalConfig == null) {
            synchronized (UserConfig.class) {
                if (mLocalConfig == null) {
                    mLocalConfig = new MMKVLocalConfig() {
                        @Override
                        public String localConfigFile() {
                            return configName;
                        }
                    };
                }
            }
        }
        return mLocalConfig;
    }

    private static LocalConfig getInstance() {
        return getInstance("user_config");
    }

 public static void setValue(boolean value) {
        getInstance().putBoolean(KEY_xxxx, value);
    }

}
```

### What's the log of MMKV when that happened?
```
20:18:50.455 MMKV                     I  Enable checkProcessMode()
20:18:50.476 MMKV                     I  <native-bridge.cpp:104::JNI_OnLoad> current API level = 31, libc++_shared=0
20:18:50.476 MMKV                     I  <MMKV.cpp:165::initialize> version v1.2.13, page size 4096, arch armeabi-v7a/NEON
20:18:50.477 MMKV                     W  <MemoryFile.cpp:273::mkPath> /data/user/0/xxxx/files : Required key not available
20:18:50.477 MMKV                     I  <MMKV.cpp:207::initializeMMKV> root dir: /data/user/0/xxxx/files/mmkv
20:18:50.618 MMKV                     E  <MemoryFile.cpp:94::open> fail to open [/data/user/0/xxx/files/mmkv/user_config], 2(No such file or directory)
20:18:50.618 MMKV                     E  <MemoryFile.cpp:94::open> fail to open [/data/user/0/xxxx/files/mmkv/user_config], 2(No such file or directory)
20:18:50.618 MMKV                     E  <MemoryFile.cpp:208::reloadFromFile> fail to open:/data/user/0/xxxx/files/mmkv/user_config, No such file or directory
20:18:50.618 MMKV                     E  <MemoryFile.cpp:94::open> fail to open [/data/user/0/xxxx/files/mmkv/user_config.crc], 2(No such file or directory)
20:18:50.619 MMKV                     E  <MemoryFile.cpp:94::open> fail to open [/data/user/0/xxx/files/mmkv/user_config.crc], 2(No such file or directory)
20:18:50.619 MMKV                     E  <MemoryFile.cpp:208::reloadFromFile> fail to open:/data/user/0/xxx/files/mmkv/user_config.crc, No such file or directory
20:18:50.619 MMKV                     E  <MemoryFile.cpp:94::open> fail to open [/data/user/0xxxx/files/mmkv/user_config], 2(No such file or directory)
20:18:50.619 MMKV                     E  <MemoryFile.cpp:208::reloadFromFile> fail to open:/data/user/0/xxx/files/mmkv/user_config, No such file or directory
20:18:50.619 MMKV                     E  <MMKV_IO.cpp:74::loadFromFile> file [/data/user/0/xxxx/files/mmkv/user_config] not valid
20:18:50.620 MMKV                     W  <MMKV_IO.cpp:346::ensureMemorySize> [user_config] file not valid
20:18:59.881 MMKV                     I  Disable checkProcessMode()


### My idea
> Is it possible that MMKV has not been successfully initialized yet when attempting to write to it after the device has been restarted?

**Comment by lingol** [comment]
You should Google about **Launcher**, and the first error MMKV prints, aka **Required key not available**. I guess there's something **special** about Launcher from a normal App.

**Comment by lzyang187** [comment]
> ### The language of MMKV
> > Java
> 
> ### The version of MMKV
> ```
> implementation 'com.tencent:mmkv:1.2.13'
> ```
> 
> ### The platform of MMKV
> > Android
> 
> ### The installation of MMKV
> > Maven
> 
> ### What's the issue?
> > After initializing MMKV in Application, attempting to write a value using MMKV immediately encountered an issue.
> 
> > My Project is **Launcher**，when I reboot device，I meet The problem，but when i restart the application, the problem has gone. I can`t understand it.
> 
> The following are the code:
> 
> ```
> //Application 
> public void onCreate() {
>         super.onCreate();
>        MMKV.initialize(this);
>       UserConfig.setValue(xxxx);
> }
> 
> //UserConfig
> public class UserConfig{
> 
>    private static volatile LocalConfig mLocalConfig;
>     protected static LocalConfig getInstance(final String configName) {
>         if (mLocalConfig == null) {
>             synchronized (UserConfig.class) {
>                 if (mLocalConfig == null) {
>                     mLocalConfig = new MMKVLocalConfig() {
>                         @Override
>                         public String localConfigFile() {
>                             return configName;
>                         }
>                     };
>                 }
>             }
>         }
>         return mLocalConfig;
>     }
> 
>     private static LocalConfig getInstance() {
>         return getInstance("user_config");
>     }
> 
>  public static void setValue(boolean value) {
>         getInstance().putBoolean(KEY_xxxx, value);
>     }
> 
> }
> ```
> 
> ### What's the log of MMKV when that happened?
> ```
> 20:18:50.455 MMKV                     I  Enable checkProcessMode()
> 20:18:50.476 MMKV                     I  <native-bridge.cpp:104::JNI_OnLoad> current API level = 31, libc++_shared=0
> 20:18:50.476 MMKV                     I  <MMKV.cpp:165::initialize> version v1.2.13, page size 4096, arch armeabi-v7a/NEON
> 20:18:50.477 MMKV                     W  <MemoryFile.cpp:273::mkPath> /data/user/0/xxxx/files : Required key not available
> 20:18:50.477 MMKV                     I  <MMKV.cpp:207::initializeMMKV> root dir: /data/user/0/xxxx/files/mmkv
> 20:18:50.618 MMKV                     E  <MemoryFile.cpp:94::open> fail to open [/data/user/0/xxx/files/mmkv/user_config], 2(No such file or directory)
> 20:18:50.618 MMKV                     E  <MemoryFile.cpp:94::open> fail to open [/data/user/0/xxxx/files/mmkv/user_config], 2(No such file or directory)
> 20:18:50.618 MMKV                     E  <MemoryFile.cpp:208::reloadFromFile> fail to open:/data/user/0/xxxx/files/mmkv/user_config, No such file or directory
> 20:18:50.618 MMKV                     E  <MemoryFile.cpp:94::open> fail to open [/data/user/0/xxxx/files/mmkv/user_config.crc], 2(No such file or directory)
> 20:18:50.619 MMKV                     E  <MemoryFile.cpp:94::open> fail to open [/data/user/0/xxx/files/mmkv/user_config.crc], 2(No such file or directory)
> 20:18:50.619 MMKV                     E  <MemoryFile.cpp:208::reloadFromFile> fail to open:/data/user/0/xxx/files/mmkv/user_config.crc, No such file or directory
> 20:18:50.619 MMKV                     E  <MemoryFile.cpp:94::open> fail to open [/data/user/0xxxx/files/mmkv/user_config], 2(No such file or directory)
> 20:18:50.619 MMKV                     E  <MemoryFile.cpp:208::reloadFromFile> fail to open:/data/user/0/xxx/files/mmkv/user_config, No such file or directory
> 20:18:50.619 MMKV                     E  <MMKV_IO.cpp:74::loadFromFile> file [/data/user/0/xxxx/files/mmkv/user_config] not valid
> 20:18:50.620 MMKV                     W  <MMKV_IO.cpp:346::ensureMemorySize> [user_config] file not valid
> 20:18:59.881 MMKV                     I  Disable checkProcessMode()
> 
> 
> ### My idea
> > Is it possible that MMKV has not been successfully initialized yet when attempting to write to it after the device has been restarted?
> ```

I also meet the same problem, **Launcher app**;**reboot device**,mmkv version is **1.3.9**.

`mmkv rootDir: /data/user/0/com.transsion.hilauncher/files/mmkv

<MemoryFile.cpp:95::open> fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default], 2(No such file or directory)

<MemoryFile.cpp:95::open> fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default], 2(No such file or directory)

<MemoryFile.cpp:220::reloadFromFile> fail to open:/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default, No such file or directory

<MemoryFile.cpp:95::open> fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc], 2(No such file or directory)

<MemoryFile.cpp:95::open> fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc], 2(No such file or directory)

<MemoryFile.cpp:220::reloadFromFile> fail to open:/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc, No such file or directory

<MemoryFile.cpp:95::open> fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc], 2(No such file or directory)

<MemoryFile.cpp:220::reloadFromFile> fail to open:/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc, No such file or directory

<MMKV_IO.cpp:192::loadMetaInfoAndCheck> file [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc] not valid

<MemoryFile.cpp:95::open> fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default], 2(No such file or directory)

<MemoryFile.cpp:220::reloadFromFile> fail to open:/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default, No such file or directory

<MMKV_IO.cpp:77::loadFromFile> file [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default] not valid
`

**Comment by lzyang187** [comment]
/cc @leeGYPlus Hello, I also meet the same problem, **Launcher app**, **reboot device**, and mmkv version is **1.3.9**. How do you solve this problem?

mmkv rootDir: /data/user/0/com.transsion.hilauncher/files/mmkv

MemoryFile.cpp:95::open fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default], 2(No such file or directory)

MemoryFile.cpp:95::open fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default], 2(No such file or directory)

MemoryFile.cpp:220::reloadFromFile fail to open:/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default, No such file or directory

MemoryFile.cpp:95::open fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc], 2(No such file or directory)

MemoryFile.cpp:95::open fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc], 2(No such file or directory)

MemoryFile.cpp:220::reloadFromFile fail to open:/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc, No such file or directory

MemoryFile.cpp:95::open fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc], 2(No such file or directory)

MemoryFile.cpp:220::reloadFromFile fail to open:/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc, No such file or directory

<MMKV_IO.cpp:192::loadMetaInfoAndCheck> file [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default.crc] not valid

MemoryFile.cpp:95::open fail to open [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default], 2(No such file or directory)

MemoryFile.cpp:220::reloadFromFile fail to open:/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default, No such file or directory

<MMKV_IO.cpp:77::loadFromFile> file [/data/user/0/com.transsion.hilauncher/files/mmkv/mmkv.default] not valid

/cc @lingol Need more logs or support?

**Comment by lzyang187** [comment]
排查到原因是设备加密存储空间访问机制的问题，初始化MMKV时传入Context.createDeviceProtectedStorageContext()的Context即可。详见：[https://developer.android.com/privacy-and-security/direct-boot?hl=zh-cn#access](url)
