### ISSUE TITLE
MultiProcessSharedPreferences的实现为啥还需要广播协助

### ISSUE THREAD

**Issue by docwei2050** [Tencent/MMKV#1075]
如题，实现sp的多进程支持，就单独给sp开个进程A，然后其他进程操作sp中的数据就通过contentProvider从A进程中进行crud，A进程的实现里面还用广播的目的是什么呢？

**Comment by lingol** [comment]
You are making a mistake. We are NOT the developers of the MultiProcessSharedPreferences. It's here because we needed it in the benchmarks testing.
