### ISSUE TITLE
Android getString ANR

### ISSUE THREAD

**Issue by simplify20** [Tencent/MMKV#1076]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

Java

### The version of MMKV
v1.2.13

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?
In bugly ANR report there are some MMKV ANR issues，the ANR trace like below(main thread)，the device OS version is android 8，in this case we use multi process mode: 

```
| group="main" sCount=1 dsCount=0 flags=1 obj=0x74405ad0 self=0x70116a3a00
| sysTid=32058 nice=0 cgrp=default sched=0/0 handle=0x70167209b0
| state=S schedstat=( 12131294718145 71407412625 1177596 ) utm=1193505 stm=19624 core=3 HZ=100
| stack=0x7ffe825000-0x7ffe827000 stackSize=8MB
| held mutexes=
kernel: (couldn't read /proc/self/task/32058/stack)
native: #00 pc 000000000001daac /system/lib64/libc.so (syscall+28)
native: #01 pc 00000000000e1ee4 /system/lib64/libart.so (_ZN3art17ConditionVariable16WaitHoldingLocksEPNS_6ThreadE+152)
native: #02 pc 00000000004e35cc /system/lib64/libart.so (_ZN3artL12GoToRunnableEPNS_6ThreadE+440)
native: #03 pc 00000000004e3b18 /system/lib64/libart.so (_ZN3art25JniMethodEndWithReferenceEP8_jobjectjPNS_6ThreadE+32)
native: #04 pc 0000000000367fac /data/app/com.tencent.now-z0CYrusD2REhpP9cJq5bXg==/oat/arm64/base.odex (Java_com_tencent_mmkv_MMKV_decodeString__JLjava_lang_String_2Ljava_lang_String_2+204)
at com.tencent.mmkv.MMKV.decodeString(Native method)
at com.tencent.mmkv.MMKV.getString(SourceFile:990)
```

**Comment by lingol** [comment]
It's not enough to diagnose ANR issue with just the main thread call stacks. You should provide native call stacks of **all threads** that has MMKV operation. And you should **symbolized** them.

**Comment by simplify20** [comment]
I can only find MMKV operations in main thread with bugly ANR Trace information，other threads seem to have no MMKV operations. How to symbolize the MMKV native call stack，should I build MMKV in local to get symbol table then symbolize the call stack?
