### ISSUE TITLE
iOS平台 set 引发内存泄漏

### ISSUE THREAD

**Issue by GG526** [Tencent/MMKV#1081]
iOS平台通过instrument检测到内存泄漏
<img width="1671" alt="Xnip2023-05-25_17-06-16" src="https://github.com/Tencent/MMKV/assets/11623029/4dced10b-c33f-49e0-a764-75a688d6a36a">

MMKVCore/MMKV_IO.cpp 文件 572行 `[key retain];` 引起的

<img width="972" alt="Xnip2023-05-25_17-04-38" src="https://github.com/Tencent/MMKV/assets/11623029/43dd4494-cb1a-4453-9769-95147bae6d7d">

**Comment by GG526** [comment]
👌🏻

**Comment by lingol** [comment]
It's fixed in v1.3.0.

**Comment by zhinengiOS-tal** [comment]
@lingol  Hello, can you create a separate version 1.2.15 to fix this problem? Because my application supports at least iOS 10, I hope I can provide a repair version that supports at least iOS 10

**Comment by lingol** [comment]
> @lingol  Hello, can you create a separate version 1.2.15 to fix this problem? Because my application supports at least iOS 10, I hope I can provide a repair version that supports at least iOS 10

I'm afraid that is impossible. That version is two years ago and out of our official support. 
Besides, I don't have the environment for it anymore.

**Comment by zhinengiOS-tal** [comment]
> > [@lingol](https://github.com/lingol)  Hello, can you create a separate version 1.2.15 to fix this problem? Because my application supports at least iOS 10, I hope I can provide a repair version that supports at least iOS 10
> 
> I'm afraid that is impossible. That version is two years ago and out of our official support. Besides, I don't have the environment for it anymore.

Thank you for your reply. Maybe I'll try to modify and compile this project into a framework
