### ISSUE TITLE
space escaped %20

### ISSUE THREAD

**Issue by freddy24** [Tencent/MMKV#1083]
` MMKV.defaultMMKV()?.encode("authorization", “Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJFbHFTUjB”)`

use ` MMKV.defaultMMKV()?.decodeString("authorization", "")`

value become `Bearer%20eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJFbHFTUjB`

**Comment by lingol** [comment]
I can't reproduce this problem. Are you sure that escape is done by MMKV? I'm afraid not.
