### ISSUE TITLE
1.2.12版本Android 12 13 启动Native崩溃

### ISSUE THREAD

**Issue by karyYacht** [Tencent/MMKV#1084]
## Note:

升级MMKV版本启动navitve崩溃

### The version of MMKV
 v1.2.12  

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?

#00 pc 000000000005205c abort+164
#01 pc 0000000000041728 scudo::die()+8
#02 pc 0000000000041dd4 scudo::ScopedErrorReport::~ScopedErrorReport()+32
#03 pc 0000000000042008 scudo::reportInvalidChunkState(scudo::AllocatorAction, void*)+76
#04 pc 000000000004361c scudo::Allocator<scudo::AndroidConfig, &scudo_malloc_postinit>::deallocate(void*, scudo::Chunk::Origin, unsigned long, unsigned long)+308
#05 pc 0000000000017a8c /data/app/~~-2unBAU7Gq3CqIZz4EOR3g==/com.tencent.qqsports-MYJlDuMUnvdb9ACr11nhfA==/lib/arm64/libmmkv.so [arm64-v8a::ef2bb0219fced16584f07469994862b7]
#06 pc 0000000000222244 art_quick_generic_jni_trampoline+148
#07 pc 0000000000211608 nterp_helper+152
#08 pc 00000000002115a4 nterp_helper+52
#09 pc 00000000002115a4 nterp_helper+52
#10 pc 0000000000218be8 art_quick_invoke_static_stub+568
#15 pc 0000000000203994 mterp_op_invoke_static+20
java:
com.tencent.mmkv.MMKV.java.lang.String doInitialize(java.lang.String,java.lang.String,com.tencent.mmkv.MMKV$LibLoader,com.tencent.mmkv.MMKVLogLevel)(MMKV.java:196)
com.tencent.mmkv.MMKV.java.lang.String initialize(android.content.Context,java.lang.String,com.tencent.mmkv.MMKV$LibLoader,com.tencent.mmkv.MMKVLogLevel)(MMKV.java:181)
com.tencent.mmkv.MMKV.java.lang.String initialize(android.content.Context)(MMKV.java:84)

崩溃机型包括但不限于以下机型
+ Android 13 
vivo/FUNTOUCH/OriginOS Ocean V2230A arm64-v8a
+ Android 12
vivo/FUNTOUCH/OriginOS Ocean  V2166BA arm64-v8a
HuaWei/EMOTION/MagicUI_6.1.0 YOK-AN10 arm64-v8a
HuaWei/EMOTION/MagicUI_6.1.0 TFY-AN00 arm64-v8a
HuaWei/EMOTION/MagicOS_7.0.0 PAR-AL00 arm64-v8a
HuaWei/EMOTION/MagicOS_7.0.0 YOK-AN10 arm64-v8a
HuaWei/EMOTION/MagicOS_7.0.0 ALA-AN70 arm64-v8a

**Comment by lingol** [comment]
Doesn't look like MMKV's problem. Anyway, v1.2.12 is way too old, you should upgrade to the latest version first.
