### ISSUE TITLE
每次冷启动，数据都会被清除

### ISSUE THREAD

**Issue by Movingbricks** [Tencent/MMKV#1085]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> Java, And Kotlin

### The version of MMKV

> v1.2.7

### The platform of MMKV

>  Android

<img width="1418" alt="image" src="https://github.com/Tencent/MMKV/assets/22463456/41fff5a4-2bfb-421e-81c9-dfde5a8bb14a">
<img width="1153" alt="image" src="https://github.com/Tencent/MMKV/assets/22463456/4a85ba47-d9d4-4afa-b32f-26f3727c7515">

MMKV: <native-bridge.cpp:103::JNI_OnLoad> current API level = 30
MMKV: <MMKV.cpp:156::initialize> version v1.2.7 page size:4096
MMKV: <MMKV.cpp:167::initialize> armv8 AES instructions is supported
MMKV: <MMKV.cpp:175::initialize> armv8 CRC32 instructions is supported
MMKV: <MMKV.cpp:198::initializeMMKV> root dir: /data/user/0/com.app.tideswing/files/mmkv
MMKV: <MMKV.cpp:382::checkFileCRCValid> check crc [sp_cache_info] fail, crc32:440698298, m_crcDigest:29637019
MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [sp_cache_info] with 4 actual size, file size 16384, InterProcess 0, meta info version:3
MMKV: <MMKV_IO.cpp:86::loadFromFile> loading [sp_cache_info] with crc 1285129681 sequence 5 version 3
MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [sp_cache_info] with 0 key-values

**Comment by lingol** [comment]
The logs are clear as crystals: your file is corrupted. It's highly likely that you use MMKV in multiple processes without setting MULTI_PROCESS_MODE.
