### ISSUE TITLE
报红

### ISSUE THREAD

**Issue by androidTH** [Tencent/MMKV#1086]
集成1.2.16版本后import androidx.annotation.NonNull;
import androidx.annotation.Nullable;报红

**Comment by lingol** [comment]
What?

**Comment by androidTH** [comment]
集成1.2.16版本后，注解库androidx.annotation:annotation:1.4.0不起作用了。

**Comment by lingol** [comment]
Still not understand.

**Comment by lingol** [comment]
I think it's your project configuration problem as no others report it. So I will close it. You should solve it yourself.

**Comment by cjun-open** [comment]
> 集成1.2.16版本后import androidx.annotation.NonNull; import androidx.annotation.Nullable;报红

我也是，换个编译器版本可以了，原来是as 4.2.2

**Comment by cjun-open** [comment]
> > 集成1.2.16版本后import androidx.annotation.NonNull; import androidx.annotation.Nullable;报红
> 
> 我也是，换个编译器版本可以了，原来是as 4.2.2

或者还有个办法，把注解的依赖去了
api ('com.tencent:mmkv:1.2.16') {
        exclude group: 'androidx.annotation', module: 'annotation'
    }

**Comment by cjun-open** [comment]
> > > 集成1.2.16版本后import androidx.annotation.NonNull; import androidx.annotation.Nullable;报红
> > 
> > 
> > 我也是，换个编译器版本可以了，原来是as 4.2.2
> 
> 或者还有个办法，把注解的依赖去了 api ('com.tencent:mmkv:1.2.16') { exclude group: 'androidx.annotation', module: 'annotation' }

依赖了mmkv后annotation版本会变成1.5.0，里面没有Nullable
