### ISSUE TITLE
mmkv-static & mmkv 有什么不同？

### ISSUE THREAD

**Issue by Aquariusjj** [Tencent/MMKV#1089]
我正在 Android 项目中混合使用 Flutter，并且希望在 Flutter 中 使用 MMKV。但我注意到，我需要将 com.tencent:mmkv 替换为 com.tencent:mmkv-static，所以我想知道替换后是否会对原有项目产生任何影响，我需要做什么适配或改动吗？

**Comment by lingol** [comment]
It's no difference since v1.2.11. Check out the release note for more background https://github.com/Tencent/MMKV/releases/tag/v1.2.11
As a matter of fact, in the next version, the flutter version will change to `com.tencent:mmkv`.
