### ISSUE TITLE
iOS check crc failed

### ISSUE THREAD

**Issue by xuzang** [Tencent/MMKV#1090]
hello:
my app used MMKV, report error "check crc [app_version] fail, crc32:3851639965, m_crcDigest:3437992453", app_version is mmkv name，please tell me the reason why this happened.

**Comment by lingol** [comment]
It's corrupted. Likely you are using MMKV in multiple processes without setting `MULTI_PROCESS_MODE`.

**Comment by xuzang** [comment]
OK thanks

**Comment by xuzang** [comment]
I found a problem. At present，we used method  "+ (instancetype)mmkvWithID:(NSString *)mmapID rootPath:(nullable NSString *)rootPath "
this method used relatePath， but relatePath and MMKVMultiProcess mode can't be set at the same time
so，what should I do？

**Comment by xuzang** [comment]
I found a problem. At present，we used method  "+ (instancetype)mmkvWithID:(NSString *)mmapID rootPath:(nullable NSString *)rootPath "
this method used relatePath， but relatePath and MMKVMultiProcess mode can't be set at the same time
so，what should I do？

**Comment by lingol** [comment]
You should create a new issue next time, it's totally different problem.

**Comment by lingol** [comment]
As for this new problem, I suggest embedding the differences into the mmapID instead of relateivePath.

**Comment by xuzang** [comment]
OK  i will close this issue and create a new issue
