### ISSUE TITLE
MMKV allKeys return expired results

### ISSUE THREAD

**Issue by calvin2021y** [Tencent/MMKV#1096]
### The version of MMKV

1.3.0

### What's the issue?

MMKV allKeys will return expired results, test on linux(guess other platform has same problem).

**Comment by lingol** [comment]
Yes. It's a known issue. The problem is that to filter an expired key we will have to check the key's value. And that is a lot of memory operation or even disk IO operation.

**Comment by lingol** [comment]
The same problem also goes with `count()`.

**Comment by lingol** [comment]
It's supported in dev branch. You can try it out. Keep in mind that it comes with costs.

**Comment by google-mirror** [comment]
> Yes. It's a known issue. The problem is that to filter an expired key we will have to check the key's value. And that is a lot of memory operation or even disk IO operation for `allKeys()`.

What is called `expired key`?

**Comment by lingol** [comment]
It's supported in v1.3.1.
