### ISSUE TITLE
MMKV.decodeString(Native Method) Crash

### ISSUE THREAD

**Issue by BaiJacky** [Tencent/MMKV#1098]
Fatal signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x74cb2ddf74
    x0  0000000000000000  x1  00000074cb2ddf74  x2  000000000000000c  x3  0000000000000001
    x4  00000000000001ec  x5  0000008000000000  x6  6665525f656d6f48  x7  687365726665525f
    x8  000000760af32020  x9  00000074cb2ddf74  x10 0000000000000001  x11 0000000000000068
    x12 0000000000000068  x13 0000000000000000  x14 00000000000002f4  x15 18023b8c1a1d2c44
    x16 000000750f6bcc28  x17 0000007608625960  x18 0000000000000046  x19 0000007fde42fe68
    x20 0000007fde42fe50  x21 0000007fde42ff00  x22 000000750f54f3e0  x23 000000760af32020
    x24 0000007fde42fe80  x25 0000000015cc9d38  x26 000000750f54f3e0  x27 0000000012f37c68
    x28 0000000012e7be90  x29 0000007fde42fde0
    sp  0000007fde42fd40  lr  000000750f674a48  pc  000000750f674730

caused by: 
    SIGBUS(BUS_ADRERR) Nonexistent Physical Address

backtrace:
    #00 pc 000000000002d730  /data/app/com.ma.app.mall-a6NnwAOsRdkNwpPTg4v4Ww==/lib/arm64/libmmkv.so
    #01 pc 000000000002da44  /data/app/com.ma.app.mall-a6NnwAOsRdkNwpPTg4v4Ww==/lib/arm64/libmmkv.so
    #02 pc 000000000002dba0  /data/app/com.ma.app.mall-a6NnwAOsRdkNwpPTg4v4Ww==/lib/arm64/libmmkv.so
    #03 pc 000000000001eccc  /data/app/com.ma.app.mall-a6NnwAOsRdkNwpPTg4v4Ww==/lib/arm64/libmmkv.so
    #04 pc 0000000000019068  /data/app/com.ma.app.mall-a6NnwAOsRdkNwpPTg4v4Ww==/lib/arm64/libmmkv.so
    #05 pc 000000000010412c  /data/app/com.ma.app.mall-a6NnwAOsRdkNwpPTg4v4Ww==/oat/arm64/base.odex (art_jni_trampoline+188)
    #06 pc 00000000000487ac  /memfd:/jit-cache (deleted)

Java Stack:
 ⇢ main (2)  RUNNABLE
    com.tencent.mmkv.MMKV.decodeString(Native Method)
    com.tencent.mmkv.MMKV.decodeString(SourceFile:1)
    com.ma.iml.b.a(SourceFile:274)
    com.ma.iml.b.b(SourceFile:53)
    com.ma.iml.b.a(SourceFile:177)

**Comment by BaiJacky** [comment]
mmkv version com.tencent:mmkv:1.2.13

**Comment by BaiJacky** [comment]
Crash rate is 4%

**Comment by lingol** [comment]
Upgrade to the latest version first. We don't have time for several updates backwards.

**Comment by wanggang0813** [comment]
@lingol Have you seen similar problem before?

**Comment by lingol** [comment]
No.
