### ISSUE TITLE
some unused variable in aes_core.c

### ISSUE THREAD

**Issue by iOSleep** [Tencent/MMKV#11]
### The language of MMKV

Swift

### The version of MMKV

 v1.0.10

### The platform of MMKV

iOS

### The installation of MMKV

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.

![image](https://user-images.githubusercontent.com/26478957/45872319-4db7db00-bdc2-11e8-8d47-39b63942c2fa.png)

> Explain what you want by example or code **in English**.

What are these things doing？And can we remove these unused variable？

**Comment by foobra** [comment]
@lingol you can warp the code with  #pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wno-unused-variable"

...
#endif

#pragma clang diagnostic pop

**Comment by lingol** [comment]
> @lingol you can warp the code with #pragma clang diagnostic push
> #pragma clang diagnostic ignored "-Wno-unused-variable"
> 
> ...
> #endif
> 
> #pragma clang diagnostic pop

Fixed by pr [pr#19](https://github.com/Tencent/MMKV/pull/19).
