### ISSUE TITLE
Why call loadFromFile() in clearAll()

### ISSUE THREAD

**Issue by xylitolhub** [Tencent/MMKV#110]
### The language of MMKV

> Java

### The version of MMKV

> v1.0.12

### The platform of MMKV

> Android

### The installation of MMKV

> AAR

### What's the issue?

I calling clearAll() just want to remove the whole mmkv file, but why call loadFromFile() in the implementation of clearAll()? It will remain a file of default size which is useless.

```
void MMKV::clearAll() {
    MMKVInfo("cleaning all key-values from [%s]", m_mmapID.c_str());
    SCOPEDLOCK(m_lock);
    SCOPEDLOCK(m_exclusiveProcessLock);

    if (m_needLoadFromFile && !m_isAshmem) {
        removeFile(m_path.c_str());
        loadFromFile(); <=========================== here, it is better if I remove it?
        return;
    }
... ...
    clearMemoryState();
    loadFromFile(); <====================== and here
}
```

**Comment by lingol** [comment]
What you need is something like `removeFile`. MMKV currently doesn't support such feature.

**Comment by xylitolhub** [comment]
But why you call removeFile(m_path.c_str())  here?

**Comment by lingol** [comment]
> But why you call removeFile(m_path.c_str()) here, if you just clear cache?

It's simpler. And I'm little lazy.

**Comment by xylitolhub** [comment]
You seem not get my meaning... What I said is that you should not unlink the file, just clearing memory is enough. Right?

**Comment by lingol** [comment]
> You seem not get my meaning... What I said is that you should not unlink the file, just clearing memory is enough. Right?

Yep. But the file size won't trim.
