### ISSUE TITLE
I'm having java.lang.UnsatisfiedLinkError on Android devices with API level 31

### ISSUE THREAD

**Issue by zuosongfeng** [Tencent/MMKV#1101]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

>Java

### The version of MMKV

> e.g. v1.2.14 
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

Android

### The installation of MMKV

>  Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
java.lang.UnsatisfiedLinkError	dlopen failed: "/data/app/~~whuzzQBp33nBO2_el2JKmA==/com.android.vivo.tws.vivotws-UWTFoxUP-6BZxJ4OjDRZ9w==/lib/arm64/libmmkv.so" has bad ELF magic: 00000000
Runtime.java	1077
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~whuzzQBp33nBO2_el2JKmA==/com.android.vivo.tws.vivotws-UWTFoxUP-6BZxJ4OjDRZ9w==/lib/arm64/libmmkv.so" has bad ELF magic: 00000000
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1656)
	at com.tencent.mmkv.MMKV.i(MMKV.java:2)
	at com.tencent.mmkv.MMKV.p(MMKV.java:5)
	at com.tencent.mmkv.MMKV.o(MMKV.java:3)

**Comment by lingol** [comment]
We don't accept issues on `UnsatisfiedLinkError` anymore. It's clearly not a library dev's problem.
