### ISSUE TITLE
在安卓上当卸载掉app 重新安装时之前app的mmkv数据又回来了

### ISSUE THREAD

**Issue by lhjandroid** [Tencent/MMKV#1104]
version: 1.2.16
app里通过mmkv保存了一些数据我卸载了app 再次安装时旧数据又回来了。不知道这是不是mmkv的特性，且文件创建的时间似乎不太对。
![image](https://github.com/Tencent/MMKV/assets/10664616/f93e5041-b593-40d2-90f5-210cf2e64354)

**Comment by lingol** [comment]
It's not MMKV's intention. If the files are still there, you can read them back.

**Comment by lhjandroid** [comment]
> It's not MMKV's intention. If the files are still there, you can read them back.

但是我不想这些数据存在，造成了一点点困扰所以提了下问题

**Comment by lingol** [comment]
Then you should complain to Android.

**Comment by gangoogle** [comment]
我也有这个问题，现在唯一的解决方式就是给mmkv换一个实例化名称。否则每次app卸载重装后，都会默认还原成之前某一个版本的数据。。

**Comment by zjxckangkang** [comment]
这个问题是allowBackup要设置为false，参考以前的issues，https://github.com/Tencent/MMKV/issues/673
