### ISSUE TITLE
对go支持的疑问

### ISSUE THREAD

**Issue by wustwg** [Tencent/MMKV#1105]
你好，
我看了go支持的介绍页面，其中对系统的要求是 Linux或unix， 那Windows是否不支持？
自己用cmake编译 我很担心可能编译出来的库会缺失，最终在其他人的电脑上无法运行，为什么不能直接放在go仓库中自动下载编译？
麻烦有空时做个解答，谢谢啦~

**Comment by lingol** [comment]
I don't think there is much serious dev using Golang on Windows. So, No, we will not add official support for Windows.
