### ISSUE TITLE
壁纸类app使用mmkv重启后会导致数据丢失

### ISSUE THREAD

**Issue by rainchen1024** [Tencent/MMKV#1106]
## Note:
我开发的一个壁纸类app，使用mmkv替换的sp，重启后会导致数据丢失，切换回sp后是正常的

### The language of MMKV
> Kotlin

### The version of MMKV
> v1.3.0

### The platform of MMKV
> Android

### The installation of MMKV
> Maven,

**Comment by lingol** [comment]
This is a weekly duplicated issue. 
It's highly likely you are using MMKV in multi-process without setting MULTI_PROCESS_MODE.

**Comment by rainchen1024** [comment]
试过设置 MULTI_PROCESS_MODE 了，也不行

**Comment by lingol** [comment]
Well, what are the logs of MMKV before & after your restart?
