### ISSUE TITLE
捕获的异常提示so找不到

### ISSUE THREAD

**Issue by wjianchen13** [Tencent/MMKV#1107]
android使用mmkv，版本1.3.0，线上捕获的异常提示so找不到
Fatal Exception: java.lang.UnsatisfiedLinkErrordlopen failed: library "libmmkv.so" not found
java.lang.Runtime.loadLibrary0(Runtime.java:1087)
java.lang.System.loadLibrary (System.java:1664)
com.tencent.mmkv.MMKV.a (MMKV.java:211)
com.tencent.mmkv.MMKV.a (MMKV.java:1 93)
com.tencent.mmkv.MMKV.a(MMKV.java:86)
com.xiaofeng.xchat_framework.utils.r.a(MMKVUtils.java:30)
com.mhyj.kc.XChatApplication.a (xchatApplication.java:137)
com.mhyj.kc.ui.launch.activity.SplashMivpActivity.a (SplashMvpActivity.java:97)
com.mhyj.kc.ui.launch.activity.SplashMvpActivity.onCreate (SplashMvpActivity.java:77)android.app.Activity.performCreate (Activity.java:8151)
com.android.internal.os.Zygotelnit.main (Zygotelnit.java:1049)

手机 CPH2239 android 11

**Comment by lingol** [comment]
We don't accept unsatisfied link errors anymore. It's clearly not a library's problem. You should complain about it to Android/Google.
