### ISSUE TITLE
mmkv崩溃

### ISSUE THREAD

**Issue by jiangsai** [Tencent/MMKV#1108]
![截图](https://github.com/Tencent/MMKV/assets/19963883/5128f1d3-c799-41a3-8f36-7a76bc19f28e)
存入的对象，在取出来的时候不完整了，然后报错了

**Comment by lingol** [comment]
It's not a valid UTF-8 when you store it in MMKV. Garbage in, garbage out.

**Comment by lingol** [comment]
Besides, your version is too old, upgrade it first.

**Comment by jiangsai** [comment]
感觉不是吧，我存的的是json，但是看日志只输出了一部分，不是一个完整的json，是不是数据丢失了

**Comment by kaitian521** [comment]
> 
怎么知道不完整的？ logcat有1024字节的限制，可能需要分段打印出来。 试试 encodeBytes instead of encodeString

**Comment by jiangsai** [comment]
你看我的图，在我用红框的地方，身份证那个字段完直接就到了下一个对象了，并不是logcat限制的问题

**Comment by jiangsai** [comment]
那个idNumber，后面正常应该跟着loginIp，但是日志看是直接到了一个对象的头，就很奇怪

**Comment by lingol** [comment]
Don't spam here. I have already told you to upgrade it first. Until then, there's nothing to discuss.

**Comment by jiangsai** [comment]
![image](https://github.com/Tencent/MMKV/assets/19963883/ab9b5044-64c9-4d20-a59a-3983a00e35a0)
我觉得不是utf-8的问题，我直接写了代码测试了
