### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by Bertkiing** [Tencent/MMKV#111]
### The language of MMKV

> Kotlin

### The version of MMKV

>  v1.0.10

### The platform of MMKV

> Android

### Reports
![report](https://user-images.githubusercontent.com/19733128/48324191-bd33a380-e66a-11e8-9275-2c94ce3d32d8.jpg)

**Comment by lingol** [comment]
Can you provider a symbolized crash report? I need exact code line of MMKV triggering the problem.
It's hard to diagnose the problem with only little info in your logcat snip.

Also, you can upgrade MMKV to v1.0.12, it's newer.

**Comment by lingol** [comment]
Or you can provide a reproducible MMKV file and demo project for us to investigate. guoling@tencent.com

**Comment by lingol** [comment]
Closing for no more detail information.

**Comment by Bertkiing** [comment]
I am sorry because so busy recently...
