### ISSUE TITLE
MMKV.initialize 无法在isolate初始化

### ISSUE THREAD

**Issue by HXiaoMing** [Tencent/MMKV#1112]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

flutter

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

1.3.0

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

mmkv: ^1.3.0

### What's the issue?
flutter3.7之后可以在isolate使用platform channel，想在isolate使用mmkv，但是初始化时候报错了，
因为MMKV.initialize调用了WidgetsFlutterBinding.ensureInitialized();
导致报错UI actions are only available on root isolate
```
MMKV.initialize
```

> Post the outputs or screenshots for errors.

E/Isolate_grpc( 6963): [, , 0]:split-0 onIsolateErr [UI actions are only available on root isolate., #0      FfiTrampoline____nativeSetNeedsReportTimings$Method$FfiNative$Ptr (dart:ffi)
E/Isolate_grpc( 6963): #1      PlatformDispatcher.__nativeSetNeedsReportTimings (dart:ui/platform_dispatcher.dart:546:24)
E/Isolate_grpc( 6963): #2      PlatformDispatcher._nativeSetNeedsReportTimings (dart:ui/platform_dispatcher.dart:543:52)
E/Isolate_grpc( 6963): #3      PlatformDispatcher.onReportTimings= (dart:ui/platform_dispatcher.dart:535:29)
E/Isolate_grpc( 6963): #4      SchedulerBinding.addTimingsCallback (package:flutter/src/scheduler/binding.dart:308:26)
E/Isolate_grpc( 6963): #5      SchedulerBinding.initInstances (package:flutter/src/scheduler/binding.dart:240:7)
E/Isolate_grpc( 6963): #6      ServicesBinding.initInstances (package:flutter/src/services/binding.dart:37:11)
E/Isolate_grpc( 6963): #7      PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:20:11)
E/Isolate_grpc( 6963): #8      SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:18:11)
E/Isolate_grpc( 6963): #9      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:30:11)
E/Isolate_grpc( 6963): #10     WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:263:11)
E/Isolate_grpc( 6963): #11     new BindingBase (package:flutter/src/foundation/binding.dart:151:5)
E/Isolate_grpc( 6963): #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
E/Isolate_grpc( 6963): #13     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
E/Isolate_grpc( 6963): #14     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
E/Isolate_grpc( 6963): #15     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
E/Isolate_grpc( 6963): #16     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding (package:flutter/src/widgets/binding.dart)
E/Isolate_grpc( 6963): #17     new _WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
E/Isolate_grpc( 6963): #18     new _Widgets
E/Isolate_grpc( 6963): [, , 0]:split-1 ndingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
E/Isolate_grpc( 6963): #19     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
E/Isolate_grpc( 6963): #20     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:1306:7)
E/Isolate_grpc( 6963): #21     MMKV.initialize (package:mmkv/mmkv.dart:160:27)

> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
You should only initialize MMKV in the main thread/isolate, it's required.
