### ISSUE TITLE
close implementation are different between iOS and Android

### ISSUE THREAD

**Issue by kaitian521** [Tencent/MMKV#1115]
### The language of MMKV
JAVA

### The version of MMKV
1.3.0

### The platform of MMKV
Android

### The installation of MMKV
Maven

### What's the issue?

iOS:
https://github.com/Tencent/MMKV/blob/dev/iOS/MMKV/MMKV/libMMKV.mm#L302
```
- (void)close {
    SCOPED_LOCK(g_lock);
    MMKVInfo("closing %@", m_mmapID);

    [g_instanceDic removeObjectForKey:m_mmapKey];
}
```

Android:
https://github.com/Tencent/MMKV/blob/272e5aa1fb57b4ee8cc0ff37e70b7885d99832a7/Android/MMKV/mmkv/src/main/cpp/native-bridge.cpp#L884
```
MMKV_JNI void close(JNIEnv *env, jobject instance) {
    MMKV *kv = getMMKV(env, instance);
    if (kv) {
        kv->close();
        env->SetLongField(instance, g_fileID, 0);
    }
}
```

Golang
```
MMKV_EXPORT void mmkvClose(void *handle) {
    MMKV *kv = static_cast<MMKV *>(handle);
    if (kv) {
        kv->close();
    }
}
```

Shall iOS add some code like this?
```
- (void)close {
    SCOPED_LOCK(g_lock);
    MMKVInfo("closing %@", m_mmapID);

    if (m_mmkv) {
        m_mmkv->close();
        m_mmkv = nullptr;
    }
    [g_instanceDic removeObjectForKey:m_mmapKey];
}
```

I am working on the last issue, when adding some tests, find that iOS close function is different from Android and Golang.
Please have a look
Thanks

**Comment by lingol** [comment]
No. Android doesn't have a cache dictionary in JNI wrapper so no need to remove it on close(). If you look deeper inside you will see why.

**Comment by kaitian521** [comment]
```
    auto mmkv2 = [MMKV mmkvWithID:@"expectedCapacityTest2"];
    [mmkv2 close];
    
    mmkv2 = [MMKV mmkvWithID:@"expectedCapacityTest2"
```
code above crashed in my Mac

So what can I do if I want to close a MMKV in OC?
