### ISSUE TITLE
InterProcessLock.cpp:137::platformUnLock error when calling allKeys()

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#1117]
An MMKV is created with MULTI_PROCESS_MODE and I can see the following error from the LogCat when calling MMKV.allKeys()
**_<InterProcessLock.cpp:137::platformUnLock> fail to unlock fd=94, ret=-1, error:Bad file descriptor_**

This problem can be reproduced by the attached sample app.
[test_mmkv_multi_process.zip](https://github.com/Tencent/MMKV/files/12143586/test_mmkv_multi_process.zip)

Please read `test_mmkv_multi_process/readme.txt` for how to reproduce it and get more detailed information.

* MMKV either 1.2.16 or 1.3.0 has the same error
* no such error when using MMKV 1.2.15
* no error on Android 6.x/Android 8.x emulator but we can see the error on
  . Pixel 3 XL with Android 12
  . Android 13 emulator

**Comment by lingol** [comment]
It's confirmed. This is a bug introduced by commit 7211057b80ddfa6bc5d37844fb22c1ed992015f3, at MMKV v1.2.16. 
Will fix soon.

**Comment by lingol** [comment]
It's fixed in the dev branch. This is a critical issue, a hotfix version will come out soon.

**Comment by lingol** [comment]
It's fixed in v1.3.1.
