### ISSUE TITLE
some Android devices might not have access permission on parent directory

### ISSUE THREAD

**Issue by memoryoff** [Tencent/MMKV#1119]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

 源码编译并在安卓真机上跑

### The version of MMKV

v1.2.16

### The platform of MMKV

> Android

### The installation of MMKV

> Git clone

### What's the issue?
已经打开了所有权限，但在某款手机上初始化返回false

![image](https://github.com/Tencent/MMKV/assets/6302224/02683669-7659-4d06-9171-924aea3f6f36)
![image](https://github.com/Tencent/MMKV/assets/6302224/0d94a0d8-e15a-427d-ba59-be6e58111c82)

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
Does your App have write permission on that location?

**Comment by memoryoff** [comment]
> Does your App have write permission on that location?

有权限

**Comment by lingol** [comment]
So did it eventually succeed in creating a MMKV instance? What's do you complain about? I'm confused.

**Comment by microIBM** [comment]
我也遇到类似的问题，在Android NDK创建MmkvMgr实例的时候，传入类似的路径/storage/emulated/0/Android/data/com.xxxx.appp/files/mmkv，在mkPath(）函数中遍历路径创建目录，当循环到/storage/emulated这个系统目录stat()函数调用失败。如果强制循环遍历/storage/emulated/0目录，stat()又可以调用成功。
目前方案是强制循环遍历到路径结束。
![image](https://github.com/Tencent/MMKV/assets/2402651/1d6134a7-028b-4d25-affd-cc18b63e1d3b)

**Comment by lingol** [comment]
It's fixed in dev branch.

**Comment by lingol** [comment]
It's fixed in v1.3.1.
