### ISSUE TITLE
avgItemSize is more larger than its real value & avoid of file expand when inserting k-v for the first time

### ISSUE THREAD

**Issue by kaitian521** [Tencent/MMKV#1120]
### The language of MMKV
JAVA

### The version of MMKV
1.3.0

### The platform of MMKV
Android

### The installation of MMKV
Maven

### What's the issue?

I am working on last  pr, but find another problem

```
    size_t lenNeeded = sizeOfDic + Fixed32Size + newSize;
    size_t dicCount = m_crypter ? m_dicCrypt->size() : m_dic->size();
    size_t avgItemSize = lenNeeded / std::max<size_t>(1, dicCount);
    size_t futureUsage = avgItemSize * std::max<size_t>(8, (dicCount + 1) / 2);
    // 1. no space for a full rewrite, double it
    // 2. or space is not large enough for future usage, double it to avoid frequently full rewrite
    if (lenNeeded >= fileSize || (lenNeeded + futureUsage) >= fileSize) {
        size_t oldSize = fileSize;
        do {
            fileSize *= 2;
        } while (lenNeeded + futureUsage >= fileSize);
```

-  the `avgItemSize` is more bigger that its real value
分母少了个1，极端情况会导致误差很大

- There is a wasting file expand if inserting key-value for the first time
假如dict是0，即文件默认4096字节；第一次插入1000字节(4096/8左右就会引发扩容)的数据，就会引发扩容，此时其实没必要扩容

修复之后，卡顿概率可能会变小。请review这个pr

谢谢

**Comment by kaitian521** [comment]
@lingol please look at this issue if having time

**Comment by lingol** [comment]
Noted.
