### ISSUE TITLE
MMKVHandler使用疑问

### ISSUE THREAD

**Issue by lvjiancong** [Tencent/MMKV#1123]
你好，我在初始化的时候，MMKVHandler的使用方式如下:
MMKV.initialize(App.getBaseContext(), new StorageBuilder().optSubDir(CommonDir.MMKV).create().getAbsolutePath(), null, MMKVLogLevel.LevelNone, new MMKVHandler() {
                @Override
                public MMKVRecoverStrategic onMMKVCRCCheckFail(String mmapID) {
                    return MMKVRecoverStrategic.OnErrorDiscard;
                }

                @Override
                public MMKVRecoverStrategic onMMKVFileLengthError(String mmapID) {
                    return MMKVRecoverStrategic.OnErrorDiscard;
                }

                @Override
                public boolean wantLogRedirecting() {
                    return false;
                }

                @Override
                public void mmkvLog(MMKVLogLevel level, String file, int line, String function, String message) {
                }
            });
crc校验失败的时候采用MMKVRecoverStrategic.OnErrorDiscard，如果出现校验失败了，是只有当次的值的存取会被丢弃吗？我还需要做什么其他处理吗？

**Comment by lingol** [comment]
The default behavior is discard. So you don't need to worry about your implementation of MMKVHandler.
