### ISSUE TITLE
v1.0.23 remove a large number of keys and trim, but the size did not change.

### ISSUE THREAD

**Issue by yetwish** [Tencent/MMKV#1125]
### The language of MMKV
Java

### The version of MMKV
v1.0.23

### The platform of MMKV
Android

### What's the issue?
I found that a significant number of unnecessary key-value pairs have been written into my program, causing the size of my MMKV to grow to 128MB. I want to clear the invalid data and free up storage while retaining useful information. Therefore, I removed irrelevant keys and called the trim operation. However, I noticed that the mmkv.totalsize did not change before and after, and even after restarting my app, it still occupies a large amount of memory. I have successfully removed the keys when checking the key count. Any suggestions for resolving this issue?

using MULTI_PROCESS_MODE.

### some code and log

```
        int beforeCount =  mmkv.allKeys().length;
        long beforeSize = mmkv.totalSize();
        try (Closeable c = MmkvRepo.withBatch()) {
              //remove keys
        } catch (Exception ignore) {
            Log.e(TAG, "mmkv batch error ", ignore);
        } finally {
            MmkvRepo.getMmkv().trim();
        }
        int afterCount = mmkv.allKeys().length;
        long afterSize = mmkv.totalSize();

        Map<String, String> params = new ArrayMap<>();
        params.put("size", StringUtils.catWithSep("#", beforeSize, afterSize));
        params.put("count", StringUtils.catWithSep("#", beforeCount, afterCount));
        Log.i(TAG, "mmkv  params = " + params);
``` 

log : MmkvChecker: mmkv params = {size=134217728#134217728, count=6860#355}

**Comment by lingol** [comment]
What does MMKV say in the logs when you call `trim()`?

**Comment by yetwish** [comment]
08-02 09:56:36.786364  2611  3505 I MMKV    : <MMKV.cpp:335::loadFromFile> loading [persona] with 112288018 size in total, file size is 134217728, InterProcess 1
08-02 09:56:37.027672  2611  3505 I MMKV    : <MMKV.cpp:359::loadFromFile> loading [persona] with crc 4066847643 sequence 51 version 2
08-02 09:56:37.673768  2611  3505 I MMKV    : <MMKV.cpp:380::loadFromFile> loaded [persona] with 364 values
08-02 09:56:37.674131  2611  3505 I MMKV    : <MMKV.cpp:591::clearMemoryState> clearMemoryState [persona]
08-02 09:56:37.697803  2611  3505 I MMKV    : <MMKV.cpp:652::trim> prepare to trim persona
08-02 09:56:37.697859  2611  3505 I MMKV    : <MMKV.cpp:335::loadFromFile> loading [persona] with 112288018 size in total, file size is 134217728, InterProcess 1
08-02 09:56:37.836304  2611  3505 I MMKV    : <MMKV.cpp:359::loadFromFile> loading [persona] with crc 4066847643 sequence 51 version 2
08-02 09:56:38.357592  2611  3505 I MMKV    : <MMKV.cpp:380::loadFromFile> loaded [persona] with 364 values
08-02 09:56:39.237123  2611  3505 I MMKV    : <MMKV.cpp:671::trim> there's no need to trim persona with size 134217728, actualSize 112288018
08-02 09:56:39.417513  2611  3505 I MMKV    : <MMKV.cpp:591::clearMemoryState> clearMemoryState [persona]
08-02 09:56:39.482025  2611  3505 I MMKV    : <MMKV.cpp:335::loadFromFile> loading [persona] with 112288018 size in total, file size is 134217728, InterProcess 1
08-02 09:56:39.653513  2611  3505 I MMKV    : <MMKV.cpp:359::loadFromFile> loading [persona] with crc 3491192241 sequence 52 version 2
08-02 09:56:40.481324  2611  3505 I MMKV    : <MMKV.cpp:380::loadFromFile> loaded [persona] with 364 values
08-02 09:56:40.481510  2611  3505 I MMKV    : <MMKV.cpp:591::clearMemoryState> clearMemoryState [persona]
08-02 09:56:40.494093  2611  3505 I MMKV    : <MMKV.cpp:335::loadFromFile> loading [persona] with 112288018 size in total, file size is 134217728, InterProcess 1
08-02 09:56:40.633404  2611  3505 I MMKV    : <MMKV.cpp:359::loadFromFile> loading [persona] with crc 3491192241 sequence 52 version 2
08-02 09:56:41.254756  2611  3505 I MMKV    : <MMKV.cpp:380::loadFromFile> loaded [persona] with 364 values
08-02 09:56:41.254871  2611  3505 I MMKV    : <MMKV.cpp:591::clearMemoryState> clearMemoryState [persona]
08-02 09:56:41.264997  2611  3505 I MMKV    : <MMKV.cpp:335::loadFromFile> loading [persona] with 112288018 size in total, file size is 134217728, InterProcess 1
08-02 09:56:41.393518  2611  3505 I MMKV    : <MMKV.cpp:359::loadFromFile> loading [persona] with crc 3491192241 sequence 52 version 2
08-02 09:56:41.891485  2611  3505 I MMKV    : <MMKV.cpp:380::loadFromFile> loaded [persona] with 364 values
08-02 09:56:41.891586  2611  3505 I MMKV    : <MMKV.cpp:591::clearMemoryState> clearMemoryState [persona]
08-02 09:56:41.897414  2611  3505 I MMKV    : <MMKV.cpp:335::loadFromFile> loading [persona] with 112288018 size in total, file size is 134217728, InterProcess 1
08-02 09:56:41.997792  2611  3505 I MMKV    : <MMKV.cpp:359::loadFromFile> loading [persona] with crc 3491192241 sequence 52 version 2
08-02 09:56:42.511945  2611  3505 I MMKV    : <MMKV.cpp:380::loadFromFile> loaded [persona] with 364 values
08-02 09:56:42.512144  2611  3505 I MMKV    : <MMKV.cpp:591::clearMemoryState> clearMemoryState [persona]
08-02 09:56:42.518806  2611  3505 I MMKV    : <MMKV.cpp:335::loadFromFile> loading [persona] with 112288018 size in total, file size is 134217728, InterProcess 1
08-02 09:56:42.640496  2611  3505 I MMKV    : <MMKV.cpp:359::loadFromFile> loading [persona] with crc 3491192241 sequence 52 version 2
08-02 09:56:43.266285  2611  3505 I MMKV    : <MMKV.cpp:380::loadFromFile> loaded [persona] with 364 values
08-02 09:56:43.267165  2611  3505 I MMKV    : <MMKV.cpp:591::clearMemoryState> clearMemoryState [persona]
08-02 09:56:43.273300  2611  3505 I MMKV    : <MMKV.cpp:335::loadFromFile> loading [persona] with 112288018 size in total, file size is 134217728, InterProcess 1
08-02 09:56:43.403369  2611  3505 I MMKV    : <MMKV.cpp:359::loadFromFile> loading [persona] with crc 3491192241 sequence 52 version 2
08-02 09:56:44.197125  2611  3505 I MMKV    : <MMKV.cpp:380::loadFromFile> loaded [persona] with 364 values
08-02 09:56:44.197340  2611  3505 I MMKV    : <MMKV.cpp:591::clearMemoryState> clearMemoryState [persona]
08-02 09:56:44.732849  2611  3505 I MMKV    : <MMKV.cpp:335::loadFromFile> loading [persona] with 112288018 size in total, file size is 134217728, InterProcess 1
08-02 09:56:45.151929  2611  3505 I MMKV    : <MMKV.cpp:359::loadFromFile> loading [persona] with crc 3491192241 sequence 52 version 2
08-02 09:56:48.993812  2611  3505 I MMKV    : <MMKV.cpp:380::loadFromFile> loaded [persona] with 364 values
08-02 09:56:48.994020  2611  3505 I MMKV    : <MMKV.cpp:591::clearMemoryState> clearMemoryState [persona]
08-02 09:56:49.008999  2611  3505 I MMKV    : <MMKV.cpp:335::loadFromFile> loading [persona] with 112288018 size in total, file size is 134217728, InterProcess 1
08-02 09:56:49.738155  2611  3505 I MMKV    : <MMKV.cpp:359::loadFromFile> loading [persona] with crc 3491192241 sequence 52 version 2
08-02 09:56:52.178007  2611  3505 I MMKV    : <MMKV.cpp:380::loadFromFile> loaded [persona] with 364 values
08-02 09:56:52.178329  2611  3505 I MMKV    : <MMKV.cpp:591::clearMemoryState> clearMemoryState [persona]
08-02 09:56:52.215866  2611  3505 I MMKV    : <MMKV.cpp:335::loadFromFile> loading [persona] with 112288018 size in total, file size is 134217728, InterProcess 1
08-02 09:56:52.515382  2611  3505 I MMKV    : <MMKV.cpp:359::loadFromFile> loading [persona] with crc 3491192241 sequence 52 version 2
08-02 09:56:53.143401  2611  3505 I MMKV    : <MMKV.cpp:380::loadFromFile> loaded [persona] with 364 values
08-02 09:56:53.143509  2611  3505 I MMKV    : <MMKV.cpp:591::clearMemoryState> clearMemoryState [persona]

**Comment by lingol** [comment]
>08-02 09:56:37.673768 2611 3505 I MMKV : MMKV.cpp:380::loadFromFile loaded [persona] with 364 values
>08-02 09:56:37.697803 2611 3505 I MMKV : MMKV.cpp:652::trim prepare to trim persona
>08-02 09:56:38.357592 2611 3505 I MMKV : MMKV.cpp:380::loadFromFile loaded [persona] with 364 values
>08-02 09:56:39.237123 2611 3505 I MMKV : MMKV.cpp:671::trim there's no need to trim persona with size 134217728, actualSize 112288018

I don't think you have ever removed any keys.

**Comment by lingol** [comment]
Or in other words, the **364** keys remaining consume that much data. Aka you have not removed the largest key-values.

**Comment by yetwish** [comment]
The above code deleted lots of keys, reducing the count from 6860 to 355, but i didn't save the log.

I don't think 364 keys consume that much data. 
Is it possible that there might be an error in the calculation of the **actualSize** ?

**Comment by lingol** [comment]
You can check each key-value's size by calling getValueSize().

**Comment by lingol** [comment]
Another way is to force a full write back to make sure no duplicate keys in the file. To do that you need to remove **two** or more keys at once, by calling removeValuesForKeys(). Then you can call trim().

**Comment by yetwish** [comment]
I printed all the key-value with this format:
one line for a key-value as **key, valueSize = value (empty when value type is not string)**

such as 
```
currentCityChangeFlag, 1  =  
request_success_time, 6  =  
last_request_time, 6  =  
```

However the result shows there are something strange like this:
<img width="1092" alt="image" src="https://github.com/Tencent/MMKV/assets/8563392/6040f047-7fb7-4db1-a8d3-4dc96109d7e7">

I thought maybe there was something wrong with this file that caused this problem?

**Comment by lingol** [comment]
Looks like it's once corrupted, and the recovery logic doesn't work very well, leaving some very large key values.

**Comment by yetwish** [comment]
That makes sense. 

I found that the latest version is already 1.3.0. Will updating to the new version be better for my situation?
Sometimes we write some large key-values, or any suggestions？

**Comment by lingol** [comment]
>Will updating to the new version be better for my situation?

No. But it's no harm in doing so.
>Sometimes we write some large key-values, or any suggestions？

Keep them in separate MMKV instances, or don't use MMKV to store them at all.

**Comment by yetwish** [comment]
> Keep them in separate MMKV instances

Already done.

Thanks.
