### ISSUE TITLE
iOS17 initializeMMKV 崩溃

### ISSUE THREAD

**Issue by migo100** [Tencent/MMKV#1127]
### The language of MMKV
> Objective-C

### The version of MMKV
> 1.3.0

### The platform of MMKV
> iOS

### The installation of MMKV
> Cocoapods

### What's the issue?
> Within the didFinishLaunchingWithOptions method call [MMKV initializeMMKV: nil]; The EXC_BAD_ACCESS problem occurred.
> In line 73 of libMMKV.mm: g_lock = new mmkv::ThreadLock();

### What's the log of MMKV when that happened?
> Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

**Comment by lingol** [comment]
There's simply too little info. Please provide full call stacks & logs from MMKV.

**Comment by migo100** [comment]
XCode version: 15.0 beta 5
iOS version: iOS 14.4
![image](https://github.com/Tencent/MMKV/assets/141730146/ab026dfb-7c51-49f4-9abc-d80413e1c3fb)

**Comment by lingol** [comment]
> There's simply too little info. Please provide full call stacks & logs from MMKV.

Again.

**Comment by lingol** [comment]
Closed due to inactive.

**Comment by lingol** [comment]
#1161

**Comment by humoroutlaw** [comment]
Not working when Podfile use_frameworks!
