### ISSUE TITLE
iOS mode is MMKVMultiProcess, found some problems

### ISSUE THREAD

**Issue by xuzang** [Tencent/MMKV#1128]
received error log

1. fail to lock fd=11, ret=-1, error:Operation not supported
2. fail to try unlock first fd=8, ret=-1, error:Operation not supported
3. fail to recover shared-lock fd=12, ret=-1, error:Operation not supported
4.  fail to unlock fd=54, ret=-1, error:Bad file descriptor

I use it like this，eg:
   MMKV *kv  = [MMKV mmkvWithID: [self mmkvID] mode:MMKVMultiProcess];
   [kv setString: "value" forKey: "key"];

what should I do？

**Comment by lingol** [comment]
There's something wrong with your App or your device's filesystem. There's nothing we can do for you.

**Comment by xuzang** [comment]
Error rate is 0.25  is too high

previous，we used MMKVSingleProcess, fewer problems，most is ’check crc failed‘，error rate is 0.002
now. we only change mode but error surge，App Code No Change.

can you provide some troubleshooting directions?

**Comment by lingol** [comment]
Well, have you configured AppGroup properly? https://github.com/Tencent/MMKV/wiki/iOS_tutorial#configuration

**Comment by xuzang** [comment]
Init Method 
 NSString *documentsDirectory = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES).firstObject;
    [MMKV initializeMMKV:nil groupDir:[NSString stringWithFormat:@"%@/ZebraStore", documentsDirectory] logLevel:MMKVLogInfo];

**Comment by lingol** [comment]
You are using it the wrong way. You should configure your App with App Group access. And configure MMKV with that group ID.
Please do as the wiki told you to do.

**Comment by lingol** [comment]
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_application-groups?language=objc

**Comment by xuzang** [comment]
thanks ！

I modify it
