### ISSUE TITLE
Android多进程问题，

### ISSUE THREAD

**Issue by ShiZhuang1993** [Tencent/MMKV#1130]
MMKV mmkv = MMKV.mmkvWithID("shared_data", MMKV.MULTI_PROCESS_MODE);
            mmkv.encode("sssssss", "111111111");
            String value = mmkv.decodeString("sssssss", "");
            Log.e("===========", value);
同样的代码在两个APP中使用，一个是读写，一个只读，但是只读的这个APP返回的null,求大佬 我这步骤差哪里了

**Comment by ShiZhuang1993** [comment]
> Your two Apps must have the same permission on **the same path**. You can check the **logs** from MMKV in **logcat** to verify that they have the **same path** for MMKV.

你好，路径看了只是包名不一样，难道要设置一样的包名吗？有没有例子给看看 谢谢！

**Comment by lingol** [comment]
You must have the exactly **same absolute path**. If your two Apps can't open the same file, there's nothing MMKV could do more than that.
As for your request for examples, I suggest you Google **how to make two Apps access the same file**.
