### ISSUE TITLE
iOS MMKVSingleProcess or MMKVMultiProcess

### ISSUE THREAD

**Issue by xuzang** [Tencent/MMKV#1133]
I have two questions that I would like to ask.

1. We don’t have the need for shared storage between our App and Extension. Do we still need to use 'MMKVMultiProcess'?
2. We previously used 'MMKVSingleProcess' and encountered 'check crc' errors. Will using 'MMKVMultiProcess' effectively reduce these types of errors?

**Comment by lingol** [comment]
>We don’t have the need for shared storage between our App and Extension. Do we still need to use 'MMKVMultiProcess'?

No, you don't need it if not shared between processes.

>We previously used 'MMKVSingleProcess' and encountered 'check crc' errors. Will using 'MMKVMultiProcess' effectively reduce these types of errors?

No, it has nothing todo with reducing file corruption. You don't need it if not shared between processes.

**Comment by xuzang** [comment]
I see 
thanks
