### ISSUE TITLE
Parcelable

### ISSUE THREAD

**Issue by jacksPeak** [Tencent/MMKV#114]
是否支持 Parcelable 接口的持久化？

**Comment by lingol** [comment]
Not yet. Volunteers are welcome to implement this feature.

**Comment by jacksPeak** [comment]
经过测试将 Parcelable 转换成 byte 数组后实现了 mmkv 存储

**Comment by lingol** [comment]
Supported with this [commit](https://github.com/Tencent/MMKV/commit/0c61567c920501017c975a2ceed350e3584ba7cb), hopefully will come out this week.

**Comment by lingol** [comment]
Released with v1.0.14.
