### ISSUE TITLE
The code size of the Maven version is much bigger than what we build with Github source files

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#1145]
I manually build the mmkv 1.3.1 library with github's source files and found the code size of mmkv.so is much smaller than the code size that we get from Maven. The other mmkv versions have the same issue.

Here shows you the code size that I built with github source files:
<img width="595" alt="mmkv_1_3_1_github" src="https://github.com/Tencent/MMKV/assets/1866938/0b93c7a7-14d2-41e3-97ef-5156ed4cfb91">

Here is the code size information of Maven version:
<img width="618" alt="mmkv_1_3_1_maven" src="https://github.com/Tencent/MMKV/assets/1866938/4af86c6a-a113-41cd-9760-85b27e37e50e">

I don't change any source files but the following to make it can be compiled with my Android Studio:
* change to classpath 'com.android.tools.build:gradle:8.0.2'
* change to distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.2-bin.zip
* remove  package="com.tencent.mmkv" from AndroidManifest.xml
* add  namespace 'com.tencent.mmkv'
* add buildFeatures.buildConfig = true

The code was built on the Windows platform. I also attach my modified source files and mmkv aars to this ticket.
[mmkv_maven_has_bigger_code_size_issue.zip](https://github.com/Tencent/MMKV/files/12340835/mmkv_maven_has_bigger_code_size_issue.zip)

**Comment by lingol** [comment]
Interesting, which NDK did you use?

**Comment by samlu** [comment]
The same as the mmkv/build.gradle defined `ndkVersion = '25.0.8775105'`
Cmake is
```
cmake {
  path "CMakeLists.txt"
  version "3.18.0+"
}
```

**Comment by lingol** [comment]
The `libmmkv.so` in the aar you provided is symbol-striped. Can you provide unstriped binary?

**Comment by samlu** [comment]
Do you mean this?
[mmkv-StaticCpp-debug.zip](https://github.com/Tencent/MMKV/files/12341036/mmkv-StaticCpp-debug.zip)

**Comment by lingol** [comment]
No. I mean unstriped so of a release build, not a debug build so.

**Comment by lingol** [comment]
You should just make and publish to local maven and zip the entire directory of `~/.m2/repository/com/tencent/mmkv/1.3.1`.

**Comment by lingol** [comment]
The unstriped so is in location `~/.m2/repository/com/tencent/mmkv/1.3.1/mmkv-1.3.1-so-symbols.jar`.

**Comment by lingol** [comment]
I did a little local search and the intermediate location of unstriped so is `path_of_mmkv/Android/MMKV/mmkv/build/intermediates/cmake/StaticCppRelease/obj`. 
You can zip that directory if having trouble in publish to local maven.

**Comment by samlu** [comment]
Here you are: 
[symbols-StaticCppRelease.zip](https://github.com/Tencent/MMKV/files/12341122/symbols-StaticCppRelease.zip)

**Comment by lingol** [comment]
The attachment fails to download in mainland China, could you send it to my email guoling@tencent.com?

**Comment by lingol** [comment]
There are LOTS of functions missing in your build, maybe they are inlined. I wonder if there's any difference in the actual build command. 
Could you provide the build command file in patch `path_to_mmkv/Android/MMKV/mmkv/.cxx/cmake/StaticCppRelease/arm64-v8a/build.ninja'?

**Comment by lingol** [comment]
Also the file `CMakeCache.txt` & `compile_commands.json` under the same location.

**Comment by samlu** [comment]
There is no `path_to_mmkv/Android/MMKV/mmkv/.cxx/cmake` directory.
Anyway, I have zipped all source and build files and send you the download link to your email box.

**Comment by lingol** [comment]
Yep, just as I have suspected, there are differences in the actual build command.
Your build:
```ninja
build Core/CMakeFiles/core.dir/MMKV.cpp.o: CXX_COMPILER__core_RelWithDebInfo R$:/MMKV_1.3.1_test/Core/MMKV.cpp || cmake_object_order_depends_target_core
  DEP_FILE = Core\CMakeFiles\core.dir\MMKV.cpp.o.d
  FLAGS = -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -DMMKV_STL_SHARED=1 -fvisibility=hidden -funwind-tables -fasynchronous-unwind-tables -O2 -g -DNDEBUG -fPIC -std=c++17
  INCLUDES = -IR:/MMKV_1.3.1_test/Core
  OBJECT_DIR = Core\CMakeFiles\core.dir
  OBJECT_FILE_DIR = Core\CMakeFiles\core.dir
```
My build:
```ninja
build Core/CMakeFiles/core.dir/MMKV.cpp.o: CXX_COMPILER__core_unscanned_Release /Users/lingol/Developer/mmkv/Core/MMKV.cpp || cmake_object_order_depends_target_core
  DEP_FILE = Core/CMakeFiles/core.dir/MMKV.cpp.o.d
  FLAGS = -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -DMMKV_STL_SHARED=0 -fvisibility=hidden -funwind-tables -fasynchronous-unwind-tables -DNDEBUG  -std=c++17 -fPIC
  INCLUDES = -I/Users/lingol/Developer/mmkv/Core
  OBJECT_DIR = Core/CMakeFiles/core.dir
  OBJECT_FILE_DIR = Core/CMakeFiles/core.dir
  TARGET_COMPILE_PDB = Core/CMakeFiles/core.dir/core.pdb
  TARGET_PDB = Core/libcore.pdb
```
The main difference is the `-O2` flags. It's not set in the project. So it must be set somewhere down your local build phase.
Anyway, thanks for the discovery. I will check each optimization level for the best size-speed trade-off.

**Comment by samlu** [comment]
I don't set any optimization flags on my end. 

What I do is:
1. download all source files from GitHub
2. modified some files as I mentioned in the first thread
3. use the "build" gradle task to build it

Would you do the same test on a clean env to see if you can reproduce this issue?

**Comment by lingol** [comment]
It's highly possible that your CMake automatically set `-O2` on the release build. I won't spend time to reproduce it, how it happens is irreverent. What matters is which optimization level provides the best size-speed trade-off.

**Comment by samlu** [comment]
Checking this
https://developer.android.com/ndk/guides/ndk-build#dvr
<img width="488" alt="ndb_debug" src="https://github.com/Tencent/MMKV/assets/1866938/04b942f8-2fd2-4bc7-8932-d081ba62a9f7">


With or without `-O2` is okay with me, but I would suggest that the developer manually build .so file size should be the same as the public one.

**Comment by lingol** [comment]
I don't think it's caused by that flag, for it's a **project setting flag**. With or without it should make the same effect on your build and my build.

**Comment by lingol** [comment]
And I think this is the cause https://stackoverflow.com/questions/24767450/using-cmake-how-do-you-determine-the-default-compiler-flags-per-build-type.

**Comment by samlu** [comment]
Great! Will you set the CMAKE_CXX_FLAGS in the makefile?

**Comment by lingol** [comment]
MMKV for Android now builds with `-O2` starting from [v1.3.2](https://github.com/Tencent/MMKV/releases/tag/v1.3.2).
