### ISSUE TITLE
Cannot compile after updating to 1.3.1

### ISSUE THREAD

**Issue by coderlzx** [Tencent/MMKV#1146]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV
> Java

### The version of MMKV
> v1.3.1

### The platform of MMKV
> Android

### The installation of MMKV
> Maven

### What's the issue?
The androidx.annotation:annotation version in 1.3.1 has been upgraded to 1.6.0, resulting in the inability to use annotation normally after upgrading from 1.3.0 to 1.3.1, as shown in the figure:
![image](https://github.com/Tencent/MMKV/assets/3348827/8994d2ea-4ec4-48ff-9d7a-8f1cad7f0546)
![image](https://github.com/Tencent/MMKV/assets/3348827/f9cc81f3-beb3-4173-a0a1-df147db9c0d7)
![image](https://github.com/Tencent/MMKV/assets/3348827/e56043b7-fe92-486c-85d0-383dcf2e9a8a)
![image](https://github.com/Tencent/MMKV/assets/3348827/659a566d-e953-40fe-a1ae-a4c54e172045)
![image](https://github.com/Tencent/MMKV/assets/3348827/f4fb99fe-c990-489a-8cfc-1b2248419c29)

**Comment by lingol** [comment]
You should upgrade your configure.

**Comment by lingol** [comment]
Duplicate with #1086 .
