### ISSUE TITLE
MMKV.allKeys() return not existing keys.

### ISSUE THREAD

**Issue by tadevi** [Tencent/MMKV#1148]
## Note:
Not a crash.

### The language of MMKV

> Kotlin

### The version of MMKV
> Version: v1.2.13

### The platform of MMKV

>  Android

### The installation of MMKV

> Maven

### What's the issue?
I use MMKV to persist some user data. Code example:
```
    mmkv.encodeInt("key1@int", 100)
    mmkv.encodeString("key2@String", "{\"name\": \"test\"}")
```
I placed a log to log `allKeys` value in firebase, and some users report the logs of `allKeys` method like this:
```
// Firebase.log(mmkv.allKeys().toList().toString())
// Result
[key1@int, key2@StringՖӖ{"name":"test"}]
```
The result is really weird. Why does MMKV return not existing key?

### What's the log of MMKV when that happened?
No

**Comment by lingol** [comment]
Can you reproduce this error? Or can you provide logs from MMKV when a use reproduces this error?

**Comment by lingol** [comment]
Without logs, there's noting to investigate any further.
