### ISSUE TITLE
7 (SIGBUS)-128 (SI_KERNEL)

### ISSUE THREAD

**Issue by joychic** [Tencent/MMKV#1152]
## Note:
#00 pc 000434a4 /data/app/com.shizhuang.duapp-QTHDAXNgy-AbHzRPeC0ZaA==/lib/arm/libmmkv.so (_ZN4mmkv10ThreadLock6unlockEv) /Users/admin/android/du/MMKV/Core/ThreadLock.cpp:56
#01 pc 00028d82 /data/app/com.shizhuang.duapp-QTHDAXNgy-AbHzRPeC0ZaA==/lib/arm/libmmkv.so (_ZN4mmkv10ScopedLockINS_10ThreadLockEE6unlockEv) /Users/admin/android/du/MMKV/Core/ScopedLock.hpp:40
#02 pc 0002303c /data/app/com.shizhuang.duapp-QTHDAXNgy-AbHzRPeC0ZaA==/lib/arm/libmmkv.so (~ScopedLock) /Users/admin/android/du/MMKV/Core/ScopedLock.hpp:50
#00 pc 0002ef1c /data/app/com.shizhuang.duapp-gMvuij_nhw-guQH-oHqxtA==/lib/arm/libmmkv.so (_ZN4MMKV10mmkvWithIDERKNSt6__ndk112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEi8MMKVModePS6_SA_) /Users/admin/android/du/MMKV/Core/MMKV_Android.cpp:161
#01 pc 0001df2e /data/app/com.shizhuang.duapp-gMvuij_nhw-guQH-oHqxtA==/lib/arm/libmmkv.so (_ZN4mmkvL13getMMKVWithIDEP7_JNIEnvP8_jobjectP8_jstringiS5_S5_) /Users/admin/android/du/MMKV/Android/MMKV/mmkv/.cxx/cmake/DefaultCppRelease/armeabi-v7a/../../../../src/main/cpp/native-bridge.cpp:322

### The language of MMKV

Java

### The version of MMKV

 v1.2.15

### The platform of MMKV

 Android

### What's the issue?
happened on Android SDK version 28

**Comment by lingol** [comment]
It crashed inside a system call. Unless you can reproduce it, there's nothing we can do about it.
