### ISSUE TITLE
[REQUEST] initialSize and repackSize params for mmkvWithID

### ISSUE THREAD

**Issue by stefano-finocchiaro-20230331** [Tencent/MMKV#1156]
### The language of MMKV
Kotlin
### The version of MMKV
v1.3.1
### The platform of MMKV
Android
### The installation of MMKV
Maven
### What's the issue?
Inefficient space use to store a few MB. In our case to store 3MB of data we end up with a file of 64MB, that's more than 95% wasted space.

When saving 3MB of data MMKV it will create a file of 32MB (totalSize() ) out of the box.
If we keep saving the same 3MB of data using the **same key** (overriding the old value), the actualSize() will keep increasing and after it has reached the 32MB limit the file will expand to 64MB and the actualSize() will go back to 3MB.

Example:

push 3MB ->  actualSize: 3MB totalSize:32MB
push 3MB ->  actualSize: 6MB totalSize:32MB
push 3MB ->  actualSize: 9MB totalSize:32MB
push 3MB ->  actualSize: 12MB totalSize:32MB
push 3MB ->  actualSize: 15MB totalSize:32MB
push 3MB ->  actualSize: 18MB totalSize:32MB
push 3MB ->  actualSize: 21MB totalSize:32MB
push 3MB ->  actualSize: 24MB totalSize:32MB
push 3MB ->  actualSize: 27MB totalSize:32MB
push 3MB ->  actualSize: 30MB totalSize:32MB
push 3MB ->  **actualSize: 3MB totalSize:64MB** //Now it **increase** the totalSize, actualSize restart from 3MB
push 3MB ->  actualSize: 6MB totalSize:64MB //Notice that actualSize it's actually double what should be even after "repacking"
push 3MB ->  actualSize: 9MB totalSize:64MB
..........
..........
push 3MB ->  actualSize: 63MB totalSize:64MB
push 3MB ->  **actualSize: 6MB totalSize:64MB** //Now it keep the same totalSize, actualSize restart from 3MB
...........

Is it possible to add a param to the "mmkvWithID" function to set the maximum file size after which it will override the old data (repack) and another param to set the start size?

like this:
`public static MMKV mmkvWithID(String mmapID, int initialSize, int repackSize)
`

So that I can set them like this `MMKV.mmkvWithID(String mmapID, 8, 16)` to avoid reaching 64MB just to store 3MB of data

**Comment by lingol** [comment]
There's an ongoing PR improving this scenario. https://github.com/Tencent/MMKV/pull/1151

**Comment by kaitian521** [comment]
push 3MB -> actualSize: 3MB totalSize:32MB

**Comment by stefano-finocchiaro-20230331** [comment]
> Interesting. if you upgrade MMKV to 1.3.1, maybe you will get a smaller file size

I'm testing with 1.3.1, I will update you

**Comment by kaitian521** [comment]
BUT you could wait for this pr to be merged, then the file size will remain 4M if there exists only one key in your MMKV  instance.

**Comment by stefano-finocchiaro-20230331** [comment]
> > Interesting. if you upgrade MMKV to 1.3.1, maybe you will get a smaller file size
> 
> I'm testing with 1.3.1, I will update you

I've tested with 1.3.1 and had same behaviour

**Comment by stefano-finocchiaro-20230331** [comment]
> BUT you could wait for this pr to be merged, then the file size will remain 4M if there exists only one key in your MMKV instance.

That would be great but does it solve the other issue that after the after writing 3MB of data the initial size is 32MB ?

**Comment by kaitian521** [comment]
> > BUT you could wait for this pr to be merged, then the file size will remain 4M if there exists only one key in your MMKV instance.
> 
> That would be great but does it solve the other issue that after the after writing 3MB of data the initial size is 32MB ?
> 
> Because having a file of 32MB to store 3MB of data it's still about 90% of wasted space

At that time, you could call `trim` function to trim the  file to appropriate size.

**Comment by lingol** [comment]
Released with [v1.3.2](https://github.com/Tencent/MMKV/releases/tag/v1.3.2).
