### ISSUE TITLE
iOS fail to lock

### ISSUE THREAD

**Issue by xuzang** [Tencent/MMKV#1163]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

你好。想请教一个问题，目前通过日志收集，收集到了一些错误。
1. fail to lock fd=59, ret=-1, error:Bad file descriptor
2. fail to lock fd=73, ret=-1, error:Operation not supported

报错日志收到的频率特别高。11用户。收到几万次的日志
希望可以给一些排查建议，或者帮忙指出我的使用错误。这个MMKV接入。
感谢！！！

背景：
我们使用的MMKVSingleProcess，没有 App 与 Extension 通讯需求

以下是我的代码。
1。初始化代码，App启动就有调用：

+ (void)initializeZebraStore {
    // 初始化 MMKV
    [MMKV initializeMMKV:nil];

    // 注册MMKV日志
    [[ZebraStoreAgent sharedInstance] registerZebraStoreLogHandler];

    // 自动清理 5分钟没有访问的 kv 对象 自动清理
    [MMKV enableAutoCleanUp:5];
}

2 KV对象彻创建：
self.cache = [MMKV mmkvWithID:ZBENonnullString(self.currentTableName) rootPath:ZBENonnullString(self.currentPath)];
最终的存储路径就是：
NSString *basePath = [MMKV mmkvBasePath]
basePath/User/TableName

3 存储和读取：
就是直接调用Api

**Comment by xuzang** [comment]
如有需要 我可以发代码到你邮箱 谢谢

**Comment by xuzang** [comment]
如有需要 我可以发代码到你邮箱 谢谢

**Comment by xuzang** [comment]
报错的文件  InterProcessLock.cpp

**Comment by xuzang** [comment]
function： platformLock

**Comment by lingol** [comment]
Why don't you follow **the issue template** and provide info as it requires.

**Comment by xuzang** [comment]
太着急了。抱歉
1.The language of MMKV  -> Objective-C
2. The version of MMKV -> 1.2.16
3. The platform of MMKV -> iOS
4. The installation of MMKV -> Cocoapods
5. What's the issue? 如正文。


如果这样不行的话。你可以直接close 我在重新提一个issue也可以。感谢

**Comment by xuzang** [comment]
只是通过远端日志，收到报错信息。并没有当时具体的日志。

**Comment by lingol** [comment]
Upgrade the v1.3.1.

**Comment by xuzang** [comment]
好的 更新下。然后在观察下。谢谢  添麻烦了

**Comment by xuzang** [comment]
我们没有使用 MMKVMultiProcess,  没有 App 与 Extension 通讯需求。1.2.16  也会导致以上错误吗
fail to lock fd=59, ret=-1, error:Bad file descriptor
fail to lock fd=73, ret=-1, error:Operation not supported
