### ISSUE TITLE
Xcode 捕捉到 278 次 crash

### ISSUE THREAD

**Issue by make1a** [Tencent/MMKV#1175]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin
 使用 oc & swift 混编

### The version of MMKV
```
  pod 'MMKV', '1.3.1'
  pod 'MMKVCore', '1.3.1'
```

### The platform of MMKV

iOS：

![image](https://github.com/Tencent/MMKV/assets/17469549/23911b94-2a74-45fb-bc46-5be64ded13ab)

### The installation of MMKV

 Cocoapods

```[tasklist]
### Tasks
```

**Comment by make1a** [comment]
![image](https://github.com/Tencent/MMKV/assets/17469549/84629997-c63e-4d98-ba3a-e80a8881ee98)

**Comment by lingol** [comment]
It's crashed inside stdlib. Noting we can do about it.

**Comment by make1a** [comment]
Thank you for getting back to me. I appreciate your response. I would like to seek some clarification regarding your previous message. You mentioned that the crash occurred inside the stdlib and that there is nothing that can be done about it. Could you please elaborate on what this means and whether there are any potential workarounds or steps I can take to address the issue?

I'm eager to better understand the situation and any guidance you can provide would be greatly appreciated.

**Comment by lingol** [comment]
By saying nothing we can do about it, it means nothing we can do about it. If you don't know that is stdlib, Google about it.

**Comment by make1a** [comment]
Thank you for getting back to me again. I've noticed that we are initializing MMKV in applicationWillTerminate. We will review this logic to address the issue.

**Comment by lingol** [comment]
One more thing, I have just noticed that your crash report is inside `-[UIApplication _terminateWithStatus]`. According to the name, looks like the user won't notice much of it.
