### ISSUE TITLE
Sometimes can't decode mmkv file into map when app re open

### ISSUE THREAD

**Issue by Designerxsh** [Tencent/MMKV#1177]
### The language of MMKV
Objective-C

### The version of MMKV
v1.2.8

### The platform of MMKV
iOS

### The installation of MMKV
Cocoapods

### What's the issue?
Sometimes can't decode mmkv file into map when app re open. 

### What's the log of MMKV when that happened?
loadFromFile() -> 
MiniPBCoder::decodeMap(*m_dicCrypt, inputBuffer, m_crypter) ->
void MiniPBCoder::decodeOneMap(MMKVMapCrypt &dic, size_t position, bool greedy) ->
const auto &key = m_inputDataDecrpt->readString(kvHolder)

Sometimes it throws length_error("InvalidProtocolBuffer negativeSize").
More often it throws throw out_of_range("InvalidProtocolBuffer truncatedMessage").

**Comment by Designerxsh** [comment]
I have collected the problematic files and their corresponding CRC files. I hope you can assist us in troubleshooting the issue.

**Comment by lingol** [comment]
v1.2.8 is just too old, upgrade to latest version first.
