### ISSUE TITLE
Android putString crash on Android 10

### ISSUE THREAD

**Issue by tiger** [Tencent/MMKV#1178]
crashInfo2: #00    pc 000000000003e328    /apex/com.android.runtime/lib64/bionic/libc.so [arm64-v8a::2a5abdc9c768b33656f7aa8d9ce5cf54]
#01    pc 000000000002e63c    /data/app/com.xiwang.zaixian-jf85-WNNazbY6DgtV7GSPQ==/lib/arm64/libmmkv.so [arm64-v8a::1051e232057f0765b8e39437bade2b4a]
#02    pc 000000000002992c    /data/app/com.xiwang.zaixian-jf85-WNNazbY6DgtV7GSPQ==/lib/arm64/libmmkv.so [arm64-v8a::1051e232057f0765b8e39437bade2b4a]
#03    pc 00000000000294c0    /data/app/com.xiwang.zaixian-jf85-WNNazbY6DgtV7GSPQ==/lib/arm64/libmmkv.so [arm64-v8a::1051e232057f0765b8e39437bade2b4a]
#04    pc 0000000000028f90    /data/app/com.xiwang.zaixian-jf85-WNNazbY6DgtV7GSPQ==/lib/arm64/libmmkv.so [arm64-v8a::1051e232057f0765b8e39437bade2b4a]
#05    pc 000000000001e914    /data/app/com.xiwang.zaixian-jf85-WNNazbY6DgtV7GSPQ==/lib/arm64/libmmkv.so [arm64-v8a::1051e232057f0765b8e39437bade2b4a]
#06    pc 0000000000018f08    /data/app/com.xiwang.zaixian-jf85-WNNazbY6DgtV7GSPQ==/lib/arm64/libmmkv.so [arm64-v8a::1051e232057f0765b8e39437bade2b4a]
#07    pc 0000000000010a4c    /data/app/com.xiwang.zaixian-jf85-WNNazbY6DgtV7GSPQ==/oat/arm64/base.odex (oatdata+64076) [arm64-v8a::881705cd4d931797585f02557d6ced3b]
java:
com.tencent.mmkv.MMKV.putString(MMKV.java:995)

**Comment by lingol** [comment]
Please provide as much info as possible, following the issue template.

**Comment by lingol** [comment]
At least provide the version of MMKV, **symbolized** call stacks, and logs of MMKV when this crash happened.

**Comment by lingol** [comment]
Closed due to lack of info.
