### ISSUE TITLE
缓存的值突然丢失的问题

### ISSUE THREAD

**Issue by BugFactory9527** [Tencent/MMKV#1186]
1.在小米12上，记录的一些配置项目，在反复打开APP，再杀死APP过程中，会出现丢失配置项的问题

单进程模式里有一个catch

试了大概30次次
<img width="1604" alt="image" src="https://github.com/Tencent/MMKV/assets/37281286/309d75bf-bf22-4f27-a2e2-46b651bae839">

中途突然出现这样的报错

<img width="1636" alt="image" src="https://github.com/Tencent/MMKV/assets/37281286/0e6cd451-e892-48ea-9a52-eaa30a4e05bb">

然后存的10个值就没了

<img width="1666" alt="image" src="https://github.com/Tencent/MMKV/assets/37281286/bbb8c075-6e10-4ffe-a1cd-96fb27337a30">

**Comment by BugFactory9527** [comment]
同样的结果  在华为  nova 5 上也复现。。整的人很猛。。。用户突然需要重新同意隐私协议。

**Comment by lingol** [comment]
Please follow the issue template and provide required info.

**Comment by lingol** [comment]
Anyway, most likely you're either using an old version of MMKV, or using MMKV in multi-process without setting `MULTI_PROCESS_MODE`. 
Or both.
