### ISSUE TITLE
Anr

### ISSUE THREAD

**Issue by lz0928** [Tencent/MMKV#1188]
### The language of MMKV

> Java

### The version of MMKV

> v1.3.1

### The platform of MMKV

> Android

### The installation of MMKV

>Maven

### What's the issue?
MMKV.initialize(context)执行了20秒才初始化完成

下面是log
	行 21821: 10-23 19:23:03.690  4025  4025 I MMKV    : Disable checkProcessMode()
	行 26483: 10-23 19:23:22.438  4025  4025 I MMKV    : current API level = 29, libc++_shared=0
	行 26487: 10-23 19:23:22.439  4025  4025 I MMKV    : <MMKV.cpp:164::initialize> version v1.3.1, page size 4096, arch arm64-v8a
	行 26489: 10-23 19:23:22.439  4025  4025 I MMKV    : <MMKV.cpp:175::initialize> armv8 AES instructions is supported
	行 26490: 10-23 19:23:22.439  4025  4025 I MMKV    : <MMKV.cpp:183::initialize> armv8 CRC32 instructions is supported
	行 26492: 10-23 19:23:22.440  4025  4025 I MMKV    : <MMKV.cpp:207::initializeMMKV> root dir: /data/user/0/com.example.app/files/mmkv

**Comment by lingol** [comment]
The logs mean there's a 20s gap between [Java code](https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/java/com/tencent/mmkv/MMKV.java#L192) & [Native code]( https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/java/com/tencent/mmkv/MMKV.java#L204). It provides little useful info if not any.
You need to catch the very method that costs max time with precise callstacks.
