### ISSUE TITLE
类型太固定

### ISSUE THREAD

**Issue by applejian** [Tencent/MMKV#119]
### The language of MMKV

Objective-C,

### The version of MMKV

v1.0.13

### The platform of MMKV

iOS

### The installation of MMKV

Cocoapods

### What's the issue?

没有getObjectForKey:也没有setObject:forKey:  等无脑实现
或者是否能通过一种关系直接存储绑定进去的value的类型 取出时也能对应有限读取绑定的类的类型关系，再去做转换

**Comment by lingol** [comment]
Oh I see. You mean storing value's type inside MMKV. Well, we won't do this. You're very welcome to wrap one on MMKV.

**Comment by applejian** [comment]
setObject string 类型值，取的时候也必须要指定string.class 这个方法名称是不是应该改成 setString 这样好直接对应起来，起先我发现getObject 的时候 设置nsobject.class 然后那个string的值就取不来，感觉方法名称上有点误导 取的时候好像必要严格对应其来

**Comment by lingol** [comment]
`setString` is released with [v1.0.15](https://github.com/Tencent/MMKV/releases/tag/v1.0.15).
