### ISSUE TITLE
杀死APP，再打开保存的值会丢失，比如保存的1，打开变成0了

### ISSUE THREAD

**Issue by wuh876** [Tencent/MMKV#1191]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> Java

### The version of MMKV

> v1.3.0
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> Android

### The installation of MMKV

> , Maven

### What's the issue?

杀死APP，再打开保存的值会丢失，比如保存的1，打开变成0了

**Comment by lingol** [comment]
Duplicated with #1186.

**Comment by lingol** [comment]
>Anyway, most likely you're either using an old version of MMKV, or using MMKV in multi-process without setting MULTI_PROCESS_MODE.
Or both.

**Comment by wuh876** [comment]
oh,yes, not use MULTI_PROCESS_MODE
