### ISSUE TITLE
Mmkv.clearAll() native crash.

### ISSUE THREAD

**Issue by lovehanze** [Tencent/MMKV#1194]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> Java

### The version of MMKV

>  v1.2.14
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

>  Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

Build fingerprint: 'HONOR/FMN-AN00/HNFMN-AN00:14/HONORFMN-AN00/2.1.0.100SP15C00E100R5P2:user/release-keys'

Revision: '0'

ABI: 'arm64'

Timestamp: 2023-11-07 14:50:37.829946918+0800

Process uptime: 6s

Cmdline: app

pid: 20027, tid: 20027, name: app  >>> app <<<

uid: 1110070

tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)

pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000

Cause: null pointer dereference

    x0  0000007261861990  x1  0000000000000000  x2  0000000000000000  x3  0000007fcbc72cd8

    x4  0000000000000001  x5  0000000000000000  x6  0000000000000000  x7  000000000000002e

    x8  0000000000000000  x9  000000749b550000  x10 000000749b550000  x11 000000749b550ee0

    x12 00000000d74a7835  x13 000000749b550ed4  x14 000000749b550ec4  x15 000000749b550ed4

    x16 0000000000000001  x17 000000749b541fbc  x18 00000074a838a000  x19 00000071ff87c4d0

    x20 0000007261861990  x21 00000074a7868000  x22 00000071e382c5f0  x23 00000072618619a8

    x24 000000749464b740  x25 0000007fcbc72e00  x26 0000000010380001  x27 0000000000000008

    x28 0000007fcbc72e20  x29 0000007fcbc72cc0

    lr  00000071955b2248  sp  0000007fcbc72ca0  pc  00000071955afd14  pst 0000000080001000

59 total frames

backtrace:

      #00 pc 0000000000027d14  /system/app/app/app.apk!libmmkv.so (offset 0x370a000) (BuildId: b67663129c27690368418b8a83464eceacc349e1)

      #01 pc 000000000002a244  /system/app/app/app.apk!libmmkv.so (offset 0x370a000) (BuildId: b67663129c27690368418b8a83464eceacc349e1)

      #02 pc 0000000000053134  /data/dalvik-cache/arm64/system@app@app@app.apk@classes.dex (art_jni_trampoline+116)

**Comment by lingol** [comment]
Please provide **symbolized** native call stacks.

**Comment by lovehanze** [comment]
![Uploading wy.png…]()

**Comment by lovehanze** [comment]
[libmmkv.zip](https://github.com/Tencent/MMKV/files/13345110/libmmkv.zip)


> Please provide **symbolized** native call stacks.

**Comment by lovehanze** [comment]
![wy](https://github.com/Tencent/MMKV/assets/20070638/1056a8c4-4d20-4d1a-abc7-5febd7e96d03)

**Comment by lingol** [comment]
That's wrong result.

**Comment by lingol** [comment]
Anyway, you're using a very old version of MMKV. Upgrade first.
