### ISSUE TITLE
Android MMKV代码中有一段疑惑

### ISSUE THREAD

**Issue by cliangtime** [Tencent/MMKV#1199]
![1701066689414](https://github.com/Tencent/MMKV/assets/20796467/5373e011-0d68-460d-89c3-9bcfd6420630)

这段代码不是恒不等么，为啥要做这样的一个判断？

**Comment by lingol** [comment]
Think twice. And, it's not an issue. The place you are looking for is _Discussions_.

**Comment by cliangtime** [comment]
是我的问题，没有直接看源代码😅
