### ISSUE TITLE
Would the data be wrong if fullWriteback is broken? 

### ISSUE THREAD

**Issue by xylitolhub** [Tencent/MMKV#120]
### The language of MMKV

> Android

### The version of MMKV

> e.g. v1.0.13

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> AAR

### What's the issue?

In fullWriteback, if app is killed before finishing writing file(just during memcpy), the file data will be wrong, right?

**Comment by lingol** [comment]
Well, not just `fullWriteback`. Other place like appending, if App is killed between writing data and calculating crc32, you're in bad luck.

**Comment by xylitolhub** [comment]
> Well, not just `fullWriteback`. Other place like appending, if App is killed between writing data and calculating crc32, you're in bad luck.

Is there any way to avoid these problems?

**Comment by lingol** [comment]
> Is there any way to avoid these problems?

As far as I know, there's no way to totally avoid these data corruption.
