### ISSUE TITLE
Android 遇到fail to mmap ,Out of memory

### ISSUE THREAD

**Issue by LinAndroid** [Tencent/MMKV#1201]
<flutter-bridge.cpp:50::mmkvInitialize_v1> current API level = 29, libc++_shared=0
<MMKV.cpp:165::initialize> version v1.2.13, page size 4096, arch arm64-v8a
<MMKV.cpp:176::initialize> armv8 AES instructions is supported
<MMKV.cpp:184::initialize> armv8 CRC32 instructions is supported
<MMKV.cpp:207::initializeMMKV> root dir: /data/user/0/com.xunyi.apollo/app_flutter/mmkv
<MemoryFile.cpp:97::open> open fd[0xb2], /data/user/0/com.xunyi.apollo/app_flutter/mmkv/mmkv.default
<MemoryFile.cpp:187::mmap> fail to mmap [/data/user/0/com.xunyi.apollo/app_flutter/mmkv/mmkv.default], Out of memory
 <MemoryFile.cpp:103::close> closing fd[0xb2], /data/user/0/com.xunyi.apollo/app_flutter/mmkv/mmkv.default
<InterProcessLock.cpp:137::platformUnLock> fail to unlock fd=178, ret=-1, error:Bad file descriptor
<MemoryFile.cpp:97::open> open fd[0x90], /data/user/0/com.xunyi.apollo/app_flutter/mmkv/mmkv.default.crc
<MemoryFile.cpp:97::open> open fd[0xa5], /data/user/0/com.xunyi.apollo/app_flutter/mmkv/mmkv.default
<MemoryFile.cpp:187::mmap> fail to mmap [/data/user/0/com.xunyi.apollo/app_flutter/mmkv/mmkv.default], Out of memory
<MemoryFile.cpp:103::close> closing fd[0xa5], /data/user/0/com.xunyi.apollo/app_flutter/mmkv/mmkv.default
<InterProcessLock.cpp:137::platformUnLock> fail to unlock fd=165, ret=-1, error:Bad file descriptor
<MMKV_IO.cpp:74::loadFromFile> file [/data/user/0/com.xunyi.apollo/app_flutter/mmkv/mmkv.default] not valid

**Comment by LinAndroid** [comment]
使用的版本：com.tencent:mmkv-static:1.2.13

**Comment by lingol** [comment]
How big is your `mmkv.default` file? Try not to store too large a key value inside, for example, a key value larger than 10M.

**Comment by LinAndroid** [comment]
嗯，我确认下是不是单个key存的 value过长了，多谢。
