### ISSUE TITLE
mmkv.decodeBytes() return null when encode an empty byte array

### ISSUE THREAD

**Issue by zj565061763** [Tencent/MMKV#1205]
### The language of MMKV

Kotlin

### The version of MMKV

1.3.2

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?

mmkv.decodeBytes() returns null when encode an empty byte array.

I think it is better returning an empty byte array in this situation.

<img width="739" alt="截屏2023-12-09 22 37 59" src="https://github.com/Tencent/MMKV/assets/26968219/0b91f795-2de4-43de-b1c3-8dc2421ea8f5">

**Comment by zj565061763** [comment]
This happened when i ran unit test in my cache library, because I used mmkv as the underlying implementation.
I fix it in this way for now.

<img width="502" alt="截屏2023-12-09 23 10 36" src="https://github.com/Tencent/MMKV/assets/26968219/a64f8fc7-7d40-4142-8edc-205444b352de">

**Comment by lingol** [comment]
Released with [v1.3.3](https://github.com/Tencent/MMKV/releases/tag/v1.3.3).
