### ISSUE TITLE
iOS App submission will require a privacy manifest

### ISSUE THREAD

**Issue by shaillymt** [Tencent/MMKV#1207]
Apple recently announced new [privacy requirements](https://developer.apple.com/news/?id=av1nevon) expected to be enforced by Spring 2024. Per the new requirements, any usage of Required Reason API’s (identified by Apple) should have a approved reason for usage (provided by Apple on the privacy manifest available with iOS17/XCode15 upgrade. Privacy manifest file name: PrivacyInfo.xcprivacy

According to our findings, you are using one or more of the Required Reason APIs. Please complete your privacy manifest at the earliest availability and publish your ETA

**Comment by lingol** [comment]
Don't spam here.
