### ISSUE TITLE
iOS17 系统  bugly卡顿上报有出现大量的 主线程死锁

### ISSUE THREAD

**Issue by xujianbo12345** [Tencent/MMKV#1208]
MMKV 版本v1.2.16

iOS17 系统  bugly卡顿上报有出现大量的 主线程加锁卡死，都上报在卡顿日志中，实际上发生死锁的时候由于主线程卡死，会被系统杀掉
<img width="958" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/4a177bad-0b5d-4eca-9ff1-ae3b5e2bee1b">
<img width="826" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/4268ddca-6270-46ba-ba12-cefb8b913f0d">
<img width="862" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/35eeed0b-d5cf-4909-baea-0642e9082dc7">

**Comment by lingol** [comment]
When you talk about ANR, you should always provide **call stacks of other threads**, especially when it **involves locking**.
By the way, v1.2.16 is considerably old, you should upgrade it first.

**Comment by xujianbo12345** [comment]
> When you talk about ANR, you should always provide **call stacks of other threads**, especially when it **involves locking**. By the way, v1.2.16 is considerably old, you should upgrade it first.

感谢答复！ 现在bugly免费版的 其他线程好像是没有解析出来，看不到具体调用堆栈，下面是其中一个卡顿日志的所有子线程截图
<img width="1133" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/0b56be06-ecf6-476c-8d91-38a464a7bf7b">
<img width="762" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/bda647ac-d422-47d0-b1e9-43087e54df2c">
<img width="546" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/66842f7e-0739-4f7b-9295-3fd1cdf4b836">
<img width="678" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/f70ff0f5-5e98-473b-bb5a-64fef3d3c007">
<img width="644" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/44e48edc-1589-4375-9489-aca486b07580">
<img width="667" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/f844e933-b4cf-47fe-9c87-bdecb9abcfe8">
<img width="678" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/cb9997f2-9f58-4320-8382-b2bbdab54948">
<img width="580" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/fe4b2ef1-5fb1-4a3f-9916-82a3b2dc57cc">
<img width="589" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/9bd59e19-2d7e-4a49-b5b2-d1c1d4a7ac01">
<img width="1124" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/13038e66-6e3c-4989-99ec-cb693149b7ed">
<img width="917" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/5664b8cc-f81b-4afe-9b84-3641683fe594">
<img width="691" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/47a4f739-58f9-469a-a82f-5dcf03d010f7">

**Comment by lingol** [comment]
Nothing special in this report.

**Comment by lingol** [comment]
Close due to inactive.

**Comment by xujianbo12345** [comment]
@lingol 我看了卡顿日志出现的版本，正好是开启了mutiProcess的版本开始的 正好这个卡顿日志就停留在InterProcessLock 这边，是iOS 下mutiProcess有问题吗，最早我们用的是默认创建的默认是singleProcess
![image](https://github.com/Tencent/MMKV/assets/17424004/5315f323-f45a-40e9-85bc-7b9192428893)
<img width="871" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/e14152aa-2cb7-483d-aa68-6901477f611a">
