### ISSUE TITLE
got crash on CodedInputData

### ISSUE THREAD

**Issue by dongfanger2018** [Tencent/MMKV#1210]
### The language of MMKV

Swift

### The version of MMKV

v1.3.2  

![image](https://github.com/Tencent/MMKV/assets/153170234/e4b81865-2e2e-458b-82e4-2a3bb33a4c66)

### The platform of MMKV

iOS 
Host App & UNNotificationServiceExtension

### The installation of MMKV

Cocoapods

### What's the issue?

crash 

### What's the log of MMKV when that happened?

didn't open MMKV log, has crash log only

App use 2 MMKV instance

shared one, across user domain, use multiProcess mode
![image](https://github.com/Tencent/MMKV/assets/153170234/33934fce-fc4d-43a9-b2de-8e1f8123493f)

user one, for every user
![image](https://github.com/Tencent/MMKV/assets/153170234/348db43b-dc7e-4c49-8a60-365184fe8ca5)

crash when using the second(user one)

this is crash log from apple
[2023-12-15_19-23-05.0669_+0700-760963e560ccc42e362536aff66627379c637e62.crash.zip](https://github.com/Tencent/MMKV/files/13723503/2023-12-15_19-23-05.0669_%2B0700-760963e560ccc42e362536aff66627379c637e62.crash.zip)

**Comment by lingol** [comment]
You should not turn off MMKV's log. And you should provide MMKV's log when crash happens.

**Comment by dongfanger2018** [comment]
> You should not turn off MMKV's log. And you should provide MMKV's log when crash happens.

which MMKVLogLevel? info or error?

**Comment by lingol** [comment]
Use the default setting.

**Comment by dongfanger2018** [comment]
> Use the default setting.

Added, but it will take time to collect the user's mmkv log and crash report.

**Comment by dongfanger2018** [comment]
[16523274.zip](https://github.com/Tencent/MMKV/files/13818357/16523274.zip)

![20240103-192233](https://github.com/Tencent/MMKV/assets/153170234/a104cdc8-ee58-440d-ba4b-4f854e86d6a7)

![image](https://github.com/Tencent/MMKV/assets/153170234/ab4ad1d1-9d39-4ac4-9c6b-3601c59de24d)

new crash user, the stack is same as old.
mmkv log has been uploaded, but log at crash moment has been flushed, don't know the following mmkv log can help?

the issue will updated as soon as I get new log

**Comment by lingol** [comment]
According to your log, the MMKV file **mmkv.user.16523274** is corrupted. You might consider delete it for this user.

**Comment by lingol** [comment]
A later log with successful loading on the file shows that the file is considerable **LARGE**. It's over 1GB. No wonder it's constantly fail to load. 
Something must be wrong with your logic. You should check on what cause it expand this large. Maybe it's too much keys, or maybe some very large value is inside?
>2024-01-02 01:57:52.513 [INFO] [KVManager:258]: [KV] info file:MMKV_IO.cpp|line:78|funcname:loadFromFile|message:Optional("loading [mmkv.user.16523274] with 562480594 actual size, file size 1073741824, InterProcess 0, meta info version:4")
>2024-01-02 01:57:53.051 [INFO] [KVManager:258]: [KV] info file:MMKV_IO.cpp|line:127|funcname:loadFromFile|message:Optional("loaded [mmkv.user.16523274] with 9088 key-values")

**Comment by lingol** [comment]
Closed due to inactive.

**Comment by dongfanger2018** [comment]
Is there an approach to limit the mmkv file size and reduce the count of keys? 
otherwise developers have to delete key-value items and call trim method in business logic layer

**Comment by lingol** [comment]
Yep, you have to do it by yourself. @dongfanger2018

**Comment by dongfanger2018** [comment]
can you give a suggestion on max number count of keys and max filesize of store file
