### ISSUE TITLE
[Help] Cross complie for aarch64(arm64) hosted on amd64 questions

### ISSUE THREAD

**Issue by catundercar** [Tencent/MMKV#1212]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin
Golang

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

arm64 linux

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone
Git

### What's the issue?

Use `[gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz](https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz)` to cross complie for arm64 on my ubuntu(amd64).

1.  Direct compile error:
![6728189a-4ba1-4837-bebe-6a7ad96dd69a](https://github.com/Tencent/MMKV/assets/24569795/27e509f5-30f3-4e7f-aace-f6e3ec1776af)

2. Then turn on the preprocess directive `MMKV_DISABLE_CRYPT`,  successfully generated two static libraries.
3. However, when cross-compiling the test through cgo, the following error was reported：
![db09fe41-eafd-4e87-9884-447bd2720857](https://github.com/Tencent/MMKV/assets/24569795/b34e5cd8-94ff-44a3-aaa6-7c152ab0a18a)

I tried to build the `libz.a`, and add the `LD_PATH`, but still the same error.

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
I'm confused, do you want to use MMKV in POSIX (C++), or POSIX (golang)?

**Comment by catundercar** [comment]
Golang
________________________________
发件人: Guo Ling ***@***.***>
发送时间: Monday, December 25, 2023 11:54:03 AM
收件人: Tencent/MMKV ***@***.***>
抄送: CatUnderCar ***@***.***>; Author ***@***.***>
主题: Re: [Tencent/MMKV] [Help] Cross complie for aarch64(arm64) hosted on amd64 questions (Issue #1212)


I'm confused, do you want to use MMKV in POSIX (C++), or POSIX (golang)?

―

**Comment by catundercar** [comment]
> I'm confused, do you want to use MMKV in POSIX (C++), or POSIX (golang)?

Golang

**Comment by lingol** [comment]
If you have defined `MMKV_DISABLE_CRYPT`, there's no way the error will occur. 
What exactly did you mean and run, when you said _cross-compiling the test through cgo_ in your step 3?

**Comment by lingol** [comment]
I don't think you have followed the wiki very faithfully. https://github.com/Tencent/MMKV/wiki/golang_setup

**Comment by catundercar** [comment]
> If you have defined `MMKV_DISABLE_CRYPT`, there's no way the error will occur. What exactly did you mean and run, when you said _cross-compiling the test through cgo_ in your step 3?

build error info: .../aarch64-linux-gnu/bin/ld: cannot find -lz

**Comment by catundercar** [comment]
Sorry, picture pined in the wrong place. I changed it.

**Comment by lingol** [comment]
Now the problem has narrowed down to how to link (well build it first in your case) in armv8 Linux for Golang.
First, forget about cross-compiling. Have you successfully built and linked it in native Linux for Golang? 
If not, try to solve it first. There's a high chance that you will solve two problems at once.
If yes, then Google about how to link zlib in cross-compiling. I'm not a professor in that area. So God bless you, you are on your own.

**Comment by lingol** [comment]
>I tried to build the libz.a, and add the LD_PATH, but still the same error.

I think when you said that, you are building zlib for amd64 and adding it to the native LD_PATH. Just saying.

**Comment by catundercar** [comment]
I did it:
![image](https://github.com/Tencent/MMKV/assets/24569795/97f040a8-50fc-407f-9592-e08785c6720e)
And there is some debug info:
![image](https://github.com/Tencent/MMKV/assets/24569795/f49a76b0-f9fb-4468-b3fe-92ff82207dae)

**Comment by lingol** [comment]
Like I said, you are on your own.

**Comment by catundercar** [comment]
> Like I said, you are on your own.

Yeap, I moved the `libz.a` to the `lib` library which is under the `mmkv`, and it compiled passed. So excited！The strange thing is that when I specify `LD_LIBRARY_PATH` it doesn't work.

**Comment by lingol** [comment]
> Yeap, I moved the `libz.a` to the `lib` library which is under the `mmkv`, and it compiled passed. So excited！

Congratulations on that.
