### ISSUE TITLE
iOS multiProcess bugly会有卡死日志

### ISSUE THREAD

**Issue by xujianbo12345** [Tencent/MMKV#1219]
我看了卡顿日志出现的版本，正好是开启了mutiProcess的版本开始的 正好这个卡顿日志就停留在InterProcessLock 这边，是iOS 下mutiProcess有问题吗，最早版本我们用的是默认创建的是singleProcess的没有发现类似的卡死日志记录
<img width="812" alt="image" src="https://github.com/Tencent/MMKV/assets/17424004/e334f89a-df4c-4be2-81f0-12da4de941f7">
![image](https://github.com/Tencent/MMKV/assets/17424004/70c13e2e-cc0d-4fcd-a6af-3d7a438b59c6)

**Comment by lingol** [comment]
That's not helping. As I have pointed out before, you should capture other threads as well.

**Comment by lingol** [comment]
Closed due to inactive.
