### ISSUE TITLE
privacy manifest for third part sdk

### ISSUE THREAD

**Issue by zziazm** [Tencent/MMKV#1220]
Could you please provide Privacy Manifest support for MMKV ? Some relevant links as follows:
https://developer.apple.com/support/third-party-SDK-requirements/
Thanks

**Comment by lingol** [comment]
MMKV doens' collect any privacy data. I don't see why we need to provide the so-called Privacy Manifest file.

**Comment by zziazm** [comment]
[Describing use of required reason API
](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc)
Do MMKV need to add this to the privacy manifest?
I searched globally and found this "mach_absolute_time" in MMKV_OSX.cpp.

**Comment by lingol** [comment]
Problem solved.

**Comment by zlmac** [comment]
Sorry to bring this up again，today our app submit to App Store and received a reminding email from Apple，
I searched globally and still found "fstat(_:_:)" and "lstat(_:_:)"API used in MMKV，so i think you should add a privacyInfo file like other SDK such as Alamofire and SDWebImage

**Comment by lingol** [comment]
Oh, what a pain in the ass. I'm forced to use alternative methods to get file size.

**Comment by zlmac** [comment]
Sorry to interrupt your dev modify, there is no need to avoid using privacy API, Apple just tell us to add the reason for it, and a question for your avoid using, I'm not ensure that there are no other privacy APIs, So I recommend adding the privacy manifest file directly,  It's just a plist file, and filling in a few corresponding keys/values.

[https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api]

**Comment by lingol** [comment]
I found it absurd and refused to comply.

**Comment by github-xiaogang** [comment]
@lingol Hi, the privacy manifest includes two items:
1、**[Collect Data]** Declare the data collected by your app or by third-party SDKs.
2、**[Privacy API]** Ensure your use of covered API is consistent with policy.

About the first item, I believe MMKV does not collect any privacy data, but the second item I think should be considered more, because MMKV uses the NSUserDefaults API. 
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401

**Comment by lingol** [comment]
No. MMKV does not use the `NSUserDefaults` API, at all. 
MMKV on iOS does provide a method for users to migrate data from NSUserDefaults, but it's on a created NSUserDefaults instance whose data is already retrieved by the user. https://github.com/Tencent/MMKV/blob/master/iOS/MMKV/MMKV/libMMKV.mm#L1039

**Comment by lingol** [comment]
To make things clear, let's drop it as well. https://github.com/Tencent/MMKV/commit/06797a74505043ede9b239afe244cab0d3623aa5

**Comment by lingol** [comment]
It's released in [v1.3.5](https://github.com/Tencent/MMKV/releases/tag/v1.3.5).
