### ISSUE TITLE
flutter开发，升级AGP >=8，报错

### ISSUE THREAD

**Issue by ruiyong-lee** [Tencent/MMKV#1224]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> Dart、Kotlin

### The version of MMKV

> e.g. v1.3.2

### The platform of MMKV

> Flutter

### The installation of MMKV

> Pub.dev

### What's the issue?

安卓端升级升级AGP >=8，编译时会提示命名空间错误

### What's the log of MMKV when that happened?

Incorrect package="com.tencent.mmkvflutter" found in source AndroidManifest.xml: D:\Pub\hosted\pub.dev\mmkv-1.3.2\android\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
Recommendation: remove package="com.tencent.mmkvflutter" from the source AndroidManifest.xml: D:\Pub\hosted\pub.dev\mmkv-1.3.2\android\src\main\AndroidManifest.xml.

**Comment by lingol** [comment]
And what's your suggestion? If the `setting namespace via the package attribute` is removed, will it work on AGP < 8 as well?

**Comment by lingol** [comment]
Released with [v1.3.3](https://github.com/Tencent/MMKV/releases/tag/v1.3.3).
