### ISSUE TITLE
Duplicate class dalvik.annotation.optimization.FastNative

### ISSUE THREAD

**Issue by kexuejin** [Tencent/MMKV#1227]
## Note:
Duplicate class dalvik.annotation.optimization.FastNative found in modules mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and tracing-perfetto-1.0.0-runtime (androidx.tracing:tracing-perfetto:1.0.0)
     
### The language of MMKV

> Kotlin

### The version of MMKV

> v1.3.2  

### The platform of MMKV

>  Android

### The installation of MMKV

> Maven 

### What's the issue?

Duplicate class dalvik.annotation.optimization.FastNative found in modules mmkv-1.3.2-runtime (com.tencent:mmkv:1.3.2) and tracing-perfetto-1.0.0-runtime (androidx.tracing:tracing-perfetto:1.0.0)

**Comment by kaitian521** [comment]
I am fixing this now.

**Comment by lingol** [comment]
> I am fixing this now.

Hi, can you make it today? I'm going to release a new version soon.

**Comment by kaitian521** [comment]
> > I am fixing this now.
> 
> Hi, can you make it today? I'm going to release a new version soon.

absolutely

**Comment by kaitian521** [comment]
https://github.com/Tencent/MMKV/pull/1228/files
