### ISSUE TITLE
Android native crash

### ISSUE THREAD

**Issue by bruce-wbh** [Tencent/MMKV#123]
### The language of MMKV

> java

### The version of MMKV

> 1.0.12

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

> ABI: 'arm64'
pid: 26331, tid: 26384, name: test_thread_au  >>> com.test.myapp <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x76d822c000
    x0   00000076d822b004  x1   5f30333935323331  x2   ffffffffffffffed  x3   00000076d822bf71
    x4   000000764d3b2fad  x5   000000764d3b2fc0  x6   3131313031315f31  x7   35315f31222c2231
    x8   3133343139393234  x9   31315f305f373738  x10  31315f3131313031  x11  7d5d223131313130
    x12  315f305f30333935  x13  315f313131313031  x14  3131313031315f30  x15  00000076d822bf84
    x16  000000763b4f7e40  x17  00000076d9a9e390  x18  0000007656400080  x19  000000764d20d0c0
    x20  0000000000000ffd  x21  0000000000000ffb  x22  00000076395d4b60  x23  0000000000000fc3
    x24  0000000000000001  x25  00000076395d7588  x26  0000007638847e40  x27  0000007638847e80
    x28  0000000000000040  x29  00000076395d4980  x30  000000763b4e128c
    sp   00000076395d4970  pc   00000076d9a9e59c  pstate 0000000080000000
    v0   0000000000000ffd000000764d3b2000  v1   0000000000000000000000003f800000
    v2   000000000000000000000000402aaaab  v3   0000000000000000000000003f400000
    v4   00000000000000008020080200000000  v5   40000000400000004000000000000000
    v6   00000000000000000000000000000000  v7   80200802802008028020080280200802
    v8   00000000000000000000000000000000  v9   00000000000000000000000000000000
    v10  00000000000000000000000000000000  v11  00000000000000000000000000000000
    v12  00000000000000000000000000000000  v13  00000000000000000000000000000000
    v14  00000000000000000000000000000000  v15  00000000000000000000000000000000
    v16  40100401401004014010040140100401  v17  00000000a00a00000000aa0040404000
    v18  00000000000000008020080200000000  v19  00000000000000000000002800000028
    v20  00000000000000000000107200000f52  v21  00000000000000000000003200000032
    v22  0000000000000000000019820000184c  v23  00000000000000000000003c0000003c
    v24  000000000000000000001b9600001ad6  v25  00000000000000000000004600000046
    v26  00000000000000000000a67000001ca0  v27  00000000000000000000000000000000
    v28  00000000000000000000000000000000  v29  00000000000000000000000000000000
    v30  00000000000000000000000000000000  v31  00000000000000000000000000000000
    fpsr 00000013  fpcr 00000000

backtrace:
    #00 pc 000000000001e59c  /system/lib64/libc.so (memcpy+524)
    #01 pc 000000000000d288  /data/app/com.test.myapp-15WSdCIbBW1y7J-k5pqw9g==/lib/arm64/libmmkv.so
	
stack:
         00000076395d48f0  00000076d9b76924  [anon:.bss]
         00000076395d48f8  0000007649df2588  [anon:libc_malloc]
         00000076395d4900  0000007649df2580  [anon:libc_malloc]
         00000076395d4908  0000007638848fe0  [anon:libc_malloc]
         00000076395d4910  00000076395d4980
         00000076395d4918  00000076d9b2d224  /system/lib64/libc.so (je_free+124)
         00000076395d4920  0000000000000001
         00000076395d4928  96d9e0ae2503a954
         00000076395d4930  0000000000000fc3
         00000076395d4938  000000764d20dfc0  [anon:libc_malloc]
         00000076395d4940  00000076395d4b60
         00000076395d4948  96d9e0ae2503a954
         00000076395d4950  0000000000000fc3
         00000076395d4958  0000007638848fe0  [anon:libc_malloc]
         00000076395d4960  00000076395d4b60
         00000076395d4968  0000000000000ffb
    #00  00000076395d4970  0000007638847e28  [anon:libc_malloc]
         ........  ........
    #01  00000076395d4970  0000007638847e28  [anon:libc_malloc]
         00000076395d4978  0000007638878000  [anon:libc_malloc]
         00000076395d4980  00000076395d4a20
         00000076395d4988  000000763b4dcf4c  /data/app/com.test.myapp-15WSdCIbBW1y7J-k5pqw9g==/lib/arm64/libmmkv.so
         00000076395d4990  00000076395d4a20
         00000076395d4998  0000000000000000
         00000076395d49a0  0000000000000000
         00000076395d49a8  0000007638876000  [anon:libc_malloc]
         00000076395d49b0  000000764d20dfc0  [anon:libc_malloc]
         00000076395d49b8  0000007638848fe0  [anon:libc_malloc]
         00000076395d49c0  000000764d3b2000  [anon:libc_malloc]
         00000076395d49c8  0000000000000ffd
         00000076395d49d0  0000000000000000
         00000076395d49d8  96d9e0ae2503a954
         00000076395d49e0  00000076388780f8  [anon:libc_malloc]
         00000076395d49e8  00000076388780f8  [anon:libc_malloc]
> 
> I've got a NativeCrash while using mmkv, seems something wrong with "memcpy". Is there anyway to avoid this crash?

**Comment by lingol** [comment]
Please provide de-symbolized crash report. It's impossible to analyze your problem without function name and line number.

**Comment by lingol** [comment]
If you don't know how to do it, just send me a reproducible demo project to guoling@tencent.com.

**Comment by lingol** [comment]
Close due to inactive.
