### ISSUE TITLE
[iOS] Issues when archiving project

### ISSUE THREAD

**Issue by vs47864** [Tencent/MMKV#1232]
### The language of MMKV

Swift

### The version of MMKV

1.3.3

### The platform of MMKV

iOS

### The installation of MMKV

Cocoapods but with modular_headers set to true

### What's the issue?

Archiving is failing with attached error when in pod file we have both MMKV and MMKVAppExenstion. This started to happen with Xcode 15 on Xcode 14 all is good.  When I remove MMKV and MMKVAppExenstion archiving succeeds. I tried with just MMKV and modular headers set to true and that works same with just MMKVAppExenstion. The issue is if I import both of them like this:

#if APP_EXTENSION
import MMKVAppExtension
#else
import MMKV
#endif

[swift_error.txt](https://github.com/Tencent/MMKV/files/14063448/swift_error.txt)

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
>4  swift-frontend           0x0000000107ebcadc swift::SILDeserializer::readVTable(llvm::PointerEmbeddedInt<unsigned int, 31>) + 1492

Looks like a Swift compiler bug to me.

**Comment by lingol** [comment]
Anyway, would you like to provide a demo project to further investigate?

**Comment by lingol** [comment]
Closed due to inactive.
