### ISSUE TITLE
kv_system和crc文件移动到其他app 不能读取和写入

### ISSUE THREAD

**Issue by sanlic** [Tencent/MMKV#1235]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
What do you mean by saying ** kv_system**?

**Comment by sanlic** [comment]
意思是，我在第一个app里用mmkv 保存了部分数据，然后移动/data/data/files/mmkv/kv_system 和 kv_system.crc到第二个app的data目录下，在第二个app内无法读取和修改kv_system

**Comment by lingol** [comment]
Quite surprising. Can you provide logs of MMKV in your second App?
