### ISSUE TITLE
Please modify README about install in `MMKV for Win32`

### ISSUE THREAD

**Issue by colmugx** [Tencent/MMKV#1238]
## Note:
here any information in `MMKV for Win32`

```
2. Add Win32/MMKV/MMKV.vcxproj to your solution;
```

But `Win32/MMKV/MMKV.vcxproj` does not exist since 1.0.x

Actually It's in `Core` right?

**Comment by lingol** [comment]
Sure. 
I have asked for volunteers for this update, both inside Tencent and outside in the _community_. However, I have never got anything in return.

**Comment by colmugx** [comment]
Ok i will fix it
