### ISSUE TITLE
MMKV::checkFileCRCValid Got CRC error

### ISSUE THREAD

**Issue by keepDeveloper** [Tencent/MMKV#1241]
### The version of MMKV

MMKV, ~> 1.3.1
MMKVAppExtension, ~> 1.3.1

### The platform of MMKV

iOS

### What's the issue?

MMKV goes to the function checkFileCRCValid Got CRC Error  ?

**Comment by 666666liu66666** [comment]
![Uploading WeChat1bbf63705e6a1e7db08e003bc27591c4.jpg…]()

**Comment by keepDeveloper** [comment]
<img width="1877" alt="截屏2024-02-28 11 10 52" src="https://github.com/Tencent/MMKV/assets/20952028/30040a24-2e7c-49d7-a2f0-a2c230cf13fb">

**Comment by lingol** [comment]
What's your problem? I don't quite get your point.
