### ISSUE TITLE
checkcrc anr when the file it too large

### ISSUE THREAD

**Issue by baiiu** [Tencent/MMKV#1243]
### The language of MMKV
> Objective-C, Swift

### The version of MMKV
> v1.2.2  

### The platform of MMKV
> iOS

### The installation of MMKV
> Git clone

### What's the issue?
When the file is larger than 4M, there is a possibility that checkcrc anr will occur.
How do your fix this problem, hope to get your apply.

### What's the log of MMKV when that happened?
libz.1.dylib	_adler32_z()         
libz.1.dylib	_crc32_z()         
xxx	            mmkv::MMKV::checkFileCRCValid(MMKV.cpp:411)         
xxx	            mmkv::MMKV::checkDataValid(MMKV_IO.cpp:233)         
xxx	            mmkv::MMKV::loadFromFile(MMKV_IO.cpp:78)         
xxx         	mmkv::MMKV::MMKV(MMKV.cpp:120)         
xxx	            mmkv::MMKV::MMKV(MMKV.cpp:92)         
xxx	            mmkv::MMKV::mmkvWithID(MMKV.cpp:231)[inlined]         
xxx	            -[MMKV initWithMMapID:cryptKey:rootPath:mode:]([libMMKV.mm:216](http://libmmkv.mm:216/))         
xxx         	+[MMKV mmkvWithID:cryptKey:rootPath:mode:]([libMMKV.mm:191](http://libmmkv.mm:191/))

**Comment by lingol** [comment]
Don't use libz's soft implementation of crc32. Use a tuned implementation of crc32 (such as hardware accelerated) if possible. MMKV has some hardware accelerated crc32 inside. I'm not sure why your App doesn't use it.

By the way, you should provide info needed by following the issue template. Things like language & platform help.

**Comment by lingol** [comment]
And 4M is not considered **LARGE** for MMKV. Generally speaking, MMKV handles files in that size range very well.

**Comment by baiiu** [comment]
appreciate for your apply and I'm sorry for that. our platform is iOS.

there is a commit: [turn off crc32 optimization for iOS](https://github.com/Tencent/MMKV/commit/093f9efc2ec4ea4d6e8641838b0baebccc7d4ca4),  does it have any problems on iOS.

**Comment by lingol** [comment]
It's turned off because back then there were repeated reports from GitHub issues that some device crashed on these crc32 instructions. Theoretically, the libz provided by Apple is already tuned with accelerated hardware.

Exactly how big is your file when this ANR happens?
