### ISSUE TITLE
【Android】1.3.3版本多进程初始化，导致数据丢失

### ISSUE THREAD

**Issue by pinguo-hedongjin** [Tencent/MMKV#1245]
1、初始化代码
override fun onCreate() {
        super.onCreate()
       
        if (isMainProcess) {
            MMKV.initialize(context) { ReLinker.loadLibrary(context, it) }
            MMKV.registerHandler(object : MMKVHandler {
                o

                override fun mmkvLog(
                    level: MMKVLogLevel?,
                    file: String?,
                    line: Int,
                    func: String?,
                    message: String?
                ) {
                    val log = "<$file" + ":" + line + "::" + func + "> " + R.id.message
                    when (level) {
                        MMKVLogLevel.LevelDebug -> logd("MMKVHelper", log)
                        MMKVLogLevel.LevelInfo -> logi("MMKVHelper", log)
                        MMKVLogLevel.LevelWarning -> logw("MMKVHelper", log)
                        MMKVLogLevel.LevelError -> loge("MMKVHelper", log)
                        else -> logv("MMKVHelper", log)
                    }
                }
            })
        } else if (isPushProcess) {
            MMKV.initialize(context) { ReLinker.loadLibrary(context, it) }
            MMKV.registerHandler(object : MMKVHandler {
                override fun mmkvLog(
                    level: MMKVLogLevel?,
                    file: String?,
                    line: Int,
                    func: String?,
                    message: String?
                ) {
                    val log = "<$file" + ":" + line + "::" + func + "> " + R.id.message
                    when (level) {
                        MMKVLogLevel.LevelDebug -> logd("MMKVHelper", log)
                        MMKVLogLevel.LevelInfo -> logi("MMKVHelper", log)
                        MMKVLogLevel.LevelWarning -> logw("MMKVHelper", log)
                        MMKVLogLevel.LevelError -> loge("MMKVHelper", log)
                        else -> logv("MMKVHelper", log)
                    }
                }
            })
        }
    }
2、日志打印
<img width="1522" alt="截屏2024-03-11 16 58 04" src="https://github.com/Tencent/MMKV/assets/11845600/a22dc391-0613-4dda-9265-18f00089d0fc">

问题：
多进程初始化后，之前保存的数据丢失

**Comment by lingol** [comment]
Your so-called _log_ doesn't print anything valuable. It's impossible to do any further investigation.
Check your log printing code again.

**Comment by pinguo-hedongjin** [comment]
What further information do we need to provide?

**Comment by lingol** [comment]
> Your so-called _log_ doesn't print anything valuable. It's impossible to do any further investigation. Check your log printing code again.

These.

**Comment by pinguo-hedongjin** [comment]
I found that the same mmapID has multi-process access, but it is still declared in SINGLE_PROCESS_MODE mode, and there is currently a problem that the data that has been written to disk before cannot be read after restarting;
Is this as expected?
