### ISSUE TITLE
iOS mmkv 沙盒目录下 权限问题

### ISSUE THREAD

**Issue by xiaoyeying** [Tencent/MMKV#1246]
iOS Objective-C编码下

通过Cocoapods管理 MMKV_VERSION = "v1.3.2" 

记录到如下日志
<MemoryFile.cpp:218::reloadFromFile> fail to open:/var/mobile/Containers/Data/Application/4E2F1FAB-F402-4BFE-9035-87BD355F6A72/Library/com.zhibo8.client81136870/UserDefault/mmkv/UserDefault, Operation not permitted

<MiniPBCoder_OSX.cpp:126::decodeOneMap> InvalidProtocolBuffer truncatedMessage

<MMKV.cpp:417::checkFileCRCValid> check crc [UserDefault] fail, crc32:1965248185, m_crcDigest:2381180596

<MMKV_IO.cpp:71::loadFromFile> file [/var/mobile/Containers/Data/Application/C931BEA1-C36B-4BFB-A247-86A18126580F/Library/com.zhibo8.client81136870/UserDefault/mmkv/UserDefault] not valid

**Comment by lingol** [comment]
Why did your location change? At one time it's
> /var/mobile/Containers/Data/Application/**4E2F1FAB-F402-4BFE-9035-87BD355F6A72**/Library/com.zhibo8.client81136870/UserDefault/mmkv/UserDefault

Later it becomes:
>/var/mobile/Containers/Data/Application/**C931BEA1-C36B-4BFB-A247-86A18126580F**/Library/com.zhibo8.client81136870/UserDefault/mmkv/UserDefault

**Comment by lingol** [comment]
I don't think you have provided logs in the order as it happens. Please provide logs with timestamps.
And don't mix logs from different devices/users.

**Comment by xiaoyeying** [comment]
抱歉，谢谢解答

这个是相同设备的日志信息，几乎是同一时间点记录到的日志 
时间点 2024-0310-1824 日志信息<MemoryFile.cpp:94::open> fail to open [/var/mobile/Containers/Data/Application/4E2F1FAB-F402-4BFE-9035-87BD355F6A72/Library/com.zhibo8.client81136870/UserDefault/mmkv/UserDefault.crc], 1(Operation not permitted)
时间点2024-0310-1824 日志信息 <MemoryFile.cpp:94::open> fail to open [/var/mobile/Containers/Data/Application/4E2F1FAB-F402-4BFE-9035-87BD355F6A72/Library/com.zhibo8.client81136870/UserDefault/mmkv/UserDefault], 1(Operation not permitted)

问题:
我们这边记录到用户读写均失效的情况，未知原因，日志较多，这个是截取一部分比较典型的日志

疑问点:
我这边的疑问点是正常状态下读取均是正常的，为何会存在沙盒文件的权限错误日志，这种是否会导致无法正常读写数据

**Comment by lingol** [comment]
On that device, does things work normally before? Or does it never work? You should provide **as many logs of MMKV as possible**. With just these two single logs it's impossible to do any diagnosis.

**Comment by lingol** [comment]
Last time I checked, on iOS an App is always sanboxed. So I don't quite understand why you said "正常状态下读取均是正常的". What do you mean by saying "正常状态"?

**Comment by xiaoyeying** [comment]
应用程序线上环境处于沙盒状态下，有记录到的绝大部分是以上相似的日志，除此之外还有类似日子
<MMKV.cpp:417::checkFileCRCValid> check crc [UserDefault] fail, crc32:2447369466, m_crcDigest:2915453613

**Comment by xiaoyeying** [comment]
应用程序线上环境处于沙盒状态下，有记录到的绝大部分是以上相似的日志，除此之外还有类似日子
<MMKV.cpp:417::checkFileCRCValid> check crc [UserDefault] fail, crc32:2447369466, m_crcDigest:2915453613

**Comment by lingol** [comment]
> > On that device, does things work normally before? Or does it never work? You should provide **as many logs of MMKV as possible**. With just these two single logs it's impossible to do any diagnosis.

**Comment by lingol** [comment]
One more useless response and this issue will be locked down. Please provide info as required.

**Comment by lingol** [comment]
Closed due to inactive.
