### ISSUE TITLE
软件升级MMKV文件会被清除！！！

### ISSUE THREAD

**Issue by guozhiqiang123** [Tencent/MMKV#125]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin
java

### The version of MMKV

> e.g. v1.0.10
v1.0.10

### The platform of MMKV

> e.g. iOS or Android
Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 软件升级的时候MMKV文件会被清除，是我使用的方式不对吗？还是暂时不支持软件升级不被清除？
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
NO, there's no such thing inside MMKV that will cause file lost after App upgrading. Check your usage twice.

**Comment by lingol** [comment]
And by the way, MMKV's current version is v1.0.13, you might consider update yours.

**Comment by lingol** [comment]
Close due to inactive.

**Comment by luckyAF** [comment]
version 1.0.19
我也遇到了 有时候版本升级会导致部分数据消失，有时候crash了应用重启也会导致部分数据消失

**Comment by lingol** [comment]
> version 1.0.19
> 我也遇到了 有时候版本升级会导致部分数据消失，有时候crash了应用重启也会导致部分数据消失

Well can you provide related logs of MMKV when it happened?
