### ISSUE TITLE
你好，有个崩溃帮忙看下

### ISSUE THREAD

**Issue by stone4302** [Tencent/MMKV#1252]
<img width="1122" alt="image" src="https://github.com/Tencent/MMKV/assets/17536181/79e02c3b-cc28-4827-9491-0cac0a4b1122">
你好，iOS系统，使用中偶现这个崩溃，帮忙看一下

**Comment by stone4302** [comment]
版本是：1.2.7

**Comment by lingol** [comment]
Specifically, provide **logs of MMKV** when this crash happened.

**Comment by stone4302** [comment]
因为是偶现的，只有bugly的崩溃日志，目前能看到的只有图中的哪些信息

**Comment by lingol** [comment]
No logs no investigation, sorry.
