### ISSUE TITLE
支持win x64吗？一直编译不了，能帮忙看看吗

### ISSUE THREAD

**Issue by Mr-Peng** [Tencent/MMKV#1254]
```[tasklist]
### Tasks
```

**Comment by lingol** [comment]
No. Not yet. And it's not in our schedule.

**Comment by Mr-Peng** [comment]
1>core\x64\Debug\AESCrypt.obj : fatal error LNK1112: 模块计算机类型“x64”与目标计算机类型“x86”冲突

**Comment by Mr-Peng** [comment]
教程里写着
编译工程 (Release 或 Debug, x86 或 x64);

**Comment by lingol** [comment]
Update: After consulting with fellow developers in the Windows platform, we will add x64 support in the future.

**Comment by lingol** [comment]
> 教程里写着 编译工程 (Release 或 Debug, x86 或 x64);

Well, that's an error in that wiki page. We never supported x64. In fact, we always call it Win32 almost everywhere in the whole wiki repo.

**Comment by Mr-Peng** [comment]
> > 教程里写着 编译工程 (Release 或 Debug, x86 或 x64);
> 
> Well, that's an error in that wiki page. We never supported x64. In fact, we always call it Win32 almost everywhere in the whole wiki repo.

了解，谢谢解答。

**Comment by lingol** [comment]
It's supported in the dev branch. You can try it out.

**Comment by lingol** [comment]
It's released in [v1.3.5](https://github.com/Tencent/MMKV/releases/tag/v1.3.5).
