### ISSUE TITLE
Non-fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmmkv.so" not found

### ISSUE THREAD

**Issue by shenhe123** [Tencent/MMKV#1257]
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: library "libmmkv.so" not found
java.lang.Runtime.loadLibrary0 (Runtime.java:1082)

java.lang.System.loadLibrary (System.java:1661)
com.tencent.mmkv.MMKV.doInitialize (MMKV.java:222)
com.tencent.mmkv.MMKV.initialize (MMKV.java:204)
com.tencent.mmkv.MMKV.initialize (MMKV.java:90)
io.bitmax.exchange.core.account.AccountManger.getMMKV (AccountManger.java:60)
io.bitmax.exchange.core.account.AccountManger.getUser (AccountManger.java:144)
io.bitmax.exchange.core.account.AccountManger.isLogin (AccountManger.java:181)
io.bitmax.exchange.trading.nvwsocket.WebSocketManager.connect (WebSocketManager.java:108)
io.bitmax.exchange.trading.nvwsocket.WebSocketManager.checkIsConnection (WebSocketManager.java:377)
io.bitmax.exchange.trading.nvwsocket.WebSocketManager.initSummaryJsonParser (WebSocketManager.java:304)
io.bitmax.exchange.market.viewmodel.BaseWsMarketSocketViewModel.<init> (BaseWsMarketSocketViewModel.java:44)
io.bitmax.exchange.market.viewmodel.MarketAllViewModel.access$getHotSearchComparator$cp (MarketAllViewModel.kt:36)
io.bitmax.exchange.market.viewmodel.MarketAllViewModel.<init> (MarketAllViewModel.kt:36)
io.bitmax.exchange.core.BMApplication.init (BMApplication.kt:97)
io.bitmax.exchange.core.BMApplication.onCreate (BMApplication.kt:74)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1316)

com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)

I collected a batch of logs. The mmkv version I used is 2.1.14. I found that the hardware information of the model reporting this crash is the Cortex micro-architecture.
CPU architecture | 64-bit
Microarchitecture | 4x 2.4 GHz – Cortex-A78
                                 4x 2.0 GHz – Cortex-A55
                                Cortex-A76
                                Cortex-A55

Models involved：Honor Pad X8、Galaxy A54 5G、Huawei CDY-AN95、OnePlus Nord CE 2、Huawei MED-LX9、LG G7 ThinQ、Samsung Galaxy A22
Hope this problem can be solved as soon as possible, thank you!

**Comment by lingol** [comment]
We simply don't accept issues of `UnsatisfiedLinkError` anymore. Because it's clearly not a lib dev's problem.
