### ISSUE TITLE
swift function name

### ISSUE THREAD

**Issue by passerbyloo** [Tencent/MMKV#126]
Now the swift get bool value function name is `boolValue(forKey:)`
Will it be updated to `bool(forKey:)`, it seems standard with mmkv oc function call(and UserDefaults also use .bool)

**Comment by lingol** [comment]
That's a good suggestion.

**Comment by passerbyloo** [comment]
i try to make it `bool(forKey:)` too, and it will auto change to _Bool.
Try to find out the solution

**Comment by lingol** [comment]
I believe is a bug in clang. I have created an [issue](https://bugs.swift.org/browse/SR-9380) for Swift team, let's wait for their response.

**Comment by lingol** [comment]
Awesome.

**Comment by passerbyloo** [comment]
Thx
