### ISSUE TITLE
 How to use it directly in C++?

### ISSUE THREAD

**Issue by maoxing** [Tencent/MMKV#1270]
Can I directly use the source code in the Core directory to compile Android, iOS, and Windows platforms myself? 

I need to use it in my C++ shared library, so what should I do?

Looking forward to your reply！

**Comment by maoxing** [comment]
Can I directly use the source code in the Core directory to compile Android, iOS, and Windows platforms myself? 

I need to use it in my C++ shared library, so what should I do?

Looking forward to your reply！

**Comment by lingol** [comment]
Assuming you are familiar with cmake, the core has a cmake project that you can use directly.

**Comment by maoxing** [comment]
thanks s lot, i'll do it
