### ISSUE TITLE
Cheers! How to start to add #import <MMKV/MMKV.h> to my source file?

### ISSUE THREAD

**Issue by EchoingA** [Tencent/MMKV#1271]
### The language of MMKV
Swift

### The version of MMKV

>  v1.2.2  

### The platform of MMKV

> iOS 

### The installation of MMKV

> Cocoapods

### What's the issue?

<img width="721" alt="Screenshot 2024-04-20 at 22 01 52" src="https://github.com/Tencent/MMKV/assets/85376543/15aad700-5189-4d90-9a26-1d19d87f7605">

**Comment by lingol** [comment]
For Swift I believe it is 

import MMKV;

**Comment by EchoingA** [comment]
yeah thx, i think the problem is that i mistake the framework file search instead of header file search. thx for reply.
