### ISSUE TITLE
minsdk 23 bump

### ISSUE THREAD

**Issue by carlonzo** [Tencent/MMKV#1279]
Hi, 
here to ask what is the reason that made you decide to bump the minsdk from 19 to 23? 

We have been affected by this and we will not be able to get mmkv updates anymore, and I was wondering what specific features were required by mmkv that pushed this decision.

google services, androidx, compose are all minsdk 21 as its a good compromise to support old devices while having a good coverage of system apis.

Thanks for your work!

**Comment by lingol** [comment]
API level 23 aka Android 6.0 is released 9 years ago. It's time to upgrade your target device.

In fact, WeChat already done that for quite a while now.

If you really want it, build it by source code yourself.

**Comment by carlonzo** [comment]
I think this is a legit question, why would you close the issue?

**Comment by lingol** [comment]
I already answered the question. There's no more point in repeating myself.

**Comment by lingol** [comment]
>If so, why block the users of this sdk who are still on minsdk 19-22 if this is not a required change?

One more thing, we are blocking no one. MMKV is **open-sourced**. If you are not happy with how things were done, you can just clone and change whatever you like.

**Comment by lingol** [comment]
[v1.3.7 LST](https://github.com/Tencent/MMKV/releases/tag/v1.3.7 ) has just been release.

**This Long Term Support (LTS) release** primarily reintroduces support for the ARMv7 architecture and lowers the minimum SDK version requirement to 21. Please note that only critical bug fixes will be applied to the 1.3.x series. 

New features will be introduced in version 2.0 and later, which will discontinue support for 32-bit architectures and raise the minimum SDK version requirement to 23.
