### ISSUE TITLE
在 HarmonyOS NEXT API 11 上初始化，发生崩溃，版本 ： @tencent/mmkv":"1.3.5"

### ISSUE THREAD

**Issue by harperhpliu** [Tencent/MMKV#1284]
### The language of MMKV

> ArkTS

### The version of MMKV

> 1.3.5

Reason:Signal:SIGABRT(SI_TKILL)@0x01317b480000675f from:26463:20020040
Fault thread Info:
Tid:26463, Name:d.tim.hmos.demo
#00 pc 00000000000e3758 /system/lib/ld-musl-aarch64.so.1(raise+124)(f53778d3455c921f0e7b0f1426816b31)
#01 pc 000000000009aa54 /system/lib/ld-musl-aarch64.so.1(abort+20)(f53778d3455c921f0e7b0f1426816b31)
#02 pc 000000000007df5c /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#03 pc 0000000000060490 /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#04 pc 0000000000060354 /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#05 pc 000000000008041c /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#06 pc 0000000000080398 /data/storage/el1/bundle/libs/arm64/libmmkv.so(__cxa_throw+124)(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#07 pc 000000000003aaa0 /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#08 pc 000000000003aa64 /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#09 pc 000000000003aa28 /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#10 pc 0000000000032e0c /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)

**Comment by lingol** [comment]
MMKV requires API 12.
