### ISSUE TITLE
Fail to find any mmkv plugin dependencies

### ISSUE THREAD

**Issue by zhoushuangjian001** [Tencent/MMKV#1285]
Running pod install...                                             412ms
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: Fail to find any mmkv plugin dependencies. If you're running pod install manually, make sure flutter pub get is executed first.

     #  from /Users/shikuai/Desktop/Work_KL/ichat_linky_client/iChat/ios/Podfile:61
     #  -------------------------------------------
     #    end
     >    raise "Fail to find any mmkv plugin dependencies. If you're running pod install manually, make sure flutter pub get is executed first"
     #  end
     #  -------------------------------------------

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:335:in `rescue in block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:329:in `block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in `from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:293:in `from_file'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:206:in `podfile'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:46:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 15 Pro Max.

```[tasklist]
### Tasks
```

**Comment by zhoushuangjian001** [comment]
This morning, I suddenly got an error when compiling the project. I tried reinstalling cocoapod and ruby and re-relying on mmkv, but neither could solve the problem.

**Comment by lingol** [comment]
The script you previously added to the pod file to rename the mmkv plugin to mmkvflutter is no longer needed after v1.3.5. 
Remove them.

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/flutter_setup#ios
