### ISSUE TITLE
Importing ArkTS files to JS and TS files is not allowed. <ArkTSCheck>

### ISSUE THREAD

**Issue by AndroidLMY** [Tencent/MMKV#1297]
Importing ArkTS files to JS and TS files is not allowed. <ArkTSCheck>
![image](https://github.com/Tencent/MMKV/assets/32607888/65058450-fd46-4fc5-b88e-4628c768abd3)

**Comment by AndroidLMY** [comment]
鸿蒙API11  mmkv版本为1.3.6-beta

**Comment by AndroidLMY** [comment]
EntryAbility类不是ets导致 已关闭

**Comment by lingol** [comment]
Yep. That's a known issue. I've asked for help but currently no response for any workaround.

**Comment by lingol** [comment]
Also, there're reports on initialize crash on API 11, you should upgrade to 12 if that happens.
