### ISSUE TITLE
鸿蒙导入MMKV初始化崩溃

### ISSUE THREAD

**Issue by apple130** [Tencent/MMKV#1298]
鸿蒙导入MMKV初始化崩溃我的电脑是Mac M1芯片的和这个有关系吗 用的是模拟器不是真机
![截屏2024-05-11 16 49 31](https://github.com/Tencent/MMKV/assets/12249106/6e5553e9-7e0f-43cd-b492-ccc087f5f4d0)
![截屏2024-05-11 16 49 42](https://github.com/Tencent/MMKV/assets/12249106/5d152393-6638-404d-b5ec-8f38c172d800)
![截屏2024-05-11 16 51 14](https://github.com/Tencent/MMKV/assets/12249106/5d4e432a-9f82-45ec-a6ed-b668da861bc2)

**Comment by lingol** [comment]
Likely, your simulator is not API 12. You can check if that's true. If so, upgrade to API 12.

**Comment by apple130** [comment]
这个不能支持API 11吗

**Comment by lingol** [comment]
We started from API 12 targeting HarmonyOS NEXT, which will be released at least from 12. 
So no, API 11 is not in our plan.
