### ISSUE TITLE
鸿蒙版本存入字符串和取出字符串不匹配

### ISSUE THREAD

**Issue by wuyouuuu** [Tencent/MMKV#1300]
依赖版本："@tencent/mmkv": "1.3.5"
存入字符串 `[{"value":"让人","type":0,"source":0},{"value":"更多","type":1,"source":0}]` 
取出字符串 `[{"value":"让人","type":0,"source":0},{"value":"更多","type":1,"source":0}`  少了最后一个`]`
![image](https://github.com/Tencent/MMKV/assets/134041434/e32449f8-5f0a-458d-bfaa-bfe877142935)

**Comment by lingol** [comment]
It's fixed in 1.3.6-beta.
