### ISSUE TITLE
MMKV for HarmonyOS NEXT 在ts文件中无法使用

### ISSUE THREAD

**Issue by ysrfeng** [Tencent/MMKV#1301]
MMKV for HarmonyOS NEXT 使用的是ets抛出，怎么在ts中调用其方法

**Comment by lingol** [comment]
Yes, it's a known issue. We have asked for help but currently no solutions. https://github.com/Tencent/MMKV/issues/1282#issuecomment-2082088705

**Comment by ysrfeng** [comment]
老师，这个官方库同步的库，是用ts导出，实现逻辑是否可以参考一下
https://ohpm.openharmony.cn/#/cn/detail/@ohos%2Fmmkv，ets方式使用限制场景太多了，期望可以用ts导出

**Comment by lingol** [comment]
You just did not read my comment, didn't you? 
>MMKV's wrapper is developed in ArtTS and we don't want to change it to TS. How can we export it as TS without changing the MMKV wrapper from .ets to .ts?

**Comment by ysrfeng** [comment]
大佬我看了评论的，如果包装器不在ArtTS 中开发呢，改动大么

**Comment by lingol** [comment]
The problem is not about how or what, it is about why. Why would we or someone transfer a ArtTS file to TS file.

**Comment by lingol** [comment]
If all libraries that expose its functionality must be provided in a TS file, what's the purpose of ArtTS language in the first place? Why bother to design it at all?

**Comment by ysrfeng** [comment]
明白这个道理，主要是已经开发的功能不想动，时间来不及
