### ISSUE TITLE
【建议】建议MMKV的python端打包发布

### ISSUE THREAD

**Issue by qingqingcaoyuanlin** [Tencent/MMKV#1302]
建议MMKV的python端打包发布，在windows平台编译太麻烦了，Linux还稍微容易些。

**Comment by lingol** [comment]
I may give it a try but no guarantees.

**Comment by lingol** [comment]
For the time being, you can check out the job done by open-source contributors:
https://github.com/Tencent/MMKV/tree/dev/Win32/Python.

**Comment by qingqingcaoyuanlin** [comment]
> For the time being, you can check out the job done by open-source contributors: https://github.com/Tencent/MMKV/tree/dev/Win32/Python.

我自己编译成功了。在Ubuntu相对容易些，Windows平台花了较长时间，稀里糊涂就编译成功了，windows编译大概需要这些：VS2017、cmake，mmkv可能需要编译为dll库，libmmkv_python.cpp需增加windows平台下MMKVPath_t类型，setup.py要去除-j8，增加pthread.lib库。 晚些我把我的一些修改上传供参考，减少工作量。

**Comment by qingqingcaoyuanlin** [comment]
> For the time being, you can check out the job done by open-source contributors: https://github.com/Tencent/MMKV/tree/dev/Win32/Python.

我提交了在windows下编译的修改点，仅适用windows平台下，仅供参考。https://github.com/qingqingcaoyuanlin/MMKV/commits/master/

**Comment by qingqingcaoyuanlin** [comment]
我在windows系统调用`mmkv.MMKV.restoreOneFromDirectory`，第一次调用正常返回True，第二次调用返回False；在Ubuntu系统调用两次均返回True，请问这可能是什么问题导致的呢？
`
r-[E] <MemoryFile_Win32.cpp:257:mkPath> fail to create dir:, 3
r-[I] <MMKV.cpp:1446:restoreOneFromDirectory> restore one cached mmkv[62aa295057e4378d16a8372644e7bde9] from [D:\linqq\code\gtest\mmkv.default] to [\mmkv.default]
r-[I] <MMKV.cpp:1190:sync> MMKV::sync, SyncFlag = 1
r-[I] <MemoryFile_Win32.cpp:76:open> open fd[00000000000001A8], D:\linqq\code\gtest\mmkv.default
r-[E] <MemoryFile_Win32.cpp:341:ftruncate> fail to SetEndOfFile:1224
r-[E] <MemoryFile_Win32.cpp:430:copyFileContent> fail to truncate [344] to size [8192]
r-[I] <MemoryFile_Win32.cpp:82:close> closing fd[00000000000001A8], D:\linqq\code\gtest\mmkv.default
r-[I] <MMKV.cpp:318:clearMemoryCache> clearMemoryCache [mmkv.default]
r-[I] <MemoryFile_Win32.cpp:82:close> closing fd[0000000000000158], \mmkv.default
r-[I] <MMKV_IO.cpp:214:loadMetaInfoAndCheck> meta file [mmkv.default] has flag [0]
r-[I] <MemoryFile_Win32.cpp:76:open> open fd[0000000000000188], \mmkv.default
r-[I] <MemoryFile_Win32.cpp:181:mmap> mmap to address [0000027BBE1E0000], [\mmkv.default]
r-[I] <MMKV_IO.cpp:84:loadFromFile> loading [mmkv.default] with 3875 actual size, file size 16384, InterProcess 0, meta info version:4
r-[I] <MMKV_IO.cpp:89:loadFromFile> loading [mmkv.default] with crc 777566069 sequence 542 version 4
r-[I] <MMKV_IO.cpp:133:loadFromFile> loaded [mmkv.default] with 60 key-values
r-[I] <MMKV.cpp:1477:restoreOneFromDirectory> finish restore one mmkv[62aa295057e4378d16a8372644e7bde9], ret: 0
`

**Comment by qingqingcaoyuanlin** [comment]
`r-[E] <MemoryFile_Win32.cpp:257:mkPath> fail to create dir:, 3

r-[I] <MMKV.cpp:1446:restoreOneFromDirectory> restore one cached mmkv[62aa295057e4378d16a8372644e7bde9] from [D:\linqq\code\gtest\mmkv.default] to [\mmkv.default]

r-[I] <MMKV.cpp:1190:sync> MMKV::sync, SyncFlag = 1

r-[I] <MemoryFile_Win32.cpp:76:open> open fd[00000000000001A8], D:\linqq\code\gtest\mmkv.default

r-[E] <MemoryFile_Win32.cpp:341:ftruncate> fail to SetEndOfFile:1224

r-[E] <MemoryFile_Win32.cpp:430:copyFileContent> fail to truncate [344] to size [8192]

r-[I] <MemoryFile_Win32.cpp:82:close> closing fd[00000000000001A8], D:\linqq\code\gtest\mmkv.default

r-[I] <MMKV.cpp:318:clearMemoryCache> clearMemoryCache [mmkv.default]

r-[I] <MemoryFile_Win32.cpp:82:close> closing fd[0000000000000158], \mmkv.default

r-[I] <MMKV_IO.cpp:214:loadMetaInfoAndCheck> meta file [mmkv.default] has flag [0]

r-[I] <MemoryFile_Win32.cpp:76:open> open fd[0000000000000188], \mmkv.default

r-[I] <MemoryFile_Win32.cpp:181:mmap> mmap to address [0000027BBE1E0000], [\mmkv.default]

r-[I] <MMKV_IO.cpp:84:loadFromFile> loading [mmkv.default] with 3875 actual size, file size 16384, InterProcess 0, meta info version:4

r-[I] <MMKV_IO.cpp:89:loadFromFile> loading [mmkv.default] with crc 777566069 sequence 542 version 4

r-[I] <MMKV_IO.cpp:133:loadFromFile> loaded [mmkv.default] with 60 key-values

r-[I] <MMKV.cpp:1477:restoreOneFromDirectory> finish restore one mmkv[62aa295057e4378d16a8372644e7bde9], ret: 0`

**Comment by lingol** [comment]
It's supported in [v1.3.6](https://github.com/Tencent/MMKV/releases/tag/v1.3.6).
