### ISSUE TITLE
Cocoapods 源最新版本1.2.16 ，没找到1.3.5 等版本

### ISSUE THREAD

**Issue by Dcell** [Tencent/MMKV#1303]
## Note:
Cocoapods 源最新版本1.2.16 ，没找到1.3.5 等版本

### The language of MMKV
NA
### The version of MMKV
NA
### The platform of MMKV
iOS没找到，android能找到最新版本
### The installation of MMKV
Cocoapods
### What's the issue?
android maven 找到最新1.3.5版本，iOS 通过Cocoapds 源 未找到最新版本，只找到1.2.16版本
### What's the log of MMKV when that happened?
NA

**Comment by lingol** [comment]
Try 
pod update 
or 
pod install --repo-update
