### ISSUE TITLE
在模拟器上会crash，真机上运行正常，这是为啥？

### ISSUE THREAD

**Issue by xinyitiandi** [Tencent/MMKV#1305]
#13 at initializeWithPath (oh_modules/.ohpm/@tencent+mmkv@1.3.5/oh_modules/@tencent/mmkv/src/main/ets/utils/MMKV.ets:78:26)
#14 at initialize (oh_modules/.ohpm/@tencent+mmkv@1.3.5/oh_modules/@tencent/mmkv/src/main/ets/utils/MMKV.ets:63:16)
#15 at onCreate (entry/src/main/ets/entryability/EntryAbility.ets:15:23)

**Comment by xinyitiandi** [comment]
onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): void {
    let appCtx = this.context.getApplicationContext();
    let mmkvRootDir = MMKV.initialize(appCtx);
    Logger.info('mmkv rootDir: ', mmkvRootDir);

**Comment by lingol** [comment]
MMKV on OHOS requires API 12.
