### ISSUE TITLE
android系统上mmkv生成的数据文件在鸿蒙中使用

### ISSUE THREAD

**Issue by wanshijie3** [Tencent/MMKV#1306]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Java

### The version of MMKV

> e.g. v1.3.5
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by wanshijie3** [comment]
android系统上mmkv生成的数据文件在鸿蒙中是否可被mmkv读取?

数据写入和读取的方式是否有区别?

目前发现在android中的mmkv在数据写入时,头信息比鸿蒙的要多一部分

**Comment by lingol** [comment]
Is there a problem?

**Comment by wanshijie3** [comment]
是的,这是一个问题,mmkv在不同平台上读写的方式是否有区别,数据文件能否共用?
