### ISSUE TITLE
鸿蒙next版本MMKV 取出的数据比保存的数据丢了一个字符

### ISSUE THREAD

**Issue by xinle** [Tencent/MMKV#1308]
import { MMKV } from '@tencent/mmkv';

@Entry
@Component
struct MMKVTestPage {
  build() {
    Row() {
      Column() {
        Button("save")
          .onClick(() => {
            let str: string = "{\"id\":5,\"name\":\"智能降噪\",\"desc\":\"保证人声和背景音无损伤的情况下，降低声音中的噪声\",\"isNeedVip\":false," +
              "\"downloadUrl\":\"GEpyiHCvL-PnJgxIcPL86hL_k" +
              "-GrUrFqfcZYWPMhDJmbDESu95nSbtIfEIbWua_EQgCf1S2oFNVBnCoukhs_mnkBFd6gT3H2f2XobvvjePhvLLiO-5Pqg6Rm_uPveVkW\",\"updateTime\":1699261134000,\"isNewProductFree\":false,\"isAuthorized\":true,\"effectVersion\":5,\"md5\":\"ee463c033e588c9da104755b1da020ca\",\"tags\":\"\",\"canLowDevice\":false,\"isValidMasterClassVip\":false,\"localPath\":\"/data/storage/el2/base/haps/MainApp/files/sound_effect/se_temp/un_zip_se_5__5\"}";
            console.log("MMKVTest saveStr " + str)
            MMKV.defaultMMKV().encodeString('string', str);
          })

        Button("get")
          .onClick(() => {
            let result = MMKV.defaultMMKV().decodeString('string')
            console.info('MMKVTest getStr = ', result);
          })
      }
      .width('100%')
    }
    .height('100%')
  }
}

下面打印出来的结果会少一个字符串 ”}“

**Comment by xinle** [comment]
![20240524102521](https://github.com/Tencent/MMKV/assets/3382058/e61425a0-72db-49ca-8941-e6689a7b0e77)

**Comment by lingol** [comment]
Duplicate with #1294
