### ISSUE TITLE
Importing ArkTS files to JS and TS files is not allowed. <ArkTSCheck>

### ISSUE THREAD

**Issue by zhixiajava** [Tencent/MMKV#1309]
添加依赖的时候，ability报错
<img width="597" alt="image" src="https://github.com/Tencent/MMKV/assets/58247435/6c995208-b387-4648-aa01-9191a201ce09">
<img width="1014" alt="image" src="https://github.com/Tencent/MMKV/assets/58247435/e40784b0-4477-4f58-9a50-f7f7989bfa49">

**Comment by lingol** [comment]
Duplicate with #1301

**Comment by lingol** [comment]
Rename your .ts file to .ets if you have just getting started on your new project.
