### ISSUE TITLE
<MMKV.cpp:331::loadFromFile> fail to mmap [xxxx], Out of memory

### ISSUE THREAD

**Issue by swiftieslizheng** [Tencent/MMKV#1314]
## Note:
发现业务逻辑无法插入，看日志发现这个报错

### The language of MMKV

> e.g. Java and Kotlin

### The version of MMKV

> e.g. v1.0.23 

### The platform of MMKV

> e.g. Android

`
05-25 06:00:41.273  1993  2094 I MMKV    : <native-bridge.cpp:101::JNI_OnLoad> current API level = 27
05-25 06:00:41.286  1993  2094 I MMKV    : <MMKV.cpp:192::initialize> page size:4096
05-25 06:00:41.287  1993  2094 I MMKV    : <MMKV.cpp:206::initializeMMKV> root dir: /data/user/0/com.xtc.datacenter/files/mmkv
05-25 06:00:41.312  1993  1993 E MMKV    : <MMKV.cpp:331::loadFromFile> fail to mmap [com.xxx], Out of memory
05-25 06:00:41.312  1993  1993 W MMKV    : <MMKV.cpp:385::loadFromFile> [com.xxx] file not valid
`

**Comment by swiftieslizheng** [comment]
看了之前的issue，尝试手动插入10M以上value的大数据，未触发该异常

**Comment by lingol** [comment]
Maybe the device is running out of memory. There's nothing we can do about it, as far as I can see.

**Comment by lingol** [comment]
Your log is somehow missing crucial information about the size of the file.

**Comment by lingol** [comment]
Closed due to inactive.
