### ISSUE TITLE
Android平台下生成的mmkv文件，在鸿蒙系统下是否可以读取出来，因为后面Android可以升级到鸿蒙需要做数据迁移

### ISSUE THREAD

**Issue by xinle** [Tencent/MMKV#1315]
Android平台下生成的mmkv文件，在鸿蒙系统下是否可以读取出来，因为后面Android可以升级到鸿蒙需要做数据迁移，
目前试了下是不行的，这个是否未来有计划支持？

**Comment by lingol** [comment]
What is the problem? Please provide logs.

**Comment by xinle** [comment]
你好这里说的鸿蒙是纯血鸿蒙

**Comment by xinle** [comment]
![Uploading 20240530103742.jpg…]()

**Comment by xinle** [comment]
这里是日志

**Comment by xinle** [comment]
I     <MMKV_Android.cpp:158::mmkvWithID> prepare to load /data/storage/el2/base/haps/MainApp/files/mmkv/mDefault_ting_data2_backup (id /data/storage/el2/base/haps/MainApp/files/mmkv/mDefault_ting_data2_backup) from rootPath 29246416848
 I     <MemoryFile.cpp:98::open> open fd[0x73], /data/storage/el2/base/haps/MainApp/files/mmkv/specialCharacter/d40df772a289f7a0eafc907d1a177ea6
 I     <MemoryFile.cpp:203::mmap> mmap to address [0x5aef3d000], oldPtr [0], [/data/storage/el2/base/haps/MainApp/files/mmkv/specialCharacter/d40df772a289f7a0eafc907d1a177ea6]
 I     RSProfiler::OnRenderBegin(): disabled
 I     <MemoryFile.cpp:98::open> open fd[0x74], /data/storage/el2/base/haps/MainApp/files/mmkv/specialCharacter/d40df772a289f7a0eafc907d1a177ea6.crc
 I     <MemoryFile.cpp:203::mmap> mmap to address [0x5aef3e000], oldPtr [0], [/data/storage/el2/base/haps/MainApp/files/mmkv/specialCharacter/d40df772a289f7a0eafc907d1a177ea6.crc]
 I     <MMKV_IO.cpp:214::loadMetaInfoAndCheck> meta file [/data/storage/el2/base/haps/MainApp/files/mmkv/mDefault_ting_data2_backup] has flag [0]
 I     <MMKV_IO.cpp:84::loadFromFile> loading [/data/storage/el2/base/haps/MainApp/files/mmkv/mDefault_ting_data2_backup] with 0 actual size, file size 4096, InterProcess 1, meta info version:4
 I     <MMKV_IO.cpp:133::loadFromFile> loaded [/data/storage/el2/base/haps/MainApp/files/mmkv/mDefault_ting_data2_backup] with 0 key-values

**Comment by lingol** [comment]
There's nothing wrong with the logs. 
Which one goes wrong, the _mDefault_ting_data2_backup_, or the _specialCharacter/d40df772a289f7a0eafc907d1a177ea6_ ? You should upload the files you extracted from Android for further investigation.
One more thing, you have tried to create one mmkv with special characters, you should provide the name of it as well.

**Comment by lingol** [comment]
Oh, I may have found out what went wrong. Did you try to load it with an absolute path? 
You should not do that. You should init mmkv with rootPath to /data/storage/el2/base/haps/MainApp/files/mmkv, and load it with the same ID mDefault_ting_data2_backup. 

Never pass the absolute path as a mmkv ID.

**Comment by xinle** [comment]
I     <MMKV_Android.cpp:158::mmkvWithID> prepare to load mDefault_ting_data2_backup (id mDefault_ting_data2_backup) from rootPath 29239936160
 I     <MemoryFile.cpp:98::open> open fd[0x72], /data/storage/el2/base/haps/MainApp/files/mmkv/mDefault_ting_data2_backup
 I     <MemoryFile.cpp:203::mmap> mmap to address [0x5aef3d000], oldPtr [0], [/data/storage/el2/base/haps/MainApp/files/mmkv/mDefault_ting_data2_backup]
 I     <MemoryFile.cpp:98::open> open fd[0x73], /data/storage/el2/base/haps/MainApp/files/mmkv/mDefault_ting_data2_backup.crc
 I     <MemoryFile.cpp:203::mmap> mmap to address [0x5aef3e000], oldPtr [0], [/data/storage/el2/base/haps/MainApp/files/mmkv/mDefault_ting_data2_backup.crc]
 I     <MMKV_IO.cpp:84::loadFromFile> loading [mDefault_ting_data2_backup] with 60 actual size, file size 4096, InterProcess 1, meta info version:3
 I     <MMKV_IO.cpp:89::loadFromFile> loading [mDefault_ting_data2_backup] with crc 3177707489 sequence 1 version 3
 E     <MiniPBCoder.cpp:591::decodeOneMap> InvalidProtocolBuffer truncatedMessage
 I     <MMKV_IO.cpp:133::loadFromFile> loaded [mDefault_ting_data2_backup] with 0 key-values

**Comment by xinle** [comment]
@lingol 你好，改了下还是获取不多，麻烦看下要怎么解决？

**Comment by xinle** [comment]
@lingol 你好，改了下还是获取不到，麻烦看下要怎么解决？
