### ISSUE TITLE
MMKV decodeDouble decodeBool api问题

### ISSUE THREAD

**Issue by CheerHarry** [Tencent/MMKV#1316]
目前遇到一场景，假如我调用：
MMKV.encodeString("string_key", "测试一下")

然后通过以下方式获取值：

方式一：
let n = MMKV.decodeDouble("string_key")

发现 n = -3.4328893225396805e+176

方式二：

let b = MMKV.decodeBool("string_key")

发现 b = true

实际开发中，希望n和b返回undefined或者设置的默认值

**Comment by lingol** [comment]
Can't be done. The reason is the same as why `gatAll()` not exists.
