### ISSUE TITLE
iOS 版本的 MMKV 1.2.12 版本，Xcode 15.4 真机运行包错

### ISSUE THREAD

**Issue by jacinzhang** [Tencent/MMKV#1317]
![image](https://github.com/Tencent/MMKV/assets/9859965/33763b03-8284-4392-9199-2f3480928a23)

**Comment by lingol** [comment]
It's not an error in running but an error in building. You must've done something wrong in installing mmkv. 

Check your steps again. And clean & check out your code if it doesn't work.

One more thing, your version is way too old. Upgrade it from time to time.
