### ISSUE TITLE
MMKV不支持鸿蒙 next 的api11 吗？

### ISSUE THREAD

**Issue by wananni-1998** [Tencent/MMKV#1319]

**Comment by wananni-1998** [comment]
鸿蒙最新版

**Comment by baochuquan** [comment]
确实，鸿蒙 api11 初始化时会崩溃

**Comment by wananni-1998** [comment]
> 确实，鸿蒙 api11 初始化时会崩溃

要等11正式发布了 才会更新库吗  这种情况

**Comment by lingol** [comment]
No, MMKV requires at least API 12.
>We started from API 12 targeting HarmonyOS NEXT, which will be released at least from 12. 
So no, API 11 is not in our plan.

_Originally posted by @lingol in https://github.com/Tencent/MMKV/issues/1298#issuecomment-2105656513_
