### ISSUE TITLE
鸿蒙Next MMKV 解析Boolean的时候比较耗时，差的时候要1ms

### ISSUE THREAD

**Issue by xinle** [Tencent/MMKV#1324]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
It's quite impossible. What is the log when it happens? Is it doing a loading/reload from file?

**Comment by lingol** [comment]
If possible you should provide a reproducible demo.

**Comment by xinle** [comment]
辛苦看下这个是trace抓到的数据
![Uploading 20240614141902.jpg…]()

**Comment by xinle** [comment]
https://imagev2.xmcdn.com/storages/34b6-audiofreehighqps/AC/FC/GArMcTAKQaRhAAOQcwLhgy5j.jpg  这个是trace的数据

**Comment by lingol** [comment]
> https://imagev2.xmcdn.com/storages/34b6-audiofreehighqps/AC/FC/GArMcTAKQaRhAAOQcwLhgy5j.jpg 这个是trace的数据

That has little info if not any. 

>辛苦看下这个是trace抓到的数据
![Uploading 20240614141902.jpg…]()

That image is broken.

**Comment by SunryOne** [comment]
hello，1.3.5版本 请问你们是如何在鸿蒙UIAbility 里面进行引入的呢。 不应该会报Importing ArkTS files to JS and TS files is not allowed. 的错误吗

**Comment by lingol** [comment]
> hello，1.3.5版本 请问你们是如何在鸿蒙UIAbility 里面进行引入的呢。 不应该会报Importing ArkTS files to JS and TS files is not allowed. 的错误吗

Don't make unrelative questions, if you have an issue open a new one.

**Comment by lingol** [comment]
Closed due to lack of information & inactive.
