### ISSUE TITLE
不支持鸿蒙API9

### ISSUE THREAD

**Issue by ant074** [Tencent/MMKV#1325]
## Note:
> hvigor Finished :module_base:default@CompileJS... after 5 ms 
 "@kit.PerformanceAnalysisKit" is imported by "oh_modules/.ohpm/@tencent+mmkv@1.3.6-beta2/oh_modules/@tencent/mmkv/src/main/ets/utils/MMKV.ets", but could not be resolved – treating it as an external dependency. 
> hvigor ERROR: Failed :module_base:default@CompileArkTS... 
> hvigor ERROR: ArkTs Compiler Error
ERROR: ArkTS:ERROR File: G:/huawei/ws/qbtmj_hm/oh_modules/.ohpm/@tencent+mmkv@1.3.6-beta2/oh_modules/@tencent/mmkv/src/main/ets/utils/MMKV.ets:22:23
 Cannot find module '@kit.PerformanceAnalysisKit' or its corresponding type declarations.

ERROR: ArkTS:ERROR File: G:/huawei/ws/qbtmj_hm/oh_modules/.ohpm/@tencent+mmkv@1.3.6-beta2/oh_modules/@tencent/mmkv/src/main/ets/utils/MMKV.ets:683:31
 Property 'getAllSync' does not exist on type 'Preferences'.

WARN: ArkTS:WARN File: G:/huawei/ws/qbtmj_hm/oh_modules/.ohpm/@tencent+mmkv@1.3.6-beta2/oh_modules/@tencent/mmkv/src/main/ets/utils/MMKV.ets:21:20
 Currently module for 'libmmkv.so' is not verified. If you're importing napi, its verification will be enabled in later SDK version. Please make sure the corresponding .d.ts file is provided and the napis are correctly declared.

COMPILE RESULT:FAIL {ERROR:3 WARN:1}
> hvigor ERROR: BUILD FAILED in 4 s 15 ms 

### The language of MMKV

> arkTS

### The version of MMKV

> 1.3.6-beta2

**Comment by lingol** [comment]
MMKV requires API 12. 

>We started from API 12 targeting HarmonyOS NEXT, which will be released at least from 12. 
>So no, API 11 is not in our plan.

_Originally posted by @lingol in https://github.com/Tencent/MMKV/issues/1298#issuecomment-2105656513_
