### ISSUE TITLE
Reason:Signal:SIGABRT(SI_TKILL)@0x01317b410000572d from:22317:20020033

### ISSUE THREAD

**Issue by xiaqingpeng** [Tencent/MMKV#1327]
Reason:Signal:SIGABRT(SI_TKILL)@0x01317b410000572d from:22317:20020033

**Comment by lingol** [comment]
Please provide full call stacks, plus details of logs from mmkv.

**Comment by lingol** [comment]
Please follow the issue template.

**Comment by lyxxman** [comment]
error on hua wei device manger.
log:
Fault thread Info:
Tid:3030, Name:ch.ecalendar.hm
#00 pc 00000000000ea4a4 /system/lib/ld-musl-aarch64.so.1(raise+192)(2fda81589b2be12f2f1e9f31f66b8d45)
#01 pc 000000000009b814 /system/lib/ld-musl-aarch64.so.1(abort+20)(2fda81589b2be12f2f1e9f31f66b8d45)
#02 pc 000000000007df5c /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#03 pc 0000000000060490 /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#04 pc 0000000000060354 /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#05 pc 000000000008041c /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#06 pc 0000000000080398 /data/storage/el1/bundle/libs/arm64/libmmkv.so(__cxa_throw+124)(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#07 pc 000000000003aaa0 /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#08 pc 000000000003aa64 /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#09 pc 000000000003aa28 /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#10 pc 0000000000032e0c /data/storage/el1/bundle/libs/arm64/libmmkv.so(1fa827624644a665c1f9431d2ee2afccb9d8ffa5)
#11 pc 000000000002bb48 /system/lib64/platformsdk/libace_napi.z.so(ArkNativeFunctionCallBack(panda::JsiRuntimeCallInfo*)+168)(24bd31e6643d9c824c1d56d38c58db47)
#12 pc 000000000013f968 /system/lib64/module/arkcompiler/stub.an
#13 at initializeWithPath (oh_modules/.ohpm/@tencent+mmkv@1.3.5/oh_modules/@tencent/mmkv/src/main/ets/utils/MMKV.ets:78:26)
#14 at initialize (oh_modules/.ohpm/@tencent+mmkv@1.3.5/oh_modules/@tencent/mmkv/src/main/ets/utils/MMKV.ets:63:16)
#15 at initSdk (entry/src/main/ets/entryability/EntryAbility.ets:77:23)
#16 at onWindowStageCreate (entry/src/main/ets/entryability/EntryAbility.ets:54:5)
#17 pc 000000000029c964 /system/lib64/platformsdk/libark_jsruntime.so(d6e8454a7b98171f727f5872b4148c10)
#18 pc 000000000029c964 /system/lib64/platformsdk/libark_jsruntime.so(d6e8454a7b98171f727f5872b4148c10)
#19 pc 00000000003dea68 /system/lib64/platformsdk/libark_jsruntime.so(panda::FunctionRef::CallForNapi(panda::ecmascript::EcmaVM const*, panda::JSValueRef*, panda::JSValueRef* const*, int)+288)(d6e8454a7b98171f727f5872b4148c10)
#20 pc 0000000000041040 /system/lib64/platformsdk/libace_napi.z.so(napi_call_function+352)(24bd31e6643d9c824c1d56d38c58db47)
#21 pc 0000000000029194 /system/lib64/platformsdk/libuiabilitykit_native.z.so(OHOS::AbilityRuntime::JsUIAbility::CallObjectMethod(char const*, napi_value__* const*, unsigned long, bool)+720)(dfa0173ade9c00c1bbf96816600f23b3)
#22 pc 000000000002a948 /system/lib64/platformsdk/libuiabilitykit_native.z.so(OHOS::AbilityRuntime::JsUIAbility::OnSceneCreated()+428)(dfa0173ade9c00c1bbf96816600f23b3)
#23 pc 000000000002c5e8 /system/lib64/platformsdk/libuiabilitykit_native.z.so(OHOS::AbilityRuntime::JsUIAbility::AbilityContinuationOrRecover(OHOS::AAFwk::Want const&)+560)(dfa0173ade9c00c1bbf96816600f23b3)
#24 pc 000000000002ce30 /system/lib64/platformsdk/libuiabilitykit_native.z.so(OHOS::AbilityRuntime::JsUIAbility::DoOnForegroundForSceneIsNull(OHOS::AAFwk::Want const&)+1204)(dfa0173ade9c00c1bbf96816600f23b3)
#25 pc 000000000002c78c /system/lib64/platformsdk/libuiabilitykit_native.z.so(OHOS::AbilityRuntime::JsUIAbility::DoOnForeground(OHOS::AAFwk::Want const&)+284)(dfa0173ade9c00c1bbf96816600f23b3)
#26 pc 0000000000051448 /system/lib64/platformsdk/libuiabilitykit_native.z.so(OHOS::AbilityRuntime::UIAbility::OnForeground(OHOS::AAFwk::Want const&)+224)(dfa0173ade9c00c1bbf96816600f23b3)
#27 pc 000000000002b538 /system/lib64/platformsdk/libuiabilitykit_native.z.so(OHOS::AbilityRuntime::JsUIAbility::OnForeground(OHOS::AAFwk::Want const&)+260)(dfa0173ade9c00c1bbf96816600f23b3)
#28 pc 0000000000058d3c /system/lib64/platformsdk/libuiabilitykit_native.z.so(OHOS::AbilityRuntime::UIAbilityImpl::Foreground(OHOS::AAFwk::Want const&)+516)(dfa0173ade9c00c1bbf96816600f23b3)
#29 pc 0000000000056ccc /system/lib64/platformsdk/libuiabilitykit_native.z.so(OHOS::AbilityRuntime::UIAbilityImpl::AbilityTransaction(OHOS::AAFwk::Want const&, OHOS::AAFwk::LifeCycleStateInfo const&)+784)(dfa0173ade9c00c1bbf96816600f23b3)
#30 pc 00000000000566dc /system/lib64/platformsdk/libuiabilitykit_native.z.so(OHOS::AbilityRuntime::UIAbilityImpl::HandleAbilityTransaction(OHOS::AAFwk::Want const&, OHOS::AAFwk::LifeCycleStateInfo const&, OHOS::sptr<OHOS::AAFwk::SessionInfo>)+588)(dfa0173ade9c00c1bbf96816600f23b3)
#31 pc 000000000003b124 /system/lib64/platformsdk/libability_thread.z.so(OHOS::AbilityRuntime::UIAbilityThread::HandleAbilityTransaction(OHOS::AAFwk::Want const&, OHOS::AAFwk::LifeCycleStateInfo const&, OHOS::sptr<OHOS::AAFwk::SessionInfo>)+516)(0ae09bd5796a689c8d250f78dc9ec8e6)
#32 pc 000000000003f818 /system/lib64/platformsdk/libability_thread.z.so(0ae09bd5796a689c8d250f78dc9ec8e6)
#33 pc 0000000000012ab0 /system/lib64/chipset-pub-sdk/libeventhandler.z.so(OHOS::AppExecFwk::EventHandler::DistributeEvent(std::__h::unique_ptr<OHOS::AppExecFwk::InnerEvent, void (*)(OHOS::AppExecFwk::InnerEvent*)> const&)+1008)(ef6664743679a9ae3e05c02984684334)
#34 pc 000000000001eaa4 /system/lib64/chipset-pub-sdk/libeventhandler.z.so(ef6664743679a9ae3e05c02984684334)
#35 pc 000000000002096c /system/lib64/chipset-pub-sdk/libeventhandler.z.so(OHOS::AppExecFwk::EventRunner::Run()+100)(ef6664743679a9ae3e05c02984684334)
#36 pc 0000000000070868 /system/lib64/platformsdk/libappkit_native.z.so(OHOS::AppExecFwk::MainThread::Start()+700)(1bf4b56cb5620a2f03be9ec27379912c)
#37 pc 0000000000011180 /system/bin/appspawn(03c81d6b22d177ce452ac07f31a4c216)
#38 pc 00000000000339c4 /system/bin/appspawn(03c81d6b22d177ce452ac07f31a4c216)
#39 pc 0000000000033834 /system/bin/appspawn(03c81d6b22d177ce452ac07f31a4c216)
#40 pc 000000000002fd10 /system/bin/appspawn(03c81d6b22d177ce452ac07f31a4c216)
#41 pc 0000000000017c14 /system/lib64/chipset-pub-sdk/libbegetutil.z.so(4c0f36c7c43a08e4aac7cdf109906bc7)
#42 pc 00000000000178b8 /system/lib64/chipset-pub-sdk/libbegetutil.z.so(4c0f36c7c43a08e4aac7cdf109906bc7)
#43 pc 0000000000015434 /system/lib64/chipset-pub-sdk/libbegetutil.z.so(4c0f36c7c43a08e4aac7cdf109906bc7)
#44 pc 000000000001504c /system/lib64/chipset-pub-sdk/libbegetutil.z.so(4c0f36c7c43a08e4aac7cdf109906bc7)
#45 pc 000000000002e764 /system/bin/appspawn(03c81d6b22d177ce452ac07f31a4c216)
#46 pc 000000000001ea54 /system/bin/appspawn(03c81d6b22d177ce452ac07f31a4c216)
#47 pc 0000000000088274 /system/lib/ld-musl-aarch64.so.1(2fda81589b2be12f2f1e9f31f66b8d45)
#48 pc 0000000000010724 /system/bin/appspawn(03c81d6b22d177ce452ac07f31a4c216)

**Comment by lyxxman** [comment]
version 1.3.5 .

**Comment by lingol** [comment]
MMKV requires API 12. Duplicated #1325
