### ISSUE TITLE
harmonyOS4.1.0(11) 模拟器启动加载异常退出。

### ISSUE THREAD

**Issue by bluesky0506** [Tencent/MMKV#1330]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV
Harmony OS ArkTS

### The version of MMKV

"@tencent/mmkv": "^1.3.5",

### The platform of MMKV

>Harmony 4.1.0(11)

### The installation of MMKV

@tencent/mmkv 安装

### What's the issue?

启动就报错，app异常退出。

### What's the log of MMKV when that happened?
06-20 14:10:35.904 32473 32473 I A00000/mmkvdemo: Ability onCreate
06-20 14:10:35.904 32473 32473 W C03f01/NAPI: [(native_module_manager.cpp:556)(LoadNativeModule)] module 'application.ApplicationContext' does not in cache
06-20 14:10:35.904 32473 32473 I C03f01/NAPI: [(native_module_manager.cpp:739)(LoadModuleLibrary)] path: /system/lib64/module/application/libapplicationcontext.z.so, pathKey: default, isAppModule: 0
06-20 14:10:35.905 32473 32473 E C03f00/MUSL-LDSO: Error loading header /system/lib64/module/application/libapplicationcontext.z.so, namespace ndk has no inherits
06-20 14:10:35.905 32473 32473 E C03f00/MUSL-LDSO: Error loading header: can't find library /system/lib64/module/application/libapplicationcontext.z.so in namespace: default
06-20 14:10:35.905 32473 32473 E C03f00/MUSL-LDSO: dlopen_impl load library header failed for /system/lib64/module/application/libapplicationcontext.z.so
06-20 14:10:35.906 32473 32473 W C03f01/NAPI: [(native_module_manager.cpp:764)(LoadModuleLibrary)] dlopen failed: Error loading shared library /system/lib64/module/application/libapplicationcontext.z.so: No such file or directory
06-20 14:10:35.906 32473 32473 I C03f01/NAPI: [(native_module_manager.cpp:739)(LoadModuleLibrary)] path: /system/lib64/module/application/libapplicationcontext_napi.z.so, pathKey: default, isAppModule: 0
06-20 14:10:35.909 32473 32473 I A00000/MMKV: <native_bridge.cpp:83::NValueToString> NAPI Error: code 1, msg Invalid parameter
06-20 14:10:35.909 32473 32473 E C03f00/ArkCompiler: [ecmascript] Pending exception before ToString called in line:242, exception details as follows:
06-20 14:10:35.909 32473 32473 E C03f00/ArkCompiler: Error: null
06-20 14:10:35.909 32473 32473 E C03f00/ArkCompiler:     at initializeWithPath (MMKV/src/main/ets/utils/MMKV.ets:54:26)
06-20 14:10:35.909 32473 32473 E C03f00/ArkCompiler:     at initialize (MMKV/src/main/ets/utils/MMKV.ets:40:16)
06-20 14:10:35.909 32473 32473 E C03f00/ArkCompiler:     at onCreate (entry/src/main/ets/entryability/EntryAbility.ets:15:22)
06-20 14:10:35.909 32473 32473 E C03f00/ArkCompiler: [default] Utf8Length:1338 JSNApi special value:0x2 checked
06-20 14:10:35.910 32473 32473 E C03f00/MUSL-SIGCHAIN: signal_chain_handler call 2 rd sigchain action for signal: 6
06-20 14:10:35.910 32473 32473 I C02d11/DfxSignalHandler: DFX_SigchainHandler :: sig(6), pid(32473), tid(32473).
06-20 14:10:35.910 32473 32473 I C02d11/DfxSignalHandler: DFX_SigchainHandler :: sig(6), pid(32473), processName(com.tencent.mmkvdemo), threadName(encent.mmkvdemo).
06-20 14:10:35.916 32473 32473 I C02d11/DfxSignalHandler: Start wait for VmProcess(32494) exit.
06-20 14:10:35.916 32473 32473 I C02d11/DfxSignalHandler: (32473) wait VmProcess(32494) exit.
06-20 14:10:36.559 32473 32473 I C02d11/DfxSignalHandler: (32473) wait for (32494) return with ret(32494) status(0)
06-20 14:10:36.560 32473 32473 I C02d11/DfxSignalHandler: Finish handle signal(6) in 32473:32473
06-20 14:10:36.560 32473 32473 E C03f00/MUSL-SIGCHAIN: signal_chain_handler call usr sigaction for signal: 6
06-20 14:10:36.560 32473 32473 E C03f00/MUSL-SIGCHAIN: signal_chain_handler call 2 rd sigchain action for signal: 6
06-20 14:10:36.560 32473 32473 I C02d11/DfxSignalHandler: DFX_SigchainHandler :: sig(6), pid(32473), tid(32473).
06-20 14:10:36.562 32473 32473 E C03f00/MUSL-SIGCHAIN: signal_chain_handler SIG_DFL handler for signal: 6

**Comment by lingol** [comment]
Duplicate with #1327
