### ISSUE TITLE
Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libmmkv.so': dlopen failed: library "libmmkv.so" not found

### ISSUE THREAD

**Issue by yoyo89757001** [Tencent/MMKV#1331]
在网络上找到这个帖子，不知道是不是这个bug的原因：
https://blog.csdn.net/pengbo6665631/article/details/129391587

**Comment by lingol** [comment]
Maybe. Can you verify that it works?

**Comment by jzlhll** [comment]
有点不负责任的感觉。1.3.5开始直接ban掉了，x86和v7a的支持（大概率是这个原因）。从打包后的包解压可以看到，只有arm64-v8a和x64目录里面有库。而1.3.4打包解压后，是4个目录有的。
![screenshot-20240624-095343](https://github.com/Tencent/MMKV/assets/19789292/9f4d2adf-63ea-4767-b169-36ac32e1bef3)

**Comment by lingol** [comment]
> 有点不负责任的感觉。1.3.5开始直接ban掉了v1.3.5 / 2024-04-24
> 
>  Drop armv7 & x86 support.，x86和v7a的支持（大概率是这个原因）。从打包后的包解压可以看到，只有arm64-v8a和x64目录里面有库。而1.3.4打包解压后，是4个目录有的。
> 
> 而如果你是googlePlay发布的话，由于平台又做了cpu架构的区别分发，用户v7a手机下载到的真实程序就没了。
> 
> 下图是1.3.4打包出来的结果：
> 
> ![screenshot-20240624-095343](https://github.com/Tencent/MMKV/assets/19789292/9f4d2adf-63ea-4767-b169-36ac32e1bef3)
> 
> 所以你懂得，降级吧，再也不升级了。
> 
> 

Don't spam everywhere. If armv7 is the issue you can always fork mmkv and add back armv7 support by yourself. 
It's **open sourced**.

**Comment by jzlhll** [comment]
> > 有点不负责任的感觉。1.3.5开始直接ban掉了v1.3.5 / 2024-04-24
> > Drop armv7 & x86 support.，x86和v7a的支持（大概率是这个原因）。从打包后的包解压可以看到，只有arm64-v8a和x64目录里面有库。而1.3.4打包解压后，是4个目录有的。
> > 而如果你是googlePlay发布的话，由于平台又做了cpu架构的区别分发，用户v7a手机下载到的真实程序就没了。
> > 下图是1.3.4打包出来的结果：
> > ![screenshot-20240624-095343](https://private-user-images.githubusercontent.com/19789292/342178502-9f4d2adf-63ea-4767-b169-36ac32e1bef3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTY1NDgsIm5iZiI6MTcxOTE5NjI0OCwicGF0aCI6Ii8xOTc4OTI5Mi8zNDIxNzg1MDItOWY0ZDJhZGYtNjNlYS00NzY3LWIxNjktMzZhYzMyZTFiZWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAyMzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMzY5OTFiYmNiYTZmMzgxMzc1OThmY2UwOGNhZjM5OTg3YTQwNDM3YmViNmUwN2Q3NTBiYTBmZGU2OTY0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._u4cEmfosJVkHgxOyU9CrRyPGv5ltN1gw5GNWGGxftw)
> > 所以你懂得，降级吧，再也不升级了。
> 
> Don't spam everywhere. If armv7 is the issue you can always fork mmkv and add back armv7 support by yourself. It's **open sourced**.

我还是坚持自己的意见。对于大部分普通程序员而言，一个库是否好用在于它的延续性，如果对于兼容性存在问题的情况下，可以将库的版本进行别的版本号区分发布。而不是1.3.4，变成1.3.5。对于版本号也不是很好的尊重。

**Comment by lingol** [comment]
[v1.3.7 LST](https://github.com/Tencent/MMKV/releases/tag/v1.3.7 ) has just been release.

**This Long Term Support (LTS) release** primarily reintroduces support for the ARMv7 architecture and lowers the minimum SDK version requirement to 21. Please note that only critical bug fixes will be applied to the 1.3.x series. 

New features will be introduced in version 2.0 and later, which will discontinue support for 32-bit architectures and raise the minimum SDK version requirement to 23.
