### ISSUE TITLE
MMKV没有对应的JDK配套表

### ISSUE THREAD

**Issue by beibeiGeng** [Tencent/MMKV#1336]
由于业务诉求，我想查询MMKV版本与JDK的配套关系，我在网上查阅了很多资料，都没有明确的说明，能否提供一个官方的配套说明表呢？万分感谢。

**Comment by lingol** [comment]
There's no list. You can get it in the code. 
https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/build.gradle#L18C5-L18C37
