### ISSUE TITLE
应用升级TargetSDK 到 34，MMKV有兼容性问题么？

### ISSUE THREAD

**Issue by mikelhm** [Tencent/MMKV#1354]
应用升级TargetSDK 到 34， MMKV 还是1.12.14，是否会有兼容性问题。
<img width="907" alt="image" src="https://github.com/user-attachments/assets/0d81f824-0613-4eb5-ab7e-23d3793b3f46">
这个版本的 MMKV 升级SDK 到34 是做了 Target34的适配么

**Comment by lingol** [comment]
TargetSDK should have no problem as far as I'm aware.
