### ISSUE TITLE
是否可以兼容下openharmony

### ISSUE THREAD

**Issue by hongshao361** [Tencent/MMKV#1360]
![Uploading WeChatd292ee5d007ccf4ee61d0909f513b2e3.jpg…]()

**Comment by lingol** [comment]
Your image is broken.

**Comment by hongshao361** [comment]
![WeChatd292ee5d007ccf4ee61d0909f513b2e3](https://github.com/user-attachments/assets/773c5c4b-0181-4e5b-bd0d-b6e562f0990a)

**Comment by lingol** [comment]
MMKV requires HarmonyOS NEXT with API level 12.

**Comment by hongshao361** [comment]
> MMKV requires HarmonyOS NEXT with API level 12.

请问有没有API10适合open harmony的兼容版本

**Comment by lingol** [comment]
No.
