### ISSUE TITLE
v1.3.9 LTS在Windows平台编译失败v1.3.6正常

### ISSUE THREAD

**Issue by 1027663760** [Tencent/MMKV#1368]
AESCrypt.cpp 中缺少 random() 命令，我改成了 rand()

使用 MMKV_DISABLE_CRYPT 和 MMKV_DISABLE_FLUTTER 后：
![QQ截图20240726201344](https://github.com/user-attachments/assets/ec3102f4-539c-415a-b2f8-1b03ff5a1f15)

**Comment by lingol** [comment]
Also fixed `MMKV_DISABLE_CRYPT`.
