### ISSUE TITLE
[Enhancement][Android] Support custom folder?

### ISSUE THREAD

**Issue by heruoxin** [Tencent/MMKV#137]
Currently MMVK Android stores all of the files to the file dir (/data/data/packagename/files/mmkv/). 
Is there any plan to support other dirs .e.g cache?

**Comment by lingol** [comment]
Not in our plan. Why would you put in cache? If you don't need those files any more, you can just remove them.

**Comment by heruoxin** [comment]
There are some benefits for putting cache files to cache folder:

1. The system settings and most app-cleaner apps separate the cache from the storage to calculate the apps size.

2. Sometimes the android system deletes the cache periodically or manually when user clicking "Release Storage" in system settings.

3. Putting cache files to cache folder is more friendly to Google backup and backup feature implemented by any other apps. (I know can use backup_descriptor.xml to exclude files but it will become hard to maintain when too many files.)

**Comment by lingol** [comment]
And why do you put cache stuff inside MMKV? Well if that's what you want, we might consider it in the future.

**Comment by lingol** [comment]
Given it a second thought last night, I  have realized there will be a hard choice to make.
Does supporting custom folder means all MMKV stored in custom folder, or some MMKV in custom folder, and some in another folder / default folder?

**Comment by heruoxin** [comment]
I think it might be better to put some in default and some in custom.

Cache is just one of the possible uses. I guess that maybe some apps can put MMKV files into some common folder to share simple data.

**Comment by lingol** [comment]
> I think it might be better to put some in default and some in custom.
> 
> Cache is just one of the possible uses. I guess that maybe some apps can put MMKV files into some common folder to share simple data.

And that's exactly what I've worried about. It means a totally redesign of MMKV's init & instance API.

**Comment by Jonwei** [comment]
1. will support it in iOS ?

2. As I see, for public method, add two init API , and change one public class API as below, then could support  this feature in iOS. 
`
+ (instancetype)mmkvWithID:(NSString *)mmapID relativePath:(nullable NSString *)path;
+ (instancetype)mmkvWithID:(NSString *)mmapID cryptKey:(nullable NSData *)cryptKey relativePath:(nullable NSString *)path;

+ (BOOL)isFileValid:(NSString *)mmapID relativePath:(nullable NSString *)path;
`
for internal implementation, focusing m_path param is OK. 

3. i implement it in [this link](https://github.com/Jonwei/MMKV/tree/develop), hope it can help.

**Comment by Jonwei** [comment]
@lingol  I didn't create pr...

**Comment by lingol** [comment]
Wow, Looks like it's a highly needed feature now. So highly needed that there's two independent implementation.

**Comment by Jonwei** [comment]
@lingol well, i create a pr just right. please review it.

**Comment by lingol** [comment]
> @lingol well, i create a pr just right. please review it.

Your implementation is better. Just modify a little bit and I'll accept it with great appreciation.

**Comment by hereisderek** [comment]
i don't see why not just use how sharedpreference implemented it. you can either pass in a store location when initialize and we can save that instance for use or pass in nothing then just use the default location

**Comment by lingol** [comment]
Android is supported with this [commit](https://github.com/Tencent/MMKV/commit/3df5a7b5ac6f67fdcfb3cd5d6aead1c3d6eb7e31). 
Hopefully will come out on next release in next week.
Or shell we say, in NEXT YEAR!

Happy New Year, guys.

**Comment by lingol** [comment]
Released with [v1.0.16](https://github.com/Tencent/MMKV/releases/tag/v1.0.16).
