### ISSUE TITLE
鸿蒙 MMKV日志 如何重定向

### ISSUE THREAD

**Issue by zangxuyfd** [Tencent/MMKV#1373]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

### The version of MMKV
>  v1.3.6  

我需要，mmkv的日志。在鸿蒙上如何设置  可以拿到mmkv相关日志 方便我们排查线上问题

**Comment by zangxuyfd** [comment]
使用的文件 是 ets文件

**Comment by lingol** [comment]
It's not supported on ohos's JS wrapper yet.

**Comment by zangxuyfd** [comment]
那在鸿蒙上  排查问题 有什么好的方案吗。  不然无法感知 存储失败 或者  其他错误

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/ohos_setup#log
Currently, there's no way to do it if you do not integrate MMKV with the C++ source code.

**Comment by zangxuyfd** [comment]
ok 明白了

**Comment by lingol** [comment]
[v2.0.0](https://github.com/Tencent/MMKV/releases/tag/v2.0.0) with this feature is out.
