### ISSUE TITLE
鸿蒙mmkv代码源如何选择。

### ISSUE THREAD

**Issue by zangxuyfd** [Tencent/MMKV#1375]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

推荐 引用 鸿蒙仓库的源   "@ohos/mmkv":"^2.0.3",
还是腾讯的代码源     "@tencent/mmkv": "1.3.9",

希望可以给点建议和选择的理由

**Comment by lingol** [comment]
The @tencent/mmkv package is official support, period.
