### ISSUE TITLE
向MMKV更新内容（string）时Crash

### ISSUE THREAD

**Issue by juggist** [Tencent/MMKV#1379]
## Note:
native crash

### The language of MMKV

kotlin

### The version of MMKV
v1.3.1

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?

应用运行时出现crash

### What's the log of MMKV when that happened?
08-08 15:18:13.605  3115  3365 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 3365 (pool-5-thread-4), pid 3115 (xxxxx:@@)
08-08 15:18:13.790  3388  3388 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-08 15:18:13.790  3388  3388 F DEBUG   : Build fingerprint: 'Infinix/X682B-GL/Infinix-X682B:10/QP1A.190711.020/210223V370:user/release-keys'
08-08 15:18:13.790  3388  3388 F DEBUG   : Revision: '0'
08-08 15:18:13.790  3388  3388 F DEBUG   : ABI: 'arm64'
08-08 15:18:13.790  3388  3388 F DEBUG   : Timestamp: 2024-08-08 15:18:13+0800
08-08 15:18:13.790  3388  3388 F DEBUG   : pid: 3115, tid: 3365, name: pool-5-thread-4  >>> xxxxx:@@ <<<
08-08 15:18:13.790  3388  3388 F DEBUG   : uid: 10077
08-08 15:18:13.790  3388  3388 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
08-08 15:18:13.790  3388  3388 F DEBUG   :     x0  0000000000000000  x1  0000000000000d25  x2  0000000000000006  x3  00000074abc672c0
08-08 15:18:13.790  3388  3388 F DEBUG   :     x4  fefeff73a9ff4444  x5  fefeff73a9ff4444  x6  fefeff73a9ff4444  x7  7f7f7f7fff7f7f7f
08-08 15:18:13.790  3388  3388 F DEBUG   :     x8  00000000000000f0  x9  00000075f24ec4e0  x10 0000000000000000  x11 0000000000000001
08-08 15:18:13.790  3388  3388 F DEBUG   :     x12 00000074abc648f8  x13 ffffffffffffffff  x14 ff00000000000000  x15 ffffffffffffffff
08-08 15:18:13.790  3388  3388 F DEBUG   :     x16 00000075f25b88c0  x17 00000075f25963e0  x18 0000007495b7a000  x19 00000000000000ac
08-08 15:18:13.790  3388  3388 F DEBUG   :     x20 0000000000000c2b  x21 00000000000000b2  x22 0000000000000d25  x23 00000000ffffffff
08-08 15:18:13.790  3388  3388 F DEBUG   :     x24 72fd1ad0f9701af3  x25 00000074abc67521  x26 00000000000002c0  x27 00000074abc6a020
08-08 15:18:13.790  3388  3388 F DEBUG   :     x28 00000075f282ba73  x29 00000074abc67370
08-08 15:18:13.790  3388  3388 F DEBUG   :     sp  00000074abc672a0  lr  00000075f254a4f0  pc  00000075f254a520
08-08 15:18:13.904  3388  3388 F DEBUG   : 
08-08 15:18:13.904  3388  3388 F DEBUG   : backtrace:
08-08 15:18:13.904  3388  3388 F DEBUG   :       #00 pc 0000000000082520  /apex/com.android.runtime/lib64/bionic/libc.so (abort+176) (BuildId: 79d4445cb019c4250b548cde1185f8b2)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #01 pc 00000000000098c8  /system/lib64/libudf.so (fdleak_aee_system_exception+264) (BuildId: cb769087f9bdc8c0f86b111a47dc1028)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #02 pc 000000000000aa8c  /system/lib64/libudf.so (fdleak_record_backtrace+2516) (BuildId: cb769087f9bdc8c0f86b111a47dc1028)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #03 pc 000000000000a06c  /system/lib64/libudf.so (open+268) (BuildId: cb769087f9bdc8c0f86b111a47dc1028)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #04 pc 000000000004fe98  /data/app/xxxxx-JLMOwpI3DFNARefZNr5X8Q==/lib/arm64/libmmkv.so (BuildId: 74cb407a0d9aff9f956ffed7929524eefb107aff)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #05 pc 00000000000516fc  /data/app/xxxxx-JLMOwpI3DFNARefZNr5X8Q==/lib/arm64/libmmkv.so (BuildId: 74cb407a0d9aff9f956ffed7929524eefb107aff)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #06 pc 0000000000051db8  /data/app/xxxxx-JLMOwpI3DFNARefZNr5X8Q==/lib/arm64/libmmkv.so (BuildId: 74cb407a0d9aff9f956ffed7929524eefb107aff)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #07 pc 0000000000040ab0  /data/app/xxxxx-JLMOwpI3DFNARefZNr5X8Q==/lib/arm64/libmmkv.so (BuildId: 74cb407a0d9aff9f956ffed7929524eefb107aff)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #08 pc 0000000000041200  /data/app/xxxxx-JLMOwpI3DFNARefZNr5X8Q==/lib/arm64/libmmkv.so (BuildId: 74cb407a0d9aff9f956ffed7929524eefb107aff)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #09 pc 0000000000031e38  /data/app/xxxxx-JLMOwpI3DFNARefZNr5X8Q==/lib/arm64/libmmkv.so (BuildId: 74cb407a0d9aff9f956ffed7929524eefb107aff)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #10 pc 00000000000bf644  /data/app/xxxxx-JLMOwpI3DFNARefZNr5X8Q==/oat/arm64/base.odex (art_jni_trampoline+244)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #11 pc 00000000020ac238  /memfd:/jit-cache (deleted) (com.tencent.mmkv.MMKV.G+88)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #12 pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #13 pc 00000000001460cc  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #14 pc 00000000002e4948  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #15 pc 00000000002df9d4  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+900) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #16 pc 00000000005a98e0  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+368) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.904  3388  3388 F DEBUG   :       #17 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #18 pc 0000000000c313e4  /data/app/xxxxx-JLMOwpI3DFNARefZNr5X8Q==/oat/arm64/base.vdex (f0.b.d.e.a.<init>+36)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #19 pc 00000000005a93d8  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #20 pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #21 pc 0000000000c31428  /data/app/xxxxx-JLMOwpI3DFNARefZNr5X8Q==/oat/arm64/base.vdex (f0.b.d.e.a.<init>+28)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #22 pc 00000000002b5278  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.6781556724778835626+240) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #23 pc 00000000005981d8  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1024) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #24 pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #25 pc 00000000020ab20c  /memfd:/jit-cache (deleted) (xxxxx.putString+156)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #26 pc 00000000020abdb8  /memfd:/jit-cache (deleted) (xxxxx.updateAppModel+424)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #27 pc 00000000020ac88c  /memfd:/jit-cache (deleted) (xxxxx.updateAppModelByOffline+76)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #28 pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 890b396cb69027b4b9539a4c757f552e)
08-08 15:18:13.905  3388  3388 F DEBUG   :       #29 pc 00000000001460ac  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: 890b396cb69027b4b9539a4c757f552e)

**Comment by lingol** [comment]
Please provide information as the issue template requires. Especially the logs of MMKV, and the symbolized call stacks.

**Comment by lingol** [comment]
Closed due to inactive.
