### ISSUE TITLE
MMKV.mmkvWithID()   crash

### ISSUE THREAD

**Issue by zaijie1213** [Tencent/MMKV#138]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin
java

### The version of MMKV

> e.g. v1.0.10

v1.0.13

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

AAR

### What's the issue?
call MMKV.mmkvWithID()  crash

> Post the outputs or screenshots for errors.
> 
[java.lang.StackOverflowError stack size 8MB
com.tencent.mmkv.MMKV.getMMKVWithID(Native Method)
com.tencent.mmkv.MMKV.a(MMKV.java:73)
******* 
******
**.**.MainActivity.onCreate(MainActivity.java:411)
android.app.Activity.performCreate(Activity.java:7183)
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
android.app.ActivityThread.-wrap11(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
android.os.Handler.dispatchMessage(Handler.java:105)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:6938)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
Have you init MMKV by calling `MMKV.initialize()` before getting any MMKV instance?
Checkout these for possible duplication. #60 #80

**Comment by zaijie1213** [comment]
I called MMKV.initialize() before，Otherwise the crash log is You should Call MMKV.initialize() first.not duplicate the #60 and #80

**Comment by zaijie1213** [comment]
get some log like this


012-02 18:09:09.143 4866 4915 E MMKV : check crc [default_process_safe] fail, crc32:3068818422, m_crcDigest:1164412735
--
112-02 18:09:09.181 4866 4915 E MMKV : check crc [default] fail, crc32:2588594211, m_crcDigest:3683764072
212-02 18:09:09.185 4866 4866 E AndroidRuntime: at com.tencent.mmkv.MMKV.getMMKVWithID(Native Method)
312-02 18:09:09.185 4866 4866 E AndroidRuntime: at com.tencent.mmkv.MMKV.a(MMKV.java:82)

**Comment by zaijie1213** [comment]
crash without set the mode  MMKV.MULTI_PROCESS_MODE

**Comment by lingol** [comment]
That's something new. Thanks for your feedback.
