### ISSUE TITLE
OpenHarmony customize storage path error

### ISSUE THREAD

**Issue by Martin-HZK** [Tencent/MMKV#1381]
OpenHarmony在定制路径的时候initialize方法在文档中写的函数参数类型不正确
let appCtx = this.context.getApplicationContext();
let rootDir = appCtx.filesDir + '/mmkv_2';
let cacheDir = appCtx.cacheDir;
MMKV.initialize(rootDir, cacheDir);
第一个传入类型报错应该是Context类型的而不是string类型

**Comment by Martin-HZK** [comment]
解决方法：修改成initializeWithPath方法即可

**Comment by lingol** [comment]
Noted. I will edit the wiki.
