### ISSUE TITLE
pod异常

### ISSUE THREAD

**Issue by q760440238** [Tencent/MMKV#1382]
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: undefined method `exists?' for class File.

     #  from /Users/qianyu/Desktop/event/xxx/xxx/ios/Podfile:10
     #  -------------------------------------------
     #    plugin_deps_file = File.expand_path(File.join(flutter_application_path, '..', '.flutter-plugins-dependencies'))
     >    if not File.exists?(plugin_deps_file)
     #      is_module = true;
     #  -------------------------------------------

**Comment by lingol** [comment]
Upgrade your CocadPods.

**Comment by lingol** [comment]
Plus, that CocoaPods plugin is no longer needed for the latest MMKV flutter plugin.

**Comment by q760440238** [comment]
请说中文，cocadpods已经是最新了，只有m2和m3芯片的电脑上，遇到了这些问题，无法pod下载依赖库，ruby@3.0
已经pub get了
    [!] Invalid `Podfile` file: Fail to find any mmkv plugin dependencies. If you're running pod install manually, make sure flutter pub get is executed first.

     #  from /Users/qianyu/Desktop/event/hayya/flutter_nigo/ios/Podfile:23
     #  -------------------------------------------
     #    end
     >    raise "Fail to find any mmkv plugin dependencies. If you're running pod install manually, make sure flutter pub get is executed first"
     #  end
     #  -------------------------------------------

**Comment by q760440238** [comment]
使用的flutter下载依赖

**Comment by lingol** [comment]
Delete your pod file.lock and try again.

PS: writing in English is convenient for all users that would possibly face the same problem.

**Comment by q760440238** [comment]
> Delete your pod file.lock and try again.
> 
> PS: writing in English is convenient for all users that would possibly face the same problem.
Unfortunately, podfile.lock did not even generate

**Comment by lingol** [comment]
After the **Podfile.lock** is deleted (or never been generated), you can try `pod install --repo-update` in your **xxx/ios** directory.
