### ISSUE TITLE
[Feature Request] Add a Multi-process Callback/listener being notified in all processes when a change is done in any of them

### ISSUE THREAD

**Issue by dimitar71** [Tencent/MMKV#1387]
MMKV for Android is great supporting multiple processes.

One important feature is missing though: the ability to notify a listener across all processes when a change is done (add/remove/delete).
Something of the vicinity of `SharedPreferences.OnSharedPreferenceChangeListener` or `LiveData` or alike.

Not sure if there is even a plan for it, at least for Android.

But honestly, there is literally no library around which supports this.
Except Harmony - but it does not work in some cases.

**Comment by lingol** [comment]
MMKV has something similar to this, it's called [ContentChangeHandler](https://github.com/Tencent/MMKV/blob/master/Core/MMKV.h#L502). 
Note that it's not in realtime. The listener will have to check or at least do a CRUD to trigger the callback.

**Comment by dimitar71** [comment]
Yeah, this will require a while loop or a count timer or alike.
Which will be read/write expensive, happening so often.

**Comment by lingol** [comment]
It's available on most platforms (except OHOS).
For Android https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/java/com/tencent/mmkv/MMKV.java#L1647-L1648

**Comment by dimitar71** [comment]
Thank you!

Spent some time with it.
Extend MMKV, and overrode `checkContentChangedByOuterProcess()`,

It is going to be an overkill, since it does not provide the key names for changed values.
We have around 300 items stored.
Getting all values may be an overkill, especially for long JSON strings.

Is there a possibility to know which keys have been updated?

E.g. `checkContentChangedByOuterProcess(changedKeys: List<String>)`

**Comment by lingol** [comment]
It's impossible. Even if we did it won't be accurate because the file might be full write back by the writer and there's no way to know which key changes.

**Comment by dimitar71** [comment]
Yes, I was suspecting such an answer.

Thank you for validating and confirming all this!
