### ISSUE TITLE
java.lang.UnsatisfiedLinkError: 

### ISSUE THREAD

**Issue by BobChuang** [Tencent/MMKV#139]
### The language of MMKV

> Java

### The version of MMKV

> v1.0.11

### The platform of MMKV

> Android

### The installation of MMKV

> Gradle

### What's the issue?

java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary (Runtime.java:367)
  at java.lang.System.loadLibrary (System.java:1076)
  at com.tencent.mmkv.MMKV.<clinit> (MMKV.java:38)
  at com.example.App.b (App.java:65)
  at com.example.App.onCreate (App.java:30)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1018)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:4959)
  at android.app.ActivityThread.-wrap1 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1549)
  at android.os.Handler.dispatchMessage (Handler.java:111)
  at android.os.Looper.loop (Looper.java:207)
  at android.app.ActivityThread.main (ActivityThread.java:5728)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:789)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:679)

![image](https://user-images.githubusercontent.com/16433004/49415664-5a897f80-f7b2-11e8-9e1e-db62d018ad31.png)

**Comment by lingol** [comment]
Is it right that it only happens on API level 19 and bellow? Similar cases had been reported. Yet we still don't know why. This link may provide some info. https://www.jianshu.com/p/fbd3820d0864

**Comment by lingol** [comment]
And can you provide the exception reason of `UnsatisfiedLinkError`? Looks like it's trimmed in your log.

**Comment by BobChuang** [comment]
This log is from Google Console. I can show u another log from firebase to help u solve this kind of crash in the latest version. Thanks a lot :)

This
![image](https://user-images.githubusercontent.com/16433004/49418032-5dd53900-f7bb-11e8-89c5-36b814dca683.png)
And this
![image](https://user-images.githubusercontent.com/16433004/49418087-9117c800-f7bb-11e8-90a7-2cc63dca906f.png)
Mobile devices
![image](https://user-images.githubusercontent.com/16433004/49418153-cb816500-f7bb-11e8-9ada-1151724e6028.png)
![image](https://user-images.githubusercontent.com/16433004/49418180-e0f68f00-f7bb-11e8-94df-05e232c5dc47.png)

**Comment by lingol** [comment]
Well for these specify error due to loading **libc++_shared.so**, you can try MMKV with static link of libc++ from v1.0.13 and above. https://github.com/Tencent/MMKV/releases

**Comment by lingol** [comment]
Or, you can try [ReLinker](https://github.com/KeepSafe/ReLinker), which solved these kind of error.

**Comment by lingol** [comment]
Close due to inactive.

**Comment by luyaotree** [comment]
我这里使用的版本是1.0.18，还是出现了此类错误：java.lang.UnsatisfiedLinkError

Native method not found: com.tencent.mmkv.MMKV.decodeString:(JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;

**Comment by luyaotree** [comment]
我使用的版本是：'com.tencent:mmkv-static:1.0.18'，还是出现了此类错误：
java.lang.UnsatisfiedLinkError

Native method not found: com.tencent.mmkv.MMKV.decodeString:(JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;

**Comment by lingol** [comment]
@luyaotree Read the info above, try it out.

**Comment by DominicYoung** [comment]
实际上不只是Android 4.4以下崩溃
![image](https://user-images.githubusercontent.com/9331919/62179495-65b3a000-b37f-11e9-8b33-8d08493ffea3.png)

**Comment by lingol** [comment]
> 实际上不只是Android 4.4以下崩溃 --- com.tencent:mmkv:1.0.17
> ![image](https://user-images.githubusercontent.com/9331919/62179495-65b3a000-b37f-11e9-8b33-8d08493ffea3.png)

Yeah, shit happens. You can try `com.tencent:mmkv-static:1.0.22` next time.
