### ISSUE TITLE
Assertion failed: (m_metaFile->isFileValid()), function readActualSize, file MMKV_IO.cpp, line 386.

### ISSUE THREAD

**Issue by bytedanceJia** [Tencent/MMKV#1402]
## Note:
Assertion failed: (m_metaFile->isFileValid()), function readActualSize, file MMKV_IO.cpp, line 386.
### The language of MMKV

> e.g. Objective-C

### The version of MMKV
 v1.2.2  

### The platform of MMKV

>  iOS 

### The installation of MMKV

>  Cocoapods

### What's the issue?

>  launch crash 
![image](https://github.com/user-attachments/assets/5d45960c-1218-4803-8968-00ed5d9b182a)
![image](https://github.com/user-attachments/assets/db27cf2e-8104-46a5-85eb-64c5afeb9818)

**Comment by lingol** [comment]
It's most likely that the device doesn't have enough space for the file to be mmapped successfully. However that requires logs from MMKV to verify. And you have provide none.
Also, your version is too old for any investigation.

So,
1. Upgrade your MMKV to latest version,
2. And, provide logs from MMKV if you still have the same problem after the upgrade.
