### ISSUE TITLE
get string function

### ISSUE THREAD

**Issue by passerbyloo** [Tencent/MMKV#141]
now for the get string is used `setObject` and `getObjectOfClass`, will consider add the setString/getString function?

Or your treat string as a object?

**Comment by lingol** [comment]
Yes. NSString **is** an OC object, no doubt about that.

**Comment by lingol** [comment]
Maybe.

**Comment by lingol** [comment]
Implemented in dev with #149 #146 .

**Comment by lingol** [comment]
Released with [v1.0.15](https://github.com/Tencent/MMKV/releases/tag/v1.0.15).
