### ISSUE TITLE
意外自动清除数据

### ISSUE THREAD

**Issue by CobblyHelloTalk** [Tencent/MMKV#1414]
经常因为内存紧张问题，意外自动清除了数据，版本是1.3.9 swift5 不知道你们有没有遇到过

**Comment by CobblyHelloTalk** [comment]
> happens

好的，目前只是有个别反馈，等复现的时候 会去留意日志的。到时候我再上来问问哈

**Comment by imaginedays** [comment]
使用1.3.7时，有以下场景会出现有些数据无法重新获取

**Comment by imaginedays** [comment]
使用1.3.7和1.3.9时也会出现有数据被清除的情况
**环境：**
1、车机台架 Android系统12
2、App内两个进程，MMKV初始化在Application里，使用多进程模式MMKV.MULTI_PROCESS_MODE
**复现流程：**
车机上 登录App（MMKV存储token），退出登录（MMKV.clearAll()），重新登录（MMKV存储token）关电源，开电源，发现token没了。

**Comment by lingol** [comment]
Again, logs please.

**Comment by lingol** [comment]
> 使用1.3.7和1.3.9时也会出现有数据被清除的情况 **环境：** 1、车机台架 Android系统12 2、App内两个进程，MMKV初始化在Application里，使用多进程模式MMKV.MULTI_PROCESS_MODE **复现流程：** 车机上 登录App（MMKV存储token），退出登录（MMKV.clearAll()），重新登录（MMKV存储token）关电源，开电源，发现token没了。

Wait, what? You call `MMKV.clearAll()` and complain about data not existing. 
Do you misunderstand what that function does?

**Comment by lingol** [comment]
Closed due to lack of info.
