### ISSUE TITLE
key类型疑问

### ISSUE THREAD

**Issue by kumor00** [Tencent/MMKV#1417]
The language of MMKV
C++
The version of MMKV
1.3.9
The platform of MMKV
Windows x86

key只能使用字符串类型吗，能否写入int32，int64类型的key。
测试中我将int32转换为4个字节写入string_view中当作key，能够正常写入和读取，但不知道mmkv库内部是否会出问题

**Comment by lingol** [comment]
There's no constraint on key as long as it can be represented by `string_view`.

**Comment by kumor00** [comment]
> There's no constraint on key as long as it can be represented by `string_view`。

thanks
