### ISSUE TITLE
1.3.x LTS  android minSdk 21 support

### ISSUE THREAD

**Issue by Virczz** [Tencent/MMKV#1418]
项目需要最低sdk为21，以前是用1.3.2的。现在升级到 1.3.7，还是提示需要最小为 23。该怎么解决。

flutter version: 3.19.6

测试：使用flutter create 了一个新的app，然后把minSdk 改 21 ，正常运行。然后加上 mmkv: 1.3.7 或  mmkv: 1.3.10。pub get 成功
![image](https://github.com/user-attachments/assets/ebc74d1e-4f38-4b5d-8290-a9fe823660fe)

运行失败：

![image](https://github.com/user-attachments/assets/b555080e-cb38-45bb-9faf-6e5c48d8dbeb)

请协助处理，谢谢。

**Comment by Virczz** [comment]
尝试过将 mmkv_android 下载到本地，强制修改 minSdk 为21后通过 dependency_overrides 引用，报错信息也是类似的。

**Comment by lingol** [comment]
Use v1.3.10.

**Comment by lingol** [comment]
Background info: https://github.com/Tencent/MMKV/issues/1410.

**Comment by Virczz** [comment]
Emm, it's not working. Even if it's a new project. The snapshot above is already v1.3.10.

**Comment by lingol** [comment]
Oh, I found out what's wrong. The minSdkVersion of `build.gradle` in the mmkv_android plugin is incorrect. I should fix it as soon as possible.

**Comment by lingol** [comment]
mmkv_android version 1.0.8 has just been published, you can try it in 10 minutes.

**Comment by Virczz** [comment]
it's working, thanks.
