### ISSUE TITLE
kotlin version conflict?

### ISSUE THREAD

**Issue by Nullifier1571** [Tencent/MMKV#1419]
use latest version 2.0.0 find this compile error, is pom conflict? use  aar compiled by myself is ok。

`> Task :rxdatasources-api:compileReleaseKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/nullifier/.gradle/caches/transforms-2/files-2.1/6bc91ea9b935f3e27737ccddaeed2a40/jetified-kotlin-stdlib-jdk7-1.3.50.jar (version 1.3)
    /Users/nullifier/.gradle/caches/transforms-2/files-2.1/924d882cd3719d0ab9d231085359939a/jetified-kotlin-stdlib-1.7.10.jar (version 1.7)
    /Users/nullifier/.gradle/caches/transforms-2/files-2.1/1d3fdd47ead9633bf8b5ec726b9760e7/jetified-kotlin-stdlib-common-1.7.10.jar (version 1.7)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: /Users/nullifier/.gradle/caches/transforms-2/files-2.1/1d3fdd47ead9633bf8b5ec726b9760e7/jetified-kotlin-stdlib-common-1.7.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.4.2.
e: /Users/nullifier/.gradle/caches/transforms-2/files-2.1/924d882cd3719d0ab9d231085359939a/jetified-kotlin-stdlib-1.7.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.4.2.
e: /Users/nullifier/.gradle/caches/transforms-2/files-2.1/b01b8cd039d9030c2255aa5d58030e4a/jetified-annotation-jvm-1.8.0.jar!/META-INF/annotation.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.0, expected version is 1.4.2.

FAILURE: Build failed with an exception.`

**Comment by lingol** [comment]
How is this a MMKV problem? Looks like it is your local environment configuration problem.

**Comment by Nullifier1571** [comment]
should be it
