### ISSUE TITLE
鸿蒙mmkv获取int32数据问题

### ISSUE THREAD

**Issue by weikjblue** [Tencent/MMKV#1423]
鸿蒙使用ohos/mmkv使用encodeNumber存储数据 迁移到腾讯mmkv后 通过decodeInt32获取不到数据  拿到的是0

**Comment by lingol** [comment]
Looks like the 'ohos/mmkv' use `double` to encode `number`. You should try decode it as `double`.
https://gitee.com/openharmony-tpc/MMKV/blob/master/library/src/main/ets/components/MainPage/MMKV.ts#L399
