### ISSUE TITLE
Fail to create an MMKV instance [XXX] in NAPI

### ISSUE THREAD

**Issue by fiveandnine** [Tencent/MMKV#1426]
MMKV初始化时大量报这个崩溃，目前使用的是1.3.9版本，harmonyOS next平台

调用方式：MMKV.mmkvWithID(fileName, MMKV.MULTI_PROCESS_MODE, crpKey, context.filesDir + "/mmkv")

**Comment by lingol** [comment]
Please follow the issue template and provide **logs from MMKV**.

**Comment by lingol** [comment]
Closed due to lack of info.
