### ISSUE TITLE
mmkv 1.3.1 Could not find 'libmmkv.so'

### ISSUE THREAD

**Issue by PanPersonalProject** [Tencent/MMKV#1427]
Firebase shows that on some devices mmkv fails to load due to not finding libmmkv.so, but the AAB release package contains libmmkv.so for both v8a and v7a.

https://github.com/Tencent/MMKV/issues/1321
According to the issue, it seems that mmkv removed the 32-bit so in version 1.3.5. However, the app is published on Google Play which only supports 64-bit, and the mmkv version used is 1.3.1, which still includes the 32-bit so.

https://github.com/Tencent/MMKV/issues/1322
This issue mentions that even after adding the ReLinker.loadLibrary code to load the library, the problem persists.

In the application's onCreate method:

String processName = Utils.getProcessName();
if (processName != null && processName.equals(this.getPackageName())) {
    try {
        MMKV.initialize(this);
    } catch (Throwable e) {
        MMKV.initialize(this, libName -> ReLinker.loadLibrary(getApplicationContext(), libName));
    }
}

Log stack:
    Caused by gt1: Could not find 'libmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:173)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       ...

**Comment by lingol** [comment]
Then it's no longer an MMKV issue. Nothing we as the library dev can do about it if the `ReLinker.loadLibrary` can't fix it.
>but the AAB release package contains libmmkv.so for both v8a and v7a.

**Comment by PanPersonalProject** [comment]
> Then it's no longer an MMKV issue. Nothing we as the library dev can do about it if the `ReLinker.loadLibrary` can't fix it.
> 
> > but the AAB release package contains libmmkv.so for both v8a and v7a.

If mmkv is upgraded to version 2.0.0, is it possible to fix this issue?

**Comment by lingol** [comment]
No I don't think so but you can try.
