### ISSUE TITLE
鸿蒙调用 decodeNumberSet 方法后，Flutter 卡死

### ISSUE THREAD

**Issue by ChanNagihong** [Tencent/MMKV#1428]
### Demo工程
[Demo工程](https://github.com/user-attachments/files/17702383/test.zip)
### 背景 
Flutter 3.22 + 鸿蒙 Api 12
### 重现步骤

**点击按钮 "MMKV valid decode"**

> 此处调用正常的 MMKV decode，随便读取一下数据

**点击按钮 "Open TestFlutterPage"**

> 此处跳转普通 Flutter 页面，是正常的

**返回首页，点击 "Open TestFlutterPage2"**

> 此处跳转多引擎创建的 Flutter 页面，是正常的

**点击按钮 "MMKV invalid decode"**

> 此处调用 MMKV decodeNumberSet 方法，随后就开始不正常了

**点击按钮 "Open TestFlutterPage"**

> 跳转普通 Flutter 页面，空白

**返回首页，点击 "Open TestFlutterPage2"**

> 跳转多引擎创建的 Flutter 页面，空白
<img width="850" alt="截屏2024-11-11 20 21 19" src="https://github.com/user-attachments/assets/e179d357-2f3e-4dfe-9b47-362b80868465">
<img width="332" alt="截屏2024-11-11 20 20 42" src="https://github.com/user-attachments/assets/035a3448-36df-4257-9563-979915b36f16">

**Comment by lingol** [comment]
Indeed. Will look into it later.

**Comment by lingol** [comment]
It's a typo in the Core lib, will fix soon.

**Comment by lingol** [comment]
It's fixed in [v2.0.1.](https://github.com/Tencent/MMKV/releases/tag/v2.0.1)
