### ISSUE TITLE
Do not support 32-bit

### ISSUE THREAD

**Issue by xiaobaicz** [Tencent/MMKV#1429]
Version 2.0.0 do not support 32-bit

Since there are still many 32-bit devices (such as Android TV or STB)
Considering continuing to support 32-bit?

**Comment by lingol** [comment]
If you need 32bit you stick to v1.3.x LTS versions.

**Comment by xiaobaicz** [comment]
Hello @lingol 
Sorry, my description is incomplete.
What I want to express is that the compatibility with Android15 16K PS can only be upgraded to V2.0.0 at present.
However, V2.0.0 does not support 32-bit and will affect some devices.

**Comment by lingol** [comment]
That's a choice you have to make. 
We have stated clearly that no features will be added in the LTS series when 1.3.7, the first LTS version, launches.

**Comment by Goooler** [comment]
See https://github.com/Tencent/MMKV/issues/1503#issuecomment-2800594744.

**Comment by lingol** [comment]
16K pagesize is supported in v1.3.14.
