### ISSUE TITLE
mmkv 1.2.2 crash  #01 pc 000000000002198c==/lib/arm64/libmmkv.so

### ISSUE THREAD

**Issue by jiahongfei** [Tencent/MMKV#1433]
### The language of MMKV
java
### The version of MMKV
v1.2.2 
### The platform of MMKV
 Android
### The installation of MMKV
 Maven
### What's the issue?
backtrace:
    #00 pc 000000000009d750  /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy_aarch64_simd+272)
    #01 pc 000000000002198c  /data/app/~~RmHOnK0S_AnicJr6Oz0a0Q==/HyIzmppytg0m4Xx0usNhHw==/lib/arm64/libmmkv.so
    #02 pc 000000000001caf0  /data/app/~~RmHOnK0S_AnicJr6Oz0a0Q==/HyIzmppytg0m4Xx0usNhHw==/lib/arm64/libmmkv.so
    #03 pc 000000000001c540  /data/app/~~RmHOnK0S_AnicJr6Oz0a0Q==/HyIzmppytg0m4Xx0usNhHw==/lib/arm64/libmmkv.so
    #04 pc 000000000001ba24  /data/app/~~RmHOnK0S_AnicJr6Oz0a0Q==/HyIzmppytg0m4Xx0usNhHw==/lib/arm64/libmmkv.so
    #05 pc 0000000000014320  /data/app/~~RmHOnK0S_AnicJr6Oz0a0Q==/HyIzmppytg0m4Xx0usNhHw==/lib/arm64/libmmkv.so
    #06 pc 0000000000010fe0  /data/app/~~RmHOnK0S_AnicJr6Oz0a0Q==/HyIzmppytg0m4Xx0usNhHw==/lib/arm64/libmmkv.so
    #07 pc 0000000000227430  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144)
    #08 pc 000000000020a990  /apex/com.android.art/lib64/libart.so (nterp_helper+5648)
    #09 pc 000000000020a2d4  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #10 pc 000000000020a2d4  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #11 pc 000000000020a2d4  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #12 pc 000000000020a2d4  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #13 pc 00000000002093b4  /apex/com.android.art/lib64/libart.so (nterp_helper+52)
    #14 pc 00000000002f904c  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+796)

java stacktrace:
  at com.tencent.mmkv.MMKV.encodeString(Native method)
  at com.tencent.mmkv.MMKV.encode(MMKV.java:373)
at com.xxx.raven.a.c.a(RavenRequestPool.java:180)
  at com.xxx.raven.a.c.a(RavenRequestPool.java:89)
  at com.xxx.raven.b.b(RavenDataManger.java:78)
  at com.xxx.raven.b.lambda$-TECYr4y87eoct1NPW434-_wDDw(unavailable:0)
  at com.xxx.raven.-$$Lambda$b$-TECYr4y87eoct1NPW434-_wDDw.run(unavailable:4)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
  at java.lang.Thread.run(Thread.java:1042)

**Comment by lingol** [comment]
v1.2.2 is just too old. Upgrade to the latest version first. Come back if you still have problem.
