### ISSUE TITLE
Abort message: 'JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xa4

### ISSUE THREAD

**Issue by gentlemanyc** [Tencent/MMKV#1437]
decodeString时崩溃：
Abort message: 'JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xa4
                                                                                                        string: '?tokopedia.link/promo-guncang-app?utm_source=noematics&utm_medium=media&utm_campaign=noem-11nov2024-11nov2024-mf-25-65-noem-app-gsb2-awr-tp-id51mlab01-1124-tkdd-cmpn'
                                                                                                        input: '<0xa4> 0x01 0x74 0x6f 0x6b 0x6f 0x70 0x65 0x64 0x69 0x61 0x2e 0x6c 0x69 0x6e 0x6b 0x2f 0x70 0x72 0x6f 0x6d 0x6f 0x2d 0x67 0x75 0x6e 0x63 0x61 0x6e 0x67 0x2d 0x61 0x70 0x70 0x3f 0x75 0x74 0x6d 0x5f 0x73 0x6f 0x75 0x72 0x63 0x65 0x3d 0x6e 0x6f 0x65 0x6d 0x61 0x74 0x69 0x63 0x73 0x26 0x75 0x74 0x6d 0x5f 0x6d 0x65 0x64 0x69 0x75 0x6d 0x3d 0x6d 0x65 0x64 0x69 0x61 0x26 0x75 0x74 0x6d 0x5f 0x63 0x61 0x6d 0x70 0x61 0x69 0x67 0x6e 0x3d 0x6e 0x6f 0x65 0x6d 0x2d 0x31 0x31 0x6e 0x6f 0x76 0x32 0x30 0x32 0x34 0x2d 0x31 0x31 0x6e 0x6f 0x76 0x32 0x30 0x32 0x34 0x2d 0x6d 0x66 0x2d 0x32 0x35 0x2d 0x36 0x35 0x2d 0x6e 0x6f 0x65 0x6d 0x2d 0x61 0x70 0x70 0x2d 0x67 0x73 0x62 0x32 0x2d 0x61 0x77 0x72 0x2d 0x74 0x70 0x2d 0x69 0x64 0x35 0x31 0x6d 0x6c 0x61 0x62 0x30 0x31 0x2d 0x31 0x31 0x32 0x34 0x2d 0x74 0x6b 0x64 0x64 0x2d 0x63 0x6d 0x70 0x6e'
                                                                                                        in call to NewStringUTF
                                                                                                        from java.lang.String com.tencent.mmkv.MMKV.decodeString(long, java.lang.String, java.lang.String)'

**Comment by lingol** [comment]
It's what it is. Likely, the value you stored before is not a valid UTF-8 string.

**Comment by lingol** [comment]
If you are using an old version of MMKV, upgrade first. 
If you cannot reproduce the whole procedure, from encoding to decoding, there's little thing we can do about it.
