### ISSUE TITLE
is there any way to backup data and restore?

### ISSUE THREAD

**Issue by ksxkq** [Tencent/MMKV#144]
The language of MMKV
Java

The version of MMKV
v1.0.14

The platform of MMKV
Android

The installation of MMKV
Maven

What's the issue?
I want to backup data on sdcard or other place, but I don't find the way to do this.

**Comment by lingol** [comment]
There's no such interface in MMKV to to it. You can just copy those files as you desire.

**Comment by ksxkq** [comment]
I have tried to save these files. but there is a problem.
When I copy backup file to inner path (context.getFilesDir().getAbsolutePath() + "/mmkv"), it works fine. All data is restored.
But when restart App (kill and restart), All data is lost.
I don't know what to do now, I need help.

**Comment by lingol** [comment]
You need to backup the crc file as well.
