### ISSUE TITLE
Android15 16kb

### ISSUE THREAD

**Issue by yankaitao** [Tencent/MMKV#1444]
java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~2LZjlB85wMEbIvw27r84mg==/zXfau7L8YABhxbg3QTRe5Q==/lib/arm64/libmmkv.so" (new hash type from the future?)

**Comment by yankaitao** [comment]
sdk版本：2.0.1

**Comment by lingol** [comment]
Please provide information required by the issue template.
