### ISSUE TITLE
HarmonyOS encodeBytes/decodeBytes

### ISSUE THREAD

**Issue by ChanNagihong** [Tencent/MMKV#1447]
Background:
Harmony OpenHarmony SDK API Version 12

```
          let binary = new Uint8Array([1, 2, 3])
          MMKV.defaultMMKV().encodeBytes('test', binary)
          let decode = MMKV.defaultMMKV().decodeBytes('test')
          console.log(`Test binary: ${binary}`)
          console.log(`Test decode: ${new Uint8Array(decode)}`)
```

Output: 
Test binary: 1,2,3
Test decode: 44,135,127

Expect output:
Test binary: 1,2,3
Test decode: 1,2,3

**Comment by lingol** [comment]
You are calling the wrong methods. Should use `encodeTypedArray()` & `decodeUint8Array()` instead.

**Comment by lingol** [comment]
Example code provided:
https://github.com/Tencent/MMKV/blob/master/OpenHarmony/entry/src/main/ets/pages/Index.ets#L189
