### ISSUE TITLE
Use Main Thread only API in `initWithMMapID` cause Test Fail

### ISSUE THREAD

**Issue by zhgw01** [Tencent/MMKV#145]
### The language of MMKV
Objective-C

### The version of MMKV

> v1.0.14

### The platform of MMKV

> iOS

### The installation of MMKV

> Cocoapods

### What's the issue?

Our unit test schema open `Main Thread Checker` by default.  As a result, MMKV's `initWithMMapID:(NSString *)mmapID cryptKey:(NSData *)cryptKey rootPath:(nullable NSString *)rootPath` throw an exception.

This is because we init MMKV from non main thread, and MMKV's `initWithMMapID:(NSString *)mmapID cryptKey:(NSData *)cryptKey rootPath:(nullable NSString *)rootPath` use `[UIApplication sharedApplication]` in this function.

`[UIApplication sharedApplication]` may be thread safe, but Apple doesn't recommend to call UIKit's function in non main thread function.

**So is it suitable to use `[UIApplication sharedApplication]` in MMKV's init function?**

**Comment by lingol** [comment]
MMKV for iOS needs to know the current application state, aka in foreground or background, to decide using `mlock` or not. I'm afraid it's inevitable to call `[UIApplication sharedApplication]`.

**Comment by zhgw01** [comment]
But this is UIKit's object, apple doesn't recommend to use UIKit object in background thread. Is there any other way to get the state without directly using UIApplication? By using notification to get the state?

**Comment by lingol** [comment]
We already did that. But the initial status is required on MMKV initialization, which can’t avoid.

**Comment by lingol** [comment]
Fixed this warning with [v1.0.23](https://github.com/Tencent/MMKV/releases/tag/v1.0.23).
