### ISSUE TITLE
 public static String initialize(String rootDir, LibLoader loader) 方法Declared

### ISSUE THREAD

**Issue by Allen-ZXJ** [Tencent/MMKV#1451]
String dir = getFilesDir().getAbsolutePath() + "/mmkv";
MMKV.initialize(dir, new MMKV.LibLoader() {
    @Override
    public void loadLibrary(String libName) {
        ReLinker.loadLibrary(MyApplication.this, libName);
    }
});
这个方法被declared了，请问还能用不？ 或者可以用哪个去替换呢

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/java/com/tencent/mmkv/MMKV.java#L253

**Comment by lingol** [comment]
I think the IDE has provided the prompt info.

**Comment by Allen-ZXJ** [comment]
Thanks a lot！
