### ISSUE TITLE
初始化崩溃问题

### ISSUE THREAD

**Issue by Allen-ZXJ** [Tencent/MMKV#1452]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

通过Java代码初始化
 MMKV.initialize(this, libName -> ReLinker.loadLibrary(XXXApplication.this, libName)); //初始化MMKV

### The version of MMKV
1.3.9

### The platform of MMKV
Android

### The installation of MMKV

Maven【implementation 'com.tencent:mmkv:1.3.9'】

### What's the issue?
Firebase报错：
com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary (ApkLibraryInstaller.java:175)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:180)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:136)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:70)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:51)
com.cider.core.CiderApplication.lambda$onCreate$0 (CiderApplication.java:129)
com.tencent.mmkv.MMKV.doInitialize (MMKV.java:221)
com.tencent.mmkv.MMKV.initialize (MMKV.java:208)
com.tencent.mmkv.MMKV.initialize (MMKV.java:121)

我们项目build.gradle配了abiFilters "armeabi-v7a", "arm64-v8a"这俩种架构， 且是通过aab上架到google Play的。 
目前发现有俩种机型会有这个问题: Pixel 6 Pro 以及Nexus 5X。

请问要如何修复它？🙏

**Comment by lingol** [comment]
I don't know.

**Comment by lingol** [comment]
https://github.com/realm/realm-kotlin/issues/1202#issuecomment-1609094782, I hope it solves your issue.

**Comment by lingol** [comment]
https://www.google.com/search?q=pixel+6+pro+unsatisfied+link+error&newwindow=1&sca_esv=360d606574466e04&sxsrf=ADLYWIICIANY8r6x6wNiFOIiJzfuZGnWMw%3A1733488472240&ei=WO9SZ7mwDsvf1e8PhLjFyQg&ved=0ahUKEwi5vPDkk5OKAxXLb_UHHQRcMYkQ4dUDCA8&uact=5&oq=pixel+6+pro+unsatisfied+link+error&gs_lp=Egxnd3Mtd2l6LXNlcnAiInBpeGVsIDYgcHJvIHVuc2F0aXNmaWVkIGxpbmsgZXJyb3IyBxAhGKABGAoyBxAhGKABGAoyBxAhGKABGApI2oECUPAMWML_AXABeAGQAQCYAW-gAZsMqgEEMTguMbgBA8gBAPgBAZgCFKACzgzCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICChAAGIAEGEMYigXCAg0QLhiABBhDGOUEGIoFwgIOEC4YgAQYkQIY5QQYigXCAgsQABiABBiRAhiKBcICBRAAGIAEwgIREAAYgAQYkQIYsQMYgwEYigXCAh0QLhiABBiRAhjlBBiKBRiXBRjcBBjeBBjgBNgBAcICCxAAGIAEGIYDGIoFwgIGEAAYFhgewgIIEAAYgAQYogTCAggQABgWGAoYHsICBRAhGKABwgIFECEYqwKYAwCIBgGQBgq6BgYIARABGBSSBwQxOS4xoAeXbQ&sclient=gws-wiz-serp

**Comment by Keko2025** [comment]
删了你 gradle中 ndk 配置("abiFilters "armeabi-v7a", "arm64-v8a"这俩种架构"),打包后默认会支持以下4种

![Image](https://github.com/user-attachments/assets/ed2b12f8-017c-40f4-a04e-66d5f16b2b3e)

**Comment by kapaseker** [comment]
> https://www.google.com/search?q=pixel+6+pro+unsatisfied+link+error&newwindow=1&sca_esv=360d606574466e04&sxsrf=ADLYWIICIANY8r6x6wNiFOIiJzfuZGnWMw%3A1733488472240&ei=WO9SZ7mwDsvf1e8PhLjFyQg&ved=0ahUKEwi5vPDkk5OKAxXLb_UHHQRcMYkQ4dUDCA8&uact=5&oq=pixel+6+pro+unsatisfied+link+error&gs_lp=Egxnd3Mtd2l6LXNlcnAiInBpeGVsIDYgcHJvIHVuc2F0aXNmaWVkIGxpbmsgZXJyb3IyBxAhGKABGAoyBxAhGKABGAoyBxAhGKABGApI2oECUPAMWML_AXABeAGQAQCYAW-gAZsMqgEEMTguMbgBA8gBAPgBAZgCFKACzgzCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICChAAGIAEGEMYigXCAg0QLhiABBhDGOUEGIoFwgIOEC4YgAQYkQIY5QQYigXCAgsQABiABBiRAhiKBcICBRAAGIAEwgIREAAYgAQYkQIYsQMYgwEYigXCAh0QLhiABBiRAhjlBBiKBRiXBRjcBBjeBBjgBNgBAcICCxAAGIAEGIYDGIoFwgIGEAAYFhgewgIIEAAYgAQYogTCAggQABgWGAoYHsICBRAhGKABwgIFECEYqwKYAwCIBgGQBgq6BgYIARABGBSSBwQxOS4xoAeXbQ&sclient=gws-wiz-serp

你好，我想问一个鱼该issue不相关的问题，但是我找不到地方问了。就是如果多个第三方库都初始化自己的MMKV，这种情况下应该如何保证MMKV仅被初始化了一次？

**Comment by Allen-ZXJ** [comment]
我的问题算是解决了。应该是Google审核机的问题，其他机型没见过。量极少，可以接受

**Comment by Allen-ZXJ** [comment]
> > https://www.google.com/search?q=pixel+6+pro+unsatisfied+link+error&newwindow=1&sca_esv=360d606574466e04&sxsrf=ADLYWIICIANY8r6x6wNiFOIiJzfuZGnWMw%3A1733488472240&ei=WO9SZ7mwDsvf1e8PhLjFyQg&ved=0ahUKEwi5vPDkk5OKAxXLb_UHHQRcMYkQ4dUDCA8&uact=5&oq=pixel+6+pro+unsatisfied+link+error&gs_lp=Egxnd3Mtd2l6LXNlcnAiInBpeGVsIDYgcHJvIHVuc2F0aXNmaWVkIGxpbmsgZXJyb3IyBxAhGKABGAoyBxAhGKABGAoyBxAhGKABGApI2oECUPAMWML_AXABeAGQAQCYAW-gAZsMqgEEMTguMbgBA8gBAPgBAZgCFKACzgzCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICChAAGIAEGEMYigXCAg0QLhiABBhDGOUEGIoFwgIOEC4YgAQYkQIY5QQYigXCAgsQABiABBiRAhiKBcICBRAAGIAEwgIREAAYgAQYkQIYsQMYgwEYigXCAh0QLhiABBiRAhjlBBiKBRiXBRjcBBjeBBjgBNgBAcICCxAAGIAEGIYDGIoFwgIGEAAYFhgewgIIEAAYgAQYogTCAggQABgWGAoYHsICBRAhGKABwgIFECEYqwKYAwCIBgGQBgq6BgYIARABGBSSBwQxOS4xoAeXbQ&sclient=gws-wiz-serp
> 
> 你好，我想问一个鱼该issue不相关的问题，但是我找不到地方问了。就是如果多个第三方库都初始化自己的MMKV，这种情况下应该如何保证MMKV仅被初始化了一次？

多次初始化也没关系吧？我没看过源码，但是按理说同一个应用顶多只会生效一次。你是遇到什么业务场景了吗

**Comment by kapaseker** [comment]
> > > https://www.google.com/search?q=pixel+6+pro+unsatisfied+link+error&newwindow=1&sca_esv=360d606574466e04&sxsrf=ADLYWIICIANY8r6x6wNiFOIiJzfuZGnWMw%3A1733488472240&ei=WO9SZ7mwDsvf1e8PhLjFyQg&ved=0ahUKEwi5vPDkk5OKAxXLb_UHHQRcMYkQ4dUDCA8&uact=5&oq=pixel+6+pro+unsatisfied+link+error&gs_lp=Egxnd3Mtd2l6LXNlcnAiInBpeGVsIDYgcHJvIHVuc2F0aXNmaWVkIGxpbmsgZXJyb3IyBxAhGKABGAoyBxAhGKABGAoyBxAhGKABGApI2oECUPAMWML_AXABeAGQAQCYAW-gAZsMqgEEMTguMbgBA8gBAPgBAZgCFKACzgzCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICChAAGIAEGEMYigXCAg0QLhiABBhDGOUEGIoFwgIOEC4YgAQYkQIY5QQYigXCAgsQABiABBiRAhiKBcICBRAAGIAEwgIREAAYgAQYkQIYsQMYgwEYigXCAh0QLhiABBiRAhjlBBiKBRiXBRjcBBjeBBjgBNgBAcICCxAAGIAEGIYDGIoFwgIGEAAYFhgewgIIEAAYgAQYogTCAggQABgWGAoYHsICBRAhGKABwgIFECEYqwKYAwCIBgGQBgq6BgYIARABGBSSBwQxOS4xoAeXbQ&sclient=gws-wiz-serp
> > 
> > 
> > 你好，我想问一个鱼该issue不相关的问题，但是我找不到地方问了。就是如果多个第三方库都初始化自己的MMKV，这种情况下应该如何保证MMKV仅被初始化了一次？
> 
> 多次初始化也没关系吧？我没看过源码，但是按理说同一个应用顶多只会生效一次。你是遇到什么业务场景了吗

![Image](https://github.com/user-attachments/assets/a4848d9d-ce76-4c04-aeb8-789a776df97a)

这个是之前 [lingol](https://github.com/lingol) 的回答

**Comment by Allen-ZXJ** [comment]
> > > > https://www.google.com/search?q=pixel+6+pro+unsatisfied+link+error&newwindow=1&sca_esv=360d606574466e04&sxsrf=ADLYWIICIANY8r6x6wNiFOIiJzfuZGnWMw%3A1733488472240&ei=WO9SZ7mwDsvf1e8PhLjFyQg&ved=0ahUKEwi5vPDkk5OKAxXLb_UHHQRcMYkQ4dUDCA8&uact=5&oq=pixel+6+pro+unsatisfied+link+error&gs_lp=Egxnd3Mtd2l6LXNlcnAiInBpeGVsIDYgcHJvIHVuc2F0aXNmaWVkIGxpbmsgZXJyb3IyBxAhGKABGAoyBxAhGKABGAoyBxAhGKABGApI2oECUPAMWML_AXABeAGQAQCYAW-gAZsMqgEEMTguMbgBA8gBAPgBAZgCFKACzgzCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICChAAGIAEGEMYigXCAg0QLhiABBhDGOUEGIoFwgIOEC4YgAQYkQIY5QQYigXCAgsQABiABBiRAhiKBcICBRAAGIAEwgIREAAYgAQYkQIYsQMYgwEYigXCAh0QLhiABBiRAhjlBBiKBRiXBRjcBBjeBBjgBNgBAcICCxAAGIAEGIYDGIoFwgIGEAAYFhgewgIIEAAYgAQYogTCAggQABgWGAoYHsICBRAhGKABwgIFECEYqwKYAwCIBgGQBgq6BgYIARABGBSSBwQxOS4xoAeXbQ&sclient=gws-wiz-serp
> > > 
> > > 
> > > 你好，我想问一个鱼该issue不相关的问题，但是我找不到地方问了。就是如果多个第三方库都初始化自己的MMKV，这种情况下应该如何保证MMKV仅被初始化了一次？
> > 
> > 
> > 多次初始化也没关系吧？我没看过源码，但是按理说同一个应用顶多只会生效一次。你是遇到什么业务场景了吗
> 
> ![Image](https://github.com/user-attachments/assets/a4848d9d-ce76-4c04-aeb8-789a776df97a)
> 
> 这个是之前 [lingol](https://github.com/lingol) 的回答

 多初始化几次也没关系的。 所以你忽略其他库对MMKV的引入，只保证你自己的代码只初始化一次就行。 你写个测试用例就知道了，不影响功能。

**Comment by kapaseker** [comment]
> > > > > https://www.google.com/search?q=pixel+6+pro+unsatisfied+link+error&newwindow=1&sca_esv=360d606574466e04&sxsrf=ADLYWIICIANY8r6x6wNiFOIiJzfuZGnWMw%3A1733488472240&ei=WO9SZ7mwDsvf1e8PhLjFyQg&ved=0ahUKEwi5vPDkk5OKAxXLb_UHHQRcMYkQ4dUDCA8&uact=5&oq=pixel+6+pro+unsatisfied+link+error&gs_lp=Egxnd3Mtd2l6LXNlcnAiInBpeGVsIDYgcHJvIHVuc2F0aXNmaWVkIGxpbmsgZXJyb3IyBxAhGKABGAoyBxAhGKABGAoyBxAhGKABGApI2oECUPAMWML_AXABeAGQAQCYAW-gAZsMqgEEMTguMbgBA8gBAPgBAZgCFKACzgzCAgoQABiwAxjWBBhHwgINEAAYgAQYsAMYQxiKBcICChAAGIAEGEMYigXCAg0QLhiABBhDGOUEGIoFwgIOEC4YgAQYkQIY5QQYigXCAgsQABiABBiRAhiKBcICBRAAGIAEwgIREAAYgAQYkQIYsQMYgwEYigXCAh0QLhiABBiRAhjlBBiKBRiXBRjcBBjeBBjgBNgBAcICCxAAGIAEGIYDGIoFwgIGEAAYFhgewgIIEAAYgAQYogTCAggQABgWGAoYHsICBRAhGKABwgIFECEYqwKYAwCIBgGQBgq6BgYIARABGBSSBwQxOS4xoAeXbQ&sclient=gws-wiz-serp
> > > > 
> > > > 
> > > > 你好，我想问一个鱼该issue不相关的问题，但是我找不到地方问了。就是如果多个第三方库都初始化自己的MMKV，这种情况下应该如何保证MMKV仅被初始化了一次？
> > > 
> > > 
> > > 多次初始化也没关系吧？我没看过源码，但是按理说同一个应用顶多只会生效一次。你是遇到什么业务场景了吗
> > 
> > 
> > ![Image](https://github.com/user-attachments/assets/a4848d9d-ce76-4c04-aeb8-789a776df97a)
> > 这个是之前 [lingol](https://github.com/lingol) 的回答
> 
> 多初始化几次也没关系的。 所以你忽略其他库对MMKV的引入，只保证你自己的代码只初始化一次就行。 你写个测试用例就知道了，不影响功能。

如果不更改rootDir，逻辑上是正确的，但是一旦有人需要更改rootDir，最后初始化的那个就会更改掉所有的rootDir。
我在想，既然MMKV可以通过类似`mmkvWithID`的方法创建新的MMKV，为什么这个地方不自定义每个MMKV自己的rootDir呢？

**Comment by Allen-ZXJ** [comment]
你遇到这种情况了吗？ 你应该去对应的库提issue

**Comment by kapaseker** [comment]
> 你遇到这种情况了吗？ 你应该去对应的库提issue

没有，我只是在想这个问题。
如果作者说的是对的，也就是MMKV只能初始化一次，那么如何在多Module或者多SDK的情况下保证MMKV初始化的正确性？

**Comment by Allen-ZXJ** [comment]
多module的话，可控性也是属于自己的，限制只初始化一次就行。 多SDK的话，如果真出现了这种情况，那就建议提issue，让对应的sdk留一个公开字段去判断是否初始化过【一般sdk不会这么设计（强调解耦），如果真有就让作者提供字段去判断或者设置】

**Comment by Allen-ZXJ** [comment]
> > 你遇到这种情况了吗？ 你应该去对应的库提issue
> 
> 没有，我只是在想这个问题。 如果作者说的是对的，也就是MMKV只能初始化一次，那么如何在多Module或者多SDK的情况下保证MMKV初始化的正确性？

多module的话，可控性也是属于自己的，限制只初始化一次就行。 多SDK的话，如果真出现了这种情况，那就建议提issue，让对应的sdk留一个公开字段去判断是否初始化过【一般sdk不会这么设计（强调解耦），如果真有就让作者提供字段去判断或者设置】

**Comment by lingol** [comment]
@Allen-ZXJ @kapaseker Wait for the next big release with [NameSpace](https://github.com/Tencent/MMKV/releases/tag/v2.0.2) feature, it will fix exactly problems like these.

**Comment by kapaseker** [comment]
> [@Allen-ZXJ](https://github.com/Allen-ZXJ) [@kapaseker](https://github.com/kapaseker) Wait for the next big release with [NameSpace](https://github.com/Tencent/MMKV/releases/tag/v2.0.2) feature, it will fix exactly problems like these.

Looking forward to the next big release.

**Comment by lingol** [comment]
The NameSpace feature is released with [v2.1.0](https://github.com/Tencent/MMKV/releases/tag/v2.1.0). @kapaseker @Allen-ZXJ

**Comment by kapaseker** [comment]
> The NameSpace feature is released with [v2.1.0](https://github.com/Tencent/MMKV/releases/tag/v2.1.0). [@kapaseker](https://github.com/kapaseker) [@Allen-ZXJ](https://github.com/Allen-ZXJ)

Thanks
