### ISSUE TITLE
ios swift语言开发组件化项目包含MMKV，组件本地调试正常，发布到私有仓库报错

### ISSUE THREAD

**Issue by czeras** [Tencent/MMKV#1453]
## Note:
swift 语言创建的私有组件化仓库，本地运行没问题，在发布到私有仓库时报错：
The Swift pod `NativeImChatSwiftModule` depends upon `MMKV`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

本地podspec大概如下：
Pod::Spec.new do |s|
  s.name             = 'NativeImChatSwiftModule'
  s.version          = '0.1.0.16'
  s.summary          = 'A short description of NativeImChatSwiftModule.'
  s.description      = <<-DESC
TODO: Add long description of the pod here.
                       DESC

  s.ios.deployment_target = '12.0'
  s.homepage         = 'http://121.40.69.36/appModule/iOS/NativeImChatSwiftModule'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'wangcm' => 'custom_mail@163.com' }
  s.source           = { :git => 'http://121.40.69.36/appModule/iOS/NativeImChatSwiftModule.git', :tag => s.version.to_s }

  s.static_framework = true
  s.swift_version = '5.0'
  s.pod_target_xcconfig = { 
    'VALID_ARCHS' => 'x86_64 armv7 arm64',
    'DEFINES_MODULE' => 'YES' 
  }
  
  s.source_files = 'NativeImChatSwiftModule/Classes/**/*'

  s.resource_bundles = {
    'NativeImChatSwiftModule' => ['NativeImChatSwiftModule/Assets/*']
  }

  s.dependency 'MMKV'
end

### The language of MMKV
> swift

### The version of MMKV
> v2.0.0

### The platform of MMKV
> iOS

### The installation of MMKV

> Cocoapods

截图如下：
<img width="1866" alt="截屏2024-12-07 21 44 41" src="https://github.com/user-attachments/assets/093aa8ce-0bea-49b1-b795-eac5c22905c7">
<img width="1863" alt="截屏2024-12-07 22 07 29" src="https://github.com/user-attachments/assets/69e601dd-9ae6-44f3-af35-cc1257dff56c">

**Comment by lingol** [comment]
I'm not familiar with this problem. You should try google about it first.

**Comment by czeras** [comment]
问题已解决，本地推送到pod仓库时出错,以下是我的发布脚本，把 --use-libraries 参数注释掉就可以了

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
cd "$(dirname $0)"

echo -e "输入 git commit 内容 :"
read git_commit_des

echo -e "\n ****** begin ****** \n"

echo -e "\n ---- 获取podspec文件 begin ---- \n"

# 获取到的文件路径
file_path=""
file_name=""
# 文件后缀名
file_extension="podspec"
# 文件夹路径，pwd表示当前文件夹
directory="$(pwd)"

# 参数1: 路径；参数2: 文件后缀名
function getFileAtDirectory(){
    for element in `ls $1`
    do  
        dir_or_file=$1"/"$element
        # echo "$dir_or_file"
        if [ -d $dir_or_file ]
        then 
            getFileAtDirectory $dir_or_file
        else
            file_extension=${dir_or_file##*.}
            if [[ $file_extension == $2 ]]; then
            	echo "$dir_or_file 是 $2 文件"
            	file_path=$dir_or_file
            	file_name=$element
            fi
        fi  
    done
}
getFileAtDirectory $directory $file_extension

echo -e "\n -------------"
echo -e "\n file_path: ${file_path}"
echo -e "\n file_name: ${file_name}"

echo -e "\n ---- 获取podspec文件 end ---- \n"



echo -e "\n ---- 读取podspec文件内容 begin ---- \n"

# 定义pod文件名称
pod_file_name=${file_name}
# 查找 podspec 的版本
search_str="s.version"

# 读取podspec的版本
podspec_version=""

#定义了要读取文件的路径
my_file="${pod_file_name}" 
while read my_line
do
#输出读到的每一行的结果
# echo $my_line

	# 查找到包含的内容，正则表达式获取以 ${search_str} 开头的内容
	result=$(echo ${my_line} | grep "^${search_str}")
	if [[ "$result" != "" ]]
	then
   		echo -e "\n ${my_line} 包含 ${search_str}"

   		# 分割字符串，是变量名称，不是变量的值; 前面的空格表示分割的字符，后面的空格不可省略
		array=(${result// / })  
		# 数组长度
		count=${#array[@]}
		# 获取最后一个元素内容
		version=${array[count - 1]}
		# 去掉 '
		version=${version//\'/}

		podspec_version=$version
	#else
   		# echo "\n ${my_line} 不包含 ${search_str}"
	fi

done < $my_file

echo -e "\n -------------"
echo -e "\n podspec_version: ${podspec_version}"

echo -e "\n ---- 读取podspec文件内容 end ---- \n"



pod_spec_name=${file_name}
pod_spec_version=${podspec_version}

echo -e "\n****** ${pod_spec_name} ${pod_spec_version} begin ****** \n"

echo -e "\n ------ 执行 git 本地提交代码操作 ------ \n"

echo "\n ------ 执行 git 打标签tag，并推送到远端 ------ \n"
branch=$(git ls-remote --tags |grep ${pod_spec_version})
if [ -n "$branch" ]; then
    echo -e "\n ======== 标签已存在！！！ ======== "
	echo -e "\n ======== 输入任意键回车退出 ======== \n"
	read end1111
	exit 0
fi


# git 操作
echo "git add ."
git add .
echo "git status"
git status
echo "git commit -m ${git_commit_des}"
git commit -m ${git_commit_des}

git pull
git push

# git推送到远端
echo "git tag ${pod_spec_version}"
git tag ${pod_spec_version}
echo "git push origin master --tags"
git push origin -f --tags

echo -e "\n ------ 执行 pod 发布 ------ \n"
# 

echo "pod repo push 私有仓库 ${pod_spec_name} --allow-warnings --use-libraries --verbose"
pod repo push 私有仓库 ${pod_spec_name} --skip-import-validation --allow-warnings --verbose  # --use-libraries


if [ $? -ne 0 ]; then
	git tag -d ${pod_spec_version}
	git push origin :refs/tags/${pod_spec_version}
    echo -e  "\n ======== 发布失败！！！ ======== \n"
	echo -e "\n ======== 输入任意键回车退出 ======== \n"
	read end
	exit 0
else
	echo -e "\n****** ${pod_spec_name} ${pod_spec_version} end ****** \n"
	echo -e "\n ======== 发布成功！！！ ======== \n"
 
    function getUserName {
      na=`git config user.name`
      echo ${na/* /}
    }
    name=`getUserName`
	function getGitBranch {
      br=`git branch | grep "*"`
  	  echo ${br/* /}
    }
	branch=`getGitBranch`
	realPodName=$(echo $pod_spec_name | sed 's/.podspec//g')

curl -X POST -H "Content-Type: application/json" \
        -d "{\"msg_type\": \"post\",\"content\": {\"post\": {\"zh_cn\": {\"title\": \"${realPodName}\",\"content\": [[{\"tag\": \"text\",\"text\": \"版本号：\"},{\"tag\": \"text\",\"text\": \"${pod_spec_version}\"}],[{\"tag\": \"text\",\"text\": \"分支：\"},{\"tag\": \"text\",\"text\": \"${branch}\"}],[{\"tag\": \"text\",\"text\": \"发布人：\"},{\"tag\": \"text\",\"text\": \"${name}\"}],[{\"tag\": \"text\",\"text\": \"提交内容：\"},{\"tag\": \"text\",\"text\": \"${git_commit_des}\"}]]}}}}" \
  https://open.feishu.cn/open-apis/bot/v2/xxx
fi

**Comment by czeras** [comment]
问题已解决，本地推送到pod仓库时出错,以下是我的发布脚本，把 --use-libraries 参数注释掉就可以了
`#!/bin/bash -l

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
cd "$(dirname $0)"

echo -e "输入 git commit 内容 :"
read git_commit_des

echo -e "\n ****** begin ****** \n"

echo -e "\n ---- 获取podspec文件 begin ---- \n"

# 获取到的文件路径
file_path=""
file_name=""
# 文件后缀名
file_extension="podspec"
# 文件夹路径，pwd表示当前文件夹
directory="$(pwd)"

# 参数1: 路径；参数2: 文件后缀名
function getFileAtDirectory(){
    for element in `ls $1`
    do  
        dir_or_file=$1"/"$element
        # echo "$dir_or_file"
        if [ -d $dir_or_file ]
        then 
            getFileAtDirectory $dir_or_file
        else
            file_extension=${dir_or_file##*.}
            if [[ $file_extension == $2 ]]; then
            	echo "$dir_or_file 是 $2 文件"
            	file_path=$dir_or_file
            	file_name=$element
            fi
        fi  
    done
}
getFileAtDirectory $directory $file_extension

echo -e "\n -------------"
echo -e "\n file_path: ${file_path}"
echo -e "\n file_name: ${file_name}"

echo -e "\n ---- 获取podspec文件 end ---- \n"



echo -e "\n ---- 读取podspec文件内容 begin ---- \n"

# 定义pod文件名称
pod_file_name=${file_name}
# 查找 podspec 的版本
search_str="s.version"

# 读取podspec的版本
podspec_version=""

#定义了要读取文件的路径
my_file="${pod_file_name}" 
while read my_line
do
#输出读到的每一行的结果
# echo $my_line

	# 查找到包含的内容，正则表达式获取以 ${search_str} 开头的内容
	result=$(echo ${my_line} | grep "^${search_str}")
	if [[ "$result" != "" ]]
	then
   		echo -e "\n ${my_line} 包含 ${search_str}"

   		# 分割字符串，是变量名称，不是变量的值; 前面的空格表示分割的字符，后面的空格不可省略
		array=(${result// / })  
		# 数组长度
		count=${#array[@]}
		# 获取最后一个元素内容
		version=${array[count - 1]}
		# 去掉 '
		version=${version//\'/}

		podspec_version=$version
	#else
   		# echo "\n ${my_line} 不包含 ${search_str}"
	fi

done < $my_file

echo -e "\n -------------"
echo -e "\n podspec_version: ${podspec_version}"

echo -e "\n ---- 读取podspec文件内容 end ---- \n"



pod_spec_name=${file_name}
pod_spec_version=${podspec_version}

echo -e "\n****** ${pod_spec_name} ${pod_spec_version} begin ****** \n"

echo -e "\n ------ 执行 git 本地提交代码操作 ------ \n"

echo "\n ------ 执行 git 打标签tag，并推送到远端 ------ \n"
branch=$(git ls-remote --tags |grep ${pod_spec_version})
if [ -n "$branch" ]; then
    echo -e "\n ======== 标签已存在！！！ ======== "
	echo -e "\n ======== 输入任意键回车退出 ======== \n"
	read end1111
	exit 0
fi


# git 操作
echo "git add ."
git add .
echo "git status"
git status
echo "git commit -m ${git_commit_des}"
git commit -m ${git_commit_des}

git pull
git push

# git推送到远端
echo "git tag ${pod_spec_version}"
git tag ${pod_spec_version}
echo "git push origin master --tags"
git push origin -f --tags

echo -e "\n ------ 执行 pod 发布 ------ \n"
# 

echo "pod repo push 私有仓库 ${pod_spec_name} --allow-warnings --use-libraries --verbose"
pod repo push 私有仓库 ${pod_spec_name} --skip-import-validation --allow-warnings --verbose  # --use-libraries


if [ $? -ne 0 ]; then
	git tag -d ${pod_spec_version}
	git push origin :refs/tags/${pod_spec_version}
    echo -e  "\n ======== 发布失败！！！ ======== \n"
	echo -e "\n ======== 输入任意键回车退出 ======== \n"
	read end
	exit 0
else
	echo -e "\n****** ${pod_spec_name} ${pod_spec_version} end ****** \n"
	echo -e "\n ======== 发布成功！！！ ======== \n"
 
    function getUserName {
      na=`git config user.name`
      echo ${na/* /}
    }
    name=`getUserName`
	function getGitBranch {
      br=`git branch | grep "*"`
  	  echo ${br/* /}
    }
	branch=`getGitBranch`
	realPodName=$(echo $pod_spec_name | sed 's/.podspec//g')

curl -X POST -H "Content-Type: application/json" \
        -d "{\"msg_type\": \"post\",\"content\": {\"post\": {\"zh_cn\": {\"title\": \"${realPodName}\",\"content\": [[{\"tag\": \"text\",\"text\": \"版本号：\"},{\"tag\": \"text\",\"text\": \"${pod_spec_version}\"}],[{\"tag\": \"text\",\"text\": \"分支：\"},{\"tag\": \"text\",\"text\": \"${branch}\"}],[{\"tag\": \"text\",\"text\": \"发布人：\"},{\"tag\": \"text\",\"text\": \"${name}\"}],[{\"tag\": \"text\",\"text\": \"提交内容：\"},{\"tag\": \"text\",\"text\": \"${git_commit_des}\"}]]}}}}" \
  https://open.feishu.cn/open-apis/bot/v2/xxx
fi`

**Comment by lingol** [comment]
How do you solve this issue?
