### ISSUE TITLE
鸿蒙 MMKV.initialize() 报 Error message:Cannot read property initialize of undefined

### ISSUE THREAD

**Issue by xlg** [Tencent/MMKV#1456]
1、"@tencent/mmkv": "^2.0.1"

2、onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): void {
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onCreate');
    MMKV.initialize(this.context.getApplicationContext(), MMKVLogLevel.LevelInfo)
  }
  
3、
Error name:TypeError
Error message:Cannot read property initialize of undefined
Stacktrace:
    at initializeWithPath (oh_modules/.ohpm/@tencent+mmkv@2.0.1/oh_modules/@tencent/mmkv/src/main/ets/utils/MMKV.ets:86:26)
    at initialize (oh_modules/.ohpm/@tencent+mmkv@2.0.1/oh_modules/@tencent/mmkv/src/main/ets/utils/MMKV.ets:70:16)
    at onCreate (entry/src/main/ets/entryability/EntryAbility.ets:11:5)

**Comment by lingol** [comment]
It's a typically error due to failing to load the native library limmkv.so.

You check out Hilog/FaultLog and find out what went wrong.

**Comment by lingol** [comment]
Did you turn on obfuscation? Have you followed the temp solution here?

https://github.com/Tencent/MMKV/issues/1385#issuecomment-2428052006

**Comment by xlg** [comment]
我的步骤非常简单，新建了一个空的工程 并引用"@tencent/mmkv": "^2.0.1"，在onCreate里进行初始化MMKV.initialize(),然后运行到模拟器上就报错了。混淆应该是没有开启的 "buildOptionSet": [
    {
      "name": "release",
      "arkOptions": {
        "obfuscation": {
          "ruleOptions": {
            "enable": false,
            "files": [
              "./obfuscation-rules.txt"
            ]
          }
        }
      }
    },
  ],
  
  {
  "modelVersion": "5.0.0",
  "description": "Please describe the basic information.",
  "dependencies": {},
  "devDependencies": {
    "@tencent/mmkv": "^2.0.1",
//    "@ohos/hypium": "1.0.19",
//    "@ohos/hamock": "1.0.0"
  },
  "dynamicDependencies": {}
}
  所以现在就很奇怪，也不知道哪里引起的
![image](https://github.com/user-attachments/assets/98c3086f-3c7e-4b3d-a319-129eee0bc4f4)

**Comment by lingol** [comment]
Does your simulator have OHOS API level 12 or above? aka HarmonyOS NEXT.

**Comment by lingol** [comment]
One more thing, MMKV does not support x86 with 32-bit arch, only x86-64 is supported.

**Comment by xlg** [comment]
不好意思，是引用的放错位置，应该放置dependencies下，而不是devDependencies。
