### ISSUE TITLE
可以使用aar或者jar的形式引入吗

### ISSUE THREAD

**Issue by dyj11** [Tencent/MMKV#1459]
可以使用aar或者jar的形式引入吗？由于项目的lib资源过大，我想压缩项目的lib资源，通过android:extractNativeLibs="true"压缩so库之后，MMKV初始化会崩溃

**Comment by lingol** [comment]
I'm not familiar with the issue, you should try Google about it.

**Comment by yymjr** [comment]
you can download aar library(https://mvnrepository.com/artifact/com.tencent/mmkv/2.0.1)
