### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by zwyxtj** [Tencent/MMKV#1460]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> , Java

### The version of MMKV
v1.0.22  

### The platform of MMKV
> Android arm64-v8a

### The installation of MMKV

>Maven

### What's the issue?

dlopen failed: "/data/app/com.supershoppad-K3eWhyO480jHaaZNttq1uQ==/lib/arm64/libc++_shared.so" has bad ELF magic: 00000000

com.tencent.mmkv.MMKV.initialize(MMKV.java:83)

**Comment by lingol** [comment]
It looks like your app's libmmkv.so is broken. Check your apk.

**Comment by lingol** [comment]
One more thing, v1.0.22 is way too old, consider upgrading it regardless of this issue.

**Comment by yymjr** [comment]
libc++_shared.so?I think you maybe import a broken so by youself. You can use readelf command to check.
