### ISSUE TITLE
Suggestion: Update the wiki of Golang Tutorial.

### ISSUE THREAD

**Issue by catundercar** [Tencent/MMKV#1464]
In the Golang Tutorial wiki page, the install command is:
``` shell
cd POSIX/golang
cmake . -DCMAKE_INSTALL_PREFIX=.
make -j8 install
```
Suggestion:
``` shell
cd POSIX/golang
cmake . -DCMAKE_INSTALL_PREFIX=. -DCMAKE_BUILD_TYPE=Release
make -j8 install
```
Specifying `-DCMAKE_BUILD_TYPE=Release` will have a greater performance improvement (Prevent developers like me, who are not very familiar with compiler, from falling into pitfalls :sob:).

**Comment by lingol** [comment]
Noted.
