### ISSUE TITLE
Could you please support getting the value size for key?

### ISSUE THREAD

**Issue by alhah** [Tencent/MMKV#147]
### The language of MMKV

Java

### The version of MMKV

v1.0.14

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?
I want to track if there are large key-values stored in mmkv, so as title.

**Comment by lingol** [comment]
`int getValueSize(String key)`? That's a maybe.
Or, you can quit waiting and wrap your own kv storage class on top of MMKV. Then you can track each `insert` with value size.

**Comment by alhah** [comment]
Track insert is a good idea, but is not elegant enough, looking forward to official support.

**Comment by lingol** [comment]
Supported with [commit](https://github.com/Tencent/MMKV/commit/6d54cedd2149f5ad568de83fa72ef3d325bf0c50). Will come out on next release.

**Comment by lingol** [comment]
Released with [v1.0.16](https://github.com/Tencent/MMKV/releases/tag/v1.0.16).
