### ISSUE TITLE
#38573252 java.lang.StackOverflowError

### ISSUE THREAD

**Issue by zaijie1213** [Tencent/MMKV#148]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

java

### The version of MMKV

> e.g. v1.0.10
1.0.14

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

gradle 

### What's the issue?

> Post the outputs or screenshots for errors.
1 com.tencent.mmkv.MMKV.getMMKVWithID(Native Method)
2 com.tencent.mmkv.MMKV.a(MMKV.java:77)

> Explain what you want by example or code **in English**.

12-11 16:35:58.398 17305 17410 E MMKV : check crc [location_info] fail, crc32:382268228, m_crcDigest:3576436193
--
3712-11 16:35:58.399 17305 17410 I MMKV : loaded [location_info] with 0 values
3812-11 16:35:58.402 17305 17305 E AndroidRuntime: at com.tencent.mmkv.MMKV.getMMKVWithID(Native Method)
3912-11 16:35:58.402 17305 17305 E AndroidRuntime: at com.tencent.mmkv.MMKV.a(MMKV.java:77)

crc check fail ，crash

**Comment by lingol** [comment]
Duplicated with #143

**Comment by lingol** [comment]
Fixed with [v1.0.15](https://github.com/Tencent/MMKV/releases/tag/v1.0.15).
