### ISSUE TITLE
native crash with  libc.so

### ISSUE THREAD

**Issue by emile2013** [Tencent/MMKV#159]
### The language of MMKV

> Java

### The version of MMKV

> v1.0.15

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 

1 #00 pc 0004a988 /system/lib/libc.so (tgkill+12) [armeabi-v7a]
--
2 #01 pc 0004806b /system/lib/libc.so (pthread_kill+34) [armeabi-v7a]
3 #02 pc 00048069 /system/lib/libc.so (pthread_kill+32) [armeabi-v7a]
4 #03 pc 00048067 /system/lib/libc.so (pthread_kill+30) [armeabi-v7a]
5 #04 pc 00048063 /system/lib/libc.so (pthread_kill+26) [armeabi-v7a]
6 #05 pc 00048061 /system/lib/libc.so (pthread_kill+24) [armeabi-v7a]
7 #06 pc 0004805f /system/lib/libc.so (pthread_kill+22) [armeabi-v7a]
8 #07 pc 0004805b /system/lib/libc.so (pthread_kill+18) [armeabi-v7a]
9 #08 pc 00048059 /system/lib/libc.so (pthread_kill+16) [armeabi-v7a]
10 #09 pc 00048057 /system/lib/libc.so (pthread_kill+14) [armeabi-v7a]
11 #10 pc 00048055 /system/lib/libc.so (pthread_kill+12) [armeabi-v7a]
12 #11 pc 00048051 /system/lib/libc.so (pthread_kill+8) [armeabi-v7a]
13 #12 pc 0004804f /system/lib/libc.so (pthread_kill+6) [armeabi-v7a]
14 #13 pc 0004804d /system/lib/libc.so (pthread_kill+4) [armeabi-v7a]
15 #14 pc 0004804b /system/lib/libc.so (pthread_kill+2) [armeabi-v7a]
16 #15 pc 00048049 /system/lib/libc.so (pthread_kill+0) [armeabi-v7a]
17 #16 pc 00048047 /system/lib/libc.so (pthread_setspecific+54) [armeabi-v7a]
18 #17 pc 00048045 /system/lib/libc.so (pthread_setspecific+52) [armeabi-v7a]
19 #18 pc 00048043 /system/lib/libc.so (pthread_setspecific+50) [armeabi-v7a]
20 #19 pc 00048041 /system/lib/libc.so (pthread_setspecific+48) [armeabi-v7a]
21 #20 pc 0004803f /system/lib/libc.so (pthread_setspecific+46) [armeabi-v7a]
22 #21 pc 0004803d /system/lib/libc.so (pthread_setspecific+44) [armeabi-v7a]
23 #22 pc 0004803b /system/lib/libc.so (pthread_setspecific+42) [armeabi-v7a]
24 #23 pc 00048039 /system/lib/libc.so (pthread_setspecific+40) [armeabi-v7a]
25 #24 pc 00048037 /system/lib/libc.so (pthread_setspecific+38) [armeabi-v7a]
26 #25 pc 00048035 /system/lib/libc.so (pthread_setspecific+36) [armeabi-v7a]
27 #26 pc 00048033 /system/lib/libc.so (pthread_setspecific+34) [armeabi-v7a]
28 #27 pc 00048031 /system/lib/libc.so (pthread_setspecific+32) [armeabi-v7a]
29 #28 pc 0004802f /system/lib/libc.so (pthread_setspecific+30) [armeabi-v7a]
30 #29 pc 0004802d /system/lib/libc.so (pthread_setspecific+28) [armeabi-v7a]
31 #30 pc 0004802b /system/lib/libc.so (pthread_setspecific+26) [armeabi-v7a]
32 #31 pc 00048029 /system/lib/libc.so (pthread_setspecific+24) [armeabi-v7a]
33 #32 pc 00048027 /system/lib/libc.so (pthread_setspecific+22) [armeabi-v7a]
34 #33 pc 00048025 /system/lib/libc.so (pthread_setspecific+20) [armeabi-v7a]
35 #34 pc 00048023 /system/lib/libc.so (pthread_setspecific+18) [armeabi-v7a]
36 #35 pc 00048021 /system/lib/libc.so (pthread_setspecific+16) [armeabi-v7a]
37 #36 pc 0004801f /system/lib/libc.so (pthread_setspecific+14) [armeabi-v7a]
38 #37 pc 0004801d /system/lib/libc.so (pthread_setspecific+12) [armeabi-v7a]
39 #38 pc 0004801b /system/lib/libc.so (pthread_setspecific+10) [armeabi-v7a]
40 #39 pc 00048019 /system/lib/libc.so (pthread_setspecific+8) [armeabi-v7a]
41 #40 pc 00048017 /system/lib/libc.so (pthread_setspecific+6) [armeabi-v7a]
42 #41 pc 00048015 /system/lib/libc.so (pthread_setspecific+4) [armeabi-v7a]
43 #42 pc 00048013 /system/lib/libc.so (pthread_setspecific+2) [armeabi-v7a]
44 #43 pc 00048011 /system/lib/libc.so (pthread_setspecific+0) [armeabi-v7a]
45 #44 pc 0004800f /system/lib/libc.so (pthread_getspecific+74) [armeabi-v7a]
46 #45 pc 0004800d /system/lib/libc.so (pthread_getspecific+72) [armeabi-v7a]
47 #46 pc 0004800b /system/lib/libc.so (pthread_getspecific+70) [armeabi-v7a]
48 #47 pc 00048009 /system/lib/libc.so (pthread_getspecific+68) [armeabi-v7a]
49 #48 pc 00048007 /system/lib/libc.so (pthread_getspecific+66) [armeabi-v7a]
50 #49 pc 00048005 /system/lib/libc.so (pthread_getspecific+64) [armeabi-v7a]
51 #50 pc 00048003 /system/lib/libc.so (pthread_getspecific+62) [armeabi-v7a]
52 #51 pc 00048001 /system/lib/libc.so (pthread_getspecific+60) [armeabi-v7a]
53 #52 pc 00047fff /system/lib/libc.so (pthread_getspecific+58) [armeabi-v7a]
54 #53 pc 00047ffd /system/lib/libc.so (pthread_getspecific+56) [armeabi-v7a]
55 #54 pc 00047ffb /system/lib/libc.so (pthread_getspecific+54) [armeabi-v7a]
56 #55 pc 00047ff9 /system/lib/libc.so (pthread_getspecific+52) [armeabi-v7a]
57 #56 pc 00047ff7 /system/lib/libc.so (pthread_getspecific+50) [armeabi-v7a]
58 #57 pc 00047ff5 /system/lib/libc.so (pthread_getspecific+48) [armeabi-v7a]
59 #58 pc 00047ff3 /system/lib/libc.so (pthread_getspecific+46) [armeabi-v7a]
60 #59 pc 00047ff1 /system/lib/libc.so (pthread_getspecific+44) [armeabi-v7a]
61 #60 pc 00047fef /system/lib/libc.so (pthread_getspecific+42) [armeabi-v7a]
62 #61 pc 00047fed /system/lib/libc.so (pthread_getspecific+40) [armeabi-v7a]
63 #62 pc 00047feb /system/lib/libc.so (pthread_getspecific+38) [armeabi-v7a]
64 #63 pc 00047fe9 /system/lib/libc.so (pthread_getspecific+36) [armeabi-v7a]
65 #64 pc 00047fe7 /system/lib/libc.so (pthread_getspecific+34) [armeabi-v7a]
66 #65 pc 00047fe5 /system/lib/libc.so (pthread_getspecific+32) [armeabi-v7a]
67 #66 pc 00047fe3 /system/lib/libc.so (pthread_getspecific+30) [armeabi-v7a]
68 #67 pc 00047fe1 /system/lib/libc.so (pthread_getspecific+28) [armeabi-v7a]
69 #68 pc 00047fdf /system/lib/libc.so (pthread_getspecific+26) [armeabi-v7a]
70 #69 pc 00047fdd /system/lib/libc.so (pthread_getspecific+24) [armeabi-v7a]
71 #70 pc 00047fdb /system/lib/libc.so (pthread_getspecific+22) [armeabi-v7a]
72 #71 pc 00047fd9 /system/lib/libc.so (pthread_getspecific+20) [armeabi-v7a]
73 #72 pc 00047fd7 /system/lib/libc.s

> Explain what you want by example or code **in English**.
# most crash in android  7.1 or 7.0 devices

**Comment by workofgao** [comment]
@emile2013  请问您最后排查到问题了吗
