### ISSUE TITLE
protection

### ISSUE THREAD

**Issue by xiongxiongjiang** [Tencent/MMKV#162]
### The language of MMKV
swift

### The version of MMKV
v1.0.10

### The platform of MMKV
 iOS

### The installation of MMKV
 Cocoapods

### What's the issue?

code:
```
let model = mmkv.object(of: PathContentModel.self as! AnyClass, forKey: presetDownloaded)
```
lldb reports:
 [/var/mobile/Containers/Data/Application/3CB2E8F5-A4EE-41FE-A247-1CDC9EF8C819/Documents/mmkv/xxxxxxx.crc] is NSFileProtectionCompleteUntilFirstUserAuthentication

**Comment by lingol** [comment]
If you think the default file protection doesn't suit your App well, you can change the root folder's (aka, `Documents/mmkv`) protection key. Once and for all.

**Comment by lingol** [comment]
Close due to inactive.
