### ISSUE TITLE
iOS 9.3.1  真机release  12点多的系统不会出现

### ISSUE THREAD

**Issue by tangmengze** [Tencent/MMKV#167]
dyld: warning, LC_RPATH @executable_path/Frameworks in /var/containers/Bundle/Application/A283E789-C6E3-4553-8271-4ED6D9552663/x x x x.app/xxxx being ignored in restricted program because of @executable_path
dyld: Library not loaded: @rpath/MMKV.framework/MMKV
  Referenced from: /var/containers/Bundle/Application/A283E789-C6E3-4553-8271-4ED6D9552663/xxxx.app/xxx
  Reason: image not found

**Comment by lingol** [comment]
A little Google leads [here](https://forums.developer.apple.com/thread/99716) and [here](https://stackoverflow.com/questions/26104975/dyld-library-not-loaded-rpath-libswiftcore-dylib-image-not-found/51649534#51649534). Try those solutions.
