### ISSUE TITLE
what to do with Compatibility of  getAll() on  Android?

### ISSUE THREAD

**Issue by easternHong** [Tencent/MMKV#168]
### The language of MMKV
> Java, or Kotlin

### The version of MMKV
> v1.0.15

### The platform of MMKV
>Android

### The installation of MMKV

>AAR 

### What's the issue?
my apps embed several third sdks, and some sp **use getAll()** ，but  mmkv#getAll() **is not recommended**.

what can i do with this?

help me guys!!!

**Comment by lingol** [comment]
Last time I check, there's a specific log about this:

```
"use allKeys() instead, getAll() not implement because type-erasure inside mmkv"
```

Try that instruction.

**Comment by vincentssn** [comment]
I meet the same problem. But there are some third-part sdk in my project that i can't modify its code. While these third-part sdk use getAll()---not only use the keys but also use the values of the map. So how to do with Compatibility of getAll() ?

**Comment by vincentssn** [comment]
I know type-erasure means. But are there some approach to know the value I get is valid? Then I can  try every type for one key and build the map.

**Comment by vincentssn** [comment]
And if any suggestions for Compatibility of getAll() in Android?  making a white-list to avoid the third-part sdk use mmkv?

**Comment by shenzhen2017** [comment]
解决方案：https://juejin.cn/post/6939473558259105805/

**Comment by lingol** [comment]
> 解决方案：https://juejin.cn/post/6939473558259105805/

For those who really worry about getAll(), that's one way to do it. It will cost you time & disk space for encoding & decoding though. And it will lose some superset features of SP, such as Parcel objects.
Ust it at your own risk.
