### ISSUE TITLE
System.loadLibrary("mmkv") crash in same devices

### ISSUE THREAD

**Issue by emile2013** [Tencent/MMKV#169]
### The language of MMKV

> Java

### The version of MMKV

> v1.0.15

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
       couldn't find "libmmkv.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
	at java.lang.System.loadLibrary(System.java:1660)
	at com.tencent.mmkv.MMKV.&lt;clinit&gt;(SourceFile:52)
	at com.tencent.mmkv.MMKV.a(SourceFile:58)

recommend  action like relinker

**Comment by emile2013** [comment]
i mean not include relinker lib, but action like it .

**Comment by lingol** [comment]
Maybe. But why do something yourself while others already provide for free?

**Comment by lingol** [comment]
As others has suggested, we has supported using custom library loader, which shipped with [v1.0.17](https://github.com/Tencent/MMKV/releases/tag/v1.0.17).
And I personally still don't think embedding what ReLinker's doing inside MMKV is a good idea. Better keep it simple & stupy.
