### ISSUE TITLE
您好，我们的App想要使用MMKV库，但是比较担心Android版本上MMKV的稳定性，请问Android版微信有使用MMKV么？如果有使用我们就放心了

### ISSUE THREAD

**Issue by mJackSparrow** [Tencent/MMKV#171]
### The language of MMKV

> e.g. Java

### The version of MMKV

> e.g. v1.0.15

### The platform of MMKV

> e.g. Android

### The installation of MMKV

> e.g. Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
Yes, we do use it inside WeChat. Checkout the latest beta version (aka, 7.0 beta) and look for yourself.

**Comment by lingol** [comment]
And more Apps from WeChat team already ship with MMKV, like 企业微信 & 订阅号助手.

**Comment by mJackSparrow** [comment]
3Q very much~
