### ISSUE TITLE
Android平台上关于升级方式的问题

### ISSUE THREAD

**Issue by mJackSparrow** [Tencent/MMKV#174]
您好，我们已经准备全面使用MMKV了，之前我们是使用ContentProvider+SharePreference方式来解决跨进程存储键值的问题的，后来碰到了性能问题，现在想要迁移到MMKV上了，我们现在有两个点还没有考虑清楚：
    1、将SharePreference全部替换为MMKV方式，还是只在有性能问题的节点上使用MMKV？
    2、在App启动时直接进行一次全面的升级，还是在使用MMKV时进行透明的升级？
    在微信或其他使用MMKV的App上是采用什么样的做法呢？非常感谢~

**Comment by lingol** [comment]
1. You can start with some speed sensitive sp, try out a bit, gather some confidence. And then you can push it further with more sp, even every sp.
2. Do it at once is better. Make it relative with specific version.
