### ISSUE TITLE
mmkv 学习

### ISSUE THREAD

**Issue by jacksPeak** [Tencent/MMKV#181]
您好，看了 Android mmkv 源码发现核心逻辑都在 native 层，可是我个人对于 native 方面知识完全小白就认识一点基础语法。很想研究明白 mmkv native 层的原理但又没有方向，请问我除了该学习 c++ 语言之外还应该掌握什么呢？可以推荐一下相关教材嘛？谢谢！

**Comment by lingol** [comment]
Looks like you are interested in JNI development. Well I suggest starting with Linux/Unix development, especially on `file/memory/inter-process communication`. (A little hint, avoid the `fork` stuff, it's a waste of time.)
At the same time you should get your hands on C++ study, especially with the `C++11/17` standard.

**Comment by caixingke** [comment]
对于安卓开发来说, 无论是应用层还是框架层, linux内核是真得需要了解的, 否则对framework难于理解. 
我曾经想研究framework, 发现卡住的地方一直都是linux内核. 
了解linux内核花了我的大量时间, 但接下来安卓的framework的研究, 就没有花多少时间了.

**Comment by lingol** [comment]
`Advanced Programming in the UNIX Environment` would be a good start. As for CPP, it's complicated, check other answers online, like this one on [reddit](https://www.reddit.com/r/cpp/comments/5pqv8o/whats_the_best_c_beginners_book/).

**Comment by jacksPeak** [comment]
Thank you for your recommendation. Looking forward to being a programmer like you.
