### ISSUE TITLE
/data partition suddenly became read-only 

### ISSUE THREAD

**Issue by alhah** [Tencent/MMKV#184]
### The language of MMKV

Java

### The version of MMKV

v1.0.14

### The platform of MMKV

Android

### The installation of MMKV

Git clone

### What's the issue?
21:01:54.576 everything is OK, 21:01:54.657 /data partition suddenly became read-only, have you ever seen this kind of errors before?

```
01-06 21:01:54.576 1231 1231 I MMKV : loading [im_resource_config] with 2018 size in total, file size is 4096
01-06 21:01:54.576 1231 1231 I MMKV : loading [im_resource_config] with crc 1787799328 sequence 2
01-06 21:01:54.576 1231 1231 I MMKV : loaded [im_resource_config] with 1 values
01-06 21:01:54.657 1231 1231 E MMKV : fail to open:/data/user/0/com.smile.gifmaker/files/mmkv/payment.crc, Read-only file system
01-06 21:01:54.657 1231 1231 E MMKV : fail to lock fd=-1, ret=-1, error:Bad file descriptor
01-06 21:01:54.657 1231 1231 F libc : MMKVMetaInfo.hpp:39: void MMKVMetaInfo::read(const void *): assertion "ptr" failed
01-06 21:01:54.669 1231 1231 E CrashReport-Native: Failed to open file /data/user/0/com.smile.gifmaker/app_bugly/tomb_1546779714657.txt: Read-only file system
```

**Comment by lingol** [comment]
Are you getting this log from online user or in your development device?

**Comment by alhah** [comment]
Online user

**Comment by lingol** [comment]
I have ask around and none has seen something like that before. Maybe it's a bug in os?

**Comment by alhah** [comment]
We have met 13 till now, the device model and os version are different. I thought wechat have met this before.
![image](https://user-images.githubusercontent.com/12094621/50765986-a39d8980-12b2-11e9-8f4a-c662b5b1388c.png)

**Comment by lingol** [comment]
Nan, we don't get such errors.

**Comment by lingol** [comment]
Will it possibly be some service or 3rd app that revoke your app's access permission of disk?

**Comment by lingol** [comment]
One more thing, we have added checks & protection from read-only filesystem on `dev` branch. Check it out and give a try.

**Comment by alhah** [comment]
Thank you, I will try it.
