### ISSUE TITLE
Android source code question

### ISSUE THREAD

**Issue by zuowenpin** [Tencent/MMKV#187]
I have read android source code recently, the interprocess file lock is based on crc file, and crc file is created when mmkv is instantiated, so if multiple mmkv objects are created in different processes at the same time, is there any problem with this case~  Thanks.

**Comment by lingol** [comment]
There shall be no problems. Multi-process calling `open()` on the same path will not result in two files. You still get the same file. And the same lock on it.

**Comment by lingol** [comment]
Oh I see. It might happen, though very rare, for process A will not zero-file crc file if it's size is less than `DEFAULT_MMAP_SIZE`, aka already initialized. But if A's calling `fstat` to get filesize of crc file just before B's zero-fill & write-data logic, then shit happens.
A file-lock on the fd returned by `open` should do the job.  Will fix later.

**Comment by zuowenpin** [comment]
I have a little worry about the resource consumption of this library. To replace system shared preference with mmkv,  one file handle and shared mmap will be added, do you has any consideration in this respect? Thanks.

**Comment by lingol** [comment]
> I have a little worry about the resource consumption of this library. To replace system shared preference with mmkv, one file handle and shared mmap will be added, do you have any consideration in this respect? Thanks.

Generally MMKV should be long-living storage, for the sake of efficiency. If it not true on some of your use case, just call `close()` when you are done with it. And nothing will be wasted.

**Comment by lingol** [comment]
Fixed with [commit](https://github.com/Tencent/MMKV/commit/de8b32efa3b195598045a3d846d57b28f67e2e24).

**Comment by lingol** [comment]
Shipped with [v1.0.17](https://github.com/Tencent/MMKV/releases/tag/v1.0.17).
