### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference  com.tencent.mmkv.MMKV.initialize(MMKV.java:54)

### ISSUE THREAD

**Issue by wanchunyang** [Tencent/MMKV#189]
### The language of MMKV
java and kotlin

### The version of MMKV

v1.0.13

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?
java.lang.RuntimeException:Unable to create application com.kanshu.ksgb.fastread.doudou.App: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4536)
 ......
 Caused by:
 java.lang.NullPointerException:Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
 com.tencent.mmkv.MMKV.initialize(MMKV.java:54)

**Comment by wanchunyang** [comment]
![default](https://user-images.githubusercontent.com/11011286/50946664-6d8c1f80-14d5-11e9-9adc-16762b906248.png)

**Comment by lingol** [comment]
Try v1.0.16. And pass your mmkv folder path as `String` instead of `Context` to `MMKV.initialize()`
