### ISSUE TITLE
iOS ENABLE_MMKV_LOG 定义

### ISSUE THREAD

**Issue by SuiFeng** [Tencent/MMKV#191]
### The language of MMKV

> Objective-C

### The version of MMKV

> v1.0.16

### The platform of MMKV

> ios

### The installation of MMKV

> Cocoapods

### What's the issue?

建议将#define ENABLE_MMKV_LOG 改为如下的方式：

#if DEBUG
#define ENABLE_MMKV_LOG
#endif

在线上环境可以直接去掉LOG

**Comment by lingol** [comment]
Nan. Won't do it. Log is still useful even on release version.
However, an option to turn off logging should be provided.
Or even better, add something like `log re-route handler`.

**Comment by lingol** [comment]
Supported with [commit](https://github.com/Tencent/MMKV/commit/40a82767805e5934cef71d54800ded531be23cdc).

**Comment by lingol** [comment]
Shipped with [v1.0.17](https://github.com/Tencent/MMKV/releases/tag/v1.0.17).
