### ISSUE TITLE
native crash

### ISSUE THREAD

**Issue by zaijie1213** [Tencent/MMKV#194]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10
v 1.0.15

### The platform of MMKV

> e.g. iOS or Android

Android 

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

AAR

### What's the issue?

> Post the outputs or screenshots for errors.
> 

1 #00 pc 0000fab4 /system/lib/libc.so (__memcpy_base+164) [armeabi-v7a]
2 #01 pc 000093d1 /data/app/****-1/lib/arm/libmmkv.so [armeabi-v7a]
3 java:
4 com.tencent.mmkv.MMKV.a(MMKV.java:77)
> Explain what you want by example or code **in English**.

crash on some device,Android 5.1  Android 6.0

**Comment by lingol** [comment]
Please provide **symbolized** crash stack. And better with logcat output of MMKV>

**Comment by zaijie1213** [comment]
some crash logcat print "No space left on device"

001-13 09:52:28.141 7571 17228 I MMKV : loading [prefer] with 160 size in total, file size is 4096
101-13 09:52:28.141 7571 17228 I MMKV : loading [prefer] with crc 1621199383 sequence 2
201-13 09:52:28.141 7571 17228 I MMKV : loaded [prefer] with 6 values
301-13 09:52:29.281 7571 17228 E MMKV : fail to write fd[116], error:No space left on device
401-13 09:52:29.281 7571 17228 E MMKV : fail to truncate [/data/data/c**/files/mmkv/***.crc] to size 4096, No space left on device

**Comment by lingol** [comment]
Well, I believe that log has explain everything. What more do you expect from MMKV?

**Comment by zaijie1213** [comment]
No space left on device is one of the reasons cause crash ， We observed this crash on some devices with enough storage space，but the is no logcat log

**Comment by lingol** [comment]
Will you try v1.0.16? It's has fix some issues on read-only filesystem / space-not enough occasion.

**Comment by lingol** [comment]
Close due to inactivated.
