### ISSUE TITLE
Can you provide an option to turn off logging

### ISSUE THREAD

**Issue by BinBear** [Tencent/MMKV#195]
### The language of MMKV

> e.g. Objective-C

### The version of MMKV

> e.g. v1.0.16

### The platform of MMKV

> e.g. iOS

### The installation of MMKV

> e.g. Cocoapods

### What's the issue?

Can you provide an option to turn off logging

**Comment by lingol** [comment]
Duplicated with #191

**Comment by lingol** [comment]
Shipped with [v1.0.17](https://github.com/Tencent/MMKV/releases/tag/v1.0.17).
