### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by wanchunyang** [Tencent/MMKV#196]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin
java，kotlin

### The version of MMKV

v1.0.16

### The platform of MMKV
Android

### The installation of MMKV

Maven

### What's the issue?

1
java.lang.Runtime.loadLibrary(Runtime.java:373)
2
java.lang.System.loadLibrary(System.java:540)
3
com.tencent.mmkv.MMKV.<clinit>(MMKV.java:46)

![default](https://user-images.githubusercontent.com/11011286/51298499-bad13980-1a5f-11e9-8d13-349cfdbadede.png)

how to slove this issue?

**Comment by lingol** [comment]
Try rReLinker. #139

**Comment by wanchunyang** [comment]
@lingol Why not put it in mmkv as you have known this question？

**Comment by lingol** [comment]
Maybe.
