### ISSUE TITLE
1.0.16 native crash

### ISSUE THREAD

**Issue by coolegos** [Tencent/MMKV#205]
### The language of MMKV

> Kotlin

### The version of MMKV

> v1.0.16

### The platform of MMKV

> Android

### The installation of MMKV

> AAR Package

### What's the issue?

![image](https://user-images.githubusercontent.com/6348861/51722186-8a0c8800-208f-11e9-9a72-e4c40e0544bc.png)

**Comment by lingol** [comment]
PLEASE provide symbolized crash stack with detail info, logcat. Especially the call stack of native code.

**Comment by lingol** [comment]
Close due to inactive.

**Comment by coolegos** [comment]
升级到v1.0.17 以后目前没有发现问题。

**Comment by coolegos** [comment]
@lingol 有一个问题咨询下你呢。之前是在bugly 上发现了crash，按照你建议的直接升级了。现在尝试在bugly 上还原一下stack，我是直接`implementation 'com.tencent:mmkv:1.0.16'`依赖的mmkv。我本地clone 1.0.16版本的mmkv 生成的符号表对应不上`libmmkv.so`。是不是我只有通过源码编译的方式才能拿到正确的符号表呢？多谢了！

**Comment by lingol** [comment]
I'm afraid you have to ask bugly about this.

**Comment by coolegos** [comment]
谢谢，问了bugly 直接使用你们release 包不能拿到debug so。不过一般的使用都是直接implementation 'com.tencent:mmkv:1.0.16' 😢

**Comment by lingol** [comment]
That's right. You should use our pre-build packages in JCenter, which can be handle correctly by bugly.
https://bugly.qq.com/docs/utility-tools/plugin-gradle-bugly/
