### ISSUE TITLE
ios上pod install MMKV之后，使用智能指针(auto_ptr)会编译错误?

### ISSUE THREAD

**Issue by wzpziyi1** [Tencent/MMKV#212]
std::auto_ptr就编译报错是No template named 'auto_ptr' in namespace 'std'
发现MMKV使用的是shared_ptr，要使用的话就只能升级库的auto_ptr了么？

**Comment by lingol** [comment]
I don't think that has anything to do with MMKV. Check your project settings, Google yourself.

**Comment by lingol** [comment]
I guess you're using some `auto_ptr` on files out of MMKV, which is deprecated & removed on C++17. If that's true, you can:  
1. Change your workspace's setting to C++14 or below.
2. Change those `auto_ptr` to C++17 smart pointer.
