### ISSUE TITLE
MMKV storage problem

### ISSUE THREAD

**Issue by wanchunyang** [Tencent/MMKV#213]

**Comment by wanchunyang** [comment]
The first day of storage is successful, but the second day of acquisition is not.
mmkv version:1.0.17

**Comment by wanchunyang** [comment]
Android

**Comment by wanchunyang** [comment]
huawei p20

**Comment by lingol** [comment]
Provide catlog if possible. A reproducible demo project is most appreciated. guoling@tencent.com

**Comment by lingol** [comment]
Close due to inactive.
