### ISSUE TITLE
我用 MMKV 再引入  libcrypto.a,   定义的一些宏引入冲突.   MD5_Transform  MD5_Init  MD5_Final MD5_Update 

### ISSUE THREAD

**Issue by yyyear** [Tencent/MMKV#214]
###  引入冲突
> 在用 pod 同时引入  
pod 'MMKV'
pod 'QIYU_iOS_SDK'

报  `MD5_Transform`  `MD5_Init`  `MD5_Final MD5_Update` 等 宏方法重复定义   
重复定义文件 为 `libcrypto.a`  内的宏定义

临时的解决方法  是把 MMKV 打包成 Framwork 导入项目

希望解决一下 可以用 pod 导入

**Comment by lingol** [comment]
I have try using those two libs together in one demo project. And get no errors.  
Can you send me a reproducible demo project? guoling@tencent.com

**Comment by lingol** [comment]
I see. The `-all_load` flag in `Other Linker Flags` setting trigger this issue. Remove it and things works just right. Why did you add `-all_load`?  
For the time being, you get two options:  
1. Remove `-all_load` flag.
2. Linke MMKV as dynamic framework, as you has done.

MMKV will hide those symbols inside in next release.

**Comment by lingol** [comment]
Fixed with [commit](https://github.com/Tencent/MMKV/commit/93aef48e0ae6b3258b24e604c2f44799dee027fb).

**Comment by yyyear** [comment]
resolved  thanks

**Comment by lingol** [comment]
Released with [v1.0.18](https://github.com/Tencent/MMKV/releases/tag/v1.0.18).
