### ISSUE TITLE
详见报错信息

### ISSUE THREAD

**Issue by zsy78191** [Tencent/MMKV#215]
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 6738, TID: 1099231, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   MMKV                                0x00000001050d09d8 -[MMKV initWithMMapID:cryptKey:path:] + 700
5   MMKV                                0x00000001050d04b4 +[MMKV mmkvWithID:cryptKey:relativePath:] + 620
6   MMKV                                0x00000001050d00d4 +[MMKV mmkvWithID:cryptKey:] + 100
7   MMKV                                0x00000001050d000c +[MMKV mmkvWithID:] + 72
8   MMKV                                0x00000001050cffb8 +[MMKV defaultMMKV] + 64
9   oc_util                             0x0000000105725a50 +[MVCKeyValue d] + 52
10  oc_util                             0x0000000105725d0c +[MVCKeyValue getIntforKey:] + 64
11  rework-reader                       0x00000001049dbb9c __33-[RPCoreDataInsertOperation main]_block_invoke.85 + 68
12  libdispatch.dylib                   0x0000000105828dc8 _dispatch_client_callout + 16
13  libdispatch.dylib                   0x000000010582e6f4 _dispatch_sync_function_invoke + 112
14  rework-reader                       0x00000001049da9b4 -[RPCoreDataInsertOperation main] + 2132

**Comment by zsy78191** [comment]
换主线程就没问题了～ 请问MMKV必须要用主线程么？

**Comment by lingol** [comment]
It works just fine. Ignore this warning. 
See also #145

**Comment by lingol** [comment]
Fixed this warning with [v1.0.23](https://github.com/Tencent/MMKV/releases/tag/v1.0.23).
