### ISSUE TITLE
SIGBUS(BUS_ADRERR)

### ISSUE THREAD

**Issue by coolegos** [Tencent/MMKV#218]
### The language of MMKV

Kotlin

### The version of MMKV

v1.0.17

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?
![image](https://user-images.githubusercontent.com/6348861/54002832-e385cd80-418a-11e9-9adb-9fab5d7b16f2.png)

**Comment by lingol** [comment]
That line of code (MMKV.cpp:749) doesn't agree with the symbol `appendDataWithKey`. Can you provide original(原始) crash stack file?
It will be much helpful if you can provide logcat too.

**Comment by lingol** [comment]
And are you using com.tencent.mmkv:1.0.17, or com.tencent.mmkv-static:1.0.17?

**Comment by coolegos** [comment]
`com.tencent.mmkv:1.0.17`

**Comment by coolegos** [comment]
bugly 上面只能看到这个日志😅

**Comment by lingol** [comment]
How many users has faced this crash daily?

**Comment by coolegos** [comment]
我这几天一直在观察这个crash。最高峰的时候大概100人/天(非常少)，但是到3月9号的时候这个bug 就没有上报了，我确认下是不是使用方式的问题。有问题再提issue 😅😅😅

**Comment by lingol** [comment]
Some cases happened because there's not enough FreeStorage on device. Check your crash log for possible evidence?

**Comment by coolegos** [comment]
![image](https://user-images.githubusercontent.com/6348861/54206030-7ff4fa80-4512-11e9-8518-88186b3eaa67.png)
好像确实是因为空间不足😅，抱歉了。
