### ISSUE TITLE
Supported Parcelable?

### ISSUE THREAD

**Issue by orange1988** [Tencent/MMKV#220]
### The language of MMKV
Kotlin

### The version of MMKV
v1.0.10

### The platform of MMKV
Android

### The installation of MMKV
AAR Package 

### What's the issue?

> Explain what you want by example or code **in English**.
Official tutorial tells us  MMKV support the type which is class that implements Parcelable.  But the library doesn't provide the method.

**Comment by lingol** [comment]
For your convenience, here's the [example code](https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkvdemo/src/main/java/com/tencent/mmkvdemo/MainActivity.java#L205) from the official demo project.

**Comment by orange1988** [comment]
> For your convenience, here's the [example code](https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkvdemo/src/main/java/com/tencent/mmkvdemo/MainActivity.java#L205) from the official demo project.

Thanks a lot. I used 1.0.12 before, so I couldn't find the method.
