### ISSUE TITLE
key相同时，不是覆盖存储的吗

### ISSUE THREAD

**Issue by zengggongliang** [Tencent/MMKV#221]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
What's your problem, I don't quite understand.

**Comment by lingol** [comment]
Close due to inactive.
