### ISSUE TITLE
Using `pod_target_xcconfig` in Podspec to avoid modifying user application level xcconfig

### ISSUE THREAD

**Issue by dreampiggy** [Tencent/MMKV#226]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin
Objective-C/Swift

### The version of MMKV

> e.g. v1.0.10
1.0.17

### The platform of MMKV

> e.g. iOS or Android
iOS

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
CocoaPods

### What's the issue?
The podspec of MMKV, using the following syntax:

```ruby
  s.xcconfig = {
    "CLANG_CXX_LANGUAGE_STANDARD" => "gnu++17",
    "CLANG_CXX_LIBRARY" => "libc++",
    "CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF" => "NO",
  }
```

The `xcconfig` syntax of CocoaPods is deprecated in 1.6.0, and already been splited into two different syntax: `pod_target_xcconfig` and `user_target_xcconfig`, see https://guides.cocoapods.org/syntax/podspec.html

When using `xcconfig` in CocoaPods 1.6.0, any build settings of user application will be modified by the `xcconfig` used in Pods. For example, our application have a custom xcconfig with the following value:

```
"CLANG_CXX_LANGUAGE_STANDARD" = "gnu++14"
```

which is different from MMKV's value `gnu++17`. After running `pod install`, this will trigger the warning:

```
[!] The `DemoApp [Debug]` target overrides the `CLANG_CXX_LANGUAGE_STANDARD` build setting defined in `../../Pods/Target Support Files/Pods-DemoApp/Pods-DemoApp.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

I suggest to use `pod_target_xcconfig` (which is supported from the CocoaPods 1.0.x) instead of `xcconfig`.

**Comment by lingol** [comment]
Okey. I will look into it.

**Comment by lingol** [comment]
Fixed with [commit](https://github.com/Tencent/MMKV/commit/3b2ecbe26ccb1c47fe5383060df537d4891f5ba4).

**Comment by dreampiggy** [comment]
@lingol Thanks.

**Comment by lingol** [comment]
Release with [v1.0.19](https://github.com/Tencent/MMKV/releases/tag/v1.0.19).
