### ISSUE TITLE
couldn't find "libc++_shared.so" Device is x86

### ISSUE THREAD

**Issue by ZengCS** [Tencent/MMKV#227]
### The language of MMKV
Java

### The version of MMKV
v1.0.18

### The platform of MMKV
Android

### The installation of MMKV
AAR Package

### What's the issue?
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/NQSafeLauncher/NQSafeLauncher.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libc++_shared.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:366)
        at java.lang.System.loadLibrary(System.java:989)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:83)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:68)

**Comment by lingol** [comment]
Try `com.tencent.mmkv-static:1.0.18` with static linked of libc++.

**Comment by ZengCS** [comment]
> Try `com.tencent.mmkv-static:1.0.18` with static linked of libc++.

still error

**Comment by lingol** [comment]
> > Try `com.tencent.mmkv-static:1.0.18` with static linked of libc++.
> 
> still error

Well, what is it?

**Comment by lingol** [comment]
> > > Try `com.tencent.mmkv-static:1.0.18` with static linked of libc++.
> > 
> > 
> > still error
> 
> Well, what is it?

What's the error log after you tried `com.tencent.mmkv-static:1.0.18`?

**Comment by ZengCS** [comment]
> > > > Try `com.tencent.mmkv-static:1.0.18` with static linked of libc++.
> > > 
> > > 
> > > still error
> > 
> > 
> > Well, what is it?
> 
> What's the error log after you tried `com.tencent.mmkv-static:1.0.18`?

--------------2019-3-21 15:49:52
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/NQSafeLauncher/NQSafeLauncher.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libmmkv.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:366)
        at java.lang.System.loadLibrary(System.java:989)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:85)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:68)

**Comment by lingol** [comment]
Well, well, well, I don't think your apk is packaged correctly, seams the loader can't even find `libmmkv.so`. Unzip your apk package and check yourself.

**Comment by ZengCS** [comment]
> Well, well, well, I don't think your apk is packaged correctly, for the lib-loader can't even find `libmmkv.so`. Unzip your apk package and check yourself.

I konw the reason.Our app is **system app**,we install it with [adb push /system/app/].
Google said that must push the .so file to [/system/lib/] when someone install system app with [adb push] cmd.

Our app has other .so file,we put it under [/data/data/app_package/app_lib].
So,can we put the MMKV .so file into [/data/data/app_package/app_lib] like others?

**Comment by lingol** [comment]
I don't know for sure, but it should be no problem.

**Comment by lingol** [comment]
Any update on this issue?

**Comment by ZengCS** [comment]
SP I am back
