### ISSUE TITLE
repeat include aes.h compile error

### ISSUE THREAD

**Issue by y2kbug** [Tencent/MMKV#228]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Objective-c

### The version of MMKV

> e.g. v1.0.10

1.0.18

### The platform of MMKV

> e.g. iOS or Android

iOS

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
Repeated include aes.h file with third-party library SSZipArchive causes compilation to fail

**Comment by y2kbug** [comment]
How to solve this compilation error？

**Comment by lingol** [comment]
What's your podfile?

**Comment by y2kbug** [comment]
project 'GamePlatform.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '9.0'
use_frameworks!
## ignore warning
inhibit_all_warnings!

target 'GamePlatform' do

pod 'BGFMDB', '~> 2.0.13'
pod 'RealReachability', '~> 1.3.0'
pod 'Masonry'                           , '1.1.0'
pod 'UITableView+FDTemplateLayoutCell'  , '1.6'
pod 'MJExtension'                       , '3.0.13'
pod 'MJRefresh'                         , '3.1.12'
pod 'CocoaSecurity'                     , '1.2.4'
pod 'Colours'                           , '5.13.0'
pod 'UIImage+ImageWithColor'            , '1.4.0'
pod 'MBProgressHUD'                     , '1.0.0'
pod 'JDStatusBarNotification'           , '1.5.5'
pod 'DACircularProgress'                , '2.3.1'
# pod 'ReactiveCocoa'                     ,'2.5'
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
pod 'SDWebImage'                        , '4.0.0'
pod 'FXBlurView'                        , '1.6.4'
pod 'CocoaAsyncSocket'                  , '~> 7.6.3'
pod 'WZLBadge'                          , '1.2.6'
pod 'JSBadgeView'                       , '1.4.1'
pod 'SSZipArchive'                      , '1.8.1'
pod 'MMKV'                              , '1.0.18'
pod 'SAMKeychain'                       , '1.5.2'
pod 'MMMaterialDesignSpinner', '0.2.3'
pod 'JXCategoryView'             , '1.2.9'
pod 'JPFPSStatus', '0.1'
pod 'LxDBAnything', '1.1.0'
pod 'HYBImageCliped'                    , '2.2.4'
pod 'ZYCornerRadius'                    , '1.0.2'
pod 'HJCornerRadius', :git => 'https://github.com/panghaijiao/HJCornerRadius.git'
pod 'TTTAttributedLabel'                , '2.0.0'
pod 'libextobjc'                        , '0.4.1'
pod 'BlocksKit'                         , '2.2.5'
# UICollectionView左对齐布局
pod 'UICollectionViewLeftAlignedLayout' , '1.0.2'


# FaceBook KVO（优雅的代替系统原生的KVO）
pod 'KVOController'                     , '1.2.0'

# FaceBook 内存分析工具 其中包括了：FBAllocationTracker 和 FBRetainCycleDetector两个工具
pod 'FBMemoryProfiler'                  , '0.1.3'

# 二维码，条形码
pod 'LBXScan/LBXNative'                 ,'2.0'
pod 'LBXScan/LBXZXing'                  ,'2.0'
pod 'LBXScan/LBXZBar'                   ,'2.0'
pod 'LBXScan/UI'                        ,'2.0'

# 类似微博图片选择器
pod 'HXWeiboPhotoPicker'                     , '2.1.5'
# 点赞动画
pod 'YJFavorEmitter'

#pod 'SDCycleScrollView',                '~> 1.75'

#######---------- 企业第三方 ------------------########
# 集成腾讯bugly，用于打包测试和bug异常收集
pod 'Bugly'                             , '2.5.0'
# 极光推送
# pod 'JPush'                             , '3.0.6'
# 友盟相关
#pod 'UMengAnalytics-NO-IDFA'            , '4.2.5'
pod 'UMCCommon'
pod 'UMCPush'
pod 'UMCSecurityPlugins'
pod 'UMCAnalytics'

# U-Share SDK UI模块（分享面板，建议添加）
# pod 'UMengUShare/UI'                    , '6.4.5'
# 集成微信(完整版14.4M)
# pod 'UMengUShare/Social/GamePlatform'         , '6.4.5'
# 集成新浪微博(精简版1M)
# pod 'UMengUShare/Social/ReducedSina'    , '6.4.5'
# 集成QQ/QZone/TIM(精简版0.5M)
# pod 'UMengUShare/Social/ReducedQQ'      , '6.4.5'

# 高的定位地图
# pod 'AMapLocation'                      , '2.4.0'

# 文字滚动的label
pod 'TXScrollLabelView'                 , '1.3.1'

# iOS程序调试神器
# http://neater.github.io/blog/2014/07/31/flex!iosdiao-shi-li-qi/
# http://www.cocoachina.com/ios/20140728/9259.html
# http://www.starming.com/index.php?v=index&view=23
pod 'FLEX'                              , '2.4.0'

# pop动画
pod 'pop'                               , '1.0.10'
# 键盘管理
#pod 'IQKeyboardManager'                 , '5.0.2'
# 瀑布流
pod 'CHTCollectionViewWaterfallLayout'  , '0.9.6'
# 选择器
pod 'ActionSheetPicker-3.0'             , '2.2.0'

# 空占位
pod 'DZNEmptyDataSet'                   , '1.8.1'

pod 'PlaceholderTextView'               , '~> 0.3.0'

target 'GamePlatformTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'GamePlatformUITests' do
  inherit! :search_paths
  # Pods for testing
end

end

**Comment by y2kbug** [comment]
pod 'SSZipArchive'                      , '1.8.1'
pod 'MMKV'                              , '1.0.18'

**Comment by y2kbug** [comment]
Since both libraries include the aes.h file of openssl, the compilation error cannot be passed.

**Comment by lingol** [comment]
I've got it reproduced. Looking into it now.

**Comment by y2kbug** [comment]
> I've got it reproduced. Looking into it now.

Thank you for your reply!

**Comment by lingol** [comment]
I decide [renaming](https://github.com/Tencent/MMKV/commit/7f2949d81cc4cdcb6023be89ae75f87d8d72d08c) all those openssl files, which will come out at next version.
For the time being, you can build MMKV from source & import it as a pre-build framework.
https://github.com/Tencent/MMKV/wiki/iOS_setup#installation

**Comment by y2kbug** [comment]
Great, the speed at which you solve the problem.

**Comment by lingol** [comment]
Release with [v1.0.19](https://github.com/Tencent/MMKV/releases/tag/v1.0.19).
