### ISSUE TITLE
SharedPreferences and mmkv Memory Occupancy

### ISSUE THREAD

**Issue by corabsins** [Tencent/MMKV#230]
### The language of MMKV

> Java,

### The version of MMKV

> e.g. v1.0.17

### The platform of MMKV

> Android

### What's the issue?
I tested it with mmkv, using 65534 bytes of data storage, and looked at the file size in memory as 2M, while the file size in Shared Preferences was only 85kb. Why?

**Comment by lingol** [comment]
Would you like to show your test code?

**Comment by corabsins** [comment]
Look at the code below. The length of the data is 65534 and the size of the file stored is 2M.

private void testMMKV(){
        //data 的长度为 65534
        String data = "{\"token\":\"SNTA0MjAjIzEwMjc1OTQ5IyNhNDAzNjBiZTJmNGIwM2Q4YjliZDg4MTNlYjA0Y2RiZSMjYjQzMmUwYjcxYTgzNmQ0NWVlYTY2NWQzMmE1OGFkOTcjIzE0NjMwMzk1Nzc=z\",\"uid\":\"50420\",\"userType\":\"visitor\"}...........";
        MMKV kv2 = MMKV.mmkvWithID("file.txt",1);
        kv2.encode("bbb",data);
    }

**Comment by corabsins** [comment]
I found that mmkv had more than twice as much storage space as SharedPreferences.

**Comment by lingol** [comment]
I'll test it later. Thanks for your feedback.

**Comment by corabsins** [comment]
ok ，Thx , Small data is the same.

**Comment by lingol** [comment]
I have look into the code. That behavior is OK. For MMKV is designed for **frequently writing** & reading. To avoid unnecessary full-writeback, MMKV will make some reserved room for future usage, aka `max(8, key_count / 2) * average_value_size`. 

As long as the file size doesn't grow unlimitedly in the foreseeable future, that's totally OK.

**Comment by corabsins** [comment]
Can you help me figure out what average_value_size means?

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/cpp/MMKV.cpp#L688
