### ISSUE TITLE
这个错误是怎么导致的？

### ISSUE THREAD

**Issue by dragon-y** [Tencent/MMKV#231]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android
![image](https://user-images.githubusercontent.com/44430123/54862786-9b65ce00-4d7a-11e9-9a0f-7f50f030aa54.png)
![image](https://user-images.githubusercontent.com/44430123/54862795-c2240480-4d7a-11e9-8b93-8973abe6ce61.png)

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
Your file is corrupted.
