### ISSUE TITLE
_MMKVLogWithLevel.cpp:72

### ISSUE THREAD

**Issue by hick1213** [Tencent/MMKV#232]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin
C++

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android
Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

mmkv/MMKVLog.cpp:72:28: error: cannot initialize a parameter of type 'char *' with an rvalue of type 'const std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::value_type *' (aka 'const char *')
            std::vsnprintf(message.data(), length + 1, format, args);

**Comment by lingol** [comment]
Thanks for your feedback. Fixed in `dev` now.

**Comment by lingol** [comment]
Release with [v1.0.19](https://github.com/Tencent/MMKV/releases/tag/v1.0.19).
