### ISSUE TITLE
Read and write multiple times, reading the old value

### ISSUE THREAD

**Issue by yihuajia** [Tencent/MMKV#234]
### The language of MMKV

>Java

### The version of MMKV

>v1.0.18

### The platform of MMKV

> Android

### The installation of MMKV

>  Maven

### What's the issue?
Hey,When I use MMKV on an android device, if I do multiple reads and writes, the next time I read the data, there is a certain probability that the old data will appear.We use an offline and online environment switching business. After switching to offline, we did not go through other operations. When the device is restarted after power failure, we get the online environment.But the same operation is changed to sp will be no problem.

**Comment by lingol** [comment]
Check your write orders, is it possible that you writing old value to override new value?
If you can reproduce such cases, send me a demo project would be nice.

**Comment by yihuajia** [comment]
The write order has been checked and there is no old value to overwrite the new value.
e.g:The state value of a switch has been saved, and the switch has been turned on, but occasionally it is turned off in the program. This problem is not necessarily a must.

**Comment by lingol** [comment]
Now do you have any logs when it went wrong? Try redirect & save MMKV's internal log, and send them to me when it happens.

**Comment by yihuajia** [comment]
This problem has only appeared on the customer side, and we are still unable to reproduce it for the time being. Only the next version of MMKVHandler can be added to record the log.

**Comment by yihuajia** [comment]
Hello, there is the same situation as last time.After the device is restarted, when you enter the app again, a certain probability will appear.

**The following is the log record**
`{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\"}","f":6,"l":1554860678859,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 295 size in total, file size is 4096\"}","f":6,"l":1554860679269,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 3935354034 sequence 4\"}","f":6,"l":1554860679282,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 3 values\"}","f":6,"l":1554860679287,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:699::ensureMemorySize\\u003e extending [xxxxxxxx] file size from 4096 to 32768, incoming size:4614, futrue usage:6604\"}","f":6,"l":1554860679594,"n":"RxComputationThreadPool-5","i":592,"m":false}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\",\"store_id\":\"47\"}","f":6,"l":1554860707466,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 21842 size in total, file size is 32768\"}","f":6,"l":1554860707532,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 3361599648 sequence 5\"}","f":6,"l":1554860707537,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 42 values\",\"store_id\":\"47\"}","f":6,"l":1554860707544,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:699::ensureMemorySize\\u003e extending [xxxxxxxx] file size from 32768 to 262144, incoming size:81941, futrue usage:88506\",\"store_id\":\"47\"}","f":6,"l":1554860708648,"n":"RxCachedThreadScheduler-5","i":675,"m":false}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\",\"store_id\":\"47\"}","f":6,"l":1554860794281,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 259595 size in total, file size is 262144\"}","f":6,"l":1554860794604,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 3965174467 sequence 6\"}","f":6,"l":1554860794611,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\",\"store_id\":\"47\"}","f":6,"l":1554860794615,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:699::ensureMemorySize\\u003e extending [xxxxxxxx] file size from 262144 to 524288, incoming size:2150, futrue usage:89784\",\"store_id\":\"47\"}","f":6,"l":1554860794895,"n":"RxComputationThreadPool-5","i":226,"m":false}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\",\"store_id\":\"54\"}","f":6,"l":1554860861016,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 191880 size in total, file size is 524288\"}","f":6,"l":1554860861075,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 3749838197 sequence 7\"}","f":6,"l":1554860861085,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\",\"store_id\":\"54\"}","f":6,"l":1554860861092,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\"}","f":6,"l":1554860875753,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 191985 size in total, file size is 524288\"}","f":6,"l":1554860875767,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 2331278955 sequence 7\"}","f":6,"l":1554860875775,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\"}","f":6,"l":1554860875780,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\"}","f":6,"l":1554860875781,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 191985 size in total, file size is 524288\"}","f":6,"l":1554860875795,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 2331278955 sequence 7\"}","f":6,"l":1554860875800,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\"}","f":6,"l":1554860875804,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\"}","f":6,"l":1554860875805,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 191985 size in total, file size is 524288\"}","f":6,"l":1554860875817,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 2331278955 sequence 7\"}","f":6,"l":1554860875822,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\"}","f":6,"l":1554860875826,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\"}","f":6,"l":1554860875827,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 191985 size in total, file size is 524288\"}","f":6,"l":1554860875846,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 2331278955 sequence 7\"}","f":6,"l":1554860875857,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\"}","f":6,"l":1554860875862,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\"}","f":6,"l":1554860875863,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 191985 size in total, file size is 524288\"}","f":6,"l":1554860875881,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 2331278955 sequence 7\"}","f":6,"l":1554860875886,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\"}","f":6,"l":1554860875892,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\"}","f":6,"l":1554860875893,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 191985 size in total, file size is 524288\"}","f":6,"l":1554860875904,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 2331278955 sequence 7\"}","f":6,"l":1554860875909,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\"}","f":6,"l":1554860875913,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\"}","f":6,"l":1554860875914,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 191985 size in total, file size is 524288\"}","f":6,"l":1554860875922,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 2331278955 sequence 7\"}","f":6,"l":1554860875927,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\"}","f":6,"l":1554860875932,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\"}","f":6,"l":1554860875933,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 191985 size in total, file size is 524288\"}","f":6,"l":1554860875949,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 2331278955 sequence 7\"}","f":6,"l":1554860875953,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\"}","f":6,"l":1554860875960,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\"}","f":6,"l":1554860875961,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 191985 size in total, file size is 524288\"}","f":6,"l":1554860875978,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 2331278955 sequence 7\"}","f":6,"l":1554860876000,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\"}","f":6,"l":1554860876009,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\"}","f":6,"l":1554860876010,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 191985 size in total, file size is 524288\"}","f":6,"l":1554860876166,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 2331278955 sequence 7\"}","f":6,"l":1554860876170,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\"}","f":6,"l":1554860876174,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:566::clearMemoryState\\u003e clearMemoryState [xxxxxxxx]\",\"store_id\":\"47\"}","f":6,"l":1554860883859,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:330::loadFromFile\\u003e loading [xxxxxxxx] with 202126 size in total, file size is 524288\"}","f":6,"l":1554860883929,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:354::loadFromFile\\u003e loading [xxxxxxxx] with crc 4177682793 sequence 7\"}","f":6,"l":1554860883936,"n":"main","i":1,"m":true}
{"c":"{\"msg\":\"redirect logging MMKV i|\\u003cMMKV.cpp:375::loadFromFile\\u003e loaded [xxxxxxxx] with 58 values\",\"store_id\":\"47\"}","f":6,"l":1554860883942,"n":"main","i":1,"m":true}
`

**Comment by yihuajia** [comment]
When the program is started, the corresponding key is written once, and then acquired at the time of login, and the value obtained is not the value just written.

**Comment by lingol** [comment]
When did the reboot happen, in your specific log? Your log starts at Wed Apr 10 2019 09:44:38, ends at Wed Apr 10 2019 09:48:03.

**Comment by lingol** [comment]
And by the way, I strongly recommend using [mars-xlog](https://github.com/Tencent/mars#mars-xlog), it makes everything easy about logging.

**Comment by lingol** [comment]
Also, it will be much helpful if you can print the process-id & thread-id on each line of log.

**Comment by yihuajia** [comment]
Otherwise, I will send the entire log file to your mailbox?

**Comment by yihuajia** [comment]
We are currently using Logan to record log.

**Comment by lingol** [comment]
That's very helpful. guoling@tencent.com

> Otherwise, I will send the entire log file to your e-mail?
