### ISSUE TITLE
high CPU and IO cost when memory is almost filled 

### ISSUE THREAD

**Issue by chenzhu33** [Tencent/MMKV#235]
### The language of MMKV

> Java

### The version of MMKV

> all version

### The platform of MMKV

> Android

### The installation of MMKV

> aar

### What's the issue?

When system memory is almost filled, MMKV will cost high cpu and IO usage.
The possible reason may be the memory of mmap is swapped to disk and leads to lots of IO operation

**Comment by lingol** [comment]
Well I haven't come across such case. Should that be true, it's something we(the App developer) can't do a thing about, right? I would love to hear any advise.

**Comment by lingol** [comment]
Close due to inactive.
