### ISSUE TITLE
Android Q 对共享内存进行了调整，以 Android Q 为目标平台的应用无法再直接使用 ashmem (/dev/ashmem)。

### ISSUE THREAD

**Issue by qiaoshouqing** [Tencent/MMKV#242]
### The platform of MMKV
Android

### 描述
根据Android Q行为变更中关于共享内存的描述：

> Ashmem 更改了 /proc/<pid>/maps 中的 dalvik 映射的格式，这会影响那些直接解析映射文件的应用。如果应用依赖于 dalvik 映射格式，则应用开发者应该在设备上测试新的 /proc/<pid>/maps 格式并相应地进行解析。
> 
> **以 Android Q 为目标平台的应用无法再直接使用 ashmem (/dev/ashmem)**，而必须通过 NDK 的 ASharedMemory 类访问共享内存。此外，应用无法直接对现有 ashmem 文件描述符进行 IOCTL，而必须改为使用 NDK 的 ASharedMemory 类或 Android Java API 创建共享内存区域。这项变更可以提高使用共享内存时的安全性和稳健性，从而提高 Android 的整体性能和安全性。

导致MMKV在目标平台为Android Q的时候可能无法正常使用，这个能否及时处理一下呢？

**Comment by lingol** [comment]
Thanks for the update. We'll look into it.

**Comment by lingol** [comment]
Supported with this [commit](https://github.com/Tencent/MMKV/commit/fabce0a3ff1d707de6b82c3291b8599f89766c7d) on `dev` branch.

**Comment by qiaoshouqing** [comment]
赞，好有效率！

**Comment by lingol** [comment]
Release with [v1.0.19](https://github.com/Tencent/MMKV/releases/tag/v1.0.19).
