### ISSUE TITLE
auto appState = [UIApplication sharedApplication].applicationState;

### ISSUE THREAD

**Issue by hulailin** [Tencent/MMKV#245]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

[UIApplication applicationState] must be used from main thread only

**Comment by lingol** [comment]
Duplicate with #209

**Comment by lingol** [comment]
Fixed with [v1.0.23](https://github.com/Tencent/MMKV/releases/tag/v1.0.23).
