### ISSUE TITLE
SIGABRT Crash

### ISSUE THREAD

**Issue by Heycz** [Tencent/MMKV#248]
### The language of MMKV

> Java

### The version of MMKV

> v1.0.18

### The platform of MMKV

> Android

### The installation of MMKV

> Gradle

### What's the issue?

> 04-26 15:52:07.194 4543-4543/? I/MMKV: <MMKV.cpp:192::initialize> page size:4096
04-26 15:52:07.199 4481-4533/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_cryptKey__
04-26 15:52:07.199 4481-4533/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_cryptKey
04-26 15:52:07.199 4481-4533/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_cryptKey__
04-26 15:52:07.199 4481-4533/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_cryptKey
04-26 15:52:07.199 4481-4533/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_cryptKey__
04-26 15:52:07.199 4481-4533/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_cryptKey
04-26 15:52:07.202 4543-4543/? I/MMKV: <MMKV.cpp:206::initializeMMKV> root dir: /data/user/0/com.heycz.mission.test5/files/mmkv
04-26 15:52:07.225 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_getDefaultMMKV
04-26 15:52:07.227 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_getDefaultMMKV__ILjava_lang_String_2
04-26 15:52:07.227 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_getDefaultMMKV
04-26 15:52:07.227 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_getDefaultMMKV__ILjava_lang_String_2
04-26 15:52:07.227 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_getDefaultMMKV
04-26 15:52:07.236 4543-4543/? I/MMKV: <MMKV.cpp:330::loadFromFile> loading [mmkv.default] with 14785 size in total, file size is 16384
04-26 15:52:07.236 4543-4543/? I/MMKV: <MMKV.cpp:354::loadFromFile> loading [mmkv.default] with crc 618403423 sequence 11
04-26 15:52:07.267 4543-4543/? I/MMKV: <MMKV.cpp:375::loadFromFile> loaded [mmkv.default] with 15 values
04-26 15:52:07.271 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeString
04-26 15:52:07.271 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeString__JLjava_lang_String_2Ljava_lang_String_2
04-26 15:52:07.271 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeString
04-26 15:52:07.271 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeString__JLjava_lang_String_2Ljava_lang_String_2
04-26 15:52:07.271 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeString
04-26 15:52:07.275 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeString
04-26 15:52:07.276 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeString__JLjava_lang_String_2Ljava_lang_String_2
04-26 15:52:07.276 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeString
04-26 15:52:07.276 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeString__JLjava_lang_String_2Ljava_lang_String_2
04-26 15:52:07.276 4543-4543/? V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeString
04-26 15:52:07.696 4543-4571/? D/CrashReport-Native: Parsing line: 0ca00000-0ca12000 r-xp 00000000 08:13 1736861    /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so
04-26 15:52:07.697 4543-4571/? D/CrashReport-Native: Parsing line: 0ca12000-0ca13000 r-xp 00011000 08:13 1736861    /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so
04-26 15:52:07.697 4543-4571/? D/CrashReport-Native: Parsing line: 0ca13000-0ca14000 rwxp 00012000 08:13 1736861    /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so
04-26 15:52:07.721 4543-4571/? D/CrashReport-Native: Parsing line: a851a000-a851e000 rw-s 00000000 08:13 639377     /data/data/com.heycz.mission.test5/files/mmkv/mmkv.default
04-26 15:52:07.732 4543-4571/? D/CrashReport-Native: Parsing line: ab7bc000-ab7bd000 rw-s 00000000 08:13 639192     /data/data/com.heycz.mission.test5/files/mmkv/mmkv.default.crc
04-26 15:52:07.922 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:330::loadFromFile> loading [AppBrandUI] with 3131 size in total, file size is 4096
04-26 15:52:07.922 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:354::loadFromFile> loading [AppBrandUI] with crc 508567664 sequence 2
04-26 15:52:07.924 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:375::loadFromFile> loaded [AppBrandUI] with 3 values
04-26 15:52:07.924 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeInt
04-26 15:52:07.924 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeInt__JLjava_lang_String_2I
04-26 15:52:07.924 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeInt
04-26 15:52:07.924 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeInt__JLjava_lang_String_2I
04-26 15:52:07.924 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeInt
04-26 15:52:07.924 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeInt__JLjava_lang_String_2I
04-26 15:52:07.924 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_encodeInt
04-26 15:52:08.009 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:330::loadFromFile> loading [mop] with 14154 size in total, file size is 16384
04-26 15:52:08.009 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:354::loadFromFile> loading [mop] with crc 2948289918 sequence 8
04-26 15:52:08.010 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:375::loadFromFile> loaded [mop] with 22 values
04-26 15:52:08.384 4481-4561/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeBool
04-26 15:52:08.384 4481-4561/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeBool__JLjava_lang_String_2Z
04-26 15:52:08.384 4481-4561/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeBool
04-26 15:52:08.384 4481-4561/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeBool__JLjava_lang_String_2Z
04-26 15:52:08.384 4481-4561/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeBool
04-26 15:52:08.384 4481-4561/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeBool__JLjava_lang_String_2Z
04-26 15:52:08.384 4481-4561/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeBool
04-26 15:52:08.613 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:330::loadFromFile> loading [liangyj3_preferences] with 211 size in total, file size is 4096
04-26 15:52:08.613 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:354::loadFromFile> loading [liangyj3_preferences] with crc 2641939807 sequence 2
04-26 15:52:08.614 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:375::loadFromFile> loaded [liangyj3_preferences] with 4 values
04-26 15:52:08.614 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_count
04-26 15:52:08.614 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_count__J
04-26 15:52:08.614 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_count
04-26 15:52:08.614 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_count__J
04-26 15:52:08.614 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_count
04-26 15:52:08.614 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_count__J
04-26 15:52:08.614 4481-4481/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_count
04-26 15:52:08.671 4481-4596/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_allKeys
04-26 15:52:08.671 4481-4596/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_allKeys__
04-26 15:52:08.671 4481-4596/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_allKeys
04-26 15:52:08.671 4481-4596/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_allKeys__
04-26 15:52:08.671 4481-4596/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_allKeys
04-26 15:52:08.671 4481-4596/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_allKeys__
04-26 15:52:08.671 4481-4596/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_allKeys
04-26 15:52:08.723 4481-4596/com.heycz.mission.test5 A/art: art/runtime/java_vm_ext.cc:410]     from java.lang.String[] com.tencent.mmkv.MMKV.allKeys()
04-26 15:52:08.723 4481-4596/com.heycz.mission.test5 A/art: art/runtime/java_vm_ext.cc:410]   at com.tencent.mmkv.MMKV.allKeys(Native method)
04-26 15:52:09.580 4481-4596/com.heycz.mission.test5 A/art: art/runtime/runtime.cc:366]   at com.tencent.mmkv.MMKV.allKeys(Native method)
04-26 15:52:09.581 4481-4596/com.heycz.mission.test5 A/art: art/runtime/runtime.cc:366]   at com.tencent.mmkv.MMKV.allKeys(Native method)
04-26 15:52:09.726 4481-4558/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:330::loadFromFile> loading [config_liangyj3] with 11667 size in total, file size is 16384
04-26 15:52:09.726 4481-4558/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:354::loadFromFile> loading [config_liangyj3] with crc 860279315 sequence 5
04-26 15:52:09.731 4481-4558/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:375::loadFromFile> loaded [config_liangyj3] with 9 values
04-26 15:52:09.732 4481-4596/com.heycz.mission.test5 D/CrashReport-Native: Parsing line: 0ca00000-0ca12000 r-xp 00000000 08:13 1736861    /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so
04-26 15:52:09.732 4481-4596/com.heycz.mission.test5 D/CrashReport-Native: Parsing line: 0ca12000-0ca13000 r-xp 00011000 08:13 1736861    /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so
04-26 15:52:09.733 4481-4596/com.heycz.mission.test5 D/CrashReport-Native: Parsing line: 0ca13000-0ca14000 rwxp 00012000 08:13 1736861    /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so
04-26 15:52:09.743 4481-4596/com.heycz.mission.test5 D/CrashReport-Native: Parsing line: 97dc5000-97dc9000 rw-s 00000000 08:13 639478     /data/data/com.heycz.mission.test5/files/mmkv/config_liangyj3
04-26 15:52:09.761 4481-4596/com.heycz.mission.test5 D/CrashReport-Native: Parsing line: 9adf7000-9adf8000 rw-s 00000000 08:13 639477     /data/data/com.heycz.mission.test5/files/mmkv/config_liangyj3.crc
04-26 15:52:09.765 4481-4596/com.heycz.mission.test5 D/CrashReport-Native: Parsing line: 9c043000-9c044000 rw-s 00000000 08:13 639475     /data/data/com.heycz.mission.test5/files/mmkv/liangyj3_preferences
04-26 15:52:09.765 4481-4596/com.heycz.mission.test5 D/CrashReport-Native: Parsing line: 9c4c0000-9c4c1000 rw-s 00000000 08:13 639473     /data/data/com.heycz.mission.test5/files/mmkv/liangyj3_preferences.crc
04-26 15:52:09.786 4481-4596/com.heycz.mission.test5 D/CrashReport-Native: Parsing line: ab7bc000-ab7bd000 rw-s 00000000 08:13 639192     /data/data/com.heycz.mission.test5/files/mmkv/mmkv.default.crc
04-26 15:52:09.860 4481-4596/com.heycz.mission.test5 D/CrashReport-Native: Found the module: /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so
04-26 15:52:09.860 4481-4596/com.heycz.mission.test5 D/CrashReport-Native: Got module name: /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so for pc: 0xca03607
04-26 15:52:09.860 4481-4596/com.heycz.mission.test5 I/CrashReport-Native: Parsing ELF file: /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so
04-26 15:52:09.863 4481-4596/com.heycz.mission.test5 D/CrashReport-Native: Function with offset 0x3607 may only be contained in debug so of: /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so
04-26 15:52:09.863 4481-4596/com.heycz.mission.test5 I/CrashReport-Native:         #00    pc 00003607    /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so [armeabi-v7a::89f80396294b0bb525a85e08dfeb79f4]
04-26 15:52:09.866 4481-4596/com.heycz.mission.test5 D/Bugly-libunwind: Trying to find .debug_frame for /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so
04-26 15:52:09.866 4481-4596/com.heycz.mission.test5 D/Bugly-libunwind: opened file '/data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so'. Section header at offset 74212
04-26 15:52:09.872 4481-4596/com.heycz.mission.test5 D/Bugly-libunwind: Trying to find .debug_frame for /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so
04-26 15:52:10.660 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:330::loadFromFile> loading [2806155387147264] with 239 size in total, file size is 4096
04-26 15:52:10.661 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:354::loadFromFile> loading [2806155387147264] with crc 3876434036 sequence 7
04-26 15:52:10.661 4481-4481/com.heycz.mission.test5 I/MMKV: <MMKV.cpp:375::loadFromFile> loaded [2806155387147264] with 6 values
04-26 15:52:10.809 4481-4624/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeInt
04-26 15:52:10.809 4481-4624/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeInt__JLjava_lang_String_2I
04-26 15:52:10.809 4481-4624/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeInt
04-26 15:52:10.811 4481-4624/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeInt__JLjava_lang_String_2I
04-26 15:52:10.811 4481-4624/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeInt
04-26 15:52:10.811 4481-4624/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeInt__JLjava_lang_String_2I
04-26 15:52:10.811 4481-4624/com.heycz.mission.test5 V/libnb: enter native_bridge2_getTrampoline Java_com_tencent_mmkv_MMKV_decodeInt
04-26 15:52:11.075 4481-4629/com.heycz.mission.test5 E/CrashReport: SIGABRT
    0x1181
    #00    pc 00003607    /data/app/com.heycz.mission.test5-1/lib/arm/libmmkv.so [armeabi-v7a::89f80396294b0bb525a85e08dfeb79f4]
    java:
    com.heycz.util.McPreferencesImpl.allKeys(McPreferencesImpl.kt:116)
    com.heycz.mop.internal.MopJobThread.queueIdle(MopJobThread.java:54)
    android.os.MessageQueue.next(MessageQueue.java:392)
    android.os.Looper.loop(Looper.java:135)
    android.os.HandlerThread.run(HandlerThread.java:61)
> 
 Native Crash on Android 6.0.1,level 23 Xiaomi x86

**Comment by lingol** [comment]
Although you have closed this issue, I have to ask, did you find the answer to the crash?

**Comment by Heycz** [comment]
MMKV如果一开始没有用加密存储数据,然后之后如果B密码创建MMKV的时候,调allKey会crash,但是其他方法(写入,查询数量)都不会报错
