### ISSUE TITLE
Use explicit registration to avoid UnsatisfiedLinkError.

### ISSUE THREAD

**Issue by alhah** [Tencent/MMKV#252]
### The language of MMKV

Java

### The version of MMKV

v1.0.19

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?
From my experience, implicit registration like "Java_com_tencent_mmkv_MMKV_encodeString" may caused `UnsatisfiedLinkError(No implementation found for native Lcom/tencent/mmkv/MMKV;.encodeString:(JLjava/lang/String;Ljava/lang/String;)Z)` below Android 5.0 occasionally(maybe 0.01%).

I don't know the real reason about that, but when I use explicit registration with `env->RegisterNatives`, this kind of issues gone. 

Just a suggestion.

**Comment by lingol** [comment]
Thanks for your input. I will look into it.

**Comment by lingol** [comment]
After Google about it a bit, I don't think `RegisterNatives` has anything todo with avoiding `UnsatisfiedLinkError` crash, as those kinds of crash were mainly due to missing relative so when the APK is installed/updated.
However, I do believe using `RegisterNatives` can simplify the native method naming. So I'll probably using that in next version.

**Comment by lingol** [comment]
Released with [v1.0.20](https://github.com/Tencent/MMKV/releases/tag/v1.0.20).

**Comment by alhah** [comment]
I found the reason of UnsatisfiedLinkError below Android 5.0 in https://github.com/Tencent/mars/issues/334, which caused by dalvik bug(Multi-threaded competition). RegisterNatives will change native method calling timing(resolve method in advance).

**Comment by lingol** [comment]
> I found the reason of UnsatisfiedLinkError below Android 5.0 in [Tencent/mars#334](https://github.com/Tencent/mars/issues/334), which caused by dalvik bug(Multi-threaded competition). RegisterNatives will change native method calling timing(resolve method in advance).

That's good to know, thanks.
