### ISSUE TITLE
MMKV 原子性保证

### ISSUE THREAD

**Issue by yejkk** [Tencent/MMKV#253]
MMKV 会考虑原子操作(比如提供CAS)吗？
比如存的数据+1等等操作。

**Comment by lingol** [comment]
Maybe.

**Comment by lingol** [comment]
After months of thinking about this feature, now I don't think MMKV should provide it.

It's about responsibility and targeting.
MMKV is a very fast key-value storage engine. Better keep it that way. And doing any atomic operation(++/--/cas, etc) above a storage engine makes little sense. You better do it in native memory, and store the final value in MMKV only if you want to keep it persistently.

So NO, MMKV won't do it.
