### ISSUE TITLE
在子线程中调用[MMKV defaultMMKV]出现错误

### ISSUE THREAD

**Issue by hejunbinlan** [Tencent/MMKV#254]
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]

**Comment by hejunbinlan** [comment]
这样只能在主线程中调用[MMKV defaultMMKV]？

**Comment by heyangJob** [comment]
1、我的理解是写入都是内存，会不会造成app使用的时候内存很大。

**Comment by lingol** [comment]
Duplicated with #245 .

**Comment by lingol** [comment]
Fixed with [v1.0.23](https://github.com/Tencent/MMKV/releases/tag/v1.0.23).
