### ISSUE TITLE
关于mmkv在低端手机上的测试（512mb）

### ISSUE THREAD

**Issue by heyangJob** [Tencent/MMKV#255]
Android 几大问题：
1、写入内存，然后系统负责写入文件。mmkv在内存中占了多大，是apped 一直扩张吗？
2、批量写入时需要用线程池？
3、系统写入部分使用了文件锁，在低端机型上会出现anr吗？我们现在的app使用的sp，出现很多类似的anr。就是在commit写入的时候需要等待写完成才能向下进行。阻塞主线程导致anr。小白请教，并没有看c++实现的代码。大佬互喷

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
Please read the [design](https://github.com/Tencent/MMKV/wiki/design) first, come back if you still have questions.

**Comment by heyangJob** [comment]
谢谢大佬，文档我已经看过了，增加相同的key 是用的append，这样内存中存的就越来越大了，会不会影响app的体验速度，能不能设置使用的内存的大小，如果超出就能文档说的重排。

**Comment by lingol** [comment]
The default memory growth algorithm should suite most common usage. Make such request(setting a fixed memory size, etc) if only you have evidence that things doesn't work for you.

Remember, **premature** optimization is the root of all evil.
