### ISSUE TITLE
MMKV删除文件保存路径不会清除数据吗

### ISSUE THREAD

**Issue by xiexin52k** [Tencent/MMKV#256]
### The language of MMKV

> Java

### The version of MMKV

> 1.0.19

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

我将MMKV保存在外部指定的目录, 然后从代码中删除掉这个目录. 我本意是打算连同MMKV的记录一起删除的. 但是事实上并没有这样, 等下次再使用这个目录的时候, MMKV的数据还是以前的.

下面贴上伪代码:
```java
//先创建
 mmkv = MMKV.mmkvWithID(name, mmkvPath);
//保存一个 100的int值
mmkv.encode("int",100);
 //删除这个目录
FileUtils.delete(mmkvPath);
//重新创建
 mmkv = MMKV.mmkvWithID(name, mmkvPath);
//这时候int并不是我想要的-1, 而是以前的100. 
int = mmkv.decodeInt("int",-1);
```

**Comment by heyangJob** [comment]
内存中还存在吧 clearMemoryCache

**Comment by lingol** [comment]
> 内存中还存在吧 clearMemoryCache

That's correct.
You should do this by calling MMKV's `clearAll()` method.
