### ISSUE TITLE
存取方法不一致时没有正确返回错误

### ISSUE THREAD

**Issue by yuman07** [Tencent/MMKV#257]
### The language of MMKV

Objective-C

### The version of MMKV

1.0.19

### The platform of MMKV

iOS

### The installation of MMKV

Cocoapods

### What's the issue?

` 
[[MMKV defaultMMKV] clearAll];

 [[MMKV defaultMMKV] setObject:@(1) forKey:@"123"];

int a = [[MMKV defaultMMKV] getInt32ForKey:@"123" defaultValue:10];

NSLog(@"%@", @(a));
`

这段代码在我的模拟器上永远输出'98'

这段代码存取方法不对应，合乎逻辑的结果应该是取失败，或者取到默认值。
不然的话，除非我对这个值的真实含义很明白，不然很可能就把这个'98'当做正确值一直用下去了

**Comment by lingol** [comment]
Duplicate with #63
