### ISSUE TITLE
Android4.4及以下崩溃：Native method not found

### ISSUE THREAD

**Issue by luyaotree** [Tencent/MMKV#258]
之前有issue反应说是升级到v1.0.13以上可以解决，但是我这都1.0.18了还是报错
使用版本号是：com.tencent:mmkv-static:1.0.18'  
@lingol
报错如下：
![image](https://user-images.githubusercontent.com/13991485/57444165-17ac6600-7282-11e9-9706-b6e220cae4f1.png)

**Comment by luyaotree** [comment]
之前有issue反应说是升级到v1.0.13以上可以，但是我这都1.0.18了还是报错， @lingol 

1 java.lang.IllegalStateException:Fatal Exception thrown on Scheduler.Worker thread.
--
2 rx.internal.schedulers.ScheduledAction.run(SourceFile:62)
3 ......
4 Caused by:
5 java.lang.UnsatisfiedLinkError:Native method not found: com.tencent.mmkv.MMKV.decodeString:(JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
6 com.tencent.mmkv.MMKV.decodeString(Native Method)
7 com.tencent.mmkv.MMKV.decodeString(SourceFile:353)

**Comment by lingol** [comment]
Duplicate with #139
