### ISSUE TITLE
android minsdk怎么支持下15

### ISSUE THREAD

**Issue by wangzt** [Tencent/MMKV#26]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
That's not in our current plan.
As a matter of fact, WeChat on Android has just change its miniSDK up to API level 19.

It's good to look forward.
