### ISSUE TITLE
rootDir 赋值

### ISSUE THREAD

**Issue by pipBug** [Tencent/MMKV#260]
### The language of MMKV

> e.g. Java

### The version of MMKV

> e.g. v1.0.19

### The platform of MMKV

> e.g. Android

### The installation of MMKV

> e.g. Maven

### What's the issue?

![image](https://user-images.githubusercontent.com/13911593/57862685-58c8eb00-782b-11e9-8273-9fb903ccaa87.png)

正在尝试如何多进程使用 mmkv 的时候发现了这里 rootDir 赋值的问题，请问这里不用加 this 嘛？

**Comment by pipBug** [comment]
错了，应该是 MMKV.rootDir = rootDir

**Comment by lingol** [comment]
Got it. It's actually confusing. Will fix soon.

**Comment by lingol** [comment]
You are looking at the wrong file. Decompiled .class?
![image](https://user-images.githubusercontent.com/2088859/57901237-c2321380-7896-11e9-83ac-e0395d461885.png)
 
Last time I check, Code in MMKV is fine.
https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/java/com/tencent/mmkv/MMKV.java#L87
