### ISSUE TITLE
Will MMKV migrate to AndroidX

### ISSUE THREAD

**Issue by zhangzhenxi** [Tencent/MMKV#262]
### The language of MMKV

> Java

### The version of MMKV

> 1.0.10

### The platform of MMKV

> Android

### The installation of MMKV

> AAR Package

### What's the issue?

Will MMKV migrate to AndroidX ？

**Comment by zhangzhenxi** [comment]
[PR#263](https://github.com/Tencent/MMKV/pull/263)

**Comment by lingol** [comment]
Thanks.

**Comment by lingol** [comment]
Sadly I found that you were making changes directly into `master` branch. I have to revert it.
I'll **properly** migrate to Android X on `dev` branch later today.

**Comment by lingol** [comment]
Released with [v1.0.20](https://github.com/Tencent/MMKV/releases/tag/v1.0.20).
