### ISSUE TITLE
carsh on HUAWEI CAZ AL10

### ISSUE THREAD

**Issue by imxy** [Tencent/MMKV#266]
### The language of MMKV

Java

### The version of MMKV

1.0.16

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?

java.lang.UnsatisfiedLinkError
dlopen failed: "/data/app/com.xiaoyutimes.carloanonline-2/lib/arm/libc++_shared.so" .dynamic section header was not found

only happen on HUAWEI CAZ AL10 by now

![UK$ZKDZS@VM%X5@ OGNY%F4](https://user-images.githubusercontent.com/20613737/58771783-9201a900-85e8-11e9-9af8-93e3f66127ff.png)

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/android_advance_cn#%E8%87%AA%E5%AE%9A%E4%B9%89-library-loader

**Comment by imxy** [comment]
> https://github.com/Tencent/MMKV/wiki/android_advance_cn#%E8%87%AA%E5%AE%9A%E4%B9%89-library-loader

but the device is Android 7.0，is the same solution？

**Comment by imxy** [comment]
but the device is Android 7.0，is the same solution？
@lingol

**Comment by lingol** [comment]
Try that first.
Also you might consider using `com.tencent.mmkv-static:1.0.19`, avoiding the dependency of libc++_shared.

**Comment by imxy** [comment]
ok，thanks @lingol

**Comment by andyhaha** [comment]
java.lang.UnsatisfiedLinkError
dlopen failed: "/data/app/com.xxx.yyy-rfEohkeeqMnQNmAd2i9SFQ==/lib/arm/libc++_shared.so" has bad ELF magic: 00000000

I also meet the same problem on device HUAWEI mate20, android 10.0.

**Comment by lingol** [comment]
> java.lang.UnsatisfiedLinkError
> dlopen failed: "/data/app/com.xxx.yyy-rfEohkeeqMnQNmAd2i9SFQ==/lib/arm/libc++_shared.so" has bad ELF magic: 00000000
> 
> I also meet the same problem on device HUAWEI mate20, android 10.0.

And the solution is the same. Use statically linked mmkv.  `com.tencent.mmkv-static:1.1.1`
In fact, that's the **default** on readme & wiki now.
