### ISSUE TITLE
input is not valid Modified UTF-8: illegal continuation byte 0x4

### ISSUE THREAD

**Issue by Haoxiqiang** [Tencent/MMKV#274]
### The language of MMKV

> Java

### The version of MMKV

> v1.0.20

### The platform of MMKV

> Android

### The installation of MMKV

> Git clone

### What's the issue?

```
A/zygote: runtime.cc:531] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0x4
A/zygote: runtime.cc:531]     string: '559746815753_7��{"action":"recommend","otype":"'
A/zygote: runtime.cc:531]     input: '0x35 0x35 0x39 0x37 0x34 0x36 0x38 0x31 0x35 0x37 0x35 0x33 0x5f 0x37 0xc3 <0x04> 0xc1 0x04 0x7b 0x22 0x61 0x63 0x74 0x69 0x6f 0x6e 0x22 0x3a 0x22 0x72 0x65 0x63 0x6f 0x6d 0x6d 0x65 0x6e 0x64 0x22 0x2c 0x22 0x6f 0x74 0x79 0x70 0x65 0x22 0x3a 0x22'
A/zygote: runtime.cc:531]     in call to NewStringUTF
A/zygote: runtime.cc:531]     from java.lang.String[] com.tencent.mmkv.MMKV.allKeys()
```

### More

This is the cache file.

[mmkv's file.zip](https://github.com/Tencent/MMKV/files/3259792/mmkv.s.file.zip)

You can reproduce the crash with the cache file.

**Comment by lingol** [comment]
What key do you use? Is it valid utf-8?

**Comment by Haoxiqiang** [comment]
No.In the most time,It works well.but you can get the crash in the order and it will crash when the mmkv's init.

* run the app and write some key-values.
* force kill the process.
* repeat and may be you can get it.

**Comment by lingol** [comment]
I believe your MMKV file is corrupted, somehow the crc checksum didn't report any error.

**Comment by lingol** [comment]
More importantly is, how did you create such corrupted MMKV file? 
Can you make it reproducible?

**Comment by Haoxiqiang** [comment]
Yeah. We have try many times and many devices.We can reproduce the crash.But It's very strange.
We build the mmkv's so in  the v1.0.20 tag.

* run the app and write some key-values. must use the v1.0.20
* force kill the process.
* repeat and may be you can get it.

**Comment by lingol** [comment]
Send me a reproducible demo project, please. guoling@tencent.com

**Comment by lingol** [comment]
And do you find anything interesting in the MMKV's log, just before that force kill & crash happened?

**Comment by Haoxiqiang** [comment]
ok.I will create a reproducible demo as soon as possible.

**Comment by lingol** [comment]
I found the issue. It's a bug intruded in v1.0.20. Will fix as soon as possible.

**Comment by Haoxiqiang** [comment]
Ok.Please let me know that if you want more detail.

**Comment by lingol** [comment]
Fixed in [hotfix_fast_remove](https://github.com/Tencent/MMKV/tree/hotfix_fast_remove) branch.

**Comment by lingol** [comment]
Apparently there's still a bug in v1.0.21. It's recommended that you should upgrade to v1.0.22.

**Comment by Haoxiqiang** [comment]
@lingol I have use the v1.0.22 about 7 days. I think you have resolve the problem.I have change my code: Always retain at least one key and no crash happened.

**Comment by lingol** [comment]
Well...You might consider remove such _protection_ sometime later.😂

**Comment by Haoxiqiang** [comment]
> Well...You might consider remove such _protection_ sometime later.😂

I should say a little more in detail:

In the last two weeks,I have try the mmkv without any protection that in the about 10k users in the first week.(others user in v1.0.19, because the 20 and 21 have a serious bug ) . I think 22 you have fixed the bug and I replace the  MMKV.encodeString  with MMKV.encodeParcelable and keep retain at least one key for some millions in the second week.
there is nothing happed.

**Comment by Haoxiqiang** [comment]
I will try remove the retain key strategy in the next week.
Are they equivalent MMKV.encodeString and MMKV.encodeParcelable ?

**Comment by lingol** [comment]
NO, that's not the same.

**Comment by lingol** [comment]
> NO, that's not the same.

In fact, this bug has nothing to do with `MMKV.encodeString`. Switching to `MMKV.encodeParcelable` will slow down encode/decode speed a little bit.
