### ISSUE TITLE
iOS版 v1.0.21 无法持久化

### ISSUE THREAD

**Issue by ctinusDev** [Tencent/MMKV#277]
### The language of MMKV

> e.g. Objective-C

### The version of MMKV

> e.g. v1.0.21

### The platform of MMKV

> e.g. iOS

### The installation of MMKV

> e.g. Cocoapods

### What's the issue?
MMKV无法持久化，下面的代码最终取到的currentProfileModel是nil。

        if (![[MMKV defaultMMKV] setObject:self.currentProfileModel forKey:kMMKVCurrentProfileKey]) {
            SKLogError(@"当前用户信息保存失败");
        }
        [[MMKV defaultMMKV] clearMemoryCache];
        SKProfileModel *currentProfileModel = [[MMKV defaultMMKV] getObjectOfClass:SKProfileModel.class forKey:kMMKVCurrentProfileKey];

**Comment by lingol** [comment]
How is your `SKProfileModel` implemented? Can we see it? Does it implement `<NSCoding>` properly?

**Comment by lingol** [comment]
Oh I see. Yet another bug.

**Comment by lingol** [comment]
Release with v1.0.22. Sorry for the inconvenience.
