### ISSUE TITLE
支持数据监听吗？

### ISSUE THREAD

**Issue by yimigao** [Tencent/MMKV#28]
日常开发经常会遇到对存储数据变化监听，mmkv支持数据监听吗？

**Comment by ysbing** [comment]
I suggest you can use ViewModule

**Comment by lingol** [comment]
No. MMKV doesn't support data-change observer/listener by design.
As ysbing has [suggested](https://github.com/Tencent/MMKV/issues/28#issuecomment-424219167), you can use ViewModule or something else to trigger an event after you change the data.

**Comment by as11051105** [comment]
room+ViewModule

**Comment by langzuxiaozi** [comment]
建议支持数据监听,安卓需要跨进程监听数据变化,我自己是用getContentResolver实现的跨进程 sp

**Comment by lingol** [comment]
MMKV does not and will not support data-change observer/listener.
And this is by design.

You're very welcome to wrap one on top of MMKV, if such feature is so crucial to you.
