### ISSUE TITLE
Android Native crash

### ISSUE THREAD

**Issue by wang-xiong** [Tencent/MMKV#280]
### The language of MMKV
Java
### The version of MMKV
v1.0.19
### The platform of MMKV
Android
### The installation of MMKV
Maven
### What's the issue?
java.lang.UnsatisfiedLinkError: Native method not found: com.tencent.mmkv.MMKV.encodeLong:(JLjava/lang/String;J)Z
    com.tencent.mmkv.MMKV.encodeLong(Native Method:0)
    com.tencent.mmkv.MMKV.putLong(MMKV.java:585)

**Comment by lingol** [comment]
Try v1.0.22 & [ReLinker](https://github.com/Tencent/MMKV/wiki/android_advance_cn#%E8%87%AA%E5%AE%9A%E4%B9%89-library-loader).
