### ISSUE TITLE
概率性的出现获取已保存的数据为空（1/10）排除了逻辑上的覆盖，且出现了CRC校验失败的Log

### ISSUE THREAD

**Issue by HanselLi** [Tencent/MMKV#281]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

java

### The version of MMKV

> e.g. v1.0.22

### The platform of MMKV

> e.g. Android
android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
maven

### What's the issue?

> Post the outputs or screenshots for errors.
> just a simple logic about save first install time ,and then load the long type timestamps with mmkv, unfortunately, loaded long timestamps may probability be 0L , about 1/10 . meantime , i found the mmkv log like this  == E/MMKV: <MMKV.cpp:985::checkFileCRCValid> check crc [xxx_mmap_id] fail, crc32:1973263984, m_crcDigest:3447641212 , I tried use MMKVHandler 's implement method and return strategy "MMKVRecoverStrategic.OnErrorRecover" recover mode , it works . But in wiki  it says that this recover mode not guarantee 100 percent works well and may cause weird error . So it confused me . There 's any solution about this ? Thanks
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
Send me a demo project that can make that can **reproduce such 1/10 failure**.

**Comment by lingol** [comment]
Hi, you still there? @HanselLi

**Comment by HanselLi** [comment]
I tried write some demo using mmkv . but the phenomenon of loading data failed do not occur again , just occurred in my project . Maybe it is coursed by error use or  config mmkv in a wrong way . i 'll check my project more detail . if any questions , can i just continue communicate with you on this board ? thanks .

**Comment by lingol** [comment]
Is it possible that you open that MMKV in multi-process without setting `MULTI_PROCESS_MODE`?
You can try open with that flag, and see if that error happen again.

**Comment by HanselLi** [comment]
i check the mmkv config is correct in project  . and the quote from wiki  "考虑到文件系统、操作系统都有一定的不稳定性，我们另外增加了 crc 校验，对无效数据进行甄别。在 iOS 微信现网环境上，我们观察到有平均约 70万日次的数据校验不通过" .  how your app deal with this condition when crc check failed , just use mmkvHandler 's onErrorRecover mode ?

**Comment by HanselLi** [comment]
btw the phenomenon crc check failed jsut occurred frequently  in device MotoXT-1789-05 , by far ,other device works fine .

**Comment by lingol** [comment]
We just drop everything when shit happens.

**Comment by lingol** [comment]
However, that 70w/day is considerable low. Your 1/10 is quite unacceptable, something must be wrong.

**Comment by tangxiangpi** [comment]
> We just drop everything when shit happens.

是将mmap文件内容清空？

**Comment by lingol** [comment]
> > We just drop everything when shit happens.
> 
> 是将mmap文件内容清空？

`MMKVRecoverStrategic.OnErrorDiscard`

**Comment by HanselLi** [comment]
i 've send the demo file via email to you , pls kindly help me  review ,thanks a lot

**Comment by lingol** [comment]
There's nothing to see. Show your log when that error happens, both before & after.

**Comment by HanselLi** [comment]
error log had been send to your email

**Comment by lingol** [comment]
> Is it possible that you open that MMKV in multi-process without setting `MULTI_PROCESS_MODE`?
> You can try open with that flag, and see if that error happen again.

Looks like that's the exact problem.
