### ISSUE TITLE
Is there any negative side-effect if calling MMKV.initialize multiple times?

### ISSUE THREAD

**Issue by fvdcx** [Tencent/MMKV#282]
Like calling it in Application.onCreate() and Activity.onCreate() simultaneously

@lingol

**Comment by lingol** [comment]
Just don't do this.

**Comment by fvdcx** [comment]
@lingol 
However, as the doc said, we can initialize MMKV in MainActivity.onCreate()
![image](https://user-images.githubusercontent.com/3365271/59767198-58ad8680-92d4-11e9-97f6-5a30f900315e.png)
I think this means `MMKV.initialize()` will execute every time when activity.onCreate().
Actually in an app's lifecycle, activity.onCreate() can happen many times.

But you were saying that we should not call `MMKV.initialize()`  multiple times?

**Comment by lingol** [comment]
Okey, do it inside Application.onCreate() for that matter.
