### ISSUE TITLE
Call UIApplication in subThread

### ISSUE THREAD

**Issue by reboot-jia** [Tencent/MMKV#284]
### The language of MMKV

> Objective-C

### The version of MMKV

>  v1.0.10

### The platform of MMKV

>  iOS 

### The installation of MMKV

>  Cocoapods

### What's the issue?

<img width="1400" alt="WX20190628-184303@2x" src="https://user-images.githubusercontent.com/47767090/60339957-ce080e00-99dc-11e9-9982-8a999488cd54.png">

**Comment by lingol** [comment]
Fixed in dev branch.

**Comment by lingol** [comment]
Released with [v1.0.23](https://github.com/Tencent/MMKV/releases/tag/v1.0.23).
