### ISSUE TITLE
mmkv和imsdk共同使用，报错：More than one file was found with OS independent path 'lib/x86/libc++_shared.so'

### ISSUE THREAD

**Issue by kingrukawa** [Tencent/MMKV#285]
### The language of MMKV

> Java

### The version of MMKV

> all

### The installation of MMKV

> AAR Package

### What's the issue?

当我同时使用mmkv和imsdk时，引用方式为aar，在构建工程会报错：
More than one file was found with OS independent path 'lib/x86/libc++_shared.so'
我尝试在gradle中使用第一次获取的so库配置

```
packagingOptions {
        //mmkv和imsdk有so冲突
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
}
```

虽然可以打包了，但是运行时，找不到imsdk.so文件了

我看到这两个aar中包含的so库都存在这个libc++shared.so，但是我不知道通过gradle依赖aar的方式如何移除其中的so文件，希望得到帮助

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/android_setup_cn#%E5%AE%89%E8%A3%85%E5%BC%95%E5%85%A5
