### ISSUE TITLE
MemoryFile.mm read data may return wrong result

### ISSUE THREAD

**Issue by chenzhengxu** [Tencent/MMKV#286]
L168 in `MemoryFile.mm` should replace `return nil` with `return data`

[source code](https://github.com/Tencent/MMKV/blob/master/iOS/MMKV/MMKV/MemoryFile.mm#L145-L168)

**Comment by lingol** [comment]
Yeah, that code is never called. In fact, that just some code for features that's on plan, but never get the time to fully implement, aka `big file support`.
