### ISSUE TITLE
Eclipse 怎么使用MMKV？

### ISSUE THREAD

**Issue by haishuang** [Tencent/MMKV#287]
在Android Studio上可以用依赖的方式引入MMKV，但是由于一些历史原因，这边项目还在Eclipse上维护，想要使用MMKV，请问是否有x.jar/x.aar架包提供呢？

**Comment by lingol** [comment]
You can just download the latest aar file from jCenter.
For instance, the [com.tencent.mmkv-static](https://bintray.com/bintray/jcenter?filterByPkgName=com.tencent%3Ammkv-static).
