### ISSUE TITLE
Wrong use of AES_CFP can result in ciphertext and key can be recoverd

### ISSUE THREAD

**Issue by edwardz246003** [Tencent/MMKV#288]
### What's the issue?
MMKV use AES_CFP for encryption.  However, it is not used according to the standard (the IV should be unique and unpredictable). In the lastest version. It initialize the IV (m_vector) as the key (m_key).

https://github.com/Tencent/MMKV/blob/master/iOS/MMKV/MMKV/aes/AESCrypt.mm#L27-L35

AESCrypt::AESCrypt(const unsigned char *key, size_t keyLength) {
	if (key && keyLength > 0) {
		memcpy(m_key, key, (keyLength > AES_KEY_LEN) ? AES_KEY_LEN : keyLength);
		memcpy(m_vector, m_key, AES_KEY_LEN);

		int ret = openssl::AES_set_encrypt_key(m_key, AES_KEY_BITSET_LEN, &m_aesKey);
		assert(ret == 0);
	}
}

Then use the IV (m_vector) directly for encryption, and decryption.

https://github.com/Tencent/MMKV/blob/master/iOS/MMKV/MMKV/aes/AESCrypt.mm#L48-L60

void AESCrypt::encrypt(const unsigned char *input, unsigned char *output, size_t length) {
	if (!input || !output || length == 0) {
		return;
	}
	openssl::AES_cfb128_encrypt(input, output, length, &m_aesKey, m_vector, &m_number, AES_ENCRYPT);
}

An active attack  can use this vunlerbility to recover ciphertext and key of MMKV.

Credits:
 Zhiniang Peng of Qihoo 360 Core Security.

**Comment by lingol** [comment]
Yes, that's one potential security leak we knew when MMKV for Android is first designed.
The problem of random IV, is that if it's totally random, how does MMKV decrypt the file on App restart?

**Comment by lingol** [comment]
Just out of cruise, how does the attacher recover the key of MMKV exactly?

**Comment by edwardz246003** [comment]
According to the standard, IV should be save as part of cipertext. So you can decrypt the file when app restart.

As for how attacker recover the key of MMKV.
    At first, the IV should be publish in aes_cfp. Which means key been published here. However, IV keep secret in this project, so ,it will not be the problem.
   But if an attacker can do chosen ciphertext attack he can recover IV by padding oracle (CCA attack)
   Another problem is that if you use the same IV for all the cipertext. Then the same plaintext will result in same ciphertext. This will make aes_cfp lose the IND_CPA security. Make is vunlerable to CPA attack.

**Comment by edwardz246003** [comment]
According to the standard, IV should be save as part of cipertext. So you can decrypt the file when app restart.

As for how attacker recover the key of MMKV.
At first, the IV should be publish in aes_cfp. Which means key will be published here. However, IV keep secret in this project, so ,it will not be the problem. 
But if an attacker can do chosen ciphertext attack he can recover IV by using padding oracle (CCA attack)
Another problem is that if you use the same IV for all the cipertext. Then the same plaintext will always result in same ciphertext. This will make aes_cfp lose the IND_CPA security. This make it vunlerable to CPA attack.

**Comment by lingol** [comment]
Okey, both attacks are theoretically possible, if not likely happen on a file-storage encryption.
I will think about using a random IV & storing somewhere.
Thanks for your input.

**Comment by passerbyloo** [comment]
and for the `CFP` mode, maybe the `IV` no need unpredictable, just unique is ok.

**Comment by lingol** [comment]
> and for the `CFB` mode, maybe the `IV` no need unpredictable, just unique is ok.

That's good to know.

**Comment by lingol** [comment]
Fixed in dev branch. Will come out in next release, with other bug fixes or features(if any).

**Comment by lingol** [comment]
Released with [v1.0.23](https://github.com/Tencent/MMKV/releases/tag/v1.0.23).
