### ISSUE TITLE
iOS版 1.0.22 无法持久化存储

### ISSUE THREAD

**Issue by YuXilong** [Tencent/MMKV#289]
### The language of MMKV

 Objective-C

### The version of MMKV

 v1.0.22

### The platform of MMKV

iOS

### The installation of MMKV

 Cocoapods

### What's the issue?

iOS version cannot be persisted storage

**Comment by lingol** [comment]
That's simply impossible. Show me your code, aka a reproducible demo project to guoling@tencent.com.

**Comment by YuXilong** [comment]
Sorry, there is a problem with the code logic of another of us.
