### ISSUE TITLE
同时集成Mars 和 MMKV 运行程序闪退

### ISSUE THREAD

**Issue by huapeng222** [Tencent/MMKV#292]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Java 安卓

### The version of MMKV

> e.g. v1.0.10

v1.0.22

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone
Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

项目中集成了mars,然后现在我开始集成mmkv,
最开始使用

> implementation 'com.tencent:mmkv:1.0.22'

编译报错
> More than one file was found with OS independent path 'lib/armeabi/libc++_shared.so'

然后根据android_setup_cn 修改使用static
> implementation 'com.tencent:mmkv-static:1.0.22'

成功编译,但是运行起来闪退
报错
> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/base.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_resources_apk.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/lib/arm64, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/base.apk!/lib/arm64-v8a, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.x com.aa iaozhi-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.aa-40n3ckncbUirRHcZo3BLrw==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libc++_shared.so"

浏览lssue ,找到类似的[问题](https://github.com/Tencent/MMKV/issues/285),
解决方案,是该为使用static的库,但我的问题依旧

以下是我的部分配置

``` ext.supportLibVersion = '27.1.1'

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support:cardview-v7:23.1.1'
    implementation "com.android.support:design:${supportLibVersion}"
    implementation "com.android.support:recyclerview-v7:${supportLibVersion}"
    implementation "com.android.support:appcompat-v7:${supportLibVersion}"
    implementation 'com.tencent.mars:mars-core:1.2.2'
    implementation 'com.google.protobuf:protobuf-java:2.6.1'
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    implementation 'com.zhihu.android:matisse:0.5.2-beta1'
    implementation 'com.makeramen:roundedimageview:2.3.0'
    implementation 'com.tencent:mmkv-static:1.0.22'

}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '27.1.1'
            }
        }
    }
}
```

mars 集成初始化
```
@Override
  public void onCreate() {
    super.onCreate();
    sContext = this;
    sUser = getUser();
    sAddr = getAddr();
    sToken = getToken();
    sBots = getBots();



    if (!isFirstTimeLogin() && !sConnected) {
      init();

    }




  }

static void init() {


    System.loadLibrary("c++_shared");
    System.loadLibrary("marsxlog");
    openXlog();

    MarsCallback callback = new MarsCallback();
    AppLogic.setCallBack(callback);
    StnLogic.setCallBack(callback);
    SdtLogic.setCallBack(callback);

    Mars.init(sContext, new Handler(Looper.getMainLooper()));

    StnLogic.setLonglinkSvrAddr(getHost(), new int[]{getPort()});
    StnLogic.setClientVersion(200);
    Mars.onCreate(true);
    BaseEvent.onForeground(true);

    StnLogic.makesureLongLinkConnected();
    StnLogic.keepSignalling();
  }

```

**Comment by lingol** [comment]
Remove those mars init logic and see if such crash happens
>    System.loadLibrary("c++_shared");
>    System.loadLibrary("marsxlog");
>    openXlog();
>
>    MarsCallback callback = new MarsCallback();
>    AppLogic.setCallBack(callback);
>    StnLogic.setCallBack(callback);
>    SdtLogic.setCallBack(callback);
>
>    Mars.init(sContext, new Handler(Looper.getMainLooper()));
>
>    StnLogic.setLonglinkSvrAddr(getHost(), new int[]{getPort()});
>    StnLogic.setClientVersion(200);
>    Mars.onCreate(true);
>    BaseEvent.onForeground(true);
>
>    StnLogic.makesureLongLinkConnected();
>    StnLogic.keepSignalling();

If no crash, then there's something wrong with your mars configuration & init logic, nothing todo with MMKV I believe.

**Comment by lingol** [comment]
Also, you might consider invalid Android Studio's cache & do a clean build.

**Comment by huapeng222** [comment]
Thank you for your reply.
I solved the problem at your prompt.

https://github.com/Tencent/mars/issues/164
