### ISSUE TITLE
a design question about using NSMutableDictionary to manager all mmkv

### ISSUE THREAD

**Issue by yuman07** [Tencent/MMKV#294]
### The language of MMKV

Objective-C

### The version of MMKV

1.0.22

### The platform of MMKV

iOS

### The installation of MMKV

Cocoapods

### What's the issue?

我注意到MMKV使用g_instanceDic这个NSMutableDictionary来持有所有mmkv。但是这就造成了所有mmkv都被g_instanceDic强持有了。如果某个使用方认为之后不再使用某个mmkv，必须自己手动调用'close'这个方法来释放资源。
但是，通常情况下，一个mmkv有多个使用方，某个使用方不用，但他并不知道其它使用方还用不用。因此，很难找到一个合适的使用方或者时机来调用这个'close'操作，因为多个使用方之间是不知道其他人还用不用的。
貌似使用NSMapTable能解决这个问题，保存对所有mmkv的弱引用，这样当mmkv的所有使用方都释放其持有的mmkv时，该mmkv可以在其delloc中释放相关资源，这样就解决了这个找不到合适close时机的问题。

所以我的问题是：
1 为什么使用NSMutableDictionary来持有所有mmkv，当时这样设计的考虑？
2 对于这样多个使用方使用同一个mmkv，需要合适时机close的问题，有什么好的建议?

**Comment by lingol** [comment]
>1 为什么使用NSMutableDictionary来持有所有mmkv，当时这样设计的考虑？

Consider this: There's only one user, who doesn't keep nor retain MMKV instances, just get one when needed (just like they did with NSUserDefaults). Now there will be frequently init & close operation, which is unacceptable.

>2 对于这样多个使用方使用同一个mmkv，需要合适时机close的问题，有什么好的建议?

Why not just let MMKV alone? Why do you have to close it? Did you have problems without closing MMKV?

**Comment by yuman07** [comment]
> > 1 为什么使用NSMutableDictionary来持有所有mmkv，当时这样设计的考虑？
> 
> Consider this: There's only one user, who doesn't keep nor retain MMKV instances, just get one when needed (just like they did with NSUserDefaults). Now there will be frequently init & close operation, which is unacceptable.
> 
> > 2 对于这样多个使用方使用同一个mmkv，需要合适时机close的问题，有什么好的建议?
> 
> Why not just let MMKV alone? Why do you have to close it? Did you have problems without closing MMKV?

因为如果不关闭，相关资源就无法释放。这样一个不再使用mmkv却一直占用内存资源，显然不合理。对于全局的defaultMMKV，这倒还好，因为它时刻可能被用到。但是对于某个模块自己的mmkv，不使用时却一直占用内存显然不太好

**Comment by lingol** [comment]
If it's only used in one module, I'm sure there's some place you can find an reasonable way to safely close it. And if that place & time is hard to find, then maybe it's not suitable to close it at first place.

Besides, MMKV does have some cleanup logic inside, aka clear all memory & file usage on memory warning. I don't think you should worry.

Premature optimization is the root of all evil.
