### ISSUE TITLE
1.0.22版本,编译错误:undeclared identifier '__ANDROID_API_L__'

### ISSUE THREAD

**Issue by mengsanye** [Tencent/MMKV#296]
### The version of MMKV

> v1.0.22

### The platform of MMKV

> Android

### What's the issue?
编译环境：
- Mac, AndroidStudio3.4.2, NDKr14b, 
- 其他配置如gradle, android gradle plugin版本和源代码保持一致

编译1.0.22版本代码，编译发生如下错误
```
native-bridge.cpp:37:21: error: use of undeclared identifier '__ANDROID_API_L__'
int g_android_api = __ANDROID_API_L__;
```

**Comment by lingol** [comment]
Use NDKr16b.
