### ISSUE TITLE
对象操作怎么修改里面的数据，set再去get返回是空的

### ISSUE THREAD

**Issue by douya40** [Tencent/MMKV#297]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android
Android
对象操作怎么修改里面的数据，set再去get返回是空的

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
Run the demo project for example usage.
