### ISSUE TITLE
__FILE__在不同平台的取值问题

### ISSUE THREAD

**Issue by lockupwqe** [Tencent/MMKV#298]
windows下面使用cmake编译时__FILE__的取值是这样的：
F:\dev\MMKV-master\Android\MMKV\mmkv\src\main\cpp\MMKV.cpp

如果使用代码中的方式去获取文件名取到的是野指针：
#define __filename__ (strrchr(__FILE__, '/') + 1)”

那么在log打印那里就会出现异常， file这个值有问题：
 __android_log_print(MMKVLogLevelDesc(level), APPNAME, "<%s:%d::%s> %s", file, line,
                                func, message.c_str());

是否可以采用这种方式：
#define __filename__  (strrchr(__FILE__, '/') ? strrchr(__FILE__, '/') + 1 : __FILE__)

**Comment by lingol** [comment]
A good advise. Thank you.

**Comment by lingol** [comment]
Supported with [commit](https://github.com/Tencent/MMKV/commit/8bffb6c9d5ddb0e761c44b0fef04860c785e2967#diff-a33a3a86ff20c84ce5168e236f78848e) on dev branch.

**Comment by lingol** [comment]
Released with [v1.0.23](https://github.com/Tencent/MMKV/releases/tag/v1.0.23).
