### ISSUE TITLE
保存一个对象，过了几天去使用发现对象里面的值变成空！

### ISSUE THREAD

**Issue by douya40** [Tencent/MMKV#300]
保存一个对象，过了几天去使用发现对象里面的值变成空！是不是一个大BUG呢

**Comment by lingol** [comment]
NO. I don't think there's such bug inside MMKV. Have you check these possibilities?

1. The file is deleted.
2. The key is deleted.
3. The file is corrupted.

**Comment by zyyoona7** [comment]
我也遇到过类似的问题，还在排查~我的是整个 MMKV 的缓存文件夹都消失了，没有写过任何删除操作相关的代码，很难复现~

**Comment by douya40** [comment]
如何进行相关检查呢

**Comment by lingol** [comment]
Logs is a very helpful tool for analyzing bugs. Make a log on every important operation. Diagnose them when shit happens.
