### ISSUE TITLE
g_instanceLock的初始化问题

### ISSUE THREAD

**Issue by wuyunpeng163** [Tencent/MMKV#301]
想问个问题:mmkv的g_instanceLock是静态变量，进程运行时，会自动构造一遍。为什么在InitializeMMKV里面g_instanceLock = ThreadLock()能够去掉这句嘛?

**Comment by lingol** [comment]
There are several calls of `pthread_mutexXXX()` inside `ThreadLock ()`. I'm not quite sure if it's ok to call them on global initialization procedure. So just call it again to make sure things works.

**Comment by wuyunpeng163** [comment]
不好意思，可能我没讲明，是在PC端的源码ThreadLock使用的是CRITICAL_SECTION，但是此对象，msdn上表明A critical section object cannot be moved or copied. 因为如果operator=的话，可能会导致一些不可预料的情况。我在xin7物理机环境中以及winxp虚拟机环境上，调试发现，g_instanceLock = ThreadLock()后，在g_instanceLock 的析构函数中DeleteCriticalSection会出现失败，抛出异常的情况。(win7物理环境偶然会出现，而winxp虚拟机环境一直会出现这种情况。)去掉这句话之后，一切正常，所以我怀疑直接operator=，是出问题的原因。不知道我的想法对不对?

**Comment by wuyunpeng163** [comment]
调用方式是，在dll中使用mmkv的静态lib

**Comment by lingol** [comment]
Okay, I'll look into it later next week.

**Comment by lingol** [comment]
Fixed on dev branch with [commit](https://github.com/Tencent/MMKV/commit/42234688ba42d0ecde4e19c224f57676fea68456).

**Comment by lingol** [comment]
Released with [v1.0.23](https://github.com/Tencent/MMKV/releases/tag/v1.0.23).
