### ISSUE TITLE
Api doc

### ISSUE THREAD

**Issue by fghjhuang** [Tencent/MMKV#303]
我好像没有找到MMKV的所有api的document，不知道在哪里呢？源码里面没看到，里面有些方法我想看详细的api说明，例如cleanAll，用key去加密数据等等接口

**Comment by lingol** [comment]
No, this no such thing as classical API documentation for MMKV.

**Comment by lingol** [comment]
Docs for encryption is added now. 
[iOS](https://github.com/Tencent/mmkv/wiki/iOS_tutorial_cn#%E5%8A%A0%E5%AF%86), [Android](https://github.com/Tencent/mmkv/wiki/android_advance_cn#%E5%8A%A0%E5%AF%86).

**Comment by fghjhuang** [comment]
thanks！
