### ISSUE TITLE
序列化对象导致出错

### ISSUE THREAD

**Issue by chengsewennuan** [Tencent/MMKV#304]
### The language of MMKV

> Java, or Kotlin
### The version of MMKV

>  v1.0.10
### The platform of MMKV

>  Android
### The installation of MMKV

>  Maven
### What's the issue?

> java.lang.IllegalStateException: source.readParcelable<Ba…::class.java.classLoader) must not be null
> 
> encode 一个序列化对象，当重新修改序列化对象，删除某些数据后导致程序Crash。
>错误提示依旧读取被删除的旧的属性

**Comment by lingol** [comment]
Show your example code.
