### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by guaixiangjieke** [Tencent/MMKV#305]
### The language of MMKV
java

### The version of MMKV
implementation 'com.tencent:mmkv:1.0.22'

### The platform of MMKV

Android

### What's the issue?

java.lang.NullPointerException
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
com.tencent.mmkv.MMKV.onMMKVCRCCheckFail(MMKV.java:5)
com.tencent.mmkv.MMKV.getMMKVWithID(Native Method)
com.tencent.mmkv.MMKV.c(MMKV.java:2)

**Comment by lingol** [comment]
How about don't return null inside `onMMKVCRCCheckFail()` of your `MMKVHandler` implementation?

**Comment by lingol** [comment]
Protected with [commit](https://github.com/Tencent/MMKV/commit/30ce8413e8ea032682c47efbab41035d3b0eb1aa) on dev branch, anyway.
