### ISSUE TITLE
iOS 不支持 `AppGroup`？

### ISSUE THREAD

**Issue by GitHubZHH** [Tencent/MMKV#306]
比如希望在主项目与 `TodayExtension` 中共用数据。

**Comment by lingol** [comment]
Not supported yet.

**Comment by demoker** [comment]
mmkv 现在已经支持AppGroup了对吧？@lingol
NSString *myGroupID = @"group.company.mmkv";
// the group dir that can be accessed by App & extensions
NSString *groupDir = [[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:myGroupID].path;
[MMKV initializeMMKV:nil groupDir:groupDir logLevel:MMKVLogInfo];

**Comment by lingol** [comment]
@demoker Read the wiki. https://github.com/Tencent/MMKV/wiki/iOS_tutorial_cn
>如果你需要多进程访问(在主 App 与 Extension 之间)，那么需要在初始化时设置 [group directory](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_application-groups?language=objc):
>```objective-c
>NSString *myGroupID = @"group.company.mmkv";
>// the group dir that can be accessed by App & extensions
>NSString *groupDir = [[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:myGroupID].path;
>[MMKV initializeMMKV:nil groupDir:groupDir logLevel:MMKVLogInfo];
>```
