### ISSUE TITLE
大文件支持，需要考虑哪些问题？

### ISSUE THREAD

**Issue by Jonwei** [Tencent/MMKV#307]
看到项目正在开发支持大文件。想了解一下，项目支持大文件，目前在考虑哪些问题？多大文件，会考虑新增文件？

**Comment by lingol** [comment]
Actually that improvement is on hold. Many things to be considered when large key-values stored inside(10M+).

1. Cacheing all key-values in memory might not be acceptable.
2. Loading all key-values will be very slow.
3. Full write back will be very slow.
