### ISSUE TITLE
lib/arm/libmmkv.so" has bad ELF magic

### ISSUE THREAD

**Issue by stayinxing** [Tencent/MMKV#308]
### The language of MMKV

JAVA

### The version of MMKV

 implementation 'com.tencent:mmkv-static:1.0.22'

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?

Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.XXX.XXX-8qI5vAWCWtuoUxtVUtu2ZQ==/lib/arm/libmmkv.so" has bad ELF magic
at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
at java.lang.System.loadLibrary(System.java:1660)
at com.tencent.mmkv.MMKV.initialize(MMKV.java:85)
at com.tencent.mmkv.MMKV.initialize(MMKV.java:68)

有一台华为P9的用户，无法打开App。但不是所有的华为P9都无法打开，只碰到这一个用户。

设备： 华为 EVA-AL10

系统版本：  Android 8.0.0

CPU指令集：ARMV7

ndk {
abiFilters "armeabi"
}

**Comment by stayinxing** [comment]
华为P9的用户打开App，无限崩溃。
    ndk {
            abiFilters "armeabi"
        }

**Comment by lingol** [comment]
I don't know for sure. But it looks like has nothing to do with MMKV. 
Maybe you should go check somewhere else, such as `abiFilters` and device CPU type, etc.

**Comment by guowuque** [comment]
@stayinxing  请问下这个问题有解决么

**Comment by rahul-mahato11** [comment]
@stayinxing 
Has this been resolved ? 
If yes could you mention the steps?

**Comment by kaitian521** [comment]
use https://github.com/KeepSafe/ReLinker to load libmmkv.so
```
public static String initialize(Context context, LibLoader loader) {
}
```

**Comment by rahul-mahato11** [comment]
mine is bad ELF magic
dlopen failed: "/data/app/~~KLnTaxf5MpeWw5efuwuf7A==/com.package.name==/lib/arm64/libmmkv.so" has bad ELF magic: 00000000

**Comment by kaitian521** [comment]
1、check your build.gradle，make sure add support of  all devices for your users
```
ndk {
    abiFilters "armeabi-xxx"
}
```
2、use Renlinker
3、 if 1 & 2 does not work, let it go

**Comment by 330132662** [comment]
> use https://github.com/KeepSafe/ReLinker to load libmmkv.so
> 
> ```
> public static String initialize(Context context, LibLoader loader) {
> }
> ```

 nice  bro
