### ISSUE TITLE
切换MMKV实例

### ISSUE THREAD

**Issue by fghjhuang** [Tencent/MMKV#309]
初始化:
`
MMKV.initialize(this);
MMKV mmkv = MMKV.mmkvWithID("MyID1");`
然后有需求需要切换其他的实例可否用同一个变量？
`mmkv=MMKV.mmkvWithID("MyID2");
..dosomething...
mmkv=MMKV.mmkvWithID("MyID3");
...dosomething...
`
这样来实现切换不同的业务之间存储
这样写可以吗？

**Comment by lingol** [comment]
Yes that it's totally ok. Although I don't recommend using the same variable for different instances. It may confuse others who read the code later.
