### ISSUE TITLE
我的app是集成在/system/app目录下，但是加载不了so文件

### ISSUE THREAD

**Issue by ANDROID-S** [Tencent/MMKV#310]
Process: com.xxx.xxx, PID: 4007
    java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/data/com.xxx.xxx/app_lib/libc++_shared.so" segment 0: Permission denied
        at java.lang.Runtime.load0(Runtime.java:928)
        at java.lang.System.load(System.java:1633)
        at nn.b(SourceFile:29)
        at nm.d(SourceFile:204)
        at nm.a(SourceFile:136)
        at nl.a(SourceFile:70)
        at nl.a(SourceFile:51)
        at com.xxx.xxx.CardApplication$1.loadLibrary(SourceFile:95)
        at com.tencent.mmkv.MMKV.initialize(SourceFile:78)

**Comment by ANDROID-S** [comment]
使用ReLinker也不行，android9.0系统

**Comment by lingol** [comment]
Why don't you Google a bit before asking questions?
https://blog.csdn.net/carefulboys/article/details/53893567

**Comment by lingol** [comment]
One more thing, if you're developing a system app, I recommend using MMKV by static linking of libc++: `com.tencent.mmkv-static:1.0.22`.

**Comment by ANDROID-S** [comment]
If this is the case, is it necessary to add the so file in the jniLibs of the project?




------------------ 原始邮件 ------------------
发件人: "Guo Ling"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 中午11:09
收件人: "Tencent/MMKV"<MMKV@noreply.github.com>;
抄送: "3601269"<3601269@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Tencent/MMKV] 我的app是集成在/system/app目录下，但是加载不了so文件 (#310)




One more thing, if you're developing a system app, I recommend using MMKV by static linking of libc++: com.tencent.mmkv-static:1.0.22.

**Comment by lingol** [comment]
Google and try yourself.
