### ISSUE TITLE
add a no_log parameter to initialize() for not dumping log messages

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#311]
Thank you for publishing this awesome library. I notice an issue below:

On the Android platform, MMKV will print the following log message when calling initialize()
I/MMKV: <native-bridge.cpp:95::JNI_OnLoad> current API level = 28
I/MMKV: <MMKV.cpp:192::initialize> page size:4096
I/MMKV: <MMKV.cpp:206::initializeMMKV> root dir: /data/user/0/xxxx/app_mmkv

Is there a way to not print messages above? If not, please a "no_log" parameter to initialize() functions.

**Comment by lingol** [comment]
Noted.

**Comment by lingol** [comment]
Supported in dev branch. Just pass `MMKVLogLevel.LevelInfo` on `MMKV.initialize()` to turn off all logging.
Though I don't recommend doing it. Logs are helpful for diagnosing bugs.

**Comment by lingol** [comment]
Released with [v1.0.23](https://github.com/Tencent/MMKV/releases/tag/v1.0.23).
