### ISSUE TITLE
add a onContentChangedByOuterProcess() callback function in MMKV::checkLoadData()

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#313]
On the Android platform, the Java layer won't be notified when an mmkv file content is changed by another process. 

I noticed that the file content changed detection is done in `MMKV::checkLoadData()`.
Would you add a code to call a java callback function (e.g. `onContentChangedByOuterProcess()`) in both `m_metaInfo.m_sequence != metaInfo.m_sequence` and `m_metaInfo.m_crcDigest != metaInfo.m_crcDigest` blocks?

**Comment by lingol** [comment]
Even if  that notification is added, it's not in time. It won't notify when the changes happen, but only when you check for it, either by getting or setting a key-value.
I believe there's some more accurate way to communicate between your processes, using Binder or something else.

**Comment by samlu** [comment]
A "not in time" notification is okay with me. Why I need this is because:
* a UI is displaying the content of the mmkv file
* this mmkv file content may be changed by another process
* when the content is changed, the UI should also update the content
* without the onContentChangedByOuterProcess() notification, we have to use a polling scheme to update the UI. It's time-consuming and may create bad UI experiences to users.
Thanks.

**Comment by lingol** [comment]
If that's the case, it won't be just adding a notify, but also a corresponding `checkSomeThing()` method. To make it not relying on getting or setting kv, and to make things straight forward.

**Comment by samlu** [comment]
Sorry, no idea about what "checkSomeThing()" is.

As to me, we can retrieve the new content of mmkv in onContentChangedByOuterProcess() for updating the UI. It should be good enough for me.

**Comment by lingol** [comment]
`void CheckContentChangedByOuterProcess()`, or simply `void CheckContentChanged()`.

**Comment by samlu** [comment]
Agree. It's peerfect if both `onContentChangedByOuterProcess()` and `CheckContentChanged()` are provided.

**Comment by lingol** [comment]
Added with [commit](https://github.com/Tencent/MMKV/commit/4042e639132adad1d4972f9bb4f57a6df2508345) on `dev` branch.

**Comment by samlu** [comment]
The implementation looks perfect with me. 
Just one suggestion: Can the checkContentChangedByOuterProcess() function returns a boolean value?

**Comment by lingol** [comment]
That will be redundant. Just wait for the callback, tidy & clean.

**Comment by lingol** [comment]
Released with [v1.0.23](https://github.com/Tencent/MMKV/releases/tag/v1.0.23).
