### ISSUE TITLE
OOM问题

### ISSUE THREAD

**Issue by yuxueting** [Tencent/MMKV#318]
### The language of MMKV

>java

### The version of MMKV

> v1.0.19

### The platform of MMKV

>Android

### The installation of MMKV

> AAR Package

### What's the issue?
自从接入MMKV后，OOM暴增，基本都是因为进程内存耗尽导致的。
没有头绪，使用上有一点可能和官方demo不一样。
每次调用encode方法存数据后，都调用了commit，这个会是根本原因吗？

**Comment by lingol** [comment]
You can just remove those `commit()`. MMKV doesn't rely on that, it's just for your convenience of migrating from SP.
As for the OOM, did you store large values inside a single MMKV? ***Large* means 10M+. Avoid that.

**Comment by lingol** [comment]
One more thing, your OOM may not have anything to do with MMKV. To prove that, you can try this: switch back to SP while **keep everything else the same**. Now check again to see if OOM still happens that much.

**Comment by lingol** [comment]
close due to inactive.
