### ISSUE TITLE
如何让mmkv只加载一个架构

### ISSUE THREAD

**Issue by akiraxiao** [Tencent/MMKV#319]
和腾讯X5webview 共用时 64位系统加载不到X5  同时使用mmvk和X5 发现导致无法在64位无法加载X5的库 分析apk发现 原来mmvk默认会加载 
armeabi armeabi-7a arm-v8a x86 x86-64 mips 而X5官方给出的让64位设备已32位运行只是加载 armeabi 同时添加 
ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }
分析X5官方apk发现只加载了armeabi 我的问题是如何让mmvk也只加载armeabi 而其他架构只通过abiFilters 运行

**Comment by lingol** [comment]
I don't quite understand. Would you add some comma`,` and period`。` in your question?
