### ISSUE TITLE
UnsatisfiedLinkError on Android 9

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#322]
Android platform. MMKV v1.0.22
ReLinker.loadLibrary() is used.

I cannot reproduce the following error but I can see it happens on some Android 9 Samsung devices. Any idea what the problem is?

```
Caused by java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mmkv.MMKV.jniInitialize(java.lang.String) (tried Java_com_tencent_mmkv_MMKV_jniInitialize and Java_com_tencent_mmkv_MMKV_jniInitialize__Ljava_lang_String_2)
       at com.tencent.mmkv.MMKV.jniInitialize(MMKV.java)
       at com.tencent.mmkv.MMKV.initialize + 88(MMKV.java:88)
```

**Comment by lingol** [comment]
No idea.

**Comment by lingol** [comment]
Can you get logs of MMKV initialization on those devices?

**Comment by samlu** [comment]
**Samsung, Android 9:** 
SM-G965F, SM-A205G, SM-T830, SM-G965U, SM-A605GN, SM-G950U, SM-N950N, SM-A750FN

**Comment by lingol** [comment]
That won't help. I need logs.

**Comment by lingol** [comment]
https://support.crashlytics.com/knowledgebase/articles/120066-how-do-i-use-logging

**Comment by samlu** [comment]
Most errors are caused by devices failed to load libmmkv.so when apps are installed on the SD card.
You can close this ticket as it looks like the system issue.
