### ISSUE TITLE
Can MMKV fix the ANR ?  

### ISSUE THREAD

**Issue by banana-lina** [Tencent/MMKV#323]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

I’m Na,  I am doing an Android app now, as our app grow more and more big , there are many keys(int, long , string, string set) are put in SharedPreferences file, the SharedPreferences write ANR become our top ANR. Data read/write performance and reliability are both important to us. So there are some questions want to community with you, hope your reply:
•	Does android Wechat also use your library replace all SharedPreferences usage ? Or do you know any product use your library ? 
•	For our product case if it’s suit to user your library ?

**Comment by lingol** [comment]
Already reply your email. Hope it helps.
