### ISSUE TITLE
怎么查询所有的数据(键值对)

### ISSUE THREAD

**Issue by qq2748** [Tencent/MMKV#324]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
get all keys.

**Comment by qq2748** [comment]
有什么工具可以直接看到吗?

**Comment by lingol** [comment]
No such tools.

**Comment by lingol** [comment]
For those still in need of a visualizer, here's an online tool. https://www.mmkv-visualizer.com/
It at least decodes all the keys correctly.
