### ISSUE TITLE
libc++_shared.so 有点大，能按需编译吗

### ISSUE THREAD

**Issue by haizhiyun** [Tencent/MMKV#325]
libc++_shared.so 有点大，能按需编译吗？ 比如mmkv 用到哪些标准库的文件，就编译这些文件就行了，请问能否做到这样？

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
com.tencent.mmkv-static
https://github.com/Tencent/MMKV/wiki/android_setup
