### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by snpmyn** [Tencent/MMKV#327]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Java

### The version of MMKV

> e.g. v1.0.10

v1.0.23

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 只是使用MMKV简单保存、获取几个String数据，在OPPO机型出现内存溢出。使用SP正常。
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
Logs please?

**Comment by snpmyn** [comment]
Sorry, I have no logs this moment.

**Comment by lingol** [comment]
Any logs now?

**Comment by snpmyn** [comment]
> Any logs now?

The application is uninstalled and needs to wait for the next time the bug is triggered.

**Comment by lingol** [comment]
Any updates?

**Comment by snpmyn** [comment]
> Any updates?

Thanks! Recently, it working normally.
