### ISSUE TITLE
crash when MMKV.initialize invoked

### ISSUE THREAD

**Issue by baidengpan** [Tencent/MMKV#329]
### The language of MMKV

> java

### The version of MMKV
>1.0.22

### The platform of MMKV

>Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?
native:
std::__ndk1::char_traits<char>::move(char*, char const*, unsigned int)
std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::operator=(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
MMKV::initializeMMKV(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
mmkv::jniInitialize(_JNIEnv*, _jobject*, _jstring*)

java:
at com.tencent.mmkv.MMKV.jniInitialize(com.tencent.mmkv.MMKV.java:-2)
at com.tencent.mmkv.MMKV.initialize(com.tencent.mmkv.MMKV.java:88)
at com.tencent.mmkv.MMKV.initialize(com.tencent.mmkv.MMKV.java:68)

when i initialize mmkv, it sometimes happens.
wish your response, thanks~
> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
No clue. Have you try print the rootDir passed to MMKV? Does it look like valid utf-8 string?

**Comment by baidengpan** [comment]
Yes,it's valid utf-8.
Maybe i initialize a few times, does it matter? Does this have the chance to  crash?

**Comment by lingol** [comment]
Maybe.

**Comment by baidengpan** [comment]
Okay, i'll have a try to check when initializing and see whether the crash will occur again.
Feedback a few days later.
Thanks.

**Comment by lingol** [comment]
Any updates?
