### ISSUE TITLE
数据自动清除，有时进来app，mmkv的数据没有了

### ISSUE THREAD

**Issue by mytimeshow** [Tencent/MMKV#337]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

**Comment by lingol** [comment]
duplicate with #300

**Comment by mytimeshow** [comment]
解决了，原因是多进程的时候，被初始化多次的问题，现在改为了只在主进程的时候去初始化mmkv就行了，但是我不明白为什么多进程初始化有时候就会清空数据的呢

**Comment by lingol** [comment]
There's no such limitation for MMKV to only initialized in main process. Something is wrong with your usage. Send me a reproducible demo project and I'll check for you. guoling@tencent.com
