### ISSUE TITLE
app crashes caused by memcpy(m_ptr, &actualSize, Fixed32Size) when disk is full

### ISSUE THREAD

**Issue by yubansama** [Tencent/MMKV#338]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Java

### The version of MMKV

> e.g. v1.0.10

v1.0.22.1

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

I find when disk is full, call  encodeXXX method will cause crash. 

stack traces:
memcpy(m_ptr, &actualSize, Fixed32Size);
MMKV::writeAcutalSize(unsigned int)
MMKV::appendDataWithKey(MMBuffer const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
MMKV::setDataForKey(MMBuffer&&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
MMKV::setBool(bool, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
mmkv::encodeBool(_JNIEnv*, _jobject*, long long, _jstring*, unsigned char)

**Comment by lingol** [comment]
And what do you expect when disk is full? MMKV will lost data if not crash.
Things that really needs to do it for your App to make a tips to your users, tell them to clean up some space, or shit will happen.

**Comment by yubansama** [comment]
Thanks for your response, what i expect is to avoid crash when disk is full just like sp.
Of course  tips is necessary but it's expensive to check if disk is full every time save data.
So can MMKV notify us when save data error due to disk is full instead of crash, or if there is a better way?
Look forward to your answer.
@lingol

**Comment by lingol** [comment]
Check space each time your App launches/being switched to foreground.
