### ISSUE TITLE
Custom folder is unvalid

### ISSUE THREAD

**Issue by leo-wxy** [Tencent/MMKV#339]
### The language of MMKV
Java

### The version of MMKV
1.0.23

### The platform of MMKV
Android

### The installation of MMKV
Maven

### What's the issue?
I use the demo and found 
```java
String otherDir = Environment.getExternalStorageDirectory().getAbsolutePath()+ "/mmkv_3";
        MMKV kv = testMMKV("ES", "Tencent MMKV", false, otherDir);
```
when test this code the  `mmkv_3/ES`  file is null . And i test old mmkv version(1.0.19) also have this issue.

**Comment by lingol** [comment]
MMKV is based on `mmap()`. I don't think mmaping a external storage file is a good idea.

**Comment by leo-wxy** [comment]
But i need export this file to analyse

**Comment by lingol** [comment]
> But i need export this file to analyse

Export it(and the `ES.crc`) by copying to external storage folder as a simple file when your business are done.
