### ISSUE TITLE
MMKV保存的数据丢失问题

### ISSUE THREAD

**Issue by hw1015** [Tencent/MMKV#342]
app 重新打开或重新安装   MMKV保存的数据都会丢失
报错如下
<native-bridge.cpp:95::JNI_OnLoad> current API level = 26
<MMKV.cpp:192::initialize> page size:4096
<MMKV.cpp:206::initializeMMKV> root dir: /data/user/0/***/files/mmkv
<MMKV.cpp:330::loadFromFile> loading [***_mmkvmanager] with 6930 size in total, file size is 16384
<MMKV.cpp:985::checkFileCRCValid> check crc [***_mmkvmanager] fail, crc32:545742726, m_crcDigest:1672270912
***_mmkvmanager is OnErrorDiscard
<MMKV.cpp:375::loadFromFile> loaded [***_mmkvmanager] with 0 values

**Comment by lingol** [comment]
Just as the log suggested, Your file is corrupted.

**Comment by hw1015** [comment]
好好的文件为啥会损坏？ 初始化，添加数据什么的都没问题，大概app 停留一段时间 或 关闭一段时间再打开 都提示这个。 一般会导致文件损坏的原因有哪些 ？

**Comment by lingol** [comment]
It doesn't have anything todo with your app being close or stay still.
Check if you have open an MMKV in multi-process with SINGLE-PROCESS-MODE.

**Comment by hw1015** [comment]
不能在子线程调用 ？只能在主线程 ？

**Comment by hw1015** [comment]
在Retrofit 的 拦截器中，添加header 实时获取数据  会造成文件损坏 ？

**Comment by hw1015** [comment]
文件损坏的概率太高了 ，总是丢失数据 ，放弃了

**Comment by lingol** [comment]
Must be something wrong with your usage. Tens of millions of user in WeChat are using MMKV and we don't face much corruption.

**Comment by lingol** [comment]
> Check if you have open an MMKV in multi-process with SINGLE-PROCESS-MODE.

Looks like you don't understand English much, I'll translate for you:

是不是以`单进程模式`在多个进程打开了同一个MMKV文件？

**Comment by hw1015** [comment]
多个地方不同的线程同时操作 一个key- value？      查找了基本所有代码  把所有操作基本都改到主线程 来操作  但是还是有问题   又没可能是 lib-armeabi-v7a  包的问题   我这边只有一个 armeabi-v7a包

**Comment by lingol** [comment]
Did I mention `thread(线程)` at all? Which part about process(进程) that you don't understand?

**Comment by hw1015** [comment]
多个进程打开了同一个MMKV文件？   我这个app没有做进程 通讯什么的 基本不会存在这个问题吧？ app用一个第三方  正常的使用方法 会出现严重问题  一般都会被放弃使用的

**Comment by lingol** [comment]
I give up. Just try this ok?

>如果业务需要多进程访问，那么在初始化的时候加上标志位 `MMKV.MULTI_PROCESS_MODE`：

>MMKV* mmkv = MMKV.mmkvWithID("InterProcessKV", MMKV.MULTI_PROCESS_MODE);
>mmkv.encode("bool", true);

**Comment by hw1015** [comment]
原来是单列使用   
MMKV.initialize(context.getApplicationContext());
kv = MMKV.defaultMMKV(1, "***_mmkvmanager");
我试一下您这种模式，但是我比较纳闷，好像没有多个进程操作啊  再一个就是 好多源码 都是c native 方法，还看不到  有什么方法 能看这些方法吗？

**Comment by lingol** [comment]
Code is available on GitHub, that's the whole point of being **open source**.
If you still don't fix the problem of corruption, send me a demo project that can reproduce the bug. guoling@tencent.com.

**Comment by beanu** [comment]
我也遇到这个问题了，但是没有收集到mmkv的报错信息。我之前保存的变量，重新打开app 突然就没有了。使用android的sharepreference保存的数据都还在。

**Comment by lingol** [comment]
> 我也遇到这个问题了，但是没有收集到mmkv的报错信息。我之前保存的变量，重新打开app 突然就没有了。使用android的sharepreference保存的数据都还在。

NO logs no way to further investigation.

**Comment by HikingChen** [comment]
I also encountered this problem. I save some bool flag and a parcelable class. That's all. However, I found I got empty value. I have printed process log to confirm never used multi-process. 
And then, I try to get MMKV instance with another id. Using this id to save that parcelable class. What surprised me is It' s working. I guess that maybe the parcelable class take up too much capacity. I don't know if it is correct. Look forward to your reply.

**Comment by lingol** [comment]
> I also encountered this problem. I save some bool flag and a parcelable class. That's all. However, I found I got empty value. I have printed process log to confirm never used multi-process.
> And then, I try to get MMKV instance with another id. Using this id to save that parcelable class. What surprised me is It' s working. I guess that maybe the parcelable class take up too much capacity. I don't know if it is correct. Look forward to your reply.

Still, I need logs to investigate. Talk is really cheap, show me the log.

**Comment by lingol** [comment]
And if you can reproduce it, a demo project will be much more helpful.

**Comment by shenguojun** [comment]
没有声明MMKV多进程的情况下，在多进程使用会报错误。解决的办法有两个，一个是声明MMKV为多进程，第二个是保持单进程使用。不过有个建议，像SP，多进程情况下拿Key对应的value可能会不准，但是主进程读写还是能保证的，不过MMKV只要有多进程的读取，那么主进程就无法继续保证key-value持久化了。建议MMKV也能在存在多进程读写的情况下，保持主进程内的读写正常。

**Comment by lingol** [comment]
I don't know what you are talking about. What do you mean "但是主进程读写还是能保证的"?

> 没有声明MMKV多进程的情况下，在多进程使用会报错误。解决的办法有两个，一个是声明MMKV为多进程，第二个是保持单进程使用。不过有个建议，像SP，多进程情况下拿Key对应的value可能会不准，但是主进程读写还是能保证的，不过MMKV只要有多进程的读取，那么主进程就无法继续保证key-value持久化了。建议MMKV也能在存在多进程读写的情况下，保持主进程内的读写正常。
