### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by Freedom0925** [Tencent/MMKV#345]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Java

### The version of MMKV

> e.g. v1.0.10

1.0.15

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

AAR Package

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

自从引入了MMKV之后，由于OOM导致的崩溃剧增。捕获到的堆栈有两种：
一是内存耗尽，二是线程创建。

项目中使用了比较多的文件（200+），会是这个导致的OOM吗？

**Comment by lingol** [comment]
Maybe.

**Comment by Freedom0925** [comment]
> Maybe.

这些文件不会被同时使用，不使用的文件会有影响吗？
