### ISSUE TITLE
雷电模拟器运行Android Demo崩溃

### ISSUE THREAD

**Issue by leezicws** [Tencent/MMKV#346]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   native: #16 pc 00182b2b  /data/dalvik-cache/x86/data@app@com.tencent.mmkvdemo-1@base.apk@classes.dex (Java_com_tencent_mmkv_MMKV_decodeInt__JLjava_lang_String_2I+175)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   native: #17 pc 00000c82  ???
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at com.tencent.mmkv.MMKV.decodeInt(Native method)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at com.tencent.mmkv.MMKV.decodeInt(MMKV.java:321)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at com.tencent.mmkvdemo.MainActivity.testInterProcessLogic(MainActivity.java:161)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at com.tencent.mmkvdemo.MainActivity.onCreate(MainActivity.java:138)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at android.app.Activity.performCreate(Activity.java:5990)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at android.app.ActivityThread.access$800(ActivityThread.java:151)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at android.os.Handler.dispatchMessage(Handler.java:102)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at android.os.Looper.loop(Looper.java:135)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at android.app.ActivityThread.main(ActivityThread.java:5254)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at java.lang.reflect.Method.invoke!(Native method)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at java.lang.reflect.Method.invoke(Method.java:372)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
10-29 18:31:16.529 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
10-29 18:31:16.530 10648-10648/com.tencent.mmkvdemo A/art: art/runtime/runtime.cc:289] Dumping all threads without appropriate locks held:

**Comment by lingol** [comment]
I don't know. Maybe you should post this bug to 雷电模拟器.
