### ISSUE TITLE
fail to open:/data/user/0/com.test.phone/files/mmkv/mmkv.default, No such file or directory

### ISSUE THREAD

**Issue by s3hengwu** [Tencent/MMKV#348]
我有个时间每隔1分钟会保存一次，此时我重启手机，收到自启动广播后，我再读这个时间，报错：
3043/? E/MMKV: <MmapedFile.cpp:43::MmapedFile> fail to open:/data/user/0/com.test.phone/files/mmkv/mmkv.default.crc, No such file or directory
2019-11-01 20:18:32.382 3043-3043/? E/MMKV: <MMKV.cpp:311::loadFromFile> fail to open:/data/user/0/com.test.phone/files/mmkv/mmkv.default, No such file or directory.
自启动失败后，我手动去打开我的app。我有个字段保存是否是首次打开，也是用的这个库，此时为默认值true。
W/MMKV: <MMKV.cpp:703::ensureMemorySize> [mmkv.default] file not valid

**Comment by lingol** [comment]
I don't really understand your question.

**Comment by s3hengwu** [comment]
简单说就是重启后，缓存数据没了。目前发现荣耀10会这样，红米note8正常

**Comment by s3hengwu** [comment]
修复好了，新增了一下数据恢复：
 public MMKVRecoverStrategic onMMKVCRCCheckFail(String s) {
                return MMKVRecoverStrategic.OnErrorRecover;
            }

            @Override
            public MMKVRecoverStrategic onMMKVFileLengthError(String s) {
                return MMKVRecoverStrategic.OnErrorRecover;
            }
