### ISSUE TITLE
关于丢数据的修正建议

### ISSUE THREAD

**Issue by bigboysun** [Tencent/MMKV#349]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

目前，配置文件被写入两个文件，数据文件和校验文件，有以下几点 问题
1. 如果校验文件写入失败或被删除
整个数据文件失效

2. 数据文件头部数据大小字段写入失败，校验文件写入成功
整个文件失效

综上所属，都是校验和文件位置不一致造成的文件失效。

修改建议，是否可以把校验直接写在数据文件头，在文件头中文件长度字段的后面，由于磁盘属于块设备，写入两个数据不一致的问题会大大降低。文件格式如下：
｜文件长度|文件校验和｜数据｜

当然这样也可产生数据写入失败，文件头写入成功的现象，是否可以改成：
|文件长度1｜文件校验和1｜文件长度2｜校验和2｜数据｜
这样可以防止一次写入失败

**Comment by anql** [comment]
这个建议很好，希望能被官方采纳

**Comment by zhangyinglong** [comment]
踩坑发现的问题

**Comment by lingol** [comment]
Short answer: NO, it will not work.

Long answer. First, according to our monitoring of MMKV inside WeChat,  the chances of **file length error** is quite the same as the chances of **crc check fail**. That means the possibility of header error is the same as the possibility of failing to sync to another file. There no such thing as `由于磁盘属于块设备，写入两个数据不一致的问题会大大降低`. When shit happens, it just happens anywhere.

**Comment by lingol** [comment]
For those who face data lost, I recommend calling `sync()`/`async()` in-time. And do [data recovery](https://github.com/Tencent/MMKV/wiki/android_advance#recover-from-data-corruption) if needed.

**Comment by richlxx** [comment]
> Short answer: NO, it will not work.
>
> Long answer. First, according to our monitoring of MMKV inside WeChat, the chances of file length error is quite the same as the chances of crc check fail. That means the possibility of header error is the same as the possibility of failing to sync to another file. There's no such thing as 由于磁盘属于块设备，写入两个数据不一致的问题会大大降低, especially when the file is larger than one pagesize.
>
> When shit happens, it just happens anywhere.

我翻译下，经过微信验证过了，没毛病，不改。

**Comment by lingol** [comment]
Now a second thought about it, there's actually something we could do to make it better.
Will come soon on `dev` branch.

**Comment by lingol** [comment]
Duplicate with #350
