### ISSUE TITLE
Expected NDK STL shared object file at /Users/didi/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi/libc++_shared.so

### ISSUE THREAD

**Issue by hanhailong** [Tencent/MMKV#35]
Expected NDK STL shared object file at /Users/didi/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi/libc++_shared.so

**Comment by lingol** [comment]
NDK r16b or older is required to build MMKV in Android. See the [wiki](https://github.com/Tencent/MMKV/wiki/android_setup) for detail instruction.

Note: if you don't need `ARMv5 (armeabi)`, then any NDK is fine. Check the wiki above for more info.
