### ISSUE TITLE
关于数据文件和校验文件的写入

### ISSUE THREAD

**Issue by bigboysun** [Tencent/MMKV#350]
bool MMKV::appendDataWithKey(const MMBuffer &data, const std::string &key)
//==========================
 writeAcutalSize(m_actualSize + size);
    m_output->writeString(key);
    m_output->writeData(data); // note: write size of data

    auto ptr = (uint8_t *) m_ptr + Fixed32Size + m_actualSize - size;
    if (m_crypter) {
        m_crypter->encrypt(ptr, ptr, size);
    }
    updateCRCDigest(ptr, size, KeepSequence);
//============================

如上段代码，写入顺序为：
1. 加锁
2. 写入文件新大小
3. 写入数据
4. 加密数据
5. 写入crc

是否应该调整为：
1. 拷贝数据到临时缓冲区
2. 加密数据
3. 加锁
4. 写入加密后的数据
5. 修改文件长度和crc

有几点好处：
1. 锁的范围最小
2. 在任何一步崩溃，不影响整个文件

还有一个疑问，如果磁盘满了，在哪一步捕捉错误：mmap？ 写入数据？

**Comment by lingol** [comment]
There's a problem with your proposal, a temp memory buffer is needed and a memcpy is needed. Which is not quite acceptable. Data integrity is just one consideration of design, you have to consider efficiency.

When the disk is full, MMKV will fail to expand it length on `ensureMemorySize()`.

**Comment by lingol** [comment]
The order of writing data and the writing of file length & crc chechsum doesn't make any difference.

**Comment by lingol** [comment]
Now a second thought about it, there's actually something we could do to make it better.
Will come soon on `dev` branch.

**Comment by bigboysun** [comment]
感谢回复，期待新版本

**Comment by lingol** [comment]
After two weeks' development, it's been live on the `dev` branch. Try it out and feedback is welcome.

Basically, we store confirmed file length & CRC checksum on the meta info file. And by saying **confirmed**, we mean it's been synced to file. In order to achieve that, we sync the mmkv to file on each full write back, together with the related meta info file.
Also, we store the file length on the meta info file as well, together with the CRC checksum.

**Comment by lingol** [comment]
These improvements have been tried in the WeChat App on iOS. We are happy to report that the file corruption rate has been greatly reduced (almost in half).

We will roll out them in the next major version (likely v1.1.0) after the Chinese New Year.

**Comment by samlu** [comment]
When will we expect the version 1.1.0 released?
Thanks.

**Comment by lingol** [comment]
> When will we expect the version 1.1.0 released?
> Thanks.

Hopefully in this month(March). There's some uint test case to write for POSIX platforms.

**Comment by lingol** [comment]
It's out finally. 
https://github.com/Tencent/MMKV/releases/tag/v1.1.0
