### ISSUE TITLE
decodeDouble return wrong value

### ISSUE THREAD

**Issue by yubansama** [Tencent/MMKV#351]
### The language of MMKV

Java

### The version of MMKV

v1.0.22.1

### The platform of MMKV

 Android

### The installation of MMKV

Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

put int: mmkv.encode("key", 10);

try to get double: mmkv.decodeDouble("key", -1);
but it returns 5.0E-323  not default value.

decodeFloat return 1.4E-44, 
decodeLong return 10.

**Comment by lingol** [comment]
If you want different types for the same key, just use different key for different type. 
MMKV does type erasure inside. There's no way for MMKV to know the value of the type.
