### ISSUE TITLE
-[UIApplication applicationState] must be used from main thread only. (may crash on iOS13)

### ISSUE THREAD

**Issue by WhatTheNathan** [Tencent/MMKV#356]
### The language of MMKV

> Objective-C

### The version of MMKV

> v1.0.23

### The platform of MMKV

> iOS

### The installation of MMKV

> Cocoapods

### What's the issue?

-[UIApplication applicationState] must be used from main thread only.

I know you did some changes on version 1.0.23.
you moved `auto appState = [UIApplication sharedApplication].applicationState;` to `+ (void)initialize`.
However, If the first use of MMKV is not in the main thread，it's still an invalid call.
And I found some crashes on iOS13.

**Comment by lingol** [comment]
I'm afraid that's the best we can do. There will be much buggy if we somehow force that API call inside `+ (void)initialize` to take place in the main thread. A dead-lock will likely happen if we do that.

I recommend initializing MMKV in the main thread immediately after `didFinishLaunch`.

**Comment by WhatTheNathan** [comment]
> I'm afraid that's the best we can do. There will be much buggy if we somehow force that API call inside `+ (void)initialize` to take place in the main thread. A dead-lock will likely happen if we do that.
> 
> I recommend initializing MMKV in the main thread immediately after `didFinishLaunch`.

Got it. Maybe you can update the README. = =
And I wonder if WeChat team did it like you said. Or you guys never use MMKV in the child thread for the first time.

**Comment by lingol** [comment]
Last time I check, no such crash reports in WeChat.

**Comment by lingol** [comment]
`+[MMKV initializeMMKV:]` is added with [v1.0.24](https://github.com/Tencent/MMKV/releases/tag/v1.0.24). You can call that method on App startup.

**Comment by WhatTheNathan** [comment]
> `+[MMKV initializeMMKV:]` is added with [v1.0.24](https://github.com/Tencent/MMKV/releases/tag/v1.0.24). You can call that method on App startup.

thanks~
