### ISSUE TITLE
introducing wyhash hash function

### ISSUE THREAD

**Issue by wangyi-fudan** [Tencent/MMKV#357]
Dear All:
I would like to introduce wyhash (https://github.com/wangyi-fudan/wyhash)
It is a 64-bit little endian portable hash function. It is the fastest one that passed all strict hash function tests (https://github.com/rurban/smhasher). I think MMKV can make use of it to increase performance.

**Comment by lingol** [comment]
We use CRC32 to make a file checksum, which could be benefited from your hash algorithm.
However, that checksum is not our performance bottle net. Because it's always incremental.

Thanks for your tips anyway. I will consider it in the future on choosing a hash method.
