### ISSUE TITLE
启动闪退，型号：vivo X6Plus D，5.0

### ISSUE THREAD

**Issue by wangprofessor** [Tencent/MMKV#358]
11-27 22:18:36.615 W/linker  (28853): libmmkv.so: unused DT entry: type 0x6ffffffe arg 0x4ed4
11-27 22:18:36.615 W/linker  (28853): libmmkv.so: unused DT entry: type 0x6fffffff arg 0x3
11-27 22:18:36.617 I/MMKV    (28853): <native-bridge.cpp:95::JNI_OnLoad> current API level = 22
11-27 22:18:36.618 I/MMKV    (28853): <MMKV.cpp:192::initialize> page size:4096
11-27 22:18:36.618 I/MMKV    (28853): <MMKV.cpp:206::initializeMMKV> root dir: /data/data/com.wumii.android.athena/files/mmkv
11-27 22:18:36.619 F/libc    (28853): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x239d3b18 in tid 28853 (.android.athena)
11-27 22:18:36.622 I/BufferQueueProducer(28167): [minicap](this:0x7f7e46f000,id:0,api:1,p:13166,c:28167) queueBuffer: slot 0 is dropped, handle=0x7f7e4578e0
11-27 22:18:36.622 D/AEE/AED (  316): $===AEE===AEE===AEE===$
11-27 22:18:36.622 D/AEE/AED (  316): p 0 poll events 1 revents 0
11-27 22:18:36.622 D/AEE/AED (  316): not know revents:0
11-27 22:18:36.622 D/AEE/AED (  316): p 1 poll events 1 revents 0
11-27 22:18:36.622 D/AEE/AED (  316): not know revents:0
11-27 22:18:36.622 D/AEE/AED (  316): p 2 poll events 1 revents 1
11-27 22:18:36.624 D/AEE/AED (  316): aed_main_fork_worker: generator 0xf6837148, worker 0xffa8a7d8, recv_fd 0
11-27 22:18:36.625 D/AEE/AED (  316): p 3 poll events 1 revents 0
11-27 22:18:36.625 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.625 D/AEE/AED (  316): not know revents:0
11-27 22:18:36.625 D/AEE/AED (  316): p 4 poll events 1 revents 0
11-27 22:18:36.625 D/AEE/AED (  316): not know revents:0
11-27 22:18:36.625 D/AEE/AED (  316): p 5 poll events 0 revents 0
11-27 22:18:36.625 D/AEE/AED (  316): not know revents:0
11-27 22:18:36.625 I/AEE/AED (28882): handle_request(0)
11-27 22:18:36.626 W/BufferQueueProducer(13166): [VDS: minicap](this:0x7f88c88000,id:1076,api:0,p:-1,c:13166) dequeueBuffer() in a disconnected state
11-27 22:18:36.626 I/AEE/AED (28882): check process 28853 name:.android.athena
11-27 22:18:36.626 I/AEE/AED (28882): tid 28853 abort msg address is:0x00000000, si_code is:2 (request from 28853:11329)
11-27 22:18:36.626 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.626 I/AEE/AED (28882): BOOM: pid=28853 uid=11329 gid=11329 tid=28853
11-27 22:18:36.627 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.628 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.628 I/AEE/AED (28882): [OnPurpose Redunant in void preset_info(aed_report_record*, int, int)] pid: 28853, tid: 28853, name: .android.athena  >>> com.wumii.android.athena <<<
11-27 22:18:36.629 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.630 W/BufferQueueProducer(13166): [VDS: minicap](this:0x7f88c88000,id:1076,api:0,p:-1,c:13166) queueBuffer() in a disconnected state
11-27 22:18:36.630 D/AALService(  328): enableAALEvent: 1 -> 0
11-27 22:18:36.631 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.631 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.640 I/BufferQueueProducer(28167): [minicap](this:0x7f7e46f000,id:0,api:1,p:13166,c:28167) queueBuffer: slot 2 is dropped, handle=0x7f7dc12160
11-27 22:18:36.642 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.643 W/BufferQueueProducer(13166): [VDS: minicap](this:0x7f88c88000,id:1076,api:0,p:-1,c:13166) dequeueBuffer() in a disconnected state
11-27 22:18:36.643 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.644 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.644 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.644 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.645 W/BufferQueueProducer(13166): [VDS: minicap](this:0x7f88c88000,id:1076,api:0,p:-1,c:13166) queueBuffer() in a disconnected state
11-27 22:18:36.646 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.646 E/SurfaceFlinger(13166): onDraw: bindTextureImage test
11-27 22:18:36.647 D/AALService(  328): enableAALEvent: 0 -> 1
11-27 22:18:36.680 I/AEE/AED (28882): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-27 22:18:36.680 I/AEE/AED (28882): Build fingerprint: 'vivo/PD1501D/PD1501D:5.1/LMY47I/1533368721:user/release-keys'
11-27 22:18:36.680 I/AEE/AED (28882): Revision: '0'
11-27 22:18:36.680 I/AEE/AED (28882): ABI: 'arm'
11-27 22:18:36.680 I/AEE/AED (28882): pid: 28853, tid: 28853, name: .android.athena  >>> com.wumii.android.athena <<<
11-27 22:18:36.680 I/AEE/AED (28882): signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x239d3b18
11-27 22:18:36.691 I/AEE/AED (28882):     r0 eeccf000  r1 cd3412aa  r2 ff98a474  r3 eeccf070
11-27 22:18:36.691 I/AEE/AED (28882):     r4 f4635fd8  r5 00000000  r6 00000000  r7 00001287
11-27 22:18:36.691 I/AEE/AED (28882):     r8 cd3412ee  r9 00000000  sl 00000000  fp f46aa380
11-27 22:18:36.691 I/AEE/AED (28882):     ip f6ec37c0  sp ff98a450  lr f4207959  pc f41c8a24  cpsr 80010030
11-27 22:18:36.692 I/AEE/AED (28882):
11-27 22:18:36.692 I/AEE/AED (28882): backtrace:
11-27 22:18:36.692 I/AEE/AED (28882):     #00 pc 000bfa24  /system/lib/libart.so (_ZNK3art7DexFile29StringDataAndUtf16LengthByIdxEjPj+7)
11-27 22:18:36.692 I/AEE/AED (28882):     #01 pc 000fe955  /system/lib/libart.so (_ZNK3art7DexFile12FindClassDefEPKcj+612)
11-27 22:18:36.692 I/AEE/AED (28882):     #02 pc 007fd4b0  [stack]

**Comment by lingol** [comment]
Please provide symbolized crash stack.

**Comment by lingol** [comment]
Hello, any problems providing the call stack?

**Comment by wangprofessor** [comment]
我只有上边的打印，没有java的打印，这是一个偶现的问题，目前只发现在题目所说的一种机器上有出现。请问mmkv是否存在在一些特定的机器上无法使用的问题？

**Comment by lingol** [comment]
> 我只有上边的打印，没有java的打印，这是一个偶现的问题，目前只发现在题目所说的一种机器上有出现。请问mmkv是否存在在一些特定的机器上无法使用的问题？

NO.
