### ISSUE TITLE
mmkv和mars 中的xlog 都引用了c++shared   运行会报错   怎么解决呢

### ISSUE THREAD

**Issue by jiaguangfeng** [Tencent/MMKV#362]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

**Comment by lingol** [comment]
Use `com.tencent.mmkv-static`.
