### ISSUE TITLE
[Needs Best Practice] Save hundreds of values to several mmkv instances or in single instance?

### ISSUE THREAD

**Issue by teoking** [Tencent/MMKV#368]
### The version of MMKV
v1.0.19

### The platform of MMKV
iOS or Android

### What's the issue?
Before migrated to MMKV, we use SharedPreferences to save hundreds values. While migrating to MMKV in following ways:
1. save hundreds of values in several mmkv instances
2. save hundreds of values in a single mmkv instance

Which one is better?  And why?

**Comment by lingol** [comment]
As for efficiency, it's totally fine to store hundreds of key-values inside a single MMKV instance. Even thousands of them is not a problem.

However, it's a **good practice** to separate different key-values of **different businesses** into different MMKV instances. It is cleaner, easier to manage, and much robust from storage failure.

**Comment by teoking** [comment]
Thanks lingol. Appreciate for you detailed answer.
