### ISSUE TITLE
iOS  ObjC  with 0 size in total, file seze is 16384

### ISSUE THREAD

**Issue by wanglelewang** [Tencent/MMKV#370]
2020-01-07 10:32:55.669579+0800 Soul_New[5632:1671261] [I] <MMKV.mm:1396::+[MMKV mmapKeyWithMMapID:relativePath:]> mmapKey: mmkv.default
2020-01-07 10:32:55.670682+0800 Soul_New[5632:1671261] [I] <MMKV.mm:283::-[MMKV loadFromFile]> loading [mmkv.default] with 0 size in total, file size is 16384
(lldb)

**Comment by lingol** [comment]
So what?

**Comment by wanglelewang** [comment]
crash

https://user-images.githubusercontent.com/20278050/71864543-054d3980-313b-11ea-9042-9084af555bbe.png

**Comment by wanglelewang** [comment]
- (BOOL)checkFileCRCValid {
	if (m_ptr != nullptr && m_ptr != MAP_FAILED) {
		int offset = pbFixed32Size(0);

//////////////////////
		m_crcDigest = (uint32_t) crc32(0, (const uint8_t *) m_ptr + offset, (uint32_t) m_actualSize);//这句代码 导致crash
//////////////////////

if (m_metaFilePtr == nullptr || m_metaFilePtr == MAP_FAILED) {
			[self prepareMetaFile];
		}

**Comment by lingol** [comment]
That log is a normal log.
Yet the crash is not quite normal. It just makes no sense to crash there.

**Comment by lingol** [comment]
Which version did you use? And how did you reproduce this problem? 
Is it launching the App by background fetch?

**Comment by wanglelewang** [comment]
MMKV 版本号是1.0.23
  app 正常启动的时候百分百出现  貌似是crc32 这个引起的  跟我自己制作的一个库有冲突 两个一起用 就会引起crash

**Comment by lingol** [comment]
> MMKV 版本号是1.0.23
> app 正常启动的时候百分百出现 貌似是crc32 这个引起的 跟我自己制作的一个库有冲突 两个一起用 就会引起crash

Looks like your lib has a `crc32` method, which MMKV links from `libz`. You can try remove that method and use zlib as well.

**Comment by wanglelewang** [comment]
好的 感谢 我找找看 应该我制作的库中使用了 其它人的.a文件 导致的  libfdk-aac  libmedialivelib libmp4stream  libx264 libyuv中的一个 但是我不知道从何下手找。。。

**Comment by lingol** [comment]
```bash
nm xxx.a | grep crc32
```

**Comment by wanglelewang** [comment]
/vendor/lib/libmedialivelib.a | grep crc32
00000000 T _crc32
0000000000000000 T _crc32

只有这个库有从crc32 相关的 但是他的名字并不一样 这也会引起错的的吗？

**Comment by wanglelewang** [comment]
确实是 crc冲突了 
https://blog.csdn.net/mandagod/article/details/79635793
通过这个文章的步骤 删掉了 重复库中的crc.o  之后 成功解决了这个问题

**Comment by wanglelewang** [comment]
非常感谢
