### ISSUE TITLE
希望有更详细的文档

### ISSUE THREAD

**Issue by Whoisurdady** [Tencent/MMKV#371]
### The language of MMKV

> Java

### The version of MMKV

> v1.0.23

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 有没有详细一点的方法文档，譬如reKey方法的具体用途

**Comment by lingol** [comment]
No. As for `reKey()`, I believe it's quite clear on the comment above it.

```Java
    // transform plain text into encrypted text
    // or vice versa by passing cryptKey = null
    // or change existing crypt key
    public native boolean reKey(String cryptKey);
```

For usage, you can always check out the mmkvdemo project. https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkvdemo/src/main/java/com/tencent/mmkvdemo/MainActivity.java#L291

**Comment by lingol** [comment]
A complete JavaDoc is added on v1.2.10. You can check it out locally or online.
