### ISSUE TITLE
mmkv.putString("test", "1") 然后把android开发板断电  然后通电以后   mmkv.getString("test")的数据无效

### ISSUE THREAD

**Issue by huangtaoit123** [Tencent/MMKV#372]
mmkv.putString("test", "1") 然后把android开发板断电  然后通电以后   mmkv.getString("test")出来的数据不是"1"  得到的数据是上一次的0

**Comment by huangtaoit123** [comment]
mmkv.putString("test", "1") 然后把android开发板断电 然后通电以后 mmkv.getString("test")出来的数据不是"1" 得到的数据是上一次的0!   我断电之前确定 "1" 已经put进去了

**Comment by lingol** [comment]
Maybe it's not synced to file. Have you called `sync()` before that power down?

PS: That `0` is not necessary the old value. You should get the string with a default value to make sure.

**Comment by SJX516** [comment]
我这边也碰到这样的问题，而且是在模拟器上 100% 复现
  1. puString 之后 调用了 sync(false) 在 1s 内直接关闭模拟器，开机后取到的不是最后一次 putString 的值，而是倒数第二次的值
  2. 另外，如果 puString 之后 调用了 sync(true) 在 1s 内直接关闭模拟器，开机后只能取到空值，这个问题好像更严重
  3. putString 之后不管调哪个 sync，在 1s 后关闭模拟器，都是正常的

**Comment by lingol** [comment]
> @lingol 我这边也碰到这样的问题，而且是在模拟器上 100% 复现
> 
> 1. puString 之后 调用了 sync(false) 在 1s 内直接关闭模拟器，开机后取到的不是最后一次 putString 的值，而是倒数第二次的值
> 2. 另外，如果 puString 之后 调用了 sync(true) 在 1s 内直接关闭模拟器，开机后只能取到空值，这个问题好像更严重
> 3. putString 之后不管调哪个 sync，在 1s 后关闭模拟器，都是正常的

The OS fails to sync(true) to file in time. Yet it tells the developer it has successfully done that. There's nothing we can do about that.

**Comment by lingol** [comment]
>2. 另外，如果 puString 之后 调用了 sync(true) 在 1s 内直接关闭模拟器，开机后只能取到空值，这个问题好像更严重

As for this case, it's likely the file is corrupted. You can check the logcat for hints.

**Comment by SJX516** [comment]
> > 1. 另外，如果 puString 之后 调用了 sync(true) 在 1s 内直接关闭模拟器，开机后只能取到空值，这个问题好像更严重
> 
> As for this case, it's likely the file is corrupted. You can check the logcat for hints. @SJX516

```
01-13 11:14:48.984 3416-3416/com.duchen.myapplication I/MMKV: <native-bridge.cpp:101::JNI_OnLoad> current API level = 22
01-13 11:14:48.984 3416-3416/com.duchen.myapplication I/MMKV: <MMKV.cpp:192::initialize> page size:4096
01-13 11:14:48.984 3416-3416/com.duchen.myapplication I/MMKV: <MMKV.cpp:206::initializeMMKV> root dir: /data/data/com.duchen.myapplication/files/mmkv
01-13 11:14:48.986 3416-3416/com.duchen.myapplication I/MMKV: <MMKV.cpp:335::loadFromFile> loading [mmkv.default] with 6202 size in total, file size is 8192, InterProcess 0
01-13 11:14:48.986 3416-3416/com.duchen.myapplication E/MMKV: <MMKV.cpp:1017::checkFileCRCValid> check crc [mmkv.default] fail, crc32:1916073315, m_crcDigest:3676121144
01-13 11:14:48.989 3416-3416/com.duchen.myapplication I/MMKV: Recover strategic for mmkv.default is OnErrorDiscard
01-13 11:14:48.989 3416-3416/com.duchen.myapplication I/MMKV: <MMKV.cpp:380::loadFromFile> loaded [mmkv.default] with 0 values
```
这是这种情况下，开机后的日志，看起来是校验失败了，所以丢弃了之前的缓存，这种情况是所有key的缓存都会被丢弃么？

**Comment by lingol** [comment]
> 01-13 11:14:48.984 3416-3416/com.duchen.myapplication I/MMKV: <native-bridge.cpp:101::JNI_OnLoad> current API level = 22
> 01-13 11:14:48.984 3416-3416/com.duchen.myapplication I/MMKV: <MMKV.cpp:192::initialize> page size:4096
> 01-13 11:14:48.984 3416-3416/com.duchen.myapplication I/MMKV: <MMKV.cpp:206::initializeMMKV> root dir: /data/data/com.duchen.myapplication/files/mmkv
> 01-13 11:14:48.986 3416-3416/com.duchen.myapplication I/MMKV: <MMKV.cpp:335::loadFromFile> loading [mmkv.default] with 6202 size in total, file size is 8192, InterProcess 0
> 01-13 11:14:48.986 3416-3416/com.duchen.myapplication E/MMKV: <MMKV.cpp:1017::checkFileCRCValid> check crc [mmkv.default] fail, crc32:1916073315, m_crcDigest:3676121144
> 01-13 11:14:48.989 3416-3416/com.duchen.myapplication I/MMKV: Recover strategic for mmkv.default is OnErrorDiscard
> 01-13 11:14:48.989 3416-3416/com.duchen.myapplication I/MMKV: <MMKV.cpp:380::loadFromFile> loaded [mmkv.default] with 0 values
> ```
> 
> @lingol 这是这种情况下，开机后的日志，看起来是校验失败了，所以丢弃了之前的缓存，这种情况是所有key的缓存都会被丢弃么？

Yes, that's the default behavior. Developers can override that by implementing `MMKVHandler` and return `OnErrorRecover` to recover as much data as possible. You can try that.
However, the recovery rate is not promised. The `dev` branch has some improvement in recovery, you can try that as well.
