### ISSUE TITLE
android 支持list或者arraylist吗

### ISSUE THREAD

**Issue by ab175528** [Tencent/MMKV#373]
android 支持list或者arraylist吗，

**Comment by lingol** [comment]
Yes, but only with `String` inner type. Check out [this method](https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/java/com/tencent/mmkv/MMKV.java#L390).

For other types, you can serialize them with `<Parcelable>` interface. Note: there is a known bug that Parcel doesn't handle adding or removing members properly. Check out this issue #369  for details.
