### ISSUE TITLE
android SharedPreferences 存储的Serializable对象如何迁移到mmkv

### ISSUE THREAD

**Issue by ab175528** [Tencent/MMKV#374]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

**Comment by lingol** [comment]
MMKV doesn't support `Serializable` by choice because it's pretty slow. You can add `Parccelable` to your Class, decode it manually from SP, then store to MMKV using Parcel.
