### ISSUE TITLE
在安卓中适合用来保存大概10M以下的字符串数据吗

### ISSUE THREAD

**Issue by luoqiang108** [Tencent/MMKV#375]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

**Comment by lingol** [comment]
You should just use a normal file.
