### ISSUE TITLE
支持object么?

### ISSUE THREAD

**Issue by as11051105** [Tencent/MMKV#38]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

支持object么?

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
NO. MMKV doesn't support object directly. But you can archive into NSData, and store that inside MMKV.

**Comment by lingol** [comment]
Supported with #62
