### ISSUE TITLE
怎么看存储的数据，有工具可以看吗？？？

### ISSUE THREAD

**Issue by zhongrenzhan** [Tencent/MMKV#382]

**Comment by lingol** [comment]
No such tools. Check out #197 for reasons.

**Comment by pengwei1024** [comment]
I developed a MMKV reading tool on macos, welcome to try [https://github.com/pengwei1024/MMKVReader](https://github.com/pengwei1024/MMKVReader)

**Comment by lingol** [comment]
For those still in need of a visualizer, here's an online tool. https://www.mmkv-visualizer.com/
It at least decodes all the keys correctly.

**Comment by spak9** [comment]
Just to add some context, it also decodes the values, but because the value type is unknown until runtime, you _have to click on each value cell_ and iterate through all of the possible types.
