### ISSUE TITLE
A simple debug tool for MMKV

### ISSUE THREAD

**Issue by ddyos** [Tencent/MMKV#383]
[flipper-plugin-mmkv-viewer](https://github.com/ddyos/flipper-plugin-mmkv-viewer) is a simple debug tool for MMKV. Currently only Android is supported.
Just like Stetho, it can view or edit the key-value inside the MMKV file.

Is it necessary to add this infomation to FAQ?  It may help somebody who need debug tool, such as #382  #336 .

**Comment by lingol** [comment]
Thanks for your input. I will look into your project.
