### ISSUE TITLE
能否替代 PreferenceFragment

### ISSUE THREAD

**Issue by PlexPt** [Tencent/MMKV#386]
### The language of MMKV
 

Kotlin

### The version of MMKV
1.0.24
 

### The platform of MMKV
Android
 

### The installation of MMKV

  Maven 

### What's the issue?

PreferenceFragment 默认使用系统的 Preference， mmkv能否有迁移方案

**Comment by lingol** [comment]
I don't think there's much ANR inside a normal PreferenceFragment usage. It just doesn't need to write or read data from file that often.

**Comment by lingol** [comment]
In a word,  it makes little sense to port `PreferenceFragment` from SP to MMKV.

**Comment by PlexPt** [comment]
tks

**Comment by PlexPt** [comment]
1
