### ISSUE TITLE
MMKV在Android普通类中初始化报错

### ISSUE THREAD

**Issue by iqiqiya** [Tencent/MMKV#388]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Java

### The version of MMKV

> e.g. v1.0.10

v1.0.24

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

在Activity里边初始化是成功的，但java普通类初始化报错
// 引入mmkv
String rootDir = MMKV.initialize(this);

问题如下图所示：
![sc_20200225172112](https://user-images.githubusercontent.com/43666095/75233514-efcbc600-57f3-11ea-82c9-197e9f91c6f2.png)

麻烦了，感激不尽
刚学Android的菜鸟

**Comment by lingol** [comment]
Don't just initialize MMKV in any Classes, initialize it in MainActivity or main Application when your app just startup.
