### ISSUE TITLE
迁移到MMKV中如何屏蔽第三方库sp迁移

### ISSUE THREAD

**Issue by RogerWP** [Tencent/MMKV#389]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

由于有些第三方库会使用sp中getAll()方法，如何在迁移操作时排除第三方库的sp。我目前迁移操作是在Application的getSharedPreferences函数进行的

**Comment by lingol** [comment]
Add something like `getMMKVSharedPreferences()` to your Application Class.

**Comment by RogerWP** [comment]
@lingol 感谢回复，按照我的理解，岂不项目中每一个地方使用getSharedPreferences()这个函数都需要替换成getMMKVSharedPreferences()吗

**Comment by lingol** [comment]
> @lingol 感谢回复，按照我的理解，岂不项目中每一个地方使用getSharedPreferences()这个函数都需要替换成getMMKVSharedPreferences()吗

Yes, replace SP with MMKV on the heavily use case. That's the right way to go. Optimize only when you face problems.

**Comment by RogerWP** [comment]
@lingol 非常感谢，由于我们项目很庞大，最开始想法是能通过几行代码就完成整个迁移，看来我的思路有些问题。
