### ISSUE TITLE
迁移之后，为了少修改项目中代码，需要屏蔽commit()这个方法吗

### ISSUE THREAD

**Issue by RogerWP** [Tencent/MMKV#390]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html
由于项目中sp代码比较分散很多，迁移之后，为了少修改项目中代码，需要屏蔽commit()这个方法吗，这个方法很耗时吗？

**Comment by lingol** [comment]
It does cost some time for `commit()` to call `msync()` to sync memory to file. However, I don't think you should remove that method.
