### ISSUE TITLE
Android 华为P30 重启APP数据丢失

### ISSUE THREAD

**Issue by newtalentxp** [Tencent/MMKV#392]
### The language of MMKV
Java, or Kotlin

### The version of MMKV
latest

### The platform of MMKV
Android

### The installation of MMKV
Maven

### What's the issue?
Android 华为P30 重启APP数据丢失

**Comment by lingol** [comment]
Any logs/call stacks?

**Comment by newtalentxp** [comment]
已经解决了, 是调用 mmkvById传入参数错误导致
请问有没有开发qq群或者微信群？

**Comment by lingol** [comment]
> 已经解决了, 是调用 mmkvById传入参数错误导致
> 请问有没有开发qq群或者微信群？

Lesson learned from other projects(like WCDB) is that, don't ever create any such talk groups. It's full of bias, faq questions, redundant questions, etc.
Just create issues on GitHub is enough.
