### ISSUE TITLE
Java_com_tencent_mmkv_MMKV_checkReSetCryptKey SIGSEGV(SEGV_ACCERR)

### ISSUE THREAD

**Issue by stefanJi** [Tencent/MMKV#394]
### The language of MMKV

Kotlin

### The version of MMKV

v1.0.12

### The platform of MMKV

Android

### The installation of MMKV

Gradle AAR

### What's the issue?

Application Crash, **SIGSEGV(SEGV_ACCERR)**

```
pc 0001a014 /system/lib/libc.so (memcpy+200) 
[armeabi-v7a::f76ceabc8d849a203baefd7b78a981d0]
--
pc 00007ec1  /lib/arm/libmmkv.so 
[armeabi-v7a::e25abdc17cc61b68b67da13ce9ce39e1]
java:
com.tencent.mmkv.MMKV.boolean encode(java.lang.String,java.lang.String)(SourceFile:252)
```

Via addr2line found: `pc 00007ec1` -> `Java_com_tencent_mmkv_MMKV_checkReSetCryptKey`

**Comment by lingol** [comment]
That's just too old. Why not upgrade to v1.0.24 and check if it happens again?

**Comment by stefanJi** [comment]
🤔 I will upgrade and track this crash. Thanks for your reply.
