### ISSUE TITLE
Ask a question about ftruncate and zeroFillFile

### ISSUE THREAD

**Issue by pengwei1024** [Tencent/MMKV#396]
[https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/cpp/MMKV.cpp](https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/cpp/MMKV.cpp) 

On line 322 of the file,  Does ftruncate and zeroFillFile have the same function? Are actively increasing the file size。

Why does ftruncate call zeroFillFile regardless of success or failure?  After ftruncate fails, the parameters of zerofile are also wrong.

I'm very puzzled about this, I hope the author can answer my questions. thank you very much。

**Comment by lingol** [comment]
On Android(actually on any Linux distribution), `ftruncate()` a file doesn't mean it has that actual space on the disk. You got to zero-fill it to make sure.
As for the failure of `ftruncate()`, it doesn't hurt to call `zeroFill()` with size zero -- I just didn't want to write that much `if else` thing.

**Comment by lingol** [comment]
Oh, and one more thing. If you are interested in the code, you should differently look into the `dev` branch, which will be rolled out this month as v1.1.0. There're bunches of new stuff there.

**Comment by pengwei1024** [comment]
> Oh, and one more thing. If you are interested in the code, you should definitely look into the `dev` branch, which will be rolled out this month as v1.1.0. There're bunches of new stuff there.

Thanks a lot。 MMKV is a great framework。
