### ISSUE TITLE
iOS 切换账号后，重启App，数据丢失！！！

### ISSUE THREAD

**Issue by difoi** [Tencent/MMKV#397]
### The language of MMKV

> Swift

### The version of MMKV

> 1.0.24

### The platform of MMKV

> iOS

### The installation of MMKV

> Cocoapods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

1、清除代码
    /// 清除所有缓存数据
    class func clear() {
        let mmkv = MMKV.default()
        mmkv.clearMemoryCache()
        mmkv.clearAll()
        mmkv.close()
    }

2、实例代码
        MMKV.initialize(rootDir: nil)
        MMKV.setLogLevel(MMKVLogDebug)

3、保存和读取代码
    class func setDefValueByKey<T>(key:DefKeys, value:T) {
        let mmkv = MMKV.default()
        if value is String {
            mmkv.set(value as! String, forKey: key.rawValue)
        }
        else if value is Bool {
            mmkv.set(value as! Bool, forKey: key.rawValue)
        }
        else if value is Data {
            mmkv.set(value as! Data, forKey: key.rawValue)
        }
        else if value is Float {
            mmkv.set(value as! Float, forKey: key.rawValue)
        }
        else if value is Double {
            mmkv.set(value as! Double, forKey: key.rawValue)
        }
    }

    class func getStringForKey(key:DefKeys) -> String {
        let mmkv = MMKV.default()
        return mmkv.string(forKey: key.rawValue, defaultValue: "") ?? ""
    }

4、问题过程
 4.1 启动App，输入账号A和密码，登录成功;
 4.2 注销当前已登录账号A,（并清除所有保存数据，重新跳转登录界面）
 4.3 再次输入账号B和密码，登录成功;
 4.4 退出App（手动后台杀掉）
 4.5 再次启动App，之前登录成功账号B保存数据丢失;

5、试验
 5.1 单个账号A登录成功，在退出App，再次启动，偶尔也会发现数据丢失，但是次数不多;
 5.2 appstore 上线版本使用 1.0.23 没有发生已上问题;

6、注销功能 相当于同一个App切换不同账号登录，不需要重启app;

7、已测试机型 iPhone XS，iOS 13.3.1, iPhone 11  iOS 13.3.1 ,iPhone 6 plus iOS 12.4 

8、如果需要可以提供已上线app下载址和录制视频;

**Comment by difoi** [comment]
![Screen Shot 2020-03-13 at 9 28 39 PM](https://user-images.githubusercontent.com/2200801/76627326-c641c700-6575-11ea-8f22-f4d45943cd37.png)

登录界面

**Comment by lingol** [comment]
I don't need your app or your screenshots, that just not helpful. Please provide **logs**.

And it's really **confusing** reading your issue report, as you don't make any valid bug reports of mmkv itself. 
Maybe you should provide **a demo app(with source code)** that can demo your bug. And send it to me guoling@tencent.com.

**Comment by lingol** [comment]
FYI, MMKV doesn't care about users, log in or log out, etc. They are just the same to MMKV. It makes no sense for MMKV to lose data when you just log out A & log in B, and doesn't lose data otherwise.

Looks like you have some bug in **your logic code**.

**Comment by difoi** [comment]
> FYI, MMKV doesn't care about users, log in or log out, etc. They are just the same to MMKV. It makes no sense for MMKV to lose data when you just log out A & log in B, and doesn't lose data otherwise.
> 
> Looks like you have some bug in **your logic code**.

注销A账号，就会清除A账号 MMKV 保存的所有数据;
登录B账号，MMKV就会保存B账号所有数据;

A&B账号切换登录没有任何问题，但是App退出后，再次启动，MMKV保存数据丢失;

有可能我解释并不准确，已录制操作视频发送邮箱;
打扰了

**Comment by lingol** [comment]
You don't read my words. I DON'T NEED YOUR APP OR SCREENSHOTS OR VIDEOS.

**Comment by lingol** [comment]
MMKV just doesn't lose data on killing the app in anyways. You should provide a demo App that can reproduce such bug.
