### ISSUE TITLE
Can I use this with App Groups?

### ISSUE THREAD

**Issue by djorkaeffalexandre** [Tencent/MMKV#398]
I want to be able to share data between my app and my share extension, this can be able using App Groups. I can use App Groups with MMKV to share data between my apps?

**Comment by lingol** [comment]
It's one major feature in v1.1.0, which will be released soon. You can try the `dev` branch.

**Comment by lingol** [comment]
For instructions, check out the wiki `dev` branch as well.
https://github.com/Tencent/MMKV.wiki.git

**Comment by djorkaeffalexandre** [comment]
Really thanks @lingol !! I saw this [here](https://github.com/Tencent/MMKV/blob/master/iOS/MMKV/MMKV/MMKV.mm#L109), maybe passing the path of the appGroups dir this will work fine, right?

**Comment by lingol** [comment]
No. Check [this](https://github.com/Tencent/MMKV/blob/dev/iOS/MMKVDemo/MMKVDemo/AppDelegate.m#L45) for example.

**Comment by djorkaeffalexandre** [comment]
Oh, thats all I need.
Closing for now.
Really thanks about your quickly response! 👍

**Comment by lingol** [comment]
> Really thanks @lingol !! I saw this [here](https://github.com/Tencent/MMKV/blob/master/iOS/MMKV/MMKV/MMKV.mm#L109), maybe passing the path of the appGroups dir this will work fine, right?
> Feel free to close this.
> Best regards.

Passing the path of app groups is not enough. Inter-process locking is also required, which is not included before v1.1.0.
