### ISSUE TITLE
activity crash 

### ISSUE THREAD

**Issue by hytcooker2009** [Tencent/MMKV#399]
### The language of MMKV

> java

### The version of MMKV

>  com.tencent:mmkv-static:1.0.23

### The platform of MMKV

>android

### The installation of MMKV

> gradle

### What's the issue?
i find a crash for this in:
java.lang.UnsatisfiedLinkError: dlopen failed: library "ted_virtual" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
	at java.lang.System.loadLibrary(System.java:1669)
	at com.tencent.mmkv.MMKV.a(SourceFile:1100)

ths

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

**Comment by lingol** [comment]
MMKV knows nothing about that library "ted_virtual". You should check your apk.
