### ISSUE TITLE
Legacy support?

### ISSUE THREAD

**Issue by ChanNagihong** [Tencent/MMKV#402]
Would you release legacy support version without androidX in the future?

**Comment by lingol** [comment]
No, won't do it. It's better to keep pace with tech trends.
Any particular reason you are not migrating to AndroidX? I'm curious.

**Comment by ChanNagihong** [comment]
Our project exports SDKs to customers, some of them won't migrate to AndroidX in the near future. MMKV was a great project, it's fast and stable, we want to use it in our products.

**Comment by lingol** [comment]
If that's the case, I recommend integrating MMKV by source code.

**Comment by ChanNagihong** [comment]
Thank your~
