### ISSUE TITLE
trim调用时机问题

### ISSUE THREAD

**Issue by free46000** [Tencent/MMKV#409]
### The language of MMKV

> Java  

### The version of MMKV

> e.g. v1.0.24

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

通过代码注释，我发现咱们`deleting key-values`的时候不去释放本地文件存储空间，所以我想咨询的是：我能通过什么方法知道当前的无效本地存储空间是多少，来判断一个合适的时机去调用 `trim` 方法，这样既能兼顾存储的效率，也不至于浪费过多的空间

辛苦解答~~

**Comment by lingol** [comment]
You should call it when deleting huge numbers of keys. Generally, just don't worry about it.

**Comment by free46000** [comment]
正常情况，我很少会记录我删除了多少的key，如果一般情况下不用考虑这个问题，那我可以考虑定期trim一下，多谢
