### ISSUE TITLE
iOS v1.1.0版本多进程widget内部用mmkv替代NSUserDefault，直接crash

### ISSUE THREAD

**Issue by code1303009** [Tencent/MMKV#421]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

在widget的TodayViewController.m内是这么使用的
    dispatch_async(dispatch_get_main_queue(), ^{
        NSURL *url = [[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:WIDIDGET_GROUP_IDENTIFY];
        NSString *plist = [NSString stringWithFormat:@"%@Library/Preferences/",url.absoluteString];
        NSString * groupPath = [plist stringByReplacingOccurrencesOfString:@"file://" withString:@""];
        [MMKV initializeMMKV:nil groupDir:groupPath logLevel:MMKVLogNone];
        MMKV *widgetMmkv = [MMKV mmkvWithID:kWidgetGroup mode:MMKVMultiProcess];
        if ([widgetMmkv allKeys].count == 0) {
            //mmkv迁移数据
            NSUserDefaults *defaults = [[NSUserDefaults alloc] initWithSuiteName:WIDIDGET_GROUP_IDENTIFY];
            [widgetMmkv migrateFromUserDefaults:defaults];
        }
    });
同时在主app的appdelegate内是这使用的
- (void)initialize{
    MMKVLogLevel logLevel = MMKVLogNone;
#if DEBUG
    logLevel = MMKVLogDebug;
#endif
    [MMKV initializeMMKV:nil groupDir:_groupPath logLevel:logLevel];
    MMKV *widgetMmkv = [MMKV mmkvWithID:kWidgetGroup mode:MMKVMultiProcess];
    if ([widgetMmkv allKeys].count == 0) {
        //mmkv迁移数据
        NSUserDefaults *defaults = [[NSUserDefaults alloc] initWithSuiteName:WIDIDGET_GROUP_IDENTIFY];
        [widgetMmkv migrateFromUserDefaults:defaults];
    }
}
内部数据的调用更新是这样的：
    MMKV *mmkv = [MMKV mmkvWithID:kWidgetGroup mode:MMKVMultiProcess];
    BOOL isWidgetLaunch = [mmkv getBoolForKey:kWidgetLaunch];

**Comment by code1303009** [comment]
请问一下 我是不是有什么用法上的错误

**Comment by lingol** [comment]
Show your crash stacks instead of code.

Also, check if you link MMKV to your widget target properly. https://github.com/Tencent/MMKV/wiki/iOS_tutorial#configuration

**Comment by lingol** [comment]
Example code goes to https://github.com/Tencent/MMKV/blob/master/iOS/MMKVDemo/MMKVTodayExtensionDemo/TodayViewController.m#L31

**Comment by code1303009** [comment]
> Example code goes to https://github.com/Tencent/MMKV/blob/master/iOS/MMKVDemo/MMKVTodayExtensionDemo/TodayViewController.m#L31

**Comment by code1303009** [comment]
我更换一下用法 先试一下

**Comment by code1303009** [comment]
![1585155114552](https://user-images.githubusercontent.com/3941156/77563447-43692680-6efc-11ea-9d7a-86db1d54cbff.jpg)
你好，貌似demo也会崩溃

**Comment by code1303009** [comment]
我是直接下载的demo直接运行的

**Comment by lingol** [comment]
Did you find the problems yet?

**Comment by code1303009** [comment]
> Did you find the problems yet?

是的，应该是内部调用类型不匹配引起的crash

**Comment by code1303009** [comment]
> Did you find the problems yet?

你好，能帮看一下widget的崩溃么，主app用pod方式引入MMKV 1.1.0，在widget的target引入MMKVAppExtension.framework库，会引起崩溃，这是崩溃信息

{"app_name":"MojiWidget","timestamp":"2020-04-08 00:00:15.58 +0800","app_version":"8.2.2","slice_uuid":"2b8311bb-c7da-314e-815f-146435da0512","adam_id":0,"build_version":"202003161753","bundleID":"com.moji.MojiWeather.MojiWidget","share_with_app_devs":false,"is_first_party":false,"bug_type":"109","os_version":"iPhone OS 13.3.1 (17D50)","incident_id":"561ADBA1-7BA9-4E14-ABD9-58AEA31C6378","name":"MojiWidget"}
Incident Identifier: 561ADBA1-7BA9-4E14-ABD9-58AEA31C6378
CrashReporter Key:   8cbb6a185687a3744336edb72f28c6ed50405a8f
Hardware Model:      iPhone10,1
Process:             MojiWidget [3242]
Path:                /private/var/containers/Bundle/Application/B8F000CE-ABE2-457C-A114-F58BCC26A13F/MojiWeather.app/PlugIns/MojiWidget.appex/MojiWidget
Identifier:          com.moji.MojiWeather.MojiWidget
Version:             202003161753 (8.2.2)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.moji.MojiWeather.MojiWidget [2321]


Date/Time:           2020-04-08 00:00:15.4379 +0800
Launch Time:         2020-04-08 00:00:15.3452 +0800
OS Version:          iPhone OS 13.3.1 (17D50)
Release Type:        User
Baseband Version:    5.30.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dependent dylib '@rpath/MMKVAppExtension.framework/MMKVAppExtension' not found for '/private/var/containers/Bundle/Application/B8F000CE-ABE2-457C-A114-F58BCC26A13F/MojiWeather.app/PlugIns/MojiWidget.appex/MojiWidget', tried but didn't find: '/private/var/containers/Bundle/Application/B8F000CE-ABE2-457C-A114-F58BCC26A13F/MojiWeather.app/PlugIns/MojiWidget.appex/Frameworks/MMKVAppExtension.framework/MMKVAppExtension' '/private/var/containers/Bundle/Application/B8F000CE-ABE2-457C-A114-F58BCC26A13F/MojiWeather.app/PlugIns/MojiWidget.appex/../../Frameworks/MMKVAppExtension.framework/MMKVAppExtension' '@rpath/MMKVAppExtension.framework/MMKVAppExtension' '/System/Library/Frameworks/MMKVAppExtension.framework/MMKVAppExtension'
Highlighted by Thread:  0

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016b05e070   x3: 0x00000000000000cb
    x4: 0x000000016b05dc70   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x4d2f6b726f77656d  x11: 0x7845707041564b4d
   x12: 0x656d6172662e6e6f  x13: 0x4b4d4d2f6b726f77  x14: 0x6574784570704156  x15: 0x0020276e6f69736e
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016b05dc70  x21: 0x00000000000000cb  x22: 0x000000016b05e070  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000001054c4000  x26: 0x0000000000000001  x27: 0x00000001054c4000
   x28: 0x0000000000000000   fp: 0x000000016b05dc40   lr: 0x00000001054ae498
    sp: 0x000000016b05dc00   pc: 0x00000001054a75e4 cpsr: 0x00000000
   esr: 0x00000000  Address size fault

Binary images description not available

Error Formulating Crash Report:
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯

EOF

**Comment by lingol** [comment]
>Termination Description: DYLD, dependent dylib '@rpath/MMKVAppExtension.framework/MMKVAppExtension' not found for '/private/var/containers/Bundle/Application/B8F000CE-ABE2-457C-A114-F58BCC26A13F/MojiWeather.app/PlugIns/MojiWidget.appex/MojiWidget', tried but didn't find: '/private/var/containers/Bundle/Application/B8F000CE-ABE2-457C-A114-F58BCC26A13F/MojiWeather.app/PlugIns/MojiWidget.appex/Frameworks/MMKVAppExtension.framework/MMKVAppExtension' '/private/var/containers/Bundle/Application/B8F000CE-ABE2-457C-A114-F58BCC26A13F/MojiWeather.app/PlugIns/MojiWidget.appex/../../Frameworks/MMKVAppExtension.framework/MMKVAppExtension' '@rpath/MMKVAppExtension.framework/MMKVAppExtension' '/System/Library/Frameworks/MMKVAppExtension.framework/MMKVAppExtension'

You have forgotten to embed the dynamic framework. Add a **Copy File** phase to your target & copy the MMKVAppExtension.framework to the **Frameworks** folder.

**Comment by code1303009** [comment]
方式一：
![image](https://user-images.githubusercontent.com/3941156/78758452-bff60d80-79b0-11ea-9625-ff16c6d12053.png)

方式二：直接用pod方式在主app导入，将MMKVAppExtension.framework添加到工程内，关联引用到widget的对应target

你的意思是2种方式都可以，还是只能使用方式一

**Comment by code1303009** [comment]
> > Termination Description: DYLD, dependent dylib '@rpath/MMKVAppExtension.framework/MMKVAppExtension' not found for '/private/var/containers/Bundle/Application/B8F000CE-ABE2-457C-A114-F58BCC26A13F/MojiWeather.app/PlugIns/MojiWidget.appex/MojiWidget', tried but didn't find: '/private/var/containers/Bundle/Application/B8F000CE-ABE2-457C-A114-F58BCC26A13F/MojiWeather.app/PlugIns/MojiWidget.appex/Frameworks/MMKVAppExtension.framework/MMKVAppExtension' '/private/var/containers/Bundle/Application/B8F000CE-ABE2-457C-A114-F58BCC26A13F/MojiWeather.app/PlugIns/MojiWidget.appex/../../Frameworks/MMKVAppExtension.framework/MMKVAppExtension' '@rpath/MMKVAppExtension.framework/MMKVAppExtension' '/System/Library/Frameworks/MMKVAppExtension.framework/MMKVAppExtension'
> 
> You have forgotten to embed the dynamic framework. Add a **Copy File** phase to your target & copy the MMKVAppExtension.framework to the **Frameworks** folder.

![image](https://user-images.githubusercontent.com/3941156/78759019-94275780-79b1-11ea-9645-a6fc7116c229.png)
![image](https://user-images.githubusercontent.com/3941156/78759139-bc16bb00-79b1-11ea-9a72-662ae8c3e31c.png)

目前是这么引用的

**Comment by lingol** [comment]
Both. Remember to **embed** it if you choose to use a dynamic framework.

**Comment by code1303009** [comment]
您有聊天方式么 可以私信您么

**Comment by lingol** [comment]
Just release [v1.1.1](https://github.com/Tencent/MMKV/releases/tag/v1.1.1). 
You should check out the [wiki](https://github.com/Tencent/MMKV/wiki/iOS_tutorial) for the latest instruction about setting up MMKV with AppExtension & WatchExtension.
