### ISSUE TITLE
maven 同步com.tencent:mmkv-static:1.1.0 失败

### ISSUE THREAD

**Issue by onexuan** [Tencent/MMKV#422]
maven 同步com.tencent:mmkv-static:1.1.0 失败，没有找到

**Comment by lingol** [comment]
Check your network connection. Last time I check, it's there.
https://bintray.com/wemobiledev/maven/com.tencent:mmkv-static#files/com%2Ftencent%2Fmmkv-static%2F1.1.0

**Comment by onexuan** [comment]
it is OK
