### ISSUE TITLE
Crashed with NSFileProtectionCompleteUntilFirstUserAuthentication After upgraded v1.1.0

### ISSUE THREAD

**Issue by calvingit** [Tencent/MMKV#423]
### The language of MMKV

Objective-C

### The version of MMKV

v1.1.0

### The platform of MMKV

iOS

### The installation of MMKV

Cocoapods

### What's the issue?

After upgraded from 1.0.24, the App is crashed.

 I have added  initialize method in main thread: `[MMKV initializeMMKV:nil];`

Anything else should I do?
![1585199420590](https://user-images.githubusercontent.com/2109371/77612460-2ae02700-6f63-11ea-820d-fd257d3aac1c.jpg)

The Xcode console log:
```
 <MMKV.cpp:147::initialize> page size:16384
 <MMKV_OSX.cpp:59::minimalInit> default root dir: /var/mobile/Containers/Data/Application/F5B69EB9-5B1B-49CF-94C1-CCB72B2B095E/Documents/mmkv
 <MMKV.cpp:160::initializeMMKV> root dir: /var/mobile/Containers/Data/Application/F5B69EB9-5B1B-49CF-94C1-CCB72B2B095E/Documents/mmkv
 <MemoryFile_OSX.cpp:36::tryResetFileProtection> protection on [/var/mobile/Containers/Data/Application/F5B69EB9-5B1B-49CF-94C1-CCB72B2B095E/Documents/mmkv/mmkv.default] is NSFileProtectionCompleteUntilFirstUserAuthentication
 <MemoryFile_OSX.cpp:36::tryResetFileProtection> protection on [/var/mobile/Containers/Data/Application/F5B69EB9-5B1B-49CF-94C1-CCB72B2B095E/Documents/mmkv/mmkv.default.crc] is NSFileProtectionCompleteUntilFirstUserAuthentication
```

**Comment by lingol** [comment]
Which device did you run?

**Comment by lingol** [comment]
And do you have problems running the mmkvdemo app on the same device? If no, then something is wrong with your project config. We should find out.

**Comment by calvingit** [comment]
Hardware: iPad Air 2
System: iPadOS 13.3.1

The demo MMKVDemo for iOS also crashed

**Comment by lingol** [comment]
Did MMKVDemo also crash in the same function `__crc32w()`?

**Comment by lingol** [comment]
Borrowing an iPad Air2, I can reproduce this crash. Looking into it now.

**Comment by calvingit** [comment]
Some difference, MMKVDemo crash in `__crc32b()`. And It's the same with iPhone 5s.

**Comment by lingol** [comment]
You can check out the `dev` branch and see if things work.

**Comment by lingol** [comment]
Clean your local CocoaPods caches and install again. Things should work.
Paths to be clean: 
`~/Library/Caches/CocoaPods/Pods/Release/MMKVCore`
`~/Library/Caches/CocoaPods/Pods/Release/MMKV`
`~/Library/Caches/CocoaPods/Pods/External/MMKCore`
`~/Library/Caches/CocoaPods/Pods/External/MMK`
