### ISSUE TITLE
1.1.0   华为p30 pro 启动 crash

### ISSUE THREAD

**Issue by zhuangzhitu** [Tencent/MMKV#427]
The language of MMKV

 Java, or Kotlin

The version of MMKV

 v1.1.0

 Android

The installation of MMKV

Maven

### What's the issue?

启动crash :  

<img width="1770" alt="WechatIMG201" src="https://user-images.githubusercontent.com/13757638/77645971-a1e6e100-6f9e-11ea-8eac-83eacc5b9286.png">

**Comment by lingol** [comment]
Try `com.tencent.mmkv-static:1.1.0`.

**Comment by lingol** [comment]
MMKV previous v1.1.0 had disabled C++ exceptions. Starting from v1.1.0, MMKV uses a common Core library that uses C++ exception to make encoding/decoding more robust.
Now, if you have other 3rd libraries that also include libc++_shared.so while turning C++ exceptions off, you will likely face that **cannot locate symbol _Unwind_Resume** error.

**Comment by zhuangzhitu** [comment]
Thank you. I feel like I have to wait for 1.1.0 to be stable and then upgrade. For the moment, I will back 1.0.24 version, which seems to have some problems

**Comment by lingol** [comment]
Well, you should at least give it a try. Let's see if it crash again on com.tencent:mmkv-static. 
Would you do that for me?

**Comment by zhuangzhitu** [comment]
Ok. I will try it at work tomorrow and I will tell you the result.

**Comment by zhuangzhitu** [comment]
Hi, I'm using implementation 'com. Tencent: MMKV -static:1.1.0' no problem。Thanks

**Comment by lingol** [comment]
That's good to know.

**Comment by alhah** [comment]
> MMKV before v1.1.0 had disabled C++ exceptions. Starting from v1.1.0, MMKV uses the `Core` library that uses C++ exception to make encoding/decoding much more robust.
> Now, if you have other 3rd libraries that also include libc++_shared.so while turning C++ exceptions off, you will likely face that **can not locate symbol "_Unwind_Resume"** error.

Which ndk version mmkv build with? I think rebuild it with ndk r20 can fix this issue.

**Comment by lingol** [comment]
> > MMKV before v1.1.0 had disabled C++ exceptions. Starting from v1.1.0, MMKV uses the `Core` library that uses C++ exception to make encoding/decoding much more robust.
> 
> > Now, if you have other 3rd libraries that also include libc++_shared.so while turning C++ exceptions off, you will likely face that **can not locate symbol "_Unwind_Resume"** error.
> 
> 
> 
> Which ndk version mmkv build with? I think rebuild it with ndk r20 can fix this issue.

MMKV is compiled by ndk r16b, to support armeabi. I’m afraid that can’t be done.
Besides, Why ndk r20 can fix that?

**Comment by alhah** [comment]
libc++ r16: 

> > > MMKV before v1.1.0 had disabled C++ exceptions. Starting from v1.1.0, MMKV uses the `Core` library that uses C++ exception to make encoding/decoding much more robust.
> > 
> > 
> > > Now, if you have other 3rd libraries that also include libc++_shared.so while turning C++ exceptions off, you will likely face that **can not locate symbol "_Unwind_Resume"** error.
> > 
> > 
> > Which ndk version mmkv build with? I think rebuild it with ndk r20 can fix this issue.
> 
> MMKV is compiled by ndk r16b, to support armeabi. I’m afraid that can’t be done.
> Besides, Why ndk r20 can fix that?

Check symbol "_Unwind_Resume" with readelf:
libc++ r16:  **`GLOBAL`** DEFAULT   11 _Unwind_Resume
libc++ r20:  **`LOCAL`**  DEFAULT   11 _Unwind_Resume
mmkv : GLOBAL DEFAULT  **`UND`** _Unwind_Resume
Any so build with r20:  GLOBAL DEFAULT   **`11`** _Unwind_Resume, it's not **`UND`**
So use libc++ r16 or rebuild mmkv with r20 will fix  _Unwind_Resume issue.

**Comment by lingol** [comment]
@alhah That's good to know, thanks.
