### ISSUE TITLE
最新1.1.0版本的+ (void)onExit;方法名和libextobjc库的onExit宏定义重名了

### ISSUE THREAD

**Issue by xborong** [Tencent/MMKV#429]

**Comment by xborong** [comment]
SDWebImage也有onExit宏，建议MMKV改一下方法名吧，这个onExit宏算是业界比较通用的一个宏了

**Comment by lingol** [comment]
Noted.

**Comment by lingol** [comment]
Fixed in `dev` branch with commit. https://github.com/Tencent/MMKV/commit/072e2bb7226bb2f6635f10059e3ba362cd2969e8

Will be released on the next version. For the time being, you can just rename it to `onAppTerminate` in your local project.

**Comment by lingol** [comment]
Reopen this to prevent any duplicate reports...

**Comment by lingol** [comment]
Solved with [v1.1.1](https://github.com/Tencent/MMKV/releases/tag/v1.1.1).
