### ISSUE TITLE
Encrypting & Decrypting MMKV Instance

### ISSUE THREAD

**Issue by ammarahm-ed** [Tencent/MMKV#430]
MMKV Version: 1.1.0

Platform: Android 9

So I dont know if this is how MMKV is supposed to work but here is the problem I am facing:

1. I create an encrypted MMKV instance with a specific `cryptKey` and ID.

```java

MMKV kv = MMKV.mmkvWithID("myMMKVStorage", MMKV.SINGLE_PROCESS_MODE, "myencryptionkey");



```

2. Close the app and change the `cryptKey` I was using to something else. 

```java

MMKV kv = MMKV.mmkvWithID("myMMKVStorage", MMKV.SINGLE_PROCESS_MODE, "myencryptionkeychanged");

// A new instance is created on the same ID i used before because the cryptKey is changed. I does not throw any error or something.

```

3. Now when I reload the app, MMKV does not give me error that the `cryptKey` for the given mmkv Instance on the same ID is wrong. It creates a new instance with the same ID again and the new `cryptKey`. Is this normal behavior of MMKV? How do I know if I have given the wrong cryptKey for the Encrypted MMKV Instance? 

4. If I change the cryptKey back to the one I used to encrypt MMKV Instance initially, It. will again load the MMKV Instance I was trying to load actually.

```java

MMKV kv = MMKV.mmkvWithID("myMMKVStorage", MMKV.SINGLE_PROCESS_MODE, "myencryptionkey");



```

**Comment by lingol** [comment]
No. You should load MMKV with the old key, then change the encrypt key by calling `reKey()`.

**Comment by ammarahm-ed** [comment]
So by loading MMKV with a wrong key, it will not show any error?

**Comment by lingol** [comment]
The key is not stored in file. Just can be sure if the key is valid or not.

**Comment by ammarahm-ed** [comment]
I think It does not report. However I have found my answer here so thank you. I will close this issue now.

**Comment by tsdmrfth** [comment]
I've just noticed the same thing. Isn't that a security leak?
1. I create the instance with an ID and encryption key and then store some value on the storage.
2. Close the app and create an instance with the same ID as the previous one but with a different encryption key this time.
3.  Try to read the stored value at step 1 and it returns the stored value correctly. 

Is this normal behaviour?

**Comment by lingol** [comment]
> I've just noticed the same thing. Isn't that a security leak?
> 
> 1. I create the instance with an ID and encryption key and then store some value on the storage.
> 2. Close the app and create an instance with the same ID as the previous one but with a different encryption key this time.
> 3. Try to read the stored value at step 1 and it returns the stored value correctly.
> 
> Is this normal behaviour? If yes what's the point of encryption key then?

Are you sure about that? How about providing a demo project?

**Comment by tsdmrfth** [comment]
Yes, I am 100% sure.
I use react-native-mmkv library but since it's just a wrapper for this project I asked the question here.
I can provide a demo project running on Expo (React Native) if that's okay.

**Comment by lingol** [comment]
Sure, please.
>I can provide a demo project running on Expo (React Native) if that's okay.

**Comment by ammarahm-ed** [comment]
There's a high chance that before you read data from instance 2nd time with wrong key, you have already written data to it on app launch. Because mmkv doesn't throw error if key is incorrect, just creates an instance with the wrong key i guess.

**Comment by lingol** [comment]
> There's a high chance that before you read data from instance 2nd time with wrong key, you have already written data to it on app launch. Because mmkv doesn't throw error if key is incorrect, just creates an instance with the wrong key i guess.

That's exactly what I have wondered.

**Comment by tsdmrfth** [comment]
@ammarahm-ed Oh, it's my bad. Since it's a react native app I just tried it by reloading whole app instead of hard killing and restarting. So it works as expected.

**Comment by ammarahm-ed** [comment]
Proper way to test would be remove app from recents menu then relaunching it an testing.
