### ISSUE TITLE
Swift混编和ReactiveObjC函数名冲突的问题

### ISSUE THREAD

**Issue by devcxm** [Tencent/MMKV#432]
### The language of MMKV

> Objective-C, Swift

### The version of MMKV

> v1.1.0

### The platform of MMKV

>  iOS

### The installation of MMKV

>Cocoapods

### What's the issue?

我的项目主是要Objective-C编写，项目引入了`ReactiveObjC`库，现在准备使用Swift混编，在引入`MMKV`最新版本时，发现ReactiveObjC的宏定义`onExit`和MMKV的`+ (void)onExit;`方法冲突了，我把MMKV的`+ (void)onExit;`方法修改成其它名称后就不会报错了。我尝试新建项目pod引入`ReactiveObjC`和`MMKV`编译正常，但我项目使用CocoaPods组件化开发，依赖很复杂，暂时找不出依赖哪里出错了。所以请问下作者，能不能把MMKV的`+ (void)onExit;`改成其它名称(如`+ (void)mmkvOnExit;`)避免与其它库冲突？

https://github.com/Tencent/MMKV/blob/b02ae889e74f80d83ca498484d6bc99c1d0a53f7/iOS/MMKV/MMKV/MMKV.h#L79

https://github.com/ReactiveCocoa/ReactiveObjC/blob/master/ReactiveObjC/extobjc/EXTScope.h#L31-L33

![Jietu20200331-180632](https://user-images.githubusercontent.com/8568955/78014620-c82fc680-737a-11ea-913b-08fe8b51d96c.jpg)

**Comment by devcxm** [comment]
如果不是Swift混编编译不会报错

**Comment by lingol** [comment]
Duplicate with #429

**Comment by lingol** [comment]
Fixed with release [v1.1.1](https://github.com/Tencent/MMKV/releases/tag/v1.1.1).
