### ISSUE TITLE
mmkv1.1.0 集成报错

### ISSUE THREAD

**Issue by LionNeo** [Tencent/MMKV#435]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

// you can call this on applicationWillTerminate, it's totally fine if you don't call
+ (void)onExit; 
这一行报错提示: EXPECTED ‘;’ AFTER METHOD PROTOTYPE

**Comment by lingol** [comment]
Duplicate with #429 . This is the third duplication within three days. Your guys just don't search, ha.
Will fix asap.

**Comment by lingol** [comment]
Fixed with release [v1.1.1](https://github.com/Tencent/MMKV/releases/tag/v1.1.1).
