### ISSUE TITLE
安卓版本号1.0.23，未清除文件数据， 冷启动后获取不到key-value值，读取文件keys为空

### ISSUE THREAD

**Issue by healer-dream** [Tencent/MMKV#439]
### The language of MMKV
java
### The version of MMKV
1.0.23

### The platform of MMKV
Android

设备：OPPO R9s Plus

有用户反馈问题，查看日志是用户读取mmkv数据为空导致，用户使用应用过程中写入数据，未冷启动之前获取数据正常，冷启动过后读取mmkv数据为空，应用未在冷启动过程中有清除数据的操作

**Comment by lingol** [comment]
It's highly suspected that the file is corrupted. If you have logs you can provide them.
The newest release v1.1.0 has improvement about this, you should upgrade.

**Comment by shore-zzq** [comment]
Found same issues  v1.0.22

**Comment by lingol** [comment]
> Found same issues  v1.0.22

Upgrade to latest version. Come back if It still appears.
