### ISSUE TITLE
Crash when initialize MMKV after upgrade to v1.1.0

### ISSUE THREAD

**Issue by strangeliu** [Tencent/MMKV#440]
### The language of MMKV

> Swift

### The version of MMKV

> v1.1.0

### The platform of MMKV

> iOS

### The installation of MMKV

> CocoaPods with static linkage

### What's the issue?

升级到1.1.0版本后，线上用户反馈打开就闪退，目前只收集到一个crash日志，见图，降级到0.9版本后不再出现闪退情况。

<img width="558" alt="Screen Shot 2020-04-07 at 19 15 28" src="https://user-images.githubusercontent.com/5244588/78663391-9d0e1f80-7904-11ea-9dd5-10d33aaaee88.png">

**Comment by lingol** [comment]
duplicate with #423
