### ISSUE TITLE
iOSv1.1.0版本的mmkv怎么应用到手表app

### ISSUE THREAD

**Issue by code1303009** [Tencent/MMKV#441]

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/iOS_tutorial_cn#%E5%88%9D%E5%A7%8B%E5%8C%96-mmkv

**Comment by code1303009** [comment]
> https://github.com/Tencent/MMKV/wiki/iOS_tutorial_cn#%E5%88%9D%E5%A7%8B%E5%8C%96-mmkv

我的项目中存在widget、手表app和NotificationServices三种扩展，我使用的方式是在扩展应用中添加动态库MMKVAppExtension.framework方式。我是需要在3个扩展中每次都去添加MMKVAppExtension.framework库么？

**Comment by code1303009** [comment]
> https://github.com/Tencent/MMKV/wiki/iOS_tutorial_cn#%E5%88%9D%E5%A7%8B%E5%8C%96-mmkv

还是说只需要添加一次MMKVAppExtension.framework库文件，重复引用该库文件就可以

**Comment by lingol** [comment]
> > https://github.com/Tencent/MMKV/wiki/iOS_tutorial_cn#%E5%88%9D%E5%A7%8B%E5%8C%96-mmkv
> 
> 还是说只需要添加一次MMKVAppExtension.framework库文件，重复引用该库文件就可以

Yes.

**Comment by code1303009** [comment]
> > > https://github.com/Tencent/MMKV/wiki/iOS_tutorial_cn#%E5%88%9D%E5%A7%8B%E5%8C%96-mmkv
> > 
> > 
> > 还是说只需要添加一次MMKVAppExtension.framework库文件，重复引用该库文件就可以
> 
> Yes.

我是按照您给的方式去运行的，但是在WatchKit App Extension内部去调用MMKV就会报错
ld: warning: ignoring file /Users/wei.jiang/Desktop/iOSMojiWeatherBugfix/MMKVAppExtension.framework/MMKVAppExtension, building for watchOS-arm64_32 but attempting to link with file built for iOS Simulator-x86_64
Undefined symbols for architecture arm64_32:
  "_OBJC_CLASS_$_MMKV", referenced from:
      objc-class-ref in WatchToIOSSessionManager.o
ld: symbol(s) not found for architecture arm64_32
clang: error: linker command failed with exit code 1 (use -v to see invocation)

调用代码是这里
- (void)setUpSession {
    WCSession *session = [WCSession defaultSession];
    session.delegate = self;
    [session activateSession];
    [MMKV initializeMMKV:nil];
}

**Comment by lingol** [comment]
I see.

**Comment by lingol** [comment]
I believe there's no use for MMKV to run on Watch Apps--they run on different devices and not sharing the same directory anymore from WatchOS 2.0.
https://stackoverflow.com/questions/46140731/iphone-and-apple-watch-not-sharing-app-group

**Comment by code1303009** [comment]
> https://stackoverflow.com/questions/46140731/iphone-and-apple-watch-not-sharing-app-group

是的，手表app本身有一套wc的交互可以直接传送数据，我们工程目前是直接使用wc协议在主app和手表app之间传送数据。手表app的pod库引入只能在WatchKit App Extension内，但是我需要确认一下，mmkv目前有没有针对手表app的支持。换句话说，就是目前针对手表app的mmkv可以走得通的流程。

**Comment by lingol** [comment]
> > https://stackoverflow.com/questions/46140731/iphone-and-apple-watch-not-sharing-app-group
> 
> 是的，手表app本身有一套wc的交互可以直接传送数据，我们工程目前是直接使用wc协议在主app和手表app之间传送数据。手表app的pod库引入只能在WatchKit App Extension内，但是我需要确认一下，mmkv目前有没有针对手表app的支持。换句话说，就是目前针对手表app的mmkv可以走得通的流程。

Not supported for now. It's not even clear that `mmap()` works on WatchOS or not. Maybe later.

**Comment by code1303009** [comment]
> > > https://stackoverflow.com/questions/46140731/iphone-and-apple-watch-not-sharing-app-group
> > 
> > 
> > 是的，手表app本身有一套wc的交互可以直接传送数据，我们工程目前是直接使用wc协议在主app和手表app之间传送数据。手表app的pod库引入只能在WatchKit App Extension内，但是我需要确认一下，mmkv目前有没有针对手表app的支持。换句话说，就是目前针对手表app的mmkv可以走得通的流程。
> 
> Not supported for now. It's not even clear that `mmap()` works on WatchOS or not. Maybe later.

好的 非常感谢您

**Comment by lingol** [comment]
I have given it a try on  Watch. Looks like everything works fine. You can try it out on the `dev` branch with commit:
https://github.com/Tencent/MMKV/commit/7b553089874b2a4de0a5bed68e89f50e1b1b87a5 .

**Comment by code1303009** [comment]
> I have given it a try on  Watch. Looks like everything works fine. You can try it out on the `dev` branch with commit: [7b55308](https://github.com/Tencent/MMKV/commit/7b553089874b2a4de0a5bed68e89f50e1b1b87a5) .

我这边昨天手表app存在导入问题，导入MMKVAppExtension.framework库会报错product module name和product name，你这边是有做修改么

**Comment by lingol** [comment]
> > I have given it a try on  Watch. Looks like everything works fine. You can try it out on the `dev` branch with commit: [7b55308](https://github.com/Tencent/MMKV/commit/7b553089874b2a4de0a5bed68e89f50e1b1b87a5) .
> 
> 我这边昨天手表app存在导入问题，导入MMKVAppExtension.framework库会报错product module name和product name，你这边是有做修改么

Follow the demo project's setting.

**Comment by code1303009** [comment]
> > > I have given it a try on  Watch. Looks like everything works fine. You can try it out on the `dev` branch with commit: [7b55308](https://github.com/Tencent/MMKV/commit/7b553089874b2a4de0a5bed68e89f50e1b1b87a5) .
> > 
> > 
> > 我这边昨天手表app存在导入问题，导入MMKVAppExtension.framework库会报错product module name和product name，你这边是有做修改么
> 
> Follow the demo project's setting.

好的

**Comment by lingol** [comment]
Just release [v1.1.1](https://github.com/Tencent/MMKV/releases/tag/v1.1.1). 
You should check out the [wiki](https://github.com/Tencent/MMKV/wiki/iOS_setup) for the latest instruction about setting up MMKV with AppExtension & WatchExtension. [Chinese version](https://github.com/Tencent/MMKV/wiki/iOS_setup_cn).

**Comment by code1303009** [comment]
> Just release [v1.1.1](https://github.com/Tencent/MMKV/releases/tag/v1.1.1).
> You should check out the [wiki](https://github.com/Tencent/MMKV/wiki/iOS_setup) for the latest instruction about setting up MMKV with AppExtension & WatchExtension. [Chinese version](https://github.com/Tencent/MMKV/wiki/iOS_setup_cn).

好的
