### ISSUE TITLE
aidl compiling error

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#442]
MMKV, Android, 1.1.0
Got the following error while compiling.
```
> Task :mmkv:compileStaticCppReleaseAidl
aidl.exe E 04-09 16:46:43  7868 12828 aidl.cpp:581] refusing to generate code from aidl file defining parcelable
```
Please refer to https://stackoverflow.com/a/47455795/1078971 for how to remove this error.

**Comment by lingol** [comment]
Just ignore it. By the way, the link you provide does not answer the problem we face. 
Here's the correct one. https://stackoverflow.com/questions/49029520/android-studio-aidl-refusing-to-generate-code-from-aidl-file-defining-parcelabl
