### ISSUE TITLE
_MMKVLogWithLevel crash

### ISSUE THREAD

**Issue by linhanda** [Tencent/MMKV#443]
### The language of MMKV
> e.g. Objective-C
### The version of MMKV
> e.g. v1.0.23
### The platform of MMKV
> e.g. iOS
### The installation of MMKV
> e.g. Cocoapods

### What's the issue?
Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_malloc.dylib        	0x000000018ad4c0d0 nanov2_allocate_from_block + 8
1   libsystem_malloc.dylib        	0x000000018ad4b434 nanov2_allocate + 128
2   libsystem_malloc.dylib        	0x000000018ad4b368 nanov2_malloc + 64
3   libsystem_malloc.dylib        	0x000000018ad5225c default_zone_malloc + 76
4   libsystem_malloc.dylib        	0x000000018ad4f73c malloc_zone_malloc + 164
5   CoreFoundation                	0x000000018af79598 CFAllocatorAllocate + 108
6   CoreFoundation                	0x000000018b014600 __CFStrAllocateMutableContents + 100
7   CoreFoundation                	0x000000018b013ea8 __CFStringChangeSizeMultiple + 608
8   CoreFoundation                	0x000000018b00e89c __CFStringAppendBytes + 616
9   CoreFoundation                	0x000000018afff870 __CFStringAppendFormatCore + 10040
10  CoreFoundation                	0x000000018b000a1c _CFStringCreateWithFormatAndArgumentsAux2 + 156
11  CoreFoundation                	0x000000018b04cb78 _CFLogvEx2Predicate + 160
12  CoreFoundation                	0x000000018b04cdcc _CFLogvEx3 + 252
13  Foundation                    	0x000000018b438f64 _NSLogv.llvm.9441159058638075197 + 128
14  Foundation                    	0x000000018b438fb4 NSLog + 56
15  MMKV                          	0x000000010449e1a8 _MMKVLogWithLevel(MMKVLogLevel, char const*, char const*, int, NSString*, ...) + 74152 (MMKVLog.mm:58)
16  MMKV                          	0x000000010449d0d8 +[MMKV mmapKeyWithMMapID:relativePath:] + 69848 (MMKV.mm:1398)
17  MMKV                          	0x0000000104497d9c +[MMKV mmkvWithID:cryptKey:relativePath:] + 48540 (MMKV.mm:0)
18  MMKV                          	0x0000000104497c2c +[MMKV mmkvWithID:cryptKey:] + 48172 (MMKV.mm:0)
19  MMKV                          	0x0000000104497bdc +[MMKV mmkvWithID:] + 48092 (MMKV.mm:0)

**Comment by lingol** [comment]
It's crashed inside system lib, nothing we can do about that.
