### ISSUE TITLE
编译不过(gcc version 4.8.5)

### ISSUE THREAD

**Issue by fengqieer1988** [Tencent/MMKV#445]
linux环境编译不过，Target: x86_64-redhat-linux，gcc是4.8.5.
1)/data/roger/code/POSIX/demo/UnitTest.cpp:128:31: error: call of overloaded 'abs(float)' is ambiguous
解决：我改成fabs，然后头文件引用#include <math.h>

2）/data/roger/code/POSIX/demo/UnitTest.cpp:192:103: error: 'memcmp' was not declared in this scope
我引用#include <string.h>即可。

**Comment by lingol** [comment]
Thanks. Will fix soon.

**Comment by lingol** [comment]
Fixed in the `dev` branch. https://github.com/Tencent/MMKV/commit/db64061642bb10c52f3c799056850b9c6a8a6ca2

**Comment by lingol** [comment]
Solved with [v1.1.1](https://github.com/Tencent/MMKV/releases/tag/v1.1.1).
