### ISSUE TITLE
Error in ~MMKV() when m_crypter is null

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#448]
mmkv 1.1.1

Should we check if m_crypter is null before deleting it?
 
```
MMKV::~MMKV() {
    clearMemoryCache();

    delete m_crypter; // <- m_crypter may be a null value
    delete m_file;
...
```
https://github.com/Tencent/MMKV/blob/8d5302065ad6aeaf05d5a2910d287aeb1a25a5e4/Core/MMKV.cpp#L119

**Comment by lingol** [comment]
deleting a nullptr is considerable safe in c++.
