### ISSUE TITLE
项目中引入MMKVWatchExtension 报错

### ISSUE THREAD

**Issue by LionNeo** [Tencent/MMKV#449]
<img width="500" alt="1" src="https://user-images.githubusercontent.com/16424323/79216669-2cc14a00-7e80-11ea-807a-0b7446794b5a.png">

**Comment by lingol** [comment]
How did you set up the project, by CocoaPods or by sources?

**Comment by LionNeo** [comment]
通过cocoapods 方式引入的,xcode 是11.1.手表和手机各自引入了 MMKVWatchExtension 和 MMKVAppExtension

**Comment by lingol** [comment]
> 通过cocoapods 方式引入的,xcode 是11.1.手表和手机各自引入了 MMKVWatchExtension 和 MMKVAppExtension

Which version of Xcode do you use? Xcode 10.x or Xcode 11.x?

**Comment by lingol** [comment]
I can't reproduce this error. You can provide me a demo project. guoling@tencent.com

**Comment by LionNeo** [comment]
我使用的是 xcode 11.x

**Comment by lingol** [comment]
It turns out this is a bug in the **Legacy Build System**. Switch to **New Build System** and the error is gone.
Here's how to switch it: _File -> Workspace Settings -> Build System -> New Build System._
