### ISSUE TITLE
mmkv crash when encodeString

### ISSUE THREAD

**Issue by wjxfhxy** [Tencent/MMKV#451]
### The language of MMKV
 Kotlin

### The version of MMKV
v1.1.0

### The platform of MMKV
 Android

### The installation of MMKV
implementation 'com.tencent:mmkv:1.1.0'

### What's the issue?
crash !!   ---->  SIGBUS (signal SIGBUS: illegal address)

the stack above

-------------------------------------------------------------------------

memcpy 0x0000007987331e84
___lldb_unnamed_symbol216$$libmmkv.so 0x0000007967f174c0
___lldb_unnamed_symbol102$$libmmkv.so 0x0000007967f0f538
___lldb_unnamed_symbol101$$libmmkv.so 0x0000007967f0f3c0
___lldb_unnamed_symbol118$$libmmkv.so 0x0000007967f10bfc
___lldb_unnamed_symbol38$$libmmkv.so 0x0000007967f0af9c
encodeString 0x0000007968706980
art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*) 0x0000007984114e4c
art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842bf4bc
bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842b9b84
bool art::interpreter::DoInvoke<(art::InvokeType)1, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842e5598
art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842de488
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a964
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842a1000
bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842ba2f4
bool art::interpreter::DoInvoke<(art::InvokeType)2, false, true>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842d0b5c
art::JValue art::interpreter::ExecuteSwitchImpl<true, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842cd2f0
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a9dc
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842a1000
bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842ba2f4
bool art::interpreter::DoInvoke<(art::InvokeType)2, false, true>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842d0b5c
art::JValue art::interpreter::ExecuteSwitchImpl<true, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842cd2f0
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a9dc
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842a1000
bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842b9b64
bool art::interpreter::DoInvoke<(art::InvokeType)0, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842e6a98
art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842de074
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a964
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842a1000
bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842b9b64
bool art::interpreter::DoInvoke<(art::InvokeType)0, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842e6a98
art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842de074
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a964
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842a1000
bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842b9b64
bool art::interpreter::DoInvoke<(art::InvokeType)0, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842e6a98
art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842de074
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a964
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842a1000
bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842b9b64
bool art::interpreter::DoInvoke<(art::InvokeType)4, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842e5ff8
art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842df340
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a964
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842a1000
bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842b9b64
bool art::interpreter::DoInvoke<(art::InvokeType)2, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842e3e1c
art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842e18b8
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a964
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842a1000
bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842b9b64
bool art::interpreter::DoInvoke<(art::InvokeType)4, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842e5ff8
art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842df340
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a964
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842a1000
bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842ba2f4
bool art::interpreter::DoInvoke<(art::InvokeType)2, false, true>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842d0b5c
art::JValue art::interpreter::ExecuteSwitchImpl<true, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842cd2f0
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a9dc
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842a1000
bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842ba2f4
bool art::interpreter::DoInvoke<(art::InvokeType)1, false, true>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842d3230
art::JValue art::interpreter::ExecuteSwitchImpl<true, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842c9f14
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a9dc
art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*) 0x00000079842a1000
bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842b9b64
bool art::interpreter::DoInvoke<(art::InvokeType)0, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*) 0x00000079842e6a98
art::JValue art::interpreter::ExecuteSwitchImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x00000079842de074
art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool) 0x000000798429a964
artQuickToInterpreterBridge 0x0000007984525b18
art_quick_to_interpreter_bridge 0x0000007984553820
art_quick_invoke_stub 0x000000798454a388
art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*) 0x0000007984114e4c
art::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::ArgArray*, art::JValue*, char const*) 0x000000798446e2d0
art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*) 0x000000798446f45c
art::Thread::CreateCallback(void*) 0x00000079844989d4
__pthread_start(void*) 0x000000798737a7f4
__start_thread 0x00000079873332f8

--------------------------------------------------------------

**Comment by lingol** [comment]
I can't symbolize your call stack with any arch of v1.1.0's library. Maybe you should symbolize them.
>___lldb_unnamed_symbol216$$libmmkv.so 0x0000007967f174c0
>___lldb_unnamed_symbol102$$libmmkv.so 0x0000007967f0f538
>___lldb_unnamed_symbol101$$libmmkv.so 0x0000007967f0f3c0
>___lldb_unnamed_symbol118$$libmmkv.so 0x0000007967f10bfc
>___lldb_unnamed_symbol38$$libmmkv.so 0x0000007967f0af9c

**Comment by lingol** [comment]
Also, logs & a reproducible demo project are always welcome.

**Comment by wjxfhxy** [comment]
> Also, logs & a reproducible demo project are always welcome.

# main(16069)

SIGBUS(BUS_ADRERR)

1 #00 pc 000000000006ab34 /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy+356) [arm64-v8a]
--
2 #01 pc 00000000000102fc /data/app/com.xuanwu.apaas.app-g9bAYC6DOUyoLpauxglX1A==/lib/arm64/libmmkv.so [arm64-v8a]
3 java:
4 [Failed to get java stack]


and, I found many many this crash in Bugly

**Comment by lingol** [comment]
Again, symbolize your stack before posting. And logs please.

**Comment by wjxfhxy** [comment]
我更新了v1.1.1版本，并把源码整合到我在用的工程，终于在崩溃时定位到出现问题的地方
但这是原因引起的？

---mmkv::CodedOutputData::writeRawByte(unsigned char) CodedOutputData.cpp:118
---mmkv::CodedOutputData::writeRawVarint32(int) CodedOutputData.cpp:135
---mmkv::CodedOutputData::writeString(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) CodedOutputData.cpp:85
---MMKV::appendDataWithKey(mmkv::MMBuffer const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) MMKV.cpp:797
---MMKV::setDataForKey(mmkv::MMBuffer&&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) MMKV.cpp:735
---MMKV::set(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) MMKV.cpp:1105
---mmkv::encodeString(_JNIEnv*, _jobject*, long long, _jstring*, _jstring*) native-bridge.cpp:461
<unknown> 0x00000000b52e543d

**Comment by lingol** [comment]
The code on `CodedOutputData.cpp:118` is

```cpp
    m_ptr[m_position++] = value;
```

Looks like the memory is not valid. 
Can you provide the logs of MMKV from the logcat when this crash happens?

**Comment by wjxfhxy** [comment]
每天都会有两到三次的崩溃，还是比较频繁的...........

崩溃时logcat记录到关于mmkv的日志如下

2020-05-08 10:01:22.143 28892-29820/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:481::clearAll> cleaning all key-values from [mmkv.default]
2020-05-08 10:01:22.144 28892-29820/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:509::clearMemoryCache> clearMemoryCache [mmkv.default]
2020-05-08 10:01:22.144 28892-29820/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:263::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3
2020-05-08 10:01:22.144 28892-29820/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:296::loadFromFile> loaded [mmkv.default] with 0 values
2020-05-08 10:01:24.654 28892-28892/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:617::ensureMemorySize> extending [mmkv.default] file size from 4096 to 8192, incoming size:644, future usage:5192
2020-05-08 10:02:03.271 28892-29820/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:481::clearAll> cleaning all key-values from [mmkv.default]
2020-05-08 10:02:03.272 28892-29820/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:509::clearMemoryCache> clearMemoryCache [mmkv.default]
2020-05-08 10:02:03.273 28892-29820/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:263::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3
2020-05-08 10:02:03.273 28892-29820/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:296::loadFromFile> loaded [mmkv.default] with 0 values
2020-05-08 10:02:12.426 28892-28892/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:617::ensureMemorySize> extending [mmkv.default] file size from 4096 to 8192, incoming size:650, future usage:5240
2020-05-08 10:02:25.769 28892-29819/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:481::clearAll> cleaning all key-values from [mmkv.default]
2020-05-08 10:02:25.769 28892-29819/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:509::clearMemoryCache> clearMemoryCache [mmkv.default]
2020-05-08 10:02:25.769 28892-29819/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:263::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3
2020-05-08 10:02:25.769 28892-29819/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:296::loadFromFile> loaded [mmkv.default] with 0 values
2020-05-08 10:02:25.975 28892-28892/com.xuanwu.apaas.app I/MMKV: <MMKV.cpp:617::ensureMemorySize> extending [mmkv.default] file size from 4096 to 8192, incoming size:650, future usage:5240

**Comment by lingol** [comment]
>2020-05-08 10:01:22.144 28892-29820/com.xuanwu.apaas.app I/MMKV: MMKV.cpp:263::loadFromFile loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3

Is it possible that you access the default MMKV instance in multi-process? The default MMKV instance is loaded as single-process mode according to your log, aka `InterProcess 0`.

**Comment by lingol** [comment]
You can verify that by loading the default MMKV by `MULTI_PROCESS_MODE` mode:
`MMKV.defaultMMKV(int mode, String cryptKey)`

**Comment by wjxfhxy** [comment]
我们只在多线程（multi-thread）中使用，并不涉及multi-process，我试试你的建议

**Comment by lingol** [comment]
Hi, how did it go?

**Comment by lingol** [comment]
Hey, any update yet?

**Comment by wjxfhxy** [comment]
加上MULTI_PROCESS_MODE后，目前并没有发现崩溃
