### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by andyhaha** [Tencent/MMKV#452]
mmkv version: com.tencent:mmkv-static:1.1.1"

Caused by:
 java.lang.UnsatisfiedLinkError:dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/hwkeystore.jar", zip file "/data/app/com.xueqiu.android-WSVESjU78glCTzFHnFpkQA==/base.apk"],nativeLibraryDirectories=[/data/app/com.xueqiu.android-WSVESjU78glCTzFHnFpkQA==/lib/arm, /data/app/com.xueqiu.android-WSVESjU78glCTzFHnFpkQA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]] couldn't find "libmmkv.so"
 java.lang.Runtime.loadLibrary0(Runtime.java:1011)
 java.lang.System.loadLibrary(System.java:1660)
com.tencent.mmkv.MMKV.initialize(MMKV.java:96)
com.tencent.mmkv.MMKV.initialize(MMKV.java:67)

help!

**Comment by lingol** [comment]
> couldn't find "libmmkv.so"

It's been told. Solve it yourself.

**Comment by andyhaha** [comment]
> > couldn't find "libmmkv.so"
> 
> It's been told. Solve it yourself.

how to resolve this problem，I have no idea

**Comment by lingol** [comment]
Check your apk to see if it's there. Reinstall the apk to see if there's something wrong on installing.
The **ReLinker** framework on the [FAQ](https://github.com/Tencent/MMKV/wiki/FAQ) also worth a try.

**Comment by andyhaha** [comment]
I analysis my apk with android studio，and find libmmkv.so in x86 and armeabi-v7a folder

**Comment by andyhaha** [comment]
in additional，it is a online crash error，the device is HuaWei phone，device modle 华为EDI AL10 and 华为EVE AL00，system version is 8.0.0

**Comment by andyhaha** [comment]
> Check your apk to see if the so is there. Reinstall the apk to see if there's something wrong on installing.
> The **ReLinker** framework on the [FAQ](https://github.com/Tencent/MMKV/wiki/FAQ) also worth a try.

I also tried this way，but it crashed Immediately

**Comment by lingol** [comment]
You crashed on ReLinker? That doesn't make sense.

**Comment by andyhaha** [comment]
> You crashed on ReLinker? That doesn't make sense.

no，it crashed online device，and I tried ReLinker to initialize mmkv in my device，then it crashed Immediately

crash info：
 java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.mmkv.MMKV.jniInitialize(java.lang.String, int) (tried Java_com_tencent_mmkv_MMKV_jniInitialize and Java_com_tencent_mmkv_MMKV_jniInitialize__Ljava_lang_String_2I)

user ReLinker：
String root = context.getFilesDir().getAbsolutePath() + "/mmkv";
                try {
                    MMKV.initialize(root, libName -> {
                        try {
                            DLog.INSTANCE.d("ReLinker loadLibrary libName = " + libName);
                            ReLinker.loadLibrary(context, libName, new ReLinker.LoadListener() {
                                @Override
                                public void success() {
                                    DLog.INSTANCE.d("ReLinker loadLibrary success libName = " + libName);
                                }

                                @Override
                                public void failure(Throwable t) {
                                    DLog.INSTANCE.e("ReLinker loadLibrary failure libName = " + libName, t);
                                }
                            });
                        } catch (Throwable throwable) {
                            // ignore
                            DLog.INSTANCE.e(throwable);
                        }
                    });
                } catch (Throwable throwable) {
                    DLog.INSTANCE.e(throwable);
                }

**Comment by andyhaha** [comment]
in additional, I upgrade mmkv from "com.tencent:mmkv:1.0.22" to "com.tencent:mmkv-static:1.1.1", then the crashes grows suddenly. is there any differences bettween the two versions.
I have made great effort but no effect. There's no choice but to ask for help!

**Comment by andyhaha** [comment]
mmkv version: com.tencent:mmkv-static:1.1.1"

Caused by:
 java.lang.UnsatisfiedLinkError:dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/hwkeystore.jar", zip file "/data/app/com.xueqiu.android-WSVESjU78glCTzFHnFpkQA==/base.apk"],nativeLibraryDirectories=[/data/app/com.xueqiu.android-WSVESjU78glCTzFHnFpkQA==/lib/arm, /data/app/com.xueqiu.android-WSVESjU78glCTzFHnFpkQA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]] couldn't find "libmmkv.so"
 java.lang.Runtime.loadLibrary0(Runtime.java:1011)
 java.lang.System.loadLibrary(System.java:1660)
com.tencent.mmkv.MMKV.initialize(MMKV.java:96)
com.tencent.mmkv.MMKV.initialize(MMKV.java:67)

it crashed online and I analsed my apk in android studio，mmkv.so is fund in armeabi-v7a and x86 folder. I have no choice but ask for help.

**Comment by NiaNingXue** [comment]
same issue

**Comment by lingol** [comment]
> same issue

Same answer.

**Comment by RitaLing** [comment]
java.lang.UnsatisfiedLinkError:
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1012)
  at java.lang.System.loadLibrary (System.java:1669)
  at com.tencent.mmkv.MMKV.initialize (MMKV.java:100)
  at com.tencent.mmkv.MMKV.initialize (MMKV.java:69)

The same crash！ Happended some online.

**Comment by lingol** [comment]
> java.lang.UnsatisfiedLinkError:
> at java.lang.Runtime.loadLibrary0 (Runtime.java:1012)
> at java.lang.System.loadLibrary (System.java:1669)
> at com.tencent.mmkv.MMKV.initialize (MMKV.java:100)
> at com.tencent.mmkv.MMKV.initialize (MMKV.java:69)
> 
> The same crash！ Happended some online.

https://github.com/Tencent/MMKV/wiki/FAQ

**Comment by wlj190785060** [comment]
一样的奔溃，也是偶发，如果包有问题，怎么解释大部分用户是好的呢？另外，使用了Relink，部分用户开始报com.getkeepsafe.relinker.MissingLibraryException。我看到issues中有很多mmkv.so报错的问题，但是没有一个好的解决方案，统一的回复都是你的包坏了，或者你的ide有问题。

**Comment by lingol** [comment]
> 一样的奔溃，也是偶发，如果包有问题，怎么解释大部分用户是好的呢？另外，使用了Relink，部分用户开始报com.getkeepsafe.relinker.MissingLibraryException。我看到issues中有很多mmkv.so报错的问题，但是没有一个好的解决方案，统一的回复都是你的包坏了，或者你的ide有问题。

You are asking a question at the wrong place. Ask it at Android. Or, ask it at the device manufacturer. There's nothing we the library writer can do about failing to load a dynamic library. The truth is just that simple. It's not that we don't want to help you.

**Comment by 532922397** [comment]
请问mmkv的java层有提供拦截这种崩溃的能力吗？

**Comment by 532922397** [comment]
> > 一样的奔溃，也是偶发，如果包有问题，怎么解释大部分用户是好的呢？另外，使用了Relink，部分用户开始报com.getkeepsafe.relinker.MissingLibraryException。我看到issues中有很多mmkv.so报错的问题，但是没有一个好的解决方案，统一的回复都是你的包坏了，或者你的ide有问题。
> 
> You are asking a question at the wrong place. Ask it at Android. Or, ask it at the device manufacturer. There's nothing we the library writer can do about failing to load a dynamic library. The truth is just that simple. It's not that we don't want to help you.

请问mmkv的java层有提供拦截这种崩溃的能力吗？
