### ISSUE TITLE
"You should Call MMKV.initialize() first." On Huawei decices.

### ISSUE THREAD

**Issue by zhaobozhen** [Tencent/MMKV#453]
### The language of MMKV

Kotlin

### The version of MMKV

v1.1.1

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?

I have already call MMKV.initialise(application) in Application#onCreate function. But on many Huawei devices(eg. Honor 10, EMUI 8.1 or Honor V20, EMUI10.1),they also report errors like "You should Call MMKV.initialize() first.". I have no ideas.

**Comment by lingol** [comment]
Neither do I.

**Comment by lingol** [comment]
MMKV will complain about that when the **root directory** is not set or set with nil.
https://github.com/Tencent/MMKV/blob/ed194ddef9611cecad371e8bd32777e699a4c95c/Android/MMKV/mmkv/src/main/java/com/tencent/mmkv/MMKV.java#L151

**Comment by zhaobozhen** [comment]
If I call MMKV.initialize(application), it will use `context.getFilesDir().getAbsolutePath() + "/mmkv"` as the default dir. So I think maybe I call MMKV#mmkvWithID method before initialzing unintentional. Is MMKV#initialize an asynchronous method? 

```kotlin
fun init(application: AnywhereApplication) {
        initMMKV(application)
        setLogger()
        setTheme(GlobalValues.darkMode)
        initIconPackManager()
        setDate()
        initToken()
    }
```

I managed all the MMKV operations in the GlobalValues class and used it immediately after initializing the MMKV. Is this the correct way to use？

This is my GlobalValues class.

```kotlin
object GlobalValues {

    private val mmkv: MMKV = MMKV.mmkvWithID(SPUtils.sPName)

    var isStreamCardMode
        get() = mmkv.decodeBool(Const.PREF_STREAM_CARD_MODE)
        set(value) {
            mmkv.encode(Const.PREF_STREAM_CARD_MODE, value)
        }

    var isStreamCardModeSingleLine
        get() = mmkv.decodeBool(Const.PREF_STREAM_CARD_SINGLE_LINE)
        set(value) {
            mmkv.encode(Const.PREF_STREAM_CARD_SINGLE_LINE, value)
        }

    var isMd2Toolbar
        get() = mmkv.decodeBool(Const.PREF_MD2_TOOLBAR)
        set(value) {
            mmkv.encode(Const.PREF_MD2_TOOLBAR, value)
        }
    ...
}
```

**Comment by lingol** [comment]
> So I think maybe I call MMKV#mmkvWithID method before initialzing unintentional.
I don't have a Huawei Honor device, so you have to check it yourself.

>Is MMKV#initialize an asynchronous method?
NO.

**Comment by zhaobozhen** [comment]
Ok, I will check it. Thanks a lot!
