### ISSUE TITLE
IOS 编译问题 No member named 'armv8_crc32' in namespace 'mmkv'

### ISSUE THREAD

**Issue by oangkin** [Tencent/MMKV#456]
MMKVCore/Core/MMKV_OSX.cpp:93:9: Use of undeclared identifier 'CRC32'
MMKVCore/Core/MMKV_OSX.cpp:93:23: No member named 'armv8_crc32' in namespace 'mmkv'
No member named 'armv8_crc32' in namespace 'mmkv'

**Comment by lingol** [comment]
Duplicate with #444.

**Comment by lingol** [comment]
Fixed in [v1.2.0](https://github.com/Tencent/MMKV/releases/tag/v1.2.0).
