### ISSUE TITLE
[Android端]如何比较方便的查看MMKV中存储的数据?

### ISSUE THREAD

**Issue by jiangkang** [Tencent/MMKV#457]
### The language of MMKV

Java, and Kotlin

### The version of MMKV

1.1.0

### The platform of MMKV

Android

### The installation of MMKV

Maven 

### What's the issue?

有没有什么比较方便的办法查看存储在MMKV中的数据?(不希望在项目中使用代码进行遍历)

**Comment by lingol** [comment]
No such tools for now. There are some 3rd tools you can checkout, though not very perfect. #383

**Comment by pengwei1024** [comment]
I developed a MMKV reading tool on macos, welcome to try [https://github.com/pengwei1024/MMKVReader](https://github.com/pengwei1024/MMKVReader)

**Comment by lingol** [comment]
> I developed a MMKV reading tool on macos, welcome to try https://github.com/pengwei1024/MMKVReader

That's good job, thanks.
