### ISSUE TITLE
Mac OS 10.15.4 setString:(NSString *)value forKey:(NSString *)key 写入失败 

### ISSUE THREAD

**Issue by sunleic** [Tencent/MMKV#458]
### The language of MMKV

> Objective-C

### The version of MMKV

> v1.1.1

### The platform of MMKV

> Mac OS 10.15.4

### The installation of MMKV

> Cocoapods

### What's the issue?

用setString:(NSString *)value forKey:(NSString *)key缓存数据之后，然后调用- (nullable NSString *)getStringForKey:(NSString *)key获取不到存储的值

**Comment by lingol** [comment]
Logs, please?

**Comment by lingol** [comment]
Have you tried the **MMKVMacDemo** from the demo project? Did it fail to decode as well?

**Comment by lingol** [comment]
Are you still there? Issues that lacks input will be closed.

**Comment by lingol** [comment]
Close due to inactive.
