### ISSUE TITLE
Fail to install v1.1.2 via Cocoapods

### ISSUE THREAD

**Issue by lingol** [Tencent/MMKV#463]
### The version of MMKV

> e.g. v1.1.2

### The platform of MMKV

> iOS / macOS

### The installation of MMKV

> Cocoapods

### What's the issue?

Fail to upgrade to v1.1.2 via Cocoapods. This is [a known issue](https://github.com/CocoaPods/CocoaPods/issues/9828) due to some bug of the Cocoapods CDN server.
For the time being, you can add this line to your Podfile:  
```
source 'https://github.com/CocoaPods/Specs.git'
```
Aka using GitHub instead of CDN to fetch Cocoapods specs.

**Comment by canberksinangil** [comment]
https://github.com/CocoaPods/CocoaPods/issues/9827
