### ISSUE TITLE
[!] CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/8/8/5/MMKV/1.1.2/MMKV.podspec.json Response: SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by KeynoWu** [Tencent/MMKV#464]
### The language of MMKV

>OC

### The version of MMKV

>现版本1.1.1，更新到1.1.2

### The platform of MMKV

> iOS

### The installation of MMKV

> Cocoapods

### What's the issue?

pod install之后就会报这个错误
[!] CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/8/8/5/MMKV/1.1.2/MMKV.podspec.json Response: SSL peer certificate or SSH remote key was not OK

**Comment by lingol** [comment]
I believe you should ask the Cocoapods guys.

**Comment by lingol** [comment]
https://github.com/CocoaPods/CocoaPods/issues/9834

**Comment by lingol** [comment]
Looks like CocoaPods has fixed it. It should be OK now.
