### ISSUE TITLE
我用简单的for循环测试发现mmkv的效率远远低于NSUserdefaults的效率，并且1.0版本低于0.x版本

### ISSUE THREAD

**Issue by RhettTamp** [Tencent/MMKV#465]
NSTimeInterval startTime = CACurrentMediaTime();
    for (int i = 0; i < 100000; i++) {
//        [[NSUserDefaults standardUserDefaults] setObject:[NSString stringWithFormat:@"str %d",i] forKey:[NSString stringWithFormat:@"str %d",i]];
        [[NSUserDefaults standardUserDefaults] objectForKey:[NSString stringWithFormat:@"str %d",i]];
//        [[NSUserDefaults standardUserDefaults] synchronize];
    }
    NSTimeInterval end = CACurrentMediaTime();
    NSTimeInterval interval = (end - startTime) * 1000;
    
    startTime = CACurrentMediaTime();
    for (int i = 0; i < 100000; i++) {
//        [[MMKV defaultMMKV] setObject:[NSString stringWithFormat:@"str %d",i] forKey:[NSString stringWithFormat:@"str %d",i]];
        [[MMKV defaultMMKV] getObjectOfClass:[NSString class] forKey:[NSString stringWithFormat:@"str %d",i]];
    }
    end = CACurrentMediaTime();
    interval = (end - startTime) * 1000;

上面是我简单测试的代码，不知道这个测试代码有说服力吗

**Comment by lingol** [comment]
I don't see much difference between them, running on MMKV v1.1.2. 

Did you run MMKV older than [v1.0.24](https://github.com/Tencent/MMKV/releases/tag/v1.0.24)? I suspect so. You can try 
1. Upgrade MMKV to the latest version, or
2. Move the `[MMKV defaultMMKV]` call outside of the loop, use a temp instance instead.

**Comment by RhettTamp** [comment]
对我用的1.0.23，但是我现在的问题是1.0.23这个版本的性能要比1.1.1号，但是性能都要差与NSUserdefaults

**Comment by lingol** [comment]
What do you mean by saying that v1.1.1 is worst than v1.0.23? Any proves?

**Comment by RhettTamp** [comment]
就是上面这个简单的例子，同样的代码使用1.1.1比1.0.23耗时。另外也比NSUserdefaults耗时

**Comment by RhettTamp** [comment]
还有个问题就是我在测试中发现iPhone xs（iOS13）的耗时也高于iPhone 7（iOS11）

**Comment by RhettTamp** [comment]
经过你的提醒，把+[MMKV defaultMMKV]放外面后没有这么耗时。所以是+[MMKV defaultMMKV]这个方法本身的开销就很大，包括1.0.23还是1.1.1版本，1.1.1甚至比1.0.23耗时。测试例子如下：
```
    for (int i = 0; i < 10000; i++) {
        MMKV *m = [MMKV defaultMMKV];
    }
```

**Comment by lingol** [comment]
> 经过你的提醒，把+[MMKV defaultMMKV]放外面后没有这么耗时。所以是+[MMKV defaultMMKV]这个方法本身的开销就很大，包括1.0.23还是1.1.1版本，1.1.1甚至比1.0.23耗时。测试例子如下：
> 
> ```
>     for (int i = 0; i < 10000; i++) {
>         MMKV *m = [MMKV defaultMMKV];
>     }
> ```

That doesn't make sense. MMKV has improved the cost of getting an instance since v1.0.24.
Are you sure you are using v1.1.1? What about v1.0.24 or v1.1.2?

**Comment by lingol** [comment]
Why not just use the mmkvdemo project to test performance that comes with MMKV? There's a much more reliable baseline test inside.

**Comment by lingol** [comment]
> 还有个问题就是我在测试中发现iPhone xs（iOS13）的耗时也高于iPhone 7（iOS11）

Doesn't make sense as well. You should run the mmkvdemo project instead.

**Comment by RhettTamp** [comment]
嗯，使用你们的demo发现，在写的效率上mmkv确实很高。但是对于读来说，由于demo中的写和读是在一次启动过程中，这样其实走的是内存缓存，并没有走IO ，如果换成下一次启动来读数据话其实是NSUserdefaults效率更高的。
另外，MMKVLogLevel的默认值是MMKVLogInfo，但是我看MMKVLogInfo的log有点多，刚刚我这个测试耗时的原因就是多次调用了`+[MMKV defaultMMKV]`，而`+[MMKV defaultMMKV]`的主要耗时就是NSLog，建议默认可以改一下或者给个提示，可能大多数使用者没有注意会使用默认level。

**Comment by RhettTamp** [comment]
感谢回答，知道原因了，是因为我没有调用`+[MMKV initializeMMKV]`
