### ISSUE TITLE
1.1.2版本相对1.0.23版本性能有所下降

### ISSUE THREAD

**Issue by RhettTamp** [Tencent/MMKV#466]
在iPhone 7（iOS11）上面测试发现1.1.2相较1.0.23版本性能有说下降，这个是什么原因呀？
iPhone 7    （1.0.23）
![image](https://user-images.githubusercontent.com/15962636/84118936-43da7d80-aa66-11ea-9df9-a43b60dd895c.png)
![image](https://user-images.githubusercontent.com/15962636/84118964-4e951280-aa66-11ea-8230-84d5b00806ea.png)
iPhone 7  （1.1.2）
![image](https://user-images.githubusercontent.com/15962636/84118999-5b196b00-aa66-11ea-93a5-1fe8dfb06721.png)
![image](https://user-images.githubusercontent.com/15962636/84119010-5f458880-aa66-11ea-9c50-a7bafe237da1.png)

**Comment by lingol** [comment]
Stick to the **mmkvdemo** project for the baseline performance testing.
In face, v1.1.0 and above have some improvement than older versions.

**Comment by lingol** [comment]
One little hint, when doing performance testing, you should avoid any time-consuming things such as string allocation & deallocation.

**Comment by RhettTamp** [comment]
这个测试已经足够简单并且保证了所有条件的一致性，看起来没有其它能够影响性能的地方，虽然这里有字符串创建，但是他们的条件是一样的

**Comment by lingol** [comment]
If you are really curious about this specific case, you can just run it on the **Instrument** tools in Xcode. 
It will give you a clear view of each function's cost.

**Comment by lingol** [comment]
Did you try to instrument those cases? What does it tell you?

**Comment by RhettTamp** [comment]
我使用mmkvdemode中的性能测试进行测试结果和上面一致，以下是测试数据：

**Comment by RhettTamp** [comment]
但是使用instruments结论却又相反，暂时还不知道原因，希望你们可以看一下这个问题
![image](https://user-images.githubusercontent.com/15962636/84744509-f4f09300-afe5-11ea-86b2-f638b27f2d0e.png)
![image](https://user-images.githubusercontent.com/15962636/84744547-0043be80-afe6-11ea-8ca1-312e45d300a8.png)
上面图片是使用1.0.23版本，下面图片是使用1.1.2版本
