### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fazhongxu** [Tencent/MMKV#467]
### The language of MMKV

Java

### The version of MMKV

1.1.0

### The platform of MMKV

android （OPPO Reno ACE Android9.0，OPPO R15 Android9.0）

### The installation of MMKV

maven implementation

### What's the issue?

![image](https://user-images.githubusercontent.com/24353536/84126646-c5370d80-aa70-11ea-8d56-f2288bfe9aa8.png)

Caused by: com.getkeepsafe.relinker.MissingLibraryException: libmmkv.so

直接运行就报错，打包安装就不会错，不用 ReLinker 报错，用了也报错，错误日志如图，尝试了几台设备（小米，华为，乐视）都没问题，就这OPPO报错了,尝试过升级到1.1.2一样报错

**Comment by lingol** [comment]
Something is wrong with your IDE. There's nothing we (the library devs) can do about it.
I recommend you check your IDE settings, try things such as invalid cache & restart and stuff like that.
