### ISSUE TITLE
ILL_ILLTRP  Shipper _ZN4mmkv11armv8_crc32EjPKhm (crc32_armv8.cpp:)

### ISSUE THREAD

**Issue by dirfox** [Tencent/MMKV#473]
### The language of MMKV

> Objective-C

### The version of MMKV

> e.g. v1.1.1

### The platform of MMKV

> e.g. iOS

### The installation of MMKV

> e.g. Cocoapods

### What's the issue?
线上环境，小部分用户在使用时会出现如下crash，本地未复现。(crash由bugly进行统计收集）

ILL_ILLTRP
TestDemo _ZN4mmkv11armv8_crc32EjPKhm (crc32_armv8.cpp:)

0 TestDemo	mmkv::armv8_crc32(unsigned int, unsigned char const*, unsigned long) (crc32_armv8.cpp:37)
1 TestDemo	mmkv::MMKV::recaculateCRCDigestWithIV(void const*) (MMKV.cpp:990)
2 TestDemo	mmkv::MMKV::doFullWriteBack(mmkv::MMBuffer&&) (MMKV.cpp:0)
3 TestDemo	mmkv::MMKV::ensureMemorySize(unsigned long) (MMKV.cpp:0)
4 TestDemo	mmkv::MMKV::appendDataWithKey(mmkv::MMBuffer const&, NSString*) (MMKV.cpp:781)
5 TestDemo	mmkv::MMKV::setDataForKey(mmkv::MMBuffer&&, NSString*) (MMKV.cpp:0)
6 TestDemo	mmkv::MMKV::set(NSObject<NSCoding>*, NSString*) (MMKV_OSX.cpp:0)
7 TestDemo	-[MMKV setObject:forKey:] (libMMKV.mm:0)
8 TestDemo	-[MMKV setData:forKey:] (libMMKV.mm:0)
9 TestDemo	setValue (MBMMKVDriver.swift:17)

**Comment by lingol** [comment]
Crashing inside crc32, I don't have any clue. Are there any logs?

**Comment by lingol** [comment]
By the way, you should upload the **full** crash stacks.

**Comment by dirfox** [comment]
> By the way, you should upload the **full** crash stacks. Information like the device type, memory usage, OS version, are very helpful.

Device : Iphone X
System Version:12.4

#0 Thread
SIGILL
ILL_ILLTRP

0 Shipper | mmkv::armv8_crc32(unsigned int, unsigned char const*, unsigned long) (crc32_armv8.cpp:37)
-- | --
1 Shipper | mmkv::MMKV::recaculateCRCDigestWithIV(void const*) (MMKV.cpp:990)
2 Shipper | mmkv::MMKV::doFullWriteBack(mmkv::MMBuffer&&) (MMKV.cpp:0)
3 Shipper | mmkv::MMKV::ensureMemorySize(unsigned long) (MMKV.cpp:0)
4 Shipper | mmkv::MMKV::appendDataWithKey(mmkv::MMBuffer const&, NSString*) (MMKV.cpp:781)
5 Shipper | mmkv::MMKV::setDataForKey(mmkv::MMBuffer&&, NSString*) (MMKV.cpp:0)
6 Shipper | mmkv::MMKV::set(NSObject<NSCoding>*, NSString*) (MMKV_OSX.cpp:0)
7 Shipper | -[MMKV setObject:forKey:] (libMMKV.mm:0)
8 Shipper | -[MMKV setData:forKey:] (libMMKV.mm:0)
9 Shipper | setValue (MBMMKVDriver.swift:17)
10 Shipper | set (MBStorageDataClient.swift:82)
11 Shipper | set (<compiler-generated>:0)
12 Shipper | set (<compiler-generated>:0)
13 Shipper | -[MBStorageService set:forKey:] (MBStorageService.m:75)
14 Shipper | +[YMMUserModuleTool saveUserCenterConfiguratioToLocalCache:] (YMMUserModuleTool.m:846)
15 Shipper | -[YMMUserCenter updateUserConfigModel:] (YMMUserCenter.m:407)
16 Shipper | __38-[YMMUserCenter requestUserConfigData]_block_invoke (YMMUserCenter.m:726)
17 Shipper | __69-[NSObject(NetworkExtention) ymm_executeNetworkTask:success:failure:]_block_invoke (NSObject+NetworkExtention.m:50)
18 Shipper | __59-[YMMCommonNetworkTask ymm_sendRequestWithSuccess:failure:]_block_invoke (YMMCommonNetworkTask.m:0)
19 Shipper | -[YMMNetworkTask p_handleRequestSuccessData:success:failure:] (YMMNetworkTask.m:140)
20 Shipper | __53-[YMMNetworkTask ymm_sendRequestWithSuccess:failure:]_block_invoke (YMMNetworkTask.m:345)
21 Shipper | ___116-[AFHTTPSessionManager  dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:]_block_invoke_2 + 116
22 Shipper | ___72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.125 + 148
23 libdispatch.dylib | __dispatch_call_block_and_release + 24
24 libdispatch.dylib | __dispatch_client_callout + 16
25 libdispatch.dylib | __dispatch_main_queue_callback_4CF$VARIANT$mp + 628
26 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
27 CoreFoundation | ___CFRunLoopRun + 1964
28 CoreFoundation | CFRunLoopRunSpecific + 436
29 GraphicsServices | GSEventRunModal + 100
30 UIKitCore | UIApplicationMain + 212
31 Shipper | MBApplicationMain (MBAppDelegate.m:15)
32 Shipper | main (main.m:17)
33 libdyld.dylib | _start + 4

**Comment by dirfox** [comment]
可用内存大小 | 54.63 MB ( 1.93% ) | 可用存储空间 | 3.71 GB ( 6.23% )

**Comment by lingol** [comment]
iPhone X should be OK with `armv8_crc32()`. 
According to some Google, to some crash of `ILL_ILLTRP`, you can tell the user to reboot the device and try again.

**Comment by dirfox** [comment]
> iPhone X should be OK with `armv8_crc32()`.
> According to some Googleing, as to some crash of `ILL_ILLTRP`, you can tell the user to reboot the device and try again.

我通知用户并建议其重启设备，但依旧会发生Crash。

**Comment by lingol** [comment]
Any logs then?

**Comment by dirfox** [comment]
> Any logs then?

上面贴出的Crash栈

**Comment by lingol** [comment]
I mean LOGS, not crash stacks.

**Comment by lingol** [comment]
Specifically, I need [this line of log](https://github.com/Tencent/MMKV/blob/master/Core/MMKV_OSX.cpp#L96). Somehow I don't believe that the device is actually iPhone X.

**Comment by lingol** [comment]
Now that you can reach the user, you can comment out [this line of code](https://github.com/Tencent/MMKV/blob/master/Core/MMKV_OSX.cpp#L93), send him/her a debug version of your App, and see if it crash again.

**Comment by lingol** [comment]
Hi there, any updates?

**Comment by lingol** [comment]
Any updates yet?
By the way, v1.2.0 is out, you might consider upgrade to the latest version.

**Comment by lingol** [comment]
Close due to inactive.

**Comment by hllGitHub** [comment]
我们目前线上用户大量出现这个Crash。在1.2.0版本先出现，之后我们升级到了1.2.2版本，但是线上问题依旧存在，猜测是否是持久性的影响。降级到1.2.0版本以下也是一样。请问有什么可以解决的办法吗？

**Comment by lingol** [comment]
> 我们目前线上用户大量出现这个Crash。在1.2.0版本先出现，之后我们升级到了1.2.2版本，但是线上问题依旧存在，猜测是否是持久性的影响。降级到1.2.0版本以下也是一样。请问有什么可以解决的办法吗？

check out#525
