### ISSUE TITLE
Android配置写入后杀死应用，配置出现异常情况

### ISSUE THREAD

**Issue by mutour** [Tencent/MMKV#475]
原本以为接入mmkv后应用的ANR会降低，但是从GP后台看到的情况来看，ANR没有任何变化。蛋疼。
现在又发现一个更加啃爹的问题。
应用启动后，会写入很多配置文件和配置，观察写入的文件里面也有了该字段。但是杀死应用后再次启动，配置文件里的字段没了。有时一次就出现，有时需要多次，多次即进入应用杀死进入杀死。
改怎么解决？有人遇到这个问题吗？

**Comment by lingol** [comment]
1. When you said that ANR was not dropped, did you mean the ANR cause by SP still there? Or did you mean there's a lot of ANR of MMKV? You should provide more info.

2. There are two possible answers. 
 * Either the file is corrupted, in which case you can find error logs of MMKV. 
 * Or you have mistakenly overridden/deleted the key-value somewhere else in your code. You should double-check your usage.

**Comment by mutour** [comment]
1. 现在应用完全使用MMKV写配置文件，从GP后台看之前很多ANR都是和SP有关，接入MMKV后，暂时没发现和SP有关的ANR，应该也不会有，因为已经不用SP了，但是奇怪的是ANR率没降低，现在的好多ANR都出现再Service上，但是Service的onStartCommand也没没做耗时操作，有些压根没任何调用代码也出现了 ANR。

2. 检查过代码，代码里没有删除键值的代码，覆盖是有可能，但是我遇到的问题是刻意杀死应用后，写的配置文件里看不到该键值也取不到 内容。所以应该不是覆盖导致，覆盖至少键值是存在的。


3. 有一个疑问，为什么MMKV不支持all操作，因为产品里会接入很多第三方SDK，好几个SDK都有用到SP的all操作，导致出现很多奇怪问题，后来没办法采用了一个很笨的办法，就是写一个配置会同时写入2个文件，一个文件是写key的值，一个文件是写key的值的类型，重写了all接口，通过读两个文件来完成all的操作。
为什么不支持all操作呢？或者通过一个get接口获取值，不管他是什么类型，类似java的Object，或者用一个接口判断key对应值的类型？因为不知道key的类型就没办法获取key的值，也就没办法完成all操作。

**Comment by mutour** [comment]
> 1. 当您说没有删除ANR时，您是说SP引起的ANR仍然存在吗？还是您说MMKV的ANR太多？您应该提供更多信息。
> 2. 有两个可能的答案。
> 
> * 该文件已损坏，在这种情况下，您可以找到MMKV的错误日志。
> * 或者您错误地覆盖/删除了代码中其他地方的键值。您应该仔细检查您的用法。

现在应用完全使用MMKV写配置文件，从GP后台看之前有很多ANR都是和SP有关，接收MMKV后，暂时没发现和SP有关的ANR，应该也不会有，因为已经不用SP了，但是奇怪的是ANR率没降低，现在的好多ANR都出现再服务上，但是Service的onStartCommand也没没做耗时操作，有些压根没任何调用代码也出现了ANR。

检查过代码，代码里没有删除键值的代码，覆盖是有可能，但是我遇到的问题是刻意杀死应用后，写的配置文件里看不到该键值也取不到内容。所以应该不是覆盖导致，覆盖至少键值是存在的。

有一个疑问，为什么MMKV不支持all操作，因为产品里会联系很多第三方SDK，好几个SDK都有用到SP的all操作，导致出现很多奇怪的问题，后来没办法采用了一个很笨的办法，就是写一个配置会同时写入2个文件，一个文件是写密钥的值，一个文件是写密钥的值的类型，转换了所有接口，通过读两个文件来完成所有的操作。
为什么不支持all操作呢？或者通过一个get接口获取值，不管他是什么类型，类似java的Object，或者用一个接口判断key对应值的类型？因为不知道key的类型就没办法获取key的值，也就没办法完成all操作。

**Comment by lingol** [comment]
1. That's not MMKV's problem. Nothing we can do for you about that.
2. If you are so sure about not override/delete the key-value, then you should be able to find MMKV's error log. Are there any error logs from MMKV?
3. https://github.com/Tencent/MMKV/issues/168#issuecomment-455405033

**Comment by mutour** [comment]
> 1. That's not MMKV's problem. Nothing we can do for you about that.
> 2. If you are so sure about not override/delete the key-value, then you should be able to find MMKV's error log. Are there any error logs from MMKV?
> 3. [#168 (comment)](https://github.com/Tencent/MMKV/issues/168#issuecomment-455405033)


出错信息如下：能看出是什么原因吗？
2020-06-23 22:03:49.004 8253-8253/xxx.xxxxx E/MMKV: <MMKV.cpp:982::checkFileCRCValid> check crc [sp_common] fail, crc32:4225403136, m_crcDigest:3034291718

**Comment by lingol** [comment]
It's corrupted.

**Comment by mutour** [comment]
> It's corrupted.

该怎么解决呢？从代码上看貌似是验证sp_common和sp_common.crc两个文件的crc不同判定为失效，可是配置文件本身不一定损坏，而且之前写过的内容应该是没问题的，如果单纯通过2个文件的这种方式判断，岂不是整个配置文件都丢失了（实际原始配置文件还在而且可能有效，只是杀死前写入的内容失效或者没写进去，或者sp_common写了，sp_common.crc文件没来的及更新），用户杀死应用是很常见的行为，一旦这样配置文件损坏，整个业务逻辑可能都出了问题了，之前用sp貌似没遇到过这个问题。

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/android_advance_cn#%E6%95%B0%E6%8D%AE%E6%81%A2%E5%A4%8D

**Comment by mutour** [comment]
> https://github.com/Tencent/MMKV/wiki/android_advance_cn#%E6%95%B0%E6%8D%AE%E6%81%A2%E5%A4%8D


实际上我已经按上面的方式加了OnErrorRecover，但是恢复的数据貌似是0个

2020-06-23 22:44:49.584 14426-14426/xxx.xxxx E/MMKV: <MMKV.cpp:985::checkFileCRCValid> check crc [sp_common] fail, crc32:2843552671, m_crcDigest:1562278910
2020-06-23 22:44:49.584 14426-14426/xxx.xxxx I/MMKV: <MMKV.cpp:263::loadFromFile> loading [sp_common] with 1 actual size, file size 4096, InterProcess 0, meta info version:3
2020-06-23 22:44:49.584 14426-14426/xxx.xxxx I/MMKV: <MMKV.cpp:268::loadFromFile> loading [sp_common] with crc 3523407757 sequence 3 version 3
2020-06-23 22:44:49.584 14426-14426/xxx.xxxx I/MMKV: <MMKV.cpp:296::loadFromFile> loaded [sp_common] with 0 values

**Comment by lingol** [comment]
Which version did you use? I don't think you are using the latest version, according to your logs.

**Comment by mutour** [comment]
> Which version did you use? I don't think you are using the latest version, according to your logs.

使用的是com.tencent:mmkv-static:1.1.2
现在是使用的源码再调试观察原因，可能MMKV.cpp的log行数会对不上，因为添加了部分log

**Comment by lingol** [comment]
NO, I mean there's some log missing. Some keyword like `lastActualSize` should be there. 
Why not just use maven?

**Comment by lingol** [comment]
> > It's corrupted.
> 
> 该怎么解决呢？从代码上看貌似是验证sp_common和sp_common.crc两个文件的crc不同判定为失效，可是配置文件本身不一定损坏，而且之前写过的内容应该是没问题的，如果单纯通过2个文件的这种方式判断，岂不是整个配置文件都丢失了（实际原始配置文件还在而且可能有效，只是杀死前写入的内容失效或者没写进去，或者sp_common写了，sp_common.crc文件没来的及更新），用户杀死应用是很常见的行为，一旦这样配置文件损坏，整个业务逻辑可能都出了问题了，之前用sp貌似没遇到过这个问题。

I'll explain a little more. Normally speaking, the operating system will keep the mmap memory synced to files no matter the App is killed or inactive. File corruption only happens on device reboot, such as running out of battery.
As for your case, there's some guess.
* Something is wrong with your development device. the operating system doesn't keep its promise to sync mmap memory to file after the App is kill.
* You have misused that [sp_common] instance. A classical error is accessing it from multi-process with single-process mode.
* You have mistakenly modified MMKV's source code. This is easy to check out by switching to maven and see if the error still there.

**Comment by mutour** [comment]
> I'll explain a little more. Normally speaking, the operating system will keep the mmap memory synced to files no matter the App is killed or inactive. File corruption only happens on device reboot, such as running out of battery.
> As for your case, there's some guess.
> 
> * Something is wrong with your development device. The operating system doesn't keep its promise to sync mmap memory to file after the App is killed.
> * You have misused that [sp_common] instance. A classical error is accessing it from multi-process with single-process mode.
> * You have mistakenly modified MMKV's source code. This is easy to check out by switching to maven and see if the error still there.




* 设备应该是没有问题的，因为更换设备，也会有这个情况
* 暂时应用中没有用到多进程写配置的方式
* android项目，使用的是Android Studio的gradle进行编译运行，因为是使用com.tencent：mmkv-static：1.1.2出现问题，所以才使用源代码进行调试跟踪问题。而且源代码除了增加了几个log，其他并未进行修改。

**Comment by mutour** [comment]
> > > It's corrupted.
> > 
> > 
> > 该怎么解决呢？从代码上看貌似是验证sp_common和sp_common.crc两个文件的crc不同判定为失效，可是配置文件本身不一定损坏，而且之前写过的内容应该是没问题的，如果单纯通过2个文件的这种方式判断，岂不是整个配置文件都丢失了（实际原始配置文件还在而且可能有效，只是杀死前写入的内容失效或者没写进去，或者sp_common写了，sp_common.crc文件没来的及更新），用户杀死应用是很常见的行为，一旦这样配置文件损坏，整个业务逻辑可能都出了问题了，之前用sp貌似没遇到过这个问题。
> 
> I'll explain a little more. Normally speaking, the operating system will keep the mmap memory synced to files no matter the App is killed or inactive. File corruption only happens on device reboot, such as running out of battery.
> As for your case, there's some guess.
> 
> * Something is wrong with your development device. The operating system doesn't keep its promise to sync mmap memory to file after the App is killed.
> * You have misused that [sp_common] instance. A classical error is accessing it from multi-process with single-process mode.
> * You have mistakenly modified MMKV's source code. This is easy to check out by switching to maven and see if the error still there.

我检查下代码，看看是不是有多进程访问同一个sp_common的情况。
谢谢你的耐心 解答···

**Comment by lingol** [comment]
Any updates yet? You might check that out by using multi-process mode to all the code that opens [sp_common].

**Comment by mutour** [comment]
> Any updates yet? You might check that out by using multi-process mode to all the code that opens [sp_common].

好的，应该是这个引起的。
不过我有一个疑问，android程序如果有多进程，如果不做特殊处理Application的onCreate都会被调用，如果这样的话，这种情况就很难避免，因为增加一个进程服务或其他都不能第一时间想到某个aps会否需要考虑多进程情况。
所以：
1. 如果主进程使用了sp_common，子进程也用到了，是否2个进程都必须使用multiprocess mode，还是主进程可以single mode子进程使用multiprocess mode？
2. 使用multi mode对sp使用速度影响大吗？
3. 如果sp_comon文件只有单进程使用，采用single和multi mode有什么区别没有？如果没有影响是否可以直接在应用中直接全部使用multi mode？多人协同开发多少会出现一些配置文件被误用。

**Comment by lingol** [comment]
1. Once MULT_PROCESS, always MULTI_PROCESS.
2. A little cost on locking `flock()`. But there will be no significant difference unless you are accessing it from multi-process **at the same time**.
3. Same as 2. Use your best judgment.

**Comment by mutour** [comment]
> 1. Once MULT_PROCESS, always MULTI_PROCESS.
> 2. A little cost on locking `flock()`. But there will be no significant difference unless you are accessing it from multi-process **at the same time**.
> 3. Same as 2. Use your best judgment.

明白了。谢谢指教
