### ISSUE TITLE
Does MMKV support multiple rootDir ?

### ISSUE THREAD

**Issue by jeffy26** [Tencent/MMKV#476]
### The language of MMKV

> C++

### The version of MMKV

> v1.1.2

### The platform of MMKV

> Linux (POSIX)

### The installation of MMKV

>CMake

### What's the issue?

> I am using MMKV in Linux,I need to save the config files in different directory
 ,but，it seems that MMKV only  support single rootDir which is initialized by  **MMKV::initializeMMKV(rootDir)**，
is there any means I can  change rootDir of MMKV ?
thanks.

**Comment by lingol** [comment]
There's only one root directory of MMKV for a process. 
You can specify a relative root for each MMKV instance. https://github.com/Tencent/MMKV/blob/master/Core/MMKV.h#L158

**Comment by jeffy26** [comment]
> There's only one root directory of MMKV for a process.
> You can specify a relative folder for each MMKV instance. https://github.com/Tencent/MMKV/blob/master/Core/MMKV.h#L158

thanks.
