### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by Solido** [Tencent/MMKV#48]
Since Android and iOS are already present, are you considering plugin for cross platforms like Google Flutter ?

**Comment by lingol** [comment]
Not in our current plan. But that's interesting though.
I would love to see a third party integration.

**Comment by Solido** [comment]
Would I've been surprised if already in your plan but here's a signal of interest ;)

**Comment by lingol** [comment]
Porting to macOS and supporting big-file are our top priorities. 
Volunteers are welcome on Flutter/RN integration.

**Comment by yuyongmao** [comment]
https://pub.dartlang.org/packages/mmkv_flutter 
I just make a flutter plugin base on MMKV framework.
You can try it.
Please feel free to contact me if you have any questions.

**Comment by yuyongmao** [comment]
> Do you want to PR it to Awesome Flutter https://github.com/Solido/awesome-flutter ?
> So your name would be added to the list of contributors or I'll do it.
> You squashed it in 150 lines 🎉

Of course, you can do it. It's my pleasure!
And I just have transferred this repository to the OpenFlutter organization.(https://github.com/OpenFlutter/mmkv_flutter)

**Comment by lingol** [comment]
The official flutter has just been released with [v1.2.6](https://github.com/Tencent/MMKV/releases/tag/v1.2.6). Checkout the [wiki](https://github.com/Tencent/MMKV/wiki/flutter_setup) for usage.
