### ISSUE TITLE
support MMKV_AES_CRYPT preprocess directive 

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#481]
Please add a new preprocess directive `MMKV_AES_CRYPT` so we can build the mmkv.so file with smaller file and memory footprint size.

The `MMKV_AES_CRYPT`  is **true** by default.

We always store key-values in plain text on file so we'd like to set `MMKV_AES_CRYPT` as **false** for building .so files with smaller file size without adding unused code.

When the `MMKV_AES_CRYPT`  is false:
1. don't include any aes/<aes related .h/.cpp> files
2. all mmkv encrypt/decrypt related functions should do nothing or give an error on calling

**Comment by lingol** [comment]
Which platform do you use?

**Comment by samlu** [comment]
Android

**Comment by lingol** [comment]
Added MMKV_DISABLE_CRYPT with commit #74be762

**Comment by lingol** [comment]
Released in [v1.2.1](https://github.com/Tencent/MMKV/releases/tag/v1.2.1).

**Comment by samlu** [comment]
Thank you. I can build the mmkv aar file with `MMKV_DISABLE_CRYPT` defined without any issues. 

Please add some description under the **Build from Source** section about how to define `MMKV_DISABLE_CRYPT` for building the mmkv library without any encryption functions/code.

**Comment by lingol** [comment]
Thank you, that's a good suggestion about wiki. Will do.
