### ISSUE TITLE
There's only one root directory of MMKV for a process.

### ISSUE THREAD

**Issue by jeffy26** [Tencent/MMKV#485]
There's only one root directory of MMKV for a process. 
You can specify a relative folder for each MMKV instance. https://github.com/Tencent/MMKV/blob/master/Core/MMKV.h#L158

_Originally posted by @lingol in https://github.com/Tencent/MMKV/issues/476#issuecomment-650696391_

**Comment by lingol** [comment]
What are you doing?

**Comment by jeffy26** [comment]
I just test the use of  "a relative folder for each MMKV instance",but it seems that the **relative folder** is not relative for
the  root directory,but for the directory which the process is started

here is my test code:
![image](https://user-images.githubusercontent.com/19582132/86338003-66863d80-bc84-11ea-8881-838c53f7f27e.png)

the output log:
![image](https://user-images.githubusercontent.com/19582132/86338100-80c01b80-bc84-11ea-93fe-6e36f6cd30ff.png)

the root directory does not have any  relative folder:
but relative folder and mmkv file was created in my build dir:

![mmkv1](https://user-images.githubusercontent.com/19582132/86339026-ab5ea400-bc85-11ea-90c9-33e88b9780ea.png)


https://github.com/Tencent/MMKV/blob/b9820029c1911721e35cf912744089752713e48f/Core/MMKV.cpp#L903

code above seems thast if  a relative path is set, the g_rootDir  will not be used

anything is wrong?I just want every relative directory is created in my root dir, which seems intuitive I think.

**Comment by lingol** [comment]
You should pass an absolute path to that parameter `relativePath`.

**Comment by jeffy26** [comment]
if the **relativePath** means  **an absolute path** ,i think it is misleading somehow

**Comment by lingol** [comment]
It's a bad choice. Will rename it.

**Comment by jeffy26** [comment]
appreciate that.

**Comment by lingol** [comment]
8f20ae1846bb575ab901c0370fc97da157364fe5

**Comment by lingol** [comment]
Released with v1.2.1, check it out.
