### ISSUE TITLE
删除数据后，文件在磁盘上的空间未释放

### ISSUE THREAD

**Issue by 15321657258** [Tencent/MMKV#488]
### The language of MMKV

>  Java

### The version of MMKV

> v1.2.1

### The platform of MMKV

> Android

### The installation of MMKV

> gradle

### What's the issue?

在新增和删除数据后，磁盘占用空间未新增或减小，比如第一次放入数据32mb，在新增数据和删除数据后，空间仍然为32mb

**Comment by lingol** [comment]
trim().
