### ISSUE TITLE
actualSize不准确

### ISSUE THREAD

**Issue by dachangjin** [Tencent/MMKV#489]
首次设置某个key-value后，可获得count为1，actualSize为26。当我删除后这个key-value后，count为0，然后actualSize却变大了为35。这个actualSize到底为何物？

**Comment by lingol** [comment]
MMKV is append-only. Think about that.

**Comment by dachangjin** [comment]
+1

**Comment by lingol** [comment]
> +1

Don't spam. https://github.com/Tencent/MMKV/wiki/design

**Comment by dachangjin** [comment]
+1表示明白了😂

**Comment by lingol** [comment]
Okay.
