### ISSUE TITLE
协程使用出

### ISSUE THREAD

**Issue by Bear950925** [Tencent/MMKV#491]
### The language of MMKV

> e.g.  or Kotlin

### The version of MMKV

> e.g. v1.2.1

### The platform of MMKV

> e.g. Android

### The installation of MMKV

> e.g. Maven

### What's the issue?

1.我用协程保存一串字符串之后，马上重新获取打印字符串显示数据还在
2.跳转到另一个界面之后重新获取该字符串，期间马上重新获取该字符串，结果输出为空

##############
A界面：
private fun getAds() {
        jobs.add(CoroutineScope(Dispatchers.IO).launch {
            val ads = model!!.apiService.getAds().data
            MMKV.defaultMMKV().putString(CommonConstants.ADS, Gson().toJson(ads))
            val adss = MMKV.defaultMMKV().getString(CommonConstants.ADS, "")
            YLog.e("ads", "ads加载完成" + adss);
        })
    }
打印的日志为：
 ads加载完成{"five":[{"cid":1,"clickNum":10,"createTime":"2020-07-08 10:34:53","id":7,"imgUrl":"htt....(省略未写)
############################################

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

**Comment by lingol** [comment]
If you are using MMKV in multi-process, you should pass `MMKV.MULTI_PROCESS`.
```
MMKV.defaultMMKV(MMKV.MULTI_PROCESS)
```

**Comment by Bear950925** [comment]
> If you are using MMKV in multi-process, you should pass `MMKV.MULTI_PROCESS`.
> 
> ```
> MMKV.defaultMMKV(MMKV.MULTI_PROCESS)
> ```
> 
> And remember, once it's multi-process, anywhere should be multi-process for the default MMKV instance.

你说的是多进程，这种情况是和线程以及协程一样么？

**Comment by lingol** [comment]
I'm not so sure about that _coroutine_ description. Frankly, when some **Android** guy comes up and complains about MMKV not syncing data, it is **almost always** due to the multi-process mode not being set correctly.

**Comment by lingol** [comment]
I have updated the [FAQ](https://github.com/Tencent/MMKV/wiki/FAQ) to make things clear.

FAQ in Chinese https://github.com/Tencent/MMKV/wiki/FAQ_cn

**Comment by calvin2021y** [comment]
test on multi thread and sing thread,  coroutine & android loss data.
