### ISSUE TITLE
多进程下同步修改数据

### ISSUE THREAD

**Issue by RogerWP** [Tencent/MMKV#492]
多进程下，某一进程修改数据，其他进程能够实时同步数据状态吗

**Comment by lingol** [comment]
Yes, definitely.

**Comment by RogerWP** [comment]
我看源码是有监听多进程数据状态的回调方法，想问下是如何做到其他进程能够实时同步数据状态吗

**Comment by lingol** [comment]
If you mean realtime notification, there's none. You have to check it yourself.

**Comment by lingol** [comment]
The data changes itself, however, is in realtime to all processes. You just have to check for notifications.
