### ISSUE TITLE
version 1.1.1，crash 

### ISSUE THREAD

**Issue by happytianqiu** [Tencent/MMKV#495]
#00 pc 000000000001975c /data/app/com.qts.customer-f3dPgJMioUB0S9_VIQwc3Q==/lib/arm64/libmmkv.so [arm64-v8a]
--
2 #01 pc 000000000001b148 /data/app/com.qts.customer-f3dPgJMioUB0S9_VIQwc3Q==/lib/arm64/libmmkv.so [arm64-v8a]
3 #02 pc 0000000000010348 /data/app/com.qts.customer-f3dPgJMioUB0S9_VIQwc3Q==/lib/arm64/libmmkv.so [arm64-v8a]
4 #03 pc 00000000002e662c /data/app/com.qts.customer-f3dPgJMioUB0S9_VIQwc3Q==/oat/arm64/base.odex [arm64-v8a]
5 java:
6 com.tencent.mmkv.MMKV.mmkvWithID(SourceFile:164)

**Comment by lingol** [comment]
That's just too old. I don't have time for that. 
Please upgrade to v1.2.1. Come back again if you still have such crashes.
