### ISSUE TITLE
Crash on version 1.2.2 when app received memory warning notification

### ISSUE THREAD

**Issue by ElephantMans** [Tencent/MMKV#501]
### The language of MMKV

> Objective-C

### The version of MMKV

> v1.2.2

### The platform of MMKV

> iOS

### The installation of MMKV

> Cocoapods

### What's the issue?

![20200731151204](https://user-images.githubusercontent.com/6240848/89009994-5a070a80-d340-11ea-92b2-80737491929f.jpg)

**Comment by lingol** [comment]
Fixed in the master branch. For those who has checkout v1.2.2 via CocoaPods, clean your local cache & do a fresh pod install. Things should work now.
>rm -rf ~/Library/Caches/CocoaPods; rm -rf Pods; rm -rf ~/Library/Developer/Xcode/DerivedData/*; pod deintegrate; pod setup; pod install;

https://gist.github.com/mbinna/4202236#gistcomment-1814665
