### ISSUE TITLE
请问Win32版本的MMKV不支持X64吗？

### ISSUE THREAD

**Issue by YuQianhao** [Tencent/MMKV#502]
请问Win32版本的MMKV不支持X64吗？

**Comment by lingol** [comment]
What do you mean?

**Comment by YuQianhao** [comment]
The Win32 version of mmkv only supports x86? Is x64 not supported?Because Windows is divided into 32-bit (x86) and 64 bit (x64).

**Comment by YuQianhao** [comment]
On windows, 32-bit applications can only apply for 2G memory, but the data content stored by mmkv has exceeded 2G

**Comment by lingol** [comment]
Noted.

By the way, I don't think MMKV handles data larger than 100M very well. Just saying.

**Comment by YuQianhao** [comment]
ok, thank you very much.
