### ISSUE TITLE
Feature Request: interpreter for mmkv files

### ISSUE THREAD

**Issue by jianzhongli** [Tencent/MMKV#506]
MMKV persists key-value pairs in protobuf format, which is not human readable. Sometimes for debug purpose we would like to pull the mmkv files and see what's in it. A convenient tool for interpreting contents in the mmkv files will be really helpful. 

Is this in the road map? Or will you accept a PR for this feature?

**Comment by lingol** [comment]
I don't think it will be any chances to make it perfectly work, for mmkv erases type info on encoding. You're very welcome to try one though.

**Comment by jianzhongli** [comment]
Never mind, a hex dump command is enough in most cases.
