### ISSUE TITLE
iOS Compiler Flags 

### ISSUE THREAD

**Issue by zqx654033799** [Tencent/MMKV#508]
language: Objective-C
version: 1.2.2
platform: iOS

我注意到MMKVDemo中，MMKVCore lib下 AESCrypt.cpp 文件的Compiler Flags，没有"-fno-objc-arc"标记，
而用Cocoapods引入的时候，MMKVCore lib下的 同名文件，却含有"-x objective-c++ -fno-objc-arc"标记
不明白这两者之间 的区别，还烦请大神解答一下

**Comment by lingol** [comment]
AESCrypt.cpp contains no OC code. So this flag makes little difference. You can just ignore it.
