### ISSUE TITLE
作者大大，我想问，这个库可以当做数据库来用吗？

### ISSUE THREAD

**Issue by wdq123550** [Tencent/MMKV#511]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

objc and swift

### The version of MMKV

> e.g. v1.0.10

null

### The platform of MMKV

> e.g. iOS or Android

ios 

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

null

### What's the issue?
作者大大，我想问，这个库可以当做数据库来用吗？
> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your detail logs. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.

**Comment by wdq123550** [comment]
因为wcdb貌似很久没更新了，我可以拿这个库来替代wcdb吗？

**Comment by lingol** [comment]
No.
- WCDB is still maintained, it just being stable so updates might not be that often. MMKV will be stable in the future as well.
- MMKV is not a database. While it does function like a db in some use case, it doesn't scale well when data are large(100M+).

**Comment by wdq123550** [comment]
你好，请问这里的100M+是指mmkv文件的总大小还是一次性写入的大小？另外我看WCDB很多iss从去年开始就没人解决了.

**Comment by lingol** [comment]
> 你好，请问这里的100M+是指mmkv文件的总大小还是一次性写入的大小？另外我看WCDB很多iss从去年开始就没人解决了.

Total size obviously.
