### ISSUE TITLE
IllegalArgumentException 升级 1.2.2 版本后，历史版本兼容性问题

### ISSUE THREAD

**Issue by ValuesFeng** [Tencent/MMKV#512]
java.lang.IllegalArgumentException

Opening a single-process MMKV instance [du_device] with MULTI_PROCESS_MODE!

 com.tencent.mmkv.MMKV.com.tencent.mmkv.MMKV checkProcessMode(long,java.lang.String,int)(MMKV.java:5)
--
 com.tencent.mmkv.MMKV.com.tencent.mmkv.MMKV mmkvWithID(java.lang.String,int)(MMKV.java:7)
 com.shizhuang.duapp.common.utils.MMKVUtils.com.tencent.mmkv.MMKV getMMKV(java.lang.String)(MMKVUtils.java:3)
 com.shizhuang.duapp.common.utils.DeviceUtil.void getOaidFromMMKV()(DeviceUtil.java:1)
 com.shizhuang.duapp.common.utils.DeviceUtil.java.lang.String getOaid()(DeviceUtil.java:2)
 com.shizhuang.duapp.common.base.BaseApplication.void initOAIDLib()(BaseApplication.java:16)
 com.shizhuang.duapp.common.base.BaseApplication.void initAyncSetting(java.lang.String)(BaseApplication.java:87)
 com.shizhuang.duapp.common.base.BaseApplication.void lambda$initOnMainProcess$2(java.lang.String)(BaseApplication.java:2)
 com.shizhuang.duapp.common.base.-$$Lambda$BaseApplication$JdOAcSVUF8tUV6EIriv21oLvgYE.run(Unknown Source:4)
 java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 java.lang.Thread.run(Thread.java:929)

**Comment by lingol** [comment]
Like it said, you are accessing a multi-process MMKV instance with singole-process-mode. It's wrong, there will be data corruption and/or crash. 
You should access it with multi-process-mode.
