### ISSUE TITLE
clearAll carch

### ISSUE THREAD

**Issue by yangbo930204** [Tencent/MMKV#514]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Swift and OC

### The version of MMKV

> e.g. v1.0.10

v1.2.2、v1.2.1

### The platform of MMKV

> e.g. iOS or Android

iOS

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?

问题：Swift中调用clearAll()崩溃

Incident Identifier: BD4BC54D-EDB5-41DB-921C-AE8F50D7379C
Hardware Model:      iPhone12,3
Process:             DianBo [221]
Path:                /private/var/containers/Bundle/Application/A23CE535-05FE-4A18-847B-68E780B03043/DianBo.app/DianBo
Identifier:          com.dianboLive.www
Version:             1.7 (2.2.0)
AppStoreTools:       11E707
AppVariant:          1:iPhone12,3:13
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.dianboLive.www [352]

Date/Time:           2020-08-18 09:38:13.5354 +0800
Launch Time:         2020-08-18 01:23:45.1131 +0800
OS Version:          iPhone OS 13.6 (17G68)
Release Type:        User
Baseband Version:    1.06.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x18a60d344 __exceptionPreprocess + 228 (NSException.m:199)
1   libobjc.A.dylib               	0x18a322cc0 objc_exception_throw + 60 (objc-exception.mm:565)
2   CoreFoundation                	0x18a4fd51c +[NSException raise:format:] + 112 (NSException.m:155)
3   DianBo                        	0x105370afc 0x104350000 + 16911100
4   DianBo                        	0x1050894cc 0x104350000 + 13866188
5   DianBo                        	0x105089064 0x104350000 + 13865060
6   libsystem_platform.dylib      	0x18a311414 _sigtramp + 60 (sigtramp.c:100)
7   libsystem_pthread.dylib       	0x18a314948 pthread_kill + 228 (pthread.c:1458)
8   libsystem_c.dylib             	0x18a2a3ba4 abort + 104 (abort.c:110)
9   libsystem_c.dylib             	0x18a2a2ef8 __assert_rtn + 292 (assert.c:96)
10  MMKVCore                      	0x106c5ee40 mmkv::MemoryFile::reloadFromFile() (.cold.1) + 88
11  MMKVCore                      	0x106c4f9b0 mmkv::MemoryFile::reloadFromFile() + 216 (MemoryFile.cpp:132)
12  MMKVCore                      	0x106c59f68 mmkv::MMKV::clearAll() + 140 (MMKV_IO.cpp:1048)
13  DianBo                        	0x104aad740 specialized setLoginVCWithRoot(_:) + 3436 (CommonlyUsedTool.swift:425)
14  DianBo                        	0x1049b87f8 thunk for @escaping @callee_guaranteed (@guaranteed UIAlertAction) -> () + 48 (<compiler-generated>:0)
15  UIKitCore                     	0x18dd20ccc -[UIAlertController _invokeHandlersForAction:] + 116 (UIAlertController.m:1081)
16  UIKitCore                     	0x18dd2168c __103-[UIAlertController _dismissAnimated:triggeringAction:triggeredByPopoverDimmingView:dismissCompletion:]_block_invoke.463 + 36 (UIAlertController.m:1246)
17  UIKitCore                     	0x18dfe285c -[UIPresentationController transitionDidFinish:] + 988 (UIPresentationController.m:462)
18  UIKitCore                     	0x18dfe6f00 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.516 + 212 (UIPresentationController.m:1086)
19  UIKitCore                     	0x18e0f08d0 -[_UIViewControllerTransitionContext completeTransition:] + 112 (UIViewControllerTransitioning.m:285)
20  UIKitCore                     	0x18ebfa814 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 600 (UIView.m:14135)
21  UIKitCore                     	0x18ebcdad4 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 248 (UIView.m:0)
22  UIKitCore                     	0x18ebcdffc -[UIViewAnimationState animationDidStop:finished:] + 248 (UIView.m:2222)
23  UIKitCore                     	0x18ebce154 -[UIViewAnimationState animationDidStop:finished:] + 592 (UIView.m:2241)
24  QuartzCore                    	0x19126be84 CA::Layer::run_animation_callbacks(void*) + 276 (CALayer.mm:6843)
25  libdispatch.dylib             	0x18a2af5ac _dispatch_client_callout + 20 (object.m:495)
26  libdispatch.dylib             	0x18a2bb7d4 _dispatch_main_queue_callback_4CF + 832 (inline_internal.h:2484)
27  CoreFoundation                	0x18a5888d4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CFRunLoop.c:1749)
28  CoreFoundation                	0x18a58358c __CFRunLoopRun + 1692 (CFRunLoop.c:3069)
29  CoreFoundation                	0x18a582bc8 CFRunLoopRunSpecific + 480 (CFRunLoop.c:3192)
30  GraphicsServices              	0x1949645cc GSEventRunModal + 164 (GSEvent.c:2246)
31  UIKitCore                     	0x18e735744 UIApplicationMain + 1936 (UIApplication.m:4823)
32  DianBo                        	0x10478a4d0 main + 68 (AppDelegate.swift:21)
33  libdyld.dylib                 	0x18a3ff384 start + 4

**Comment by lingol** [comment]
Logs of mmkv, please.

**Comment by yangbo930204** [comment]
线上日志级别是：MMKVLogNone。
线上用户出现的，我尝试复现，但是没有出现过。

**Comment by lingol** [comment]
Come back later when you have logs.

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/iOS_advance#log

**Comment by lingol** [comment]
Close due to inactive.

**Comment by hezheop** [comment]
+1，也出现了
