### ISSUE TITLE
ILL_ILLTRP Crash

### ISSUE THREAD

**Issue by ElephantMans** [Tencent/MMKV#517]
### The language of MMKV

>  Objective-C

### The version of MMKV

> v1.2.1

### The platform of MMKV

> iOS

### The installation of MMKV

> Cocoapods

### What's the issue?

#20 Thread

SIGILL

ILL_ILLTRP

0 GoodTransport | armv8_crc32 (crc32_armv8.cpp:45)
-- | --
1 GoodTransport | mmkv::MMKV::recaculateCRCDigestWithIV(void const*) (MMKV.cpp:354)
2 GoodTransport | mmkv::MMKV::doFullWriteBack(std::__1::pair<mmkv::MMBuffer, unsigned long>, mmkv::AESCrypt*) (MMKV_IO.cpp:0)
3 GoodTransport | mmkv::MMKV::ensureMemorySize(unsigned long) (MMKV_IO.cpp:0)
4 GoodTransport | mmkv::MMKV::doAppendDataWithKey(mmkv::MMBuffer const&, mmkv::MMBuffer const&, bool, unsigned int) (MMKV_IO.cpp:635)
5 GoodTransport | mmkv::MMKV::appendDataWithKey(mmkv::MMBuffer const&, NSString*, bool) (MMKV_IO.cpp:0)
6 GoodTransport | mmkv::MMKV::setDataForKey(mmkv::MMBuffer&&, NSString*, bool) (MMKV_IO.cpp:561)
7 GoodTransport | mmkv::MMKV::set(NSObject<NSCoding>*, NSString*) (MMKV_OSX.cpp:0)
8 GoodTransport | -[MMKV setObject:forKey:] (libMMKV.mm:0)
9 GoodTransport | -[MMKV setData:forKey:] (libMMKV.mm:0)
10 GoodTransport | setValue (MBMMKVDriver.swift:17)
11 GoodTransport | set (MBStorageDataClient.swift:82)
12 GoodTransport | set (<compiler-generated>:0)
13 GoodTransport | set (<compiler-generated>:0)
14 GoodTransport | -[MBStorageService set:forKey:] (MBStorageService.m:75)
15 GoodTransport | -[MBAdvertCache cleanExtraVersionAdvertisements] (MBAdvertCache.m:68)
16 GoodTransport | __21-[MBAdvertCache init]_block_invoke (MBAdvertCache.m:40)
17 libdispatch.dylib | __dispatch_call_block_and_release + 24
18 libdispatch.dylib | __dispatch_client_callout + 16
19 libdispatch.dylib | __dispatch_lane_serial_drain$VARIANT$mp + 608
20 libdispatch.dylib | __dispatch_lane_invoke$VARIANT$mp + 416
21 libdispatch.dylib | __dispatch_workloop_worker_thread + 588
22 libsystem_pthread.dylib | _pthread_wqthread + 272

### What's the log of MMKV when that happened?
App will be crashed when write data to MMKV in the first time. The available memory is very low as shown in the bellow picture.
![20200824154145](https://user-images.githubusercontent.com/6240848/91017458-db407d00-e620-11ea-929a-c9c06c03bab0.jpg)

**Comment by lingol** [comment]
`SIGILL ILL_ILLTRP` means the device needs to reboot.

**Comment by ElephantMans** [comment]
The only way to resolve this problem is rebooting the device?

**Comment by ElephantMans** [comment]
Can I avoid this issue by defining MMKV_EMBED_ZLIB?

**Comment by lingol** [comment]
> The only way to resolve this problem is rebooting the device?

Right.

**Comment by lingol** [comment]
> Can I avoid this issue by defining MMKV_EMBED_ZLIB?

Don't do it. It slows down MMKV.

**Comment by ElephantMans** [comment]
> > The only way to resolve this problem is rebooting the device?
> 
> Right.

So many crashes caused this issue occur in out app. If we can't resolve this issue, the only selection for us is to remove MMKV. Do you have some good suggestions?

**Comment by lingol** [comment]
Have you tried to upgrade to the lastest MMKV? https://github.com/Tencent/MMKV/releases/tag/v1.2.2

**Comment by ElephantMans** [comment]
> Have you tried to upgrade to the lastest MMKV? https://github.com/Tencent/MMKV/releases/tag/v1.2.2

which commit in v1.2.2 is helpful for this issue?

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/commit/09ed7f609e2d96d2ad91e6fc127d6387798215b3
But I don't recommend just merge this specific commit. You should upgrade the whole MMKV project.

**Comment by ElephantMans** [comment]
> [09ed7f6](https://github.com/Tencent/MMKV/commit/09ed7f609e2d96d2ad91e6fc127d6387798215b3)
> But I don't recommend just merge this specific commit. You should upgrade the whole MMKV project.

I know this commit, but I think the situation that system info is uncorrected it fix isn't useable for my issue maybe.
