### ISSUE TITLE
Crash: MiniCodedOutputData::writeRawByte(unsigned char)

### ISSUE THREAD

**Issue by liftliftlift** [Tencent/MMKV#519]
**MMKV version: 1.0.12**

UserExceptionType
Incident Identifier: 798EDC0A-330E-4623-A618-84B7D376CDB7
CrashReporter Key:   temporary
Hardware Model:      iPhone7,2
@Process:            Reading [2045]
Path:                /var/mobile/Containers/Data/Application/CCB28D82-64D5-4260-96C4-375326EA7FCE
Identifier:xxxx
Version:x.x.x(x.x.x.xx)
Code Type:           arm64
Parent Process:
Date/Time:           2020-08-24 16:30:26 +0800
OS Version:iOS 12.4.8 (16G201)
Report Version:      104
crashTypeString MACH_Exception
exception EXC_BAD_ACCESS (SIGBUS)
reason EXC_BAD_ACCESS KERN_MEMORY_ERROR fault_address:0x0000000106da5b0f
fault_address: 0x0000000106da5b0f
sig_num: 10
sig_code: 0
sub_code
SDK Start:
SDK End:

Thread 24 name:  xxx_handle_serial_queue
Thread 24: Crashed
0   Reading                         0x000000010129b404 MiniCodedOutputData::writeRawByte(unsigned char) (in Reading) (MiniCodedOutputData.mm:109)
1   Reading                         0x000000010129b4d4 MiniCodedOutputData::writeString(NSString*) (in Reading) (MiniCodedOutputData.mm:72)
2   Reading                         0x000000010129f1d4 __26-[MMKV appendData:forKey:]_block_invoke.139 (in Reading) (MMKV.mm:584)
3   Reading                         0x000000010129e5b8 -[MMKV protectFromBackgroundWritting:writeBlock:] (in Reading) (MMKV.mm:421)
4   Reading                         0x000000010129ef48 -[MMKV appendData:forKey:] (in Reading) (MMKV.mm:581)
5   Reading                         0x000000010129ed90 -[MMKV setData:forKey:] (in Reading) (MMKV.mm:544)
6   Reading                         0x000000010129ff98 -[MMKV setObject:forKey:] (in Reading) (MMKV.mm:826)
7   Reading                         0x00000001010493ac -[DiskImageFileCache setData:forKey:] (in Reading) (DiskImageFileCache.m:133)
8   Reading                         0x000000010104cdac -[ImageCache saveImageToDisk:data:forKey:] (in Reading) (ImageCache.m:285)
9   Reading                         0x000000010104ca18 -[ImageCache setImage:imageData:forKey:withType:] (in Reading) (ImageCache.m:239)
10  Reading                         0x0000000101057a0c -[WebImageManager trasformImageWithCache:cacheKey:cacheType:currentRequest:data:decodeError:downloader:image:needImage:realData:realImage:task:] (in Reading) (WebImageManager.m:822)
11  Reading                         0x0000000101058744 -[WebImageManager downloader:task:finishedWithData:savePath:] (in Reading) (WebImageManager.m:941)
12  Reading                         0x000000010106feb8 -[DownloadManager downloadTask:finishedWithData:savePath:] (in Reading) (DownloadManager.m:170)
13  Reading                         0x0000000101047ea4 __63-[DownloadChromiumTask callbackActionWithError:Obj:response:]_block_invoke (in Reading) (DownloadChromiumTask.mm:209)
14  libdispatch.dylib               0x00000001ec078a38 __dispatch_call_block_and_release (in libdispatch.dylib) + 24
15  libdispatch.dylib               0x00000001ec0797d4 __dispatch_client_callout (in libdispatch.dylib) + 16
16  libdispatch.dylib               0x00000001ec022324 __dispatch_lane_serial_drain$VARIANT$mp (in libdispatch.dylib) + 592
17  libdispatch.dylib               0x00000001ec022e40 __dispatch_lane_invoke$VARIANT$mp (in libdispatch.dylib) + 428
18  libdispatch.dylib               0x00000001ec02b4ac __dispatch_workloop_worker_thread (in libdispatch.dylib) + 596
19  libsystem_pthread.dylib         0x00000001ec25a114 __pthread_wqthread (in libsystem_pthread.dylib) + 304
20  libsystem_pthread.dylib         0x00000001ec25ccd4 _start_wqthread (in libsystem_pthread.dylib) + 4

Thread 0 name:  com.apple.main-thread
Thread 0: 
0   libsystem_kernel.dylib          0x00000001ec1cc0f4 _mach_msg_trap (in libsystem_kernel.dylib) + 8
1   libsystem_kernel.dylib          0x00000001ec1cb5a0 _mach_msg (in libsystem_kernel.dylib) + 72
2   CoreFoundation                  0x00000001ec5cc914 ___CFRunLoopServiceMachPort (in CoreFoundation) + 236
3   CoreFoundation                  0x00000001ec5c7824 ___CFRunLoopRun (in CoreFoundation) + 1360
4   CoreFoundation                  0x00000001ec5c6fb4 _CFRunLoopRunSpecific (in CoreFoundation) + 436
5   GraphicsServices                0x00000001ee7c879c _GSEventRunModal (in GraphicsServices) + 104
6   UIKitCore                       0x0000000218e28c38 _UIApplicationMain (in UIKitCore) + 212
7   Reading                         0x0000000100ae2214 main (in Reading) (main.m:43)
8   libdyld.dylib                   0x00000001ec08a8e0 _start (in libdyld.dylib) + 4

**Comment by lingol** [comment]
That's just too old. Upgrade to the latest version. v1.2.2

**Comment by liftliftlift** [comment]
> That's just too old. Upgrade to the latest version. v1.2.2

And what is the reason for the crash of the old version?

**Comment by lingol** [comment]
Simply No time for old version support.
