### ISSUE TITLE
InterProcessLock_Android::ashmemLock: fail to recover shared-lock error

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#523]
mmkv 1.2.2 Android platform

I can see the following errors on Android 5.0/8.1.0 devices

```
10:46:25.176 AM ERR InterProcessLock_Android.cpp:78::ashmemLock: fail to recover shared-lock fd=49, ret=-1, error:Try again
10:46:25.178 AM ERR MMKV_Android.cpp:230::checkProcessMode: Fail to exclusive lock [xxx]
```

The "xxx" mmkv file is opened with the multiple process mode.

Any idea what the possible cause would be?

**Comment by lingol** [comment]
Like the exaction has said,"The "xxx" mmkv file is opened with the multiple process mode.", you are opening a multi-process mmkv with single process mode.
Check your usage on the xxx mmkv instance, use multi-process mode everywhere.

**Comment by samlu** [comment]
I am sure that the "xxx" file is always opened with the multiple process mode. 

We only see this kind of error on a few devices and not always happen.

```
InterProcessLock_Android.cpp:78

// let's hope this never happen
MMKVError("fail to recover shared-lock fd=%d, ret=%d, error:%s", m_fd, ret, strerror(errno));
```

May I ask what the "Try again" error means?

**Comment by lingol** [comment]
Are there any more logs from MMKV about [xxx], before that `fail to recover shared-lock` error happened?

**Comment by lingol** [comment]
You can give it a try on the `dev` branch.
https://github.com/Tencent/MMKV/commit/339d038ab800650c8fd947bc72dccedb773c71ee

**Comment by samlu** [comment]
> Are there any more logs from MMKV about [xxx], before that `fail to recover shared-lock` error happened?
> I have an explanation. But I need more logs to make sure.

No. Only the two error lines that I can see.

**Comment by samlu** [comment]
> You can give it a try on the `dev` branch.
> [339d038](https://github.com/Tencent/MMKV/commit/339d038ab800650c8fd947bc72dccedb773c71ee) & [81187a8](https://github.com/Tencent/MMKV/commit/81187a86bc5796b043e5ca4b9f14d31c59f46dde)

Okay. I will try it and let you know if there are any updates.

**Comment by lingol** [comment]
Released with [v1.2.3](https://github.com/Tencent/MMKV/releases/tag/v1.2.3).

**Comment by siyehua** [comment]
我用了 1.2.5 的版本, 但还有解决这个问题, 发生时的日志
`
12-19 03:14:06.722 E/anager:transmi(22066): Not starting debugger since process cannot load the jdwp agent.
12-19 03:14:07.224 E/MMKV    (22066): <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [default_name_mmkv]
--------- beginning of crash
`

**Comment by lingol** [comment]
> 我用了 1.2.5 的版本, 但还有解决这个问题, 发生时的日志
> `12-19 03:14:06.722 E/anager:transmi(22066): Not starting debugger since process cannot load the jdwp agent. 12-19 03:14:07.224 E/MMKV (22066): <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [default_name_mmkv] --------- beginning of crash`

Dont's spam the same problem on multi issues.
