### ISSUE TITLE
中文文档mmkv包导入地址多加了一个空格

### ISSUE THREAD

**Issue by Richair** [Tencent/MMKV#524]
https://github.com/Tencent/MMKV/wiki/android_setup_cn
dependencies {
    implementation 'com.tencent: mmkv-static:1.2.2'
    // replace "1.2.2" with any available version
}
中文文档说明，在tencent:mmkv中间多了一个空格，导致包导入失败，在特在此提醒腾讯的诸位大佬

**Comment by lingol** [comment]
Noted, thanks.

**Comment by lingol** [comment]
Fixed.
