### ISSUE TITLE
crash mmkv::armv8_crc32(unsigned int, unsigned char const*, unsigned long) (malformed)

### ISSUE THREAD

**Issue by yunjinghui123** [Tencent/MMKV#528]
### The language of MMKV

>  Objective-C

### The version of MMKV

> 1.2.2  
### The platform of MMKV

>  iOS 12 ~13
> iPhone X  iPhone 8 iPhone Xs Max iPhone 7 Plus

### The installation of MMKV

> Cocoapods

### What's the issue?
<img width="993" alt="image" src="https://user-images.githubusercontent.com/9649401/93053177-09eaca00-f69a-11ea-82a9-51ec1843c762.png">

**Comment by lingol** [comment]
#525
