### ISSUE TITLE
Android V1.2.2 版本在无网络情况取出String数据出现错误

### ISSUE THREAD

**Issue by skyCracks** [Tencent/MMKV#530]
使用MMKV 本地存储了 token值：
正常情况下：eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIxMjMxOTRhMWQ3NzU0MTVmYWY2YWZhOTlhYTYyOTVlMSIsImV4cCI6MTYwMTQ0NDExOSwiZGlkIjoiMTcifQ.MyCMEA_igFivqDU4t4Xjg1DwWOTe9vg-rLkVfnHiJCk

无网络情况下：
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIxhas_network

回退到1.1.2版本无此问题。

**Comment by lingol** [comment]
#529

**Comment by lingol** [comment]
As far as I know, MMKV doesn't care about the network.

**Comment by skyCracks** [comment]
> As far as I know, MMKV doesn't care about the network.
> Do you use encryption? You can check #529 for a possible answer.
> If no, then it must be something else. I recommend checking your logic to find out who writes that `has_network` string.

没有进行加密，只有有一个Boolean类型数据存储key值为has_network，将这个Boolean类型存储去掉之后，测试之后没有出现这个问题。

**Comment by lingol** [comment]
OK, you can upload that file & crc file here after things go wrong without network.

**Comment by lingol** [comment]
And a demo project will be very helpful.

**Comment by lingol** [comment]
Hello, are you still there?

> OK, you can upload that file & crc file here after things go wrong without network.

**Comment by lingol** [comment]
Close due to inactive.
