### ISSUE TITLE
引入MMKVcore代码后 原有项目报错 Declaration of anonymous class must be a definition

### ISSUE THREAD

**Issue by fighting300** [Tencent/MMKV#532]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your detail logs. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.

**Comment by lingol** [comment]
Please follow the issue template, provide your info such as language, platform, version of MMKV, etc.

**Comment by lingol** [comment]
And when reporting a compiler error, you should post the relative **source code** as well. 
Otherwise, there's no way to figure out what goes wrong.

**Comment by lingol** [comment]
Close due to inactive.
