### ISSUE TITLE
How do I clean up all key values?

### ISSUE THREAD

**Issue by SuperXpher** [Tencent/MMKV#533]
### The language of MMKV
> java

### The version of MMKV
> 1.1.2 

### The platform of MMKV
> Android

### The installation of MMKV
> implementation 'com.tencent:mmkv-static:1.1.2'

### What's the issue?

> Post the outputs or screenshots for errors.
> call mmkv.clearAll() After, the local data(mmkv.default) has not been cleaned up. How do I clean up all key values?

### What's the log of MMKV when that happened?
>MMKV: <MMKV.cpp:481::clearAll> cleaning all key-values from [mmkv.default]
MMKV: <MMKV.cpp:508::clearMemoryCache> clearMemoryCache [mmkv.default]
MMKV: <MMKV.cpp:263::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3
MMKV: <MMKV.cpp:296::loadFromFile> loaded [mmkv.default] with 0 values

**Comment by lingol** [comment]
What do you mean by saying "the local data(mmkv.default) has not been cleaned up" after calling `MMKV.clearAll()`?
I believe the log has specifically tells you that there are **zero** key-values inside.
>MMKV: MMKV.cpp:296::loadFromFile loaded [mmkv.default] with 0 values

**Comment by SuperXpher** [comment]
> 调用后说“_尚未清除本地数据（mmkv.default）_ ”_是_什么意思`MMKV.clearAll()`？
> 我相信该日志已专门告诉您，其中的键值**为零**。
> 
> > MMKV：MMKV.cpp：296 :: loadFromFile已加载[mmkv.default]，值为0

Yes, the log shows that it has been cleared, but I checked the mmkv.default file in the sandbox, the previous data still exists in it, and it has not been cleared.

**Comment by lingol** [comment]
So you were worrying about information security? If that's the case, you can just delete the file. 
Otherwise, just calm down and listen to what the log has said.
