### ISSUE TITLE
Native Crash on getMMKVWithID

### ISSUE THREAD

**Issue by xiaomin8676** [Tencent/MMKV#540]
### The language of MMKV
Java
> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV
1.0.23
> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV
Android
> e.g. iOS or Android

### The installation of MMKV
Maven
> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?
Native Crash on getMMKVWithID，only happend online, we cann't make it happen locally.
 this is  the trace:

Native crash	Bus error
unknown	0

Revision: '0'
ABI: 'arm64'
pid: 5406, tid: 5422, name: Binder:5406_2  >>> #<<<
signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x7a721e4000
    x0  000000006f682e69  x1  0000007a721d3004  x2  000000000000655d  x3  0000000000000007
    x4  0000000000000037  x5  0000007a68fdc5b2  x6  0f00000000000000  x7  000000000000800f
    x8  0000000030b5ffe9  x9  000000000001753d  x10 0000000000017520  x11 0000007b0a61e2ec
    x12 0000007a721e3fe4  x13 0000007b0a61eeec  x14 0000007b0a61eaec  x15 0000007b0a61e6ec
    x16 000000000b732b72  x17 000000006a77ec5b  x18 0000000039316bae  x19 0000007a85a42c80
    x20 0000007a85a42ca8  x21 0000007a85a42cc0  x22 0000007a85a42ca8  x23 0000000000000002
    x24 0000007a69f31588  x25 0000007a85a42cd8  x26 0000000000000000  x27 000000006f838990
    x28 0000007a69f31588  x29 0000007a69f304d0
    sp  0000007a69f304c0  lr  0000007a63e51ad0  pc  0000007b0a60c568

backtrace:
    #00 pc 0000000000003568  /system/lib64/libz.so (crc32_z+672)
    #01 pc 0000000000009acc  /data/app/#-LFdFNdUfIHUt4RxoeMi8uA==/lib/arm64/libmmkv.so
    #02 pc 0000000000007c54  /data/app/#-LFdFNdUfIHUt4RxoeMi8uA==/lib/arm64/libmmkv.so
    #03 pc 00000000000073ec  /data/app/#-LFdFNdUfIHUt4RxoeMi8uA==/lib/arm64/libmmkv.so
    #04 pc 0000000000008bf8  /data/app/#-LFdFNdUfIHUt4RxoeMi8uA==/lib/arm64/libmmkv.so
    #05 pc 0000000000004634  /data/app/#-LFdFNdUfIHUt4RxoeMi8uA==/lib/arm64/libmmkv.so
    #06 pc 00000000012097fc  /data/app/#-LFdFNdUfIHUt4RxoeMi8uA==/oat/arm64/base.odex (offset 0xaef000) (com.tencent.mmkv.MMKV.getMMKVWithID+236)
    #07 pc 0000000001207ed4  /data/app/#-LFdFNdUfIHUt4RxoeMi8uA==/oat/arm64/base.odex (offset 0xaef000) (com.tencent.mmkv.MMKV.a+84)

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
we haven't get mmkv log yet.

> Your detail logs. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.

**Comment by lingol** [comment]
Upgrade to the latest version (v1.2.2 and above) and try again. Sorry, we don't have time for v1.0.x, nor v1.1.x.

**Comment by xiaomin8676** [comment]
> Upgrade to the latest version (v1.2.2 and above) and try again. Sorry, we don't have time for v1.0.x, nor v1.1.x.

Thanks for reply, have we dealed with issue like this one before?
