### ISSUE TITLE
小米手机安卓8.1.0 未存值时getLong永远是764846

### ISSUE THREAD

**Issue by fanqieVip** [Tencent/MMKV#543]
Kotlin-1.2.3-Android-AAR
小米手机安卓8.1.0，当value是Long型，key为“common_user_uuid”时，如果没有存储过值，get到的value永远是764846，卸载重装APP问题依旧，除非在应用管理里面清除该APP全部缓存，否则问题依旧。
当我把key改为“common_user_uuid1”后就不会有问题了

**Comment by fanqieVip** [comment]
经确认，应该是在该类设备，卸载APP后，内置缓存卸不掉造成的

**Comment by lingol** [comment]
You should report this bug to Xiaomi.
