### ISSUE TITLE
做一下flutter版的吧

### ISSUE THREAD

**Issue by Dboy233** [Tencent/MMKV#547]
做一下flutter版的mmkv吧。 flutter的插件mmkv这个关键字已经被长期不维护的开发者使用了。
再不搞以后的插件库名字就不好起了。

**Comment by lingol** [comment]
The problem with flutter is that people who use MMKV in flutter will also use MMKV in native(Android or iOS). So there will be two libMMKV.so in your App bundle. 
That's not acceptable to me. And I still don't know how to use only one copy of libMMKV.so to do the same.

**Comment by lingol** [comment]
> The problem with flutter is that people who use MMKV in flutter will also use MMKV in native(Android or iOS). So there will be two libMMKV.so in your App bundle.
> That's not acceptable to me. And I still don't know how to use only one copy of libMMKV.so to do the same.

In case some may say that they use pure flutter code or they simply don't care about App size, I have a look into flutter plugin dev this afternoon. The find out is not satisfying. Currently, the official guild for plugin development recommends using `MethodChannel` to communicate between Dart and native code, which means each call to MMKV will involve a **thread switch**. 
That's simply too much. It will make MMKV's core feature, aka **speed**, irreverent.

The [dart:ffi](https://api.dart.dev/dev/dart-ffi/dart-ffi-library.html) library looks like a solution. Yet it's still in beta and lacks considerable functionalities such as passing dart function as a callback, auto binding to C++ STL strings & containers, etc.
We will keep an eye on this issue.

**Comment by Dboy233** [comment]
Thank you for the answer. I see.

**Comment by lingol** [comment]
[Looks like](https://groups.google.com/g/dart-ffi/c/6vKmRgLeH4Y/m/dt8gARLVBgAJ) we can use `dart:ffi` even when it's in beta. I will give it a try and see what comes out.

**Comment by Dboy233** [comment]
Okay, I'll try to use it in my own project.

**Comment by lingol** [comment]
Release with [v1.2.6](https://github.com/Tencent/MMKV/releases/tag/v1.2.6). Checkout the [wiki](https://github.com/Tencent/MMKV/wiki/flutter_setup) for usage.
