### ISSUE TITLE
android.preference 库已弃用-- Android 10

### ISSUE THREAD

**Issue by ypus1987** [Tencent/MMKV#548]
android.preference 库已弃用
从 Android 10 开始，将弃用 android.preference 库。

**Comment by lingol** [comment]
Noted. Google suggests using `androidx.preference` instead. 
I assume that's part of the `androidx` library migration work. Nothing to do with performance improvement.

**Comment by lingol** [comment]
I have checked the MMKV project and I don't think MMKV have anything to do with the `android.preference` library. 
Where do you think it's been used?

**Comment by ypus1987** [comment]
public class MMKV implements SharedPreferences, Editor




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Guo Ling"<notifications@github.com&gt;; 
发送时间: 2020年10月26日(星期一) 下午3:18
收件人: "Tencent/MMKV"<MMKV@noreply.github.com&gt;; 
抄送: "水月洞天"<287072279@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tencent/MMKV] android.preference 库已弃用-- Android 10 (#548)





 
I have checked the MMKV project and I don't think MMKV has anything to do with the android.preference library.
 Where do you think it's been used?
 
&mdash;

**Comment by lingol** [comment]
That's `android.content.SharedPreferences`, not `android.preference`.

**Comment by ypus1987** [comment]
I know，Thanks。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Guo Ling"<notifications@github.com&gt;; 
发送时间: 2020年10月26日(星期一) 下午3:24
收件人: "Tencent/MMKV"<MMKV@noreply.github.com&gt;; 
抄送: "水月洞天"<287072279@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tencent/MMKV] android.preference 库已弃用-- Android 10 (#548)





 
Closed #548.
 
&mdash;
