### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/proguard/androidx-annotations.pro'

### ISSUE THREAD

**Issue by moshangpiaoxue** [Tencent/MMKV#549]
步骤：
1 添加依赖：  implementation 'com.tencent:mmkv-static:1.2.4' 
2、同步后直接运行程序会报：More than one file was found with OS independent path 'META-INF/proguard/androidx-annotations.pro'
3、网上的解决方案，在gradle添加下面这个会报另一个
//    packagingOptions {
//        pickFirst 'META-INF/*'
//    }
会引出另外一个问题，运行程序后直接白屏，但是log里能看到我的网络请求正常在跑

**Comment by lingol** [comment]
```
    packagingOptions {
        exclude 'META-INF/proguard/androidx-annotations.pro'
    }
```
Try this.

**Comment by moshangpiaoxue** [comment]
packagingOptions {
        pickFirst 'META-INF/proguard/androidx-annotations.pro'
    }
用exclude 字段会白屏，并且Application里会不断初始化，在log看到的，大概3秒友盟的初始化log就会刷一次

**Comment by lingol** [comment]
Sorry but this issue is new to me as well. There's nothing more I can do for you, for MMKV's use of the `androidx` lib has nothing wrong.
Maybe you should Google about it and fix it by yourself.

**Comment by lingol** [comment]
And if you find the solution, please come back and provide it here. Thanks.

**Comment by lingol** [comment]
Did any of the libraries you use, including your main App, use androidx with an **alpha** version or version lower than v1.1.0? If so, you should consider using the latest version of androidx (v1.1.0) everywhere.

```gradle
dependencies {
    implementation 'androidx.annotation:annotation:1.1.0'
}
```

**Comment by lingol** [comment]
Hi, any luck yet?

**Comment by lingol** [comment]
Close due to inactive.
