### ISSUE TITLE
保存数组有问题

### ISSUE THREAD

**Issue by BinBear** [Tencent/MMKV#550]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Objective-C

### The version of MMKV
 

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

v1.2.4

### The platform of MMKV

> e.g. iOS or Android

iOS

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

Cocoapods

### What's the issue?
![截屏2020-11-03 下午3 49 48](https://user-images.githubusercontent.com/13587915/97960922-478fe780-1ded-11eb-8ea0-b9add427532e.png)
![截屏2020-11-03 下午3 48 58](https://user-images.githubusercontent.com/13587915/97960929-4ced3200-1ded-11eb-8d94-0fd5535b236d.png)

使用 mmkvWithID: cryptKey: 创建的mmkv对象来保存数组时候会进入下图的断言，如果是 defaultMMKV 则不会

**Comment by lingol** [comment]
Fixed in the `dev` branch.

**Comment by BinBear** [comment]
When will it be released

**Comment by lingol** [comment]
Hopefully this week, or next week.

**Comment by mateosilguero** [comment]
Same error here :(

**Comment by horaciom** [comment]
please merge this fix!

**Comment by lingol** [comment]
OK, your voices are heard. I will make a merge to the master branch ASAP.

**Comment by lingol** [comment]
The fix has been merged into the master branch. For those who are affected, you can modify your Podfile to depend on the master branch instead of a specific tag name.
A new release, however, won't come out next week. I will notify you guys under this issue when it's out. Stay tuned.

**Comment by BinBear** [comment]
When will it be released

**Comment by BinBear** [comment]
I modify Podfile depend：
pod 'MMKV', :git => 'https://github.com/Tencent/MMKV'
But cannot update the latest code，Hope you can release as soon as possible

**Comment by BinBear** [comment]
I modify Podfile to depend on the master:
pod 'MMKV', :git => 'https://github.com/Tencent/MMKV.git'
But can't update the latest code, Hope you can release  as soon as possible

**Comment by lingol** [comment]
Like I have said before, it will roll out this week, one way or another.

**Comment by lingol** [comment]
Released with [v1.2.5](https://github.com/Tencent/MMKV/releases/tag/v1.2.5).
