### ISSUE TITLE
iOS memory leak

### ISSUE THREAD

**Issue by a8695363** [Tencent/MMKV#551]
need delete[] encryptText;
![image](https://user-images.githubusercontent.com/18377130/97965149-e2d88b00-1df4-11eb-982c-f7c43f9717c0.png)

need NSString *result = [[[NSString alloc] initWithBytes:ptr length:s_size encoding:NSUTF8StringEncoding] autorelease];
![image](https://user-images.githubusercontent.com/18377130/97965211-f8e64b80-1df4-11eb-8b08-dc7afec0d6f6.png)

**Comment by lingol** [comment]
Fixed in the `dev` branch. Note that this is in a test code, so don't you worry about any leak in the production/release code.

**Comment by lingol** [comment]
`need NSString *result = [[[NSString alloc] initWithBytes:ptr length:s_size encoding:NSUTF8StringEncoding] autorelease];`
That's fixed as well. 
It's a little complicated than missing `autorelease`, for that's already added. 
If you are interested, you can check out the commit above.

**Comment by lingol** [comment]
Released with [v1.2.5](https://github.com/Tencent/MMKV/releases/tag/v1.2.5).
