### ISSUE TITLE
ClassCastExceptionjava.util.HashMap$Nodecannotbecasttojava.util.HashMap$TreeNodecom.tencent.mmkv.MMKV.checkProcessMode

### ISSUE THREAD

**Issue by 532922397** [Tencent/MMKV#552]
# main(1)java.lang.ClassCastExceptionjava.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
 1 java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1850)
 2 java.util.HashMap$TreeNode.treeify(HashMap.java:1967)
 3 java.util.HashMap.treeifyBin(HashMap.java:784)
 4 java.util.HashMap.putVal(HashMap.java:656)
 5 java.util.HashMap.put(HashMap.java:624)
 6 java.util.HashSet.add(HashSet.java:219)
 7 com.tencent.mmkv.MMKV.checkProcessMode(MMKV.java:286)
 8 com.tencent.mmkv.MMKV.mmkvWithID(MMKV.java:168)
 9 com.xx.xx.core.sharedpreferences.c.b(SPUtil.kt:61)
 10 com.xx.xx.bean.ModelAdaptStrategy.setStrategies(ModelAdaptStrategy.java:47)
 11 com.xx.xx.framework.pushagent.a.a$8.a(PushAgent.java:454)
 12 com.xx.xx.a.b.b.a(ConcretePushParser.java:167)
 13 com.meitu.pushagent.a.b.b.lambda$cL3lQUNRAgukLetxbNUj3w5TSvE(Unknown Source:0)
 14 com.meitu.pushagent.a.b.-$$Lambda$b$cL3lQUNRAgukLetxbNUj3w5TSvE.run(Unknown Source:4)
 15 android.os.Handler.handleCallback(Handler.java:900)
 16 android.os.Handler.dispatchMessage(Handler.java:103)
 17 android.os.Looper.loop(Looper.java:219)
 18 android.app.ActivityThread.main(ActivityThread.java:8349)
 19 java.lang.reflect.Method.invoke(Native Method)
 20 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
 21 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by 532922397** [comment]
version:1.2.3

**Comment by lingol** [comment]
I need all call stacks from all threads, not just the main thread.

**Comment by lingol** [comment]
> I need all call stacks from all threads, not just the main thread.

Specifically, is there any other thread also accessing the same HashSet?

**Comment by 532922397** [comment]
No multi thread access to log was found。
I'll try 
![Uploading image.png…]()

**Comment by 532922397** [comment]
When will it be available？

**Comment by lingol** [comment]
> When will it be available？

Hopefully this week.

**Comment by lingol** [comment]
Released with [v1.2.5](https://github.com/Tencent/MMKV/releases/tag/v1.2.5).
