### ISSUE TITLE
mmkv::MMKV::set(bool, NSString*) (malformed)

### ISSUE THREAD

**Issue by yunjinghui123** [Tencent/MMKV#555]
### The language of MMKV

> Objective-C

### The version of MMKV

> pod 'MMKV', '1.2.2'

### The platform of MMKV

>  iOS

### The installation of MMKV

>Cocoapods

### What's the log of MMKV when that happened?
    [[MMKV defaultMMKV] setBool:YES forKey:@"KEY"];

MMKVCore    0x68e8    mmkv::armv8_crc32(unsigned int, unsigned char const*, unsigned long) (malformed)
MMKVCore    0x10c60    mmkv::MMKV::doFullWriteBack(std::__1::pair<mmkv::MMBuffer, unsigned long>, mmkv::AESCrypt*) (malformed)
MMKVCore    0x10268    mmkv::MMKV::ensureMemorySize(unsigned long) (malformed)
MMKVCore    0x11be4    mmkv::MMKV::doAppendDataWithKey(mmkv::MMBuffer const&, mmkv::MMBuffer const&, bool, unsigned int) (malformed)
MMKVCore    0x11538    mmkv::MMKV::appendDataWithKey(mmkv::MMBuffer const&, NSString*, bool) (malformed)
MMKVCore    0x11194    mmkv::MMKV::setDataForKey(mmkv::MMBuffer&&, NSString*, bool) (malformed)
MMKVCore    0xcaa0    mmkv::MMKV::set(bool, NSString*) (malformed)
YouPinHui    0x10036d88c    -[HMUserPrivacyView agreeAction:] +64 (HMUserPrivacyView.m:106)
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/9649401/98617890-f5921900-233a-11eb-865e-e2aeb8e418a2.png">

**Comment by lingol** [comment]
Upgrade to the latest version and try again.
