### ISSUE TITLE
磁盘文件的同步时机问题

### ISSUE THREAD

**Issue by EnjoyCoding007** [Tencent/MMKV#557]
了解到：“一般说来，进程在映射空间的对共享内容的改变并不直接写回到磁盘文件中，往往在调用munmap（）后才执行该操作。

可以通过调用msync()实现磁盘上文件内容与共享内存区的内容一致。”

在使用文档中都没有相关接口的调用，请问一下mmkv的内部实现，磁盘文件被内存文件同步的时机是同步的还是异步的呢？如果，默认是异步，需要主动调用“- (void)sync”来完成同步吗？

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/FAQ_cn

**Comment by EnjoyCoding007** [comment]
Thanks.
