### ISSUE TITLE
v1.2.4 加密会导致所有数据丢失的问题

### ISSUE THREAD

**Issue by KotlinLan** [Tencent/MMKV#558]
机型：oneplus 5t android 10 系统
采用加密方式进行保存，第一次安装打开，会根据一个bool值判断是否弹窗，用户点击同意后，保存值为true 
退出app并完全杀死，重新打开又弹窗了，这样看来是数据丢失了，但是这个时候，退出app又完全杀死，就不会有这样的情况出现，也就是说会杀死app退出，会出现一次，不管设置MULTI_PROCESS_MODE或者SINGLE_PROCESS_MODE都是一样；
以下截图是数据丢失时的错误日志
![image](https://user-images.githubusercontent.com/50512101/98781528-6d426f80-2431-11eb-9bb1-aae5ccf1ffa1.png)

**Comment by lingol** [comment]
Looks like the file is corrupted.
Upload your file here (and the relative crc file as well) just before your second launch. 
And provide the encryption key for the file. You might consider using a temporary encryption key for this.

**Comment by KotlinLan** [comment]
经排查，因为加密key是动态的，并且依赖第三方sdk，当第三方sdk没有相关权限获取到的信息是不一样，从而引起了这个问题，谢谢你的解答，后续有问题会继续跟进。
