### ISSUE TITLE
MMKV取对象数据时空指针

### ISSUE THREAD

**Issue by BeiHaiCoding** [Tencent/MMKV#559]
>Kotlin
>  v1.2.4
>Android
> Maven,

我使用MMKV保存User数据，User如下：
`data class User(
    val address: String,
    val age: Int,
    val icon: String="",
    val nickname: String,
    val phone: String,
    val sex: String,
    val token: String,
    val username: String
): Parcelable,BaseObservable(){

    constructor(parcel: Parcel) : this(
        parcel.readString()!!,
        parcel.readInt(),
        parcel.readString()!!,
        parcel.readString()!!,
        parcel.readString()!!,
        parcel.readString()!!,
        parcel.readString()!!,
        parcel.readString()!!
    )

    override fun describeContents(): Int {
        return 0
    }

    override fun writeToParcel(p0: Parcel, p1: Int) {
        p0.apply {
            writeString(address)
            writeInt(age)
            writeString(icon)
            writeString(nickname)
            writeString(phone)
            writeString(sex)
            writeString(username)
            writeString(token)
        }
    }

    companion object CREATOR : Parcelable.Creator<User> {
        override fun createFromParcel(parcel: Parcel): User {
            return User(parcel)
        }

        override fun newArray(size: Int): Array<User?> {
            return newArray(size)
        }
    }

}`
保存的时候成功了，但是取数据的时候MMKV一直报NullPointerException，日志如下:
`I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 613 actual size, file size 4096, InterProcess 0, meta info version:3
 I/MMKV: <MMKV_IO.cpp:86::loadFromFile> loading [mmkv.default] with crc 2145624805 sequence 1 version 3
 I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 2 key-values
 E/MMKV: java.lang.NullPointerException`

只有取对象数据才会发生（可以保存，并且有键值），存取基本数据和String数据没有问题。
想问下有什么办法排查问题吗？

**Comment by lingol** [comment]
Show me your crash call stacks.

**Comment by BeiHaiCoding** [comment]
没有奔溃，只是无法取数据
![image](https://user-images.githubusercontent.com/30135449/98893118-c2878b00-24dc-11eb-8cf2-898843240e39.png)
日志只有一个NullPointerException的提示。

**Comment by lingol** [comment]
I don't think it has anything to do with MMKV. 
Have you try to encode your object to Bytes and decode from that Bytes directly? I suspect that will throw an exception as well.

**Comment by BeiHaiCoding** [comment]
I only use  mmkv.encode to write User object and use mmkv.decodeParcelable to read User object, but when i read the data, the data is null ( I sure exist the key in MMKV)

**Comment by BeiHaiCoding** [comment]
when  I read String data, it's true

**Comment by lingol** [comment]
You don't get it. I mean encode it to Bytes and decode it directly, not by MMKV, but by yourself. I will explain later.

**Comment by BeiHaiCoding** [comment]
I see what you mean , I will try it later. Thanks!

**Comment by lingol** [comment]
Like this:

```Java
        // encode to bytes
        User user = ...;
        Parcel source = Parcel.obtain();
        value.writeToParcel(source, value.describeContents());
        byte[] bytes = source.marshall();
        source.recycle();

        // decode from bytes
        Parcel source2 = Parcel.obtain();
        source2.unmarshall(bytes, 0, bytes.length);
        source2.setDataPosition(0);
        User result = User.CREATOR.createFromParcel(source2);
```

**Comment by BeiHaiCoding** [comment]
very thanks

**Comment by BeiHaiCoding** [comment]
I try it like this
![image](https://user-images.githubusercontent.com/30135449/98896461-fb772e00-24e3-11eb-991d-8905ae55fab5.png)
And I get this 
![image](https://user-images.githubusercontent.com/30135449/98896530-16e23900-24e4-11eb-8b98-848fc5ed0d2f.png)

**Comment by lingol** [comment]
And **the same** user object goes inside MMKV, you get an exception?

**Comment by BeiHaiCoding** [comment]
yeah , get a error log
![image](https://user-images.githubusercontent.com/30135449/98896680-85bf9200-24e4-11eb-8f92-e5644c9d52e9.png)

**Comment by lingol** [comment]
OK, upload your source file here. I'll have a look later afternoon.

**Comment by BeiHaiCoding** [comment]
I forget this file . I package MMKV to SpUtil . like this 
![image](https://user-images.githubusercontent.com/30135449/98896861-f8c90880-24e4-11eb-876c-7e217be50efc.png)
![image](https://user-images.githubusercontent.com/30135449/98896883-01214380-24e5-11eb-9bd4-543778c2b999.png)
I use the util can get String data, but cannot get User object data

**Comment by lingol** [comment]
That doesn't matter. I need your `User` class file & the test case code, that's all.

**Comment by lingol** [comment]
Oh, wait. Maybe it does matter. Can you set a breakpoint inside `func encode(key: String, value: Any?)`? 
I doubt that when you encode a user object, it goes into that func instead of the generic func bellow.

**Comment by BeiHaiCoding** [comment]
good idea

**Comment by BeiHaiCoding** [comment]
嗨，非常感谢您的帮助。我已解决该问题。问题的原因不是调用错了SpUtil的函数，而是User里icon字段为空的原因。因为调试了刚才您说的那个方法，注意到了icon这个字段为空可能会导致MMKV编解码。所以最终发现了该问题，非常感谢您的帮助。
