### ISSUE TITLE
Failed to compile v1.2.5 when MMKV_DISABLE_CRYPT is defined

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#564]
MMKV 1.2.5

If MMKV_DISABLE_CRYPT is defined, we will get the following compilation error:
Android\MMKV\mmkv\src\main\cpp\flutter-bridge.cpp:215:24: error: no member named 'reKey' in 'MMKV'

**Comment by lingol** [comment]
Noted. For the moment, you can make a hotfix locally. Should not be a big big problem for you, I assume.

**Comment by samlu** [comment]
Yes, it's not a problem for me to handle this issue.

**Comment by lingol** [comment]
Fixed in the dev branch 5a89f31. 
Also,  `MMKV_DISABLE_FLUTTER` is added. You might gonna make use of it.

**Comment by lingol** [comment]
Release with [v1.2.6](https://github.com/Tencent/MMKV/releases/tag/v1.2.6).
