### ISSUE TITLE
能否支持监听者模式？

### ISSUE THREAD

**Issue by saiwailiuxing** [Tencent/MMKV#565]
MMKV类的registerOnSharedPreferenceChangeListener并没有实现，是否无法支持实时监听key-value发生变化？
类似于SharedPreference的监听者模式？

**Comment by lingol** [comment]
No. We don't do it on purpose. 
It's not because adding a listener is difficult or something, it's because that will harm performance.
You can, however, listen on `onContentChange()`, which will notify you ** sometime later** after **other processes** changed the file.
