### ISSUE TITLE
为什么MMKV生成的文件会比SP的xml大

### ISSUE THREAD

**Issue by inwhites** [Tencent/MMKV#566]
Android使用的MMKV进行存储，生成了两个文件demo和demo.crp其中demo文件大小居然有4M，crp只有4kb，而sp生成的xml只有200多kb，这是为啥啊？理论上采用编码不是更省空间吗

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/design

**Comment by lingol** [comment]
MMKV never talks about file size. All it matters is performance & data intergrity.
