### ISSUE TITLE
能否跨多个应用使用mmkv

### ISSUE THREAD

**Issue by xiaoxixi615** [Tencent/MMKV#568]
demo里是在一个app里开启了多个service进程，然后跨进程访问，mmkv文件都是存在app的files/mmkv/目录下。
能否在多个App里跨进程访问，比如AppA进程写入值，然后AppB读取， 我这边尝试了一下，好像不能成功，AppB好像无法读取AppA创建的目录files/mmkv/，不知道我的理解是否有误。

**Comment by lingol** [comment]
You are right. One app can't simply access another app's `files` directory (so is `files/mmkv`).
