### ISSUE TITLE
一个安全问题 | A security issue

### ISSUE THREAD

**Issue by Dboy233** [Tencent/MMKV#569]
### The language of MMKV

> java

### The version of MMKV
 这个问题是我去年发现的，不记得当时的版本号了。

### The platform of MMKV
> android

### The installation of MMKV
> Maven

### What's the issue?
>#### 这个问题是我去年发现的，当时保存了一些简单的用户数据，但是我将mmkv保存的文件复制到另一个app项目里。
>#### 等mmkv初始化完成后，也可以直接读取另外一个app保存的信息。
>#### 我通过遍历key，并修改value。再将文件复制回原来的app里。里面的数据确实被修改了。
>#### 这样可能有安全风险。现在的版本我没有测试过是否还有这个问题。不知道你们之前有没有发现并优化这个问题。

>#### This problem was discovered last year, when some simple user data was saved, but I copied the files saved by mmkv to >another app project.
>#### Another mmkv app can also be read directly after initialization.
>#### I go through the key and modify the value. Then copy the file back to the original app. The data in it has been modified.
>#### There may be security risks. I haven't tested the current version for this problem. I don't know if you have found and optimized this problem before.

**Comment by lingol** [comment]
That's not MMKV's problem. You should keep MMKV's root path inside your App's sandbox directory.
If you really worry about that, you can use MMKV with encryption. https://github.com/Tencent/MMKV/wiki/android_advance_cn#%E5%8A%A0%E5%AF%86
