### ISSUE TITLE
onDestroy方法中必须调用MMKV.onExit()方法嘛？

### ISSUE THREAD

**Issue by duanyuGit** [Tencent/MMKV#57]
onDestroy方法调用MMKV.onExit是为了清除缓存嘛？还有其它作用嘛？如果不调用有什么问题？

**Comment by ysbing** [comment]
Called when the process leaves, it can immediately synchronize the data to the file and empty the cache data for that process.

**Comment by duanyuGit** [comment]
> Called when the process leaves, it can immediately synchronize the data to the file and empty the cache data for that process.

如果不调用，有没有问题？

**Comment by lingol** [comment]
It's quit OK not calling onExit() in onDestroy. Data won't lose if there's no immediate device shutdown.
But it's recommended. Shit happens, you know.

**Comment by lingol** [comment]
I hate to repeat myself. **It's quit OK not calling onExit() in onDestroy. Data won't lose if there's no immediate device shutdown.**.
