### ISSUE TITLE
failed to compile mmkv 1.2.6

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#578]
mmkv 1.2.6

Got the following error while compiling mmkv 1.2.6 
`Core/MMKVLog_Android.cpp:71: error: undefined reference to '_getFileName(char const*)'`

**Comment by lingol** [comment]
Which NDK do you use?

**Comment by samlu** [comment]
21.3.6528147

**Comment by lingol** [comment]
Noted. Maybe MMKV should drop the support of `armeabi` as well, then we could use the latest NDK.

**Comment by lingol** [comment]
Fixed in the dev branch b722143.

**Comment by samlu** [comment]
The fixed code works. Thanks.

**Comment by lingol** [comment]
Released with [v1.2.7](https://github.com/Tencent/MMKV/releases/tag/v1.2.7).
