### ISSUE TITLE
是否有计划推出一个golang封装的版本

### ISSUE THREAD

**Issue by zxxf18** [Tencent/MMKV#579]
如题，是否有这样的计划呢，如果做的话会采用cgo包一下还是怎么样呢

**Comment by lingol** [comment]
Why, do you need MMKV on a server?

**Comment by zxxf18** [comment]
考虑在云原生项目下使用，比如边缘计算场景中，边缘设备适合这样一个小的kv型数据库

**Comment by lingol** [comment]
Noted. We will look into it.

**Comment by lingol** [comment]
Just asking, do you use gc or gccgo?

**Comment by lingol** [comment]
Golang is supported now. https://github.com/Tencent/MMKV/releases/tag/v1.2.6-golang

**Comment by wustwg** [comment]
> Golang is supported now. https://github.com/Tencent/MMKV/releases/tag/v1.2.6-golang

这个看起来太弱了，能不能发布到go仓库去？
