### ISSUE TITLE
feature request 支持flutter 插件形式

### ISSUE THREAD

**Issue by 1and1get2** [Tencent/MMKV#58]
RT

**Comment by lingol** [comment]
Checkout this issue #48

**Comment by 1and1get2** [comment]
awesome！

**Comment by lingol** [comment]
Release with [v1.2.6](https://github.com/Tencent/MMKV/releases/tag/v1.2.6). Checkout the [wiki](https://github.com/Tencent/MMKV/wiki/flutter_setup) for usage.
