### ISSUE TITLE
Android 读取单进程数据出现异常

### ISSUE THREAD

**Issue by hongqinghe** [Tencent/MMKV#580]
### The language of MMKV

> Kotlin

### The version of MMKV

> e.g. v1.2.6
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> Android

### The installation of MMKV

>  AAR 

### What's the issue?

>项目没有开启多进程，读取同一个KEY 会出现如下错误（没有进行任何的删除操作）,创建方式 `MMKV.defaultMMKV()`

>
![Xnip2020-12-01_20-54-46](https://user-images.githubusercontent.com/25189458/100745999-14a43800-341b-11eb-8895-c1b7b019caee.jpg)
)
> 但是如果使用多进程创建MMKV 实例` MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE,"")`，读取存贮字段正常

> 请问出现这种问题是不是内部存贮方式的问题，还是必须开启多进程才能访问

**Comment by lingol** [comment]
I don't see any MMKV error or any MMKVs logs here.

**Comment by lingol** [comment]
Maybe you should upload a demo project to represent your point.

**Comment by duanwei913** [comment]
We had faced a very similar scenarios recently with `com.tencent:mmkv-static:1.2.2`, with the setup of

**Comment by duanwei913** [comment]
We had faced very similar scenarios recently with `com.tencent:mmkv-static:1.2.2`, the setup being 
`
MMKV.initialize(this)
private static MMKV kv = MMKV.mmkvWithID("FileName", MMKV.SINGLE_PROCESS_MODE, "SomeAppId");
`.
when constantly performing `String value = kv.decodeString(Key, "");` from non-UI thread and UI thread concurrently, the resulting value jumps between regular JsonObject data we wrote before and some weird string `\u000F\u0003g`

**Comment by lingol** [comment]
Like I said, a demo project will be very helpful.

**Comment by lingol** [comment]
Would any one of you two like to provide a demo project?

**Comment by lingol** [comment]
Close due to inactive.
