### ISSUE TITLE
memory increase 12MB after set a bool key between true and false 9500 times

### ISSUE THREAD

**Issue by jeffy26** [Tencent/MMKV#581]
mmkv ：1.1.2
platform: Linux

> 使用 append 实现增量更新带来了一个新的问题，就是不断 append 的话，文件大小会增长得不可控。例如同一个 key 不断更新的话，是可能耗尽几百 M 甚至上 G 空间，而事实上整个 kv 文件就这一个 key，不到 1k 空间就存得下。这明显是不可取的。我们需要在性能和空间上做个折中：以内存 pagesize 为单位申请空间，在空间用尽之前都是 append 模式；当 append 到文件末尾时，进行文件重整、key 排重，尝试序列化保存排重结果；排重后空间还是不够用的话，将文件扩大一倍，直到空间足够。

if pagesize is 4KB , how much memory will be used at most for a single key append in a single MMKV instance??

**Comment by lingol** [comment]
You should use the latest version.

**Comment by jeffy26** [comment]
any commit for this condition,or 1.1.2 had this problem actually ?

**Comment by lingol** [comment]
Not that I record. Just don't have time to support old versions.

**Comment by lingol** [comment]
So, have you tried it yet? Can you reproduce this on the latest version? If that happens, post your demo code here.

**Comment by lingol** [comment]
Close due to inative.
