### ISSUE TITLE
mmkv flutter 安装不上

### ISSUE THREAD

**Issue by liziyang0625** [Tencent/MMKV#584]
1.2.7版本，提示

  -> Fetching podspec for `mmkv` from `.symlinks/plugins/mmkv/ios`
    [!] No podspec found for `mmkv` in `.symlinks/plugins/mmkv/ios`

**Comment by lingol** [comment]
Please read the wiki carefully. https://github.com/Tencent/MMKV/wiki/flutter_setup#ios

**Comment by liziyang0625** [comment]
wiki. https://github.com/Tencent/MMKV/wiki/flutter_setup#ios
