### ISSUE TITLE
A Native Crash about MMKV

### ISSUE THREAD

**Issue by iceAnson** [Tencent/MMKV#585]
### The language of MMKV

> Java

### The version of MMKV

> 1.0.17

### The platform of MMKV

> Android

### The installation of MMKV

>  AAR Package

### What's the issue?

DEBUG   : total lines: 2882, matched 1028 lines, write 1028 lines.
12-09 10:04:00.724 24768 24746 E DEBUG   : total address size: 2013432 kB
12-09 10:04:00.724 24768 24746 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
12-09 10:04:00.724 24768 24746 E DEBUG   : Process Name: 'com.xx.xx'
12-09 10:04:00.724 24768 24746 E DEBUG   : Thread Name: 'TaskManager('
12-09 10:04:00.724 24768 24746 E DEBUG   : pid: 24625, tid: 24746  >>> com.xx.xx <<<
12-09 10:04:00.724 24768 24746 E DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
12-09 10:04:00.724 24768 24746 E DEBUG   :   r0 00000000  r1 000060aa  r2 00000006  r3 b385fec8
12-09 10:04:00.724 24768 24746 E DEBUG   :   r4 b385fedc  r5 b385fec0  r6 00006031  r7 0000016b
12-09 10:04:00.725 24768 24746 E DEBUG   :   r8 b385fed8  r9 b385fec8  10 b385fef8  fp b385fee8
12-09 10:04:00.725 24768 24746 E DEBUG   :   ip 000060aa  sp b385fe98  lr efbe1143  pc efbe1156  cpsr 000f0030
12-09 10:04:00.725 24768 24746 E DEBUG   :   d0  0000000000000000  d1  0000000000000000
12-09 10:04:00.725 24768 24746 E DEBUG   :   d2  0000000000000000  d3  000003e800000000
12-09 10:04:00.725 24768 24746 E DEBUG   :   d4  0000000000000004  d5  0000000000000000
12-09 10:04:00.725 24625 24666 I MMKV    : <MMKV.cpp:328::loadFromFile> loading [rsa_pub_file] with 15 size in total, file size is 4096
12-09 10:04:00.725 24768 24746 E DEBUG   :   d6  00000000c3b9c8a0  d7  00000000c3b9c8a8
12-09 10:04:00.725 24625 24666 I MMKV    : <MMKV.cpp:351::loadFromFile> loading [rsa_pub_file] with crc 3242610001 sequence 2
12-09 10:04:00.725 24625 24666 I MMKV    : <MMKV.cpp:372::loadFromFile> loaded [rsa_pub_file] with 1 values
12-09 10:04:00.725 24768 24746 E DEBUG   :   d8  0000000000000000  d9  0000000000000000
12-09 10:04:00.725 24768 24746 E DEBUG   :   d10 0000000000000000  d11 0000000000000000
12-09 10:04:00.725 24768 24746 E DEBUG   :   d12 0000000000000000  d13 0000000000000000
12-09 10:04:00.725 24768 24746 E DEBUG   :   d14 0000000000000000  d15 0000000000000000
12-09 10:04:00.725 24768 24746 E DEBUG   :   d16 0000000000000000  d17 0000000000000000
12-09 10:04:00.725 24768 24746 E DEBUG   :   d18 0000000000000002  d19 0000000000000000
12-09 10:04:00.725 24768 24746 E DEBUG   :   d20 0000000000000000  d21 0000000000000000
12-09 10:04:00.725 24768 24746 E DEBUG   :   d22 3fa55316fff040a0  d23 43380000000004fc
12-09 10:04:00.725 24768 24746 E DEBUG   :   d24 3f50000000000000  d25 3d2ef35793c76730
12-09 10:04:00.725 24768 24746 E DEBUG   :   d26 bf40000000000000  d27 bfe5515621f780a3
12-09 10:04:00.725 24768 24746 E DEBUG   :   d28 bff2455b90657c59  d29 bfe555555529a47a
12-09 10:04:00.725 24768 24746 E DEBUG   :   d30 3fe994456859c3eb  d31 40026bb1fbaaab00
12-09 10:04:00.725 24768 24746 E DEBUG   :   scr 60000010

it happens at Hua Honor 10 sometimes  . hot to fix it?

**Comment by lingol** [comment]
Upgrade to the latest version. If it still happens, open a new issue.
