### ISSUE TITLE
flutter在IOS模拟器上运行不起来

### ISSUE THREAD

**Issue by zhangjz-109** [Tencent/MMKV#586]
flutter环境

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E287 darwin-x64,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

第一次运行是没问题，这时候GeneratedPluginRegistrant.m是这样的
![image](https://user-images.githubusercontent.com/66583493/101726862-49d11a00-3aee-11eb-9ae8-cb81e3dc4236.png)

然后杀掉进程，然后再次运行，这个文件就会变成这样，然后导致运行不起来
![image](https://user-images.githubusercontent.com/66583493/101726547-b7c91180-3aed-11eb-8f31-46ee92d3f215.png)

错误如下：
![image](https://user-images.githubusercontent.com/66583493/101727212-0c20c100-3aef-11eb-9337-fb8d1adabb2d.png)

**Comment by lingol** [comment]
I recommend using Xcode to run in the simulator.

**Comment by zhangjz-109** [comment]
> I recommend using Xcode to run in the simulator.
在Xcode运行可以，为什么在android  studio  运行的时候会出现以上问题呢？

**Comment by lingol** [comment]
I guess Android Studio will run `flutter get` each time before running. And that will override the file.
