### ISSUE TITLE
Add document for fd usages

### ISSUE THREAD

**Issue by coldcode001** [Tencent/MMKV#593]
On Android it uses mmap() to implement the MMKV, and for multi process mode file lock is used.
Then is there any document about the usages of file descriptor (I mean the max count of fd used in MMKV) on WIKI?
1. for Multi-process mode (true/false) + defaultMMKV()
2. extra fds used for mmkvWithID()?

**Comment by lingol** [comment]
File lock won't use anymore FDs, MMKV's implementation just reuse the meta file's FD.
So All in All, MMKV will use **two** FD for each MMKV instance, regardless of whether it's multi-process mode or not.

**Comment by coldcode001** [comment]
Great, thanks for your quick reply.

**Comment by coldcode001** [comment]
@lingol Could you please kindly add such Q/A on FAQ page?

**Comment by lingol** [comment]
Will do if there's someone else that also raises worry about FD.

**Comment by lingol** [comment]
It's added along with #598 .
