### ISSUE TITLE
About kotlin version conflict After update mmkv to 1.2.6

### ISSUE THREAD

**Issue by iceAnson** [Tencent/MMKV#594]
### The language of MMKV

> Java, or Kotlin

### The version of MMKV

> 1.2.6

### The platform of MMKV

> Android

### What's the issue?

How to fix this problem ,my  project uses kotlin version 1.3 

Runtime JAR files in the classpath have the version 1.1, which is older than the API version 1.3. Consider using the runtime of version 1.3, or pass '-api-version 1.1' explicitly to restrict the available APIs to the runtime of version 1.1. You can also pass '-language-version 1.1' instead, which will restrict not only the APIs to the specified version, but also the language features
w: /Users/mu/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.1.51/e34fe80c9714240525f665113dd3749415515655/kotlin-stdlib-1.1.51.jar: Runtime JAR file has version 1.1 which is older than required for API version 1.3

**Comment by lingol** [comment]
I don't know. Have you try to Google about it yet?

**Comment by lingol** [comment]
I have checked MMKV's kotlin version. It's v1.4.10.

**Comment by lingol** [comment]
https://www.google.com/search?q=Runtime+JAR+files+in+the+classpath+have+the+version+1.1%2C+which+is+older+than+the+API+version+1.3&rlz=1C5CHFA_enCN870CN870&oq=Runtime+JAR+files+in+the+classpath+have+the+version+1.1%2C+which+is+older+than+the+API+version+1.3&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8

**Comment by iceAnson** [comment]
ok,thanks ,i fix it.
