### ISSUE TITLE
NPE when calling putStringSet() if value is null

### ISSUE THREAD

**Issue by coldcode001** [Tencent/MMKV#596]
MMKV implements SharedPreferences.Editor, so it must comply with the API contracts.
putStringSet(String key, @Nullable Set<String> values) calls encode(String key, Set<String> value), but if values is null then it will throw NPE as encode() doesn't accept null.

btw I suggest you adding @NonNull/@Nullable to the MMKV specific APIs (encode*, decode*) as well.

**Comment by lingol** [comment]
Noted.

**Comment by lingol** [comment]
Released with [v1.2.7](https://github.com/Tencent/MMKV/releases/tag/v1.2.7).
