### ISSUE TITLE
Call ::msync with incorrect flags

### ISSUE THREAD

**Issue by coldcode001** [Tencent/MMKV#597]
bool MemoryFile::msync(SyncFlag syncFlag) {
        auto ret = ::msync(m_ptr, m_size, syncFlag ? MMKV_SYNC : MMKV_ASYNC);
}

Here you call global msync with MMKV_SYNC/MMKV_ASYNC, but it's bool value so it casts to 1 or 0.
But for the API we need to pass in MS_SYNC(value is 4) or MS_ASYNC(value is 1). Please double confirm if it's a bug caused by typo.
See https://man7.org/linux/man-pages/man2/msync.2.html

**Comment by lingol** [comment]
OMG, it's a typo. I'm so embarrassed. Will fix it soon.

**Comment by coldcode001** [comment]
btw I assume this issue doesn't affect the performance benchmark testing data posted on WIKI? could you please confirm?

**Comment by lingol** [comment]
Nan, that doesn't matter.

**Comment by lingol** [comment]
Released with [v1.2.7](https://github.com/Tencent/MMKV/releases/tag/v1.2.7).
