### ISSUE TITLE
Add guidance to add backup element for auto backup on Android

### ISSUE THREAD

**Issue by coldcode001** [Tencent/MMKV#598]
[Request for document update]
I saw there's one issue about the backup/restore in https://github.com/Tencent/MMKV/issues/144, thanks for this ticket that I know we need to backup the crc file as well otherwise it craps.
For Android auto backup feature we need to add element in the config xml then the file can be counted for backup/restore. If I want to just backup one of the MMKV file (and its crc file) then we need to add elements for the selected files, could you please add an item in the FAQ section to tell users HOW-TO? And especially you may need to mention about the case for defaultMMKV().
See https://developer.android.com/guide/topics/data/autobackup

**Comment by lingol** [comment]
Noted.

**Comment by lingol** [comment]
Added to [FAQ](https://github.com/Tencent/MMKV/wiki/FAQ).
