### ISSUE TITLE
Add API for MMKV.initialize with Context and LibLoader

### ISSUE THREAD

**Issue by coldcode001** [Tencent/MMKV#599]
[New API request]
Actually we have no interest in specifying a root dir on initializing the lib, so it would be much simple to use Context to initialize the lib, but there's no API to support the custom LibLoader, could you please add new methods as below?
public static String initialize(Context, LibLoader loader)
public static String initialize(Context, LibLoader loader, MMKVLogLevel logLevel)

**Comment by lingol** [comment]
That's a reasonable request.

**Comment by lingol** [comment]
Released with [v1.2.7](https://github.com/Tencent/MMKV/releases/tag/v1.2.7).
