### ISSUE TITLE
MMKV.mmkvWithID crash

### ISSUE THREAD

**Issue by rednels** [Tencent/MMKV#60]
```kotlin
MMKV.mmkvWithID("test/hello2").encode("hello", "world")
```

id中使用`/`会导致崩溃

**Comment by lingol** [comment]
Well, MMKV uses id as filename. For the time being, just don't do this.

**Comment by rednels** [comment]
Why not Hash Code or MD5

**Comment by lingol** [comment]
> Why not Hash Code or MD5

It's already shipped. Now is too late for that. That's why.

**Comment by ysbing** [comment]
> > Why not Hash Code or MD5
> 
> It's already shipped. Now is too late for that. That's why.

Is it possible to encode only special characters?

**Comment by lingol** [comment]
> Is it possible to encode only special characters?

Or just throw exception on bad id?

**Comment by zhongwuzw** [comment]
Is this related to `Android`? I don't familiar with it,  butI think we can find the issue character and just encode it, the way like `encodeURI ` which transform certain characters using escape sequences.

**Comment by lingol** [comment]
> Is this related to `Android`? I don't familiar with it, butI think we can find the issue character and just encode it, the way like `encodeURI` which transform certain characters using escape sequences.

No. It has nothing todo with Android. All those `ecodeXXX` has the same problem I described before: they don't support backward compatibility.

**Comment by ysbing** [comment]
Other char?
![qwe](https://user-images.githubusercontent.com/12974456/46857498-addaf380-ce3b-11e8-85bf-d443c3326c87.png)

**Comment by lingol** [comment]
> Other char?
> ![qwe](https://user-images.githubusercontent.com/12974456/46857498-addaf380-ce3b-11e8-85bf-d443c3326c87.png)

Hmm...

**Comment by zhongwuzw** [comment]
@lingol 
> No. It has nothing to do with Android. All those ecodeXXX has the same problem I described before: they don't support backward compatibility.

No backward compatible? I think it does, previous it would crash, after encode specific char, it works.

**Comment by lingol** [comment]
> No backward compatible? I think it compatible, previously it would crash, after encode specific char, it works.

>Encoding special char is always complicated. Say you replaces / with _, now how do you handle normal _? With __? Now don't forget there may already be some id that has an _, how do you handle old id?

Had I not been clear? Those encodeXXX algorithms, no matter which char(s) they choose to escape, are choosing valid chars to escape with. And how do they handle these valid chars themself? They do **double escape**. That's where the **No backward compatible** happens.

**Comment by lingol** [comment]
@zhongwuzw 

Say we replace `/` with `_`.

Given `test/hello2`, we get `test_hello2`, right? Everything goes well. Except if there is some one already create a MMKV instance with `test_hello2`.

Now tell me, how do you handle this collision?

**Comment by zhongwuzw** [comment]
@lingol Emm, maybe you don't get what I point 😂 . I'll explain further, as your example, if given `test/hello2`, we find it contains special character `/`, so we encode it to `test_hello2`, and besides this, we add a separate subdirectory to store the file, so file would be stored in `mmkv/special-character/` directory (PS. for `id` which not contains special character, we still store the files in `mmkv/` directory). So no collision would be happen.

**Comment by ajinwu** [comment]
what?  are you sure


Sent from Meizu M5 Note

-------- Original message --------
Sender: ysbing <notifications@github.com>
Time: Fri 10/12 16:27
To: Tencent/MMKV <MMKV@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
 Subject: Re: [Tencent/MMKV] MMKV.mmkvWithID crash (#60)

**Comment by lingol** [comment]
@zhongwuzw That might just work. Would you like to write a pr?

**Comment by zhongwuzw** [comment]
@lingol Yeah, I can, but firstly, I need to confirm something because I'm not familiar `Android`, the reason which causes crash is the file cannot created? because intermediate directories not exist if `id` contains `/`? If it is, I think we only need to modify implementation [mappedKVPathWithID and crcPathWithID](https://github.com/Tencent/MMKV/blob/786a83c7de641928f234490b3c1b0e587220f644/Android/MMKV/mmkv/src/main/cpp/MMKV.cpp#L1207-L1214), and judge wether contains `/`, if existed, encode it and create a separate sub-directory, am I right?

**Comment by lingol** [comment]
> Other char?
> ![qwe](https://user-images.githubusercontent.com/12974456/46857498-addaf380-ce3b-11e8-85bf-d443c3326c87.png)

@zhongwuzw Not just `/`.

**Comment by lingol** [comment]
Release with v1.0.13.
