### ISSUE TITLE
auto crypt = [NSString stringWithUTF8String:cryptKey]; iOS模拟器运行崩溃在此处

### ISSUE THREAD

**Issue by Bingbing0311** [Tencent/MMKV#600]
flutter集成之后，在iOS模拟器运行初始化崩溃

**Comment by lingol** [comment]
Full call stacks, please.

**Comment by lingol** [comment]
Hello?

**Comment by Bingbing0311** [comment]
flutter 在 main里初始化

    final rootDir = await MMKV.initialize(logLevel: MMKVLogLevel.None);
    debugPrint('MMKV for flutter with rootDir = $rootDir');
   _mmkv = MMKV.defaultMMKV();

运行在iOS模拟器，奔溃在下面iOS原生代码处
auto crypt = [NSString stringWithUTF8String:cryptKey];

**Comment by lingol** [comment]
**Full call stacks**, please.

**Comment by Bingbing0311** [comment]
MMKV_EXPORT int64_t getDefaultMMKV(int32_t mode, const char *cryptKey) {
    MMKV *kv = nil;

    if (cryptKey) {
        auto crypt = [NSString stringWithUTF8String:cryptKey];**/*io.flutter.1.ui (9): EXC_BAD_ACCESS (code=1, address=0x5900)*/**
        auto cryptKeyData = [crypt dataUsingEncoding:NSUTF8StringEncoding];
        if (cryptKeyData.length > 0) {
            kv = [MMKV defaultMMKVWithCryptKey:cryptKeyData];
        }
    }
    if (!kv) {
        kv = [MMKV defaultMMKV];
    }

    return (int64_t) kv;
}

**Comment by lingol** [comment]
OK, I see.

**Comment by lingol** [comment]
It's fixed in the dev branch. For the time being, you can avoid calling `MMKV.default()` in the simulator.

**Comment by lingol** [comment]
Released with MMKV for flutter v1.2.8. https://pub.dev/packages/mmkv/
