### ISSUE TITLE
Save to mmap only if data really changed

### ISSUE THREAD

**Issue by coldcode001** [Tencent/MMKV#601]
Not sure if you ever tried to check if the value of a specified key is really changed before writing to the underling mmap data? It only need to hold the reader lock this way and if it's same as before then we can just return from set* methods. I guess it would be cheap to do this from small data (boolean, Number and short strings).
But considering that the page size is 4KB so I don't know if it's more efficient or not, maybe depending on how the MMKV is used in app.

**Comment by lingol** [comment]
Writing to mmap data is just as simple & efficient as writing a memory. I don't see much to gain from checking value changed or not.

**Comment by coldcode001** [comment]
I just thought that it may reduce the chance to reach a page size limit for writing unchanged prefs.
But since you are sure that it can't help then it's OK.
