### ISSUE TITLE
clearAll() 引起崩溃

### ISSUE THREAD

**Issue by memoryoff** [Tencent/MMKV#603]
线上环境pc版，Android版本都会调用clearAll()都有概率崩溃，mmkv版本 1.2.4
![Lark20201223-154941](https://user-images.githubusercontent.com/6302224/102985986-098c8580-454b-11eb-9103-80ebd6447237.png)
![Lark20201223-155025_精灵看图](https://user-images.githubusercontent.com/6302224/102986363-a8b17d00-454b-11eb-8776-3a4ae963abeb.png)

**Comment by lingol** [comment]
Full call stacks & MMKV's logs, please. 
PS, the call stacks in your snapshot is not accurate & not including source file **line number**.

**Comment by lingol** [comment]
One more thing, you should always use the latest version.

**Comment by memoryoff** [comment]
线上版本，没有开启MMKV's logs，但从堆栈崩溃看是在
![微信图片_20201223181836](https://user-images.githubusercontent.com/6302224/102986599-11005e80-454c-11eb-897e-d332f0910b49.png)

**Comment by lingol** [comment]
First thing first, you should **never turn MMKV's log off** unless you have very strong evidence that it makes your App slow.

Next, when it crashed on `memcpy()`, it means the mmap() call has failed to allocate memory as it has promise. And that probably means the device is **running out of disk space**.

**Comment by lingol** [comment]
>First thing first, you should never turn MMKV's log off unless you have very strong evidence that it makes your App slow.


In fact, I should make it clear on wiki.

**Comment by lingol** [comment]
Hey, did you turn on MMKV's log and correct more info about disk pace?

**Comment by PApatigers** [comment]
clearAll同样存在上述问题，日志反馈由于未获取到访问内部文件权限，猜测m_file mk_dir()失败，m_file读写文件失败

**Comment by lingol** [comment]
Again, can't diagnose without logs.

> clearAll同样存在上述问题，日志反馈由于未获取到访问内部文件权限，猜测m_file mk_dir()失败，m_file读写文件失败

**Comment by PApatigers** [comment]
> Again, can't diagnose without logs.
> 
> > clearAll同样存在上述问题，日志反馈由于未获取到访问内部文件权限，猜测m_file mk_dir()失败，m_file读写文件失败

oldStyleWriteActualSize 方法在memcpy前针对ios进行了内存校验，针对android却没有

**Comment by lingol** [comment]
> > Again, can't diagnose without logs.
> > > clearAll同样存在上述问题，日志反馈由于未获取到访问内部文件权限，猜测m_file mk_dir()失败，m_file读写文件失败
> 
> oldStyleWriteActualSize 方法在memcpy前针对ios进行了内存校验，针对android却没有

It's because iOS has a bug for accessing mmap address when App is running in background mode. No such bug on Android, as  far as I know.

**Comment by lingol** [comment]
Or on any other platforms.

**Comment by PApatigers** [comment]
> > > Again, can't diagnose without logs.
> > > > clearAll同样存在上述问题，日志反馈由于未获取到访问内部文件权限，猜测m_file mk_dir()失败，m_file读写文件失败
> > 
> > 
> > oldStyleWriteActualSize 方法在memcpy前针对ios进行了内存校验，针对android却没有
> 
> It's because iOS has a bug for accessing mmap address when App is running in background mode. No such bug on Android, as far as I know.

![image](https://user-images.githubusercontent.com/34330947/103892731-04246300-5127-11eb-9762-8d428698367e.png)
这里是不是有时序问题，在oldStyleWriteActualSize方法内没有对m_file的有效性校验

**Comment by lingol** [comment]
Close due to inactive.
