### ISSUE TITLE
flutter插件在iOS无法导入

### ISSUE THREAD

**Issue by ShikinChen** [Tencent/MMKV#605]
### The language of MMKV

> e.g. Objective-C

### The version of MMKV

> e.g. v1.2.7  

### The platform of MMKV

> e.g. iOS 

### The installation of MMKV

> e.g. Cocoapods, Flutter

使用flutter的mmkv插件iOS无法用Cocoapods导入mmkv 提示 [!] No podspec found for `mmkv` in `.symlinks/plugins/mmkv/ios

**Comment by lingol** [comment]
#584

**Comment by lingol** [comment]
Oh, and one more thing, you should upgrade to MMKV for flutter v1.2.8 now. Just released today.
