### ISSUE TITLE
More than one file was found with OS independent path 'lib/x86/libc++_shared.so'

### ISSUE THREAD

**Issue by rice1994** [Tencent/MMKV#607]
### The language of MMKV

Java

### The version of MMKV

> e.g. v1.2.1

### The platform of MMKV

 Android

### The installation of MMKV

Maven

### What's the issue?

More than one file was found with OS independent path 'lib/x86/libc++_shared.so'

### What's the log of MMKV when that happened?

More than one file was found with OS independent path 'lib/x86/libc++_shared.so'

**Comment by lingol** [comment]
Use com.tencent:mmkv-static.
