### ISSUE TITLE
Should return false in case mmkv file doesn't exist

### ISSUE THREAD

**Issue by coldcode001** [Tencent/MMKV#608]
```
bool MMKV::isFileValid(const string &mmapID, MMKVPath_t *relatePath) {
    MMKVPath_t kvPath = mappedKVPathWithID(mmapID, MMKV_SINGLE_PROCESS, relatePath);
    if (!isFileExist(kvPath)) {
        return true;
    }
    // blabla
}
```
IsFileValid() === mmkv file exists && crc file exists && data consistency, so it should return false here, please confirm.

**Comment by lingol** [comment]
That logic does look like faulted, yet it is by design. And the reason is irrelevant to users outside of the WeChat App. 
Anyway, it can't do any harm to announce a non-exist MMKV as valid.

**Comment by coldcode001** [comment]
OK. But MMKV has a public API isFileValid() calls this, not sure if it's used by mistake to check if the MMKV ever created (used).
Comments or API doc may be needed if it's designed like that.

**Comment by lingol** [comment]
Sure.
