### ISSUE TITLE
synchronize is deprecated and will be marked with the NS_DEPRECATED macro in a future release.(from Apple)

### ISSUE THREAD

**Issue by xueminlee** [Tencent/MMKV#61]
This is a great frameworks to solve the key-value read/write problems, and has great performance comparing to NSUserDefaults and SQLite。It use the mmap, protobuf and some elegant strategies。 

My question is your idea is base on the NSUserDefaults's poor performance is due to synchronize call, but from apple, synchronize will be deprecated and should be remove the synchronize call. (synchronize is deprecated and will be marked with the NS_DEPRECATED macro in a future release.)

**Comment by lingol** [comment]
And what do they mean by deprecate this method? Does that mean NSUserDefaults will never lose data on App crashing? No? Well, here comes MMKV.

It's not about NSUserDefaults being slow, it's about keeping efficiency while not losing data.

**Comment by xueminlee** [comment]
Please refer:https://developer.apple.com/library/archive/releasenotes/Foundation/RN-FoundationOlderNotes/index.html#X10_10Notes

**Comment by lingol** [comment]
Apple declared in iOS 10 release note that
> Synchronized to avoid losing data if your app crashed
is not needed anymore. Which I highly doubt that.

Well, let's trust that statement. Try this: comment the `synchronize ` in the baseline code and run again. You can find out that NSUserDefaults is not any faster. What does that tell you?

**Comment by xueminlee** [comment]
Thanks. I try to comment *synchronize* and also 10 time the test case to see the result, the result is very interesting. 

I also wonder if need other test case, like read, write, read, write, ...., to simulator the real world access.
