### ISSUE TITLE
 mmkv1.2.8 flutter mac initialize throw exception

### ISSUE THREAD

**Issue by LuckyJayce** [Tencent/MMKV#612]
### The language of MMKV

> dart

### The version of MMKV

> 1.2.8

### The platform of MMKV

>flutter mac

### The installation of MMKV

> pubspec.yaml Cocoapods

### What's the issue?

await MMKV.initialize(); throw exception

### What's the log of MMKV when that happened?
error

[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, mmkvInitialize): symbol not found)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
#1      _mmkvInitialize (package:mmkv/mmkv.dart:638:14)
#2      _mmkvInitialize (package:mmkv/mmkv.dart)
#3      MMKV.initialize (package:mmkv/mmkv.dart:165:7)
<asynchronous suspension>
#4      main (package:flutter_app/main.dart:25:3)
<asynchronous suspension>

**Comment by lingol** [comment]
I don't think we support flutter on mac. It's for iOS & Android.

**Comment by LuckyJayce** [comment]
原来flutter版本目前还没支持macOS，没注意看pub上简介，flutter版本后面是否考虑支持macOS和Windows

**Comment by lingol** [comment]
Not in our plan. As far as it matters, flutter is mainly targeting mobile dev.
For the macOS & POSIX platforms, we have better options than flutter: Golang and Python. Both are officially supported by MMKV.
