### ISSUE TITLE
Initialize issue in some devices

### ISSUE THREAD

**Issue by necatisozer** [Tencent/MMKV#614]
### The language of MMKV

> Kotlin

### The version of MMKV

> v1.2.4

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

I'm getting some crash reports in some devices.

- Desire 816 (Android 6.0)
- JNY-LX1 (Android 10)
- One (M8) (Android 6)
- Galaxy J7 Prime (Android 8.1)

We're using App Bundles & initializing MMKV via [App Startup](https://developer.android.com/topic/libraries/app-startup).

### What's the log of MMKV when that happened?

> Caused by java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/appcent.mobi.waterboyandroid-2/split_config.armeabi_v7a.apk" segment 1: Permission denied
>        at java.lang.Runtime.loadLibrary(Runtime.java:372)
>        at java.lang.System.loadLibrary(System.java:1076)
>        at com.tencent.mmkv.MMKV.initialize(MMKV.java:99)
>        at com.tencent.mmkv.MMKV.initialize(MMKV.java:70)
>        at tr.com.bisu.app.core.database.keyvaluestorage.MmkvInitializer.create(MmkvInitializer.java:9)
>        at tr.com.bisu.app.core.database.keyvaluestorage.MmkvInitializer.create(MmkvInitializer.java:7)
>        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
>        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
>        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42)
>        at android.content.ContentProvider.attachInfo(ContentProvider.java:1759)
>        at android.content.ContentProvider.attachInfo(ContentProvider.java:1728)
>        at android.app.ActivityThread.installProvider(ActivityThread.java:5534)
>        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5105)
>        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5045)
>        at android.app.ActivityThread.access$1600(ActivityThread.java:150)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1459)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:168)
>        at android.app.ActivityThread.main(ActivityThread.java:5845)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by lingol** [comment]
>Caused by java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/mnt/asec/appcent.mobi.waterboyandroid-2/split_config.armeabi_v7a.apk" segment 1: Permission denied

Nothing we can do about it.

**Comment by necatisozer** [comment]
Probably correlated with this issue.
https://issuetracker.google.com/issues/127691101
