### ISSUE TITLE
flutter plugin支持的flutter sdk版本可否降低一些，在用的工程里面flutter-boost现在只支持到了1.17.1版本，希望可以一起使用

### ISSUE THREAD

**Issue by kingrukawa** [Tencent/MMKV#615]
flutter plugin支持的flutter sdk版本可否降低一些，在用的工程里面flutter-boost现在只支持到了1.17.1版本，希望可以一起使用

**Comment by lingol** [comment]
It's OK to downgrade to v1.17, I think. But I don't have the luxury of time to test it.
You can make a local module of mmkv for the moment, modify its `pubspec.yaml` file, check if everything really works.

**Comment by kingrukawa** [comment]
这本身就是个method channel调用，没问题的，只不过插件版本太高了，我直接引用就会报错，这个我很难受，想官方可以支持掉，方便大家使用

**Comment by lingol** [comment]
No. MMKV for flutter doesn't use method channel for the most part of its API. 
For performance consideration, we use `dart:ffi`.

**Comment by lingol** [comment]
The thing you should do, in my humble opinion, is asking the flutter-boost team to support the latest flutter SDK.
