### ISSUE TITLE
iOS中MMKV文件修改时间什么时候会改变？

### ISSUE THREAD

**Issue by kingsword** [Tencent/MMKV#616]
当我创建一个MMKV实例后，首先操作[setObject:@"123" forKey:@"string1"]，确保在沙盒中生成了MMKV对应的文件。
假设操作完毕的时间为12:05，此时MMKV文件的修改时间是12:05。
过10分钟再进行[setObject:@"345" forKey:@"string2"]后，但MMKV文件的修改时间没有变化，还是12：05？
所以想问一下MMKV文件的修改时间什么时候会改变？具体原因是什么？

**Comment by lingol** [comment]
The file is mapped. We don't modify the file directly. So the modified time of the file is updated by the OS. 

Don't rely on that.

**Comment by kingsword** [comment]
thk u
