### ISSUE TITLE
The mmkv.default file has so many repeat keys

### ISSUE THREAD

**Issue by Pslilysm** [Tencent/MMKV#617]
### The language of MMKV

> java

### The version of MMKV

>  v1.2.7

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?
why the mmkv.default file have so many repeat keys?
> Post the outputs or screenshots for errors.
> 
![image](https://user-images.githubusercontent.com/41366450/104276935-d6ea0300-54e0-11eb-8b9f-7fc54ed22730.png)
I'm using MMKV.encode method to store the keys.

> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your detail logs. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.

**Comment by lingol** [comment]
Don't you worry about that. MMKV uses an append-only algorithm to store any updates to any keys. It's natural to have duplicated keys inside. And MMKV will use the latest one.
