### ISSUE TITLE
希望合理使用nullable注解

### ISSUE THREAD

**Issue by Reginer** [Tencent/MMKV#624]
### The language of MMKV
Kotlin

### The version of MMKV
1.2.7

### The platform of MMKV
Android

希望可以保证基本的必要初始化成功率，比如 `defaultMMKV()`返回值非空，而不是像现在一样是个返回值就是可空。

I hope mmkv can guarantee the basic success rate of necessary initialization. For example, the return value of 'defaultmmkv()' is not null, instead of all nullable as it is now.

**Comment by lingol** [comment]
If the file fails to `open()`, or the `mmap()` memory fails to allocate, there's no point to provide a non-null instance for you. The data you put in will be lost anyway.

That's the law of leaky abstractions. https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/
When the underlying system fails, you can't pretend it didn't.

**Comment by Reginer** [comment]
如果mmkv在初始化的时候真的发生了错误，那是mmkv需要解决的bug，而不是什么都不处理像现在一样返回一个null。
要真的返回null的话，要如何处理，是不是要再创建一个SharePreference？那么是不是SharePreference这种备用方案正式上位，而mmkv变成了备胎？

If there is a real error in mmkv initialization, it is a bug that mmkv needs to solve instead of returning a null as it does now.

If mmkv return null, what should I do?  Create a sharepreference?  So, is sharepreference is better, and mmkv a spare tire?

**Comment by lingol** [comment]
It's no a bug when shit happens inside the operating system.
Now you tell me, how to make sure the system call `open()` won't fail? Or how to make sure the `mmap()` system call won't fail?

**Comment by Reginer** [comment]
我无法告诉你在`defaultMMKV()`返回空的时候mmkv该如何处理，是我的技术不到位，希望可以留下这个issue直到它被解决。如果不做处理的话，mmkv可能失去了它的价值，因为它连第一步都没有完成。

I can't tell you how to deal with mmkv when 'defaultmmkv()' returns to null. My level is not up to standard. I hope you can open this issue until it is solved .  If mmkv don't deal with it, mmkv may lose its value because it hasn't  completeed in the first step.

**Comment by lingol** [comment]
I'm sorry but you are just being unreasonable. Good luck with finding any never-fail storage frameworks.

**Comment by Reginer** [comment]
在存储的过程中成功或者失败这是可以被理解的，mmkv独创了初始化可空的操作。
defaultMmkv报空使我不得不用替代mmkv的存储方式，因为当时属于mmkv1.2.7的表演已经结束了，app的存储工作却不得不重新开始。

**Comment by lingol** [comment]
If all you ask is an operational instance and doesn't care about the failure of disk-io, like you probably had, calling SharedPreferences' `void apply()` which returns `void`, you should stick to SharedPreferences.

Wo choose not to give users a delusional abstraction. If you are not happy with that, so be it.

**Comment by Reginer** [comment]
明确的是，现在这样直接返回null不是最佳的处理方案吧。

而我显然显然不是希望返回一个实例完事了，需要的是让mmkv可以继续运行下去。

实例的成功创建是必要的，它是第一步呀，就算现在你还做不到，以后可能会做到，更多看到问题的人也可能会提出方案如何确保完成这第一步。

**Comment by lingol** [comment]
Okay, to suit the Java/Kotlin convention, I make MMKV construction methods **non-nullable**. 
It will throw exceptions instead, which maybe is the preferred way for Java devs.

**Comment by Reginer** [comment]
非常高兴做出了这个更新
