### ISSUE TITLE
存储可靠性如果无法被保证

### ISSUE THREAD

**Issue by DaveBoy** [Tencent/MMKV#626]
我存一个变量A到本地，
第一次我存MMKV成功了。
第二次你MMKV初始化失败了，让我自己处理。。。我用SP存。

然后第三次我就得想想了，我到底取哪里的数据呢？

**Comment by DaveBoy** [comment]
我们都知道如果出现极低的情况，无法存储是必然的。
那么问题来了，当出现这种情况之后返回空告诉给开发者有啥用？（如果开发者用其他方案存储不就出现了我最开始提出的”不知道取哪的数据“现象了吗）

**Comment by lingol** [comment]
And what's your question? Sorry, but I don't see any.

**Comment by DaveBoy** [comment]
> And what's your question? Sorry, but I don't see any.

我的问题是新版获取实例可空的意义在哪

**Comment by lingol** [comment]
It's always nullable, not just in the latest version. We just make it clear by adding the @Nullable annotation.

**Comment by lingol** [comment]
Just as what you have been dealing with any `encode()` that returns false, aka either ignore it, loop over it, or retry later.

Or, in most cases, you should **check the disk usage** to see if there's enough space for any storage. And if there's little space, you should alert the user to clean up some space for further use of your App.

**Comment by lingol** [comment]
In fact, if you rarely see any **Null Pointer Exception** of MMKV on your App crash reports, you can just **simply crash your App** on a null instance of MMKV. 

That is way simpler.

**Comment by lingol** [comment]
#624
