### ISSUE TITLE
Default value was not returned when decode type and encode type mismatch

### ISSUE THREAD

**Issue by kexanie** [Tencent/MMKV#63]
If we write some data of type `A` and read it as type `B` with the same key, unexpected value will be returned. For example:
```java
MMKV kv = MMKV.mmkvWithID(mmapID, MMKV.SINGLE_PROCESS_MODE, cryptKey);
kv.encode("bool", true);
int val = kv.decodeInt("bool", 100);
System.out.println("decode int with key bool: " + val);
```
The terminal will print `decode int with key bool:  1`. That is kind of misleading since we never store any `int` value with key `"bool"`, meanwhile there was no error or exception thrown when we are doing this implicit casting.

Is this an intentional design?

**Comment by lingol** [comment]
Yes. MMKV does type erasure while storing values. That means type mismatch detection is impossible.
