### ISSUE TITLE
 Use of '@import' when modules are disabled ,  Use of undeclared identifier 'MMKVPlugin'

### ISSUE THREAD

**Issue by maitianyihu** [Tencent/MMKV#633]
### The version of MMKV

> e.g. v1.2.7
### The version of Flutter

> e.g. v1.22.6

### The platform of MMKV

> e.g. flutter iOS 端

### What's the issue?

> flutter项目中yaml引入mmkv ^1.2.8，cocoapod install版本为1.2.7，拉取后运行项目报错:
> Use of '@import' when modules are disabled ,  Use of undeclared identifier 'MMKVPlugin'

### What's the log of MMKV when that happened?
> @import' when modules are disabled
> Use of undeclared identifier 'MMKVPlugin'

**Comment by lingol** [comment]
Duplicated with #628.
