### ISSUE TITLE
Licensing issue - distributing under MIT

### ISSUE THREAD

**Issue by mrousavy** [Tencent/MMKV#635]
I've developed a library called "react-native-mmkv", which wraps the MMKV library.

So the user, in a React Native application, uses my library, which itself uses this MMKV library under the hood.

Can I license my library with MIT? Should I mention the license of this library somewhere in my license?

**Comment by lingol** [comment]
MMKV's source code & binary are **licensed under the BSD 3-Clause License**. Basically, you should just mention that MMKV is licensed under the BSD 3-Clause License, and provide a full BSD 3-Clause License in your license file.

You can check out the `LICENSE.TXT` from MMKV repo for example.
