### ISSUE TITLE
iOS: Building from source, header import not found (CocoaPods)

### ISSUE THREAD

**Issue by mrousavy** [Tencent/MMKV#638]
### The language of MMKV

Objective-C

### The version of MMKV

(master)

### The platform of MMKV

iOS

### The installation of MMKV

Git clone (subspec)

### What's the issue?

I'm trying to include the MMKV library (`MMKV/iOS` and `MMKV/Core`) from source in my library. The library will be distributed using a podspec.

The problem is that the `MMKV/iOS/MMKV/MMKV/libMMKV.mm` file includes MMKVCore headers using `<` syntax:

```objc
#import <MMKVCore/MMKV.h>
#import <MMKVCore/MMKVLog.h>
#import <MMKVCore/ScopedLock.hpp>
#import <MMKVCore/ThreadLock.h>
#import <MMKVCore/openssl_md5.h>
```

> see [here](https://github.com/Tencent/MMKV/blob/master/iOS/MMKV/MMKV/libMMKV.mm#L22-L26)

Because of this, I cannot build the library since the "system headers" MMKVCore/* do not exist. The correct input path would be some relative path like `"../../../Core/MMKV.h"`, but that _also_ won't work since CocoaPods flattens out header files in a single one layer file hierarchy.

This means, `MMKV.h` from MMKVCore and `MMKV.h` from MMKV-iOS will be in the same path, and will cause a nameclash.

I've been trying to understand how CocoaPods manages those issues, but I couldn't find a good solution for this. Sorry if this doesn't really belong here and is more of a CocoaPods issue, but since you have a "build from source" section in the docs I figured that you'd know how to disambiguate between MMKVCore and iOS and correctly import & link the headers with the pod.

This is my current `podspec`:

```ruby
Pod::Spec.new do |s|
  s.name         = "react-native-mmkv"
  # collapsed version, summary, platform, etc

  # All source files that should be publicly visible
  # Note how this does not include headers, since those can nameclash.
  s.source_files = [
    "ios/**/*.{m,mm}",
    "ios/RNMMKV.h",
  ]
  # Any private headers that are not globally unique should be mentioned here.
  # Otherwise there will be a nameclash, since CocoaPods flattens out any header directories
  # See https://github.com/firebase/firebase-ios-sdk/issues/4035 for more details.
  s.preserve_paths = [
    'ios/**/*.h',
    'MMKV/**/*.h'
  ]

  s.requires_arc = [
    'ios/**/*.mm'
  ]

  s.compiler_flags = '-x objective-c++'
  s.framework    = "CoreFoundation"
  s.ios.frameworks = "UIKit"
  s.libraries    = "z", "c++"
  s.pod_target_xcconfig = {
    "CLANG_CXX_LANGUAGE_STANDARD" => "gnu++17",
    "CLANG_CXX_LIBRARY" => "libc++",
    "CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF" => "NO",
    'ALWAYS_SEARCH_USER_PATHS' => 'NO'
  }

  # MMKVCore
  s.subspec 'MMKVCore' do |spec|
    spec.name = 'MMKVCore'
    spec.source_files = [
      "MMKV/Core/**/*.{cpp}",
    ]
    spec.public_header_files = [
      "MMKV/Core/**/*.{h,hpp}"
    ]
    spec.header_mappings_dir = "MMKV/Core/**"

    spec.requires_arc = [
      'MMKV/Core/MemoryFile.cpp',
      'MMKV/Core/ThreadLock.cpp',
      'MMKV/Core/InterProcessLock.cpp',
      'MMKV/Core/MMKVLog.cpp',
      'MMKV/Core/PBUtility.cpp',
      'MMKV/Core/MemoryFile_OSX.cpp',
      'MMKV/aes/openssl/openssl_cfb128.cpp',
      'MMKV/aes/openssl/openssl_aes_core.cpp',
      'MMKV/aes/openssl/openssl_md5_one.cpp',
      'MMKV/aes/openssl/openssl_md5_dgst.cpp',
      'MMKV/aes/AESCrypt.cpp',
    ]
  end

  # MMKV-iOS
  s.subspec 'MMKVIOS' do |spec|
    spec.name = 'MMKVIOS'
    spec.source_files = [
      "MMKV/iOS/MMKV/**/*.{m,mm}"
    ]
    spec.public_header_files = [
      "MMKV/iOS/MMKV/**/*.{h,hpp}"
    ]
    spec.header_mappings_dir = "MMKV/iOS/MMKV/**"
  end

  s.dependency "React-Core"
end
```

**Comment by lingol** [comment]
That `Compile by Source` wiki is out of date. You should use CocoaPods instead.

**Comment by mrousavy** [comment]
@lingol Thanks - I'm trying to share the MMKV abstraction between iOS and Android to only have a single C++ codebase, and finally managed to get a working podspec (see [here](https://github.com/mrousavy/react-native-mmkv/blob/style/use-single-cpp-codebase/react-native-mmkv.podspec)). The problem is, that I cannot figure out how to avoid using NeXt step types (`NSString`) and also simply use `std::string` on iOS - I see the preprocessor directives that set the `MMKVKey_t` here: https://github.com/Tencent/MMKV/blob/200b4decfb479bddbd549aa90201fbdd229b048f/Core/MMKV.h#L89-L95

is this a design decision? Is it not possible to use `std::string` keys on iOS/Apple platforms? I'm assuming it's a bad idea to unset the `MMKV_APPLE` directive to avoid using NSString...

**Comment by mrousavy** [comment]
(the reason I'm trying to use MMKVCore instead of the MMKV iOS abstraction (aka the `std::string` types instead of `NSString`) is because I am already working with C++ types (`std::string`) and wanted to avoid the conversion from `std::string` -> `NSString`, then `NSString` -> `std::string`.)

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/blob/master/Core/MMKVPredef.h#L28

**Comment by lingol** [comment]
PS, the pod setting you are looking for is 
```ruby
    'GCC_PREPROCESSOR_DEFINITIONS' => 'FORCE_POSIX=1'
```

**Comment by lingol** [comment]
But I have to mind you that once you set this macro, you also lost some protection provided by MMKV. It will increase your chance of crashing.

**Comment by mrousavy** [comment]
> instead of more efficient iOS/macOS ones

what do you mean by more efficient iOS/macOS ones? Do those "more efficient iOS/macOS system calls" require the use of NSString or can they also accept std::string/C style strings?

**Comment by lingol** [comment]
It's wholesale. You can't just take std::string without losing some platform-specific optimization.
