### ISSUE TITLE
Xcode12使用carthage, build framework 不成功，错误如下

### ISSUE THREAD

**Issue by weiguangmeng** [Tencent/MMKV#640]
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/weiguangmeng/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/MMKV/v1.2.7/Build/Intermediates.noindex/ArchiveIntermediates/MMKV/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/MMKV.framework/MMKV /Users/weiguangmeng/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/MMKV/v1.2.7/Build/Products/Release-iphonesimulator/MMKV.framework/MMKV -output /Users/weiguangmeng/Documents/BuildStaticLibrary/BuildStaticLibrary/Carthage/Build/iOS/Static/MMKV.framework/MMKV

**Comment by lingol** [comment]
That log contains nothing useful. You should provide meaningful logs.
