### ISSUE TITLE
iOS xcode12 模拟器编译失败

### ISSUE THREAD

**Issue by weiguangmeng** [Tencent/MMKV#641]
![193CEFD5-49A4-4C15-B562-17E62949E574](https://user-images.githubusercontent.com/24958332/109459944-c09d0400-7a9a-11eb-8bef-13d8b8452140.png)

**Comment by lingol** [comment]
That screenshot contains nothing useful. You should provide meaningful information.

**Comment by lingol** [comment]
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios
