### ISSUE TITLE
Windows: "A reference to 'core' could not be added because it is incompatible with this project"

### ISSUE THREAD

**Issue by mrousavy** [Tencent/MMKV#642]
### The language of MMKV

C++ (Win32)

### The version of MMKV

current master

### The platform of MMKV

Windows

### The installation of MMKV

Git clone (submodule)

### What's the issue?

I have added the `MMKV/Core/core.vcxproj` to my solution and then tried to add it to my Project's references (via **MyProject** > **References** > **Add Reference** > **Projects** > **core**), but that gives me the following error:

![image](https://user-images.githubusercontent.com/15199031/109564815-dc77c880-7ae1-11eb-8802-12d0a60a7862.png)

Looks like the MMKV core project has been created with Visual Studio 2015, and I'm on Visual Studio 2019 - I'd assume that is the current issue here.

**Comment by lingol** [comment]
Visual Studio doesn't support old versions very well. You have to modify/upgrade it yourself.

**Comment by mrousavy** [comment]
Would you be accepting PRs to upgrade the VS2015 project to a newer version (like at least VS2017)?

**Comment by lingol** [comment]
No, thanks. I do have VS 2017 & 2019 installed locally. The reason I keep it VS 2015 is that some users still use VS 2015.
