### ISSUE TITLE
migration to null safety?

### ISSUE THREAD

**Issue by matejthetree** [Tencent/MMKV#645]
Is there any plan to migrate mmkv to null safety?

**Comment by lingol** [comment]
This month, hopefully.

**Comment by lingol** [comment]
Wait, what do you mean by saying null safety?

**Comment by matejthetree** [comment]
https://dart.dev/null-safety

**Comment by lingol** [comment]
Migrated on the dev branch. Hopefully will come out this month.

**Comment by lingol** [comment]
Released with [v1.2.8](https://github.com/Tencent/MMKV/releases/tag/v1.2.8).
