### ISSUE TITLE
自己维护了一个mmkv的对象，创建正常，close销毁是源码内部的m_mmapKey值发生了变化

### ISSUE THREAD

**Issue by dander521** [Tencent/MMKV#646]
### The language of MMKV

- (void)close {
    SCOPED_LOCK(g_lock);
    MMKVInfo("closing = %@", m_mmapID);
    [g_instanceDic removeObjectForKey:m_mapKey];
}

### The version of MMKV

最新版本

### The platform of MMKV

iOS

### The installation of MMKV

源码添加 framework

### What's the issue?
#查看代码没有任何赋值修改的地方，而且每次m_mmapKey的值都是随机的，内存地址是没有发生变化的，就是值变了，导致close时候g_instanceDic removeObjectForKey 发生崩溃

![1](https://user-images.githubusercontent.com/15241138/110271443-090c7280-8003-11eb-8735-1753cc848e98.png)
![2](https://user-images.githubusercontent.com/15241138/110271449-0c076300-8003-11eb-8d74-e7ecdbe41fd2.png)
 mmkv 的对象始终是 75da0 但是close的时候m_mapKey的值已经不是g_instanceDic对应的key，排查好久不清楚什么原因

**Comment by lingol** [comment]
It has nothing to do with MMKV. Check your code for potential double release / invalid address access. 
For example, you should not keep an MMKV instance after it's been closed, etc.

**Comment by dander521** [comment]
其他三个值 都是正确的 
    NSString *m_mmapID;
    mmkv::MMKV *m_mmkv;
    uint64_t m_lastAccessTime;
唯独m_mmapKey不对，但是我把私有变量修改成
@interface MMKV ()
@property (nonatomic, copy) NSString *m_mmapKey;
@end
使用起来就正常了

**Comment by lingol** [comment]
> It has nothing to do with MMKV. Check your code for potential double release / invalid address access.
> For example, you should not keep an MMKV instance after it's been closed, etc.

I won't repeat myselft.
