### ISSUE TITLE
truncate 扩容是是否需要进行存储空间检查

### ISSUE THREAD

**Issue by PApatigers** [Tencent/MMKV#647]
### The language of MMKV
java

### The version of MMKV
> e.g. v1.0.21

### The platform of MMKV
>  Android

### What's the issue?
每次append data时进行调用ensureMemorySize（）来判断是否需要truncate扩容，这里是否需要判断存储空间不足的case

**Comment by lingol** [comment]
The last time I checked, we have verified the return code of `ftruncate()`.

**Comment by PApatigers** [comment]
那是否有接口能过获取真实数据的大小，目前抛出的totalSize接口获取的是文件的size

**Comment by lingol** [comment]
No there is no such method.
However, you could loop over all the keys and sum up the size of each value. This will give you something close to the _actual size_.
https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/java/com/tencent/mmkv/MMKV.java#L520

**Comment by PApatigers** [comment]
好的感谢
