### ISSUE TITLE
数据丢失

### ISSUE THREAD

**Issue by idealcn** [Tencent/MMKV#648]
app module，login module依赖base library，login module负责登录，将登陆返回的用户数据通过base library的MMKV实例来保存。杀死app但不调用app的退出登录api，也不清空本地数据。再次打开app，之前保存的用户数据没了。如果是通过返回键退出app，再次打开app，之前保存的登录数据是存在的。这个是什么原因呢，我使用姿势不对？

**Comment by lingol** [comment]
I don't quite understand your problem. 
Maybe you should check the logs of MMKV.

**Comment by idealcn** [comment]
I/MMKV: <native-bridge.cpp:103::JNI_OnLoad> current API level = 29
 I/MMKV: <MMKV.cpp:156::initialize> version v1.2.7 page size:4096
 I/MMKV: <MMKV.cpp:198::initializeMMKV> root dir: /data/user/0/com.hehewang.hhw.android/files/mmkv
 E/MMKV: <MMKV.cpp:382::checkFileCRCValid> check crc [mmkv.default] fail, crc32:740653741, m_crcDigest:1149076597
 I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 4 actual size, file size 4096, InterProcess 0, meta info version:3
 I/MMKV: <MMKV_IO.cpp:86::loadFromFile> loading [mmkv.default] with crc 1285129681 sequence 4 version 3
 I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values
 
 ------------------------------------------------------------------------------------------------------------------------

麻烦大佬帮我看下

**Comment by lingol** [comment]
Your file is corrupted.
>E/MMKV: MMKV.cpp:382::checkFileCRCValid check crc [mmkv.default] fail, crc32:740653741, m_crcDigest:1149076597

Check the [FAQ](https://github.com/Tencent/MMKV/wiki/FAQ_cn) for "为什么 MMKV 在 App 重启后丢失数据？".

**Comment by idealcn** [comment]
非常感谢！
`
 MMKV.initialize(this) //fail
  MMKV.mmkvWithID("",MMKV.MULTI_PROCESS_MODE)//success
`
