### ISSUE TITLE
Parcelable集合支持问题

### ISSUE THREAD

**Issue by wangrunxiang** [Tencent/MMKV#649]
我看官方文档和代码接口，encode这个接口是有Parcelable的重载，为什么没有Parcelable集合的重载？如果要存一个集合，要怎么存储？

**Comment by lingol** [comment]
It will be very complicated to support all those containers, `Array, List, Map, ArrayList, SparseArray`, etc.
You could use `Parcel` to write your container into a data, using [one of those methods](https://developer.android.com/reference/android/os/Parcel#untyped-containers), and store that data into MMKV.

**Comment by wangrunxiang** [comment]
你的意思是让我新建一个类，然后把这个对象集合放到这个类里面，然后序列化这个类？
是这个意思吗？
如果这样的话，是不是还不如加一个List<Parcelable>的重载更香

**Comment by wangrunxiang** [comment]
@lingol

**Comment by lingol** [comment]
No. I mean using Parcel to encode your container to a memory buffer.

**Comment by lingol** [comment]
Example code:
```Java
        Parcel source = Parcel.obtain();
        source. writeTypedList(myList);
        byte[] bytes = source.marshall();
        source.recycle();

        mmkv.encode(key, bytes);
```

**Comment by wangrunxiang** [comment]
Can you give me an example

**Comment by wangrunxiang** [comment]
thanks

**Comment by lingol** [comment]
And here's the decoding example. I haven't tested it yet. But you get the idea.
```Java
        List<MyClass> list;
        byte[] bytes = mmkv.decodeBytes(key);
        if (bytes == null) {
            return list;
        }

        Parcel source = Parcel.obtain();
        source.unmarshall(bytes, 0, bytes.length);
        source.setDataPosition(0);
        source.readTypedList(list, MyClass.CREATOR);
        source.recycle();

        return list;
```

**Comment by wangrunxiang** [comment]
i can get it

**Comment by wangrunxiang** [comment]
建议还是把这几个重载加上把？迪米特法则嘛

**Comment by lingol** [comment]
No, as described above, we won't do it.

**Comment by PeOS-China** [comment]
> And here's the decoding example. I haven't tested it yet. But you get the idea.
> 
> ```java
>         List<MyClass> list;
>         byte[] bytes = mmkv.decodeBytes(key);
>         if (bytes == null) {
>             return list;
>         }
> 
>         Parcel source = Parcel.obtain();
>         source.unmarshall(bytes, 0, bytes.length);
>         source.setDataPosition(0);
>         source.readTypedList(list, MyClass.CREATOR);
>         source.recycle();
> 
>         return list;
> ```

Is this code thread safe? When multithreading reads and runs this code, it will crash!

**Comment by hs16542** [comment]
In Android Parcel`s javadoc:
"The data you retrieve here must not be placed in any kind of persistent storage (on local disk, across a network, etc). For that, you should use standard serialization or another kind of general serialization mechanism. The Parcel marshalled representation is highly optimized for local IPC, and as such does not attempt to maintain compatibility with data created in different versions of the platform."

It seems like marshalled bytes are not recommended to store locally.
