### ISSUE TITLE
to clear key-values from mmkv.default file

### ISSUE THREAD

**Issue by soniarojhwal** [Tencent/MMKV#650]
### The language of MMKV

>  Kotlin

### The version of MMKV

> v1.2.7 

### The platform of MMKV

> Android

### The installation of MMKV

>  Maven, AAR Package or Git clone

### What's the issue?
When trying to remove keys using
mmkv.removeValueForKey("key"), is not clearing up key-values from "mmkv.default" file.
It clear up from mmkv instance, but the values are still present in the file, and when we add the keys again then it appends the values in the file.

 Is there any way, i can clear values from the " mmkv.default" file?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your detail logs. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.

**Comment by lingol** [comment]
Duplicated wtih #636 .
