### ISSUE TITLE
打包IOS报错

### ISSUE THREAD

**Issue by folinwu2296** [Tencent/MMKV#654]
### Flutter  IOS打包时报错
运行命令：pod install

> e.g. Swift,  Kotlin

[!] No podspec found for `mmkv` in `.symlinks/plugins/mmkv/ios`

[!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by folinwu2296** [comment]
fluttermmkv.podspec  这个文件名  改成   mmkv.podspec 就好了，（文件里面：s.name改成：mmkv，这个没试，name 改的和yaml一致了）

**Comment by lingol** [comment]
It won't work when trying to publish to the dart library.
