### ISSUE TITLE
SEGV_ACCERR MMKVCore mmkv::MMKV::oldStyleWriteActualSize(unsigned long)

### ISSUE THREAD

**Issue by chensheng12330** [Tencent/MMKV#655]
### The language of MMKV

>  Objective-C

### The version of MMKV

> e.g. v1.2.7

### The platform of MMKV

> iOS [13.0<iOS_Sys<15.0]

### The installation of MMKV

> Cocoapods

### What's the issue?
call [MMKV clearAll] crash in app start.

SEGV_ACCERR MMKVCore mmkv::MMKV::oldStyleWriteActualSize

Error stack：
MMKVCore | mmkv::MMKV::oldStyleWriteActualSize(unsigned long) + 72
1 MMKVCore | mmkv::MMKV::oldStyleWriteActualSize(unsigned long) + 56
2 MMKVCore | mmkv::MMKV::writeActualSize(unsigned long, unsigned int, void const*, bool) + 48
3 MMKVCore | mmkv::MMKV::clearAll() + 256
4 MMKV |  [mmkvObj clearAll]

base device info:
model: iPhone6/6s/7/7p/8/8p/X
mem: 78MB
storage: 16.86G

Crash Cumulative influence: 100w+
Cumulative impact equipment: 1w+

**Comment by lingol** [comment]
Provide the **complete** crash call-stacks & MMKV logs, please.

**Comment by chensheng12330** [comment]
> Provide the **complete** crash call-stacks & MMKV logs, please.

Because it is an online crash, the log of MMKV cannot be obtained, so it cannot be provided.

I now provide a detailed stack at the time of the crash.

[MMKV_crash_call-stacks.rtf.zip](https://github.com/Tencent/MMKV/files/6203688/MMKV_crash_call-stacks.rtf.zip)

**Comment by lingol** [comment]
>0 MMKVCore
0x0000000105e69ff8 mmkv::MMKV::oldStyleWriteActualSize(unsigned long)
1 MMKVCore
0x0000000105e69fe8 mmkv::MMKV::oldStyleWriteActualSize(unsigned long)
2 MMKVCore
0x0000000105e687b4 mmkv::MMKV::writeActualSize(unsigned long, unsigned int, void const*, bool)
3 MMKVCore
0x0000000105e6b0fc mmkv::MMKV::clearAll()
4 XXXXActDataCollector
0x000000010324bf14 -[XXXXActDataStoreManage init]

Look at the stacks between 3 & 4, there's no call of the MMKV ObjC instance. 
Did you use the **MMKV Core** directly? You should use the **MMKV ObjC interface** instead. It protects you from such a potential crash.

**Comment by chensheng12330** [comment]
> > 0 MMKVCore
> > 0x0000000105e69ff8 mmkv::MMKV::oldStyleWriteActualSize(unsigned long)
> > 1 MMKVCore
> > 0x0000000105e69fe8 mmkv::MMKV::oldStyleWriteActualSize(unsigned long)
> > 2 MMKVCore
> > 0x0000000105e687b4 mmkv::MMKV::writeActualSize(unsigned long, unsigned int, void const*, bool)
> > 3 MMKVCore
> > 0x0000000105e6b0fc mmkv::MMKV::clearAll()
> > 4 XXXXActDataCollector
> > 0x000000010324bf14 -[XXXXActDataStoreManage init]
> 
> Look at the stacks between 3 & 4, there's no call of the MMKV ObjC instance.
I’m sure that the MMKV object was first used, and the crashed stack was not shown.

> Did you use the **MMKV Core** directly? You should use the **MMKV ObjC interface** instead. It protects you from such a potential crash.
I’m sure that use the **MMKV ObjC interface** instead. 

`
self.mProductCodeStore = [MMKV mmkvWithID:kProductCodeStore rootPath:[HLLActDataTool getForeverPathWithName:kProductCodeStore]];

[self.mProductCodeStore clearAll];
`
Using the above code, the above bug will occur with a certain probability.
I hope that this bug will be taken seriously. I see other people have reported similar exceptions.

**Comment by chensheng12330** [comment]
Attached is my sample code.
[cswActDataStoreManage.m.zip](https://github.com/Tencent/MMKV/files/6218965/cswActDataStoreManage.m.zip)

**Comment by lingol** [comment]
Well, can you provide the logs of MMKV when you do reproduce this bug with a certain probability?

**Comment by chensheng12330** [comment]
> Well, can you provide the logs of MMKV when you do reproduce this bug with a certain probability?

Because the online environment is crashing and there is no channel to get the log, I am very sorry that I cannot provide it here. This bug is provided by Tencent's bugly.

**Comment by lingol** [comment]
Looks like you are not taking this seriously. You said you can reproduce this bug with a certain probability, and you upload a demo project. And you can't collect any logs when this bug is reproduced with that demo project?

**Comment by chensheng12330** [comment]
> Looks like you are not taking this seriously. You said you can reproduce this bug with a certain probability, and you upload a demo project. And you can't collect any logs when this bug is reproduced with that demo project?

Yes, I cannot reproduce this bug. If you need a log of the MMKV crash, I can add a reporting mechanism to the project in the later version.

**Comment by lingol** [comment]
That will be very helpful.

> Yes, I cannot reproduce this bug. If you need a log of the MMKV crash, I can add a reporting mechanism to the project in the later version.

**Comment by lingol** [comment]
Any updates?

**Comment by OspreyRen** [comment]
Same crash, I am trying to invoke mmkv API in a single queue to fix this problem

**Comment by lingol** [comment]
> Same crash, I am trying to invoke mmkv API in a single queue to fix this problem

And again, can you provide **any logs** about your crash?

**Comment by lingol** [comment]
Closed due to inactive.
