### ISSUE TITLE
多进程用法

### ISSUE THREAD

**Issue by zirconnnn** [Tencent/MMKV#657]
### The language of MMKV

> Java, or Kotlin

### The version of MMKV

> the latest

### The platform of MMKV

>  Android

### The installation of MMKV

> maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> 这样的用法是否可以，比如：只有一个以user为key的数据是在多进程中同时使用到的，其他key的数据只有主进程会用到，那获取这个user为key的数据的时候以defaultMMKV(MULTI_PROCESS_MODE)形式获取，其他key则以defaultMMKV(SINGLE_PROCESS_MODE)获取，如果这样使用会有什么问题吗？多谢。

**Comment by lingol** [comment]
Why don't you separate those keys into different MMKV instances? The key that only the main process will use should keep in one file, the other keys that will be used by mult-process should keep in another file.

**Comment by zirconnnn** [comment]
> Why don't you separate those keys into different MMKV instances? The key that only the main process will use should keep in one file, the other keys that will be used by mult-process should keep in another file.

历史原因，为了兼容新老版本，这些数据是放在一个mmkv里面了，我上面想问这样的用法是否可以，如果这样使用了，会有什么问题？

**Comment by lingol** [comment]
You should never use MMKV like that.
