### ISSUE TITLE
清除应用缓存，写入失败

### ISSUE THREAD

**Issue by joker-fu** [Tencent/MMKV#662]
Android

MMKV： 1.2.7

代码清除应用缓存，然后MMKV->encode写入数据，返回结果为true。实际本地没有写入成功，decode也读取不出来。

**Comment by lingol** [comment]
Logs, please.

**Comment by lingol** [comment]
And a reproducible demo project.

**Comment by lingol** [comment]
What do you mean by '清除应用缓存', did you just delete the MMKV files on the disk?

**Comment by lingol** [comment]
This issue will be closed this week if there's no further information provided.

**Comment by joker-fu** [comment]
https://github.com/joker-fu/mmkvdemo

先点击 【读写测试】按钮，正常读写。
再点击【清除数据重启写入测试失效演示】，可见写入成功，重启后“println("===============> test1：  $str1")” 输出null。

**Comment by lingol** [comment]
```Java
            DataCleanUtils.cleanApplicationData(this@Demo1Activity)  // 
            val result = MMKVUtils.saveStr("test1", "bbbbbbbbbbb")  // 
```
And why do you think you can delete a file without deleting its content?
You have just deleted the MMKV files. It's **undefined behavior** to write data to a deleted file, even if the Operating System returns true.
