### ISSUE TITLE
希望可以添加 flutter 插件库的性能与 hive 库的对比

### ISSUE THREAD

**Issue by madroidmaq** [Tencent/MMKV#664]
目前 Flutter 中最主流的 key-value 存储库应该是 [hive](https://github.com/hivedb/hive) 库，他自己的性能数据如下：
![image](https://user-images.githubusercontent.com/6247142/114002125-2dbc6a00-988f-11eb-9aee-dcfd4c87f32b.png)

希望可以在文档中添加一下 mmkv flutter 插件与 hive 的性能对比信息。

**Comment by lingol** [comment]
Not interested. You can run some instrument by yourself.
