### ISSUE TITLE
SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by 532922397** [Tencent/MMKV#666]
version:1.2.5

Mobile phone model：
![image](https://user-images.githubusercontent.com/19923181/114381129-5ad58900-9bbd-11eb-8118-34dc21c529a1.png)

Presupposition：mode->MULTI_PROCESS_MODE

Problem description：Bugly feedback: when using app related functions, the mmkv access value was touched and this exception was raised.

java：
1 #00 pc 0000000000027708 /data/app/xxxx-sglRupzZh04mGvBshbXTSQ==/lib/arm64/libmmkv.so [arm64-v8a]
--
2 #01 pc 000000000001b858 /data/app/xxxx-sglRupzZh04mGvBshbXTSQ==/lib/arm64/libmmkv.so [arm64-v8a]
3 #02 pc 0000000000012378 /data/app/xxxx-sglRupzZh04mGvBshbXTSQ==/lib/arm64/libmmkv.so [arm64-v8a]
4 #03 pc 0000000000004d38 /data/app/xxxx-sglRupzZh04mGvBshbXTSQ==/oat/arm64/base.odex (oatdata+15672) [arm64-v8a]
5 java:
6 com.tencent.mmkv.MMKV.checkProcessMode(MMKV.java:275)
7 com.tencent.mmkv.MMKV.mmkvWithID(MMKV.java:167)
......
21 android.view.View.performClick(View.java:7281)
22 android.view.View.performClickInternal(View.java:7255)
23 android.view.View.access$3600(View.java:828)
24 android.view.View$PerformClick.run(View.java:27924)
25 android.os.Handler.handleCallback(Handler.java:900)
26 android.os.Handler.dispatchMessage(Handler.java:103)
27 android.os.Looper.loop(Looper.java:219)
28 android.app.ActivityThread.main(ActivityThread.java:8387)
29 java.lang.reflect.Method.invoke(Native Method)
30 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
31 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by lingol** [comment]
First thing first, upgrade to the latest version. If this still happens, we will continue talking inside #658

**Comment by 532922397** [comment]
There are also issues in 1.2.7, so it's meaningless to upgrade or not. 1.2.6 and 1.2.7 version change instructions are not found to have relevant repair?

**Comment by lingol** [comment]
Suit yourself.

**Comment by 532922397** [comment]
> Suit yourself.

Give me a general reason for the problem, OK?

**Comment by lingol** [comment]
Released with [v1.2.8](https://github.com/Tencent/MMKV/releases/tag/v1.2.8).
