### ISSUE TITLE
Migration from JCenter

### ISSUE THREAD

**Issue by carlonzo** [Tencent/MMKV#667]
### The platform of MMKV
Android

### The installation of MMKV
Maven

### What's the issue?

MMKV needs to migrate from JCenter as they are shutting down the repository.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by lingol** [comment]
Noted, thanks.

**Comment by carlonzo** [comment]
hi @lingol why is this close? does it mean it is done already?

**Comment by lingol** [comment]
It means I got the information.

**Comment by lingol** [comment]
MMKV will migrate to other repos in the next version. FYI

**Comment by lingol** [comment]
Migrated to Maven Central starting from [v1.2.8](https://github.com/Tencent/MMKV/releases/tag/v1.2.8).
