### ISSUE TITLE
有没有什么方法把一个mmkv文件里的所有kv迁移到另外一个文件中

### ISSUE THREAD

**Issue by zhuxianfeng13** [Tencent/MMKV#668]
### The language of MMKV

Java

### The version of MMKV
1.0.22

### The platform of MMKV
Android

### The installation of MMKV

AAR Package

### What's the issue?

工程中存在过多的mmkv文件，现在想把一些文件中的kv整理到同一个文件中（避免占用过多fd）
看了下，目前没有api能完成这个操作

**Comment by lingol** [comment]
No, this is no such thing.
