### ISSUE TITLE
confusedness with encodeString 

### ISSUE THREAD

**Issue by Yellup** [Tencent/MMKV#67]
### The language of MMKV

> Java

### The version of MMKV

> v1.0.10

### The platform of MMKV

> Android

### The installation of MMKV

> Maven, AAR Package 

### What's the issue?

> call kv.encode("string", null) will not update the value to ""

**Comment by lingol** [comment]
Call removeValue instead. Setting a null value is not allowed.

**Comment by lingol** [comment]
Null value is supported now. Checkout the latest version. (https://github.com/Tencent/MMKV/releases).
