### ISSUE TITLE
请教一下，NSUserDefault迁移至MMKV的实用性建议

### ISSUE THREAD

**Issue by nicolasiJasica** [Tencent/MMKV#671]
### The language of MMKV

> e.g. Objective-C, Swift,

### The version of MMKV

> e.g. v1.2.2  

### The platform of MMKV

> e.g. iOS

### The installation of MMKV

> e.g. Cocoapods
### What's the issue?

目前我们的项目是个中型项目，NSUserDefault的使用大概有几千处，我们想做老数据整体迁移至mmkv，但是目前经过考虑 有以下几个问题:
1.如果我们做整体数据迁移，目前来看需要将所有使用NSUserDefault的地方全部换为mmkv，迁移的方法是要写在启动的最前面么，这样子会对启动产生影响吧？ 

2.如果迁移的方法写到启动完成后，那么在启动期间使用老数据的地方，都需要做数据判断（判断是否数据迁移到了mmkv）？
比如：userdefault里有个count计数值（老版本数据），新版本（已经引入mmkv），在启动期间使用到count，我是需要写逻辑 来判断count值是否已经迁移到了mmkv里，然后再从mmkv里获取么，否则就还是从userdefault里获取？

3.如果不做整体迁移，做部分迁移的话，那之后如果想改为整体迁移，NSUserDefault的老数据就会覆盖mmkv里的新数据吧？

请问下 有什么针对数据迁移的建议么？

**Comment by lingol** [comment]
Here are the things you should do.  

* Profile the **performance** of migration before any optimization.
* Collect the **average time** of migration.
* Use your best judgement.

**Comment by nicolasiJasica** [comment]
> Here are the things you should do.
> 
> * Profile the **performance** of migration before any optimization.
> * Collect the **average time** of migration.
> * Use your best judgement.

好的 感谢 我需要再想想折中方案
