### ISSUE TITLE
mmkv encode return boolean

### ISSUE THREAD

**Issue by PApatigers** [Tencent/MMKV#672]
### The language of MMKV
java

### The version of MMKV
v1.0.19

### The platform of MMKV
android

### What's the issue?
mmkv 执行写操作return boolean 表示mmkv本次写操作可能是失败的，这里目前是否有数据支撑mmkv写操作的稳定性，目前看当抛出crc校验失败的场景，写入失败的概率会提高

**Comment by lingol** [comment]
No.
