### ISSUE TITLE
卸载app后MMKV数据没有被删除

### ISSUE THREAD

**Issue by bunny-pu** [Tencent/MMKV#673]
### The language of MMKV
Java

### The version of MMKV
com.tencent:mmkv-static:1.2.7

### The platform of MMKV
 Android

### The installation of MMKV
Maven

### What's the issue?
使用MMKV存储信息，将app卸载后重装，还未进行存储，mmkv里却有卸载前的数据

手机：samsung SM-J7109
Vivo vivo Xplay6
其他手机未尝试

**Comment by lingol** [comment]
It's not an MMKV bug.
If any, it should be the Android OS's bug, or the file system's bug.

**Comment by zhaowhao** [comment]
In android M and above versions they keep application backups in google driver, you can disable this by using, go to your project manifest file under Application section set android:allowBackup="true" to false.and you are good to go.

https://developer.android.com/guide/topics/data/autobackup#BackupSchedule
