### ISSUE TITLE
flutter 资源报错

### ISSUE THREAD

**Issue by ytx222** [Tencent/MMKV#674]
我使用flutter的mmkv 1.2.8
在打包的时候加载这个资源报错.我在chrome输入该地址,google返回了404 
https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml
完整日志如下
Launching lib\main.dart on JEF AN00 in debug mode...

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.tencent:mmkv-static:[1.2.7,).
     Required by:
         project :app > project :mmkv
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml'.
               > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml'.
               > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml'.
               > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml'.
               > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml'.
               > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/tencent/mmkv-static/maven-metadata.xml'.
               > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
                  > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://storage.flutter-io.cn/download.flutter.io/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not get resource 'https://storage.flutter-io.cn/download.flutter.io/com/tencent/mmkv-static/maven-metadata.xml'.
               > Could not GET 'https://storage.flutter-io.cn/download.flutter.io/com/tencent/mmkv-static/maven-metadata.xml'.
                  > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
                  > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
                  > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
                  > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
                  > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect
      > Failed to list versions for com.tencent:mmkv-static.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/tencent/mmkv-static/maven-metadata.xml'.
                  > Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15m 29s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by lingol** [comment]
Looks like your mirror is down.
> Connect to mirrors.opencas.cn:80 [mirrors.opencas.cn/2001:cc0:2020:4075:0:0:0:211] failed: Connection timed out: connect

**Comment by ytx222** [comment]
重复一遍,不是连接不上,而是google给我返回了404
![image](https://user-images.githubusercontent.com/43210216/115983545-66b94600-a5d4-11eb-9b89-62657d38a964.png)

**Comment by ytx222** [comment]
我觉得应该是 mirrors.opencas.cn 这个地址挂了,我更换了几个梯子,都无法连接,然后我在本机 ping mirrors.opencas.cn无法连接,之后又在一个阿里云服务器上 ping mirrors.opencas.cn同样无法连接(没有找到ip)

最后,请问下这种情况有什么其他的解决办法吗,因为这个问题,我无法继续完成我的调试

**Comment by ytx222** [comment]
我已经确定了,确实是域名的问题而不是我的问题
请查看这个域名分析结果
https://dns.tech/opencas.cn
数据显示opencas.cn未绑定ip

**Comment by lingol** [comment]
I don't know anything about _mirrors.opencas.cn_. It's not part of MMKV or MMKV project.
Sorry, there's nothing I can help you withthis.

**Comment by lingol** [comment]
Maybe you should check your local proxy setting for _mirrors.opencas.cn_? Find out why do you need to connect _mirrors.opencas.cn_ to download packages from JCenter.

**Comment by ytx222** [comment]
好的,谢谢

**Comment by ytx222** [comment]
感谢你的建议,我通过修改用户文件夹C:\Users\Administrator\.gradle下的gradle.properties文件,将其中的

`
systemProp.http.proxyHost=mirrors.opencas.cn
systemProp.http.proxyPort=80
systemProp.https.proxyHost=mirrors.opencas.cn
systemProp.https.proxyPort=80
`
部分注释,之后就可以访问了

但是奇怪的是,我从没有设置过相关内容,即这部分是默认生成的
