### ISSUE TITLE
Android后台起了一个Service，重新登录后，未能拿到更新后的token数据

### ISSUE THREAD

**Issue by wjbd** [Tencent/MMKV#681]
### The language of MMKV

> Java

### The version of MMKV

> 1.2.8

### The platform of MMKV

>  Android

### The installation of MMKV

> Maven

### What's the issue?
Android App在退出登录后，清掉了MMKV存储的数据，然后重新登录的时候，保存了Token数据信息，但是在Service中，MMKV拿不到重新登录保存的数据（Token，UserId等信息），导致Service的网络请求一直报错，但是在杀死进程后，重新进入APP，就可以正常拿到登录保存的数据了，请问是什么原因？

### What's the log of MMKV when that happened?
> 未保存log日志

**Comment by lingol** [comment]
You need to provide the logs of both the App & the Service.

**Comment by wjbd** [comment]
一次完整复现问题过程输出的Log日志如下：
I/MMKV: <MMKV_IO.cpp:1047::clearAll> cleaning all key-values from [mmkv.default]
I/MMKV: <MMKV.cpp:276::clearMemoryCache> clearMemoryCache [mmkv.default]
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values
I/MMKV: <MMKV.cpp:276::clearMemoryCache> clearMemoryCache [mmkv.default]
I/MMKV: <MMKV.cpp:139::~MMKV> destruct [mmkv.default]
I/MMKV: <MMKV_IO.cpp:1047::clearAll> cleaning all key-values from [mmkv.default]
I/MMKV: <MMKV.cpp:276::clearMemoryCache> clearMemoryCache [mmkv.default]
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values
I/MMKV: Enable checkProcessMode()
I/MMKV: <MMKV.cpp:198::initializeMMKV> root dir: /data/user/0/com*************/files/mmkv
I/MMKV: Enable checkProcessMode()
I/MMKV: <native-bridge.cpp:103::JNI_OnLoad> current API level = 26
I/MMKV: <MMKV.cpp:156::initialize> version v1.2.8 page size:4096
I/MMKV: <MMKV.cpp:198::initializeMMKV> root dir: /data/user/0/com*************/files/mmkv
I/MMKV: Enable checkProcessMode()
I/MMKV: <MMKV.cpp:198::initializeMMKV> root dir: /data/user/0/com*************/files/mmkv
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 567 actual size, file size 4096, InterProcess 1, meta info version:3
I/MMKV: <MMKV_IO.cpp:86::loadFromFile> loading [mmkv.default] with crc 3396335 sequence 43 version 3
E/MMKV: <MiniPBCoder.cpp:328::decodeOneMap> InvalidProtocolBuffer truncatedMessage
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values

**Comment by wjbd** [comment]
我把模式换成   MMKV.MULTI_PROCESS_MODE    后，完全没办法正常用了，日志为：
E/MMKV: <MiniPBCoder.cpp:328::decodeOneMap> InvalidProtocolBuffer truncatedMessage
E/MMKV: <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [mmkv.default]
E/MMKV: <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [mmkv.default]
E/MMKV: <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [mmkv.default]

**Comment by lingol** [comment]
First thing first, when used in multiple processes (App & Service), you **MUST** use `MMKV.MULTI_PROCESS_MODE`.
Second, you must use `MMKV.MULTI_PROCESS_MODE` on the same MMKV on **ALL process**.

**Comment by lingol** [comment]
You can not use a single process mode on one process, while using a multi-process mode on the other process.
It's must be **the same mode**.

**Comment by wjbd** [comment]
我现在已经把工具类全部改为了：MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null")，但是在Service中使用的时候，直接报错了 <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [mmkv.default]，Service中的网络请求也没有继续往下进行

**Comment by lingol** [comment]
Did you turn off App debuggable while turn on Service debuggable? Or did you run App in release build, while running Service in debug build?

**Comment by wjbd** [comment]
目前还是测试版，在测试的过程中发现的问题

**Comment by lingol** [comment]
Have you try downgrade to mmkv v1.2.7?

**Comment by wjbd** [comment]
原来使用的是1.0.15版本，发现了这个问题后，才切换到1.2.8的，现在问题是一样的

**Comment by lingol** [comment]
OK. I believe you must have forgotten to change somewhere to multi-process mode. 
Could you provide complete logs again? There's this keyword `InterProcess` that tells you whether you are loading in single/multi process mode.
>I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3

**Comment by wjbd** [comment]
1.0.15版本出现的问题是，我在后台的Service拿到的是之前的Token

**Comment by wjbd** [comment]
我现在已经把我的工具类全部修改成为 MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null")去用了，一次完成操作流程日志如下：
E/MMKV: <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [mmkv.default]
I/MMKV: <MMKV_IO.cpp:1047::clearAll> cleaning all key-values from [mmkv.default]
I/MMKV: <MMKV.cpp:276::clearMemoryCache> clearMemoryCache [mmkv.default]
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values
I/MMKV: <MMKV_IO.cpp:1047::clearAll> cleaning all key-values from [mmkv.default]
I/MMKV: <MMKV.cpp:276::clearMemoryCache> clearMemoryCache [mmkv.default]
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values
I/MMKV: <MMKV_IO.cpp:276::checkLoadData> [mmkv.default] oldSeq 55, newSeq 59
I/MMKV: <MMKV.cpp:276::clearMemoryCache> clearMemoryCache [mmkv.default]
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 460 actual size, file size 4096, InterProcess 1, meta info version:3
I/MMKV: <MMKV_IO.cpp:86::loadFromFile> loading [mmkv.default] with crc 2958263538 sequence 59 version 3
E/MMKV: <MiniPBCoder.cpp:328::decodeOneMap> InvalidProtocolBuffer truncatedMessage
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values
E/MMKV: <MiniPBCoder.cpp:320::decodeOneMap> InvalidProtocolBuffer truncatedMessage

**Comment by wjbd** [comment]
我又抓了一下从打开这个APP到切换账号的所有日志，如下：
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 688 actual size, file size 4096, InterProcess 0, meta info version:3
I/MMKV: <MMKV_IO.cpp:86::loadFromFile> loading [mmkv.default] with crc 420423162 sequence 59 version 3
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 15 key-values
I/MMKV: Enable checkProcessMode()
I/MMKV: <native-bridge.cpp:103::JNI_OnLoad> current API level = 26
I/MMKV: <MMKV.cpp:156::initialize> version v1.2.8 page size:4096
I/MMKV: <MMKV.cpp:198::initializeMMKV> root dir: /data/user/0/***/files/mmkv
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 702 actual size, file size 4096, InterProcess 1, meta info version:3
I/MMKV: <MMKV_IO.cpp:86::loadFromFile> loading [mmkv.default] with crc 3304325265 sequence 59 version 3
E/MMKV: <MiniPBCoder.cpp:328::decodeOneMap> InvalidProtocolBuffer truncatedMessage
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values
E/MMKV: <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [mmkv.default]
I/MMKV: Enable checkProcessMode()
I/MMKV: <native-bridge.cpp:103::JNI_OnLoad> current API level = 26
I/MMKV: <MMKV.cpp:156::initialize> version v1.2.8 page size:4096
I/MMKV: <MMKV.cpp:198::initializeMMKV> root dir: /data/user/0/***/files/mmkv
I/MMKV: Enable checkProcessMode()
I/MMKV: <native-bridge.cpp:103::JNI_OnLoad> current API level = 26
I/MMKV: <MMKV.cpp:156::initialize> version v1.2.8 page size:4096
I/MMKV: <MMKV.cpp:198::initializeMMKV> root dir: /data/user/0/***/files/mmkv
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 809 actual size, file size 4096, InterProcess 0, meta info version:3
I/MMKV: <MMKV_IO.cpp:86::loadFromFile> loading [mmkv.default] with crc 3769006877 sequence 59 version 3
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 15 key-values
E/MMKV: <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [mmkv.default]
E/MMKV: <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [mmkv.default]
E/MMKV: <MMKV_Android.cpp:244::checkProcessMode> Got a shared lock, but fail to exclusive lock [mmkv.default]
I/MMKV: <MMKV_IO.cpp:1047::clearAll> cleaning all key-values from [mmkv.default]
I/MMKV: <MMKV.cpp:276::clearMemoryCache> clearMemoryCache [mmkv.default]
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values
I/MMKV: <MMKV_IO.cpp:1047::clearAll> cleaning all key-values from [mmkv.default]
I/MMKV: <MMKV.cpp:276::clearMemoryCache> clearMemoryCache [mmkv.default]
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values
I/MMKV: <MMKV_IO.cpp:276::checkLoadData> [mmkv.default] oldSeq 59, newSeq 63
I/MMKV: <MMKV.cpp:276::clearMemoryCache> clearMemoryCache [mmkv.default]
I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 460 actual size, file size 4096, InterProcess 1, meta info version:3
I/MMKV: <MMKV_IO.cpp:86::loadFromFile> loading [mmkv.default] with crc 1444860945 sequence 63 version 3
E/MMKV: <MiniPBCoder.cpp:328::decodeOneMap> InvalidProtocolBuffer truncatedMessage
I/MMKV: <MMKV_IO.cpp:130::loadFromFile> loaded [mmkv.default] with 0 key-values
E/MMKV: <MiniPBCoder.cpp:320::decodeOneMap> InvalidProtocolBuffer truncatedMessage

**Comment by wjbd** [comment]
MMKV工具类如下：
`
public class DictUtils {

    public DictUtils() {
        /* cannot be instantiated */
        throw new UnsupportedOperationException("cannot be instantiated");
    }

    public static void put(String key,String str){
        MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").encode(key, str);
    }

    public static void put(String key,int i){
        MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").encode(key, i);
    }

    public static void put(String key,boolean bool){
        MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").encode(key, bool);
    }

    public static void put(String key,float f){
        MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").encode(key, f);
    }

    public static void put(String key,long l){
        MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").encode(key, l);
    }

    public static void put(String key,double d){
        MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").encode(key, d);
    }

    public static String getString(String key) {
        return MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").decodeString(key);
    }

    public static String getString(String key, String defaultValue) {
        return MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").decodeString(key, defaultValue);
    }

    public static int getInt(String key) {
        return MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").decodeInt(key);
    }

    public static int getInt(String key, int defaultValue) {
        return MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").decodeInt(key, defaultValue);
    }

    public static boolean getBool(String key) {
        return MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").decodeBool(key);
    }

    public static boolean getBool(String key, boolean defaultValue) {
        return MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").decodeBool(key, defaultValue);
    }

    public static float getFloat(String key) {
        return MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").decodeFloat(key);
    }

    public static float getFloat(String key, float defaultValue) {
        return MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").decodeFloat(key, defaultValue);
    }


    /**
     * 移除某个key值已经对应的值
     *
     * @param key
     */
    public static void remove(String key) {
        MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").removeValueForKey(key);
    }

    /**
     * 清除所有数据
     */
    public static void clearAll() {
        MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").clear();
    }

    /**
     * 查询某个key是否已经存在
     *
     * @param key
     * @return
     */
    public static boolean contains(String key) {
        return MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, "null").contains(key);
    }

    /**
     * 移除所用用户信息
     */
    public static void removeAllUser() {
        String lastUser = getString(Constants.LAST_USER);
        String lastAddress = getString(Constants.TEMP_BASE_URL);
        boolean BASE_URL_CHANGED = getBool(Constants.BASE_URL_CHANGED, false);
        clearAll();
        if (!TextUtils.isEmpty(lastUser)) {
            put(Constants.LAST_USER, lastUser);
        }
        if (!TextUtils.isEmpty(lastAddress)) {
            put(Constants.TEMP_BASE_URL, lastAddress);
        }
        put(Constants.BASE_URL_CHANGED, BASE_URL_CHANGED);
    }

}

`

**Comment by lingol** [comment]
>I/MMKV: <MMKV_IO.cpp:81::loadFromFile> loading [mmkv.default] with 0 actual size, file size 4096, InterProcess 0, meta info version:3
