### ISSUE TITLE
mmkv概率性崩溃

### ISSUE THREAD

**Issue by wddpxqq** [Tencent/MMKV#682]
mmkv版本：com.tencent:mmkv-static:1.2.8

堆栈如下，线上出现崩溃，

`backtrace:
      #00 pc 000000000004aec8  /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy+56) (BuildId: 2ecb1c994eb985bd1c2cba0c1f4ffc5e)
      #01 pc 00000000000246b4  /xxxx/data/app/XXXXXXX/lib/arm64/libmmkv.so (BuildId: d8fc5b053d1e0159c7bf1cdee18289895ffeaafc)
      #02 pc 000000000001f774  /xxxx/data/app/XXXXXXX/lib/arm64/libmmkv.so (BuildId: d8fc5b053d1e0159c7bf1cdee18289895ffeaafc)
      #03 pc 000000000001f338  /xxxx/data/app/XXXXXXX/lib/arm64/libmmkv.so (BuildId: d8fc5b053d1e0159c7bf1cdee18289895ffeaafc)
      #04 pc 000000000001e648  /xxxx/data/app/XXXXXXX/lib/arm64/libmmkv.so (BuildId: d8fc5b053d1e0159c7bf1cdee18289895ffeaafc)
      #05 pc 0000000000016d14  /xxxx/data/app/XXXXXXX/lib/arm64/libmmkv.so (BuildId: d8fc5b053d1e0159c7bf1cdee18289895ffeaafc)
      #06 pc 0000000000011e98  /xxxx/data/app/XXXXXXX/lib/arm64/libmmkv.so (BuildId: d8fc5b053d1e0159c7bf1cdee18289895ffeaafc)
      #07 pc 0000000000034f3c  /data/dalvik-cache/arm64/system@app@XXXXXXX@XXXXXXX.apk@classes.dex (art_jni_trampoline+188)
      #08 pc 0000000000139564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #09 pc 000000000019df00  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+204) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #10 pc 000000000030e7c4  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #11 pc 00000000003098dc  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+884) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #12 pc 000000000064d2cc  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+592) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #13 pc 0000000000133914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #14 pc 0000000000706ad6  /data/dalvik-cache/arm64/system@app@XXXXXXX@XXXXXXX.apk@classes.vdex (com.tencent.mmkv.MMKV.encode+60)
      #15 pc 0000000000651810  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtualQuick+1268) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #16 pc 0000000000137594  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual_quick+20) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #17 pc 00000000003e3450  /data/dalvik-cache/arm64/system@app@XXXXXXX@XXXXXXX.apk@classes.vdex (com.XXXXX.XX.Maaaaaa.aaaaaaa.Accccc.saveCardSortEntity+84)
      #18 pc 000000000064d508  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+1164) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #19 pc 0000000000133914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #20 pc 00000000003e1cc0  /data/dalvik-cache/arm64/system@app@XXXXXXX@XXXXXXX.apk@classes.vdex (com.XXXXX.XX.Maaaaaa.aaaaaaa.Accccc.getResultCode+212)
      #21 pc 000000000064d508  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+1164) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #22 pc 0000000000133914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #23 pc 00000000003e10a4  /data/dalvik-cache/arm64/system@app@XXXXXXX@XXXXXXX.apk@classes.vdex (com.XXXXX.XX.Maaaaaa.aaaaaaa.Accccc.onDisplayCard+102)
      #24 pc 0000000000651810  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtualQuick+1268) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #25 pc 0000000000137594  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual_quick+20) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #26 pc 00000000003ce6f4  /data/dalvik-cache/arm64/system@app@XXXXXXX@XXXXXXX.apk@classes.vdex (com.XXXXX.XX.contentprovider.DisplayCardProvider.onDisplayCard+8)
      #27 pc 000000000064d508  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+1164) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #28 pc 0000000000133914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #29 pc 00000000003ce736  /data/dalvik-cache/arm64/system@app@XXXXXXX@XXXXXXX.apk@classes.vdex (com.XXXXX.XX.contentprovider.DisplayCardProvider.prepareOnDisplayCard+52)
      #30 pc 000000000064d508  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+1164) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #31 pc 0000000000133914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #32 pc 00000000003ce6ba  /data/dalvik-cache/arm64/system@app@XXXXXXX@XXXXXXX.apk@classes.vdex (com.XXXXX.XX.contentprovider.DisplayCardProvider.call+162)
      #33 pc 00000000003012b8  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.9308488903873149651)+268) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #34 pc 0000000000633e84  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+796) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #35 pc 0000000000142ff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #36 pc 000000000066a5ac  /system/framework/arm64/boot-framework.oat (android.content.ContentProvider.call+76) (BuildId: e616cb78b85414a7acf76e16fb35db33982535fc)
      #37 pc 00000000006e7f3c  /system/framework/arm64/boot-framework.oat (android.content.ContentProvider$Transport.call+444) (BuildId: e616cb78b85414a7acf76e16fb35db33982535fc)
      #38 pc 000000000066d628  /system/framework/arm64/boot-framework.oat (android.content.ContentProviderNative.onTransact+3192) (BuildId: e616cb78b85414a7acf76e16fb35db33982535fc)
      #39 pc 00000000007fa7dc  /system/framework/arm64/boot-framework.oat (android.os.Binder.execTransactInternal+876) (BuildId: e616cb78b85414a7acf76e16fb35db33982535fc)
      #40 pc 00000000007fa348  /system/framework/arm64/boot-framework.oat (android.os.Binder.execTransact+296) (BuildId: e616cb78b85414a7acf76e16fb35db33982535fc)
      #41 pc 0000000000139564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #42 pc 000000000019df00  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+204) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #43 pc 000000000053dbdc  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #44 pc 000000000053f178  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+448) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #45 pc 000000000053f35c  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #46 pc 00000000003906e8  /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+660) (BuildId: ed957f9e6baee31469cf7b20a8b02d77)
      #47 pc 00000000000cec2c  /system/lib64/libandroid_runtime.so (_JNIEnv::CallBooleanMethod(_jobject*, _jmethodID*, ...)+124) (BuildId: 1242581802427fda42fc3b4cf957a509)
      #48 pc 0000000000167948  /system/lib64/libandroid_runtime.so (JavaBBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+160) (BuildId: 1242581802427fda42fc3b4cf957a509)
      #49 pc 0000000000054834  /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+232) (BuildId: f13c744dc8784aa69858a9ba1a91ced4)
      #50 pc 000000000005e660  /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1272) (BuildId: f13c744dc8784aa69858a9ba1a91ced4)
      #51 pc 000000000005e0b8  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+156) (BuildId: f13c744dc8784aa69858a9ba1a91ced4)
      #52 pc 000000000005ea0c  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+64) (BuildId: f13c744dc8784aa69858a9ba1a91ced4)
      #53 pc 000000000008592c  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24) (BuildId: f13c744dc8784aa69858a9ba1a91ced4)
      #54 pc 0000000000015578  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+320) (BuildId: 4d6b4dc3db3be810ef9feb7f334230a9)
      #55 pc 00000000000d4ee4  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+144) (BuildId: 1242581802427fda42fc3b4cf957a509)
      #56 pc 0000000000014dec  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+408) (BuildId: 4d6b4dc3db3be810ef9feb7f334230a9)
      #57 pc 00000000000b7038  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 2ecb1c994eb985bd1c2cba0c1f4ffc5e)
      #58 pc 0000000000051ca0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 2ecb1c994eb985bd1c2cba0c1f4ffc5e)`

**Comment by lingol** [comment]
Please symbolize your native call stacks.
And provide the logs of MMKV.

**Comment by lingol** [comment]
This issue will be closed without further imformation.

**Comment by lingol** [comment]
Closed due to inactive & lack of information.
