### ISSUE TITLE
MMKV init  loadLibraryFailed

### ISSUE THREAD

**Issue by guowuque** [Tencent/MMKV#687]
java.lang.UnsatisfiedLinkError	dlopen failed: "/data/app/XXX-pFtq7UnNps0LWeo-zbC86w==/lib/arm/libmmkv.so" has bad ELF magic
Runtime.java	1016
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/XXX-pFtq7UnNps0LWeo-zbC86w==/lib/arm/libmmkv.so" has bad ELF magic
	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
	at java.lang.System.loadLibrary(System.java:1657)
	at com.tencent.mmkv.MMKV.initialize(SourceFile:110)
	at com.tencent.mmkv.MMKV.initialize(SourceFile:71)

**Comment by lingol** [comment]
I believe you can solve this problem by googling. It's not MMKV's issue but your building problems.

**Comment by lingol** [comment]
The key word is "java.lang.UnsatisfiedLinkError bad ELF magic", by the way.
