### ISSUE TITLE
MMKV can't be used in Flutter iOS

### ISSUE THREAD

**Issue by orangeLong** [Tencent/MMKV#689]
when flutter run，ios project import mmkv can't find，

#if __has_include(<mmkv/MMKVPlugin.h>)
#import <mmkv/MMKVPlugin.h>
#else
@import mmkv;      //---- this line
#endif

because the flutter plugin name is mmkvflutter，so，i need modify the ios code like this 

#if __has_include(<mmkv/MMKVPlugin.h>)
#import <mmkv/MMKVPlugin.h>
#else
@import mmkvflutter;
#endif

can you fix this? tks

**Comment by lingol** [comment]
Duplicated with #605

**Comment by orangeLong** [comment]
I have configured it as wiki, but sometimes it works，mostly not

**Comment by lingol** [comment]
Well, then I guess you are not reading the wiki **carefully**. You must has been ignoring these two points:

* Note: you need to run pod install each time you have called flutter pub get, or has just returned to Xcode from Android Studio.
* We recommend using Xcode to debug iOS App.

**Comment by orangeLong** [comment]
ok，i see，tks, use xcode debug is not friendly，maybe change the flutter plugin name is a good idea

**Comment by lingol** [comment]
Changing the plugin name is impossible. The reason has been explained in the wiki, as well.

**Comment by orangeLong** [comment]
i know. thanks for answering my question. have a good day
