### ISSUE TITLE
遇到一个多线程crash

### ISSUE THREAD

**Issue by RhettTamp** [Tencent/MMKV#691]
The version of MMKV is   v1.2.2  
The platform of MMKV is iOS

FATAL_SIGNAL SIGABRT fault_address:0x00000001a05160dc
Thread 27 name: com.apple.root.default-qos
0NULL
((null))
1NULL
((null))
2NULL
((null))
3NULL
((null))
4PonyAI
mmkv::MMKV::readActualSize() (in PonyAI) MMKV_IO.cpp:385
5PonyAI
mmkv::MMKV::checkDataValid(bool&, bool&) (in PonyAI) MMKV_IO.cpp:220
6PonyAI
mmkv::MMKV::loadFromFile() (in PonyAI) MMKV_IO.cpp:78
7PonyAI
mmkv::MMKV::MMKV(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mmkv::MMKVMode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) (in PonyAI) MMKV.cpp:114
8PonyAI
mmkv::MMKV::mmkvWithID(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mmkv::MMKVMode, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) (in PonyAI) MMKV.cpp:219
9PonyAI
-[MMKV initWithMMapID:cryptKey:rootPath:mode:] (in PonyAI) libMMKV.mm:205
10PonyAI
+[MMKV mmkvWithID:cryptKey:rootPath:mode:] (in PonyAI) libMMKV.mm:180
11PonyAI
__62-[BDImageCache initWithMemoryCache:storePath:inlineThreshold:]_block_invoke.86 (in PonyAI) BDImageCache.m:152

#0 Thread 0 name: com.apple.main-thread
0NULL
((null))
1NULL
((null))
2NULL
((null))
3PonyAI
mmkv::ThreadLock::lock() (in PonyAI) ThreadLock.cpp:49
4PonyAI
mmkv::ScopedLock<mmkv::ThreadLock>::ScopedLock(mmkv::ThreadLock*) (in PonyAI) ScopedLock.hpp:47
5PonyAI
+[MMKV mmkvWithID:cryptKey:rootPath:mode:] (in PonyAI) libMMKV.mm:168
6PonyAI
__29+[NestieMMKV commonMMKVCache]_block_invoke (in PonyAI) NestieMMKV.m:50
7NULL
((null))
8NULL
((null))
9PonyAI
+[NestieMMKV commonMMKVCache] (in PonyAI) NestieMMKV.m:49
10PonyAI
+[NestieMMKV storageWithConfig:] (in PonyAI) NestieMMKV.m:72
11PonyAI
-[NestieCenter boolForKey:config:defaultValue:] (in PonyAI) NestieCenter.m:151
12PonyAI
-[NestieCenter boolForKey:config:] (in PonyAI) NestieCenter.m:145
13PonyAI
-[ChameleonManager isSkyMode] (in PonyAI) ChameleonManager.m:69
14PonyAI
AppDelegate.application(_: UIApplication, didFinishLaunchingWithOptions: [UIApplicationLaunchOptionsKey : Any]?) (in PonyAI) AppDelegate.swift:43
15PonyAI
@objc AppDelegate.application(_: UIApplication, didFinishLaunchingWithOptions: [UIApplicationLaunchOptionsKey : Any]?) (in PonyAI) <compiler-generated>:0

**Comment by RhettTamp** [comment]
crash_info_0 | Assertion failed: (m_metaFile-&gt;isFileValid()), function readActualSize, file /Library/Caches/bytebus/packager_projects/xcproject_MMKVCore_1.2.2.Osm6myqE/Pods/MMKVCore/Core/MMKV_IO.cpp, line 386.

**Comment by lingol** [comment]
Nah, it has nothing with multi-threading. If you crash on that assertion, it means the file is invalid.

**Comment by lingol** [comment]
You should check the **logs** of MMKV. I'm sure it tells why the file is invalid.

**Comment by lingol** [comment]
Close due to inactive.
