### ISSUE TITLE
 <MMKV.cpp:537::getString> InvalidProtocolBuffer negativeSize

### ISSUE THREAD

**Issue by madreain** [Tencent/MMKV#692]
<MMKV.cpp:537::getString> InvalidProtocolBuffer negativeSize

**Comment by lingol** [comment]
Please follow the issue template, provide as much info as you can.

**Comment by lingol** [comment]
My best guess is that you are getting a `String` value from a key that other types such as `int` or `double` were stored.

**Comment by madreain** [comment]
ok thank you,I'll check it
