### ISSUE TITLE
MMKV 1.2.9 Users should not use the armeabi arch

### ISSUE THREAD

**Issue by carlonzo** [Tencent/MMKV#695]
### The version of MMKV
1.2.9

### The platform of MMKV
Android

### What's the issue?
Hi, compared to 1.2.8, the aar containing 1.2.9 increased its size by 1 MB
(here for comparison 1.2.8 vs 1.2.9 https://repo1.maven.org/maven2/com/tencent/mmkv-static/1.2.8/ https://repo1.maven.org/maven2/com/tencent/mmkv-static/1.2.9/ )

opening the aar of 1.2.9, I see a `jni/armeabi/libmmkv.so` binary for armeabi of 5.1MB (when before was 300 kB) even tough I thought the architecture was dropped. I guess this is a bug?

**Comment by lingol** [comment]
It's a bug. Somehow the packing script uploads the unstriped so of `armeabi`.
For the moment, you could just ignore that arch.

**Comment by lingol** [comment]
Maven Central doesn't allow deleting or editing a published version of an archive. So I have to leave it as it is for now.

For users of MMKV v1.2.9, you **should not use** the `armeabi` lib. Because it's not only big but also unstable.

**Comment by lingol** [comment]
I will leave this issue open until our next version is released.

**Comment by carlonzo** [comment]
thanks for the info. sadly the armeabi arch cant be ignored, as its packed in the final apk. any tips to ignore it?

**Comment by lingol** [comment]
Maybe this will work. [Gradle splits.](https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkvdemo/build.gradle#L50)

**Comment by lingol** [comment]
https://developer.android.com/studio/build/configure-apk-splits

**Comment by mutour** [comment]
建议把版本号改成1.2.9.1重新提交到Maven Central。

**Comment by lingol** [comment]
Nah, v1.2.10 will come out instead.

**Comment by carlonzo** [comment]
Any ETA when this fix will be out? We need an universal APK and we can't use split.

**Comment by lingol** [comment]
> Any ETA when this fix will be out? We need an universal APK and we can't use split.

Okay, I'll make it happen ASAP.

**Comment by lingol** [comment]
Released with [v1.2.10](https://github.com/Tencent/MMKV/releases/tag/v1.2.10).
