### ISSUE TITLE
Swift下set(_:forKey:) 在Float和Double中遇到的问题

### ISSUE THREAD

**Issue by FunnyerFeng** [Tencent/MMKV#697]
Swift下set(_:forKey:) 在Float和Double中遇到的问题
在Swift下，因为setFloat和setDouble是一个方法
mmkv.set(-3.1415926, forKey: "float_Type")
print(mmkv.float(forKey: "float_Type")) ——> 1.5397802e+08
print(mmkv.double(forKey: "float_Type")) ——>  -3.1415926
所以，建议对float(forKey:) 和double(forKey:)做一定的兼容处理，使都能获取正确的值

**Comment by lingol** [comment]
No, you have get it wrong. The problem is not about `float(forKey:)` or `double(forKey:)`. 
It's about `set(_:forKey)`. Here's what the Swift document saying:
>Likewise, if you don’t specify a type for a floating-point literal, Swift infers that you want to create a Double:
>
>>let pi = 3.14159
>>// pi is inferred to be of type Double
>
>Swift always chooses Double (rather than Float) when inferring the type of floating-point numbers.

That means you have to **be specific** about the type of the value you are setting into MMKV.
```Swift
mmkv.set(Float(-3.1415926), forKey: "float_Type")
print(mmkv.float(forKey: "float_Type"))
```
