### ISSUE TITLE
mmkv 1.2.8 iOS 不能运行，duplicate symbol 错误

### ISSUE THREAD

**Issue by EchoPuda** [Tencent/MMKV#698]
版本：1.2.8
平台：iOS

看描述是与其他SDK中的静态库冲突了？
这个要怎么办？
```
duplicate symbol '_version' in:
    /Users/zhengjiaming/Desktop/Project/1.0.0/buylive/buy_live/ios/Pods/IKVideoSDK/iOS/pod/libMeeLiveMedia.a(ZegoRoomWrapper.o)
    /Users/zhengjiaming/Library/Developer/Xcode/DerivedData/Runner-bmerwndliqatmhcbacbveqcbjchz/Build/Products/Debug-iphoneos/mmkvflutter/libmmkvflutter.a(flutter-bridge.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by lingol** [comment]
For the time being, you can either  
* make flutter relative stuff as a **dynamic framework**,
* or change the name `version` in the source file of one of the libs (libMeeLiveMedia or libmmkvflutter) **locally**.

**Comment by EchoPuda** [comment]
> For the time being, you can either
> 
> * make flutter relative stuff (or libMeeLiveMedia) as a **dynamic framework**,
> * or change the name `version` in the source file of one of the libs (libMeeLiveMedia or libmmkvflutter) **locally**.

将iOS中.mm文件中的version 同dart中的version 修改为别的函数名解决了
