### ISSUE TITLE
key相同，存储的数据类型不同时，拿到的值不争取

### ISSUE THREAD

**Issue by ljphawk** [Tencent/MMKV#699]
版本1.2.9，非业务场景，我只是写了下demo，key相同的情况下，我存的值类型不同，但我获取时，获取到的值，并不是我存的，也并没有操作保存过关于这个值的任何行为。
![image](https://user-images.githubusercontent.com/22888363/120911640-70e26000-c6bb-11eb-8f17-9b008e17ba2a.png)

**Comment by lingol** [comment]
That's expected behavior. MMKV does **type eraser** inside. It's means MMKV doesn't know which type of the value you've stored. 

You have to be specific when retrieving any values.
