### ISSUE TITLE
mmkv::MMKV::set(NSObject<NSCoding>*, NSString*) 错误

### ISSUE THREAD

**Issue by DonsonWu** [Tencent/MMKV#700]
### The language of MMKV
Objective-C

### The version of MMKV
  - MMKV (1.2.6):
   - MMKVCore (~> 1.2.6)
  - MMKVCore (1.2.6)

### The platform of MMKV
 iOS

### The installation of MMKV
Cocoapods

### What's the issue?

使用mmkv方法对用户信息进行保存

+ (void)saveUserInfoObject:(NSDictionary *)userInfo forKey:(NSString *)uid{
    
    NSDictionary *user_dict = [[MMKV defaultMMKV] getObjectOfClass:[NSDictionary class] forKey:@“userInfo”];
    
    NSMutableDictionary *user_muteDict = [NSMutableDictionary dictionaryWithDictionary:user_dict];

    [user_muteDict setObject:userInfo forKey:uid];
    
    NSMutableDictionary *user_muteDict = [NSMutableDictionary dictionaryWithDictionary:user_dict];

    //调用方法crash
    [[MMKV defaultMMKV] setObject:user_muteDict forKey:@“userInfo”];

  }

![1623117420694](https://user-images.githubusercontent.com/15194024/121111137-f17e9900-c840-11eb-86f2-b5944c95b0fa.jpg)
![1623117477209](https://user-images.githubusercontent.com/15194024/121111136-f17e9900-c840-11eb-960e-3f6060fca7ff.jpg)

### What's the log of MMKV when that happened?
线上崩溃，没有MMKV日志

**Comment by lingol** [comment]
Looking into your crash stack, I don't think it has anything to do with MMKV. The iOS's `NSKeyedArchiver` has failed to encode your dictionary into data.
For clarification, you can try this and see whether it crashes or not:
```Objective-C
[user_muteDict setObject:userInfo forKey:uid];
NSData *data = [NSKeyedArchiver archivedDataWithRootObject:user_muteDict];
```

**Comment by lingol** [comment]
My best guess is that some values stored inside the `userInfo` do not conform to `NSCoding` protocol.

**Comment by DonsonWu** [comment]
thanks!

**Comment by GE-GAO-ZHAO** [comment]
Same problem!  may I ask , how to solve problems ?
