### ISSUE TITLE
iOS 平台打包ipa后，无法正常调用对应MMKV方法

### ISSUE THREAD

**Issue by EchoPuda** [Tencent/MMKV#701]
版本：1.2.8
平台：iOS

本地Run调试正常，debug、profile、release模式均尝试过，
但在打包ipa安装后，在调用`var mmkv = MMKV('testMMKV')`后会报以下错误，

```
Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, getMMKVWithID): symbol not found)
```

若使用`MMKV.defaultMMKV()`, 则报以下错误

```
Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, getDefaultMMKV): symbol not found)
```

`MMKV.initialize()`初始化成功。

是iOS打包需要额外配置什么么？

**Comment by lingol** [comment]
MMKV requires Nothing special on packaging IPA. You should ask/search somewhere else.

**Comment by lingol** [comment]
Maybe ask the flutter guys/community.

**Comment by lingol** [comment]
By the way, the latest version of MMKV for Flutter is v1.2.10. You should upgrade yours.

**Comment by lingol** [comment]
A little search and I got this:
https://github.com/dart-lang/ffi/issues/41#issuecomment-757597034
FYI

**Comment by EchoPuda** [comment]
> A little search and I got this:
> [dart-lang/ffi#41 (comment)](https://github.com/dart-lang/ffi/issues/41#issuecomment-757597034)
> FYI

这个方法解决了，谢谢。
我们还未排时间适配Flutter 2.0，所以MMKV先接入v1.2.8.

**Comment by OnClickListener2048** [comment]
请问是如何解决的
