### ISSUE TITLE
MMKV.defaultMMKV()  nullable

### ISSUE THREAD

**Issue by CpuTurbo** [Tencent/MMKV#703]
### The language of MMKV
> Kotlin

### The version of MMKV
>  v1.2.9

### The platform of MMKV
>  Android

为什么MMKV.defaultMMKV()返回是可空的？有哪些情况可能造成可空？

为什么可空想必mmkv在创建的时候是知道的，可否使defaultMMKV返回不可空。
在现在返回null的时候抛出异常，在异常中返回导致创建失败的原因。

比如

```
throw new RuntimeException("空间不足")
```

**Comment by lingol** [comment]
Most of the case, you should crash your App when getting a null instance of MMKV. There's little thing you can do in such circumstances.

**Comment by lingol** [comment]
Duplicated with #624

**Comment by CpuTurbo** [comment]
既然是这样的话，那为什么不把nullable注解去掉直接抛出异常呢。

现在这样的设计在kotlin下调用除了增加不必要的可空判断和非空断言，可以说毫无意义吧

**Comment by lingol** [comment]
Thanks for your suggestion. I'll consider about that.

**Comment by CpuTurbo** [comment]
> Thanks for your suggestion. I'll consider about that.

期待你的更新

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/commit/d375a295c11c5481726c32a2621ff47ed0c2427e
