### ISSUE TITLE
不支持 flutter build 脚本

### ISSUE THREAD

**Issue by Lishaoshuai** [Tencent/MMKV#704]
### The language of MMKV
dart

### The version of MMKV
1.2.8

### The platform of MMKV
iOS

### The installation of MMKV
flutter build iOS

### What's the issue?
使用 `flutter build ios --debug --no-simulator  --no-codesign --verbose` 脚本编译会失败，原因是找不到 podspec

               -> Fetching podspec for `mmkv` from `Flutter/.symlinks/mmkv/ios`
               [!] No podspec found for `mmkv` in `Flutter/.symlinks/mmkv/ios`

可能的原因是 flutter 找 podspec 的时候使用的是库的名字，而 mmkv 的叫 mmkvflutter.podspec 导致找不到。
请修改为 mmkv.podspec

### What's the log of MMKV when that happened?
> Your detail logs. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.

**Comment by lingol** [comment]
PLEASE read the wiki before asking any questions. https://github.com/Tencent/MMKV/wiki/flutter_setup#installation
