### ISSUE TITLE
Android 中totalSize()是整个存储空间的大小吗？

### ISSUE THREAD

**Issue by bjhexn** [Tencent/MMKV#706]
Android:  totalSize（） 是当前存储总大小吗
 IOS： 有actualSize（）  ,  android 里没有这个方法，请问这个方法的作用是什么

**Comment by lingol** [comment]
The `totalSize()` is the size of the underlying file.
The `actualSize()` is the used size by MMKV on the file. Which will be added on Android in next version.

**Comment by bjhexn** [comment]
没明白什么意思？ 能举个例子吗？
totalSize() 是文件大小？
actualSize() 是MMKV 在文件上的大小？

**Comment by bjhexn** [comment]
totalSize  是指存储后的文件大小。
actualSize 是指MMKV存储的实际大小。

totalSize > actualSize    是这样吗？文件里还需要其它信息，我理解这两个大小差别不大

**Comment by lingol** [comment]
The code is added in the `dev` branch. You can try it out by yourself.

**Comment by lingol** [comment]
Each mmaped file will have at least the size of one **pagesize**. 
For example, the **pagesize** on Android is 4K, so each MMKV file will have at least 4K size. That is the `totalSize()`.
But not every size is used, the used size is the `actualSize()`.

**Comment by lingol** [comment]
Released with [v1.2.10](https://github.com/Tencent/MMKV/releases/tag/v1.2.10).
