### ISSUE TITLE
commit接口造成ANR问题

### ISSUE THREAD

**Issue by PApatigers** [Tencent/MMKV#708]
### The language of MMKV
java

### The version of MMKV
v 1.0.21

### The platform of MMKV
android

### The installation of MMKV
source

### What's the issue?
commit接口调用造成ANR问题：
<html>
<body>

sync /data0/workspace/library-publish-slave82-1/b8d48bf9c847e581da2295795c94bb03229/mmkv-src/src/main/cpp/MMKV.cpp:1338
--
2 | com.tencent.mmkv.MMKV.sync(MMKV.java)
3 | com.tencent.mmkv.MMKV.commit(MMKV.java:625)
4 | com.xunmeng.pinduoduo.mmkv.MMKVProxy.commit(MMKVProxy.java:423)

</body>
</html>
堆栈发现commit接口调用可能造成anr问题，考虑mmkv底层实现，似乎不依赖commit接口实现同步，请教下该接口设计含义，以及是否需要调用

**Comment by lingol** [comment]
You don't need to call it.
By the way, your version is way too old. You should upgrade to v1.2.x.
