### ISSUE TITLE
Does MMKV support multi rootDir?

### ISSUE THREAD

**Issue by zeropad** [Tencent/MMKV#712]
### The language of MMKV

> JAVA

### The version of MMKV

> v1.2.9

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?
Does MMKV support multi rootDir? This demand is out of Android sandbox design, which is a sandbox's directories could be more than one. Here listed the defination of CE and DE storage: 

> On an FBE-enabled device, each user of the device has two storage locations available to applications:
> 
> Credential Encrypted (CE) storage, which is the default storage location and only available after the user has unlocked the device.
> Device Encrypted (DE) storage, which is a storage location available both during Direct Boot mode and after the user has unlocked the device.
> (source: https://source.android.google.cn/security/encryption/file-based?hl=zh-cn)

Well. If a developer wants his appliction able to access some data before a device is unlocked, he should store the data in DE storage. However, keeping all data in DE storage is not recommended because this reduces security. Developers might expect to migrate only necessary data to DE storage and keep the most remain in CE storage. Can MMKV handle cases like this?

**Comment by lingol** [comment]
You can set a custom rootDir for any MMKV instance if that's what you are talking about.
https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/java/com/tencent/mmkv/MMKV.java#L345

**Comment by zeropad** [comment]
Thanks a lot. That solves the problem.
