### ISSUE TITLE
encode传入Parcelable数据以及decodeParcelable，Parcelable数据是否有限制呢？

### ISSUE THREAD

**Issue by PeOS-China** [Tencent/MMKV#713]
**encode传入Parcelable数据以及decodeParcelable，Parcelable数据是否有限制呢？**
当传入的Parcelable数据大小比较小时, decodeParcelable可正常返回数据；但把Parcelable数据很大时，超过2M，decodeParcelable返回的数据是null。Parcelable数据很大时调用encode，encode返回的是true，没有提示失败。

**Comment by lingol** [comment]
As long as I can tell, it is nothing about MMKV but the Parcelable framework itself. No?

**Comment by PeOS-China** [comment]
> As long as I can tell, it is nothing about MMKV but the Parcelable framework itself. No?

We need to save a large json data in multiple threads and extract it quickly. A single record of sqllite has a limit of 2M, so it is not suitable. The new database ObjectBox is fast, but it can only save basic data. Custom types need to be written in a converter. The conversion of json to object used in the converter is also time-consuming. Is there a recommended solution?

**Comment by lingol** [comment]
Everything will become slow when the JSON is large (2M). JSON is simply not designed for representing/storing large data. You should choose a different path at the very top of the data model design. 

For example, you may consider storing each key/value (inside the JSON) into MMKV instead of one big giant JSON string.

**Comment by PeOS-China** [comment]
> Everything will become slow when the JSON is large (2M). JSON is simply not designed for representing/storing large data. You should choose a different path at the very top of the data model design.
> 
> For example, you may consider storing each key/value (inside the JSON) into MMKV instead of one big giant JSON string.

I see, thank you
