### ISSUE TITLE
Android MMKV 1.2.7 出现大量的native crash

### ISSUE THREAD

**Issue by choha** [Tencent/MMKV#716]
### The language of MMKV

> Java、Kotlin

### The version of MMKV

> version：1.2.7

### The platform of MMKV

>  Android

### The installation of MMKV

> Maven

### 出现概率性Native crash，堆栈如下

backtrace:
  #00  pc 0000000000027b30  /data/app/xxx-4OvxHo2RwYcLmtvBTBQSUg==/lib/arm64/libmmkv.so
  #00  pc 000000000001ba44  /data/app/xxx-4OvxHo2RwYcLmtvBTBQSUg==/lib/arm64/libmmkv.so
  #00  pc 00000000000123e8  /data/app/xxx-4OvxHo2RwYcLmtvBTBQSUg==/lib/arm64/libmmkv.so
  #00  pc 00000000002a38c8  /data/app/xxx-4OvxHo2RwYcLmtvBTBQSUg==/oat/arm64/base.odex (art_jni_trampoline+152)
  #00  pc 0000000000a637f0  /data/app/xxx-4OvxHo2RwYcLmtvBTBQSUg==/oat/arm64/base.odex (com.tencent.mmkv.MMKV.a+176)
  #00  pc 0000000000a64150  /data/app/xxxxx-4OvxHo2RwYcLmtvBTBQSUg==/oat/arm64/base.odex (com.tencent.mmkv.MMKV.p+112)
  #00  pc 000000000099de70  /data/app/xxxx-4OvxHo2RwYcLmtvBTBQSUg==/oat/arm64/base.odex ((java.util.concurrent.ThreadPoolExecutor.runWorker+984)
  #00  pc 00000000009a5970  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
  #00  pc 00000000004afbb8  /system/framework/arm64/boot.oat (java.lang.Thread.run+72)
  #00  pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
  #00  pc 0000000000145fec  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244)
  #00  pc 00000000004b15e0  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #00  pc 00000000004b26f4  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416)
  #00  pc 00000000004f30b0  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1176)
  #00  pc 00000000000d6cb0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
  #00  pc 0000000000074eac  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

### Android 系统和机型
![image](https://user-images.githubusercontent.com/13478260/124254832-0f979a80-db5c-11eb-8320-a73ffad09059.png)

**Comment by lingol** [comment]
And the logs of mmkv please.

**Comment by lingol** [comment]
By the way, above the **logs** requirement, you should **symbolize** your crash stacks.

**Comment by lingol** [comment]
Hello, any update on logs? A crash issue without logs will be closed in a week.

**Comment by lingol** [comment]
If you are using com.tencent.mmkv, you should switch to com.tencent.mmkv-static.
This issue is closed due to inactive.
