### ISSUE TITLE
[Native Crash]signal 7 (SIGBUS), code 2 (BUS_ADRERR)

### ISSUE THREAD

**Issue by hidoudou** [Tencent/MMKV#717]
### The language of MMKV
Java

### The version of MMKV
1.2.10

### The platform of MMKV
Android

### The installation of MMKV
Git clone

### What's the issue?
getString in MMKV.java trigger crash, and we found the related code is:
int8_t CodedInputData::readRawByte() {
    if (m_position == m_size) {
        auto msg = "reach end, m_position: " + to_string(m_position) + ", m_size: " + to_string(m_size);
        throw out_of_range(msg);
    }
    auto *bytes = (int8_t *) m_ptr;
    _**return bytes[m_position++];**_ // this line
}

and the full backstrace is as following:

/Core/MMKV.cpp:534
mmkv::CodedInputData::readString() at /Core/CodedInputData.cpp:88
mmkv::CodedInputData::readRawVarint32() at /Core/CodedInputData.cpp:160
mmkv::CodedInputData::readRawByte() at /Core/CodedInputData.cpp:222

and we were thinking maybe the check expression is not robust?
if (m_position == m_size)

**Comment by lingol** [comment]
The boundary check robust. No doubt about that. 
A crash of **BUS_ADRERR** means the address itself is not valid. Either the OS has somehow dropped the mmap memory, or simply shit happens.

**Comment by lingol** [comment]
You should provide **logs** of MMKV for us to further investigate.

**Comment by hidoudou** [comment]
> You should provide **logs** of MMKV for us to further investigate.

no problem, we are working on it.
BTW, could you provide the NDK version you are using for the production environment?

**Comment by lingol** [comment]
MMKV starting from v1.2.9 uses the latest NDK.

**Comment by lingol** [comment]
Any updates yet?

**Comment by lingol** [comment]
Close due to inactive.
