### ISSUE TITLE
Add flutter test, please!

### ISSUE THREAD

**Issue by vance-liu** [Tencent/MMKV#718]
## Note:
no

### The language of MMKV

> dart, flutter

### The version of MMKV

> latest

### The platform of MMKV

> no

### The installation of MMKV

> flutter

### What's the issue?

> Awesome project! Add flutter test, make it better, please!

### What's the log of MMKV when that happened?
> no

**Comment by lingol** [comment]
Noted.

**Comment by mopi1402** [comment]
I tried to check for it but I think the easiest should be to compile a fat lib (.a for iOS) in order to use it for testing.
