### ISSUE TITLE
CRC校验失败，数据丢失

### ISSUE THREAD

**Issue by PApatigers** [Tencent/MMKV#719]
### The language of MMKV
java

### The version of MMKV
1.2.7

### The platform of MMKV
android

### What's the issue?
数据丢失

### What's the log of MMKV when that happened?
[I]13:14:14.653][3444, 49][mmkv][, , 0][**fail to lock fd=65, ret=-1, error:Resource deadlock would occur**
[I][13:14:14.658][3444, 49][mmkv][, , 0][m_crcDigest[76080634] != m_metaInfo.m_crcDigest[2349936304]
[I][13:14:14.659][3444, 49][mmkv][, , 0][clearMemoryState [test]
[I][13:14:14.669][3444, 49][mmkv][, , 0][loading [test] with 471048 size in total, file size is 524288
[I][13:14:14.671][3444, 49][mmkv][, , 0][check crc [test] fail, crc32:2349936304, m_crcDigest:76080634
[I][13:14:14.839][3444, 49][mmkv][, , 0][onMMKVCRCCheckFail mmapID : test
[I]13:14:15.225][3444, 49][mmkv][, , 0][Recover strategic for testis OnErrorDiscard
[I][13:14:15.226][3444, 49][.mmkv][, , 0][loaded [test] with 0 values
[I][13:14:17.237][3444, 189][mmkv][, , 0][[test] oldSeq 6947, newSeq 6948
[I][13:14:17.238][3444, 189][mmkv][, , 0][clearMemoryState [test]
[I][13:14:17.238][3444, 189][mmkv][, , 0]**[loading [test] with 0 size in total, file size is 524288**
[I][13:14:17.239][3444, 189][mmkv][, , 0][loaded [test] with 0 values

日志记录到一次crc校验失败的场景，猜测由于文件锁异常，造成文件损坏，后续每次打开这个mmkv文件都无法捞取真实数据
请教下日志是否能反映上述猜测

**Comment by lingol** [comment]
Maybe.

**Comment by PApatigers** [comment]
这里文件损坏如何确定是否由mmkv文件锁造成的编辑损坏，还是由于文件系统的不稳定性造成呢

**Comment by lingol** [comment]
You can never know.
