### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by bbc876219** [Tencent/MMKV#722]
The language of MMKV
Java、Kotlin

The version of MMKV
version：1.1.2

The platform of MMKV
Android

The installation of MMKV
local so

在
Motorola Moto C、Motorola Moto C Plus机器上，Android 7.0 (SDK 24)
出现概率性Native crash，堆栈如下

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.xxx.xxxx <<<

backtrace:
  #00  pc 0000000000004cae  /mnt/expand/0456a8a5-e17d-4a7c-b371-3eeb032917f2/app/com.kwai.video-1/lib/arm/libmmkv.so
  #00  pc 0000000000005323  /mnt/expand/0456a8a5-e17d-4a7c-b371-3eeb032917f2/app/com.kwai.video-1/lib/arm/libmmkv.so
  #00  pc 00000000000a78a7  /mnt/expand/0456a8a5-e17d-4a7c-b371-3eeb032917f2/app/com.kwai.video-1/oat/arm/base.odex (offset 0x276f000)

**Comment by lingol** [comment]
As it's been told in the issue template, a crash issue without **logs & symbolized call stacks** will be ignored in a week.
So please provide that information.

**Comment by lingol** [comment]
By the way, v1.1.2 is way too old, we simply don't have time for that.
Come back later if you still have such a problem after upgrade to the latest version.
