### ISSUE TITLE
build dynamic framework error 

### ISSUE THREAD

**Issue by wang542413041** [Tencent/MMKV#723]
## Note:

How to build a dynamic embed framework with podspec ?

When use `pod package --embedde --force MMKVCore.podspec`

A error occur `s.complier_flags = '-x objective-c++' xcodebuild error, a invalid param '-x'`

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin
Objective-C

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.
1.2.0

### The platform of MMKV

> e.g. iOS or Android
iOS

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
You should make this issue to the pod package team complain about not supporting extra build configures.

As for building pod dependence as dynamic frameworks, I believe the **official** way of CocoaPods is by using **use_frameworks**.
https://guides.cocoapods.org/syntax/podfile.html#use_frameworks_bang
```ruby
target 'MyApp' do
  use_frameworks! :linkage => :dynamic
  pod 'MMKV'
end
```
