### ISSUE TITLE
null pointer dereference

### ISSUE THREAD

**Issue by e53179** [Tencent/MMKV#724]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV
Java
### The version of MMKV
> v1.2.8
### The platform of MMKV
Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?
MI PAD 4 PLUS  Crash after opening the app
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/clover/clover:8.1.0/OPM1.171019.019/V10.3.2.0.ODJCNXM:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 6262, tid: 6343, name: pool-core-t-1  >>> com.xueersi.parentsmeeting <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    r0 00000000  r1 00000000  r2 00000000  r3 cdde0dcc
    r4 ec809d70  r5 00000000  r6 00000000  r7 cdde0db0
    r8 00000000  r9 cf815400  sl cdde0ee0  fp cdde0e6c
    ip 0000deec  sp cdde0da0  lr d2929073  pc d2927188  cpsr 600e0030
    d0  6f635f4d465b206e  d1  6f72662073657566
    d2  0000000000000069  d3  0000000000000067
    d4  f33bef8000000001  d5  00001362cdde0f28
    d6  f33beda7cdde0fdc  d7  f33bef8000000001
    d8  0000000000000000  d9  0000000000000000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 2e74736973726570  d17 2e6761742e676f6c
    d18 f33d3fc1f33d3f31  d19 f33d40e1f33d4051
    d20 f33d35f1f33d3591  d21 f33d36b1f33d3651
    d22 ffffffe1ffffffe1  d23 ffffffe1ffffffe1
    d24 ffffffe1ffffffe1  d25 ffffffe1ffffffe1
    d26 0000210000000100  d27 0000610000004100
    d28 0000000000000000  d29 0000000000000000
    d30 05f4825d00001876  d31 0000000000000000
    scr 60000093

backtrace:
    #00 pc 00014188  /data/app/com.xueersi.parentsmeeting-nJF_IrIR8-d6GmICXA0D9w==/lib/arm/libmmkv.so
    #01 pc 0001606f  /data/app/com.xueersi.parentsmeeting-nJF_IrIR8-d6GmICXA0D9w==/lib/arm/libmmkv.so
    #02 pc 000fd2b3  /data/app/com.xueersi.parentsmeeting-nJF_IrIR8-d6GmICXA0D9w==/oat/arm/base.odex (offset 0xfd000)

stack:
         cdde0d60  cdce3000
         cdde0d64  cdde0dd0
         cdde0d68  b36e58ca
         cdde0d6c  ec83b380  [anon:libc_malloc]
         cdde0d70  ec809d7c  [anon:libc_malloc]
         cdde0d74  00000000
         cdde0d78  cdde0db0
         cdde0d7c  00000000
         cdde0d80  cf815400  [anon:libc_malloc]
         cdde0d84  cdde0ee0
         cdde0d88  cdde0e6c
         cdde0d8c  d292fbe1  /data/app/com.xueersi.parentsmeeting-nJF_IrIR8-d6GmICXA0D9w==/lib/arm/libmmkv.so
         cdde0d90  f3b26690  /system/lib/libc.so
         cdde0d94  00000003
         cdde0d98  cdde0db0
         cdde0d9c  f3ace779  /system/lib/libc.so (lrand48+12)
    #00  cdde0da0  00000000
         cdde0da4  ec809d70  [anon:libc_malloc]
         cdde0da8  ec809d7c  [anon:libc_malloc]
         cdde0dac  00000000
         cdde0db0  cdde0de8
         cdde0db4  d2929073  /data/app/com.xueersi.parentsmeeting-nJF_IrIR8-d6GmICXA0D9w==/lib/arm/libmmkv.so
    #01  cdde0db8  00000001
         cdde0dbc  ec809d7d  [anon:libc_malloc]
         cdde0dc0  b36e58ca
         cdde0dc4  cf962140  [anon:libc_malloc]
         cdde0dc8  ec83b380  [anon:libc_malloc]
         cdde0dcc  25197c30  /dev/ashmem/dalvik-main space (region space) (deleted)
         cdde0dd0  3b746a5a  /dev/ashmem/dalvik-main space (region space) (deleted)
         cdde0dd4  1287a59c
         cdde0dd8  21824abb  /dev/ashmem/dalvik-main space (region space) (deleted)
         cdde0ddc  b36e58ca
         cdde0de0  f46c675c  /dev/ashmem/dalvik-LinearAlloc (deleted)
         cdde0de4  00000001
         cdde0de8  cdde10c8
         cdde0dec  d328a2b5  /data/app/com.xueersi.parentsmeeting-nJF_IrIR8-d6GmICXA0D9w==/oat/arm/base.odex
    #02  cdde0df0  f46c675c  /dev/ashmem/dalvik-LinearAlloc (deleted)
         cdde0df4  00000000
         cdde0df8  00000001
         cdde0dfc  13d000c8  /dev/ashmem/dalvik-main space (region space) (deleted)
         cdde0e00  00000000
         cdde0e04  00000000
         cdde0e08  00000000
         cdde0e0c  00000000
         cdde0e10  00000000
         cdde0e14  00000000
         cdde0e18  00000000
         cdde0e1c  00000000
         cdde0e20  00000000
         cdde0e24  00000000
         cdde0e28  00000000
         cdde0e2c  00000000
### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
As has been told in the issue template, a crash issue **without logs** will be ignored & closed in a week.

You should provide logs, and symbolized your crash stack.

**Comment by e53179** [comment]
> 正如问题模板中所述，**没有日志**的崩溃问题将在一周内被忽略并关闭。
> 
> 您应该提供日志，并符号化您的崩溃堆栈。

Just the logs from these users' phones, no more logs

**Comment by lingol** [comment]
No logs no investigation.

**Comment by lingol** [comment]
Closed due to inactive.
