### ISSUE TITLE
Can i read properly a not encrypted data in my old version app with a not encrypted initailized mmkv from my new version app with a encrypted initailized mmkv.

### ISSUE THREAD

**Issue by halohoop** [Tencent/MMKV#725]
## Note:
> com.tencent.mmkv.MMKV#mmkvWithID(String mmapID, int mode)
> com.tencent.mmkv.MMKV#mmkvWithID(String mmapID, int mode, @Nullable String cryptKey)

### The language of MMKV

> Kotlin

### The version of MMKV

> v1.2.8

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

> 上一个版本没有加密，但是新版中调用了加密，旧版数据还能够正确的读取嘛？
> 
> com.tencent.mmkv.MMKV#mmkvWithID(String mmapID, int mode)
> com.tencent.mmkv.MMKV#mmkvWithID(String mmapID, int mode, @Nullable String cryptKey)
> Can i read properly a not encrypted data in my old version app with a not encrypted initailized mmkv from my new version app with a encrypted initailized mmkv.

**Comment by lingol** [comment]
`MMKV.reKey()`
https://javadoc.io/static/com.tencent/mmkv/1.2.10/com/tencent/mmkv/MMKV.html#reKey(java.lang.String)

**Comment by halohoop** [comment]
bravo～
