### ISSUE TITLE
kv.getBoolean  always is false

### ISSUE THREAD

**Issue by iamdennisme** [Tencent/MMKV#728]
## Note:
 abstract class BaseApplication : Application() {

    override fun attachBaseContext(base: Context?) {
        super.attachBaseContext(base)
    }

    override fun onCreate() {
        super.onCreate()
        MMKV.initialize(context)
        val kv =MMKV.mmkvWithID(getMMapId(), MMKV.MULTI_PROCESS_MODE)
        val result =kv.getBoolean(KEY_IS_PRIVACY_POLICY_SHOWN)
    }
}

### The version of MMKV
       1.2.10
> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

maven

### What's the issue?
  
 resultI always is false on some mobile phones

**Comment by lingol** [comment]
I can see no place in your code storing any value inside. So what are you complaining about?
