### ISSUE TITLE
这样配置初始化失败

### ISSUE THREAD

**Issue by holmesfork** [Tencent/MMKV#730]
![image](https://user-images.githubusercontent.com/26991267/127836493-5ed0580f-60a5-4f2d-865c-0e8a15b71e68.png)

**Comment by lingol** [comment]
You have to use specific NDK to build from sources to support the **armeabi** arch.
https://github.com/Tencent/MMKV/wiki/android_setup_cn#%E5%AE%89%E8%A3%85%E5%BC%95%E5%85%A5
