### ISSUE TITLE
Android 11系统调用MMKV::initializeMMKV闪退，该问题必现

### ISSUE THREAD

**Issue by hyb1234hi** [Tencent/MMKV#736]
Android 11系统调用MMKV::initializeMMKV闪退，该问题必现，Android 10系统不会报错，因为是so库导入了静态库，所以只有一个和pthread_once有关的错误

**Comment by lingol** [comment]
What? I don't understand your question. 
PS: There're millions of people out there using MMKV in Android 11 with no problem. I don't think your question is MMKV's problem.

**Comment by hyb1234hi** [comment]
下面是我上传的工程,因为项目的原因，NDK引用的是MMKV里面编译的libcore.a，Android 11必闪退，您帮忙看下，是不是我工程编译或者配置的原因
[test_cpphttplib_for_app_on_android.zip](https://github.com/Tencent/MMKV/files/6965572/test_cpphttplib_for_app_on_android.zip)

**Comment by lingol** [comment]
I have take a look in your project. Here's the big question: what are you trying to do? 
Why not just use MMKV's Java interface??

**Comment by hyb1234hi** [comment]
您好，为了安全性，我有一些数据需要封装在NDK里进行数据保存

**Comment by lingol** [comment]
We don't officially support using MMKV in NDK lib directly. Use it at your own risk.
