### ISSUE TITLE
清空key 无效。怎么处理

### ISSUE THREAD

**Issue by twlk-jzy** [Tencent/MMKV#741]
MMKV.MULTI_PROCESS_MODE  使用的是这个模式。清除所有的key无效

MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE,null).clearAll()

**Comment by twlk-jzy** [comment]
请问下怎么解决. 谢谢

**Comment by lingol** [comment]
One possibility is that someone else has store new values inside after you call `clearAll`. You could set breakpoints to verify that.
By the way, you should always provide **logs of MMKV** when complaining about something.
