### ISSUE TITLE
MMKV是怎么保证线程安全的呢？

### ISSUE THREAD

**Issue by wakakajp** [Tencent/MMKV#746]
MMKV是怎么保证线程安全的呢？如果是使用锁，我在主线程调用MMKV的API，是否有可能导致跟NSUserDefaults同样的问题，阻塞住主线程呢？

**Comment by lingol** [comment]
How can one guarantee thread safety without using thread-locks? Of cause MMKV uses thread-lock.
But you don't have to worry about that because MMKV's operation is **very, very fast** most of the time. That means you don't have to wait for a child thread's operation in most cases.

**Comment by wakakajp** [comment]
thx
