### ISSUE TITLE
mmap: fail to open: xx, Operation not permitted

### ISSUE THREAD

**Issue by wakakajp** [Tencent/MMKV#753]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV
>Objective-C

### The version of MMKV
> e.g. v1.2.7

### The platform of MMKV
>iOS

### The installation of MMKV
> Cocoapods

### What's the issue?
由于特殊的原因，需要在某个分类的+（void)load中调用了[MMKV initializeMMKV:nil] 并使用 mmkvWithID初始了一个实例，使用的默认路径，保存某个值，之后，只要是使用默认路径初始化的实例，都无法生成沙盒文件，并有Operation not permitted报错。使用非默认路径生成的实例能正常运行。
创建新工程没有复现该现象

### What's the log of MMKV when that happened?
[D] <libMMKV.mm:670::+[MMKV mmapKeyWithMMapID:rootPath:]> mmapKey: mmkv.default
[E] <MemoryFile.cpp:139::reloadFromFile> fail to open:/mmkv.default, Operation not permitted
[E] <MemoryFile.cpp:139::reloadFromFile> fail to open:/mmkv.default.crc, Operation not permitted
[E] <MemoryFile.cpp:139::reloadFromFile> fail to open:/mmkv.default, Operation not permitted
[E] <MMKV_IO.cpp:74::loadFromFile> file [/mmkv.default] not valid

**Comment by lingol** [comment]
The root dir of MMKV is not properly set. 
You should never initialize MMKV in `+load`. You should manually initialize MMKV after `didFinishLaunch`.

**Comment by wakakajp** [comment]
Is there a way to set the root dir properly?
Also called initialize in +load, my demo is OK,
please teach me.

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/iOS_tutorial

**Comment by wakakajp** [comment]
If I need add switcher to control a feature which code in +load， cannot use MMKV?
Will there be a improvement in the future?
Or this is not an application scenario of MMKV？

**Comment by lingol** [comment]
I won't repeat myself.
