### ISSUE TITLE
Android MMKV 支持像 共享SharedPreference 一样的功能么

### ISSUE THREAD

**Issue by Jack1995** [Tencent/MMKV#77]
### The language of MMKV

> Java & Kotlin

### The version of MMKV

> v1.0.10

### The platform of MMKV

> Android

### The installation of MMKV

> Git clone

### What's the issue?
不知道MMKV 是否支持 共享SharedPreference?
eg. A App 想要访问 B App 的数据

**Comment by lingol** [comment]
Duplicate with #40
