### ISSUE TITLE
Android：mmkv多进程模式下decodeParcelable获取一个未存储的key出现异常

### ISSUE THREAD

**Issue by SMCXU** [Tencent/MMKV#782]
### The language of MMKV
 Java

### The version of MMKV

v1.2.11

### The platform of MMKV

 Android

### What's the issue?
1.mmkv多进程模式
2.mmkv.encode("bo", mStr2)；mStr2是String类型json串 “{\"access_token\":\"5MwvSVPujdrIupszQ2OWJI\",\"appleSocialBinding\":false,\"avatar\":\""}

3.mmkv.decodeParcelable("bo", PersonBean.class, null);PersonBean实现了Parcelable
4.正常情况下获取不到数据，但是实际上获取到了一个对象，并且对象的一个int类型属性的值是时间戳
![WechatIMG94](https://user-images.githubusercontent.com/31235189/140681034-9e4fa7df-884f-4d50-841b-4dd46dd9b2b5.png)

**Comment by SMCXU** [comment]
以下是我的javabean
`public class PersonBean implements Parcelable {
    private String name;
    public int age;


    public PersonBean() {
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }


    protected PersonBean(Parcel in) {
        name = in.readString();
        age = in.readInt();
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(name);
        dest.writeInt(age);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final Creator<PersonBean> CREATOR = new Creator<PersonBean>() {
        @Override
        public PersonBean createFromParcel(Parcel in) {
            return new PersonBean(in);
        }

        @Override
        public PersonBean[] newArray(int size) {
            return new PersonBean[size];
        }
    };
}`

**Comment by SMCXU** [comment]
请帮忙处理一下，谢谢

**Comment by lingol** [comment]
What do you expect from MMKV? 
You cannot encode one type and decode with another type. MMKV does type eraser on encoding, therefore it's impossible for MMKV to check types on decoding.

**Comment by SMCXU** [comment]
之前的想法是两种类型都存在，Parcelable查不到了再查String,现在看来需要改变一下思路了

**Comment by SMCXU** [comment]
> What do you expect from MMKV? You cannot encode one type and decode with another type. MMKV does type eraser on encoding, therefore it's impossible for MMKV to check types on decoding.

谢谢

**Comment by SMCXU** [comment]
请问什么原因呀，如果我想继续这么做，需要做些什么？

**Comment by SMCXU** [comment]
还是上边的场景，另一个json和javabean,有的会出现OOM

**Comment by lingol** [comment]
> 还是上边的场景，另一个json和javabean,有的时候会出现OOM，是同一个原因吗

And the answer is still the same. First of all you should use the same type for encode and decode. Then we talk about OOM if it still exists.
