### ISSUE TITLE
MMKV.mmkvWithID(name, MMKV.MULTI_PROCESS_MODE) return null

### ISSUE THREAD

**Issue by yaoguangdong** [Tencent/MMKV#787]
## Note:
logs has lost. call this method again can fix it？

### The language of MMKV

> Java

### The version of MMKV

> e.g. v1.0.23
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

> MMKV.mmkvWithID(name, MMKV.MULTI_PROCESS_MODE) return null

### What's the log of MMKV when that happened?
> logs has lost

**Comment by lingol** [comment]
Upgrade to the latest version and collect as many logs as possible.
