### ISSUE TITLE
Fail to create an MMKV instance [xxxx] in JNI

### ISSUE THREAD

**Issue by bjhexn** [Tencent/MMKV#791]
Operation not permitted
Fail to create an MMKV instance [xxxx] in JNI
    java.lang.RuntimeException: Fail to create an MMKV instance [xxxx] in JNI
        at com.tencent.mmkv.MMKV.checkProcessMode(MMKV.java:470)
        at com.tencent.mmkv.MMKV.mmkvWithID(MMKV.java:375)

创建MMKV失败，出现这个崩溃。

**Comment by lingol** [comment]
That's simply too little info.

**Comment by bjhexn** [comment]
mmkv = MMKV.mmkvWithID(appId, MMKV.SINGLE_PROCESS_MODE, MMKV_CRYPT_KEY, getStoragePath(appId));

只是创建一个不支持跨进程的MMKV ，在android 11上模拟器上出现

**Comment by lingol** [comment]
Looks like you don't have access in the path `getStoragePath(appId)`. You might check about that.

**Comment by bjhexn** [comment]
OK
