### ISSUE TITLE
[Crash] Fail to create an MMKV instance [xxx] in JNI  in Android 11

### ISSUE THREAD

**Issue by bjhexn** [Tencent/MMKV#792]
[MMKV.java -> mmkvWithID:375]Fail to create an MMKV instance [xxx] in JNI
    java.lang.RuntimeException: Fail to create an MMKV instance [xxxx] in JNI
        at com.tencent.mmkv.MMKV.checkProcessMode(MMKV.java:470)
        at com.tencent.mmkv.MMKV.mmkvWithID(MMKV.java:375)
        at .storage.MiniAppStoreFactory.getMiniAppStore(MiniAppStoreFactory.java:27)
        at com..getMMKV(MiniAppWhiteListProvider.java:74)

在android 11 上创建 MMKV 发生上面的崩溃，使用的小米10 。  用mix2 android 10 上没有上面的崩溃
代码如下；
public static MMKV getMiniAppStore(String appId) {
        MMKV mmkv = store.get(appId);
        if (mmkv != null) {
            return mmkv;
        } else {
            mmkv = MMKV.mmkvWithID(appId, MMKV.SINGLE_PROCESS_MODE, MMKV_CRYPT_KEY, getStoragePath(appId));
            store.put(appId, mmkv);
            return mmkv;
        }
    }

**Comment by bjhexn** [comment]
使用MMKV 的版本：com.tencent:mmkv-static:1.2.10

**Comment by lingol** [comment]
Duplicated with #791. I believe I have told you what to do.

**Comment by bjhexn** [comment]
> Duplicated with #791. I believe I have told you what to do.

检查过了getStoragePath(appId) ， 这个返回值没有问题

**Comment by bjhexn** [comment]
> Duplicated with #791. I believe I have told you what to do.

什么情况会出现这个崩溃？同一个牌子的手机，现象不一样 。

**Comment by lingol** [comment]
> > Duplicated with #791. I believe I have told you what to do.
> 
> 检查过了getStoragePath(appId) ， 这个返回值没有问题

Why don't you provide logs of MMK? As the issue template has requested doing it.

**Comment by bjhexn** [comment]
什么意思？ 让我用模板重新提个BUG？

**Comment by lingol** [comment]
Provide **LOGS** of MMKV.

**Comment by bjhexn** [comment]
![image](https://user-images.githubusercontent.com/9999952/143417934-3ac6d993-f73a-4b6b-8e42-ca413e104ff2.png)

**Comment by bjhexn** [comment]
![image](https://user-images.githubusercontent.com/9999952/143418210-b54f67b6-c0e8-4f91-b964-bc5134221c84.png)

**Comment by lingol** [comment]
> ![image](https://user-images.githubusercontent.com/9999952/143418210-b54f67b6-c0e8-4f91-b964-bc5134221c84.png)

The log is crystal clear. Your app doesn't have permission to access that path. Just as I have suggested before.

And you STILL have to ask so many questions???

**Comment by bjhexn** [comment]
好吧，我也是才发现这行日志。辛苦了，多谢
