### ISSUE TITLE
mmkv 存储Json化的数据后，取出来的确是非json格式的数据，数据也出现错误

### ISSUE THREAD

**Issue by jiangmingliu** [Tencent/MMKV#795]
@lingol @Jonwei 
### The language of MMKV
> Java
### The version of MMKV
> e.g. v1.2.10  
### The platform of MMKV
> Android
### The installation of MMKV
> Maven
### What's the issue?
> Post the outputs or screenshots for errors.
关键日志如下所示：
2021127-19:38:8.726|6909|SharedPreferenceManager|1200101150|storage:KEY_TOTAL_CAL_FROM_DEVICE_FLAG_B8:8E:82:F4:1F:F0
2021127-19:38:8.726|6909|SharedPreferenceManager|1200101150|content:{"encryptType":1,"value":"U69S":1,"value"doneA\u003d\u003dR8dEb7v9oE9arYKEDS6o6juWUFHamVWz82Uyuyky9Nw\u003d"}
详细说明：
我们存入1个json后的1个对象(string)，该对象的字段只有2个，一个是int的encryptType，另外一个是string的value字段。
但是我们存入mmkv之后，我们取出来的值是上面日志显示的，是错误的。错误有两个地方，第一个地方是这个数据不是json格式的，第二个这个数据也出现了错乱，有两个value字段了。

详细说明下：我们存入mmkv这个key为KEY_TOTAL_CAL_FROM_DEVICE_FLAG_B8:8E:82:F4:1F:F0的数据的代码过程是这样的：
1. 业务调用的接口大概类似这样putString(String key, String value);
2. 这个接口的内部实现是这样的：先讲value值进行加密，然后将该value值写入某个数据结构SharedPreferenceModel的value字段，该数据结构有2个字段，一个是int的encryptType，另外一个是string的value字段；
3. 将数据结构用Gson转化为string对象；
4. 将string对象用mmkv存入。
片段代码大概是这样。
```
try {
            MMKV kv = MMKV.mmkvWithID(moduleId);
            String content = kv.getString(storage, "");
            SharedPreferenceModel data;

            // 还没有创建的数据直接创建
            if (TextUtils.isEmpty(content)) {
                data = new SharedPreferenceModel();
                createModel(value, storageParams, data);
            } else {
                data = new Gson().fromJson(content, SharedPreferenceModel.class);
                if (data == null) {
                    return ErrorConstants.UNKNOWN_ERROR;
                } else {
                    // 如果更新的参数和上一次更新的参数不一致，需要报错
                    if (storageParams == null && data.getEncryptType() != DataType.DATA_NOT_ENCRYPT) {
                        return ErrorConstants.PARAMS_ERROR;
                    }
                    if (storageParams != null && storageParams.getDataType() != data.getEncryptType()) {
                        return ErrorConstants.PARAMS_ERROR;
                    }
                    setValue(value, data);
                }
            }
            kv.putString(storage, new Gson().toJson(data));
            return ErrorConstants.SUCCESS;
        } 
```
### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
You are making things unnecessarily complicated. Here's how you should track down this issue the right way:
1. Print the result of `new Gson().toJson(data)` before putting it into MMKV.
2. Call `MMKV.putString()`.
3. Call `MMKV.getString()` immediately, print the result, check if it's the same as the one you print in step 1.

**Comment by jiangmingliu** [comment]
1.  这个问题是我们商用的用户反馈上来的，非常不好复现，关于同样的操作，我们已经打桩测试了100W次，都没有出现。
2. 我想问的是，您有什么怀疑点可以提供给我们参考下么？
3. 使用mmkv之前我们，我们同样也是有json转化，但是还是使用的是原生的sharedpreference，没有此问题的出现，使用了mmkv之后，这个问题小概率出现了。

**Comment by lingol** [comment]
> You are making things unnecessarily complicated. Here's how you should track down this issue the right way:
> 
> 1. Print the result of `new Gson().toJson(data)` before putting it into MMKV.
> 2. Call `MMKV.putString()`.
> 3. Call `MMKV.getString()` immediately, print the result, check if it's the same as the one you print in step 1.

That will be all. Come back later if you can reproduce this error.

**Comment by jiangmingliu** [comment]
come on buddy，it's really hard to reproduce this error. i have tried 1million times as i said above

**Comment by lingol** [comment]
OK. There are two possible things you might check out. But first of all, you should **collect logs of MMKV** in your **distribution build**, if you haven't done so.
1. Is it possible that someone/someplace else use the same mmap ID in multi-process? If that's the case, the file will normally corrupt than be read & decode a value like you posted. In this case, you will see MMKV's corruption through logs of MMKV.
2. Is it possible that someone/someplace see use the same key and store some invalid value?

**Comment by lingol** [comment]
Also, the '\u003d' in your post makes me wonder. A little Google search suggests that it's some HTML encoding. You should turn it off to get a clear look into those bad cases. https://stackoverflow.com/questions/16558709/gson-issue-with-string
```java
Gson gson = new GsonBuilder().disableHtmlEscaping().create();
String s2 = gson.toJson(hm.toString());
```

**Comment by lingol** [comment]
The less of your 'invalid' value, aka 'R8dEb7v9oE9arYKEDS6o6juWUFHamVWz82Uyuyky9Nw', looks like a **base64 encoded string** to me. You might check on that clue.

**Comment by jiangmingliu** [comment]
many thanks for your advices, i will tried after.

**Comment by lingol** [comment]
Any updates yet?

**Comment by lingol** [comment]
Closed due to inactive.
