### ISSUE TITLE
mmkv 数据异常被清

### ISSUE THREAD

**Issue by diaoling90** [Tencent/MMKV#796]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

>Java, Kotlin

### The version of MMKV

> v1.2.11  

### The platform of MMKV

> Android

### The installation of MMKV

>  Maven

### What's the issue?

> 项目中使用了 MMKV ；发现有以下问题：
        1、MMKV.defaultMMKV() 的方式存储数据，存在 约4%的概率，数据被清除掉了，存储过的数据，key都被清除了
        2、MMKV.mmkvWithID("")的方式存储数据，存在 约0.15%的概率，数据被清除掉了，存储过的数据，key都被清除了
    我们的使用方式：
        1、使用的都是 默认的 单进程模式：SINGLE_PROCESS_MODE
        2、我们存在 多个进程使用 MMKV.defaultMMKV() 的情况，使用的模式都是单进程模式 SINGLE_PROCESS_MODE
        3、MMKV.mmkvWithID("") 的使用方式，只在单进程中使用，使用的单进程模式：SINGLE_PROCESS_MODE
        4、我们的业务代码是没有清除数据的操作的
    问题：
        1、有什么情况，或者发生了什么问题，才有可能数据被清除？
        2、MMKV.mmkvWithID("") 只在单进程使用，为啥会有发生数据清除现象

**Comment by lingol** [comment]
Whenever an MMKV is used in multi-process, it should be opened with MULTI_PROCESS_MODE, including the default instance.
