### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by wangwei66666** [Tencent/MMKV#798]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

>  Java

报错信息：
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: couldn't map "/mnt/asec/com.asiainno.uplive-2/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libmmkv.so" segment 1: Permission denied

### The version of MMKV

> e.g. v1.2.10 
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
>Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: couldn't map "/mnt/asec/com.asiainno.uplive-2/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libmmkv.so" segment 1: Permission denied

Just do a little Google about it and you will know exactly what went wrong. Why bother to complain about it here?
https://github.com/android/ndk/issues/979

**Comment by lingol** [comment]
The search keyword is "_dlopen failed: couldn't map_", by the way.

**Comment by wangwei66666** [comment]
I have filled in the wrong information. Please have a look

**Comment by lingol** [comment]
> > Fatal Exception: java.lang.UnsatisfiedLinkError
> > dlopen failed: couldn't map "/mnt/asec/com.asiainno.uplive-2/split_config.armeabi_v7a.apk!/lib/armeabi-v7a/libmmkv.so" segment 1: Permission denied
> 
> Just do a little Google about it and you will know exactly what went wrong. Why bother to complain about it here? [android/ndk#979](https://github.com/android/ndk/issues/979)

Did you not see this answer?
