### ISSUE TITLE
MMKV.mmkvWithID SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by pouloghost** [Tencent/MMKV#80]
### The language of MMKV

> Java

### The version of MMKV

> v1.0.10

### The platform of MMKV

> Android

### The installation of MMKV

>  Maven

### What's the issue?

![image](https://user-images.githubusercontent.com/5670459/46936441-fc350000-d090-11e8-8d15-ef78b896c11e.png)

**Comment by lingol** [comment]
Have you call MMKV.initialize() before calling any method?
