### ISSUE TITLE
打包到64位机器上报错

### ISSUE THREAD

**Issue by HeaYu** [Tencent/MMKV#800]
libmmkv.so is 32-bit instead of 64-bit，版本1.2.7，请问下这个该如何解决呢？

**Comment by lingol** [comment]
MMKV supports arm64. It's your packing tools or your ide you should check.

**Comment by HeaYu** [comment]
想咨询一个问题，libmmkv.so是装到lib/arm下的，但是预装系统会去找lib/arm64，这个有没有什么好的解决方案呢？
