### ISSUE TITLE
mmapID 如何迁移

### ISSUE THREAD

**Issue by trycatchx** [Tencent/MMKV#803]
如何获取指定 mmapID 所有的值，并迁移到另一个 mmapID ？

**Comment by lingol** [comment]
We don't support `getAll()`. Thus it's hard if not impossible to migrate one MMKV into another.
However, you can backup & restore an MMKV if that's what you ask.

**Comment by trycatchx** [comment]
@lingol  备份和恢复 ，能否变相修改了 mmapID_A - > mmapID_B？

**Comment by lingol** [comment]
That‘s correct.
