### ISSUE TITLE
加密疑问

### ISSUE THREAD

**Issue by trycatchx** [Tencent/MMKV#804]
如何一键 reKey 所有的 mmapid ？并且通过一个 versionCode 来控制？如果无法一键 rekey ，那么我需要设置多个 versionCode 对应不同的 mmapid 版本状态？

**Comment by lingol** [comment]
MMKV doesn't know how many instances are actually out there on the disk until you get one. So there's no such thing as one click to reKey() all, simply impossible.

**Comment by trycatchx** [comment]
Thx ，i got it
