### ISSUE TITLE
MMKV.mmkvWithID时发生java.lang.ClassCastException异常:

### ISSUE THREAD

**Issue by wonderfulzyt** [Tencent/MMKV#805]
## MMKV.mmkvWithID时发生java.lang.ClassCastException异常:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV
> Java

### What's the issue?

异常栈信息如下：
java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
	at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1831)
	at java.util.HashMap$TreeNode.putTreeVal(HashMap.java:2011)
	at java.util.HashMap.putVal(HashMap.java:637)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at com.tencent.mmkv.MMKV.checkProcessMode(MMKV.java:286)
	at com.tencent.mmkv.MMKV.mmkvWithID(MMKV.java:168)

**Comment by lingol** [comment]
Post call stacks of all threads please.

**Comment by lingol** [comment]
And provide your **version** of MMKV.

**Comment by lingol** [comment]
In fact, why not just follow the issue template and provide all the info we requested there?

**Comment by wonderfulzyt** [comment]
Already resolved，thanks, because the project has used an old version；Thanks again The new version uses synchronized 
synchronized (checkedHandleSet) {
            if (!checkedHandleSet.contains(handle)) {
                if (!checkProcessMode(handle)) {
                    String message;
                    if (mode == SINGLE_PROCESS_MODE) {
                        message = "Opening a multi-process MMKV instance [" + mmapID + "] with SINGLE_PROCESS_MODE!";
                    } else {
                        message = "Opening an MMKV instance [" + mmapID + "] with MULTI_PROCESS_MODE, ";
                        message += "while it's already been opened with SINGLE_PROCESS_MODE by someone somewhere else!";
                    }
                    throw new IllegalArgumentException(message);
                }
                checkedHandleSet.add(handle);
            }
        }
