### ISSUE TITLE
备份恢复问题

### ISSUE THREAD

**Issue by trycatchx** [Tencent/MMKV#806]
使用 backupAllToDirectory 是备份所有存在 sdcrad 中的 mmapid ?
如果是，那么获取备份目录的数据通过以下方式：
目前获取不到 XX  对应的 value？
```
 val mmkv = MMKV.mmkvWithID(MmkvConst.xx, MmkvConst.backDir)
mmkv.decodeInt(XX)
```

**Comment by lingol** [comment]
No. You have to restore it from backup directory to MMKV root directory, then you can call `MMKV.mmkvWithID(MmkvConst.xx)`.
