### ISSUE TITLE
How to check the type of value by key

### ISSUE THREAD

**Issue by trycatchx** [Tencent/MMKV#807]
How to check the type of value by key ：
eg:
```
public object encode(String key) {
  // xxx
}

or 
public Class<?> check(String key) {
  // xxx
}
```

**Comment by lingol** [comment]
In theory, you can't. You should know the type of key before decoding/getting its value.
In practice, there is some workaround out there. Though none of them promise correctness 100%.

**Comment by lingol** [comment]
Search this repo's issue with the keyword `getAll()` will give you some workaround.

**Comment by trycatchx** [comment]
why not provider getAll() method? like  preferences.getAll()  and return object?

**Comment by lingol** [comment]
> Search this repo's issue with the keyword `getAll()` will give you some workaround.

And the answer will still be the same. Search before you ask.
