### ISSUE TITLE
从mmkv迁移回sp的方式

### ISSUE THREAD

**Issue by Eric-Li-2356** [Tencent/MMKV#809]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV
Java

### The version of MMKV
1.2.11

### The platform of MMKV
Android

### The installation of MMKV
Maven

### What's the issue?
问下是否能增加从mmkv迁移回sp的api，目前只有从sp迁移到mmkv的api

**Comment by lingol** [comment]
It's impossible. Not that we don't want to support backward migration. 
Search this repo's issue with `getAll()` and you will know why.
