### ISSUE TITLE
the way to cause truncatedMessage

### ISSUE THREAD

**Issue by easternHong** [Tencent/MMKV#810]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

>  Java, or Kotlin

### The version of MMKV
> mmkv_version=1.2.11

### The platform of MMKV
>  Android

### What's the issue?
val instance = MMKV.mmkvWithID("default_mmkv", MMKV.MULTI_PROCESS_MODE)
instance.putString("xxx", "aa"); // 
instance.putString("xxx", "aa"); //second time

easy to  cause *truncatedMessage*

**Comment by lingol** [comment]
Since you said **easy**, would you provide a demo project that can easily **reproduce** this issue?

**Comment by lingol** [comment]
Yes?

**Comment by lingol** [comment]
Close due to inactive. Looks like it's not that easy to corrupt it.
