### ISSUE TITLE
mmkv是否存在Android Studio的插件用于查看数据

### ISSUE THREAD

**Issue by Eric-Li-2356** [Tencent/MMKV#812]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

Java

### The version of MMKV

v1.2.11  

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?
mmkv是否存在像 用于查看sqlite数据的“Database Inspector”或“DB Browser”，这样的Android Studio插件。现在要查看mmkv的数据要么代码遍历，要么文件导出来用010Editor手动分析，不是很便利。

**Comment by lingol** [comment]
Search this repo's issues with the keyword `getAll()` and you will know why **it's hard if not impossible**.
