### ISSUE TITLE
libmmkv.so 0000f594 signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8  /lib/arm/libmmkv.so

### ISSUE THREAD

**Issue by huagbo** [Tencent/MMKV#813]
### The language of MMKV
 
Kotlin、 java

### The version of MMKV
 v1.2.2  

### The platform of MMKV

Android

### The installation of MMKV

 Maven

### What's the issue?

![image](https://user-images.githubusercontent.com/8190482/148078560-5f5612a3-ae03-4226-a33e-b49384b2cf29.png)

**Comment by lingol** [comment]
That version is simply too old. Upgrade to the latest version. Come back if this crash still happens.
