### ISSUE TITLE
MMKV.clear()   SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by Huang0424** [Tencent/MMKV#815]
#00 pc 00017dba /data/app/com.maiyawx.oa-c7cZadHB9ZLIe6aYRoHRWg==/lib/arm/libmmkv.so [armeabi-v7a::c62d5b3d84e01fdc9ea943ff379d3881]
2
#01 pc 0001932b /data/app/com.maiyawx.oa-c7cZadHB9ZLIe6aYRoHRWg==/lib/arm/libmmkv.so [armeabi-v7a::c62d5b3d84e01fdc9ea943ff379d3881]
3
#02 pc 000645d3 /data/app/com.maiyawx.oa-c7cZadHB9ZLIe6aYRoHRWg==/oat/arm/base.odex (oatexec+1491) [armeabi::5372eee7bd18cc4a49061ba3a15a3fc6]
4
java:
5
com.tencent.mmkv.MMKV.clear(MMKV.java:1075)
6
com.tencent.qcloud.tuicore.net.UserHelper.clear(UserHelper.java:148)
7
com.maiyawx.oa.MainApplication.logout(MainApplication.java:276)
8
com.maiyawx.oa.pages.HomePageActivity.eventLogout(HomePageActivity.java:360)
9
java.lang.reflect.Method.invoke(Native Method)
10
org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:517)
11
org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:511)
12
org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
13
android.os.Handler.dispatchMessage(Handler.java:106)
14
android.os.Looper.loop(Looper.java:164)
15
android.app.ActivityThread.main(ActivityThread.java:6606)
16
java.lang.reflect.Method.invoke(Native Method)
17
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
18
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

**Comment by lingol** [comment]
You have miss almost every thing. We have make it clear in the issue template. Provide as much information as possible.

**Comment by Huang0424** [comment]
......Okay, I'll close it first, and I'll add it later

**Comment by Huang0424** [comment]
Okay, I'll close it first, and I'll add it later
