### ISSUE TITLE
疑似crash

### ISSUE THREAD

**Issue by DotaAntiMagic** [Tencent/MMKV#819]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin
Objective-C

### The version of MMKV
  - MMKV (1.2.7):
    - MMKVCore (~> 1.2.7)
  - MMKVCore (1.2.7)

### The platform of MMKV

> e.g. iOS or Android
iOS

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone
Cocoapods

我们的app在didFinishLaunchingWithOptions中初始化mmkv,初始化的代码为[MMKV initializeMMKV:nil];但是在bugly上发现有几个疑似跟C挂钩的崩溃,都是一启动就崩溃,现在也不太清楚是什么原因导致的,麻烦大神看下：
![image](https://user-images.githubusercontent.com/13567812/150091014-76d9ede2-67e9-458e-8e97-865a5ec7a81c.png)

![image](https://user-images.githubusercontent.com/13567812/150090049-14621798-77ec-4b50-a525-bf840375c1cc.png)
![image](https://user-images.githubusercontent.com/13567812/150090556-7a8620c9-5fa6-40bf-80e9-244504ea7470.png)
![image](https://user-images.githubusercontent.com/13567812/150090608-76aac3ae-4b25-4f3f-a478-d65739e9ab42.png)
![image](https://user-images.githubusercontent.com/13567812/150090752-be917bbb-6a37-4bc1-992b-9d53c680ce85.png)

**Comment by lingol** [comment]
There's absolutely no evidence link to MMKV. Please don't spam here.
