### ISSUE TITLE
Support for macOS?

### ISSUE THREAD

**Issue by Channe** [Tencent/MMKV#82]
[!] The platform of the target `TestOfMacOS` (macOS 10.13) is not compatible with `MMKV (1.0.10)`, which does not support `osx`.

如果macOS App是单进程模式，MMKV现在能支持吗？

**Comment by lingol** [comment]
v1.0.11 supports macOS. Try it.

**Comment by Channe** [comment]
> v1.0.11 supports macOS. Try it.

pod install
Analyzing dependencies
[!] The platform of the target `TestOfMacOS` (macOS 10.13) is not compatible with `MMKV (1.0.11)`, which does not support `osx`.

**Comment by lingol** [comment]
There's some error in the PodFile of MMKV. Will fix soon.

**Comment by lingol** [comment]
Fixed with #83 . Try again.

**Comment by dongyuwei** [comment]
From the readme.md:
> It's currently available on both iOS and Android.
Document is't updated.

**Comment by lingol** [comment]
> From the readme.md:
> 
> > It's currently available on both iOS and Android.
> 
> Document is't updated.

Okey, will be updated soon.

**Comment by lingol** [comment]
> From the readme.md:
> 
> > It's currently available on both iOS and Android.
> 
> Document is't updated.

It's done.
