### ISSUE TITLE
安卓原生sp迁移数据到mmkv，数据不同步

### ISSUE THREAD

**Issue by curtiszp** [Tencent/MMKV#820]
## Note:
我们在Application的onCreate方法中调用importFromSharedPreferences方法进行数据的迁移，然后app进入闪屏页（SplashActivity），从MMKV中获取从sp迁移过来的json数据的时候，数据读取错误。所以我们怀疑两点：
1.importFromSharedPreferences的过程在子线程中进行，而我们在splashactivity的读取是在主线程，导致了数据还没有迁移完成就去读取了
2.另外一个怀疑的点就是数据迁移importFromSharedPreferences失败了，目前我们线上用户出现迁移数据失败的案例多么？

### The language of MMKV

 Java,  and Kotlin

### The version of MMKV
com.tencent:mmkv-static:1.2.9

### The platform of MMKV

 Android

### The installation of MMKV

com.tencent:mmkv-static:1.2.9

### What's the issue?
我们在Application的onCreate方法中调用importFromSharedPreferences方法进行数据的迁移，然后app进入闪屏页（SplashActivity），从MMKV中获取从sp迁移过来的json数据的时候，数据读取错误。所以我们怀疑两点：
1.importFromSharedPreferences的过程在子线程中进行，而我们在splashactivity的读取是在主线程，导致了数据还没有迁移完成就去读取了
2.另外一个怀疑的点就是数据迁移importFromSharedPreferences失败了，目前我们线上用户出现迁移数据失败的案例多么？

联系方式：15900537531 微信就是手机号 张鹏
                  15251769192 微信就是手机号 孙正堂

**Comment by lingol** [comment]
MMKV Doesn't lock the whole import operation. It's your responsibility to lock guard the import progress. Make sure it's finished before any reads in any other threads.

**Comment by curtiszp** [comment]
想问下mmkv本身自己从sp迁移数据的方法是在哪个线程做的，简单来说就是方法
 importFromSharedPreferences
 
是在哪个线程做的，谢啦
 
 
 
 
 

  -- 
 
 
 发自新浪邮箱客户端 
 
 
  
  在 1月22日 23:13，Guo Ling ***@***.***> 写道： 
   
  MMKV Doesn't lock the whole import operation. It's your responsibility to lock guard the import progress. Make sure it's finished before any reads in any other threads. 
  —
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
