### ISSUE TITLE
关于自定义根目录时mmkv文件命名错误

### ISSUE THREAD

**Issue by Eric-Li-2356** [Tencent/MMKV#822]
### The language of MMKV

Java

### The version of MMKV

v1.2.11

### The platform of MMKV

Android12，coloros12
手机：oppo findx3

### The installation of MMKV

Maven

### What's the issue?
根据https://github.com/Tencent/MMKV/wiki/android_advance_cn
的方法，
![image](https://user-images.githubusercontent.com/55909871/150672877-ce4b407b-eb18-440b-934f-0af793232a7e.png)
代码如下：
        
        String dir = getFilesDir().getAbsolutePath() + "/mmkv_2";
        String rootDir = MMKV.initialize(this, dir);
        Log.i(TAG, "mmkv root: " + rootDir);
        //1.自定义全部文件的根目录
        //第1个mmkv
        MMKV kv = MMKV.mmkvWithID("testCustomDir1");
        kv.encode("string", "Hello from mmkv");
        System.out.println("string: " + kv.decodeString("string"));
        kv.encode("bool", true);
        System.out.println("bool: " + kv.decodeBool("bool"));
        //第2个mmkv
        kv = MMKV.mmkvWithID("testCustomDir2");
        kv.encode("string", "Hello from mmkv");
        System.out.println("string: " + kv.decodeString("string"));
        kv.encode("bool", true);
        System.out.println("bool: " + kv.decodeBool("bool"));

        //2.自定义某个文件的根目录
        String relativePath = getFilesDir().getAbsolutePath() + "/mmkv_3";
        MMKV kv1 = MMKV.mmkvWithID("testCustomDir3", relativePath);
        kv1.encode("string", "Hello from mmkv");
        System.out.println("string: " + kv1.decodeString("string"));
        kv1.encode("bool", true);
        System.out.println("bool: " + kv1.decodeBool("bool"));

得到2中的mmkv文件为：
![image](https://user-images.githubusercontent.com/55909871/150673019-1f8fb06a-8853-4f68-99dd-db82149f2437.png)
而不是mmapID：testCustomDir3。

**Comment by lingol** [comment]
That's exactly the bug I mentioned in issue #821  earlier, what's your point?

**Comment by Eric-Li-2356** [comment]
ok，I got. Since it is the bug that cannot be solved right now, I will rename the files myself.
