### ISSUE TITLE
Maximal storage problems

### ISSUE THREAD

**Issue by HenrikZabel** [Tencent/MMKV#823]
Because I thought if WeChat uses MMKV to store messages for being able to use the app even if the user is offline I wanted to add this to my chat-app too. But I ran into an issue:

When writing massive Data (massive in ratio) like 300MB to the mmkv storage I have the problem that I cannot do this. It simply wont let me because this is too much data.

I searched for the maximum storage or so in the whole repository but I coulnd't find any limitations. Are there any? Would be nice if you let me know because otherwise I would have to look for an alternative for storing chat messages on the users device :)

**Comment by lingol** [comment]
NO. WeChat doesn't use MMKV to store messages. Check our FAQ on the wiki page for the storage limit of MMKV.

**Comment by lingol** [comment]
For storing large data such as chat history, we recommend [WCDB](https://github.com/Tencent/WCDB), which is also open-sourced by the WeChat team.

**Comment by HenrikZabel** [comment]
Is there any plan to make your libaries for react-native too?

**Comment by lingol** [comment]
There's already more than one RN wrapper out there, and some of them are quite good. 
I don't see the necessity to provide another one.

**Comment by HenrikZabel** [comment]
I am sorry, but I couldn't find any RN library for wcdb :/ Do you know any?

**Comment by lingol** [comment]
I thought you mean RN library for MMKV. 
Anyway, as for WCDB, you could just use any RN wrapper of SQLite instead.

**Comment by HenrikZabel** [comment]
Okay. Thank you very much ;) If my App is getting bigger I think I am going to switch to complete native code. Than I am going to use WCBD :) And I'll take a look on these rn mmkv libraries :)

**Comment by HenrikZabel** [comment]
@lingol Do you know any good and (very) fast Sqlite wrapper for React Native? There are a tons but often they are slow or outdated or so :/

**Comment by lingol** [comment]
I don't know that. And it's unrelative to this very repo.

**Comment by HenrikZabel** [comment]
Thank you anyways :)
