### ISSUE TITLE
FlutterPluginRegistrant 位置及“”问题

### ISSUE THREAD

**Issue by ForC-M** [Tencent/MMKV#824]
### The language of MMKV

> flutter

### The version of MMKV

> v1.2.12

### The platform of MMKV

> iOS

### The installation of MMKV

> Cocoapods

### What's the issue?

> flutter demo project， ”FlutterPluginRegistrant“ path is ‘.ios/flutter/FlutterPluginRegistrant/FlutterPluginRegistrant.podspec’ and FlutterPluginRegistrant content is dependce "mmkv"

### What's the log of MMKV when that happened?
>

**Comment by lingol** [comment]
I don't quite understand your question.

**Comment by ForC-M** [comment]
https://github.com/Tencent/MMKV/pull/825

**Comment by ForC-M** [comment]
pr 有说明，主要是路径和“”问题

**Comment by lingol** [comment]
And I also don't understand your PR.

**Comment by ForC-M** [comment]
In flutter engineering in MMKV FlutterPluginRegistrant path. The ios/flutter/FlutterPluginRegistrant/FlutterPluginRegistrant podspec, Don't understand the flutter/tool/mmkvpodhelper. Rb 'Runner' path is why in the script. And if vscode has ruby format, it will change "depend" to "depend", I can mention a new pr

**Comment by lingol** [comment]
Ah, maybe you should use Google translate or simply use your native language.

And what do you mean by saying that? Looks exactly the same to me.
>And if vscode has ruby format, it will change "depend" to "depend"

**Comment by ForC-M** [comment]
1. 为什么is_module则不修改FlutterPluginRegistrant.podspec，这样会导致podsepc中depend ‘mmkv’ not found
2. 使用string.sub，则要考虑depend “”和 depend ‘‘问题，因为ruby format工具会将‘’-》“”
