### ISSUE TITLE
Data lost?

### ISSUE THREAD

**Issue by panzhenglian** [Tencent/MMKV#826]
线上用户遇到丢数据特别多，最初是一个同事推荐使用的，开发过程中没遇到问题，但是上线之后丢数据很严重，导致线上产品严重bug，不建议使用。

**Comment by lingol** [comment]
You have made a serious judgment without looking for the reason. 
WeChat, the most used App in the whole world, uses MMKV without your so-called data lost.
In fact, most of the Apps in China, and a lot of other Apps oversea also use MMKV without that problem.

Why don't you look at your own usage and seek for an answer?

**Comment by lingol** [comment]
HOW DARE YOU.

**Comment by lingol** [comment]
A reasonable issue maker will provide Info such as the **version**, the **language**, the device **platform**, and most important of all the **logs of MMKV**.
And we will look into it together.
