### ISSUE TITLE
Default Value of `nullptr` for non-reference-type functions

### ISSUE THREAD

**Issue by mrousavy** [Tencent/MMKV#827]
### The language of MMKV

Objective-C and C++

### The version of MMKV

Current master

### The platform of MMKV

iOS and Android

### The installation of MMKV

Cocoapods and Git Submodule

### Question

The `getString(..)` function returns a `bool` value, where `true` means the key exists in storage and `false` means it doesn't.

I would love to have the same functionality for non-reference-type type functions, for example for the `getDouble(..)` or `getBoolean(..)`, and am proposing two APIs:

#### API 1

This is a **breaking change**, but would align with the `getString(..)` API.

```c++
// getString(...)
std::string result;
bool hasValue = instance->getString(keyName, result);
------
// getDouble(...)
double result;
bool hasValue = instance->getDouble(keyName, &result);
```

#### API 2

This is **non-breaking**, but uses a different API than the `getString(..)` function:

```c++
// getString(...)
std::string result;
bool hasValue = instance->getString(keyName, result);
------
// getDouble(...)
bool hasValue;
double result = instance->getDouble(keyName, &hasValue);
```

@lingol I would love to hear your thoughts on this, if you are in favor of implementing this functionality, let me know and maybe I can come up with a draft PR to kick things off. :)

**Comment by mrousavy** [comment]
The motivation for this is, that I want to know if a key doesn't exist yet, and a return value of `false` or `0.0` in this case is misleading, it should be `nullptr` or throw a "key not found" error (in my opinion). Also, with the current API, my only solution would be to add an additional `contains(..)` check, which I would like to avoid.

**Comment by lingol** [comment]
This proposal is legit. The second approach might be better for non-breaking change. 
You are very welcome to make such an improvement to this repo.

**Comment by mrousavy** [comment]
Do you want the `defaultValue` parameter to be removed and replaced by the new `hasValue` parameter?

**Comment by lingol** [comment]
No, the existing API should keep un-touch as much as possible.
