### ISSUE TITLE
1.1.1 版本anr

### ISSUE THREAD

**Issue by tianshaokai** [Tencent/MMKV#829]
at com.tencent.mmkv.MMKV.sync(Native Method)
com.tencent.mmkv.MMKV.commit(MMKV.java:1034) 
com.txxx.common.mmkv.MMKVUtils.putString(MMKVUtils.java:23)

**Comment by lingol** [comment]
You have missed almost everything we require in the issue template.

**Comment by lingol** [comment]
Anyway, as far as one may concern, you don't need to call `commit()`. MMKV doesn't rely on that to write data to disk. Just delete the call and you will be alright.
