### ISSUE TITLE
关于 Kotlin Multiplatform Mobile 的支持与合作

### ISSUE THREAD

**Issue by qiaoyuang** [Tencent/MMKV#834]
嗨，我们这边是携程机票研发团队。携程 app 去年开始使用 MMKV 作为 KV 存储框架，效果非常不错。我们机票团队的移动端代码使用了 KMM（Kotlin Multiplatform Mobile）技术，因此我们将 Android 与 iOS 的 MMKV 进行了包装，编写了一套可用于 KMM 的 Kotlin 版本的 API，并已经在线上运行接近半年稳定性良好，我们希望将其开源，我希望与你们这边取得联系并商讨开源的具体事宜，如果可以的话可以通过邮件联系我：qiaoyuang2012@gmail.com。万分感谢。

**Comment by lingol** [comment]
That's good to hear. I will contact you ASAP.

**Comment by lingol** [comment]
Hi there. So long. KMP experimental support just been added in the dev branch. Let me know if we have anything missing or need to improve.
