### ISSUE TITLE
对Android是否有统计日均crc校验不通过的次数

### ISSUE THREAD

**Issue by Eric-Li-2356** [Tencent/MMKV#835]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

Java

### The version of MMKV

v1.2.11

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?

问下对mmkv for Android是否有统计：日均多少次crc数据校验不通过？
在官网只看到ios有日均70w次校验不通过，没有Android的。
因为要技术评审以此作为是否采用mmkv的一个指标。

**Comment by lingol** [comment]
No such data, sorry. 
However, if it's good enough for WeChat, it's good enough for most apps I think.
