### ISSUE TITLE
请教下关于数据迁移时出错的处理方式

### ISSUE THREAD

**Issue by Eric-Li-2356** [Tencent/MMKV#843]
### The language of MMKV

> Java

### The version of MMKV

> v1.2.12

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

参考
https://github.com/Tencent/MMKV/issues/671
https://github.com/Tencent/MMKV/issues/174
决定在新版本app启动时，即Application的onCreate()中进行sp到mmkv的一次完整迁移，迁移代码暂定如下：
Application：
![image](https://user-images.githubusercontent.com/55909871/156907907-2a88a21a-2161-48ce-9bd4-54a0d4c5bdc5.png)
util：
![image](https://user-images.githubusercontent.com/55909871/156907890-348ffc1e-a0e6-4d93-a2b1-ea30ee2b7139.png)

之前第一次评审时，同事问如果迁移失败如何处理的问题，希望大佬给点已有经验的建议，thx！

**Comment by lingol** [comment]
I don't believe you will face an import error. However, if you must ask, the answer is: try again later.

**Comment by Eric-Li-2356** [comment]
thx. 我再思考下。
plus：昨天搜了下师兄也是中大的，应该也是东校的hh。
最新做mmkv有比较多问题要问师兄，麻烦你了。

**Comment by Eric-Li-2356** [comment]
迁移失败有可能是正在迁移时手机没电关机了，以及类似这种的异常情况。我先按大佬的try again later建议写，之后有问题再请教
