### ISSUE TITLE
Question: Ability to determine value type?

### ISSUE THREAD

**Issue by mrousavy** [Tencent/MMKV#848]
Sorry this is a question, not a bug report.

I have been investigating some alternative API solutions for my React Native wrapper around MMKV, and I tried to play around with automatically detecting the value type.

I've noticed that there is a function to get the value's size, but that doesn't accurately tell me the value's type, for example:

* The value `"1"` can be either a String, or a Boolean, since both have the same byte size (1)
* The value `"helloooo"` can be either a String, or a Double, since both have the same byte size (8)

I was wondering if MMKV maybe internally saves a flag for which type the value should be interpreted as, or do you leave this completely up to the user?

**Comment by lingol** [comment]
That value size method is primarily for users to know each key's consuming space. It's not for type information. In fact, MMKV does type-erase while encoding. Type info is erased by design.

**Comment by mrousavy** [comment]
Okay got it, thanks
