### ISSUE TITLE
fail to mlock crc [mmkv.default]-0x10ac34000, 12:Cannot allocate memory

### ISSUE THREAD

**Issue by gank0326** [Tencent/MMKV#85]
[[MMKV defaultMMKV] setFloat:newLocation.coordinate.latitude forKey:CCLastLatitude];

fail to mlock crc [mmkv.default]-0x10ac34000, 12:Cannot allocate memory

**Comment by lingol** [comment]
It seams that you are facing OOM. How big is you mmkv file?

**Comment by lingol** [comment]
Reboot your device and try again?

**Comment by gank0326** [comment]
Reboot device does not work![](url)

**Comment by gank0326** [comment]
![wechatimg1](https://user-images.githubusercontent.com/10110832/47000520-091e2600-d15b-11e8-9023-dd573255afbd.jpeg)

**Comment by lingol** [comment]
That's something new. Can you make a reproducible demo project and send it to me? guoling@tencent.com

**Comment by gank0326** [comment]
demo already send

**Comment by BinBear** [comment]
@gank0326 You are using version 1.0.10 . Version 1.0.10 is fine.
