### ISSUE TITLE
MMKV 造成主线程卡顿，是否可以用读写锁来优化

### ISSUE THREAD

**Issue by hellokent** [Tencent/MMKV#850]
### The language of MMKV
> Java

### The version of MMKV
> v1.2.10  

### The platform of MMKV
>  Android

### The installation of MMKV
> Gradle via maven repo

### What's the issue?
我们在线上检测卡顿的时候，发现有一定数量的卡顿是主线程调用 mmkv 的 get 和 set 操作导致的。

通过翻阅代码发现 mmkv 底层有一把 mutex 锁，锁住了所有的操作。所以我们想了解下是否有规划用读写锁代替 mutex 来提升并发性能；或者之前有过类似的尝试，但是出于某些原因没有用上读写锁。

**Comment by lingol** [comment]
You're targeting the wrong spot to fix. Even without your detail lag stacks, I highly suspect that it's **not the lock** but **the underlying IO operation** that causes the lag. The lock itself is irreverent.
Anyway, for further diagnosis, or more importantly for more **scientific** diagnosis, you should provide **symbolized call stacks** of the lag you talked about.

**Comment by hellokent** [comment]
卡顿堆栈类似这样：

```
com.tencent.mmkv.MMKV.encodeString(MMKV.java:0)     
com.tencent.mmkv.MMKV.putString(MMKV.java:943)     
... 业务敏感堆栈 ...
io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)     
io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)     
io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)     
io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)     
android.os.Handler.handleCallback(Handler.java:938)     
android.os.Handler.dispatchMessage(Handler.java:99)     
android.os.Looper.loop(Looper.java:246)     
android.os.Handler.handleCallback(Handler.java:938)     
android.os.Handler.dispatchMessage(Handler.java:99)     
android.os.Looper.loop(Looper.java:246)     
android.app.ActivityThread.main(ActivityThread.java:8653)     
java.lang.reflect.Method.invoke(Native Method:0)     
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)     
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)   

```

主线程卡顿检测默认 1s 一次；**极端场景**下，这种堆栈的分布大量分布在 5 次以上。

**Comment by lingol** [comment]
There are no symbolized MMKV call stacks inside your report, especially no **symbolized native call stacks**. 
It's useless.

**Comment by hellokent** [comment]
嗯，我们现在的卡顿检测 sdk 暂时不支持 c++ 代码的堆栈，只有 java 侧的，所以缺失这部分信息。

**Comment by lingol** [comment]
Why don't you split into different threads when you complain about locks? And believe me, nobody cares about your classified business logic call stacks.

**Comment by hellokent** [comment]
我理解你的困惑，主要是我担心我们厂有正对 github 的定期扫描，安全第一。。。
关于拆分线程这块儿，主要是工程的代码太多了，直接拆分代码成本比较高，大几百万行里面让业务一一去改不太现实。

**Comment by lingol** [comment]
No, I mean why don't you split call stacks into different threads. Looks like you only provide call stacks in one thread. Is it your SDK only captures the main thread's call stacks?

**Comment by hellokent** [comment]
对的，这个点是通过卡顿sdk发现的，目前只能抓取主线程堆栈

**Comment by lingol** [comment]
So there's absolutely no evidence when you complain about locks. Ah...Come back when you have more.

**Comment by GE-GAO-ZHAO** [comment]
The MMKV initialization must be performed in the main thread. Please check whether the MMKV initialization is performed in the main thread

**Comment by yaoguangdong** [comment]
是中国人吗？不能说母语吗？这么狂

**Comment by yaoguangdong** [comment]
我们也遇到了很多MMKV读写的卡顿，无奈，全都改造到子线程里操作了。现在就是遇到一个改一个。
