### ISSUE TITLE
MMKV存储同样的key数据不更新问题

### ISSUE THREAD

**Issue by sldboy** [Tencent/MMKV#851]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

java

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.
1.2.6

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

Maven

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.
我发现反复存同一个key，有时候会取到一个旧的数据，指针永远指向旧数据而不能更新数据

**Comment by lingol** [comment]
That's quite impossible. As the issue template has requested, please provide logs when this happens. 

One more thing, your version is quite old. Upgrade it first.

**Comment by sldboy** [comment]
找到问题了，是存取了两次不同的数据导致的。

**Comment by lingol** [comment]
That's good to hear. Anyway, you should upgrade your MMKV to the latest one.
