### ISSUE TITLE
The device_info has deprecated which is illegal to read Android ID when the app initialized

### ISSUE THREAD

**Issue by TDForLife** [Tencent/MMKV#852]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> Flutter \ Dart

### The version of MMKV

> v1.2.13

### The platform of MMKV

> Android

### The installation of MMKV

> flutter pub

### What's the issue?

> The plugin device_info read the Android id at app lunching time, it is illegal. I run the [ flutter pub deps] and the result is :

|-- mmkv 1.2.13
|   |-- device_info 2.0.3
|   |   |-- device_info_platform_interface 2.0.1
|   |   |   |-- flutter...
|   |   |   |-- meta...
|   |   |   '-- plugin_platform_interface...
|   |   '-- flutter...
|   |-- ffi 1.1.2
|   |-- flutter...
|   '-- path_provider...

**Comment by lingol** [comment]
What do you mean by saying **illegal**? Using a deprecated API is NOT illegal. It's outdated. That's all.
