### ISSUE TITLE
关于importFromSharedPreferences的疑问

### ISSUE THREAD

**Issue by ljackChen001** [Tencent/MMKV#853]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

>  Kotlin

### The version of MMKV

>  v1.2.12  

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

>  我需要将SP数据导入到MMKV 使用 
     val mmkv = MMKV.mmkvWithID(name, if(useMultiProcess) MMKV.MULTI_PROCESS_MODE else MMKV.SINGLE_PROCESS_MODE)
     val preferences: SharedPreferences = context.getSharedPreferences(name, MODE_PRIVATE)
     mmkv.importFromSharedPreferences(preferences)
     preferences.edit().clear().apply()

   旧项目中在使用 getSharedPreferences(“xxx”, Context.MODE_MULTI_PROCESS)
    val preferences: SharedPreference = context.getSharedPreferences(name, mode) 是否需要传入 MODE_MULTI_PROCESS

**Comment by lingol** [comment]
It doesn't matter. SP's multi-process mode is a fake concept. It provides no cross-process safety.

**Comment by lingol** [comment]
If you worry about it, you could use whatever parameter your old logic is using. 
In the end, fake concepts do provide some mind comforting.

**Comment by ljackChen001** [comment]
context.getSharedPreferences(name, MODE_PRIVATE) 是否可以直接写死

**Comment by lingol** [comment]
I believe I have answered the question.
