### ISSUE TITLE
微信逆天的2天设备重新扫码设定啥时候能改

### ISSUE THREAD

**Issue by xgdgsc** [Tencent/MMKV#854]
反正其他地方反馈也没有用，只能麻烦你们问候一下你们的产品经理，有没有改的意思？

还有企业微信啥时候支持多电脑同时登录？

谢谢！

**Comment by lingol** [comment]
It's unreverent to this repo.

**Comment by xgdgsc** [comment]
你们写的库效率再好再好用，用在一坨屎上你们自己不恶心吗？

**Comment by lingol** [comment]
Choose your language carefully. You have probably violated our code of conduct. https://github.com/Tencent/MMKV/blob/master/CODE_OF_CONDUCT.md

**Comment by xgdgsc** [comment]
我是违反了你们的规则，但我也没办法，如果我违反一个规则能换来大家每天节约30s扫码时间我愿意。你们能为了全世界用户节约时间违反你门公司的潜规则吗，还是就守着你们自己的一亩三分地？

**Comment by lingol** [comment]
Again it's irreverent to this repo. If you have problems with any products, I'm sure each product has a feedback channel.
This issue is locked due to repeated warnings.
