### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError dlopen failed: library "libmmkv.so" not found

### ISSUE THREAD

**Issue by billdizl** [Tencent/MMKV#856]
mmkv版本 :com.tencent:mmkv:1.2.12
报错信息:
java.lang.Runtime.loadLibrary0 (Runtime.java:1077)

java.lang.System.loadLibrary (System.java:1656)
com.tencent.mmkv.MMKV.doInitialize (MMKV.java:194)
com.tencent.mmkv.MMKV.initialize (MMKV.java:181)
com.tencent.mmkv.MMKV.initialize (MMKV.java:134)

设备
品牌：samsung
型号：Galaxy S21+ 5G
屏幕方向： 纵向
可用 RAM： 2.64 GB
可用磁盘空间： 37.11 GB
操作系统
版本：Android 12
屏幕方向： 纵向
是否已取得 root 权限：否
崩溃
日期：2022年3月24日 11:40:59

**Comment by lingol** [comment]
Duplicated issue.
