### ISSUE TITLE
使用框架自定定义目录。二个app访问同这个目录下的数据发现不行，是框架不支持吗

### ISSUE THREAD

**Issue by douya40** [Tencent/MMKV#857]
自定定义目录。二个app访问同一个目录发现不行，是框架不支持吗

**Comment by lingol** [comment]
Different App accessing one directory, did Android support this? I don't think so.

**Comment by lingol** [comment]
If you can't access the directory using the native language or system framework, you can't do it by MMKV. It's that simple.
