### ISSUE TITLE
iOS这个方法里报错。  mmkvWithID:(NSString *)mmapID cryptKey:(NSData *)cryptKey rootPath:(nullable NSString *)rootPath mode:(MMKVMode)mode

### ISSUE THREAD

**Issue by lanwenjin** [Tencent/MMKV#858]
![截屏2022-03-29 上午9 00 50](https://user-images.githubusercontent.com/16382218/160511878-cb82db14-3d73-4820-a2a6-065066d7a64a.png)

**Comment by lingol** [comment]
>Getting a multi-process MMKV without setting `groupDir` makes no sense.

The error is quite clear. I don't know why do you ask?

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/iOS_tutorial#configuration
Check the multi-process section.
