### ISSUE TITLE
频繁调用mmkv的encode和decode性能影响大吗

### ISSUE THREAD

**Issue by taozijie** [Tencent/MMKV#861]
mmkv的存取相当于在内存中，那频繁的调用mmkv的encode和decode性能影响大吗？另外mmkv为啥不提供按条读取的操作呢？只能要不就是按照key，要不就是全部取出来

**Comment by lingol** [comment]
To your first question, No.

To your second question, maybe. We might support retrieving multi key-value if they are of the same type. 
But I doubt it. In fact, that may not be much faster than retrieving one at a time.

**Comment by taozijie** [comment]
不是担心全部取出来影响性能，主要是我不确定存储了多少数据，一次全部取出来后就在内存中，怕影响内存

**Comment by lingol** [comment]
And the answer is still NO.

**Comment by taozijie** [comment]
1，另外想知道是否有最大存储限制，防止恶意使用或者不规范使用导致无限添加数据。

**Comment by taozijie** [comment]
试了actualSize方法得到的值是48364484，然后通过as看的data下面mmkv中创建的文件的大小只有4kb，这是为啥？

**Comment by lingol** [comment]
It's impossible.
