### ISSUE TITLE
C/C++ Configuration Problem when using NDK 24.0.8215888

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#865]
MMKV 1.2.13
NDK 24.0.8215888
Gradle 7.2
Android Studio 2021.1.1 Patch 2

We get the following "C/C++ Configuration Problem" error after changing to use NDK 24.0.8215888

`MMKV.mmkv | DefaultCppDebug | x86 Compiler exited with error code 1: E:\Android\sdk\ndk\24.0.8215888\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe -xc++ --target=i686-none-linux-android19 --sysroot=E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dmmkv_EXPORTS -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -D_FORTIFY_SOURCE=2 -Wformat -DMMKV_STL_SHARED=0 -fno-limit-debug-info -fPIC -std=c++17 E:\\AndroidProgram\\share\\mmkv\\MMKV_1.2.13.modified\\Android\\MMKV\\mmkv\\src\\main\\cpp\\native-bridge.cpp -fpch-preprocess -v -dD -E Android (8075178, based on r437112b) clang version 14.0.1 (https://android.googlesource.com/toolchain/llvm-project 8671348b81b95fc603505dfc881b45103bee1731) Target: i686-none-linux-android19 Thread model: posix InstalledDir: E:\Android\sdk\ndk\24.0.8215888\toolchains\llvm\prebuilt\windows-x86_64\bin "E:\\Android\\sdk\\ndk\\24.0.8215888\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" -cc1 -triple i686-none-linux-android19 -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name native-bridge.cpp -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=all -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu i686 -target-feature +ssse3 -tune-cpu generic -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=gdb -v -ffunction-sections -fdata-sections "-fcoverage-compilation-dir=E:\\AndroidProgram\\share\\mmkv\\MMKV_1.2.13.modified\\Android\\MMKV\\mmkv\\.cxx\\Debug\\62m4e6w2\\x86" -resource-dir "E:\\Android\\sdk\\ndk\\24.0.8215888\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\14.0.1" -D mmkv_EXPORTS -D ANDROID -D _FORTIFY_SOURCE=2 -D MMKV_STL_SHARED=0 -D ___CIDR_DEFINITIONS_END -isysroot E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot -internal-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 -internal-isystem "E:\\Android\\sdk\\ndk\\24.0.8215888\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\14.0.1\\include" -internal-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include -internal-externc-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/i686-linux-android -internal-externc-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include -internal-externc-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include -Wformat -std=c++17 -fdeprecated-macro "-fdebug-compilation-dir=E:\\AndroidProgram\\share\\mmkv\\MMKV_1.2.13.modified\\Android\\MMKV\\mmkv\\.cxx\\Debug\\62m4e6w2\\x86" -ferror-limit 19 -stack-protector 2 -mstackrealign -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -dD -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o - -x c++ "E:\\AndroidProgram\\share\\mmkv\\MMKV_1.2.13.modified\\Android\\MMKV\\mmkv\\src\\main\\cpp\\native-bridge.cpp" clang -cc1 version 14.0.1 based upon LLVM 14.0.1git default target x86_64-w64-windows-gnu ignoring nonexistent directory "E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include" #include "..." search starts here: #include ...> search starts here: E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 E:\Android\sdk\ndk\24.0.8215888\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\14.0.1\include E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/i686-linux-android E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include End of search list. E:\AndroidProgram\share\mmkv\MMKV_1.2.13.modified\Android\MMKV\mmkv\src\main\cpp\native-bridge.cpp:21:10: fatal error: 'MMKVPredef.h' file not found #include "MMKVPredef.h" ^~~~~~~~~~~~~~ 1 error generated. "E:\\Android\\sdk\\ndk\\24.0.8215888\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" -cc1 -triple i686-none-linux-android19 -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name compiler-file12221505380036682481 -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=all -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu i686 -target-feature +ssse3 -tune-cpu generic -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=gdb -v -ffunction-sections -fdata-sections "-fcoverage-compilation-dir=E:\\AndroidProgram\\share\\mmkv\\MMKV_1.2.13.modified\\Android\\MMKV\\mmkv\\.cxx\\Debug\\62m4e6w2\\x86" -resource-dir "E:\\Android\\sdk\\ndk\\24.0.8215888\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\14.0.1" -D mmkv_EXPORTS -D ANDROID -D _FORTIFY_SOURCE=2 -D MMKV_STL_SHARED=0 -D ___CIDR_DEFINITIONS_END -isysroot E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot -internal-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 -internal-isystem "E:\\Android\\sdk\\ndk\\24.0.8215888\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\14.0.1\\include" -internal-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include -internal-externc-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/i686-linux-android -internal-externc-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include -internal-externc-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include -Wformat -std=c++17 -fdeprecated-macro "-fdebug-compilation-dir=E:\\AndroidProgram\\share\\mmkv\\MMKV_1.2.13.modified\\Android\\MMKV\\mmkv\\.cxx\\Debug\\62m4e6w2\\x86" -ferror-limit 19 -stack-protector 2 -mstackrealign -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -dD -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o - -x c++ "C:\\Users\\yslsa\\AppData\\Local\\Temp\\compiler-file12221505380036682481" clang -cc1 version 14.0.1 based upon LLVM 14.0.1git default target x86_64-w64-windows-gnu ignoring nonexistent directory "E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include" #include "..." search starts here: #include ...> search starts here: E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 E:\Android\sdk\ndk\24.0.8215888\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\14.0.1\include E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/i686-linux-android E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include End of search list. Compiler exited with error code 1: E:\Android\sdk\ndk\24.0.8215888\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe -xc++ --target=i686-none-linux-android19 --sysroot=E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot -Dmmkv_EXPORTS -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -D_FORTIFY_SOURCE=2 -Wformat -DMMKV_STL_SHARED=0 -fno-limit-debug-info -fPIC -std=c++17 E:\\AndroidProgram\\share\\mmkv\\MMKV_1.2.13.modified\\Android\\MMKV\\mmkv\\src\\main\\cpp\\flutter-bridge.cpp -fpch-preprocess -v -dD -E Android (8075178, based on r437112b) clang version 14.0.1 (https://android.googlesource.com/toolchain/llvm-project 8671348b81b95fc603505dfc881b45103bee1731) Target: i686-none-linux-android19 Thread model: posix InstalledDir: E:\Android\sdk\ndk\24.0.8215888\toolchains\llvm\prebuilt\windows-x86_64\bin "E:\\Android\\sdk\\ndk\\24.0.8215888\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\clang++.exe" -cc1 -triple i686-none-linux-android19 -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name flutter-bridge.cpp -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=all -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu i686 -target-feature +ssse3 -tune-cpu generic -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=gdb -v -ffunction-sections -fdata-sections "-fcoverage-compilation-dir=E:\\AndroidProgram\\share\\mmkv\\MMKV_1.2.13.modified\\Android\\MMKV\\mmkv\\.cxx\\Debug\\62m4e6w2\\x86" -resource-dir "E:\\Android\\sdk\\ndk\\24.0.8215888\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\14.0.1" -D mmkv_EXPORTS -D ANDROID -D _FORTIFY_SOURCE=2 -D MMKV_STL_SHARED=0 -D ___CIDR_DEFINITIONS_END -isysroot E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot -internal-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1 -internal-isystem "E:\\Android\\sdk\\ndk\\24.0.8215888\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\14.0.1\\include" -internal-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/local/include -internal-externc-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/i686-linux-android -internal-externc-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/include -internal-externc-isystem E:/Android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include -Wformat -std=c++17 -fdeprecated-macro "-fdebug-compilation-dir=E:\\AndroidProgram\\share\\mmkv\\MMKV_1.2.13.modified\\Android\\MMKV\\mmkv\\.cxx\\Debug\\62m4e6w2\\x86" -ferror-limit 19 -stack-protector 2 -mstackrealign -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -dD -D__GCC_HAVE_DWARF2_C ...`

**Comment by samlu** [comment]
Sorry, It seems that it's caused by my local env. settings. You can close this ticket now.

**Comment by Thanaen** [comment]
Hi @samlu !
Do you remember how you fixed this? I am facing a very similar issue!
