### ISSUE TITLE
input is not valid Modified UTF-8

### ISSUE THREAD

**Issue by nnjun** [Tencent/MMKV#868]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> Java

### The version of MMKV

> implementation "com.tencent:mmkv-static:1.2.10"

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?

I have been using multi-process operation and it is relatively high frequency.
This is my crash log, which is too much:.
[crash.txt](https://github.com/Tencent/MMKV/files/8465382/crash.txt)

Also, I often see the following logs.
`MMKV: <MMKV.cpp:589::getVector> InvalidProtocolBuffer truncatedMessage`

**Comment by lingol** [comment]
It's highly likely that you have not set the MULTI_PROCESS_MODE on some process.

**Comment by nnjun** [comment]
`private static final MMKV sMMKV = MMKV.mmkvWithID("CaptureSessionData", MMKV.MULTI_PROCESS_MODE);`

I have set it up and all processes use this class for operations, so the initialization is uniform.

**Comment by nnjun** [comment]
When I add data to set, I will first getStringSet, set.add, and then execute putStringSet, if this is easy to trigger this problem (this operation is very high frequency), if I do caching, not using getStringSet, but only execute putStringSet, this problem does not seem to appear.

**Comment by nnjun** [comment]
I don't know if this is a good choice, my scenario is to use mmkv to store network data (putBytes) and StringSet to store the index. And may be read in another process, if something is downloaded from the network, then the operation will be very frequent and need to keep reading data and manipulating mmkv

**Comment by lingol** [comment]
Don't use MMKV as a static variable. All MMKV methods must be called after MMKV is initiated.

**Comment by nnjun** [comment]
Currently I am not having these problems without using getStringSet, set.add and then performing putStringSet to add data to the StringSet. Including `MMKV:<MMKV.cpp:589::getVector> InvalidProtocolBuffer truncatedMessage`  does not appear either. If I use the above method, I get `MMKV:<MMKV.cpp:589::getVector> InvalidProtocolBuffer truncatedMessage`

This may sound absurd, but it is.Thank you for your patient answer.
