### ISSUE TITLE
com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'

### ISSUE THREAD

**Issue by liqiangCoding** [Tencent/MMKV#869]
Note:
com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'

The language of MMKV

kotlin

The version of MMKV

com.tencent:mmkv:1.2.13

The platform of MMKV

Android

The installation of MMKV

Maven

What's the issue?

com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libmmkv.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].

system :harmonyOs  2.0.0

devices : honor 9X pro   HLK-AL10

**Comment by lingol** [comment]
Duplicated with #863
