### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by DonYau** [Tencent/MMKV#87]
I always error "fail to mlock crc [mmkv.default]-0x1041b8000, 12:Cannot allocate memory"

**Comment by zhongwuzw** [comment]
@DonYau Which version of `MMKV` you use? `iOS` or `Android`? the error logs appear when your app is in background?

**Comment by DonYau** [comment]
ios and 1.011
Running in the foreground

**Comment by DonYau** [comment]
ios and 1.0.11
Running in the foreground

**Comment by zhongwuzw** [comment]
@DonYau Could you please try to use the latest `master` code or just remove one line just like [fix merge error](https://github.com/Tencent/MMKV/commit/df06b4191722054082d73880b1481339b60dc094#diff-8b58878359e253ccc0aa3a910b2f150dL395)?

**Comment by lingol** [comment]
It turns out to be `CRC_FILE_SIZE`'s fault. The mistakenly `m_isInBackground = YES` makes it worse.

**Comment by zhongwuzw** [comment]
@lingol Emm, so you mean the file size needs to be multiple of the page size? If not, `mlock` may fail?

**Comment by lingol** [comment]
> @lingol Emm, so you mean the file size needs to be multiple of the page size? If not, `mlock` may fail?

That's right.

> By the way, any reason why crc checksum should be stored in a separated file?

In fact that's called **meta info file**. That file In Android has more stuff than CRC32 digest, such as version/sequence. And in iOS that's only CRC32 digest for the time being. Separating meta info in another file makes room for further expansion.

**Comment by zhongwuzw** [comment]
@lingol Got it, seems we should make crc file pageable.

> In fact that's called meta info file. That file In Android has more stuff than CRC32 digest, such as version/sequence. And in iOS that's only CRC32 digest for the time being. Separating meta info in another file makes room for further expansion.

Emm, we can regard all data like a [TCP](https://en.wikipedia.org/wiki/Transmission_Control_Protocol) packet, we can see how `TCP` handle the extension for the future.
Yeah, we can use a separate file to store, I just have some worries, because it may increase the inconsistent of checksum and data, additional file, mmap, and so on, any of them may leads to check failed.
