### ISSUE TITLE
Crash on Android 32-bit devices, missing armeabi/libmmkv.so

### ISSUE THREAD

**Issue by wondertwo** [Tencent/MMKV#871]
<img width="474" alt="wecom-temp-97c166e44dd422ee54db61523439c48f" src="https://user-images.githubusercontent.com/16076053/162932910-19720160-ed9a-4698-bf28-5c908165d5b3.png">

Crash on Android 32-bit devices, missing armeabi/libmmkv.so, Unzip aar and find that there is 32-bit device support in the armeabi-v7a directory, but can the abiFilter in armeabi format be supported?

**Comment by lingol** [comment]
Duplicated with #863 .

**Comment by wondertwo** [comment]
谢谢！已收到啦。看完马上回复~~~
