### ISSUE TITLE
Windows下Cmake编译报错

### ISSUE THREAD

**Issue by Tlioylc** [Tencent/MMKV#874]
在windows下cmake编译MMKV,MemoryFile_Win32.cpp无法编译通过， error: cannot convert 'const wchar_t*' to 'LPCSTR' {aka 'const char*'}。我想确认一下，是否无法通过cmake在windows下打出MinGW静态库？

**Comment by lingol** [comment]
Looks like it's a configuration problem. You might want to check the win32 setup wiki again for char set settings.

**Comment by Tlioylc** [comment]
我尝试添加了这些，现在可以正常运行了
`#ifndef UNICODE
#define UNICODE
#define UNICODE_WAS_UNDEFINED
#endif

#include <Windows.h>

#ifdef UNICODE_WAS_UNDEFINED
#undef UNICODE
#endif
`
