### ISSUE TITLE
在 kotlin 内使用 decodeParcelable时泛型Class<T>报错

### ISSUE THREAD

**Issue by XiaoyuZhann** [Tencent/MMKV#876]
我在 by 代理属性get set时对缓存进行操作，但是当我如此使用时他报错了
`
inline operator fun <reified T> getValue(thisRef: Any?, property: KProperty<*>): T {
            return mmkv.decodeParcelable(
                property.name,
                T::class.java
            ) as T
    }
`
泛型T报错
`
Type mismatch.
Required:
Parcelable!
Found:
T!
`
无法理解传入data class 通过dataClass().javaClass获取就能通过，他们获取的都是同一个东西

**Comment by lingol** [comment]
It's not MMKV's problem. You complain to the wrong place.
