### ISSUE TITLE
安卓Native崩溃signal 7 (SIGBUS), code 2 (BUS_ADRERR)

### ISSUE THREAD

**Issue by noobYang95** [Tencent/MMKV#878]
### The language of MMKV

Java

### The version of MMKV

1.2.10、1.2.13

### The platform of MMKV

Android

### The installation of MMKV

Maven

### What's the issue?

线上有偶现报错，从1.2.10升级到1.2.13版本也没有得到解决，报错用户没有太多特征，各个Android版本各个厂商机型均有

signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 000000745dbd943e
  x0   0000000000000000  x1   000000745dbd943e  x2   0000000000000005  x3   0000000000000001
  x4   0000000000000007  x5   0000007ff4e7ade7  x6   0000000072657375  x7   0000000064497265
  x8   0000007486e5a000  x9   000000745dbd943e  x10  0000000000000001  x11  0000000000000064
  x12  0000000000000064  x13  000000000a3967c4  x14  0000007160adec34  x15  00000000ebad6a89
  x16  00000070d15d9c28  x17  0000007472062cb4  x18  00000000a3014314  x19  0000007ff4e7ad58
  x20  0000000000000000  x21  0000000000000000  x22  0000007ff4e7ade0  x23  0000007206d54d70
  x24  0000007486e5a000  x25  0000007ff4e7ad70  x26  0000007ff4e7af88  x27  0000007ff4e7af60
  x28  0000007ff4e7ae50  x29  0000007ff4e7ad10  x30  00000070d1591688
  sp   0000007ff4e7ac70  pc   00000070d1591730  pstate 0000000080001000
v0   00000000000000000000000000000002  v1   00000000000000000000000000000000
  v2   00000000000000000000000000000000  v3   00000000000000000000000000000000
  v4   00000000000000000000007486e5a000  v5   00000000000000000000000000000001
  v6   00000000000000000000000013b7c3f8  v7   000000000000000000000072d6cf6010
  v8   00000000000000000000000000000000  v9   00000000000000000000000000000000
  v10  00000000000000000000000000000000  v11  00000000000000000000000000000000
  v12  00000000000000000000000000000000  v13  00000000000000000000000000000000
  v14  00000000000000000000000000000000  v15  00000000000000000000000000000000
  v16  ee1b8e25fc7458e9f9305923f49888d9  v17  cffba0fea75f47816ce417c61a84b68f
  v18  00000001000000000000000000000000  v19  000000000000000000000000ebad8083
  v20  a44d08c64a5686e3b622de0a4f128729  v21  5727768298dcd67c3f8391fd5367863b
  v22  04701b1ea03d13d8ea6b953b5c494b31  v23  514e184a06696ec89eb5b8b4a1362949
  v24  000000000000000000000000ebad8088  v25  000000000000000000000000ebad8089
  v26  000000000000000000000000ebad808a  v27  000000000000000000000000ebad808b
  v28  000000000000000000000000ebad808c  v29  000000000000000000000000ebad808d
  v30  000000000000000000000000ebad808e  v31  00320062003500620061006300660033
  fpsr 00000011  fpcr 00000000
    #00 pc 000000000002d730  /data/app/~~19HPceiSr9onmgod6kpRTQ==/com.xx.xx-dKUKwE_Yq2JMrowgpXP8Vw==/lib/arm64/libmmkv.so
    #01 pc 000000000002d684  /data/app/~~19HPceiSr9onmgod6kpRTQ==/com.xx.xx-dKUKwE_Yq2JMrowgpXP8Vw==/lib/arm64/libmmkv.so
    #02 pc 000000000001f8d8  /data/app/~~19HPceiSr9onmgod6kpRTQ==/com.xx.xx-dKUKwE_Yq2JMrowgpXP8Vw==/lib/arm64/libmmkv.so
    #03 pc 0000000000018960  /data/app/~~19HPceiSr9onmgod6kpRTQ==/com.xx.xx-dKUKwE_Yq2JMrowgpXP8Vw==/lib/arm64/libmmkv.so
    #04 pc 00000000000d7644  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148)
    #05 pc 000000000000ae1c  /apex/com.android.art/lib64/libart.so (nterp_helper+7468)
    #06 pc 000000000000a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #07 pc 000000000000a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #08 pc 000000000000a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #09 pc 000000000000a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #10 pc 000000000000a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #11 pc 000000000000a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #12 pc 000000000000a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #13 pc 000000000000a044  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
    #14 pc 00000000001bf8f4  /system/framework/arm64/boot-framework.oat

**Comment by lingol** [comment]
As the issue template has said, symbolized your native call stacks and provide logs of MMMKV.

**Comment by lingol** [comment]
Closed due to inactive.
