### ISSUE TITLE
MMKV每次读取数据是从哪里读的？直接通过mmap去文件里读么？

### ISSUE THREAD

**Issue by darrenfantasy** [Tencent/MMKV#879]
## Note:
希望能对这块做更详细的说明

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
Does it matter? 

Anyway, the answer is it depends. If the the file is encrypted it's read from memory cache. Otherwise it's read from mapped file.
