### ISSUE TITLE
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by mfbx9da4** [Tencent/MMKV#881]
### The language of MMKV

Swift

### The version of MMKV

  - MMKV (1.2.11):
    - MMKVCore (~> 1.2.11)
  - MMKVCore (1.2.11)

### The platform of MMKV

ios

### The installation of MMKV

Cocoapods

### What's the issue?

I'm trying to use MMKV in an app extension, in my case I am writing a notification service extension but I get the build error

```
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
```

Is it not possible to use mmkv in app extensions with app groups?

I saw this but it didn't help too much https://github.com/Tencent/MMKV/issues/398

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/wiki/iOS_setup#installation

>Add #import <MMKV/MMKV.h> to your source file and we are done, replace with <MMKVAppExtension/MMKV.h> and <MMKVWatchExtension/MMKV.h> accordingly for other extension targets.

**Comment by Nehal-Zeller** [comment]
@lingol  I'm getting the same error but my app is react-native. I've integrated MMKV and it has been working fine. Now i want to add wallet extension in my app, that I'm doing in ios natively. I'm encountering this issue

`
....
target 'myApp' do
  config = use_native_modules!
  
  target 'WNonUIExtension' do
    pod 'MMKVAppExtension'
  end

  target 'WUIExtension' do
    pod 'MMKVAppExtension'
  end
  ...
  `
  
  adding pod for extension target is not working. could you help me here?

**Comment by Nehal-Zeller** [comment]
@mrousavy could you also take a look at above scenario please?
