### ISSUE TITLE
MMKV 子进程SIGBUS异常

### ISSUE THREAD

**Issue by PaulZJ** [Tencent/MMKV#882]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

JAVA

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

1.2.13；自行编译的so，disable flutter相关的编译

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

signal:  SIGBUS
code:  BUS_ADRERR

libmmkv.so  OUTLINED_FUNCTION_177
--
  | libmmkv.so  mmkv::AESCrypt::decrypt(void const*, void*, unsigned long) (openssl_cfb128.cpp:0)
  | libmmkv.so  mmkv::KeyValueHolderCrypt::toMMBuffer(void const*, mmkv::AESCrypt const*) const (KeyValueHolder.cpp:150)
  | libmmkv.so  decodeString (MMKV.cpp:543)
  | jit-code-cache  com.tencent.mmkv.MMKV.getString
  | boot-framework.oat  android.os.Handler.dispatchMessage
  | boot-framework.oat  android.os.Looper.loop
  | boot-framework.oat  android.os.HandlerThread.run
  | libart.so  CreateCallback
  | libc.so  __pthread_start
  | libc.so  __start_thread
  | com.tencent.mmkv.MMKV.decodeString(MMKV.java:0)
  | com.tencent.mmkv.MMKV.getString(MMKV.java:990)

MMKV存储开启了多进程模式，多进程共用一份MMKV存储(配置文件)
APP 切后台时，子进程会先调用allKeys获取所有配置的key；然后根据key获取配置(获取配置时，MMKV的decodeString方法抛出SIGBUS异常)

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

线上无MMKV异常日志，只有info相关日志；举例如下
`open open fd[xxx]`，`loadFromFile loading [xxxx] with xxx actual size, file size xxx, InterProcess 1, meta info version:3`

**Comment by lingol** [comment]
Your crash stacks & logs provide little info. Can you provide a reproducible MMKV file (and the relative.crc file)? 
You should provide the encryption key as well, for it looks like you are using encrypted MMKV.

**Comment by PaulZJ** [comment]
线下未复现类似问题；线上有一定数量的MMKV SIGBUS上报，偶现(但机型、用户也不能稳定复现)

线上监控也查看了崩溃用户的磁盘情况，磁盘空间不足（少于0.1G）的占比不足1%；用户磁盘环境，感觉不是根因

**Comment by PaulZJ** [comment]
> Your crash stacks & logs provide little info. Can you provide a reproducible MMKV file (and the relative.crc file)? You should provide the encryption key as well, for it looks like you are using encrypted MMKV.

能提供一些排查思路(如何根据这两个文件的内容来排查问题)吗？

**Comment by lingol** [comment]
Are you sure all multi-process MMKV instances are initiated with the MULTI_PROCESS_MODE flag?

**Comment by PaulZJ** [comment]
yes
