### ISSUE TITLE
MMKV Native 内存泄漏

### ISSUE THREAD

**Issue by PaulZJ** [Tencent/MMKV#883]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Java

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

1.2.13

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

```
void MiniPBCoder::decodeOneMap(MMKVMapCrypt &dic, size_t position, bool greedy) {
    auto block = [position, this](MMKVMapCrypt &dictionary) {
        if (position) {
            m_inputDataDecrpt->seek(position);
        } else {
            m_inputDataDecrpt->readInt32();
        }
        while (!m_inputDataDecrpt->isAtEnd()) {
            KeyValueHolderCrypt kvHolder;
            const auto &key = m_inputDataDecrpt->readString(kvHolder);
            if (key.length() > 0) {
                m_inputDataDecrpt->readData(kvHolder);
                if (kvHolder.realValueSize() > 0) {
                    dictionary[key] = move(kvHolder);
                } else {
                    auto itr = dictionary.find(key);
                    if (itr != dictionary.end()) {
                        dictionary.erase(itr);
                    }
                }
            }
        }
    };

    if (greedy) {
        try {
            block(dic);
        } catch (std::exception &exception) {
            MMKVError("%s", exception.what());
        }
    } else {
        try {
            MMKVMapCrypt tmpDic;
            block(tmpDic);
            dic.swap(tmpDic);
        } catch (std::exception &exception) {
            MMKVError("%s", exception.what());
        }
    }
}   
```
`dictionary[key] = move(kvHolder);`，当kvHolder是KeyValueHolderType_Memory类型时，会造成native内存没有回收的情况；

```
// kv holder for encrypted mmkv
struct KeyValueHolderCrypt {
    KeyValueHolderType type = KeyValueHolderType_Direct;

    union {
        // store value by offset
        struct {
            uint8_t pbKeyValueSize; // size needed to encode keySize & valueSize
            uint16_t keySize;
            uint32_t valueSize;
            uint32_t offset;
            AESCryptStatus cryptStatus;
        };
        // store value directly
        struct {
            uint8_t paddedSize;
            uint8_t paddedValue[1];
        };
        // store value in the heap memory
        struct {
            uint32_t memSize;
            void *memPtr;
        };
    };
}
```
单个Key持有的memSize小于256字节；但当key数量非常大的时候，`MMKVMapCrypt`集合持有的native内存还是非常可观的；能否优化一下？

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
I don't understand. What is the memory **LEAK** you are talking about? As far as I can see, there's no leak.

**Comment by PaulZJ** [comment]
> I don't understand. What is the memory **LEAK** you are talking about? As far as I can see, there's no leak.

```
KeyValueHolderCrypt::KeyValueHolderCrypt(const void *src, size_t length) {
    if (length <= SmallBufferSize()) {
        type = KeyValueHolderType_Direct;
        paddedSize = static_cast<uint8_t>(length);
        memcpy(paddedValue, src, length);
    } else {
        type = KeyValueHolderType_Memory;
        memSize = static_cast<uint32_t>(length);
        memPtr = malloc(length);
        if (!memPtr) {
            throw std::runtime_error(strerror(errno));
        }
        memcpy(memPtr, src, memSize);
    }
}
```
`KeyValueHolderType_Memory`类型的`KeyValueHolderCrypt`，被`MMKVMapCrypt `集合持有，导致`memPtr = malloc(length);`申请的内存在MMKV整个生命周期内都不会被释放。虽然单次malloc的内存空间不大，但当`KeyValueHolderCrypt`数量非常多时，是不是可以认为是native 内存泄漏？（可以做free一部分？保证整体native内存不膨胀？）

**Comment by lingol** [comment]
As far as it will be free at some point, it's not leaking.

**Comment by JasonYinH** [comment]
英文这么高大上吗
