### ISSUE TITLE
建议Flutter版本的mmkv插件改个名字

### ISSUE THREAD

**Issue by sohotz** [Tencent/MMKV#884]
flutter mmkv和native mmkv编译冲突，使用fix_mmkv_plugin_name脚本修改文件内容。这个做法很破坏流程，在一些App集成Flutter模块时，构建、依赖都是一套通用工具链封装，后置修改这种做法放Podfile里还是flutter pub get后都不合适，因为整个流程封装在通用工具链里（构建命令的，pod插件的），不合适在通用工具链里侵入特殊处理逻辑。后置修改这种做法本身破坏了flutter官方流程和增加了复杂度。

**Comment by lingol** [comment]
What can I say? The so-called _Flutter official workflow_ sucks.
