### ISSUE TITLE
stringSet写入空集合，读取却返回null

### ISSUE THREAD

**Issue by re-ovo** [Tencent/MMKV#885]
复现代码: (kotlin)
```kotlin
MMKV.defaultMMKV().encode("emptySetTest", emptySet<String>())
println(MMKV.defaultMMKV().decodeStringSet("emptySetTest"))
```

运行结果: `null`
预期结果: `[]`

如果存入空的String Set, 那么读取就会返回null, 配合default value参数使用的情况下，写入空集合以后就会始终返回default value

**Comment by re-ovo** [comment]
@lingol 🤔

**Comment by re-ovo** [comment]
yes, This should be similar to 'new ArrayList
<String>()' in java

**Comment by lingol** [comment]
Anyway, I have found the issue. Will be fixed soon in the dev branch.

**Comment by lingol** [comment]
Release in [v1.2.14](https://github.com/Tencent/MMKV/releases/tag/v1.2.14).
