### ISSUE TITLE
如何追加列表数据

### ISSUE THREAD

**Issue by lhjandroid** [Tencent/MMKV#889]
我在MMKV中存了一个列表。但我会不断的追加新的数据在列表中。我不能每次加新数据时把原来已经存好的数据都获取出来，然后再在列表末尾加上新数据吧？这样内存占用和新能是有瓶颈的。还有我怎么分页获取列表数据？假如我存的列表数据有1万条。我取的时候能指定取多少条吗？希望得到你的回复和帮助

**Comment by lingol** [comment]
Don't use a list in your case, store those values independently.

**Comment by lhjandroid** [comment]
> Don't use a list in your case, store those values independently.

```
public static void appendLocation(Location location) {
        // mmapID相当于表名
        MMKV mmkv = MMKV.mmkvWithID(NavDataManager.currentNavigation);
        long size = mmkv.count();
        // 按index存入
        mmkv.encode(String.valueOf(size),location);
    }

    public static List<Location> getLocations(int pageIndex,int pageSize) {
        long endIndex = (long) (pageSize + 1) * pageIndex;
        // mmapID相当于表名
        MMKV mmkv = MMKV.mmkvWithID(NavDataManager.currentNavigation);
        long startIndex = endIndex - pageSize;
        // 存了多少条数据
        long count = mmkv.count();
        // 已经没有下一页数据了
        if (mmkv.count() < startIndex) {
            return null;
        }
        // 如果下一页数据不够pageSize 则endIndex变为count
        if (endIndex > count) {
            endIndex = count;
        }
        List<Location> locations = new ArrayList<>();
        for (long i = startIndex; i < endIndex; i ++) {
            locations.add(mmkv.decodeParcelable(String.valueOf(i),Location.class));
        }
        return locations;
    }
```
我理解得对吗？

**Comment by lingol** [comment]
That's one way to do it, as long as you never ever delete any values, or you don't mind possibly duplication due to deletion.
Or you should use more **unique** keys than `String.valueOf(index)`.

**Comment by lhjandroid** [comment]
> That's one way to do it, as long as you never ever delete any values, or you don't mind possibly duplication due to deletion. Or you should use more **unique** keys than `String.valueOf(index)`.

了解了，我这数据要么不删除，要么全删。所以这样存的话应该没问题。非常感谢你的耐心回答,非常nice
