### ISSUE TITLE
杀掉进程重启app，导致崩溃，只有一个固定的地方会crash， 其他地方的都没问题

### ISSUE THREAD

**Issue by weiggle** [Tencent/MMKV#890]
Runtime aborting...
    runtime.cc:655] Dumping all threads without mutator lock held
    runtime.cc:655] All threads:
    runtime.cc:655] DALVIK THREADS (169):
    runtime.cc:655] "main" prio=10 tid=1 Runnable
    runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x7316a858 self=0xb400007f0e610800
    runtime.cc:655]   | sysTid=28233 nice=-10 cgrp=default sched=0/0 handle=0x7f95a39500
    runtime.cc:655]   | state=R schedstat=( 4427534326 335116475 2733 ) utm=392 stm=50 core=7 HZ=100
    runtime.cc:655]   | stack=0x7fca36d000-0x7fca36f000 stackSize=8192KB
    runtime.cc:655]   | held mutexes= "abort lock" "mutator lock"(shared held)
    runtime.cc:655]   native: #00 pc 000000000049f3e4  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+140)
    runtime.cc:655]   native: #01 pc 00000000005ac02c  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+376)
    runtime.cc:655]   native: #02 pc 00000000005c95b4  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+924)
    runtime.cc:655]   native: #03 pc 00000000005c34f4  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+528)
    runtime.cc:655]   native: #04 pc 00000000005c26c0  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+1920)
    runtime.cc:655]   native: #05 pc 000000000055db0c  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1864)
    runtime.cc:655]   native: #06 pc 0000000000013988  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76)
    runtime.cc:655]   native: #07 pc 0000000000012fb4  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+320)
    runtime.cc:655]   native: #08 pc 0000000000385620  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2572)
    runtime.cc:655]   native: #09 pc 0000000000385698  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+108)
    runtime.cc:655]   native: #10 pc 000000000037737c  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+144)
    runtime.cc:655]   native: #11 pc 000000000037726c  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckNonHeapValue(char, art::(anonymous namespace)::JniValueType)+1224)
    runtime.cc:655]   native: #12 pc 0000000000375338  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+200)
    runtime.cc:655]   native: #13 pc 0000000000374af4  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+612)
    runtime.cc:655]   native: #14 pc 000000000036ae84  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+696)
    runtime.cc:655]   native: #15 pc 0000000000018570  /data/app/~~QGspzUUso5t7iUiuHBuRtQ==/com.rjhy.jupiter-teVVGihXH-20dXZc7nWDEw==/lib/arm64/libmmkv.so (???)
    runtime.cc:655]   native: #16 pc 000000000013ced4  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148)
    runtime.cc:655]   native: #17 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
    runtime.cc:655]   native: #18 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
2022-05-16 21:36:31.044 28233-28233/com.rjhy.jupiter A/om.rjhy.jupite: runtime.cc:655]   native: #19 pc 0000000000318290  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376)
    runtime.cc:655]   native: #20 pc 000000000030e5bc  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996)
    runtime.cc:655]   native: #21 pc 000000000067efdc  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+576)
    runtime.cc:655]   native: #22 pc 000000000012d914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20)
    runtime.cc:655]   native: #23 pc 00000000003c8150  [anon:dalvik-classes7.dex extracted in memory from /data/app/~~QGspzUUso5t7iUiuHBuRtQ==/com.rjhy.jupiter-teVVGihXH-20dXZc7nWDEw==/base.apk!classes7.dex] (com.tencent.mmkv.MMKV.getString+4)
    runtime.cc:655]   native: #24 pc 000000000067e638  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1808)
    runtime.cc:655]   native: #25 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20)
    runtime.cc:655]   native: #26 pc 00000000004f3308  [anon:dalvik-classes.dex extracted in memory from /data/app/~~QGspzUUso5t7iUiuHBuRtQ==/com.rjhy.jupiter-teVVGihXH-20dXZc7nWDEw==/base.apk] (com.baidao.library.onlineconfig.OnlineConfigSharePreferences.get+12)
    runtime.cc:655]   native: #27 pc 000000000067cc00  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520)
    runtime.cc:655]   native: #28 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20)
    runtime.cc:655]   native: #29 pc 00000000004f2f44  [anon:dalvik-classes.dex extracted in memory from /data/app/~~QGspzUUso5t7iUiuHBuRtQ==/com.rjhy.jupiter-teVVGihXH-20dXZc7nWDEw==/base.apk] (com.baidao.library.onlineconfig.OnlineConfigAgent.getConfigParams+4)
    runtime.cc:655]   native: #30 pc 000000000067cc00  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520)
    runtime.cc:655]   native: #31 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20)
    runtime.cc:655]   native: #32 pc 00000000004f2f26  [anon:dalvik-classes.dex extracted in memory from /data/app/~~QGspzUUso5t7iUiuHBuRtQ==/com.rjhy.jupiter-teVVGihXH-20dXZc7nWDEw==/base.apk] (com.baidao.library.onlineconfig.OnlineConfigAgent.getConfigParams+2)
    runtime.cc:655]   native: #33 pc 000000000067cc00  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1520)
    runtime.cc:655]   native: #34 pc 000000000012d814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20)
    runtime.cc:655]   native: #35 pc 00000000004ddf64  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~QGspzUUso5t7iUiuHBuRtQ==/com.rjhy.jupiter-teVVGihXH-20dXZc7nWDEw==/base.apk!classes2.dex] (com.rjhy.meta.util.VirtualOnLineConfigUtilsKt.getVirtualState+28)
    runtime.cc:655]   native: #36 pc 0000000000305bb8  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4315910075007383753)+268)
    runtime.cc:655]   native: #37 pc 000000000030dba8  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+200)
    runtime.cc:655]   native: #38 pc 000000000030e5a0  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
    runtime.cc:655]   native: #39 pc 000000000067f8b8  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+548)
    runtime.cc:655]   native: #40 pc 000000000012d994  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20)
2022-05-16 21:36:31.044 28233-28233/com.rjhy.jupiter A/om.rjhy.jupite: runtime.cc:655]   native: #41 pc 000000000042750e  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~QGspzUUso5t7iUiuHBuRtQ==/com.rjhy.jupiter-teVVGihXH-20dXZc7nWDEw==/base.apk!classes4.dex] (com.rjhy.meta.widget.VirtualPromotionWidget.<init>+58)
    runtime.cc:655]   native: #42 pc 000000000067f27c  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+1248)
    runtime.cc:655]   native: #43 pc 000000000012d914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20)
    runtime.cc:655]   native: #44 pc 0000000000427598  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~QGspzUUso5t7iUiuHBuRtQ==/com.rjhy.jupiter-teVVGihXH-20dXZc7nWDEw==/base.apk!classes4.dex] (com.rjhy.meta.widget.VirtualPromotionWidget.<init>+20)
    runtime.cc:655]   native: #45 pc 0000000000682594  /apex/com.android.art/lib64/libart.so (MterpInvokeDirectRange+852)
    runtime.cc:655]   native: #46 pc 000000000012dc14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct_range+20)
    runtime.cc:655]   native: #47 pc 00000000004274ba  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~QGspzUUso5t7iUiuHBuRtQ==/com.rjhy.jupiter-teVVGihXH-20dXZc7nWDEw==/base.apk!classes4.dex] (com.rjhy.meta.widget.VirtualPromotionWidget.<init>+22)
    runtime.cc:655]   native: #48 pc 0000000000305bb8  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4315910075007383753)+268)
    runtime.cc:655]   native: #49 pc 000000000066b678  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780)
    runtime.cc:655]   native: #50 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88)
    runtime.cc:655]   native: #51 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
    runtime.cc:655]   native: #52 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    runtime.cc:655]   native: #53 pc 0000000000557498  /apex/com.android.art/lib64/libart.so (art::InvokeConstructor(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::ObjPtr<art::mirror::Object>, _jobject*)+504)
    runtime.cc:655]   native: #54 pc 00000000004c99d0  /apex/com.android.art/lib64/libart.so (art::Constructor_newInstance0(_JNIEnv*, _jobject*, _jobjectArray*)+508)
    runtime.cc:655]   at com.tencent.mmkv.MMKV.decodeString(Native method)

**Comment by lingol** [comment]
> runtime.cc:655] native: #14 pc 000000000036ae84 /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+696)

Looks like you are passing invalid UTF-8 string to MMKV.

**Comment by weiggle** [comment]
是utf-8， 这个问题只有杀掉重启的时候会崩溃一次，在次运行就是好的了，

**Comment by lingol** [comment]
I'm not buying it. You should check it again.

**Comment by lingol** [comment]
Did you find out what's wrong?
