### ISSUE TITLE
Windows平台的版本可以在java上使用吗

### ISSUE THREAD

**Issue by Anivie** [Tencent/MMKV#891]
在win平台的jvm平台应用，比如compss jb，javafx等等，可以使用mmkv的win适配版本吗？好像没有找到这方面的介绍？

**Comment by lingol** [comment]
Hmm...that is a new one. We never think about that. Maybe you could wrap a JNI library on top of MMKV for win32 by your own. That should not be too much work you could follow the Android JNI code.

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/blob/master/Android/MMKV/mmkv/src/main/cpp/native-bridge.cpp
