### ISSUE TITLE
check crc [mmkv.default] fail,

### ISSUE THREAD

**Issue by MasterMvp** [Tencent/MMKV#892]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV
 Java

### The version of MMKV
v1.2.13

### The platform of MMKV
 Android

### The installation of MMKV
Maven

### What's the issue?

MMKV: <MMKV.cpp:395::checkFileCRCValid> check crc [mmkv.default] fail, crc32:2723794466, m_crcDigest:2827865101

**Comment by MasterMvp** [comment]
> The file is corrupted. What else do you want?

mmkv.decodeString("key",""); 使用时,报错,无法拿到数据

**Comment by lingol** [comment]
As I have said, the file is corrupted. You should check your code to find out why it's corrupted.

**Comment by MasterMvp** [comment]
在多线程时使用mmkv读取和写入,这是关闭杀死应用,会造成文件损坏?

**Comment by MasterMvp** [comment]
还会出现 MMKV: <MMKV.cpp:537::getString> InvalidProtocolBuffer truncatedMessage  错误

**Comment by lingol** [comment]
No. It won't.

**Comment by lingol** [comment]
I strongly doubt that you are using MMKV in multi-process.
Let me make it simple for you. Try using the `MULTI_PROCESS_MODE` to get the MMKV instance.

**Comment by MasterMvp** [comment]
好的 , 解决了  初始化时 使用 mmkv = MMKV.mmkvWithID("name", MMKV.MULTI_PROCESS_MODE);  解决
