### ISSUE TITLE
 The Android device is powered off and the parameters are not saved

### ISSUE THREAD

**Issue by Sprinining** [Tencent/MMKV#896]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV
Java
> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV
v1.2.13
> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV
Android
> e.g. iOS or Android

### The installation of MMKV
Maven
> e.g. Cocoapods, Maven, or Git clone

### What's the issue?
The Android device is powered off for a short time, and the set parameters are not saved successfully
> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
The underlying mmap() MMKV uses doesn't guarantee data will sync to disk on lost power, hence MMKV doesn't ensure that. You should manually call `MMKV.sync()` or `MMKV.async()` at some point **if** you really worry about an unexpected power off.
