### ISSUE TITLE
mmkv 初始化失败

### ISSUE THREAD

**Issue by codezwc007** [Tencent/MMKV#899]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

Kotlin

### The version of MMKV
 v1.2.13 

### The platform of MMKV

Android

### The installation of MMKV

 Maven

### What's the issue?

在application的attachBaseContext 方法中进行 MMKV.initialize(context)。但是项目一启动就崩溃。

目前项目支持的架构 abiFilters 'armeabi-v7a', 'arm64-v8a'。

### What's the log of MMKV when that happened?

2022-06-02 20:46:54.765 25512-25512/com.yiqixie.kem.debug E/MMKV: <native-bridge.cpp:74::JNI_OnLoad> fail to register native methods for class com/tencent/mmkv/MMKV, ret = -1
2022-06-02 20:46:54.765 25512-25512/com.yiqixie.kem.debug A/qixie.kem.debu: java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no native method "Lcom/tencent/mmkv/MMKV;.isFileValid(Ljava/lang/String;)Z"
    java_vm_ext.cc:577]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.Class) (Runtime.java:-2)
    java_vm_ext.cc:577]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:1131)
    java_vm_ext.cc:577]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.Class, java.lang.String) (Runtime.java:1085)
    java_vm_ext.cc:577]   at void java.lang.Runtime.loadLibrary0(java.lang.Class, java.lang.String) (Runtime.java:1008)
    java_vm_ext.cc:577]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1664)
    java_vm_ext.cc:577]   at java.lang.String com.tencent.mmkv.MMKV.doInitialize(java.lang.String, java.lang.String, com.tencent.mmkv.MMKV$LibLoader, com.tencent.mmkv.MMKVLogLevel) (MMKV.java:194)
    java_vm_ext.cc:577]   at java.lang.String com.tencent.mmkv.MMKV.initialize(android.content.Context, java.lang.String, com.tencent.mmkv.MMKV$LibLoader, com.tencent.mmkv.MMKVLogLevel) (MMKV.java:181)
    java_vm_ext.cc:577]   at java.lang.String com.tencent.mmkv.MMKV.initialize(android.content.Context) (MMKV.java:84)
    java_vm_ext.cc:577]   at void com.kwai.kim.platform.storage.kv.mmkv.MMKVAgentKt.ensureMMKVInit(android.content.Context) (MMKVAgent.kt:20)

**Comment by lingol** [comment]
> 2022-06-02 20:46:54.765 25512-25512/com.yiqixie.kem.debug A/qixie.kem.debu: java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no native method "Lcom/tencent/mmkv/MMKV;.isFileValid(Ljava/lang/String;)Z"

As the log has tell, the native method isFileValid() is missing. You should check your proguard settings.

**Comment by codezwc007** [comment]
> > 2022-06-02 20:46:54.765 25512-25512/com.yiqixie.kem.debug A/qixie.kem.debu: java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no native method "Lcom/tencent/mmkv/MMKV;.isFileValid(Ljava/lang/String;)Z"
> 
> As the log has tell, the native method isFileValid() is missing. You should check your proguard settings.

没有太好的思路去排查proguard，因为里面东西太多了。
不过 我在 mmkv 1.0.19 上是可以正常运行。但这次做mmkv加密，把mmkv升级到最新版本后就出现这个报错。

**Comment by lingol** [comment]
Well, suit yourself. It's totally up to you.
