### ISSUE TITLE
check crc [mmkv.default] fail, crc32:552857142, m_crcDigest:1502984841

### ISSUE THREAD

**Issue by SYGObject** [Tencent/MMKV#90]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Java

### The version of MMKV

> e.g. v1.0.10

v1.0.11

### The platform of MMKV

> e.g. iOS or Android

Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

AAR

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

In both the main process and the push process, the push process initialization fails

**Comment by lingol** [comment]
Have you pass the `MULTI_PROCESS_MODE` flag when getting the default MMKV instance in multi process usage?
