### ISSUE TITLE
std::bad_alloc

### ISSUE THREAD

**Issue by weilihua** [Tencent/MMKV#900]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> Objective-C

### The version of MMKV

> v1.2.13 

### The platform of MMKV

>  iOS 

### The installation of MMKV

> Cocoapods

### What's the issue?

#31735620 std::bad_alloc
std::bad_alloc
__ZN4mmkv14CodedInputData11readRawByteEv (CodedInputData.cpp:)

#0 Thread
std::bad_alloc
std::bad_alloc
解析原始
0
AppName
mmkv::CodedInputData::readRawByte() (CodedInputData.cpp:0)
1
AppName
mmkv::CodedInputData::readRawLittleEndian64() (CodedInputData.cpp:204)
2
AppName
mmkv::CodedInputData::readDouble() (PBUtility.h:64)
3
AppName
mmkv::MMKV::getDouble(NSString*, double, bool*) (MMKV.cpp:0)

**Comment by lingol** [comment]
It's bad alloc, nothing we can do about it.

**Comment by ramirobg94** [comment]
@lingol other bad_alloc here, maybe you can share strategies to solve the problem here, 
Thanks,

**Comment by lingol** [comment]
@ramirobg94 
It's bad alloc, nothing we can do about it.
