### ISSUE TITLE
Mmkv正常初始化和使用，Release包会频繁出现数据丢失的问题

### ISSUE THREAD

**Issue by Onperson** [Tencent/MMKV#903]
1、redirect logging MMKV========><MiniPBCoder.cpp:285::decodeOneMap> InvalidProtocolBuffer malformed varint32；
2、redirect logging MMKV========><MMKV.cpp:382::checkFileCRCValid> check crc [mmkv.default] fail, crc32:2566490216, m_crcDigest:27015970；
3、redirect logging MMKV========><MMKV.cpp:537::getString> InvalidProtocolBuffer truncatedMessage
4、 redirect logging MMKV========><MMKV.cpp:382::checkFileCRCValid> check crc [mmkv.default] fail, crc32:1025414636, m_crcDigest:3731830670
5、redirect logging MMKV========><MMKV.cpp:537::getString> InvalidProtocolBuffer truncatedMessage
6、redirect logging MMKV========><MMKV.cpp:382::checkFileCRCValid> check crc [mmkv.default] fail, crc32:3308862198, m_crcDigest:44223551
7、redirect logging MMKV========><MMKV.cpp:537::getString> InvalidProtocolBuffer truncatedMessage

当前使用的版本：implementation 'com.tencent:mmkv-static:1.2.3'
Application里面初始化：    String rootDir = MMKV.initialize(this);
使用工具类：
public class SPUtil {
    /**
     * 保存数据的方法，我们需要拿到保存数据的具体类型，然后根据类型调用不同的保存方法
     *
     * @param key key
     * @return value
     */
    public static void put(String key, Object object) {
        if (object == null) {
            return;
        }

        MMKV kv = MMKV.defaultMMKV();

        if (object instanceof String) {
            kv.encode(key, (String) object);
        } else if (object instanceof Integer) {
            kv.encode(key, (Integer) object);
        } else if (object instanceof Boolean) {
            kv.encode(key, (Boolean) object);
        } else if (object instanceof Float) {
            kv.encode(key, (Float) object);
        } else if (object instanceof Long) {
            kv.encode(key, (Long) object);
        } else {
            kv.encode(key, object.toString());
        }
    }

    /**
     * 保存数据的方法，我们需要拿到保存数据的具体类型，然后根据类型调用不同的保存方法
     *
     * @param key key
     * @return value
     */
    public static void putWithUser(String key, Object object) {
        put(AppVariable.userId + key, object);
    }

    /**
     * 得到保存数据的方法，我们根据默认值得到保存的数据的具体类型，然后调用相对于的方法获取值
     *
     * @param key key
     * @param defaultObject defaultObject
     * @return value
     */
    public static Object getWithUser(String key, Object defaultObject) {
        return get(AppVariable.userId + key, defaultObject);
    }

    /**
     * 得到保存数据的方法，我们根据默认值得到保存的数据的具体类型，然后调用相对于的方法获取值
     *
     * @param key key
     * @param defaultObject defaultObject
     * @return value
     */
    public static Object get(String key, Object defaultObject) {

        MMKV kv = MMKV.defaultMMKV();
        if (defaultObject instanceof String) {
            return kv.getString(key, (String) defaultObject);
        } else if (defaultObject instanceof Integer) {
            return kv.getInt(key, (Integer) defaultObject);
        } else if (defaultObject instanceof Boolean) {
            return kv.getBoolean(key, (Boolean) defaultObject);
        } else if (defaultObject instanceof Float) {
            return kv.getFloat(key, (Float) defaultObject);
        } else if (defaultObject instanceof Long) {
            return kv.getLong(key, (Long) defaultObject);
        }

        return defaultObject;
    }

    public static int getInt(String key){
        MMKV kv = MMKV.defaultMMKV();
        return kv.getInt(key,0);
    }
    public static String getString(String key){
        MMKV kv = MMKV.defaultMMKV();
        return kv.getString(key,"");
    }
}

**Comment by lingol** [comment]
Your file is corrupted. It's highly possible that you are using that MMKV in multi-process without setting `MMKV.MULTI_PROCESS_MODE`.

**Comment by Onperson** [comment]
I am sure that wasn't use multi-process without setting MMKV.MULTI_PROCESS_MODE, And It all right before.Just show up 
in Release mode,I wonder why?

**Comment by lingol** [comment]
Here's a quit test you can do.
>   MMKV kv = MMKV.defaultMMKV();

Just change it to
>   MMKV kv = MMKV.defaultMMKV(MMKV.MULTI_PROCESS_MODE, null);

 And see what happens.

**Comment by Onperson** [comment]
2022-06-11 13:20:14.056 10053-13425/? E/QzoneConfig: key = qzonesetting secondaryKey= isusemmkv value= 1
This error is ok?
Thanks, It works.But i still don't understand why that error get happened when run release mode ,But didn‘t happen in Debug mode.

**Comment by lingol** [comment]
That log isn't from MMKV. I can't possibly comment about it.

**Comment by lingol** [comment]
I have said it's corrupted and provide a solution.
What are you messing around with? Do you even know what you are talking about?

**Comment by lingol** [comment]
>But i still don't understand why that error get happened when run release mode ,But didn‘t happen in Debug mode.

There's nothing magical about it. You **ARE** in fact using MMKV in multi-process. What is weird is that this shit doesn't happen in your debug code. I guess somehow in debug build, your code won't access it at the same time or won't be multi-process.

**Comment by Onperson** [comment]
![image](https://user-images.githubusercontent.com/8013937/173034333-23855b0a-fc1e-4a9f-a843-395180557d7b.png)

Changes got this happened,But file is empty.
