### ISSUE TITLE
mmkv1.2.13 Internal  crash

### ISSUE THREAD

**Issue by GE-GAO-ZHAO** [Tencent/MMKV#905]
## crash stack

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: 0x00000000 at 0x0000000000000000
Crashed Thread:  0

// 崩溃线程
Thread 0 Crashed:
0      CoreFoundation                	0x18c01f000 + 79020 
1      CoreFoundation                	0x18c01f000 + 79016 
2      Foundation                    	0x18d80d000 + 362000 
3      Foundation                    	0x18d80d000 + 562972 
4      MMKVCore                      	mmkv::MMKV::set(NSObject objcproto8NSCoding*, NSString*)	MMKV_OSX.cpp:162

## key information 
磁盘(已用/总共): 26.39G/119.18G
内存(已用/总共):108.00M/2.89G
用户使用时长: 16小时58分钟27秒

**Comment by lingol** [comment]
Please provide symbolized call stacks.
