### ISSUE TITLE
Bitcode failed to compile for your watchOS binary

### ISSUE THREAD

**Issue by ChenYalun** [Tencent/MMKV#907]
Invalid Bundle - Bitcode failed to compile for your watchOS binary because it includes assembly source code or inline assembly. To resolve this issue, rewrite the corresponding code in a higher-level language such as Objective-C or Swift and redeliver your app.

**Comment by lingol** [comment]
What is your dev setting such as Xcode version etc? And it's good to provide a reproducible demo project.
Can you build the demo project from this repo?

**Comment by lingol** [comment]
What is your dev setting such as Xcode version etc? And it's good to provide a reproducible demo project.
Can you build the demo project from this repo?
