### ISSUE TITLE
mmkv APIs differences between lock and try_lock?

### ISSUE THREAD

**Issue by SollyTaylor** [Tencent/MMKV#908]
Are there any differences between lock() and try_lock() and in what scenarios should I use lock() and try_lock()? 

For using lock() and try_lock(). It seems that try_lock() is more secure to access the data if I use the return bool to make sure I've got the lock.  Does it mean the lock() API could be replaced by try_lock()? Should I use try_lock() ( or lock() ) each time I read and write the data if I use MMKV in Multi-Process Mode?

What is the best practice? of using lock() and try_lock() for Multi-Processes Mode?

Thanks.

**Comment by lingol** [comment]
The only difference is that `lock()` will hold your process/thread until it gets the lock. `try_lock()` will return immediately whether it gets the lock or not.

**Comment by SollyTaylor** [comment]
For the reading Process 1:
`lock();   /*read some values*/    unlock(); `
For the writing Process 2:
`lock();   /*write some values*/    unlock(); `

Is the pseudocode above matching the logics of original design?

**Comment by lingol** [comment]
No. You should never do that. In fact, you should never call `lock() or `try_lock()`. MMKV already handles inter-process very well. There's no reason for a dev to call these locking methods manually.

**Comment by SollyTaylor** [comment]
Crystal Clear.
