### ISSUE TITLE
如何扩展存储加密算法？

### ISSUE THREAD

**Issue by Dullyoung** [Tencent/MMKV#911]
项目需求 要对数据进行AES256加密，但MMKV默认加密方式AES128 ，如何扩展？

**Comment by lingol** [comment]
That's an interesting question. I will think about it and come back to you later.

**Comment by Dullyoung** [comment]
> That's an interesting question. I will think about it and come back to you later.

Thanks for your help.

**Comment by lingol** [comment]
I have taken a review of MMKV's encryption design. It looks like the 128bit key length is hard coded in the code and I haven't thought of a better way to **support 256bit without losing performance**.

So, the short answer, you have to **modify the code**.
Here's how it could be done. In the file [MMKVPredef.h](https://github.com/Tencent/MMKV/blob/master/Core/MMKVPredef.h#L199), modify those two lines
```cpp
constexpr size_t AES_KEY_LEN = 16;
constexpr size_t AES_KEY_BITSET_LEN = 128;
```
into
```cpp
constexpr size_t AES_KEY_LEN = 32;
constexpr size_t AES_KEY_BITSET_LEN = 256;
```
And set MMKV's encryption key to a 32 byte length string/buffer.

**Comment by lingol** [comment]
https://github.com/Tencent/MMKV/tree/dev_aes256

**Comment by Dullyoung** [comment]
> I have taken a review of MMKV's encryption design. It looks like the 128bit key length is hard coded in the code and I haven't thought of a better way to **support 256bit without losing performance**.
> 
> So, the short answer, you have to **modify the code**. Here's how it could be done. In the file [MMKVPredef.h](https://github.com/Tencent/MMKV/blob/master/Core/MMKVPredef.h#L199), modify those two lines
> 
> ```c++
> constexpr size_t AES_KEY_LEN = 16;
> constexpr size_t AES_KEY_BITSET_LEN = 128;
> ```
> 
> into
> 
> ```c++
> constexpr size_t AES_KEY_LEN = 32;
> constexpr size_t AES_KEY_BITSET_LEN = 256;
> ```
> 
> And set MMKV's encryption key to a 32 byte length string/buffer.

It is not a perfect way that if i change the encryption algorithm by myself.First , I need download MMKV project and imp it into my project as a module.Second ,Maybe I will forget this change when update MMKV in the future.I prefer to use different API rather than modify NDK.I hope you can add this support in next upgrade.Thanks very much!

**Comment by lingol** [comment]
No, we won't add it in the official release.

**Comment by Dullyoung** [comment]
> No, we won't add it in the official release.

Thanks anyway!

**Comment by lingol** [comment]
MMKV v2.3.0 provides AES-256 key length. http://github.com/Tencent/mmkv/releases/tag/v2.3.0

**Comment by Dullyoung** [comment]
> MMKV v2.3.0 provides AES-256 key length. [http://github.com/Tencent/mmkv/releases/tag/v2.3.0](https://github.com/Tencent/mmkv/releases/tag/v2.3.0)

Thank you, but it's been three years, and I don't even remember why I needed it.
