### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by zmxmu** [Tencent/MMKV#912]
### The language of MMKV

Java and Kotlin

### The version of MMKV
1.2.13

### The platform of MMKV

Android

### The installation of MMKV
Clone the source code of MMKV to our own git server without any modification, and build our own mmkv library version 
Our main app use maven to depend on the library.

### What's the issue?

我们这个app有非常大的用户体量,采用了MMKV 安卓项目 ,但是最近一直困扰占比非常高的线上crash,采取了很多办法 包括更新MMKV到最新的 版本都无法解决 
crash描述: Fatal Exception: java.lang.UnsatisfiedLinkError ,dlopen failed: "/data/data/com.xxx.xxx/files/splitcompat/631/native-libraries/config.arm64_v8a/libmmkv.so" is 64-bit instead of 32-bit .我发现你们之前github上处理过这个issue,但是都是直接close,并没给出具体的修改措施.希望能再关注下这个问题,给出一些具体的处理建议
以下是英文描述:
The main difference of our MMKV and official MMKV is that we build the source code of MMKV and deploy it to our own maven server, during the building , we add the parameter as below:
packagingOptions {
    doNotStrip "*/*/*.so"
}
So that the so file can include symbol table
I am not sure whether it will cause such crash
### What's the log of MMKV when that happened?
![image](https://user-images.githubusercontent.com/7310288/175007711-58540481-833b-4b92-9b43-acd30c80d00a.png)

**Comment by lingol** [comment]
For example https://repo1.maven.org/maven2/com/tencent/mmkv/1.2.12/
<img width="630" alt="image" src="https://user-images.githubusercontent.com/2088859/175009561-6eb7ce2f-0c8c-470d-8c20-422faf552168.png">

**Comment by lingol** [comment]
And for the `dlopen()` failure, or the well-known `java.lang.UnsatisfiedLinkError`, here is the solution to every similar question:
**Google about it.**

**Comment by zmxmu** [comment]
We have already checked that all `.so` files packaged in the APK are correct CPU architecture. (No mixing of 32bit and 64bit). But this problem still happened. Otherwise we will not report here ,can you give me more indications? Thanks
