### ISSUE TITLE
能否支持OpenHarmony JS版本？

### ISSUE THREAD

**Issue by hzjust** [Tencent/MMKV#913]
I am developing an OpenHarmony application that uses the JavaScript language. Can you support the OpenHarmony JavaScript version? I am willing to participate in the development and look forward to reply.

**Comment by lingol** [comment]
What's OpenHarmony JS?

**Comment by lingol** [comment]
So I did a little digging and (surprisingly) found out that the OpenHarmony community already has an MMKV port.
https://gitee.com/openharmony-tpc/MMKV
Maybe that will solve your request.

**Comment by lingol** [comment]
Oh, looks like you're the [hzjust](https://gitee.com/openharmony-tpc/MMKV/commits/master?user=380861714@qq.com) that migrated MMKV to OpenHarmony. 
What's your problem with the migration? And how can I help you?
