### ISSUE TITLE
多线程情况下，主进程保存的值，子进程可以拿到，子进程保存的值，主进程拿不到。

### ISSUE THREAD

**Issue by w296488320** [Tencent/MMKV#917]
我这边有两条线程在工作
我在主进程初始化了一下mmkv，代码如下
```
    //初始化文件路径
    MMKV::initializeMMKV(path);
    //支持跨线程
    MMKV *pMmkv = MMKV::mmkvWithID("ZhenxiRuntime", MMKV_MULTI_PROCESS);
    //关闭日志
    MMKV::setLogLevel(MMKVLogNone);
```

初始化完毕以后我在fork出来一条进程，在子进程里面保存一下fork进程的pid
主进程尝试去哪子进程保存的pid , 主进程拿不到了，请问这个时候我需要在fork子进程重新初始化一下mmkv么？

**Comment by lingol** [comment]
You should put `MMKV.initializedMMKV()` after `fork()`. There's nothing inside MMKV that should be shared between root and child processes.
Check out POSIX demo code for example. https://github.com/Tencent/MMKV/blob/master/POSIX/demo/demo.cpp#L173

**Comment by w296488320** [comment]
我是放在initializedMMKV后面进行的fork
1，我在fork的进程还需要初始化一次么？
2，main进程我延迟5秒读取子进程set的值，我在fork出来的进程进行set value 。但是main进程一直读到的是失败 。
但是如果主进程初始化以后进行set，子进程是可以拿到的。
