### ISSUE TITLE
SIGBUS BUS_ADRALN __ZN4mmkv14CodedInputData11readRawByteEv (CodedInputData.cpp:)

### ISSUE THREAD

**Issue by weilihua** [Tencent/MMKV#918]
## Note:
without logs

### The language of MMKV

> Objective-C

### The version of MMKV

> v1.2.13  

### The platform of MMKV

> iOS 

### The installation of MMKV

> Cocoapods

### What's the issue?

#31356829 SIGBUS
BUS_ADRALN 
__ZN4mmkv14CodedInputData11readRawByteEv (CodedInputData.cpp:)

1.mmkv::CodedInputData::readRawByte() (CodedInputData.cpp:222) 
2.mmkv::CodedInputData::readRawVarint32() (CodedInputData.cpp:160) 
3.mmkv::CodedInputData::readRawVarint32() (CodedInputData.cpp:160)
4.mmkv::CodedInputData::readString() (CodedInputData_OSX.cpp:38)
5.mmkv::MiniPBCoder::decodeObject(mmkv::MMBuffer const&, objc_class*) (MiniPBCoder_OSX.cpp:0)
6.mmkv::MMKV::getObject(NSString*, objc_class*) (MMKV_OSX.cpp:0)
7.-[MMKV getStringForKey:defaultValue:hasValue:] (libMMKV.mm:466)

### What's the log of MMKV when that happened?
None

**Comment by lingol** [comment]
That's impossible to investigate. You should provide logs. And the corrupt mmkv file (the crc file as well ) if possible.

**Comment by lingol** [comment]
Closed due to inactive.
