### ISSUE TITLE
macos平台内存泄露

### ISSUE THREAD

**Issue by CaicaiNo** [Tencent/MMKV#919]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

Objective-C

### The version of MMKV

v1.2.13

### The platform of MMKV

macos

### The installation of MMKV

 Git clone, use source code

### What's the issue?

在macos平台上使用时，leaks检测部分内存泄露

```c
0	_malloc_zone_calloc	libsystem_malloc.dylib	
1	_CFRuntimeCreateInstance	CoreFoundation	
2	__CFStringCreateImmutableFunnel3	CoreFoundation	
3	_CFNonObjCStringCreateCopy	CoreFoundation	
4	_CFStringCreateWithFormatAndArgumentsReturningMetadata	CoreFoundation	
5	_CFStringCreateWithFormatAndArgumentsAux2	CoreFoundation	
6	_MMKVLogWithLevel(mmkv::MMKVLogLevel, char const*, char const*, int, char const*, ...)	libmmkvd.dylib	
7	mmkv::MMKV::clearMemoryCache()	libmmkvd.dylib	

```

我尝试使用这样，添加注释部分代码后，没有发生泄露
```c
void _MMKVLogWithLevel(MMKVLogLevel level, const char *filename, const char *func, int line, const char *format, ...) {
    if (level >= g_currentLogLevel) {
//        @autoreleasepool {
            NSString *nsFormat = [NSString stringWithUTF8String:format];
            va_list argList;
            va_start(argList, format);
            NSString *message = [[NSString alloc] initWithFormat:nsFormat arguments:argList];
            va_end(argList);

            if (g_logHandler) {
                g_logHandler(level, filename, line, func, message);
            } else {
                NSLog(@"[%s] <%s:%d::%s> %@", MMKVLogLevelDesc(level), filename, line, func, message);
            }
//            [message release];
//        }
    }
}
```
macos平台是c++写的，外部没有iOS的runloop，且 MMKVLog.cpp 没有设置为 mrc

![image](https://user-images.githubusercontent.com/17329515/178641675-ad9f11cd-2e3b-4f12-81bb-c589943c8661.png)

然而令我感到诧异的是，MMKVLog.cpp 似乎使用的 mrc ，我能够使用 release 方法。

这个问题是否是平台差异性，麻烦确认下是否有这样的问题

**Comment by lingol** [comment]
Can you provide a **demo project** that you can call `-[NSObject release]` inside MMKVLog.cpp?

**Comment by lingol** [comment]
I have tried it on a purely newly created macOS App project, installing MMKV by CocoadPods. The result is that it will fail to compile if `release` is called.
You should check your project setting. As far as I can see, it's none of MMKV's fault.

**Comment by CaicaiNo** [comment]
`-[NSObject release]` 不是mmkv的问题，是我工程配置遗漏问题。 thanks

**Comment by lingol** [comment]
And no, MMKVLog.cpp is **NOT** written in C++ in macOS/iOS even though it has the suffix of .cpp. It's in ObjC++.
