### ISSUE TITLE
调用 clearAll()后 ,添加数据失败

### ISSUE THREAD

**Issue by eycrckag** [Tencent/MMKV#920]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Java

     SpUtils.get(mContext).clearAll();

        SpUtils.get(mContext).put(Constants.SP_KEY_AGREE_USER_AGREEMENT,1);
        SpUtils.get(mContext).put(Constants.V5_GUIDE_VIEW_CONTROL,1);

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
Please follow the issue template to provide the information needed to further investigate.
