### ISSUE TITLE
lib/arm64-v8a/libmmkv.so is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by MrBalck** [Tencent/MMKV#921]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by MrBalck** [comment]
.apk/lib/arm64-v8a/libmmkv.so" is 64-bit instead of 32-bit
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:194)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:181)
        at com.tencent.mmkv.MMKV.initialize(MMKV.java:84)

**Comment by lingol** [comment]
> .apk/lib/arm64-v8a/libmmkv.so" is 64-bit instead of 32-bit

The error log is crystal clear. It's not MMKV's problem and we can't do anything about it.
Check your apk/aab and Google about it.
