### ISSUE TITLE
Why don't set MMKV.MULTI_PROCESS_MODE as the default parameter

### ISSUE THREAD

**Issue by zmxmu** [Tencent/MMKV#922]
As many app use multi process, but in your wiki and guild line ,there is none indication for us to set the parameter MMKV.MULTI_PROCESS_MODE, I just find it in your source code .
Why don't set MMKV.MULTI_PROCESS_MODE as the default parameter
If I set it as default value but run in the main process, will it cause any side effect or bugs ?
If don't set MMKV.MULTI_PROCESS_MODE in multi process app, will it cause another crash issue which I have submitted before
https://github.com/Tencent/MMKV/issues/912

Thanks for your reply.

**Comment by lingol** [comment]
The last time I checked, it's on the wiki. https://github.com/Tencent/MMKV/wiki/android_tutorial

As for why not set it as default, we believe you should **pay for what you get**, no more, no less. Turning on multi-process-mode does have some performance costs.
