### ISSUE TITLE
mmkv存储的数据在鸿蒙设备上经常丢失,不知道大家有没有遇到过

### ISSUE THREAD

**Issue by SmallerRui** [Tencent/MMKV#924]
app覆盖安装,或者app后台以后,直接清掉进程,再次启动就会丢失,已经在好几个鸿蒙设备上经常出现

**Comment by lingol** [comment]
You should provide logs.

**Comment by lingol** [comment]
Looks like you are using MMKV in multiple processes without setting multi-process-mode.

**Comment by SmallerRui** [comment]
@lingol  Yes, I did use it in multi-process without turning on multi-process mode. I’ll turn it on and check it out. Thanks!

**Comment by lvjiancong** [comment]
https://github.com/Tencent/MMKV/issues/924#issue-1324018322当数据丢失时，是所有的历史数据都清空吗？

**Comment by lvjiancong** [comment]
> app覆盖安装,或者app后台以后,直接清掉进程,再次启动就会丢失,已经在好几个鸿蒙设备上经常出现

你好，当出现数据丢失时，是所有历史数据都会清空吗？

**Comment by lingol** [comment]
Don't spam. @lvjiancong
