### ISSUE TITLE
MMKV stores the object Crash because NSKeyedArchiver is used internally.

### ISSUE THREAD

**Issue by GE-GAO-ZHAO** [Tencent/MMKV#933]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

MMKV stores the object Crash because NSKeyedArchiver is used internally. May I ask whether you have encountered, how to avoid this problem ?

### The stack is as follows:

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: 0x00000000 at 0x0000000000000000
Crashed Thread:  47

// 崩溃线程
Thread 47 Crashed:
0      CoreFoundation                	___CFBinaryPlistWriteOrPresize
1      CoreFoundation                	___CFBinaryPlistWriteOrPresize
2      Foundation                    	-[NSKeyedArchiver finishEncoding]
3      Foundation                    	+[NSKeyedArchiver archivedDataWithRootObject:]
4      MMKVCore                      	mmkv::MMKV::set(NSObject objcproto8NSCoding*, NSString*)	MMKV_OSX.cpp:162

**Comment by lingol** [comment]
And what do you suggest?

**Comment by lingol** [comment]
Garbage in garbage out, I think. So I should close this issue by now unless you have more to say.
