### ISSUE TITLE
the ndk and cmake version numer for each release

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#934]
For each formal release build, would you public the version number of ndk and make you are using?

Thanks.

**Comment by lingol** [comment]
The MMKV so is an all-in-one shared library. The NDK should not be a problem. Why would you be concerned about it?

**Comment by lingol** [comment]
The last version v1.2.14 is built with NDK 21.4.7075529 and CMake 3.18. FYI.

**Comment by samlu** [comment]
I am going to build an MMKV without using any encryption APIs, and would like to use the same NKD/CMAKE version as you did so it won't cause any unexpected results.

You can specify the ndk version by adding android.ndkVersion "21.4.7075529" or note the version number is the CHANGELOG.md file.
https://developer.android.com/studio/projects/install-ndk#apply-specific-version
