### ISSUE TITLE
checkFileCRCValid error when using 1.2.14

### ISSUE THREAD

**Issue by samlu** [Tencent/MMKV#935]
MMKV 1.2.14 static version on Android 6.0 emulator

* no error when using MMKV 1.2.12
* test with the fresh install so a CRC error seems strange
* will share more information with you if I have

1.2.14 log
=============================
```
D/blMmkv: <init>░init: begin, static link c++ functions
I/MMKV: Enable checkProcessMode()
D/blMmkv$1: loadLibrary░load: begin, lib name=mmkv, process=main
D/blMmkv$1: loadLibrary░load: end
D/blMmkv: <init>░init: end
D/blMmkv: _CreateMmkvFile░create a [_comm] mmkv file
D/MMKV: MemoryFile.cpp:97::open: open fd[0x14], /data/user/0/com.xxx.debug/app_mmkv/_comm
D/MMKV: MemoryFile.cpp:97::open: open fd[0x15], /data/user/0/com.xxx.debug/app_mmkv/_comm.crc
W/MMKV: MMKV.cpp:395::checkFileCRCValid: check crc [_comm] fail, crc32:0, m_crcDigest:3021209604
    java.lang.Exception: MMKV.cpp:395::checkFileCRCValid: check crc [_comm] fail, crc32:0, m_crcDigest:3021209604
        at com.tencent.mmkv.MMKV.mmkvLogImp(MMKV.java:1236)
        at com.tencent.mmkv.MMKV.getMMKVWithID(Native Method)
        at com.tencent.mmkv.MMKV.mmkvWithID(MMKV.java:377)
        at com.xxx.blMmkv._CreateMmkvFile(blMmkv.java:321)   
D/MMKV: Thread.java:818::run: Recover strategic for _comm is OnErrorDiscard
D/MMKV: MMKV_IO.cpp:235::checkDataValid: recover strategic for [_comm] is 0
D/MMKV: MMKV_IO.cpp:81::loadFromFile: loading [_comm] with 0 actual size, file size 4096, InterProcess 1, meta info version:0
D/MMKV: MMKV_IO.cpp:130::loadFromFile: loaded [_comm] with 0 key-values
D/blMmkvFile: <init>░/data/user/0/com.xxx.debug/app_mmkv/_comm, id=_comm, mmkv handler=0xaa3c9b20
```

1.2.12 log
===================================================
```
D/blMmkv: <init>░init: begin, static link c++ functions
I/MMKV: Enable checkProcessMode()
D/blMmkv$1: loadLibrary░load: begin, lib name=mmkv, process=main
I/MMKV: <native-bridge.cpp:104::JNI_OnLoad> current API level = 23, libc++_shared=0
D/blMmkv$1: loadLibrary░load: end
I/MMKV: <MMKV.cpp:165::initialize> version v1.2.12, page size 4096, arch x86
I/MMKV: <MMKV.cpp:207::initializeMMKV> root dir: /data/user/0/com.xxx.debug/app_mmkv
D/blMmkv: <init>░init: end
D/blMmkv: _CreateMmkvFile░create a [_comm] mmkv file
D/MMKV: MemoryFile.cpp:97::open: open fd[0x13], /data/user/0/com.xxx.debug/app_mmkv/_comm
D/MMKV: MemoryFile.cpp:97::open: open fd[0x14], /data/user/0/com.xxx.debug/app_mmkv/_comm.crc
D/MMKV: MMKV_IO.cpp:81::loadFromFile: loading [_comm] with 0 actual size, file size 4096, InterProcess 1, meta info version:0
D/MMKV: MMKV_IO.cpp:130::loadFromFile: loaded [_comm] with 0 key-values
D/blMmkvFile: <init>░/data/user/0/com.xxx.debug/app_mmkv/_comm, id=_comm, mmkv handler=0xae6643f0
```

**Comment by lingol** [comment]
What do you mean by saying "test with the fresh install"? Does the error happen on a fresh install App's very first launch?

**Comment by samlu** [comment]
The "fresh install" means no previous version of apk installed and no mmkv files existed.
The apk is first installed on the emulator.

**Comment by lingol** [comment]
I can't reproduce such an error on a fresh installed App on the device. 
Looks like the `_comm.crc` file is not clear while the `_com` file does. Maybe you should check about that on your emulator.

**Comment by samlu** [comment]
* uninstall the app before the test so `_comm.crc` is newly created. I also check the filesystem and make sure the file does not exist
* NDK 25.0.8775105 + CMake 3.22.1 release build -> checkFileCRCValid error
* NDK 25.0.8775105 + CMake 3.22.1 debug build -> no error (so it looks like the problem is caused by the code optimizer) 
* NDK 21.4.70755295 + CMake 3.18.1 release build -> no error
FYI.

**Comment by lingol** [comment]
Strange indeed. I will look into it later.

**Comment by lingol** [comment]
Can you reproduce this error on the device too?
>NDK 25.0.8775105 + CMake 3.22.1 release build -> checkFileCRCValid error

**Comment by lingol** [comment]
I can't reproduce this error on an x86 emulator, or on any devices, with the same NDK configuration.

**Comment by samlu** [comment]
Here are the test results:

mmkv 1.2.14 with ndk 25 release build
* Android 6.0 (emulator, system-images\android-23\google_apis\x86\) - checkFileCRCValid error
* Android 6.0 (emulator, system-images\android-23\default\x86\) - checkFileCRCValid error
* Android 6.0 (emulator, system-images\android-23\google_apis\x86_64\) - checkFileCRCValid error
* Android 6.0.1 (Samsung Note 4) - no error
* Android 7.1.1 (emulator, system-images\android-25\google_apis_playstore\x86\) - no error
* Android 12 (Pixel 3 XL) - no error

My compiled mmkv.aar can be downloaded on [https://drive.google.com/file/d/1OAxHHweftTxkug-ZfkGmbCx-DbrkzILm/view?usp=sharing](url).

It seems that the problem only happens on the Android 6 emulator. I think you can close this ticket as it may be caused by the system image (PS: I always use the latest revision of the system image).
