### ISSUE TITLE
找不到so包

### ISSUE THREAD

**Issue by ly469097645** [Tencent/MMKV#936]
### The language of MMKV

> Kotlin

### The version of MMKV

>  v1.2.14

### The platform of MMKV

> Android

### The installation of MMKV

>  Maven

### What's the issue?
在GP后台，发现了一些崩溃，问题在于高版本手机提示无法找到libmmkv.so，初始化的时候导致了异常，这块需要我做什么修改吗，感谢回复

![image](https://user-images.githubusercontent.com/12133597/184277343-d9d828f1-1fe8-4a69-b13c-5b2e6721d42c.png)

**Comment by lingol** [comment]
We don't accept issues on `UnsatisfiedLinkError` anymore. As it's clearly out of the reach of a library developer.

**Comment by mikelhm** [comment]
https://blog.csdn.net/xiaobaaidaba123/article/details/127250141?spm=1001.2014.3001.5502 this helps me fix the problem.
