### ISSUE TITLE
Android /mmkv/xxx_mtype  file not found occasionally

### ISSUE THREAD

**Issue by 13120241790** [Tencent/MMKV#937]
By MMKV version: 'com.tencent:mmkv-static:1.2.11'

Key Value get set failed  log:

![image](https://user-images.githubusercontent.com/10265829/184791921-07644060-53ec-4233-b8ed-f4e7bd09bd7f.png)
![image](https://user-images.githubusercontent.com/10265829/184791969-8b6e6d05-0e97-4f33-a385-e647eec9cb51.png)

Occasionally, there are cross process requirements

Usage：

In Application ： 

```java
 private static void init(Context context) {
        synchronized (MMKVSharedPreferencesFactory.class) {
            if (!isInit) {
                MMKV.initialize(context.getApplicationContext());
                isInit = true;
            }
        }
    }
```

In SplashActivity 
```java
Key Value get set failed

```

Full log：

[log-0(1).txt](https://github.com/Tencent/MMKV/files/9347718/log-0.1.txt)

Thank you very much for helping me troubleshoot this problem

**Comment by lingol** [comment]
Looks like your App doesn't have the right to create folders in that dictionary.
>08-16 10:56:10.574  2162  2162 W MMKV    : <MemoryFile.cpp:273::mkPath> /data/user/0/com.thunder.ktv/files/mmkv : Permission denied

**Comment by 13120241790** [comment]
![image](https://user-images.githubusercontent.com/10265829/184794871-d93c5ecf-fd8e-4927-a1f6-70527b7751a7.png)
I have the correct initialization in Application. this problem occurs occasionally. Not every device appears

During initialization 
```java
 MMKV.initialize(context.getApplicationContext());
```

In addition,
```java
    private MMKV getMmkvType() {
        synchronized (this) {
            if (mmkvType == null) {
                if (mode == Context.MODE_MULTI_PROCESS) {
                    mmkvType = MMKV.mmkvWithID(fileName + TYPE_SUFFIX, MMKV.MULTI_PROCESS_MODE);
                } else {
                    mmkvType = MMKV.mmkvWithID(fileName + TYPE_SUFFIX);
                }
            }
        }
        return mmkvType;
    }

```
 was called。

Can you read all my logs to help analyze why the initialization failed to create folders or files? Is it useful to upgrade the latest mmkv version?

**Comment by lingol** [comment]
Sorry but there's nothing I can do for you. You should check why your App doesn't have the right to create folders.

**Comment by 13120241790** [comment]
OK, thank you. I'll check myself again @lingol
