### ISSUE TITLE
ios 内存泄露

### ISSUE THREAD

**Issue by hulong121** [Tencent/MMKV#938]
Hi, 我使用ios版mmkv时发现xcode的leaks检测工具报内存泄露，疑似代码在MMKV_IO.cpp的setDataForKey函数里最后return前的[key retain];我不确定是否是leaks检测工具误报，于是进行了一个测试，创建test工程，引入mmkv，在线程中每间隔2秒执行1000次strString函数，value值填写固定字符串@"abcxyz"，key采用随机字符串[NSString stringWithFormat:@"aaa%ld", random()];然后debug运行，可以在xcode内存界面看到内存一直上涨，并且我在mmkv所有release的函数都加上断点，并没有触发断点。我尝试修改了一下mmkv源码，将[key retain];删除，重新进行刚才的测试，内存稳定，没有上涨，测试过程中没有遇到crash。
我不确定删除[key retain];后是否可能会导致bad access，所以还不太敢在线上版本进行修改，所以想请开发人员确认一下[key retain];这里是否会导致内存泄露呢？如果不会的话，那是有哪里需要注意的吗，为什么我的测试工程内存会一张上涨呢？
mmkv版本1.12.10（我看了一下当前最新版本1.12.14还是有[key retain];的），麻烦解答一下，谢谢。

**Comment by lingol** [comment]
There's no leak. I'm sure about that. You should check your project.

**Comment by lingol** [comment]
Why not upload your demo project and let's check it.

**Comment by hulong121** [comment]
[testmmkv.zip](https://github.com/Tencent/MMKV/files/9355683/testmmkv.zip)
Hi, i already upload the test project, please check it, thanks.

**Comment by lingol** [comment]
There's no leak.

**Comment by lingol** [comment]
Here is how to test leak properly. Make an exit point and check the memory footprint after the exit point, aka `[mmkv close]`.
```objc
-(void)runTest
{
    MMKV *mmkv = [MMKV defaultMMKV];
    int count = 0;
    while (true) {
        //NSLog(@"runTest");
        
        for (int i=0; i<1000; ++i)
        {
            [mmkv setString:@"abcxyz" forKey:[NSString stringWithFormat:@"keyrand%ld", random()]];
        }
        sleep(2);
        count ++;
        if (count == 10) {
            break;
        }
    }
    [mmkv close];
}
```

**Comment by klaus01** [comment]
同样的问题。
对 key 的引用，需要 close 才能释放吗？不合适。
