### ISSUE TITLE
Application的attachBaseContext里面初始化MMKV后马上调用getMMKV的话，会抛异常

### ISSUE THREAD

**Issue by alen252** [Tencent/MMKV#940]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV

> Java

### The version of MMKV

> v1.0.15 
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

### The platform of MMKV

> Android

### The installation of MMKV

> Maven

### What's the issue?
Application的attachBaseContext里面初始化MMKV后马上调用getMMKV的话，会抛异常

    java.lang.ExceptionInInitializerError

**Comment by lingol** [comment]
Please provide details on the exception, logs from logcat and full crash stacks.

**Comment by lingol** [comment]
Yes?

**Comment by alen252** [comment]
> Yes?

The other crash stacks is my project code.

**Comment by lingol** [comment]
No logs no investigation.
