### ISSUE TITLE
ReactNative cocoapods Issue

### ISSUE THREAD

**Issue by shadyashraf96** [Tencent/MMKV#955]
### The version of MMKV

> e.g. v2.4.3

xcode version: 13.4
react native version v.0.68.2

### The platform of MMKV

React Native IOS

### The installation of MMKV

Cocoapods,

I attached my Podfile

[Podfile.txt](https://github.com/Tencent/MMKV/files/9620151/Podfile.txt)

### What's the issue?
I'm getting an error on xcode when I build the project meanwhile it works perfectly on android. 
I used yarn add react-native-mmkv then cd ios && pod install as usual. without doing a thing more it fails to build

> Post the outputs or screenshots for errors.
`Showing Recent Messages
WriteAuxiliaryFile /Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/react-native-mmkv.build/react_native_mmkv-all-target-headers.hmap (in target 'react-native-mmkv' from project 'Pods')
    cd /Users/shady/ReactNative/{projectname}/ios/Pods
    write-file /Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/react-native-mmkv.build/react_native_mmkv-all-target-headers.hmap

Ld /Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/react-native-mmkv/react_native_mmkv.framework/react_native_mmkv normal (in target 'react-native-mmkv' from project 'Pods')
    cd /Users/shady/ReactNative/{projectname}/ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios11.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -L/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/react-native-mmkv -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/react-native-mmkv -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/DoubleConversion -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/MMKV -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/MMKVCore -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/RCT-Folly -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/React-Core -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/React-cxxreact -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/React-jsi -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/React-jsiexecutor -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/React-jsinspector -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/React-logger -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/React-perflogger -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/Yoga -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/fmt -F/Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/glog -filelist /Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/react-native-mmkv.build/Objects-normal/arm64/react_native_mmkv.LinkFileList -install_name @rpath/react_native_mmkv.framework/react_native_mmkv -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/react-native-mmkv.build/Objects-normal/arm64/react_native_mmkv_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -framework CoreFoundation -framework JavaScriptCore -framework MMKV -framework React -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/react-native-mmkv.build/Objects-normal/arm64/react_native_mmkv_dependency_info.dat -o /Users/shady/Library/Developer/Xcode/DerivedData/{projectname}-gfafazkzgpagvbbepmhhubzruhut/Build/Products/Debug-iphoneos/react-native-mmkv/react_native_mmkv.framework/react_native_mmkv

Undefined symbols for architecture arm64:
  "facebook::jsi::Value::asObject(facebook::jsi::Runtime&) const &", referenced from:
      -[MmkvModule install:]::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvModule.o
  "facebook::jsi::Value::asString(facebook::jsi::Runtime&) const &", referenced from:
      +[MmkvModule getPropertyAsStringOrNilFromObject:propertyName:runtime:] in MmkvModule.o
  "vtable for facebook::jsi::HostObject", referenced from:
      facebook::jsi::HostObject::HostObject() in MmkvHostObject.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "typeinfo for facebook::jsi::HostObject", referenced from:
      typeinfo for MmkvHostObject in MmkvHostObject.o
  "facebook::jsi::Value::Value(facebook::jsi::Runtime&, facebook::jsi::Value const&)", referenced from:
      facebook::jsi::detail::toValue(facebook::jsi::Runtime&, facebook::jsi::Value const&) in JSIUtils.o
  "typeinfo for facebook::jsi::JSError", referenced from:
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_1::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_2::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_4::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_5::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_8::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      ...
  "facebook::jsi::HostObject::set(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&, facebook::jsi::Value const&)", referenced from:
      vtable for MmkvHostObject in MmkvHostObject.o
  "facebook::jsi::JSError::JSError(facebook::jsi::Runtime&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      facebook::jsi::JSError::JSError(facebook::jsi::Runtime&, char const*) in MmkvHostObject.o
  "facebook::jsi::JSError::~JSError()", referenced from:
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_1::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_2::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_3::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_4::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_5::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      MmkvHostObject::get(facebook::jsi::Runtime&, facebook::jsi::PropNameID const&)::$_8::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const in MmkvHostObject.o
      ...
  "facebook::jsi::HostObject::~HostObject()", referenced from:
      MmkvHostObject::MmkvHostObject(NSString*, NSString*, NSString*) in MmkvHostObject.o
      MmkvHostObject::~MmkvHostObject() in MmkvHostObject.o
  "facebook::jsi::Value::Value(facebook::jsi::Value&&)", referenced from:
      void std::__1::allocator<facebook::jsi::Value>::construct<facebook::jsi::Value, facebook::jsi::Value>(facebook::jsi::Value*, facebook::jsi::Value&&) in JSIUtils.o
  "facebook::jsi::Object::getPropertyAsFunction(facebook::jsi::Runtime&, char const*) const", referenced from:
      createPromiseAsJSIValue(facebook::jsi::Runtime&, std::__1::function<void (facebook::jsi::Runtime&, std::__1::shared_ptr<Promise>)>) in JSIUtils.o
  "facebook::jsi::Value::~Value()", referenced from:
      convertNSDictionaryToJSIObject(facebook::jsi::Runtime&, NSDictionary*) in JSIUtils.o
      convertNSArrayToJSIArray(facebook::jsi::Runtime&, NSArray*) in JSIUtils.o
      convertNSArrayToStdVector(facebook::jsi::Runtime&, NSArray*) in JSIUtils.o
      facebook::jsi::Value::Value<facebook::jsi::String>(facebook::jsi::String&&) in JSIUtils.o
      facebook::jsi::Value::Value<facebook::jsi::Object>(facebook::jsi::Object&&) in JSIUtils.o
      facebook::jsi::Value::Value<facebook::jsi::Array>(facebook::jsi::Array&&) in JSIUtils.o
      convertJSIArrayToNSArray(facebook::jsi::Runtime&, facebook::jsi::Array const&) in JSIUtils.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

![Screenshot (103)](https://user-images.githubusercontent.com/63791031/191602778-68f77e56-ec6f-40e5-90a8-94574c43196a.png)

**Comment by lingol** [comment]
You are complaining that at the wrong repo. This is the official MMKV repo, not the react-native-mmkv repo.
