### ISSUE TITLE
Android  assembleRelease  mmkv errors:文件名、目录名或卷标语法不正确。

### ISSUE THREAD

**Issue by weyko** [Tencent/MMKV#956]

**Comment by lingol** [comment]
Please follow the issue template and provide the information as much as possible.

**Comment by weyko** [comment]
## Note:
Execution failed for task ':mmkv:externalNativeBuildSharedCppRelease'.
> java.io.IOException: 文件名、目录名或卷标语法不正确。

### The language of MMKV

Java



### The version of MMKV

 v1.2.14  




### The platform of MMKV

 Android



### The installation of MMKV

Git clone



### What's the issue?
FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':mmkv:externalNativeBuildDefaultCppRelease'.
> java.io.IOException: 文件名、目录名或卷标语法不正确。

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':mmkv:externalNativeBuildSharedCppRelease'.
> java.io.IOException: 文件名、目录名或卷标语法不正确。

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':mmkv:externalNativeBuildStaticCppRelease'.
> java.io.IOException: 文件名、目录名或卷标语法不正确。

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

**Comment by lingol** [comment]
Still, there's little helpful information. You complain about an **invalid path**, you should at least provide the **full path**, right?
Where exactly did you put your git clone? Does it or its parent folder contain space or non-ASCII char?

**Comment by weyko** [comment]
不知道你说的全路径是什么，git clone在本地E盘代码路径肯定没问题:E:\demo\android\MMKV\Android\MMKV，
编译mmkvdemo，直接跑不起来，提示"java.io.IOException: 文件名、目录名或卷标语法不正确"。也不提示是哪个路径有问题，我要是知道哪个路径有问题，就不问了

**Comment by lingol** [comment]
I don't have any thoughts on such info.
