### ISSUE TITLE
`g_rootDir` will be reset to empty if `[MMKV initialize]` in `+load`

### ISSUE THREAD

**Issue by blastmann** [Tencent/MMKV#959]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

Objective-C

### The version of MMKV

> e.g. v1.2.2  
> Note: For versions older than the latest version, please upgrade before posting any issue.  
> We don't have much time for old version tech support.

v1.2.14

### The platform of MMKV

> e.g. iOS or Android

iOS

### The installation of MMKV

> e.g. Cocoapods, Maven, or Git clone

CocoaPods

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.
> If you have a crash/OOM/ANR on Android, please provide **symbolize stack traces**. https://developer.android.com/ndk/guides/ndk-stack.html

<img width="361" alt="image" src="https://user-images.githubusercontent.com/2032369/192919387-7c5f0b3b-5d6b-4eb2-94a4-16bd49e9ee11.png">

if I initialize MMKV in `+load` methord, the `g_rootDir` will be reset to empty because of the `std::string` constructor trigger after `+load`. After that, all data can't not be saved in MMKV.

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/2032369/192919486-605db4bb-3d97-4424-b563-761f62faf52e.png">

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/2032369/192919612-3452503d-41cc-4b2b-a098-0ad341ce23a4.png">

<img width="1691" alt="image" src="https://user-images.githubusercontent.com/2032369/192919083-40679f45-f9a3-4327-bccf-8aaae3a85b41.png">

I think the `g_rootDir` should double check if the `initialized` happened too early.

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

[mmkv.log](https://github.com/Tencent/MMKV/files/9670056/mmkv.log)

**Comment by lingol** [comment]
And we have made it clear that you should init MMKV in didFinishLaunch.

**Comment by blastmann** [comment]
Sure, I totally understand that is not recommended by Apple and your document is clear. It just happened because of some other SDKs in our App do something like this.

Maybe I should find a way to check this during runtime.

**Comment by blastmann** [comment]
If the `kvPath` is not exist, `isFileValid` will return `true`. Is that correct?

``` cpp
bool MMKV::isFileValid(const string &mmapID, MMKVPath_t *relatePath) {
    MMKVPath_t kvPath = mappedKVPathWithID(mmapID, MMKV_SINGLE_PROCESS, relatePath);
    if (!isFileExist(kvPath)) {
        return true;
    }

    MMKVPath_t crcPath = crcPathWithID(mmapID, MMKV_SINGLE_PROCESS, relatePath);
    if (!isFileExist(crcPath)) {
        return false;
    }

   // ...
}
```

**Comment by lingol** [comment]
Yes. That's by design. As a matter of fact, we have specifically pointed it out in the comment.
https://github.com/Tencent/MMKV/blob/master/Core/MMKV.h#L374
