### ISSUE TITLE
既然已经c++实现了 为什么ios和安卓底层不共用一套c++代码而是两套不同代码呢？

### ISSUE THREAD

**Issue by lixiaoyu0123** [Tencent/MMKV#96]
### The language of MMKV

> e.g. Objective-C, Swift, Java, or Kotlin

### The version of MMKV

> e.g. v1.0.10

### The platform of MMKV

> e.g. iOS or Android

### The installation of MMKV

> e.g. Cocoapods, Carthage, Maven, AAR Package or Git clone

### What's the issue?

> Post the outputs or screenshots for errors.
> 
> Explain what you want by example or code **in English**.

**Comment by lingol** [comment]
After porting to Android, I had considered merging the C++ core into one. And it turns out not too much to shared cross platforms. Mainly because of the Android only features, like inter process access and ashmem MMKV.

It’s better to keep them separated for now.
