### ISSUE TITLE
native crash on android 7.1       11 (SIGSEGV)-1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by joychic** [Tencent/MMKV#960]
### The language of MMKV

> Java, Kotlin

### The version of MMKV

> v1.2.4

### The platform of MMKV
> Android

### The installation of MMKV
>  Maven

### What's the issue?
only happened on android 7.1 

### What's the log of MMKV when that happened?

trace1:

code:"128 (SI_KERNEL)"
stack:" ca636e60 00000001
ca636e64 e5e8f420 [anon:libc_malloc]
ca636e68 ca636ec8 [anon:Mem_0x10000004]
ca636e6c 00000021
ca636e70 00000014
ca636e74 c7cff8a0 [anon:libc_malloc]
ca636e78 00000000
ca636e7c 20174da2 /dev/ashmem/dalvik-main space (deleted)
ca636e80 00000000
ca636e84 00000002
ca636e88 00000000
ca636e8c 00000000
ca636e90 1017280c [anon:Mem_0x10002002]
ca636e94 00000000
ca636e98 ca636ef0 [anon:Mem_0x10000004]
ca636e9c 0c80b909 /data/app/com.shizhuang.duapp-1/lib/arm/libmmkv.so
#00 ca636ea0 00000000
........ ........
#01 ca636ea0 00000000
ca636ea4 20174da2 /dev/ashmem/dalvik-main space (deleted)
ca636ea8 ca636ec0 [anon:Mem_0x10000004]
ca636eac 1017280c [anon:Mem_0x10002002]
ca636eb0 e5e8f420 [anon:libc_malloc]
ca636eb4 ca636ed0 [anon:Mem_0x10000004]
ca636eb8 ca636ef0 [anon:Mem_0x10000004]
ca636ebc 0c80c217 /data/app/com.shizhuang.duapp-1/lib/arm/libmmkv.so
ca636ec0 00000041
ca636ec4 0000003a
ca636ec8 00000021
ca636ecc 00000014
ca636ed0 c85e83c0 [anon:libc_malloc]
ca636ed4 20174da2 /dev/ashmem/dalvik-main space (deleted)
ca636ed8 00000000
ca636edc 00000000
........ ........
#02 ca636ef8 00000000
ca636efc 00000000
ca636f00 00000000
ca636f04 00000000
ca636f08 00000000
ca636f0c 00000000
ca636f10 00000000
ca636f14 00000000
ca636f18 00000000
ca636f1c 00000000
ca636f20 00000000
ca636f24 00000000
ca636f28 00000000
ca636f2c 00000000
ca636f30 00000000
ca636f34 00000000
"
OS version:"7.1.2"
Kernel version:"Linux version 3.18.48 #1 SMP PREEMPT Tue Mar 8 18:11:19 CST 2022 (armv7l)"
API level:"25"
ABI:"arm"
signal:"7 (SIGBUS)"
java stacktrace:"at com.tencent.mmkv.MMKV.getMMKVWithID(Native Method)
at com.tencent.mmkv.MMKV.mmkvWithID(MMKV.java:6)

trace2：

fault addr:"0x0"
code:"1 (SEGV_MAPERR)"
stack:" ca49b9c0 46505845 /dev/ashmem/dalvik-main space 1 (deleted)
ca49b9c4 00000990
ca49b9c8 f284aff4 /system/lib/libhoudini.so
ca49b9cc f25e888d /system/lib/libhoudini.so
ca49b9d0 f3ffd7ee /system/lib/libc.so
ca49b9d4 f29e7ac4 [anon:.bss]
ca49b9d8 80000012
ca49b9dc f25eea02 /system/lib/libhoudini.so
ca49b9e0 12010000 [anon:Mem_0x10001000]
ca49b9e4 00000080
ca49b9e8 f284b020 /system/lib/libhoudini.so
ca49b9ec 10280850 [anon:Mem_0x10002002]
ca49b9f0 f284aff4 /system/lib/libhoudini.so
ca49b9f4 00000000
ca49b9f8 ca49bafc [anon:Mem_0x10000004]
ca49b9fc f25f99dd /system/lib/libhoudini.so
#00 ca49ba00 00000060
........ ........
#01 ca49ba00 00000060
ca49ba04 f284aff4 /system/lib/libhoudini.so
ca49ba08 f284aff4 /system/lib/libhoudini.so
ca49ba0c f25d5854 /system/lib/libhoudini.so
ca49ba10 0e11efd0 [anon:Mem_0x20000000]
ca49ba14 e0a265c8 /data/misc/shared_relro/libwebviewchromium32.relro
ca49ba18 00000007
ca49ba1c f29e7ac4 [anon:.bss]
ca49ba20 f284aff4 /system/lib/libhoudini.so
ca49ba24 00000000
ca49ba28 f2ac84ec [anon:.bss]
ca49ba2c f25f0db3 /system/lib/libhoudini.so
ca49ba30 ca49bafc [anon:Mem_0x10000004]
ca49ba34 00000000
ca49ba38 00000001
ca49ba3c 565576f2 /system/bin/app_process32
"

java stacktrace:"at com.tencent.mmkv.MMKV.getMMKVWithID(Native Method)
at com.tencent.mmkv.MMKV.mmkvWithID(MMKV.java:6)

**Comment by lingol** [comment]
Please provide **symbolized** native call stacks.

**Comment by joychic** [comment]
the trace was uploaded by xcrash，i can't get symbolized native call stacks

**Comment by joychic** [comment]
fault addr:"0x0"

**Comment by joychic** [comment]
memory near:"memory near r0:
bb2b7d10 8648862a 01010df7 0000000b 00000000 *.H.............
bb2b7d20 00000001 00000006 ebddf720 f3b501e4 ........ .......
bb2b7d30 7567696a 5f676e61 6c6f6f62 006e6165 jiguang_boolean.
bb2b7d40 7567696a 5f676e61 6c6f6f62 006e6165 jiguang_boolean.
bb2b7d50 26e5ad9e 00000016 ec5b164f 00002aa2 ...&....O.[..*..
bb2b7d60 26f6e1fc 00000016 ec5b164f 00002b06 ...&....O.[..+..
bb2b7d70 00000001 00000006 ebddf7c0 f3b501e4 ................
bb2b7d80 7567696a 5f676e61 6c6f6f62 006e6165 jiguang_boolean.
bb2b7d90 be1d4700 b852d9f0 00000118 00000000 .G....R.........
bb2b7da0 c89e2be0 bc24a150 baaf1140 a70b24c5 .+..P.$.@....$..
bb2b7db0 f3b4f4f4 be2a10c0 00000000 00000000 ......*.........
bb2b7dc0 d15f2830 d15f2880 bc49cc00 00000000 0(_..(_...I.....
bb2b7dd0 00000014 00000004 be2cda80 00000000 ..........,.....
bb2b7de0 00000010 00000002 be2a40a0 00000000 .........@*.....
bb2b7df0 bb2b7ec0 bb2b7ef0 bb2b7f30 00000000 .~+..~+.0.+.....
bb2b7e00 0000005b c80b5d00 0000007c 00000000 [....]..|.......
memory near r1:
a70b24a4 -------- -------- -------- -------- ................
a70b24b4 -------- -------- -------- -------- ................
a70b24c4 -------- -------- -------- -------- ................
a70b24d4 -------- -------- -------- -------- ................
a70b24e4 -------- -------- -------- -------- ................
a70b24f4 -------- -------- -------- -------- ................
a70b2504 -------- -------- -------- -------- ................
a70b2514 -------- -------- -------- -------- ................
a70b2524 -------- -------- -------- -------- ................
a70b2534 -------- -------- -------- -------- ................
a70b2544 -------- -------- -------- -------- ................
a70b2554 -------- -------- -------- -------- ................
a70b2564 -------- -------- -------- -------- ................
a70b2574 -------- -------- -------- -------- ................
a70b2584 -------- -------- -------- -------- ................
a70b2594 -------- -------- -------- -------- ................
memory near r2:
a70b24a4 -------- -------- -------- -------- ................
a70b24b4 -------- -------- -------- -------- ................
a70b24c4 -------- -------- -------- -------- ................
a70b24d4 -------- -------- -------- -------- ................
a70b24e4 -------- -------- -------- -------- ................
a70b24f4 -------- -------- -------- -------- ................
a70b2504 -------- -------- -------- -------- ................
a70b2514 -------- -------- -------- -------- ................
a70b2524 -------- -------- -------- -------- ................
a70b2534 -------- -------- -------- -------- ................
a70b2544 -------- -------- -------- -------- ................
a70b2554 -------- -------- -------- -------- ................
a70b2564 -------- -------- -------- -------- ................
a70b2574 -------- -------- -------- -------- ................
a70b2584 -------- -------- -------- -------- ................
a70b2594 -------- -------- -------- -------- ................
memory near r3:
002001e4 -------- -------- -------- -------- ................
002001f4 -------- -------- -------- -------- ................
00200204 -------- -------- -------- -------- ................
00200214 -------- -------- -------- -------- ................
00200224 -------- -------- -------- -------- ................
00200234 -------- -------- -------- -------- ................
00200244 -------- -------- -------- -------- ................
00200254 -------- -------- -------- -------- ................
00200264 -------- -------- -------- -------- ................
00200274 -------- -------- -------- -------- ................
00200284 -------- -------- -------- -------- ................
00200294 -------- -------- -------- -------- ................
002002a4 -------- -------- -------- -------- ................
002002b4 -------- -------- -------- -------- ................
002002c4 -------- -------- -------- -------- ................
002002d4 -------- -------- -------- -------- ................
memory near r5:
d2ae00c0 00000000 12d38f00 00000000 07c41a12 ................
d2ae00d0 00000000 00000000 0d2ae008 00000000 ..........*.....
d2ae00e0 00000011 0000000e d2a72f70 00000061 ........p/..a...
d2ae00f0 0000003a d2ae0140 00000061 0000003e :...@...a...>...
d2ae0100 d2ae01a0 d2813aa0 00000000 d2811200 .....:..........
d2ae0110 00000e34 d2a72cb0 6a620000 5a497e80 4....,....bj.~IZ
d2ae0120 d27afd80 e5e99f30 00000000 d2aa6038 ..z.0.......8`..
d2ae0130 d2b031a0 d2a72fe0 d2a72c90 00000001 .1.../...,......
d2ae0140 7461642f 73752f61 302f7265 6d6f632f /data/user/0/com
d2ae0150 6968732e 6175687a 642e676e 70706175 .shizhuang.duapp
d2ae0160 6c69662f 6d2f7365 2f766b6d 65747564 /files/mmkv/dute
d2ae0170 6a5f7473 61756769 0000676e 00000000 st_jiguang......
d2ae0180 00000000 00000000 00000000 00000000 ................
d2ae0190 00000000 00000000 00000000 00000000 ................
d2ae01a0 7461642f 73752f61 302f7265 6d6f632f /data/user/0/com
d2ae01b0 6968732e 6175687a 642e676e 70706175 .shizhuang.duapp
memory near r6:
c0becfb0 0000ca13 a70b24c5 be2a2b60 00000001 .....$..`+*.....
c0becfc0 d2ae00e0 c0becfd0 c0becff0 0c80bcaf ................
c0becfd0 00000011 0000000f bb2b7d30 a70b24c5 ........0}+..$..
c0becfe0 c0beecf8 00000065 1024a80c f2735998 ....e.....$..Ys.
c0becff0 c0bed038 0e07bf00 c0ced5d0 00000001 8...............
c0bed000 c0bed038 1024a80c 00000065 ca07652c 8.....$.e...,e..
c0bed010 c0bed198 f2735998 c0bed198 ca07652c .....Ys.....,e..
c0bed020 00000065 1024a80c c0beecf8 00000000 e.....$.........
c0bed030 00000fc5 be2a2b60 c0bed120 0c125433 ....`+*. ...3T..
c0bed040 00000089 0042c8d3 004127b9 f2735a08 ......B..'A..Zs.
c0bed050 004127b9 0042c8d3 00000089 1024a80c .'A...B.......$.
c0bed060 c0bed198 be2a2b60 00000fc5 00000000 ....`+*.........
c0bed070 00000000 00000000 004127b9 c0bed104 .........'A.....
c0bed080 1024a80c 00000065 0042c8d3 004127b9 ..$.e.....B..'A.
c0bed090 00000089 00000002 be2a3b80 00000002 .........;*.....
c0bed0a0 00000002 be2a3b80 00000039 0041116d .....;*.9...m.A.
memory near r7:
c0becfd0 00000011 0000000f bb2b7d30 a70b24c5 ........0}+..$..
c0becfe0 c0beecf8 00000065 1024a80c f2735998 ....e.....$..Ys.
c0becff0 c0bed038 0e07bf00 c0ced5d0 00000001 8...............
c0bed000 c0bed038 1024a80c 00000065 ca07652c 8.....$.e...,e..
c0bed010 c0bed198 f2735998 c0bed198 ca07652c .....Ys.....,e..
c0bed020 00000065 1024a80c c0beecf8 00000000 e.....$.........
c0bed030 00000fc5 be2a2b60 c0bed120 0c125433 ....`+*. ...3T..
c0bed040 00000089 0042c8d3 004127b9 f2735a08 ......B..'A..Zs.
c0bed050 004127b9 0042c8d3 00000089 1024a80c .'A...B.......$.
c0bed060 c0bed198 be2a2b60 00000fc5 00000000 ....`+*.........
c0bed070 00000000 00000000 004127b9 c0bed104 .........'A.....
c0bed080 1024a80c 00000065 0042c8d3 004127b9 ..$.e.....B..'A.
c0bed090 00000089 00000002 be2a3b80 00000002 .........;*.....
c0bed0a0 00000002 be2a3b80 00000039 0041116d .....;*.9...m.A.
c0bed0b0 004491c2 004109f1 004491b6 00000000 ..D...A...D.....
c0bed0c0 ca07652c 00000065 1024a80c d2c39750 ,e..e.....$.P...
memory near r8:
be2a2b40 00000000 14d6ff58 00000000 0e1302de ....X...........
be2a2b50 00000000 00000000 0be2a2b0 00000000 ................
be2a2b60 1024a80c be2a3b80 c5cb5ba0 00000000 ..$..;*..[......
be2a2b70 00000000 00000000 00000000 00000000 ................
be2a2b80 00000066 00000000 005739c0 005739d0 f........9W..9W.
be2a2b90 00573a36 00000000 0000000b 00000003 6:W.............
be2a2ba0 ea5c97e0 d2c39800 d2c6f67c 0c1476ec ..\.....|....v..
be2a2bb0 00000615 00000000 73397073 49453870 ........sp9sp8EI
be2a2bc0 f35f4770 0000002e f357b006 00000000 pG_.......W.....
be2a2bd0 00000000 00000000 00000000 00000000 ................
be2a2be0 00000000 00000000 f357b015 be2a2bc0 ..........W..+*.
be2a2bf0 00000000 00000000 00000000 00000000 ................
be2a2c00 00000000 1523a940 00000000 00000000 ....@.#.........
be2a2c10 00000000 00000000 0be2a2bc 0000002c ............,...
be2a2c20 f35f4770 0000002e f357b006 00000000 pG_.......W.....
be2a2c30 00000000 00000000 00000000 00000000 ................
memory near r10:
c0beece0 c0beecf8 c0beed28 c0beed20 c0beed18 ....(... .......
c0beecf0 c0beee78 0c10e4c3 00000006 00000000 x...............
c0beed00 be2a2b60 00000000 00000001 00000000 `+*.............
c0beed10 d2c29b00 00000000 0053b32c 00000000 ........,.S.....
c0beed20 ea5c97e0 00000000 00000615 00000000 ..\.............
c0beed30 00000015 00000000 00000003 00000000 ................
c0beed40 c0cee5e0 00000000 1024a80c 00000000 ..........$.....
c0beed50 00000000 00000000 00000000 00000000 ................
c0beed60 00000000 00000000 00000000 00000000 ................
c0beed70 00000000 00000000 00000000 00000000 ................
c0beed80 00000000 be2a2b04 00000000 00000000 .....+*.........
c0beed90 00000000 00000000 00000000 00000000 ................
c0beeda0 00000000 00000000 00000000 be2a2b00 .............+*.
c0beedb0 00000000 00000000 00000000 00000006 ................
c0beedc0 00000000 00000000 00000000 be2a2b00 .............+*.
c0beedd0 00000006 00000000 00000000 00000000 ................
memory near r11:
12020000 00000001 0000000a 00000002 00000001 ................
12020010 12020820 000037e0 1201c000 12024000 ....7.......@..
12020020 ffff037f ffff0061 ffffffff 00000000 ....a...........
12020030 00000023 00000000 ffff002b 00000000 #.......+.......
12020040 83126f00 b91b3ff5 46e48aa2 ffff755d .o...?.....F]u..
12020050 00000000 aaaaab00 00003ffd 6f000000 .........?.....o
12020060 3ff58312 cd896a48 00000000 46e5ffff ...?Hj.........F
12020070 0000755d ffff0000 00000001 00000000 ]u..............
12020080 0000ffff 00000000 3fff8000 00000061 ...........?a...
12020090 0061037f 00000000 00000000 00000000 ..a.............
120200a0 00000000 00000000 00001f80 0002ffff ................
120200b0 00000000 83126f00 00003ff5 00000000 .....o...?......
120200c0 8aa2b91b 755d46e4 0000ffff 00000000 .....F]u........
120200d0 00000000 aaaaab00 00003ffd 00000000 .........?......
120200e0 00000000 83126f00 00003ff5 00000000 .....o...?......
120200f0 cd896a48 00000000 0000ffff 00000000 Hj..............
memory near ip:
0c84cce8 0c826acd 0c825db9 0c519031 0c826a51 .j...]..1.Q.Qj..
0c84ccf8 0c517210 0c516234 0c51b804 0c52244c .rQ.4bQ...Q.L$R.
0c84cd08 0c5161e8 0c825501 0c825d2d 0c82536d .aQ..U..-]..mS..
0c84cd18 0c81d855 0c8253c9 0c825397 0c825575 U....S...S..uU..
0c84cd28 0c519cf0 0c5172c8 0c402e6c 0c517298 ..Q..rQ.l.@..rQ.
0c84cd38 0c57b984 0c518045 0c5548c0 0c517228 ..W.E.Q..HU.(rQ.
0c84cd48 0c5172a0 0c611d18 0c51b2ac 0c81d185 .rQ...a...Q.....
0c84cd58 0c8259d1 0c825ab9 0c825b61 0c51720c .Y...Z..a[...rQ.
0c84cd68 0c519ad0 0c566da4 0c2060a8 0c517258 ..Q..mV..` .XrQ.
0c84cd78 0c824369 0c81d7ed 0c81d98d 0c5172a8 iC...........rQ.
0c84cd88 0c56de00 0c579208 0c51c404 0c56e504 ..V...W...Q...V.
0c84cd98 0c56e320 0c56f038 0c526e4c 0c56e498 .V.8.V.LnR...V.
0c84cda8 0c51fee8 0c56de48 0c51ed4c 0c5692f4 ..Q.H.V.L.Q...V.
0c84cdb8 0c56943c 0c5692b4 0c522248 0c51f690 <.V...V.H"R...Q.
0c84cdc8 0c56e694 0c5194d8 0c56947c 0c0005b0 ..V...Q.|.V.....
0c84cdd8 0c51cccc 0c0005a0 0c56b670 0c56b6ac ..Q.....p.V...V.
memory near sp:
c1b769e0 1200c000 00000080 f284b020 1024a850 ........ ...P.$.
c1b769f0 f284aff4 00000000 c1b76afc f25f99dd .........j...._.
c1b76a00 00000060 f284aff4 f284aff4 f25d5854 `...........TX].
c1b76a10 0e11ec60 c5b00064 00000000 f29e7ac4 `...d........z..
c1b76a20 f284aff4 00000000 f2ac84ec f25f0db3 .............._.
c1b76a30 c1b76afc 00000000 00000001 565576f2 .j...........vUV
c1b76a40 00000000 c0ced440 c1b76ba0 00000001 ....@....k......
c1b76a50 c1b76a54 fffffbbf a70b24c5 00001240 Tj.......$..@...
c1b76a60 00000000 fffbfaff 00000000 c1b76ac8 .............j..
c1b76a70 56559f0c 00000015 5655a0ac 5655758e ..UV......UV.uUV
c1b76a80 00000007 c1b76b0c c1b76b8c 00000000 .....k...k......
c1b76a90 00000000 00000000 00000000 00001240 ............@...
c1b76aa0 00001240 00001240 a70b24c5 00000000 @...@....$......
c1b76ab0 00000000 00000000 00000000 c0beecf8 ................
c1b76ac0 0c80bcbf 56559f0c c1b76af8 56557c8f ......UV.j...|UV
c1b76ad0 00000007 c1b76b0c c1b76b8c 00000000 .....k...k......
memory near lr:
12010c90 00000000 00000000 00000000 00000000 ................
12010ca0 00000000 00000000 00000000 00000000 ................
12010cb0 00000001 00000000 c1b74000 00000000 .........@......
12010cc0 00003000 00000063 0000006b 0000002b .0..c...k...+...
12010cd0 0000002b 0c80bcbf c0beecf8 10248000 +.............$.
12010ce0 c0ced448 0e1a86d0 0c5161e8 0e01f090 H........aQ.....
12010cf0 00008600 0000000c 00000000 0e0654d0 .............T..
12010d00 00000023 00210246 c0ced448 0000002b #...F.!.H...+...
12010d10 12020020 00001200 00000000 00001200 ...............
12010d20 00000000 0000adb8 0080cd00 00000000 ................
12010d30 00000000 00000000 00000000 00000000 ................
12010d40 00000000 00000000 00000000 00000000 ................
12010d50 00000000 00000000 00000000 00000000 ................
12010d60 00000000 00000000 00000000 00000000 ................
12010d70 00000000 00000000 00000000 00000000 ................
12010d80 00000000 00000000 00000000 00000000 ................
"

**Comment by lingol** [comment]
No symbolized stacks no investigation.
