### ISSUE TITLE
1.2.12版本没有32位CPU架构的so文件

### ISSUE THREAD

**Issue by Jerrysun0227** [Tencent/MMKV#961]
1.2.12版本，没有32位CPU架构的so文件，是不再支持了么？

**Comment by lingol** [comment]
Please follow the issue template and provide as much info as possible.

**Comment by lingol** [comment]
Assuming you are talking about Android, last time I checked, it's there. https://repo1.maven.org/maven2/com/tencent/mmkv/1.2.12/
