### ISSUE TITLE
I can't delete the key in MMKV

### ISSUE THREAD

**Issue by yang6wolf** [Tencent/MMKV#966]
I'm used MMKV on iOS platform and found a bug:

After i call removeValueForKey() to remove a key, containsKey() return NO.
But when i restart my app, containsKey always return YES.

It's a problem when i enumerate allkeys.Hope you can fix it~

**Comment by lingol** [comment]
Sounds like impossible. Please provide a reproducible demo project.

**Comment by lingol** [comment]
Closed due to inactive.
