### ISSUE TITLE
MMKV initialize方法中获取了Android Id，导致Android应用无法上架

### ISSUE THREAD

**Issue by rookiegan** [Tencent/MMKV#971]
<img width="400" alt="Snipaste_2022-10-31_11-18-22" src="https://user-images.githubusercontent.com/29536791/198924169-18fe1cca-a987-43e5-97d3-24255818f410.png">

flutter版 mmkv: 1.2.14
用户同意用户协议之前需要MMKV，但MMKV initialize方法中获取了Android Id，导致Android应用无法上架

**Comment by lingol** [comment]
I can't possible image why a simple call in `DeviceInfoPlugin` would make your App unable to submit for review.

**Comment by lingol** [comment]
Let's assume that **IS** the case. If you have to use store some info before your App is allow to access `DeviceInfoPlugin`, you should store them somewhere else(memory/file), after you are allowed, move them into MMKV.

**Comment by rookiegan** [comment]
关于DeviceInfoPlugin的调用导致无法Android应用市场上架的问题，是由于今年Android隐私检测变得很严格，在用户同意隐私协议之前，不得获取手机的某些信息（包括Android Id），这是某应用市场合规检测的报告。
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/29536791/198953162-3d7a56e3-5079-4b1c-af04-4dbe61e76359.png">

**Comment by rookiegan** [comment]
我在项目中依赖我修改过的mmkv，隐私合规检测通过

**Comment by rookiegan** [comment]
如果没有升级flutter3.0的项目，可以这样添加git依赖

`  mmkv:
    git:
      url: git@github.com:rookiegan/MMKV.git
      ref: rookiegan/flutter_2.2.2
      path: flutter
`
