### ISSUE TITLE
适配Android 13了吗？在android 13上没影响吧！

### ISSUE THREAD

**Issue by abbey3** [Tencent/MMKV#974]
适配Android 13了吗？在android 13上没影响吧！

**Comment by lingol** [comment]
Is there any breaking changes in Android 13? As far as I know there isn't any.

**Comment by abbey3** [comment]
> Is there any breaking changes in Android 13? As far as I know there isn't any.

从Android 13的修改来看，mmkv应该是不受影响的。只是想来这里正式确认一下。
