### ISSUE TITLE
prevent delete mmkv storage data when app uninstall

### ISSUE THREAD

**Issue by sbh96** [Tencent/MMKV#975]
how i can prevent users to delete mmkv storage data when uninstalling the application?

**Comment by lingol** [comment]
You can't.

**Comment by sbh96** [comment]
> You can't.
@lingol 
I am a newcomer , how i can store data saved on mmkv in sdcard or another path and then after reinstalling restore it?

**Comment by lingol** [comment]
You can make mmkv store files on sdcard by customizing mmkv's root path on MMKV.initialize(). However, using sdcard is not recommended by Google/Android.
