### ISSUE TITLE
Unclear default MMKV ownership

### ISSUE THREAD

**Issue by SC-One** [Tencent/MMKV#978]
Recently, I wanted to use the library. the default usage:
`auto mmkvPtr = MMKV::defaultMMKV()`
Who is the owner of the pointer(`mmkvPtr`)? Should the API user delete it? or will it be deleted automatically?

**Comment by lingol** [comment]
Nobody owns an mmkv instance, it's shared across your application. 
If you are pretty sure no use after a certain point, you should manually call `MMKV.close()` to close it.
