### ISSUE TITLE
MMKV.mmkvWithID("") Fail to create an MMKV instance [] in JNI

### ISSUE THREAD

**Issue by wuchengithub** [Tencent/MMKV#981]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.
 Fail to create an MMKV instance [] in JNI
### The language of MMKV
 Java

### The version of MMKV
1.2.14

### The platform of MMKV

Android 13    sdk version 32 or 33

### The installation of MMKV

Maven

### What's the issue?

当使用MMKV.mmkvWithID("") 方法，参数为 空字符串时，报出异常Fail to create an MMKV instance [] in JNI，这是正常的吗？

### What's the log of MMKV when that happened?
> Your **detail logs**. As much as possible.
> For how to forward MMKV's log, you can checkout the wiki on each platform.
> An crash issue will be **ignored & closed** in a week **without logs**.

**Comment by lingol** [comment]
Yes.
