### ISSUE TITLE
Get all Instances

### ISSUE THREAD

**Issue by mrousavy** [Tencent/MMKV#982]
Hey!

I couldn't find any information in the docs or in the header file on how one could get a list of all MMKV instances (or a list of all IDs) - is that possible?

Thanks!

**Comment by lingol** [comment]
There's no such interface. Why'd you like to get all instances?

**Comment by mrousavy** [comment]
I want to delete/nuke the entire MMKV storage - basically delete all instances.

**Comment by lingol** [comment]
Do you want to delete live instances or the underlying file storage?
