### ISSUE TITLE
发现一个闪退，在华为手机上居多 应该是鸿蒙系统出现的多

### ISSUE THREAD

**Issue by zhangxiaojin770** [Tencent/MMKV#993]
1
Signal 7(SIGBUS), Code 2(BUS_ADRERR)
2
crash message: path=/data/data/com.xxx.customer/files/mmkv/COMPONENT_LOG_KV_ID, fatal_addr=00000079ee9e255c, map_addr=00000079ee9e0000-00000079ee9f0000, offset=0000000000000000
3
#00 pc 000000000006bae8 /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy+88)
4
#1 pc 000000000002e784 /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
5
#2 pc 0000000000029a60 /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
6
#3 pc 0000000000029610 /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
7
#4 pc 00000000000290e0 /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
8
#5 pc 000000000001eac4 /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
9
#6 pc 00000000000191ec /data/app/com.xxx.customer-JVMY-rYxAWTD_LMpM2oaCg==/lib/arm64/libmmkv.so
10
#7 pc 0000000000150350 /apex/com.android.runtime/lib64/libart.so (art_quick_generic_jni_trampoline+144)
11
#8 pc 0000000000147334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
12
#9 pc 00000000001561b4 /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252)
13
#10 pc 00000000002fd900 /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE+384)
14
#11 pc 00000000002f8bd0 /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+912)
15
#12 pc 00000000005cd910 /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+400)
16
#13 pc 0000000000141914 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
17
#14 pc 00000000005cb874 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1432)
18
#15 pc 0000000000141814 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20)
19
#16 pc 00000000005cb874 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1432)
20
#17 pc 0000000000141814 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20)
21
#18 pc 00000000005cdc10 /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
22
#19 pc 0000000000141914 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
23
#20 pc 00000000005ce41c /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1136)
24
#21 pc 0000000000141994 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
25
#22 pc 00000000002ce22c /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.1772238600391939451+320)
26
#23 pc 00000000005bc0a4 /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1012)
27
#24 pc 0000000000150468 /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88)
28
#25 pc 00000000003d8d08 /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+984)
29
#26 pc 00000000003d5880 /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
30
#27 pc 0000000000217fc8 /system/framework/arm64/boot.oat (java.lang.Thread.run+72)
31
#28 pc 0000000000147334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
32
#29 pc 00000000001561b4 /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+252)
33
#30 pc 00000000004d8834 /apex/com.android.runtime/lib64/libart.so (_ZN3art12_GLOBAL__N_118InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS0_8ArgArrayEPNS_6JValueEPKc+104)
34
#31 pc 00000000004d98c8 /apex/com.android.runtime/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithJValuesERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDPK6jvalue+416)
35
#32 pc 000000000051caa0 /apex/com.android.runtime/lib64/libart.so (_ZN3art6Thread14CreateCallbackEPv+1232)
36
#33 pc 00000000000cf7c0 /apex/com.android.runtime/lib64/bionic/libc.so (_ZL15__pthread_startPv+36)
37
#34 pc 00000000000721a8 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

**Comment by zhangxiaojin770** [comment]
有什么解决办法吗

**Comment by lingol** [comment]
Please follow the issue template and provide as much info as possible. Crash without **symbolized** call stacks will be ignored.
