### ISSUE TITLE
android 平台；版本1.2.9；MMKV.decodeBool 耗时过长引起ANR

### ISSUE THREAD

**Issue by undefined-hyy** [Tencent/MMKV#994]
### The language of MMKV
> Java, or Kotlin
### The version of MMKV
> v1.2.9
### The platform of MMKV
> Android
### The installation of MMKV
> Maven
### What's the issue?
> MMKV.decodeBool 耗时过长引起ANR
### What's the log of MMKV when that happened?
> 12-25 22:16:27.806 10121 24398 28074 W MIUIScout App: Enter APP_SCOUT_HANG state
12-25 22:16:27.806 10121 24398 28074 W MIUIScout App:  (**Current message: duration=5003ms** seq=46596 late=1ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
12-25 22:16:30.137 10121 24398 31284 W MIUIScout App: Event:APP_SCOUT_HANG Thread:main backtrace:
12-25 22:16:30.137 10121 24398 31284 W MIUIScout App:     at com.tencent.mmkv.MMKV.decodeBool(Native Method)
12-25 22:16:30.137 10121 24398 31284 W MIUIScout App:     at com.tencent.mmkv.MMKV.getBoolean(MMKV.java:1)
...
12-25 22:16:30.137 10121 24398 31284 W MIUIScout App:     at androidx.recyclerview.widget.RecyclerView$g.onBindViewHolder(RecyclerView.java:1)
12-25 22:16:30.137 10121 24398 31284 W MIUIScout App:     at androidx.recyclerview.widget.RecyclerView$g.bindViewHolder(RecyclerView.java:6)
12-25 22:16:30.137 10121 24398 31284 W MIUIScout App:     at androidx.recyclerview.widget.RecyclerView$t.a(RecyclerView.java:8)
### 说明
在接入mmkv替换sp，一方面也是为了降低sp引入的anr问题；但在实际接入mmkv后，通过业务的监控平台看，实际MMKV.decodeXXX、MMKV.sync等方法的耗时导致anr也一直是top级别。

**Comment by lingol** [comment]
Remove all `sync()` / `commit()` / `apply()` calls. You don't need them.
