### ISSUE TITLE
mmkv armeabi so path

### ISSUE THREAD

**Issue by mikelhm** [Tencent/MMKV#996]
## Note:
After compile by http://c.ss/V4Bx4G , where is the path of armeabi?
I hava follows the step in by http://c.ss/V4Bx4G. And build successful, but i can not find the  armeabi so, Where is the file path?

### The version of MMKV
>1.2.14

### The platform of MMKV

>  Android

### What's the issue?
After compile by http://c.ss/V4Bx4G , where is the path of armeabi?

**Comment by lingol** [comment]
I can't open http://c.ss/V4Bx4G.

**Comment by mikelhm** [comment]
> 



> I can't open http://c.ss/V4Bx4G.

https://github.com/Tencent/MMKV/wiki/android_setup_cn   this one.
i want to compile armeabi so. I follow the steps in this link. but i can't find the armeabi so file.

**Comment by lingol** [comment]
I don't know either. Maybe you should check your build logs.

**Comment by mikelhm** [comment]
> 

could you offer armeabi so file in github. For there are also other ones want it, there are some apps whose cpu is armeabi.

**Comment by lingol** [comment]
No. We remove armeabi support for a good reason.

**Comment by lingol** [comment]
And we recommend you to drop the support as well.
