### ISSUE TITLE
JNI ERROR (app bug): attempt to use stale Local 0x11 (should be 0x15)

### ISSUE THREAD

**Issue by orackxudan** [Tencent/MMKV#999]
## Note:
An crash issue will be **ignored & closed** in a week **without logs**.

### The language of MMKV
Java

### The version of MMKV
1.2.14

### The platform of MMKV
Android

### The installation of MMKV
Maven

### What's the issue?
JNI ERROR (app bug): attempt to use stale Local 0x11 (should be 0x15)
only child process

### What's the log of MMKV when that happened?

pid: 31020, tid: 31171, name: LaunchPoolT4  >>> om.sd.aa:push <<<
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'JNI ERROR (app bug): attempt to use stale Local 0x11 (should be 0x15)'
    r0  00000000  r1  000079c3  r2  00000006  r3  b9670ed8
    r4  b9670eec  r5  b9670ed0  r6  0000792c  r7  0000016b
    r8  b9670ee8  r9  b9670ed8  sl  b9670f08  fp  b9670ef8
    ip  000079c3  sp  b9670ea8  lr  eac8a343  pc  eac8a356  cpsr  000e0030

backtrace:
    #00 pc 0005f356  /apex/com.android.runtime/lib/bionic/libc.so 
           abort+165
    #01 pc 00376499  /apex/com.android.runtime/lib/libart.so 
           art::Runtime::Abort(char const*)+1676
    #02 pc 0000855f  /system/lib/libbase.so 
           android::base::LogMessage::~LogMessage()+406
    #03 pc 001de58b  /apex/com.android.runtime/lib/libart.so 
           art::IndirectReferenceTable::AbortIfNoCheckJNI(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+166
    #04 pc 0028cafb  /apex/com.android.runtime/lib/libart.so 
           art::IndirectReferenceTable::GetChecked(void*) const+278
    #05 pc 003ab3d9  /apex/com.android.runtime/lib/libart.so 
           art::Thread::DecodeJObject(_jobject*) const+52
    #06 pc 0041abc7  /apex/com.android.runtime/lib/libart.so 
           artQuickResolutionTrampoline+2334
    #07 pc 000dc4a1  /apex/com.android.runtime/lib/libart.so 
           art_quick_resolution_trampoline+32
    #08 pc 01479ecb  /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex 
           com.tencent.mmkv.MMKV.mmkvWithID+90
    #09 pc 0112f93f  /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex 
           com.ww.dd.local.d$a.c+934
    #10 pc 0112fd4d  /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex 
           com.ww.dd.local.d$a.a+404
    #11 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so 
           art_quick_invoke_stub_internal+68
    #12 pc 0042e457  /apex/com.android.runtime/lib/libart.so 
           art_quick_invoke_stub+250
    #13 pc 000dffb7  /apex/com.android.runtime/lib/libart.so 
           art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+174
    #14 pc 00210a09  /apex/com.android.runtime/lib/libart.so 
           art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+280
    #15 pc 0020c34b  /apex/com.android.runtime/lib/libart.so 
           bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+774
    #16 pc 00428beb  /apex/com.android.runtime/lib/libart.so 
           MterpInvokeVirtualQuick+518
    #17 pc 000d6594  /apex/com.android.runtime/lib/libart.so 
           mterp_op_invoke_virtual_quick+20
    #18 pc 001ec285  /apex/com.android.runtime/lib/libart.so 
           art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) [clone .llvm.4051875684531665263]+192
    #19 pc 001f0a69  /apex/com.android.runtime/lib/libart.so 
           art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+124
    #20 pc 00417fc9  /apex/com.android.runtime/lib/libart.so 
           artQuickToInterpreterBridge+808
    #21 pc 000dc5a1  /apex/com.android.runtime/lib/libart.so 
           art_quick_to_interpreter_bridge+32
    #22 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so 
           art_quick_invoke_stub_internal+68
    #23 pc 0042e56b  /apex/com.android.runtime/lib/libart.so 
           art_quick_invoke_static_stub+246
    #24 pc 000dffcb  /apex/com.android.runtime/lib/libart.so 
           art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+194
    #25 pc 00100827  /apex/com.android.runtime/lib/libart.so 
           art::ClassLinker::InitializeClass(art::Thread*, art::Handle<art::mirror::Class>, bool, bool)+1790
    #26 pc 000f0d7f  /apex/com.android.runtime/lib/libart.so 
           art::ClassLinker::EnsureInitialized(art::Thread*, art::Handle<art::mirror::Class>, bool, bool)+58
    #27 pc 0040e253  /apex/com.android.runtime/lib/libart.so 
           artInitializeStaticStorageFromCode+58
    #28 pc 000d7f4f  /apex/com.android.runtime/lib/libart.so 
           art_quick_initialize_static_storage+30
    #29 pc 014baa2b  /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex 
           com.sd.aa.entrance.impl.EntranceImpl.teenModelOpened+282
    #30 pc 010340db  /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex 
           com.ww.dd.app.launch.freemobiledata.b.b+226
    #31 pc 010347f7  /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex 
           com.ww.dd.app.launch.freemobiledata.b.b+1150
    #32 pc 01033fc9  /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex 
           com.ww.dd.app.launch.freemobiledata.b$e.run+224
    #33 pc 0103909d  /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex 
           com.ww.dd.app.launch.g$3.run+164
    #34 pc 0085281f  /system/framework/arm/boot.oat 
           java.util.concurrent.ThreadPoolExecutor.runWorker+1014
    #35 pc 0084f65f  /system/framework/arm/boot.oat 
           java.util.concurrent.ThreadPoolExecutor$Worker.run+54
    #36 pc 00433681  /system/framework/arm/boot.oat 
           java.lang.Thread.run+64
    #37 pc 013d4217  /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex 
           com.ss.android.ugc.bytex.pthread.base.convergence.hook.ThreadProxy$start$1.invoke+174
    #38 pc 013d40f5  /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex 
           com.ss.android.ugc.bytex.pthread.base.convergence.hook.ThreadProxy$start$1.invoke+68
    #39 pc 013d382d  /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex 
           com.ss.android.ugc.bytex.pthread.base.convergence.helper.ThreadWorker.run+372
    #40 pc 0085281f  /system/framework/arm/boot.oat 
           java.util.concurrent.ThreadPoolExecutor.runWorker+1014
    #41 pc 0084f65f  /system/framework/arm/boot.oat 
           java.util.concurrent.ThreadPoolExecutor$Worker.run+54
    #42 pc 00433681  /system/framework/arm/boot.oat 
           java.lang.Thread.run+64
    #43 pc 000d7bc5  /apex/com.android.runtime/lib/libart.so 
           art_quick_invoke_stub_internal+68
    #44 pc 0042e457  /apex/com.android.runtime/lib/libart.so 
           art_quick_invoke_stub+250
    #45 pc 000dffb7  /apex/com.android.runtime/lib/libart.so 
           art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+174
    #46 pc 003701f7  /apex/com.android.runtime/lib/libart.so 
           art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54
    #47 pc 00370ee9  /apex/com.android.runtime/lib/libart.so 
           art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+304
    #48 pc 003a19a7  /apex/com.android.runtime/lib/libart.so 
           art::Thread::CreateCallback(void*)+978
    #49 pc 000a6293  /apex/com.android.runtime/lib/bionic/libc.so 
           __pthread_start(void*)+20
    #50 pc 00060803  /apex/com.android.runtime/lib/bionic/libc.so 
           __start_thread+30

build id:
    /apex/com.android.runtime/lib/bionic/libc.so (BuildId: af31ec96b35fedca378e07659b30896c)
    /apex/com.android.runtime/lib/libart.so (BuildId: 04997b3570c346f812675714d1681c80)
    /system/lib/libbase.so (BuildId: a28585ee446ea17e3e6fcf9c907fff2a)
    /data/app/com.sd.aa-butcmy-ocRQfziXpkMkNrw==/oat/arm/base.odex (BuildId: 07a7aa473382e348dc34113cd317787d)
    /system/framework/arm/boot.oat (BuildId: f42dc9b49d948b0cb8e36a118523ec9c1e041148)

**Comment by lingol** [comment]
It's crashed inside system library, nothing we can do about it.
>art::Thread::DecodeJObject(_jobject*) const+52
